### ISSUE TITLE
airflow workers and scheduler memory leak

### ISSUE THREAD

**Issue by anu251989** [apache/airflow#28740] opened 2023-01-05 10:20 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

In airflow 2.2.5, The worker and scheduler memory gradually increasing day by day when no tasks are running. The log rotation also enabled. We have enabled the celery inspect command with liveness check probe for workers to resolve the communication issue between worker and airflow redis. 

 Liveness:  exec [sh -c CONNECTION_CHECK_MAX_COUNT=0 exec /entrypoint python -m celery --app airflow.executors.celery_executor.app inspect ping -d celery@${HOSTNAME}] delay=30s timeout=60s period=30s #success=1 #failure=5

I have disabled the liveness check and didn't observe the memory leak. how to enable the liveness checks to resolve disconnection between redis and workers? why redis and workers communication not resuming automatically. 

I observed memory leak issues there for scheduler pod also. but didn't find the root cause. 

![image](https://user-images.githubusercontent.com/106726701/210755823-d5f848af-e553-49b7-af4d-a8de405d6174.png)

![image](https://user-images.githubusercontent.com/106726701/210755856-1dc3722e-7fc8-474f-8412-b00caaf57701.png)

### What you think should happen instead

why celery inspect command causing the memory leak in worker. 

The redis and worker communication should resume automatically without any intervention. 

The scheduler memory leak should not happen. The scheduler utilization go up  while processing tasks and it has to comedown once done.

### How to reproduce

Install airflow 2.2.5 with Python 3.8 to replicate the issues. 

for workers memory leak: enable the below command and observe the memory utilization.

 Liveness:  exec [sh -c CONNECTION_CHECK_MAX_COUNT=0 exec /entrypoint python -m celery --app airflow.executors.celery_executor.app inspect ping -d celery@${HOSTNAME}] delay=30s timeout=60s period=30s #success=1 #failure=5

The scheduler no need of any changes. The memory gradually increasing day by day.

### Operating System

PRETTY_NAME="Debian GNU/Linux 10 (buster)" NAME="Debian GNU/Linux" VERSION_ID="10" VERSION="10 (buster)" VERSION_CODENAME=buster ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"

### Versions of Apache Airflow Providers

airflow 2.2.5 

![image](https://user-images.githubusercontent.com/106726701/210756991-3bd880a7-1868-42dd-a84f-ada4f909f613.png)

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

NA

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2023-01-05 11:04
Oh. That's an interesting observation about memory leak. 

Which version of Kubernetes are you using @anu251989. 

I strongly beleive that if the liveness check is the cause, then it's the question of a memory leak in K8S, not in Airflow.

Maybe even there is a good candidate - i.e. this error https://github.com/kubernetes-csi/livenessprobe/issues/91 

And I think the best way to fix it is to upgrade K8S.

I think this might also explain some of the other memory leak issues that we found hard to debug. #24694 #27589 #28595.

Can you please upgrade and see if it resolves your problem?

**Comment by anu251989** [comment] 2023-01-06 11:47
Thank for your reply @potiuk. 

The kubernetes version is EKS 1.21.

We will upgrade EKS version to 1.22 or 1.23 and get back to you on this.

Regarding scheduler and Trigger pod memory leak.  we yet to find the root cause.

**Comment by potiuk** [comment] 2023-01-06 12:07
> Thank for your reply @potiuk.
> 
> We will upgrade EKS version to 1.22 or 1.23 and get back to you on this.
> 

In the meantime I found out that it might also be that you need to upgrade airflow (and effectively Celery) - because this is a know bug in the celery liveness check - not in Airflow, not in Kubernetes. Here is a relevant issue https://github.com/apache/airflow/issues/21026 and https://github.com/apache/airflow/pull/19703 - If you have Celery before 5.2.3 you might experience it too. So you might also check your celery version.

> Regarding scheduler and Trigger pod memory leak. we yet to find the root cause.

I think this one might not be memory leak - but increased cache memory usage because you do not rotate logs. 

This is not a memory leak per-se - you might simply just observe wrong memory observed (And actually that might also be a reason for the first "memory leak" in celery as well - but I would rather try k8s upgrade first anyway).

You have not explained which memory you observe - but what you might see is the usual behaviour of Linux kernel, where it keeps memory-mapped files when they are saved and if the files are not rotated/moved, the cache is never freed. This is standard behaviour of Linux (generally linux in such case will fill all available memory with cache to speed up file access). If this is the case, then it is generally harmless (the memory is freed immediately when needed by something else and you will never get "out-of-memory" errors because of it), however we implemented a way how to hint the kernel not to do it when we are writing logs and it's been released in Airflow 2.4.3 https://github.com/apache/airflow/pull/27223 so upgrading to Airflow 2.4.3+ will solve it, if this is the case.

In general - I'd STRONGLY recommend you to migrate to latest released Airflow (2.5.0 currently). There are mutliple hundreds of issues fixed and you will save yourself and people who want to help you to chase the problems that have long been handled. 

I assume the problem is fixed by combination of those upgrades - closing untill the users upgrade to those versions and report back in case the problem is not fixed after applying them.

**Closed as completed by potiuk** 2023-01-06 12:07 UTC
Labels: kind:bug, area:core

**Comment by anu251989** [comment] 2023-01-08 02:22
@potiuk , We upgraded to EKS cluster 1.23 but still issue persist memory leak with respect to Workers liveness probe and scheduler pods as well.

**Comment by potiuk** [comment] 2023-01-08 10:36
> @potiuk , We upgraded to EKS cluster 1.23 but still issue persist memory leak with respect to Workers liveness probe and scheduler pods as well.

Which memory is it ? Did you take a look at https://github.com/apache/airflow/pull/27223 and related issue: https://github.com/apache/airflow/issues/27065 and https://github.com/apache/airflow/issues/14924 ?

Questions you should find answers to:

* Is it a working set memory growing or cache: https://github.com/apache/airflow/issues/14924#issuecomment-914153622

* Does ite eventually cause your containers to crash with OOM (Out of Memory) or does the memory clears itself out when needed?

* Does it go away when you (after execing in to the containers that you observe memory growth in) go away when you clear the cache manualy https://github.com/apache/airflow/issues/14924#issuecomment-914143098

* Does it go away when you clear the cache for the whole node that your Airflow pods are running on.

* Does it go away when you rotate/compress/remove log files that Airflow produces.

* If it all shows that this is the "cache" issue (which is BTW not an issue, it's normal and you just observe wrong memory) - then upgrading to 2.4.3 should remove at least some of that cache being created in the first place

Getting answers to those question should help you to understanda if what you have is a cache issue or something else.

* If it is something else, then  likely you need to find out which process is leaking memory. It might be airflow, but in case you have some monitoring or logging agents for example.

Those are the experiments and checks you should do next. I also recommend reading more about memory issues in the threads I linked to, they contain a wealth of information and links that can help you to pin-point not only Airflow-related but also other, similar issues.

**Comment by rinzool** [comment] 2024-08-28 07:47
Hi, 
If it may help someone, I faced the same issue, my scheduler memory increased from 600MB to 1.3GB in 4 days (the `container_memory_working_set_bytes` precisely).
Using Airflow 2.10.0 and chart 1.15.0.
![image](https://github.com/user-attachments/assets/9e7f6705-ad0d-42cf-ab02-20f93cea6b0d)

I tried a lot of things (exploring process using `ps` and `htop`), cleaning logs manually, etc. nothing worked.

After re-re-re-reading the last message from @potiuk I focused on:
> Does ite eventually cause your containers to crash with OOM (Out of Memory) or does the memory clears itself out when needed?

So I added a memory limit to see if the pod goes OOM or not
```yaml
scheduler:
  resources:
    requests:
      memory: 500Mi
    limits:
      memory: 1Gi
```
Here is the result: 
![image](https://github.com/user-attachments/assets/919e8cf6-21d0-4c6e-b064-cdaf206a79a4)

No OOM, the pod clears itself when it is too close to the limit.

Hope this message can help!

**Comment by danielstefanrt** [comment] 2024-11-05 07:38
Hi,

I'm facing the same issue on version 2.10.2. The scheduler memory keeps growing with ~1GB each day. 
I've tried to set the limits and I saw in Kubernetes that the pod ran out of memory (status is OOMKilled and I can see that it restarted).

**Comment by potiuk** [comment] 2024-11-05 08:26
> Hi,
> 
> I'm facing the same issue on version 2.10.2. The scheduler memory keeps growing with ~1GB each day. I've tried to set the limits and I saw in Kubernetes that the pod ran out of memory (status is OOMKilled and I can see that it restarted).

Can you please use memray (see instructions https://github.com/bloomberg/memray) to monitor and check what memory is leaking and open a new issue explaining your configuration and investigations around what you looked at and possible causes you might guess by analysing your usage. You have clearly a DIFFERENT issue than the one above - where we are talking about file system memory that grows naturally and clears itself. 

Just commenting that you have similar (i.e. related to memory) issue on a  closed issue, does not add too much value and does not help anyone to help you. I understand you are frustrated with your problem, but the best course of action is to gather enough evidences and explain your circumstances in way that is detailed enough for someone to be actually do anything about it (of course if there is enough evidences - this is a free forum where people try to help others, when they can, so helping them to help you is a good idea).

**Comment by danielstefanrt** [comment] 2024-11-05 08:32
Hi, @potiuk . Thanks for your quick reply. Sure, I'll do as you suggested and create a new issue with my findings. There is no frustration here :) I just saw that the outcome was the same and I did not want to open a new issue when there was a similar one.

**Comment by potiuk** [comment] 2024-11-05 10:42
>  I did not want to open a new issue when there was a similar one.

Except some obvious cases, It's extremely difficult even for maintainers, not mentionign the contributors to assess if an issue is the same or different - even if they look similar. 

It's ALWASY better to open new one (and mark it as `Related: #OlD_ISSUE`), especially when original issue is closed. when it follows the template and answer our questions it might contain valuable information and in more cases than not, it might be something completely different. 

Worst case we mark it as duplicate and close if issue is solved.

**Comment by zsdyx** [comment] 2024-11-29 08:22
> Hi, @potiuk . Thanks for your quick reply. Sure, I'll do as you suggested and create a new issue with my findings. There is no frustration here :) I just saw that the outcome was the same and I did not want to open a new issue when there was a similar one.
Hi @danielstefanrt  I have the same phenomenon as you, you have created new issues?

**Comment by pre-sumitbhardwaj** [comment] 2024-12-03 16:23
Hi team, I facing same issue where my worker memory keep on increasing 
Airflow version: 2.9.3

**Comment by danielstefanrt** [comment] 2024-12-04 06:30
@zsdyx No, I haven't created a new issue.  The problem is still present in our cluster, but we did not have too much time for a deeper investigation

**Comment by zsdyx** [comment] 2024-12-06 09:54
Hi @rinzool, Do you know why this is, is it because of the behavior of the linux kernel, the first time you encounter this problem, why is it GC after setting limit.

**Comment by rinzool** [comment] 2024-12-06 09:59
> Hi @rinzool, Do you know why this is, is it because of the behavior of the linux kernel, the first time you encounter this problem, why is it GC after setting limit.

Honestly no. My supposition is that the scheduler has an internal process to release some memory when it reaches a limit (like 90% of available memory for example), and by defining a memory limit to the pod it helps airflow to trigger this process. But honestly I don't know if that's the real reason. All I know is that it fixes my problem 🤷

**Comment by zsdyx** [comment] 2024-12-06 10:05
> > Hi @rinzool, Do you know why this is, is it because of the behavior of the linux kernel, the first time you encounter this problem, why is it GC after setting limit.
> 
> Honestly no. My supposition is that the scheduler has an internal process to release some memory when it reaches a limit (like 90% of available memory for example), and by defining a memory limit to the pod it helps airflow to trigger this process. But honestly I don't know if that's the real reason. All I know is that it fixed my problem 🤷

We use the same version, I find this problem in both scheduler and trigger, but when I look at airflow code, there is no gc job, which is strange.

**Comment by jplanckeel-ep** [comment] 2025-01-28 14:23
🙉 @rinzool  Have i the same problem, we use Airflow with OpenMetadata and airflow grow grow grow..

**Comment by jeromeharr** [comment] 2026-06-14 21:37
> 🙉 [@rinzool](https://github.com/rinzool) Have i the same problem, we use Airflow with OpenMetadata and airflow grow grow grow..

Hey, i experience the same memory issue in openmetadata, the shceulder (maybe triggerer too) memory linearly increases until it reaches the pod limit memory and it stablizes a tad below it. 

Did you find any solution?
