### ISSUE TITLE
on_success_callback isn't run when marking a task instance as successful when it's not in a running state

### ISSUE THREAD

**Issue by lukeknxt** [apache/airflow#22970] opened 2022-04-13 07:57 UTC
### Apache Airflow version

2.2.3

### What happened

When a task instance is in a failed state (or any other non running state), and then it's marked as successful through the UI, the `on_success_callback` set on the task instance is not run.

### What you think should happen instead

The `on_success_callback` should run when marking a task instance successful from the UI regardless of its state.

### How to reproduce

1. Create a DAG
1. Add a task with an `on_success_callback` that throws an exception (so it fails)
1. Run the DAG in the UI
1. Wait for the task instance to fail for that DAG run
1. Mark the task instance successful in the UI for that DAG run

### Operating System

Debian 10 (Buster)

### Versions of Apache Airflow Providers

`apache-airflow-providers-databricks==2.5.0`

This is the main provider we care about at the moment.

### Deployment

Other Docker-based deployment

### Anything else

From my observations, it seems as though the `on_success_callback` _is_ run when a task instance is in a `RUNNING` state, and then is marked successful from the UI, but not when the task instance is in any other state. From some brief digging this behaviour appears to be related to [the `heartbeat_callback`](https://github.com/apache/airflow/blob/e09b4f144d1edefad50a58ebef56bd40df4eb39c/airflow/jobs/local_task_job.py#L236) based on [this old bug report](https://issues.apache.org/jira/browse/AIRFLOW-6821) but I can't see any equivalent logic for when the task _isn't_ running.

For context - we are using this behaviour to track issues occurring in Airflow with a 3rd party tool where marking a task instance as successful is effectively an "ignore", and our `on_success_callback` lets us register that ignore to another tool that tracks alerting.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2022-04-13 08:30
If you try to change the status of a "non running" task in the UI - it will just change the state -> change the DB record.
This is expected.

**Comment by lukeknxt** [comment] 2022-04-13 09:19
Just seems inconsistent to me to have different behaviour when marking
successful when it’s running versus not running.

Is there any alternative to hook into a “mark successful” event?

**Comment by tirkarthi** [comment] 2022-04-13 09:51
This seems to be a duplicate of https://github.com/apache/airflow/issues/18113

**Comment by lukeknxt** [comment] 2022-04-14 03:38
@tirkarthi ,

Yep that looks like the same issue.

Based on what @andrewgodwin said in #18113, it looks like this type of thing could be done in the future via running callback-only workloads on executors, but right now it doesn't seem like a change that'd be easy to add.

**Closed as completed** 2022-04-18 08:35 UTC
Labels: kind:bug, duplicate, area:core
