### ISSUE TITLE
UI Bug: Max active runs, task, and concurrency show up as datetime in Grid view (dag details)

### ISSUE THREAD

**Issue by ketozhang** [apache/airflow#36233] opened 2023-12-14 21:52 UTC
### Apache Airflow version

2.7.3

### What happened?

![image](https://github.com/apache/airflow/assets/13506487/d2a9029a-1a18-4891-b224-f818a8740781)

### How to reproduce

Go to main page of a DAG, see right pane for dag details.

### Operating System

Amazon Linux 2 (docker apache/airflow:slim-2.7.3-python3.11)

### Deployment

Community Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment] 2023-12-15 10:50
- Duplicate of: https://github.com/apache/airflow/issues/35500
- Fixed in: https://github.com/apache/airflow/pull/35538, would be released as part of Airflow 2.8

**Closed as completed by Taragolis** 2023-12-15 10:50 UTC
Labels: kind:bug, duplicate, area:core, needs-triage
