### ISSUE TITLE
Add new DAG Run types for: `TriggerDagRunOperator` and `Rest API`

### ISSUE THREAD

**Issue by pedro-cf** [apache/airflow#40989] opened 2024-07-24 08:41 UTC
### Description

Currently DAG Runs triggered via a [TriggerDagRunOperator](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/trigger_dagrun/index.html#airflow.operators.trigger_dagrun.TriggerDagRunOperator) and the [Airflow REST API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html) are categorized with run type "Manual":
![image](https://github.com/user-attachments/assets/06290124-98d9-439d-aef2-8e7cffae3431)

Would it be possible to add 2 new types: `TriggerDagRunOperator`  `Rest API` ?

### Use case/motivation

Add the ability to distinguish different types of DAG Runs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2024-07-25 16:49
Duplicate of https://github.com/apache/airflow/issues/31557

**Closed as not planned by eladkal** 2024-07-25 16:49 UTC
Labels: area:Scheduler, kind:feature, needs-triage
