### ISSUE TITLE
External DAG processor not working

### ISSUE THREAD

**Issue by allebacco** [apache/airflow#23447] opened 2022-05-03 13:36 UTC
### Apache Airflow version

2.3.0 (latest released)

### What happened

Running a standalone Dag Processor instance with `airflow dag-processor` throws the following exception:
```
Standalone DagProcessor is not supported when using sqlite.
```

### What you think should happen instead

The `airflow dag-processor` should start without an exception in case of Postgres database

### How to reproduce

The error is in the following line: https://github.com/apache/airflow/blob/6f146e721c81e9304bf7c0af66fc3d203d902dab/airflow/cli/commands/dag_processor_command.py#L53

It should be
```python
sql_conn: str = conf.get('database', 'sql_alchemy_conn').lower() 
```
due to the change in the configuration file done in https://github.com/apache/airflow/pull/22284

### Operating System

Ubuntu 20.04

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2022-05-03 18:53
Duplicate of https://github.com/apache/airflow/issues/23408

**Comment by allebacco** [comment] 2022-05-03 19:02
@eladkal are you sure that thias issue is a duplicate? In this case I am not using `AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD`.

The line mentioned in the description of the issue is reading the sql alchemy connection string from the `core` section instead of the `database` one. Maybe I am missing some detail of the configuration mechanism.

**Comment by potiuk** [comment] 2022-05-08 22:16
@mhenc  - can you take a look please?

**Comment by tirkarthi** [comment] 2022-05-09 11:04
I guess this can be closed now with https://github.com/apache/airflow/pull/23575 merged .

**Closed as completed** 2022-05-09 12:07 UTC
Labels: duplicate
