### ISSUE TITLE
Circular package imports in Airflow 2.0

### ISSUE THREAD

**Issue by thundergolfer** [apache/airflow#14128] opened 2021-02-08 00:51 UTC
**Apache Airflow version**: `2.0.0`

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**: 

- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): OSX
- **Kernel** (e.g. `uname -a`): `Darwin Jonathons-MacBook-Pro-16-inch-2019 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64`
- **Install tools**: Bazel ?
- **Others**:

**What happened**:

A user of [bazelbuild/rules_python](https://github.com/bazelbuild/rules_python) had trouble installing `apache-airflow==2.0.0` with the Bazel build system reporting a "cycle in dependency graph" error.

Investigating the issue, I found the following in `setup.py` which does not seem accurate. 

```
# Those providers are pre-installed always when airflow is installed.
# Those providers do not have dependency on airflow2.0 because that would lead to circular dependencies.
# This is not a problem for PIP but some tools (pipdeptree) show those as a warning.
PREINSTALLED_PROVIDERS = [
    'ftp',
    'http',
    'imap',
    'sqlite',
] 
```

Specifically this claim:

> Those providers do not have dependency on airflow2.0 

I appears they **do** have this dependency, and it does lead to circular dependencies:

```
.-> @py_deps//pypi__apache_airflow:pypi__apache_airflow
|   @py_deps//pypi__apache_airflow_providers_sqlite:pypi__apache_airflow_providers_sqlite
`-- @py_deps//pypi__apache_airflow:pypi__apache_airflow
```

In that same Github issue a colleague provides further investigation of the Airflow 2.0 wheel: https://github.com/bazelbuild/rules_python/issues/411#issuecomment-772306099

**What you expected to happen**:

`apache-airflow==2.0.0` would not have circular deps and thus could be importable in build systems that do not allow circular dependencies (eg. Bazel)

**How to reproduce it**:

Issue https://github.com/bazelbuild/rules_python/issues/411 contains a reproduction repository: https://github.com/gvacaliuc/rules_python_airflow2

**Comment by thundergolfer** [comment] 2021-02-08 00:53
There appears to have been related discussion of this circular deps issue here: https://github.com/apache/airflow/issues/12744#issuecomment-738027087

**Comment by potiuk** [comment] 2021-02-08 01:06
It''s been already solved in https://github.com/apache/airflow/commit/0d214575a144356a8a83a462d6d9fb68bf4999c7#diff-ee4de59d2448e097b1d108d4d83a0d40cb3e2767c84f67a62696e62c6afa23f8R291 in master during provider package preparatin (those 4 pre-installed packges will have no dependency any more on apache-airflow to avoid the dependency).

Also we are already voting on the new provider packages (target date to relese them - tomorrow).

The discussion about release candidates for those is in https://lists.apache.org/thread.html/rffdfd355a28e08ec7e3e8749eedd51ba8a248107d72e4b893d04af81%40%3Cdev.airflow.apache.org%3E 

Kind request @thundergolfer  - could you please check the release candidates for those packages:

* https://pypi.org/project/apache-airflow-providers-http/1.1.0rc1
* https://pypi.org/project/apache-airflow-providers-ftp/1.0.1rc1/
* https://pypi.org/project/apache-airflow-providers-imap/1.0.1rc1/
* https://pypi.org/project/apache-airflow-providers-sqlite/1.0.1rc1/

and install them with airflow, and see if the circular problem is solved? I am closing this issue now, but if you find that it is not solved, let me know what the problems are and I might re-open it.

**Closed as completed by potiuk** 2021-02-08 01:06 UTC
Labels: kind:bug, duplicate

**Comment by thundergolfer** [comment] 2021-02-08 09:57
Thanks for the detailed reply. I'll check those release candidates out and report back.

**Comment by thundergolfer** [comment] 2021-02-08 23:20
I've tested https://github.com/gvacaliuc/rules_python_airflow2 with https://pypi.org/project/apache-airflow-providers-http/1.1.0rc1 and it works. 

https://pypi.org/project/apache-airflow-providers-http/1.0.0 does not work, as expected, so it looks like this issue has been addressed.

#### Bazel Detail

For `1.1.0rc1`, we can see that the dependency's `py_library` does not list deps: 

```python
py_library(
    name = "pypi__apache_airflow_providers_http",
    srcs = glob(["**/*.py"], allow_empty = True),
    data = glob(["**/*"], exclude=["**/*.py", "**/* *", "BUILD", "WORKSPACE"]),
    # This makes this directory a top-level in the python import
    # search path for anything that depends on this.
    imports = ["."],
    deps = [],
)
```

For `1.0.0` it does: 

```python
py_library(
    name = "pypi__apache_airflow_providers_http",
    srcs = glob(["**/*.py"], allow_empty = True),
    data = glob(["**/*"], exclude=["**/*.py", "**/* *", "BUILD", "WORKSPACE"]),
    # This makes this directory a top-level in the python import
    # search path for anything that depends on this.
    imports = ["."],
    deps = ["//pypi__apache_airflow"],
)
```

**Comment by potiuk** [comment] 2021-02-09 00:16
Thanks ! in the meantime the providers are released officially!

**Comment by thekyz** [comment] 2021-03-31 13:35
also looks like the issue is not fixed at least for apache-airflow-providers-cncf-kubernetes

**Comment by potiuk** [comment] 2021-03-31 17:18
> @potiuk any clue when airflow will get a new release with this issue fixed?

It's already fixed in released 2.0.1 https://github.com/apache/airflow/pull/13314

> also looks like the issue is not fixed at least for apache-airflow-providers-cncf-kubernetes
It's never been an issue for cncf-kubernetes. This was only issue for the 4 providers that are preinstalled: 'ftp', 'http', 'imap',  'sqlite'. Airflow has only "extra" dependency on cncf.kubernetes but extras are not counting as "install-requires" so this is not a problem as far as I know (unless you specifically have some problem that you would like to describe).

**Comment by thekyz** [comment] 2021-03-31 18:31
Sorry I jumped to conclusions here. I get exactly the same issue as described above when installing apache-airflow[kubernetes] thus I thought it was the same root cause. Should I create a new ticket then?

**Comment by potiuk** [comment] 2021-03-31 19:41
I don't belive it's an issue at all. Airflow  is only officialyl installable with `pip` and it works nicely when you run it in including constraints in the way described here: http://airflow.apache.org/docs/apache-airflow/stable/installation.html#installation-tools. 

This is the only installation method that brings repeatable results. Other methods might fail, but w are not supporting a full range of tools that behave differently than PIP. If you are using poetry, pipenv or other tools like that you are pretty much on your own. If this is not a 'serious issue' but "some way of using some tool', it's likely to be closed as invalid. So possibly starting discussion and discussing it might be a better way to go about it.

**Comment by thekyz** [comment] 2021-03-31 21:02
Well I'm using pip through rules_python (a set of bazel rules to use pip libraries; it actually uses pip wheel to get the modules).

The download works fine, but then apache-airflow-providers-cncf-kubernetes declares a dependency on apache-airflow, which itself declares a dependency on apache-airflow-providers-cncf-kubernetes when installed with the extra, thus making bazel complains because of the circular dependency.

Since the issue had been addressed above for the other (albeit preinstalled) providers, I thought this would be a similar issue. I'm sorry I'm not very knowledgeable on pip so I'm not aware of the underlying difference between the preinstalled providers and the extras.

Is that dependency from apache-airflow-providers-cncf-kubernetes towards apache-airflow required for regular pip install?

**Comment by potiuk** [comment] 2021-03-31 21:16
There is no need to install both provider and extra. Extra is just a legacy way to install providers, but you can simply install 'apache-airflow' (no extra) and 'apche-airflow-providers-cncf-kubernetes' as two separate packages.

**Comment by potiuk** [comment] 2021-03-31 21:18
And answering your question - yes. There is no point in installing provider without airflow. So it makes perfect sense to have this dependency. It also prevents from installing providers with airflow 1.10 (as there is 2.0 apache-airflow dependency)

**Comment by potiuk** [comment] 2021-03-31 21:20
https://stackoverflow.com/q/52474931/516701 gives a brief explanation about extras. I think it make sens to at least take a brief look if you are going to use them to understand what they are

**Comment by potiuk** [comment] 2021-03-31 21:23
And here is explanation about airflow's extras http://airflow.apache.org/docs/apache-airflow/stable/extra-packages-ref.html - it's rather straightforward and helpful I think

**Comment by thekyz** [comment] 2021-03-31 22:13
Thanks for the links, definitely appreciated!

I managed to make it work by depending directly on the providers + apache-airflow, since then the dependency on the extras is not expressed. 

For reference if somebody is encountering the same issue as me, this:
```
apache-airflow-providers-cncf-kubernetes==1.0.2
apache-airflow-providers-postgres==1.0.1
apache-airflow[statsd]==2.0.1
```

instead of this:
```
apache-airflow[statsd,postgres,kubernetes]==2.0.1
```

Thanks again @potiuk for the support!
