### ISSUE TITLE
Grid view disappears when hovering over skipped mapped tasks

### ISSUE THREAD

**Issue by erdos2n** [apache/airflow#24620] opened 2022-06-23 16:12 UTC
### Apache Airflow version

2.3.2 (latest released)

### What happened

When hovering over a `skipped` task of a DAG in the Grid view, the Grid view will disappear. The console contains the following error messages, which point to a skipped task having an unknown length value.

```
grid.56cb323501b2bfa504f1.js:2 TypeError: Cannot read properties of undefined (reading 'length')
    at BO (grid.56cb323501b2bfa504f1.js:2:715227)
    at ui (grid.56cb323501b2bfa504f1.js:2:228868)
    at Qu (grid.56cb323501b2bfa504f1.js:2:280949)
    at Pl (grid.56cb323501b2bfa504f1.js:2:268222)
    at jl (grid.56cb323501b2bfa504f1.js:2:268150)
    at Cl (grid.56cb323501b2bfa504f1.js:2:268013)
    at bl (grid.56cb323501b2bfa504f1.js:2:265000)
    at grid.56cb323501b2bfa504f1.js:2:214787
    at t.unstable_runWithPriority (grid.56cb323501b2bfa504f1.js:2:291644)
    at Go (grid.56cb323501b2bfa504f1.js:2:214564)
cu @ grid.56cb323501b2bfa504f1.js:2
n.callback @ grid.56cb323501b2bfa504f1.js:2
ma @ grid.56cb323501b2bfa504f1.js:2
gu @ grid.56cb323501b2bfa504f1.js:2
Il @ grid.56cb323501b2bfa504f1.js:2
t.unstable_runWithPriority @ grid.56cb323501b2bfa504f1.js:2
Go @ grid.56cb323501b2bfa504f1.js:2
Tl @ grid.56cb323501b2bfa504f1.js:2
bl @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
t.unstable_runWithPriority @ grid.56cb323501b2bfa504f1.js:2
Go @ grid.56cb323501b2bfa504f1.js:2
Yo @ grid.56cb323501b2bfa504f1.js:2
Xo @ grid.56cb323501b2bfa504f1.js:2
hl @ grid.56cb323501b2bfa504f1.js:2
Ai @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
setTimeout (async)
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
Ue @ grid.56cb323501b2bfa504f1.js:2
Xe @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
jr @ grid.56cb323501b2bfa504f1.js:2
Rr @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
Le @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
Br @ grid.56cb323501b2bfa504f1.js:2
Jt @ grid.56cb323501b2bfa504f1.js:2
Zt @ grid.56cb323501b2bfa504f1.js:2
t.unstable_runWithPriority @ grid.56cb323501b2bfa504f1.js:2
Kt @ grid.56cb323501b2bfa504f1.js:2
grid.56cb323501b2bfa504f1.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at BO (grid.56cb323501b2bfa504f1.js:2:715227)
    at ui (grid.56cb323501b2bfa504f1.js:2:228868)
    at Qu (grid.56cb323501b2bfa504f1.js:2:280949)
    at Pl (grid.56cb323501b2bfa504f1.js:2:268222)
    at jl (grid.56cb323501b2bfa504f1.js:2:268150)
    at Cl (grid.56cb323501b2bfa504f1.js:2:268013)
    at bl (grid.56cb323501b2bfa504f1.js:2:265000)
    at grid.56cb323501b2bfa504f1.js:2:214787
    at t.unstable_runWithPriority (grid.56cb323501b2bfa504f1.js:2:291644)
    at Go (grid.56cb323501b2bfa504f1.js:2:214564)
BO @ grid.56cb323501b2bfa504f1.js:2
ui @ grid.56cb323501b2bfa504f1.js:2
Qu @ grid.56cb323501b2bfa504f1.js:2
Pl @ grid.56cb323501b2bfa504f1.js:2
jl @ grid.56cb323501b2bfa504f1.js:2
Cl @ grid.56cb323501b2bfa504f1.js:2
bl @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
t.unstable_runWithPriority @ grid.56cb323501b2bfa504f1.js:2
Go @ grid.56cb323501b2bfa504f1.js:2
Yo @ grid.56cb323501b2bfa504f1.js:2
Xo @ grid.56cb323501b2bfa504f1.js:2
hl @ grid.56cb323501b2bfa504f1.js:2
Ai @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
setTimeout (async)
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
Ue @ grid.56cb323501b2bfa504f1.js:2
Xe @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
jr @ grid.56cb323501b2bfa504f1.js:2
Rr @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
Le @ grid.56cb323501b2bfa504f1.js:2
(anonymous) @ grid.56cb323501b2bfa504f1.js:2
Br @ grid.56cb323501b2bfa504f1.js:2
Jt @ grid.56cb323501b2bfa504f1.js:2
Zt @ grid.56cb323501b2bfa504f1.js:2
t.unstable_runWithPriority @ grid.56cb323501b2bfa504f1.js:2
Kt @ grid.56cb323501b2bfa504f1.js:2
```

### What you think should happen instead

The Grid view should not disappear and the panel on the right should contain necessary fields and options for the skipped task.

### How to reproduce

Run a DAG with a skipped task and hover over the skipped task, the Grid view should disappear.

### Operating System

Mac OS Monterey

### Versions of Apache Airflow Providers

```
apache-airflow-providers-sftp==2.1.1
apache-airflow-providers-snowflake==2.1.1
```

### Deployment

Astronomer

### Deployment details

Deployment is on Astronomer Nebula and is Airflow version 2.3.2

Dockerfile
```
FROM quay.io/astronomer/ap-airflow:2.1.4-7-buster-onbuild
```

### Anything else

Every time

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment] 2022-06-23 18:08
@erdos2n Do you have a sample DAG for this? I can't seem to replicate this for just any skipped task.

**Comment by ashb** [comment] 2022-06-24 10:26
I think this was caused by hovering over a skipped mapped task -- i.e. when `make_list` in our example map dags returns a zero length list.

We may have already fixed this in main for 2.4 with one of our optimization PRs as I can't reproduce it right on main. Checking release.

**Comment by ashb** [comment] 2022-06-24 10:56
Yes, confirmed it's a bug in 2.3.2 but not a problem in main.

**Comment by bbovenzi** [comment] 2022-06-24 12:35
It looks like it was fixed in https://github.com/apache/airflow/commit/451a6f4d9ff8b744075e2f25099046c77f28179e#diff-50b1f3bc397270b30a4ed4928fb0a03896ecae7e9278546acccb5d53bd1c0f38

We also added typechecking in https://github.com/apache/airflow/pull/24509 so we should be able to catch these issues early-on.

**Closed as completed by bbovenzi** 2022-06-24 12:35 UTC
Labels: kind:bug, area:UI, area:dynamic-task-mapping
