### ISSUE TITLE
I set "start_date" as datetime but anyway I got this error 

### ISSUE THREAD

**Issue by pysergio** [apache/airflow#13768] opened 2021-01-19 17:51 UTC
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Python version: 3.8.6
Airflow version: 2.0.0
Node: 48e4ab66fdda
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/www/decorators.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/www/views.py", line 1193, in task
    attr = getattr(ti, attr_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 792, in previous_start_date_success
    return self.get_previous_start_date(state=State.SUCCESS)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 776, in get_previous_start_date
    return prev_ti and pendulum.instance(prev_ti.start_date)
  File "/home/airflow/.local/lib/python3.8/site-packages/pendulum/__init__.py", line 174, in instance
    raise ValueError("instance() only accepts datetime objects.")
ValueError: instance() only accepts datetime objects.

**What you expected to happen**:

Get info about task instance

**How to reproduce it**:

**Anything else we need to know**:

**Comment by eladkal** [comment] 2021-01-19 20:59
Can you please share a reproduce example?
The traceback suggest that you are using `get_previous_start_date` in your DAG. I have a guess that you encounter this error in the first run on Airflow 2.0.0 but not on Airflow 1.10.X?

**Comment by kaxil** [comment] 2021-01-19 23:11
Yes please add more information, and provide your DAGs so that we can reproduce

**Comment by SamWheating** [comment] 2021-02-25 21:48
> The traceback suggest that you are using get_previous_start_date in your DAG.


We've seen this issue on one of our DAGs as well (when viewing task details from a run with many preceeding runs) and I can confirm we are not using the `get_previous_start_date` in the DAG directly - In our case (as well as the above stack trace) it looks like this is called by the get_attr when rendering the task instance details page.  

I'll see if I can gather more information on the cause of this issue and provide a simple example DAG.

**Comment by kaxil** [comment] 2021-02-25 23:57
This is fixed by https://github.com/apache/airflow/pull/14416 and will be released in 2.0.2

**Closed as completed by kaxil** 2021-02-25 23:57 UTC
Labels: kind:bug, priority:medium, pending-response
