### ISSUE TITLE
Gantt screen is flickering 

### ISSUE THREAD

**Issue by Shlomixg** [apache/airflow#42243] opened 2024-09-15 08:07 UTC
### Apache Airflow version

2.10.1

### What happened?

After upgrading to AF 2.10.1 we noticed that some of our environments started to flicker on the Gantt screen.
The issue isn’t consistent across all DAGs. So far, we haven’t observed any issues on the backend side, leading us to believe that this is a UI bug.

Here is an example:

https://github.com/user-attachments/assets/0a13fbeb-5e4a-422c-b133-cd84aea1d96a

### How to reproduce

We’re not sure how to reproduce the bug since it’s not consistent. However, the issue occurs on both Chrome (version 128.0.6613.138) and Edge (version 128.0.2739.79).

The client OS is Windows 11 23H2, and AF is running in Docker Containers on Debian 12

### Operating System

Windows 11

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2024-09-15 20:27
Duplicate of https://github.com/apache/airflow/issues/42215 ?

**Comment by Shlomixg** [comment] 2024-09-16 05:26
Indeed. We didn't noticed this issue on AF 2.8.2

**Closed as completed** 2024-09-19 18:32 UTC
Labels: kind:bug, area:core, area:UI, needs-triage
