### ISSUE TITLE
Add how-to Guide for Postgres operators #11917

### ISSUE THREAD

**Issue by drdenzy** [apache/airflow#12758] opened 2020-12-02 15:51 UTC
Description

A guide that describes how to use all the operators for Postgres (https://github.com/apache/airflow/tree/master/airflow/providers/postgres) would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Source code for those guides are at:
https://github.com/apache/airflow/tree/master/docs/howto/operator

Are you wondering how to start contributing to this project? Start by reading our contributor guide

Best regards,
Kaxil﻿

**Comment by eladkal** [comment] 2020-12-07 08:34
duplicate of https://github.com/apache/airflow/issues/11917

**Closed as completed by eladkal** 2020-12-07 08:34 UTC
