### ISSUE TITLE
WTForms Breaking Change 2.3.0

### ISSUE THREAD

**Issue by mbaroody** [apache/airflow#8517] opened 2020-04-22 14:54 UTC
**Apache Airflow version**: 1.10.9

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**: AKS

- **Cloud provider or hardware configuration**: AKS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: Helm 
```
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}                                  Server: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
```
- **Others**:

**What happened**:
Getting the following ImportError this morning: 

```
*** waiting 10s...
*** executing initdb
[2020-04-22 14:47:47,388] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=26
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 26, in <module>
    from airflow.bin.cli import CLIFactory
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 71, in <module>                                                                
    from airflow.www_rbac.app import cached_app as cached_app_rbac
  File "/usr/local/lib/python3.7/site-packages/airflow/www_rbac/app.py", line 27, in <module>                                                           
    from flask_appbuilder import AppBuilder, SQLA
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/__init__.py", line 6, in <module>                                                       
    from .base import AppBuilder  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/base.py", line 8, in <module>                                                           
    from .api.manager import OpenApiManager
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/api/manager.py", line 7, in <module>                                                    
    from flask_appbuilder.baseviews import BaseView
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/baseviews.py", line 21, in <module>                                                     
    from .forms import GeneralModelConverter
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/forms.py", line 17, in <module>                                                         
    from .fieldwidgets import (
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/fieldwidgets.py", line 3, in <module>                                                   
    from wtforms.widgets import html_params, HTMLString
ImportError: cannot import name 'HTMLString' from 'wtforms.widgets' (/usr/local/lib/python3.7/site-packages/wtforms/widgets/__init__.py)                
```

**What you expected to happen**:

due to breaking change here in v2.3.0: https://github.com/wtforms/wtforms/compare/2.2.1...2.3.0#diff-6393540c887450b9738cb2eecc5bcad8

**How to reproduce it**: 

**Anything else we need to know**:

**Comment by imatsu** [comment] 2020-04-22 15:23
@mbaroody try to install it as recommended by the documentation in the [repository](https://github.com/apache/airflow#installing-from-pypi)

**Comment by flinz** [comment] 2020-04-22 15:25
Pinning WTForms==2.2.1 solves this for me.

**Comment by potiuk** [comment] 2020-04-22 15:42
Closing as duplicate of #8512 

Kind request @mbaroody -> could you please check if an issue has not already been reported/solved. You have "similar issues" link when you click create issue and I am sure if you click it after typing the issue title. you'd see both issues already created

**Closed as completed by potiuk** 2020-04-22 15:42 UTC
Labels: duplicate

**Comment by potiuk** [comment] 2020-04-22 15:44
Also FYI. We have this new description of how to make sure apache-airflow can be installed reliably always - no matter the dependencies change: https://github.com/apache/airflow#installing-from-pypi

**Comment by mbaroody** [comment] 2020-04-22 16:35
thank you @potiuk  :)
