### ISSUE TITLE
After last updates tasks disappear and then reappear

### ISSUE THREAD

**Issue by aipatr** [apache/airflow#37774] opened 2024-02-28 15:59 UTC
### Apache Airflow version

2.8.2

### What happened?

Often starting a pipeline it is not visualized between the ongoing pipelines. The page looks like nothing happened, one need to forcefully refresh it or go out to the list of pipelines in order to see the 

### What you think should happen instead?

Have the behaviour like in 2.8.1

### How to reproduce

Install 2.8.2
Take a pipeline implemented, enter in the page where you can see the tasks composing it, logs and so on.
Press the start button for running the pipeline.
Nothing is changing in the view.

Go back to the home page with all the airflow pipelines.
Enter inside the pipeline that you just started, the new pipeline is there.

### Operating System

Ubuntu

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Eshanel** [comment] 2024-03-05 09:31
Hello, 
We have the same behavior. To add more context, the error appears everytime we have a `dag_run_id` parameter in the url in the dag grid view, it "hides" the next dagruns if we refresh the page.
It looks related to this pr https://github.com/apache/airflow/pull/34887

**Comment by hterik** [comment] 2024-03-12 09:05
Yes this is likely caused by https://github.com/apache/airflow/pull/34887

I don't know what should be the expected behaviour here. If `dag_run_id` is included in url, the base date must be adjusted to be sure that particular run is displayed. But for more recent runs where selected `dag_run_id` + most recent runs fits within 25 runs, one would probably rather see the more recent runs?

Maybe one should change the logic so that if `dag_run_id` is included, invert the sort order to take the selected run_id + 25 more recent runs, instead of 25 older runs?

Another solution is to clear the `dag_run_id` parameter after clicking start.

**Comment by aipatr** [comment] 2024-03-12 09:07
The current problem happens with 4 runs for me.

Dr. Aniello Raffaele Patrone
Lead AI Scientist

Email: ***@***.******@***.***>
Internet: www.piurimaging.com<http://www.piurimaging.com/>

***@***.***<https://www.linkedin.com/company/piur-imaging-gmbh>  ***@***.*** <https://twitter.com/piurimaging>
--------------------------

***@***.***

piur imaging GmbH
Hamburgerstr. 11/Top 7
1050 Vienna
Austria

**Comment by bbovenzi** [comment] 2024-03-12 15:59
Yes, I noticed a bug with the base_date logic. I'll work on a fix.

**Comment by bbovenzi** [comment] 2024-04-18 19:19
Fixed by: https://github.com/apache/airflow/pull/38941

**Closed as completed by bbovenzi** 2024-04-18 19:19 UTC
Labels: kind:bug, area:webserver, area:UI, _eol_affected_version:2.8
