### ISSUE TITLE
Dynamic tasks are randomly put in removed state

### ISSUE THREAD

**Issue by cesar-vermeulen** [apache/airflow#26197] opened 2022-09-07 09:18 UTC
### Apache Airflow version

Other Airflow 2 version

### What happened

We have a DAG running with a cronjob schedule every 4 minutes that checks whether there is a new file present in a file system or not. If there is one available, it lists its path and passes it as a dynamic task via XCOM (one task = one file).

We have experienced a couple of times already that this task is never started, nor does it appear in the logs (not in scheduler logs, nor in AKS logs). It simply disappears and the status of the task is removed.

The DAG has following configurations:
Schedule interval: "*/4 5-22 * * 1-5"
Catchup: False
End Date: None
Max Active Runs: 1
Concurrency: 1
DAG Run Timeout: 0:10:00

![list_metadata success](https://user-images.githubusercontent.com/94971679/188836813-64e8e89b-619e-4270-b1a3-60583cf4a46a.jpg)
![removed_task](https://user-images.githubusercontent.com/94971679/188836817-ebe79b8d-a49f-494c-9981-8c546f115a8d.jpg)
![xcom](https://user-images.githubusercontent.com/94971679/188836821-6dcb6c82-5fab-45da-b5be-29793c79d53f.jpg)

### What you think should happen instead

The task should be triggered and started. Instead, it gets the status removed without any logs or trace 

### How to reproduce

This happens in random moments, so exact steps to reproduce are hard to determine

### Operating System

Airflow base docker image

### Versions of Apache Airflow Providers

* apache-airflow-providers-microsoft-azure: 4.2.0

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

We are running on AKS with a postgresql backend, with the airflow helm chart of 2.3.3. Docker image is the airflow base image.
Logs are being sent to an azure file share.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment] 2022-09-08 02:54
duplicate of #25744

**Closed as not planned by uranusjr** 2022-09-08 02:54 UTC
Labels: duplicate

**Comment by cesar-vermeulen** [comment] 2022-09-08 08:14
Hey @uranusjr,
Thank you for your reply.
I noticed #25744, however, in this situation, it does not happen during backfill. 
Would this behaviour also be expected when not using backfill?

**Comment by uranusjr** [comment] 2022-09-08 15:13
The linked issue is slightly misleading; it describes backfilling, but the cause has nothing to do with backfilling specifically, as you can read from the PR fixing it.
