### ISSUE TITLE
data interval for manual runs show different behavior compared to scheduled runs

### ISSUE THREAD

**Issue by park-peter** [apache/airflow#25408] opened 2022-07-29 18:16 UTC
### Apache Airflow version

2.3.3 (latest released)

### What happened

When manually triggering a dag run using "Trigger DAG w/ config" and setting the logical date and time, the UI of the dag run triggered will show a data interval that is two schedule intervals off. For example, for a daily run, setting the logical date to 2022-07-24 00:00:00 UTC would show the data interval with a start date of 2022-07-22 and end of 2022-07-23. Rendering {{ ds_nodash }} on this run will show "2022-07-24" which is correct, but since the grid view orders the runs on the incorrect start date, things can get confusing.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/46539900/181820332-0eedab1d-f163-46f0-8fa7-9f6c1d24d8b8.png">

### What you think should happen instead

Either the data interval behaves the same as with the scheduled run and show start date as the logical date and the end date as the logical date + schedule interval, or, per the documentation [here](https://airflow.apache.org/docs/apache-airflow/stable/faq.html#why-next-ds-or-prev-ds-might-not-contain-expected-values) the prev_ds == next_ds == ds and so the data interval should all be 2022-07-24 for the above example. 

### How to reproduce

1. Create a simple DAG with a schedule interval, as such:
```
import json
from datetime import datetime

from airflow.decorators import dag, task


@dag(
    schedule_interval="@daily",
    start_date=datetime(2021, 1, 1),
    catchup=False,
)
def example_dag_basic():
    @task()
    def example():
        print("this is an example task")

    example()


example_dag_basic = example_dag_basic()
```
2. Trigger a run using "Trigger DAG w/ config" and manually create a run for some date
3. Observe the start date as 2 schedules off.

### Operating System

Debian Bullseye

### Deployment

Astronomer

### Deployment details

Local was tested on docker compose (from astro-cli)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment] 2022-07-30 03:44
Duplicate of #23689

**Closed as not planned by uranusjr** 2022-07-30 03:44 UTC
Labels: kind:bug, area:core
