### ISSUE TITLE
Issue when passing the output of a traditional operator to a Task Group

### ISSUE THREAD

**Issue by matthieucx** [apache/airflow#32603] opened 2023-07-14 13:41 UTC
### Apache Airflow version

2.6.3

### What happened

Hello!

When passing the output of a traditional operator to a task group, the operator is added to the task group.

![operator_tg_issue](https://github.com/apache/airflow/assets/11246353/ca99d153-e506-44f7-adf5-6eff8a6cc463)

Furthermore, when expanding the task group using this output, the task group is set as upstream of the operator, which causes a cyclic dependency and fails the DAG.

![operator_tg_expansion_issue](https://github.com/apache/airflow/assets/11246353/ede4bc69-b81f-4644-903b-d7877736ddf2)

As a quick fix, adding a task that simply returns its input between the task group and the operator solves the issue.

![operator_tg_expansion_fix](https://github.com/apache/airflow/assets/11246353/a7870d76-f6c1-441f-8206-4423eb1f9406)

### What you think should happen instead

The operator should not be added to the task group. It should behave like a `@task()` decorated function would.

### How to reproduce

The following minimal DAG is enough to reproduce the issue:

```python
from datetime import datetime

from airflow.decorators import dag, task, task_group
from airflow.operators.dummy_operator import DummyOperator

dummy_task = DummyOperator(task_id="dummy_task")


@task()
def print_task(data):
    print(data)


@task()
def passtrough(data):
    return data


@task_group()
def tg(data):
    print_task(data)


@dag(
    dag_id="expansion_classic_operator",
    schedule=None,
    catchup=False,
    start_date=datetime(2021, 1, 1),
    max_active_runs=1,
)
def ExpansionIssueDAG():
    tg.expand(data=dummy_task.output)


dag = ExpansionIssueDAG()
```

### Operating System

Ubuntu 22.04.2 LTS

### Deployment

Docker-Compose

### Anything else

I would be willing to contribute, but I haven't investigated where the issue could originate from and don't have a lot of time on my hand at the moment.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment] 2023-07-15 20:14
I assume this is rather a modelling issue than a problem with a task mapping logic. In your example the `dummy_task` is defined outside the DAG context and can not be correctly associated. Try it to be defined within the DAG scope, then it works, for example below:

```
from datetime import datetime

from airflow.decorators import dag, task, task_group
from airflow.operators.dummy_operator import DummyOperator

@task()
def print_task(data):
    print(data)

@task_group()
def tg(data):
    print_task(data)

@dag(
    dag_id="issue_32603",
    schedule=None,
    catchup=False,
    start_date=datetime(2021, 1, 1),
    max_active_runs=1,
)
def ExpansionIssueDAG():
    dummy_task = DummyOperator(task_id="dummy_task")
    tg.expand(data=dummy_task.output)


dag = ExpansionIssueDAG()
```

Result is:
![Screenshot_2023-07-15_22-13-24](https://github.com/apache/airflow/assets/95105677/7d5037ed-1aea-4daf-9de0-d31231a4c309)

**Comment by hussein-awala** [comment] 2023-07-15 20:33
@jens-scheffler-bosch Indeed, I was going to write the same comment.

However, I observed another issue (it could be an expected behavior), where the tg fails when I expend it using the output of an empty task.

**Comment by hussein-awala** [comment] 2023-07-15 21:19
> However, I observed another issue (it could be an expected behavior), where the tg fails when I expend it using the output of an empty task.

That's because EmptyOperator (or DummyOperator) doesn't push any xcom, so we cannot use its output.

I close the issue because it is not a bug, but a modelling issue.

**Closed as completed by hussein-awala** 2023-07-15 21:19 UTC
Labels: kind:bug, invalid, area:core, affected_version:main_branch

**Comment by matthieucx** [comment] 2023-07-16 11:15
Thanks a lot for the correction.

To anyone who ends up here having a similar issue, from what I understand:

When you create a `@task()` decorated function, you create a new task template.
When you call the function inside tha dag context, you create a task.

When you call a traditional operator, you directly create a task, which is why you have to call the operator in the DAG context.

Those are relevant :
[Tasks Doc](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#tasks)
[Operators Doc](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/operators.html#operators)
