### ISSUE TITLE
S3 to GCS to BQ daily incremental data transfer pipeline. Append data from only the incremental (newly added) files from GCS into BQ table?

### ISSUE THREAD

**Issue by arubafna** [apache/airflow#13898] opened 2021-01-25 21:06 UTC
**Description**
Set up an automated Airflow pipeline for data transfer from S3 to GCS to BQ. 

**Use case / motivation**
A major requirement of the solution is to trigger the dag daily, to get daily S3 data uploaded into BQ external source partitioned(hive) tables

**Related Issues**
For the first part, we have used the **"S3ToGoogleCloudStorageOperator"** which imports the files from the source s3 bucket into the destination GCS bucket. This operator ensures to copy only the newly added (incremental) files. In the backend, it returns a list of newly added filenames which is pushed into XCOM and which we then pass onto the 
**"BigQueryInsertJobOperator"** by **pulling the XCOM**.
This ensures that only the data from the incremental files is appended into the BQ tables.

 **Issue:**
This works perfectly fine for most of my S3 buckets, however for some cases I receive this error:
**ERROR - (_mysql_exceptions.DataError) (1406, "Data too long for column 'value' at row 1"
[SQL: INSERT INTO xcom (`key`, value, timestamp, execution_date, task_id, dag_id) VALUES (%s, %s, %s, %s, %s, %s)**
Which I realize is because of **XCOM size limitations**. The list of string filenames may be exceeding the limit.
An example of the list returned: ["partner=doubleverify/sfmt=v1/table=blk/seat=607671/dt=2021-01-15/file=ATT_BLK_ImpID-20210115-07.csv.gz/part-00000-10065608-4a8e-45e3-99df-3f1c7765ed3f-c000.snappy.parquet", .....500 more elements ]

**Comment by eladkal** [comment] 2021-01-27 05:28
Xcom has limits. In Airflow 2 you can define a custom xcom backend 
see [documentation](https://airflow.apache.org/docs/apache-airflow/stable/concepts.html?highlight=xcom#custom-xcom-backend), [polidea article](https://www.polidea.com/blog/airflow-2-0-dag-authoring-redesigned/)

I don't really know your use case but I'm not really sure if xcom are even needed here. Why not simply writing the delta (increment) to a folder in GCS in a known path? For example using `{{ ds }}` for daily runs or  `{{ ts_nodash }}` for hourly runs then the loading job can just read the data from this known path without looking in xcoms.

In any case since this is not a bug/feature request but more of a troubleshooting question for a specific ETL I'm closing this issue. If you need further assistance please ask on https://stackoverflow.com/

**Closed as completed by eladkal** 2021-01-27 05:28 UTC
Labels: invalid
