### ISSUE TITLE
task is incorrectly triggered after dynamic task mapping with BranchPythonOperator

### ISSUE THREAD

**Issue by raycarter** [apache/airflow#40620] opened 2024-07-05 11:49 UTC
### Apache Airflow version

2.9.2

### What happened?

We need to use BranchPythonOperator and dynamic task mapping in a DAG to meet our requirements. The BranchPythonOperator controls whether dynamic mapping is needed, and there is a task (branch_2_task) following the dynamic task mapping that must be executed regardless of whether the dynamic task mapping runs (it can be skipped by receiving an empty list). As shown in the diagram 1, the trigger_rule for branch_2_task needs to be set to none_failed. 

diagram 1:
![image](https://github.com/apache/airflow/assets/2765326/5d12e4d8-365a-40ef-b554-09a5729fecbc)

If it is set to all_success, the task branch_2_task will also be skipped if the dynamic mapping is skipped due to an empty list (diagram 2). 

diagram 2:
![image](https://github.com/apache/airflow/assets/2765326/f063a815-2976-44d8-8006-fa80ebaae687)

However, when BranchPythonOperator triggers the branch_1 task, the task branch_2_task on the other branch also gets executed (diagram 3). 

diagram 3:
![image](https://github.com/apache/airflow/assets/2765326/31a2c2e6-112f-42c5-b8d0-4911bed161f7)

The potential bug could be that Airflow does not check if a task is on the executing branch but only checks the trigger_rule.

Could you fix this?

### What you think should happen instead?

The task branch_2_task has trigger_rule none_failed to be executed even if the dynamic task mapping before it is skipped. If the other branch is executed, the task branch_2_task must be skipped because the branch should be skipped.

### How to reproduce

- Airflow 2.9.2
- the demo DAG is here: https://gist.github.com/raycarter/75e896d600adec0563545fc58e3795d2
  - use parameters condition1 = 2, mapping_count = 0 to reproduce diagram 1
  - use parameters condition1 = 1, mapping_count = 0 to reproduce diagram 3
  - change trigger_rule of branch_2_task to all_success, use parameters condition1 = 2, mapping_count = 0 to reproduce diagram 2 

### Operating System

Ubuntu

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by romsharon98** [comment] 2024-07-05 12:33
In the third picture the branch_2_task trigger rule set to `none_failed`,since all the previous tasks are not failed (skipped or success) it should run.

**Comment by raycarter** [comment] 2024-07-05 13:42
> In the third picture the branch_2_task trigger rule set to `none_failed`,since all the previous tasks are not failed (skipped or success) it should run.

the problem is actually, in the 3rd picture the task branch_2_task should not run, because the branch operator decided branch_1 (the other branch) to trigger.

**Comment by romsharon98** [comment] 2024-07-05 14:12
I see.
I still don't know if it's a bug though because the reason I mention, so we will wait for third opinion.
A quick action that I think of to avoid it, in branch_2_task you can retrive the task_id from the branch_operator and decide to run the logic or not by this.

**Comment by raycarter** [comment] 2024-07-08 12:58
sure! thank you for the quick first response!

**Comment by shahar1** [comment] 2024-07-28 15:08
The interaction between the trigger rule `none_failed` and skipped tasks [is not well defined in the docs](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html#trigger-rules), as only `all_success` and `alll_failed` are mentioned. 
However, following the example in the docs, which sets a trigger rule to a downstream task of a skipped branch - we could conclude that defining trigger rules for tasks overcomes the behavior of `BranchPythonOperator`.
Thus, the behavior that you presented is expected. I agree, though, that this behavior should be clarified (or maybe even revised). You're welcome to create a PR for adding this exact example to the docs.
I'm closing this issue, but feel free to create a new one if you need (this issue was very comfortable to reproduce).

**Closed as not planned by shahar1** 2024-07-28 15:08 UTC
Labels: kind:bug, area:core, area:dynamic-task-mapping, _eol_affected_version:2.9
