### ISSUE TITLE
Use full postgresql URI connection prefix.

### ISSUE THREAD

**Issue by codekronik** [apache/airflow#27474] opened 2022-11-02 19:11 UTC
### Apache Airflow version

2.4.2

### What happened

This creates a deprecated URI string. I've added a new connection, using `get_uri()` returns a URI with `postgres://` instead of `postgressql://` so it's incompatible with a few libs. Should this be updated to return valid format URI ?

### What you think should happen instead

The URI should return URI with `postgresql://` prefix.

### How to reproduce

Add a new postgres connection, pull up the Connection by ID in DAG and try using it directly with SQLAlchemy

### Operating System

Debian

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bdsoha** [comment] 2022-11-02 20:02
This has already been implemented in the [postgres hook](https://github.com/apache/airflow/blob/main/airflow/providers/postgres/CHANGELOG.rst#400).

**Comment by codekronik** [comment] 2022-11-02 20:14
Hm. Odd I'm using Airflow 2.4.2 and its still returning old prefix.

**Comment by potiuk** [comment] 2022-11-02 20:18
You must have wrong Provider version: https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/index.html#id12 (postgres provider 4.0.0 has this fix implemented https://github.com/apache/airflow/pull/21205.  I guess you have not installed/upgraded to the new version of airflow with constraints (https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html)  and you have an old version of Postgres provider.

**Comment by potiuk** [comment] 2022-11-02 20:19
Closing. We can reopen if there are new evidences.

**Closed as completed by potiuk** 2022-11-02 20:19 UTC
Labels: kind:bug, area:core

**Comment by codekronik** [comment] 2022-11-02 20:56
@potiuk I have the latest airflow, with latest packages.

![Screenshot 2022-11-02 215436](https://user-images.githubusercontent.com/12471965/199600779-1cd79984-1160-41ed-9104-608b07f78d9c.png)

![Screenshot 2022-11-02 215608](https://user-images.githubusercontent.com/12471965/199600870-c226b693-ce04-4467-82ee-f4b8e2b96b88.png)

I have tried rebuilding the image. I have tried refreshing the requirements, checked 3 times that I have the latest package version. :/

**Comment by potiuk** [comment] 2022-11-03 08:48
Which postgres provider do you have ?

**Comment by potiuk** [comment] 2022-11-03 08:52
And what is the connection you have defined for postgres that returns the URI and how you defined it. Generally the problem is solved, so it is like some problem with your configuration/ways of defining or using the connections  If you do not provide reproducible steps how to get to the same results it will be difficult to help to solve your problem (or find a flaw in Airflow which might also be the case but I think  it is unlikely)

**Comment by codekronik** [comment] 2022-11-03 22:35
@potiuk Ok the issue appears because this has not been updated in the Connection model. Basically if you do `BaseHook.get_connection(conn_id).get_uri()`

**Comment by potiuk** [comment] 2022-11-04 13:08
You still have not explained how did you define your connection - What is the connection type you have in your connection?
You might have be completely mislead -  `PostgressHook.get_hook()` is NOT a PostgresHook method - it is the "BaseHook" static method - and it will only return PostgresHook if you pass it the connection, that it will recognise as Postgres - this is likely the reason - likely "PostgresHook.get_hook()" will actually return non-PostgresHook but something else.

Can you please explain how your connection_id is defined and what type it has ? And what is the hook returned by `get_hook` method?

**Comment by andersbogsnes** [comment] 2022-11-09 18:17
Someone from my team ran into a similar problem. I believe the problem stems from this line: https://github.com/apache/airflow/blob/main/airflow/models/connection.py#L215.

If you use `BaseHook.get_connection()` passing in a "Postgres" type connection, the `conn_type` will be "postgres": https://github.com/apache/airflow/blob/main/airflow/providers/postgres/hooks/postgres.py#L66, meaning the final uri will start with `postgres` instead of `postgresql`.

The fix as I see it, is to use either `BaseHook.get_hook(conn_id).get_uri()` if you want a generic solution or to use the `PostgresHook` directly but I guess the question is whether or not `BaseHook.get_uri()` is supposed to render the uri correctly in all cases?

**Comment by potiuk** [comment] 2022-11-16 22:24
> Someone from my team ran into a similar problem. I believe the problem stems from this line: https://github.com/apache/airflow/blob/main/airflow/models/connection.py#L215.
> 
> If you use `BaseHook.get_connection()` passing in a "Postgres" type connection, the `conn_type` will be "postgres": https://github.com/apache/airflow/blob/main/airflow/providers/postgres/hooks/postgres.py#L66, meaning the final uri will start with `postgres` instead of `postgresql`.
> 
> The fix as I see it, is to use either `BaseHook.get_hook(conn_id).get_uri()` if you want a generic solution or to use the `PostgresHook` directly but I guess the question is whether or not `BaseHook.get_uri()` is supposed to render the uri correctly in all cases?

Would you like to make a PR to fix it @andersbogsnes ?

**Comment by andersbogsnes** [comment] 2022-11-17 06:26
@potiuk Sure - I'll give it a go 👍
