### ISSUE TITLE
The `/dags/{dag_id}/details` endpoint returns less data than is documented

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#33482] opened 2023-08-17 19:15 UTC
### What do you see as an issue?

The [/dags/{dag_id}/details](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/post_set_task_instances_state) endpoint of the REST API does not return all of the keys that are listed in the documentation. If I run `curl -X GET localhost:8080/api/v1/dags/{my_dag}/details`, then compare the results with the results in the documentation, you can see the following missing keys:

```python
>>> for key in docs.keys():
...     if not key in actual.keys():
...             print(key)
...
root_dag_id
last_parsed_time
last_pickled
last_expired
scheduler_lock
timetable_description
has_task_concurrency_limits
has_import_errors
next_dagrun
next_dagrun_data_interval_start
next_dagrun_data_interval_end
next_dagrun_create_after
template_search_path
```

### Solving the problem

Either remove these keys from the documentation or fix the API endpoint

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment] 2023-08-18 10:06
In OpenAI specification all of this fields marked as nullable, so I assume if no data exists for this fields (`null`) then this key doesn't exists in response. I'm not sure is it a bug or by design

- [DagDetail object specification](https://github.com/apache/airflow/blob/eed09daad3278706da29c8f172899e67ecadc40a/airflow/api_connexion/openapi/v1.yaml#L3543)
- [Dag object specification](https://github.com/apache/airflow/blob/eed09daad3278706da29c8f172899e67ecadc40a/airflow/api_connexion/openapi/v1.yaml#L2603)

**Comment by hussein-awala** [comment] 2023-08-18 20:21
> In OpenAI specification all of this fields marked as nullable, so I assume if no data exists for this fields (null) then this key doesn't exists in response.

I don't think so, when I run the same query I get some fields with none values.

The problem is that we dump an instance of DAG class, but some of our fields exists in the DagModel class. I'm trying to find a solution, but IMHO it is not a bug in the documentation.

cc: @pankajkoti

**Comment by Taragolis** [comment] 2023-08-18 20:53
Oh, you right. I've also have a look, and found that there are different approaches to get data for DAGSchema ([from DagModel](https://github.com/apache/airflow/blob/53c6305bd0a914738074821d5f5f233e3ed5bee5/airflow/api_connexion/endpoints/dag_endpoint.py#L48-L57)) and DAGDetailsSchema ([from DagBag](https://github.com/apache/airflow/blob/53c6305bd0a914738074821d5f5f233e3ed5bee5/airflow/api_connexion/endpoints/dag_endpoint.py#L60C4-L66))

**Comment by RNHTTR** [comment] 2023-09-11 13:30
So... all of the "missing" fields are attributes defined in [DAGSchema](https://github.com/apache/airflow/blob/53c6305bd0a914738074821d5f5f233e3ed5bee5/airflow/api_connexion/schemas/dag_schema.py#L42) that for some reason aren't propagating to [DAGDetailSchema](https://github.com/apache/airflow/blob/53c6305bd0a914738074821d5f5f233e3ed5bee5/airflow/api_connexion/schemas/dag_schema.py#L91)? Is that accurate...?

**Closed as completed** 2023-11-24 09:47 UTC
Labels: kind:bug, area:API, kind:documentation
