### ISSUE TITLE
[BUG] 2.4.0b1 - google-provider - AttributeError: 'str' object has no attribute 'version'

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#26238] opened 2022-09-08 14:46 UTC
### Apache Airflow version

main (development)

### What happened

when I start airflow 2.4.0b1 with the `apache-airflow-providers-google==8.3.0`

the webserver log give : 

```log
[2022-09-08 14:39:53,158] {webserver_command.py:251} ERROR - [0 / 0] Some workers seem to have died and gunicorn did not restart them as expected
[2022-09-08 14:39:53,275] {providers_manager.py:228} WARNING - Exception when importing 'airflow.providers.google.common.hooks.base_google.GoogleBaseHook' from 'apache-airflow-providers-google' package
2022-09-08T14:39:53.276959961Z Traceback (most recent call last):
2022-09-08T14:39:53.276965441Z   File "/usr/local/lib/python3.8/site-packages/airflow/providers_manager.py", line 260, in _sanity_check
2022-09-08T14:39:53.276969533Z     imported_class = import_string(class_name)
2022-09-08T14:39:53.276973476Z   File "/usr/local/lib/python3.8/site-packages/airflow/utils/module_loading.py", line 32, in import_string
2022-09-08T14:39:53.276977496Z     module = import_module(module_path)
2022-09-08T14:39:53.276981203Z   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2022-09-08T14:39:53.276985012Z     return _bootstrap._gcd_import(name[level:], package, level)
2022-09-08T14:39:53.277005418Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-09-08T14:39:53.277011581Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-09-08T14:39:53.277016414Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-09-08T14:39:53.277020883Z   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2022-09-08T14:39:53.277025840Z   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2022-09-08T14:39:53.277029603Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-09-08T14:39:53.277032868Z   File "/usr/local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 49, in <module>
2022-09-08T14:39:53.277036076Z     from airflow.providers.google.cloud.utils.credentials_provider import (
2022-09-08T14:39:53.277038762Z   File "/usr/local/lib/python3.8/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 36, in <module>
2022-09-08T14:39:53.277041651Z     from airflow.providers.google.cloud._internal_client.secret_manager_client import _SecretManagerClient
2022-09-08T14:39:53.277044383Z   File "/usr/local/lib/python3.8/site-packages/airflow/providers/google/cloud/_internal_client/secret_manager_client.py", line 26, in <module>
2022-09-08T14:39:53.277047248Z     from airflow.providers.google.common.consts import CLIENT_INFO
2022-09-08T14:39:53.277050101Z   File "/usr/local/lib/python3.8/site-packages/airflow/providers/google/common/consts.py", line 23, in <module>
2022-09-08T14:39:53.277052974Z     CLIENT_INFO = ClientInfo(client_library_version='airflow_v' + version.version)
2022-09-08T14:39:53.277055720Z AttributeError: 'str' object has no attribute 'version'
[2022-09-08 14:39:53,299] {providers_manager.py:228} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.cloud_sql.CloudSQLHook' from 'apache-airflow-providers-google' package
2022-09-08T14:39:53.300816697Z Traceback (most recent call last):
2022-09-08T14:39:53.300822358Z   File "/usr/local/lib/python3.8/site-packages/airflow/providers_manager.py", line 260, in _sanity_check
2022-09-08T14:39:53.300827098Z     imported_class = import_string(class_name)
2022-09-08T14:39:53.300831757Z   File "/usr/local/lib/python3.8/site-packages/airflow/utils/module_loading.py", line 32, in import_string
2022-09-08T14:39:53.300836033Z     module = import_module(module_path)
2022-09-08T14:39:53.300840058Z   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2022-09-08T14:39:53.300844580Z     return _bootstrap._gcd_import(name[level:], package, level)
2022-09-08T14:39:53.300862499Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-09-08T14:39:53.300867522Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-09-08T14:39:53.300871975Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-09-08T14:39:53.300876819Z   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2022-09-08T14:39:53.300880682Z   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2022-09-08T14:39:53.300885112Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-09-08T14:39:53.300889697Z   File "/usr/local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/cloud_sql.py", line 51, in <module>
2022-09-08T14:39:53.300893842Z     from airflow.providers.google.common.hooks.base_google import GoogleBaseHook
2022-09-08T14:39:53.300898141Z   File "/usr/local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 49, in <module>
2022-09-08T14:39:53.300903254Z     from airflow.providers.google.cloud.utils.credentials_provider import (
2022-09-08T14:39:53.300906904Z   File "/usr/local/lib/python3.8/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 36, in <module>
2022-09-08T14:39:53.300911707Z     from airflow.providers.google.cloud._internal_client.secret_manager_client import _SecretManagerClient
2022-09-08T14:39:53.300916818Z   File "/usr/local/lib/python3.8/site-packages/airflow/providers/google/cloud/_internal_client/secret_manager_client.py", line 26, in <module>
2022-09-08T14:39:53.300920595Z     from airflow.providers.google.common.consts import CLIENT_INFO
2022-09-08T14:39:53.300926003Z   File "/usr/local/lib/python3.8/site-packages/airflow/providers/google/common/consts.py", line 23, in <module>
2022-09-08T14:39:53.300931078Z     CLIENT_INFO = ClientInfo(client_library_version='airflow_v' + version.version)
2022-09-08T14:39:53.300934596Z AttributeError: 'str' object has no attribute 'version'
....
```

### Operating System

ubuntu 22.04.1

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2022-09-08 16:05
Duplicate of https://github.com/apache/airflow/issues/26227 ?

**Comment by uranusjr** [comment] 2022-09-08 16:49
Yes, these are essntially reporting the exact same exception.

**Closed as completed** 2022-09-09 08:41 UTC
Labels: kind:bug, area:core, _eol_affected_version:2.4
