### ISSUE TITLE
Scheduler takes 100% of CPU without task execution

### ISSUE THREAD

**Issue by OliverPfau** [apache/airflow#13637] opened 2021-01-12 14:16 UTC
Hi,

running airflow 2.0.0 with python 3.6.9 the scheduler is consuming much CPU time without execution any task:

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
15758 oli       20   0   42252   3660   3124 R 100.0  0.0   0:00.06 top
16764 oli       20   0  590272  90648  15468 R 200.0  0.3   0:00.59 airflow schedul
16769 oli       20   0  588808  77236  13900 R 200.0  0.3   0:00.55 airflow schedul
    1 root      20   0    1088    548    516 S   0.0  0.0   0:13.28 init
   10 root      20   0     900     80     16 S   0.0  0.0   0:00.00 init

**Comment by gmontanola** [comment] 2021-01-13 12:39
I can confirm this too. Airflow 2.0.0 with Python3.8, KubernetesExecutor on EKS with Kubernetes 1.18

**m5.large node** and nothing but Airflow running (no task executions besides some tests)

![image](https://user-images.githubusercontent.com/35972814/104453292-f5083f80-5582-11eb-851f-c8ada92b8181.png)

I noticed the same thing while using Kind locally, but with Minikube it was ok! I'll test and come back with results just to be sure.

**Comment by kaxil** [comment] 2021-01-13 13:03
It will be fixed in 2.0.1 by default (it has always been the case -- even for 1.10.x), for now, you can change `[scheduler] min_file_process_interval = 1` or `2`.

**Closed as completed** 2021-01-14 13:08 UTC
Labels: kind:bug

**Comment by linxiaohui** [comment] 2021-03-05 01:55
Hi everypone， I am using apache-airflow 2.0.1 (using CeleryExecuor), an I have set `min_file_process_interval = 60`  and `parsing_processes = 2`.  But still the scheduler CPU using is very high. (according the `top` )

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND    
32057 root      20   0 1753140 121540  11728 R **138.7**  0.0   0:04.19 airflow schedul                                                                                                          
32093 root      20   0 1578452  61000   4812 R  **90.4**  0.0   0:02.73 airflow schedul  

any help? thanks a lot

**Comment by bobo333** [comment] 2021-05-03 03:31
hi, we (@yuzeh and I) are also seeing this behavior on airflow `2.0.2` using `LocalExecutor`. With `min_file_process_interval = 60` and `parsing_processes = 2` cpu usage for the scheduler is very similar to what @linxiaohui posted, both processes are using 90% or higher cpu, often up to 150%.

There are no active workloads running during this time either, those only run on the hour, but this behavior happens constantly.

**Comment by yuzeh** [comment] 2021-05-03 03:34
To add to @bobo333 's comment, here's the before + after on CPU utilization:

![image](https://user-images.githubusercontent.com/351023/116839049-a27c7e80-ab85-11eb-9c84-fd4150723456.png)

Other info about our deployment:
- Python 3.7
- Everything runs in docker-compose with a custom built docker image

**Comment by david30907d** [comment] 2021-06-05 02:56
hi, is there any update about this issue?
I'm using Airflow 2.1.0 with Python3.8 on k8s (celery executor), scheduler pod also consume like 90% of CPU resource as others mentioned above

**Comment by kaxil** [comment] 2021-07-01 23:39
@david30907d What are the values for the following?

 - `[scheduler] parsing_processes`
 - `[scheduler] min_file_process_interval`

And how much CPU is allocated to the Scheduler POD?

**Comment by sreeram004** [comment] 2021-07-24 12:18
I'm seeing same issue in Airflow 2.1.2. Any known fixes?

**Comment by fmv1992** [comment] 2021-08-03 17:14
We upgraded from `airflow` `1.10.15` to `2.0.2` and are experiencing this. @kaxil, configs:

*   `[scheduler] parsing_processes`: `2`.

*   `[scheduler] min_file_process_interval`: `60`.

**Comment by fmv1992** [comment] 2021-08-03 23:11
In our case we get n processes determined by `parsing_processes`. `top` gives:

```
airflow scheduler - DagFileProcessor /mydags/dag1.py
```

All of them with a super high CPU usage. I wonder what's that for. Is is "re-parsing" the DAGs to try to pick up updates in the code?

**Comment by fmv1992** [comment] 2021-08-04 15:46
Setting the following helped immensely:

```
[core]
min_serialized_dag_update_interval = 600
min_serialized_dag_fetch_interval = 300
[scheduler]
min_file_process_interval = 600
processor_poll_interval = 5
parsing_processes = 2
```

Some of these are suitable for our use case, I believe `min_file_process_interval = 600` might be the minimal required change.

**Comment by veinkr** [comment] 2022-03-28 16:12
Hi, It seems that the issue still exists.
I'm using Airflow 2.2.4 with Python3.9 on local,
`airflow scheduler - DagFileProcessor xxx.py` 
It show my `top ` every seconds with different pid , does it will create process every seconds?

My config is below.
```
[core]
min_serialized_dag_update_interval = 600
min_serialized_dag_fetch_interval = 300
[scheduler]
min_file_process_interval = 600
parsing_processes = 2
```

**Comment by DONDJJ** [comment] 2022-04-11 19:08
@[veinkr](https://github.com/veinkr)
@[kaxil](https://github.com/kaxil)

https://github.com/apache/airflow/blob/2400de2c5ece644cadb870baeea28907fa4dcf58/airflow/dag_processing/processor.py#L641

In my case the problem appears when there are syntax or import errors in dags. I fixed it by just commenting out this string. I don't know why, but every time I use log with "warning" and higher levels in DagFileProcessor class this issue occurs

I use airflow 2.2.4

**Comment by manosk88** [comment] 2022-06-17 13:53
Another way to mitigate this problem is done by limiting the CPU resource for the scheduler, according to this [doc](https://docs.docker.com/compose/compose-file/compose-file-v3/#resources).
E.g:
```
airflow-scheduler:
 deploy:
   resources:
     limits:
       cpus: '0.3'
```

**Comment by e-compagno** [comment] 2022-08-05 11:08
I experience the same issue of high schedule cpu usage with airflow 2.2.2. Settings are

```
min_file_process_interval = 30
min_serialized_dag_fetch_interval = 10
min_serialized_dag_update_interval = 30
min_file_process_interval = 30
parsing_processes = 2
```

**Comment by lexmiln** [comment] 2023-02-07 18:04
We also saw this 100% CPU issue in our kubernetes cluster.

We later observed that liveness checks on the scheduler pod were consistently timing out.

Manually running `time airflow jobs check` on the scheduler container (as the liveness probe does) showed that this command takes about a minute to run to completion with our configuration (500 mCPUs, 2GB RAM).

Given this, we increased the scheduler liveness probe timeout and interval. 

```
  scheduler:
    # The liveness probe takes a while to run on our cluster due to limited
    # resources, so we run it only very occasionally, and we give it lots of
    # time to complete.
    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 180
      failureThreshold: 5
      periodSeconds: 600
      command: ~
```

Since we made this change, the pod averages around 250mCPU utilisation (ie. 50% of its limit). A possible explanation for the CPU saturation that many are seeing is that the container is perpetually tied up trying to complete execution of the liveness probe in too short a window.
