### ISSUE TITLE
Setting up development environment for Airflow: Pyenv commands failed in macOS

### ISSUE THREAD

**Issue by Bowrna** [apache/airflow#19045] opened 2021-10-18 14:54 UTC
### Describe the issue with documentation

I am following the steps in this link to set up the breeze in my machine
https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst
Under the title `Installing airflow in the local virtual environment airflow-env with breeze.`

i am running the below command :
```$ ./breeze initialize-local-virtualenv --python 3.8```

I get the following error:
```(airflow-env) sathishkannan@Sathishs-MacBook-Air airflow % ./breeze initialize-local-virtualenv --python 3.8
Good version of docker 20.10.7.
Python version: 3.8

Initializing local virtualenv


   CI image.

   Branch name:             main
   Docker image:            ghcr.io/apache/airflow/main/ci/python3.8


   Airflow source version:  2.3.0.dev0
   Python version:          3.8
   Backend:                 mysql 5.7

./breeze: line 241: python3.8: command not found

ERROR: Initializing local virtualenv only works when you have virtualenv activated

Please enter your local virtualenv before (for example using 'pyenv activate' or 'workon')


ERROR: The previous step completed with error. Please take a look at output above
```

it says enter your local virtualenv. but i have my virtualenv activated. 

### How to solve the problem

I solved this issue by following the instruction in the below link:

https://github.com/pyenv/pyenv/issues/1948

It's a pyenv related issue in macOS. I tried the fix mentioned in the above link, which asks to add the below commands in ~/.zshrc file.

eval "$(pyenv init --path)"
eval "$(pyenv init -)"

Adding this information in docs, could be helpful for setting up the env in macOS

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2021-10-18 19:35
Also - following the discussion https://apache-airflow.slack.com/archives/CQ9QHSFQX/p1634550158070300 

It seems that we have a little "destructive" behaviour of "initialize-local-virtualenv" that could be corrected along the way.

Airflow, by default stores all "dynamically" generated stuff (logs, sqlite database, configuration) in `AIRFLOW_HOME` environment variable. If you do not happen to have `AIRFLOW_HOME` set, then it will fall-back to `${HOME}/airflow`.

While this is pretty reasonable for "user" installation, it might get very nasty during development,  when you happen to checkout SOURCES of AIrflow in ${HOME} dir - which might happen if you are "fresh" developer where you have not learned not to check-out your code directly in the HOME dir (this is kinda bad practice - a lof of tools does somewhat similar approach as airflow and it's all too-easy to get some nasty side effect):

```
cd ${HOME}
git checkout https://github.com/apache/airflow.git
```

Then you end up with sources of Airflow checked out to `${HOME}/airflow` - which is the very place where dynamic configuration/dbs/logs etc of Airflow are generated.

What's more - `initialize-virtualenv` command actually DELETES all the content of that "${AIRFLOW_HOME}" (it warns that it does it, but the warning might be easily not correlated with the fact that you have Airflow checked out in this directory.

I think Breeze should ERROR OUT if you try to run "initialize-virtualenv" and your checked out sources from where you run Breeze are in the directory about to be deleted. Moreover, I think Breeze shoudl also WARN the user always if the source code of airflow (And Breeze) is the same as ${AIRFLOW_HOME} - because this might lead to some unexpected behaviours if the dynamically generated content by airflow overrides some of the files in sources. We already have those auto-generated files mostly added to .gitignore, but this might not be sustainable in the future.

**Comment by Bowrna** [comment] 2021-10-20 07:12
https://github.com/apache/airflow/pull/19100

**Comment by eladkal** [comment] 2022-01-24 21:07
fixed by https://github.com/apache/airflow/issues/19045

**Closed as completed by eladkal** 2022-01-24 21:07 UTC
Labels: kind:bug, kind:documentation
