### ISSUE TITLE
Table View

### ISSUE THREAD

**Issue by alexhallam** [apache/airflow#21160] opened 2022-01-27 16:56 UTC
### Description

One of the main things we want to know is task durations. 

The main way I know how to get this is to hover over the `Gannt` chart or use the `Task Duration` chart. 

It would be nice to have the data that is in the `Gannt` chart or the `Task Duration` chat in a table view.

### Use case/motivation

That plots are making the data harder to find than a table alone.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2022-01-27 19:15
There is a new tree view coming in Airlfwow 2.3.0 It's already merged. Initial version of it can be seen here https://github.com/apache/airflow/pull/18675 but it already had gone through a number of iterations so it is even better than that. I guess it handles your request pretty nicely. I will close this one as duplicate but if you think your issue is not handled, feel free to comment here and explain.

**Comment by potiuk** [comment] 2022-01-27 19:15
Duplicate of #18675

**Closed as completed by potiuk** 2022-01-27 19:15 UTC
Labels: kind:feature, duplicate

**Comment by potiuk** [comment] 2022-01-27 19:16
Note - It is shown in "graphical" way not only as tooltip.

**Comment by alexhallam** [comment] 2022-01-27 19:19
That makes sense. 

I still think explicit tables would be nice so statistics show without needing to hover, but it is not a big enough issue to fuss about.

**Comment by potiuk** [comment] 2022-01-27 19:22
Maybe worth re-evaluation after 2.3.0 is released. When you see how it works and if you are unhappy about it, this might be re-requrested (but in the new context). I do believe the new "not-tree-view-any-more" might change a lot of user patterns there :)

**Comment by alexhallam** [comment] 2022-01-27 19:25
I agree!
