### ISSUE TITLE
SQLBranchOperator

### ISSUE THREAD

**Issue by jeffolsi** [apache/airflow#8525] opened 2020-04-23 07:59 UTC
Airflow has SQLSensor and PythonBranchOperator it seems that the logic of both can be combined to create SQLBranchOperator

SQLSenor knows to take single sql query and wait for condition on it. it can be copied and changed so that it won't wait (like sensor) but simply return true false. According to the value returned from the query it will follow the chosen branch.

**Comment by pujaji** [comment] 2020-05-01 10:14
Hey! I would like to work on this

**Comment by potiuk** [comment] 2020-05-01 10:29
Please do !

**Comment by samuelkhtu** [comment] 2020-05-12 22:45
> Hey! I would like to work on this

Hey @pujaji just wondering if you get a chance to work on this?

**Comment by samuelkhtu** [comment] 2020-05-12 22:58
Hi @potiuk , sorry to bother you.  I am just wondering what will be a good way to write unit tests for this type of SQL related operators? I looked at the existing unit test for MsSqlOperator and found that the unit test only initialize the MsSqlOperator and call the "get_hook()" method and assert on hook.__class__. 

Thanks.

**Comment by jeffolsi** [comment] 2020-05-13 19:12
I would assume that the tests should be similar to SQLSensor which already utilises various of databases options into single sensor.
The SQL part itself (taking query and run it) is the same between the SQLSensor and the SQLBranchOperator the difference comes after the query run and returned value.

**Comment by potiuk** [comment] 2020-05-13 19:22
Yep. Thanks @jeffolsi for the explanation. Yep. I think this is about right.

**Comment by samuelkhtu** [comment] 2020-05-13 19:23
Thanks @jeffolsi & @potiuk 

Since there are many SQL favors supported within Airflow, do you have a specific backend in mind? SQLite? Postgres? MySQL?  

Maybe you are thinking a generic SQL branch operator using ODBC hook instead?

**Comment by samuelkhtu** [comment] 2020-05-13 19:26
Thank you both!

**Comment by pujaji** [comment] 2020-05-13 20:00
> > Hey! I would like to work on this
> 
> Hey @pujaji just wondering if you get a chance to work on this?

Hello @samuelkhtu Please don't bother working on this. Please continue to finish this.
regards,
Puja

**Comment by samuelkhtu** [comment] 2020-05-13 20:45
Thanks @pujaji  , sounds like you've got this. I will circle back in a few days. Can't wait to see this new operator!

**Comment by pujaji** [comment] 2020-05-13 20:51
@samuelkhtu No Samuel You have got me wrong. I have stopped working on this. I urge you to accomplish this ans present this to the community

**Comment by samuelkhtu** [comment] 2020-05-13 20:52
Hi @pujaji , I am sorry I misunderstood you. Sounds good. I will give this a try!

**Comment by pujaji** [comment] 2020-05-13 20:53
No regrets! Happy coding-contributing!! :dagger:

**Comment by samuelkhtu** [comment] 2020-05-15 05:05
Hey @jeffolsi , quick question for you. In the existing Airflow Python Branching Operator, the python callback function will return the 'task_id' or list of 'tasl_ids' for selecting the branching to follow.

I am just wondering  if you would like to use the SQL query to select the branches as well?  

For example, the SQL query "SELECT 'branch_a', 'branch_b' will return 2 columns and the SQLBranchOperator will follow branch_a and branch_b. (branch_a and branch_b are task_ids within the DAG)

Or you expect the SQL query to return multiple rows, each row will represent the task_id within the DAG?

Thanks

**Comment by jeffolsi** [comment] 2020-05-15 12:22
@samuelkhtu the query return only true / false.
Think of the query as the equivalent of the python callable. The callable return only true false and with that the follow branch is decided.

I don't think it's a good idea to combine the task_id into the sql.

**Comment by samuelkhtu** [comment] 2020-05-15 13:09
Thank you @jeffolsi . I see. I guess what you are looking for is sightly different than the Python version. Yes, the SQL query can decide True/False but we still need to let the operator knows which "branch" or path you want to follow right?  How about the following?

`
BranchSqlOperator(
conn_id: str,
sql: str, 
parameters: Optional, 
follow_tasks_if_true: list, # list of task ids to follow if SQL return True,
follow_tasks_if_false: list, # list of task ids to follow if SQL return False
)
`

**Comment by jeffolsi** [comment] 2020-05-15 15:07
@samuelkhtu exactly what i was thinking about

**Comment by samuelkhtu** [comment] 2020-05-15 15:15
Great. Thank you @jeffolsi !

**Comment by samuelkhtu** [comment] 2020-05-21 04:26
Code and test completed for this item. I am working on the PR.

**Comment by samuelkhtu** [comment] 2020-05-22 16:31
Quick update. The PR is under review.

**Comment by samuelkhtu** [comment] 2020-05-26 16:34
Hi @potiuk , can you help and comment on a question raised by @eladkal in this PR? https://github.com/apache/airflow/pull/8942 

I believe this PR is ready to go otherwise. 

Thanks!

**Comment by samuelkhtu** [comment] 2020-06-01 18:24
Hello @jeffolsi , the new operator is in. Maybe we can close this issue?

**Comment by samuelkhtu** [comment] 2020-06-02 15:48
Hi @mik-laj , can you help and close this item? Thanks.

**Comment by potiuk** [comment] 2020-06-02 15:52
Closed. For the future - it's enough to add Closes #ISSUE in the commit message so that the issue is closed automatically on merge :)

**Closed as completed** 2020-06-02 15:51 UTC
Labels: kind:feature, good first issue

**Comment by samuelkhtu** [comment] 2020-06-02 16:09
Thank you for the tips!
