### ISSUE TITLE
DAG run fails when leaf node task is skipped.

### ISSUE THREAD

**Issue by Cricktom** [apache/airflow#32324] opened 2023-07-03 09:24 UTC
### Apache Airflow version

2.6.2

### What happened

I created a DAG with single task and forced that task to be skipped. In that case as per the Airflow documentation when the leaf node task get skipped, the DAG should be successful by default.

![image](https://github.com/apache/airflow/assets/19358003/da17c384-3d90-4c4a-bcd5-8aeb9e3c9c7a)

Ref: https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dag-run.html#dag-runs

But we didn't find the same behavior in our testing.
<img width="624" alt="Screenshot 2023-07-03 145013" src="https://github.com/apache/airflow/assets/19358003/6b301aaf-2d94-40e8-a9e4-c2f638c94a9f">

### What you think should happen instead

Instead of the DAG run failure it should have been success as per the documentation.

### How to reproduce

Create a DAG with the following code , which has single task and force it to get skip and this will cause the DAG run failure which is not expected.

```
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.exceptions import AirflowSkipException

def task_func():
    if True:
        raise AirflowSkipException


with DAG(dag_id="test_skip_task_dag",
         start_date=datetime(2022, 1, 1),
         schedule_interval='*/5 * * * 1-5',
         catchup=False,
         render_template_as_native_obj=True,
         dagrun_timeout=timedelta(minutes=4)
         ) as dag:

    task1 = PythonOperator(
        task_id='skip_task',
        python_callable=task_func
    )
```

### Operating System

Debian GNU/Linux 

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==3.2.0
apache-airflow-providers-common-sql==1.5.1
apache-airflow-providers-ftp==3.4.1
apache-airflow-providers-http==4.4.1
apache-airflow-providers-imap==3.2.1
apache-airflow-providers-sqlite==3.4.1

### Deployment

Docker-Compose

### Deployment details

We are using slim image for airflow 2.6.2: apache/airflow:slim-2.6.2-python3.9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment] 2023-07-03 10:06
DAG success is determined by the leaf task's states. What's your expectation here where the task is skipped? What state do you want the Dagrun to be in?

**Comment by Cricktom** [comment] 2023-07-03 10:13
@ephraimbuddy  It's not about the state which I want DAG run to be in. The expected state should be success as per the documentation and that's not happening in my case.

**Comment by Adaverse** [comment] 2023-07-03 10:43
I tried with the same code above; the DAG succeeded for the same Airflow version.

**Comment by ephraimbuddy** [comment] 2023-07-03 11:01
I tried in main and the dag succeeded too.

**Comment by ephraimbuddy** [comment] 2023-07-03 11:03
@Cricktom, we can't reproduce your issue with the dag you provided. Let us know if you have any other reproduction steps

**Comment by ephraimbuddy** [comment] 2023-07-04 05:39
Closing for now. Do let us know if there's a way to reproduce it

**Closed as completed by ephraimbuddy** 2023-07-04 05:39 UTC
Labels: kind:bug, Can't Reproduce, pending-response, area:core

**Comment by Cricktom** [comment] 2023-07-04 10:22
@ephraimbuddy  could you please suggest that what might be causing this? I am executing exactly the same DAG mentioned above but getting DAG run failure. Is there any configuration which can override this default behavior?
