### ISSUE TITLE
can not run celery worker with -D

### ISSUE THREAD

**Issue by zhegemingzimeibanquan** [apache/airflow#37811] opened 2024-03-01 07:05 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.0

### What happened?

when i run airflow celery worker -D,it reports a error on airflow-worker.err
but i am sure that zhe pid file is generated after i run the command
![Uploading image.png…]()

[2024-03-01 14:51:37 +0800] [21102] [INFO] Starting gunicorn 21.2.0
[2024-03-01 14:51:37 +0800] [21102] [INFO] Listening at: http://[::]:8793 (21102)
[2024-03-01 14:51:37 +0800] [21102] [INFO] Using worker: sync
[2024-03-01 14:51:37 +0800] [21103] [INFO] Booting worker with pid: 21103
[2024-03-01 14:51:37 +0800] [21104] [INFO] Booting worker with pid: 21104
ERROR: Pidfile (/home/idomp/airflow/conf/airflow-worker.pid) already exists.
Seems we're already running? (pid: 21101)
[2024-03-01 14:51:37 +0800] [21102] [INFO] Handling signal: term
[2024-03-01 14:51:37 +0800] [21104] [INFO] Worker exiting (pid: 21104)
[2024-03-01 14:51:37 +0800] [21103] [INFO] Worker exiting (pid: 21103)
[2024-03-01 14:51:38 +0800] [21102] [INFO] Shutting down: Master

### How to reproduce

source the virtualenv
run airflow celery worker -D

### Operating System

NAME="CentOS Linux" VERSION="7 (Core)" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (Core)" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:7" HOME_URL="https://www.centos.org/" BUG_REPORT_URL="https://bugs.centos.org/"  CENTOS_MANTISBT_PROJECT="CentOS-7" CENTOS_MANTISBT_PROJECT_VERSION="7" REDHAT_SUPPORT_PRODUCT="centos" REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment] 2024-03-01 08:43
Duplicate of:
- https://github.com/apache/airflow/issues/36541

Fixed by:
- https://github.com/apache/airflow/pull/36794

**Closed as completed by Taragolis** 2024-03-01 08:43 UTC
Labels: kind:bug, duplicate, area:core, needs-triage
