### ISSUE TITLE
DagBag import timeout errors not propagating to Airflow UI

### ISSUE THREAD

**Issue by RNHTTR** [apache/airflow#41979] opened 2024-09-03 15:37 UTC
### Apache Airflow version

2.10.0

### What happened?

When top-level DAG code causes a DagBag import timeout error, this will fail silently (from a DAG author's perspective -- it will fail in the DAG processor logs).

### What you think should happen instead?

An error banner should be shown in the Airflow UI.

### How to reproduce

```python
from datetime import datetime
from airflow.decorators import dag, task
from time import sleep

@dag(start_date=datetime(2023, 1, 1), max_active_runs=3, schedule=None, catchup=False)
def bad_practices_dag_1():

    sleep(40)

    @task
    def do_something():
        print(f"The meaning of life, the universe, and everything is... 42.")

    do_something()

bad_practices_dag_1()
```

### Operating System

n/a

### Deployment

Astronomer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2024-09-03 17:06
Duplicate of https://github.com/apache/airflow/issues/41976

**Comment by potiuk** [comment] 2024-09-03 17:06
Closing as duplicate

**Closed as completed by potiuk** 2024-09-03 17:06 UTC
Labels: kind:bug, duplicate, area:core, area:UI
