### ISSUE TITLE
Need alert for dag import error

### ISSUE THREAD

**Issue by rajeshdhanda** [apache/airflow#27089] opened 2022-10-17 09:20 UTC
### Description

dag import fails sometimes due to some changes in sys config, ignored rare case scenario. 
Need an alert on slack/mail whenever dag import fails. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2022-10-17 10:32
Duplicate of https://github.com/apache/airflow/issues/10968

**Closed as not planned by eladkal** 2022-10-17 10:32 UTC
Labels: kind:feature, duplicate

**Comment by potiuk** [comment] 2022-10-24 03:04
And my be fixed by https://github.com/apache/airflow/pull/26027 - it just needs fixing/rebasing/answering comments.

**Comment by potiuk** [comment] 2022-10-24 03:04
Feel free to comment [there](https://github.com/apache/airflow/pull/26027) @rajeshdhanda if you need this as well.
