### ISSUE TITLE
Add number to each dag in DAGs list page

### ISSUE THREAD

**Issue by tshrinivasan** [apache/airflow#11781] opened 2020-10-23 13:31 UTC
**Description**

The DAGs list page lists all the dags. It will be good to have "Number" as first column. 

**Use case / motivation**

We dont have any number displayed on the DAGs list page, to know how many dags are there.
It will be help to have a serial number as first column.

**Comment by madison-ookla** [comment] 2020-10-23 16:00
Are you running airflow with RBAC enabled? Because there is a count of all DAGs (and active vs paused) on the DAG list page:
![Screen Shot 2020-10-23 at 9 00 14 AM](https://user-images.githubusercontent.com/52679885/97026456-3eaa3680-150e-11eb-82fe-dbbf7eac45ea.png)

**Comment by tshrinivasan** [comment] 2020-10-23 16:05
This is nice.

It will be nice to see the serial number as the first column on the DAGs
list page.

It will be good to identify the DAGs and mention to others, when we have
the DAG names as alphanumeric characters only.

**Comment by madison-ookla** [comment] 2020-10-23 16:44
DAG IDs are currently the primary key for the DAG table, and I don't imagine that an additional serial will be added to the model definition as the alphanumeric name serves as the unique identifier: https://github.com/apache/airflow/blob/master/airflow/models/dag.py#L1970

**Comment by kurtqq** [comment] 2020-10-25 20:27
if the issue is only total number than you already have an answer in previous comments.
if you are after just numbing the dags i don't think i see the value of this. The numbing you will see is artificial in the UI - it will be based on ur current filtering, someone else will have different numbers to the same dags.

**Comment by ryw** [comment] 2020-10-27 15:22
Thanks for the suggestion @tshrinivasan - but I agree with others that we do have total # of DAGs in the UI, and adding a new column to the listing w/ an ordinal dag number doesn't add value, and we're already constrained for horizontal space in that view. Closing issue.

**Closed as completed by ryw** 2020-10-27 15:22 UTC
Labels: kind:feature

**Comment by tshrinivasan** [comment] 2020-10-27 15:43
Thanks all for the inputs. Agreeing with the current design.
