### ISSUE TITLE
max_active_runs ignored with externally triggered DAGs

### ISSUE THREAD

**Issue by easthy-alterpost** [apache/airflow#19344] opened 2021-11-01 09:38 UTC
### Apache Airflow version

2.1.4

### Operating System

Amazon Linux 2 AMI

### Deployment

Other

### Deployment details

Cloudformation template based on https://github.com/villasv/aws-airflow-stack/blob/v2/aws/cloud-formation-template.yml

### What happened

DAG can have multiple active runs despite of `max_active_runs` set to 1 when it is triggered externally from TriggerDagRunOperator

### What you expected to happen

If DAG has max_active_runs = 1 it should never be started more than once

### How to reproduce

DAG #1
```
with DAG('dag_1',
                default_args=default_args,
                max_active_runs=1,
                start_date=datetime(2021, 11, 1),
                schedule_interval="* * * * *",
                dagrun_timeout=timedelta(minutes=1),
                catchup=False) as dag:

    TriggerDagRunOperator(task_id='trigger_dag_2',
                                                          trigger_dag_id='dag_2')
```

DAG #2
```
from airflow.operators.bash import BashOperator

with DAG('dag_2',
                default_args=default_args,
                max_active_runs=1,
                start_date=datetime(2021, 11, 1),
                schedule_interval=None,
                dagrun_timeout=timedelta(minutes=10),
                catchup=False) as dag:

    BashOperator(
        task_id="dag_keeper",
        bash_command="sleep 5m"
    )
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bhavaniravi** [comment] 2021-11-01 12:11
Duplicate of #18583
This PR #18226 have fixed this

**Closed as completed** 2021-11-01 12:40 UTC
Labels: kind:bug, area:core
