### ISSUE TITLE
Grid view does not show running DAGs

### ISSUE THREAD

**Issue by AzeemIqbal** [apache/airflow#26629] opened 2022-09-23 12:19 UTC
### Apache Airflow version

2.4.0

### What happened

Upgraded airflow from 2.1.4 to 2.4.0, did airflow db upgrade, all seems to work ok
In the new grid view UI though, we don't seem to be able to see running DAGs in the default grid view (All run states)
Filtering for "Running" does show the DAG is actually running, with the latest DAGRun, I'm just wondering why it doesn't show for All run states, the DAG runs shown there are 1 run behind. 

### What you think should happen instead

Shows all DAG runs from latest backwards, as with old UI

### How to reproduce

Upgrade from 2.1.4 to 2.4 and look at grid view for DAGs that have been upgraded and have many runs over the past few years.

Not sure if one actually needs to upgrade airflow and db or if the bug is purely from 2.4 Grid view, probably the latter. 

### Operating System

Ubuntu 18.04.6 LTS (Bionic Beaver)

### Versions of Apache Airflow Providers

2.4 apache-airflow

### Deployment

Virtualenv installation

### Deployment details

AWS Ec2 running airflow using the pinned requirements files you have

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment] 2022-09-26 03:02
I think this is #26505. _Not showing running DAGs_ is inaccurate, they are simply put in the wrong order.

**Comment by ashb** [comment] 2022-09-26 12:58
Closing as a duplicate of #26505 -- please let us know if this is something else and we can re-open it!

**Closed as completed by ashb** 2022-09-26 12:58 UTC
Labels: kind:bug, area:UI, _eol_affected_version:2.4
