### ISSUE TITLE
Audit logs entry as clear event even if we click on the tasks.

### ISSUE THREAD

**Issue by sktemkar16** [apache/airflow#36119] opened 2023-12-08 01:16 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Whenever I click on the task, there is an entry added in the audit logs as task being cleared. This is misleading.
I want the report from the audit logs to check who cleared the tasks from the airflow ui.

Please let me know how to remove this logs. airflow versions - 2.6.1, 2.7.1

### What you think should happen instead

The audit logs should not add the entry as clear event by just clicking on the task in the airflow grid.

### How to reproduce

Click on any of the executed task in the airflow grid. Go to the audit logs and check the entries to find that it has created a clear event.

### Operating System

Linux

### Versions of Apache Airflow Providers

 2.6.1, 2.7.1

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment] 2023-12-20 20:33
I can confirm this "problem" and when I open the GRID view for example in `example_params_ui_tutorial` DAG and then select one task, two additional audit log entries are created:

369 	2023-12-20, 21:07:35 	[example_params_ui_tutorial](http://localhost:28080/dags/example_params_ui_tutorial/graph) 	show_params 	confirm 		admin 	Thor Adminstra 	[('dag_id', 'example_params_ui_tutorial'), ('dag_run_id', 'manual__2023-12-20T21:05:39+01:00'), ('past', 'false'), ('future', 'false'), ('upstream', 'false'), ('downstream', 'false'), ('state', 'success'), ('task_id', 'show_params')]

368 	2023-12-20, 21:07:35 	[example_params_ui_tutorial](http://localhost:28080/dags/example_params_ui_tutorial
/graph?execution_date=2023-12-20+20%3A05%3A39%2B00%3A00) 	show_params 	clear 	2023-12-20, 21:05:39 	admin 	Thor Adminstra 	[('dag_id', 'example_params_ui_tutorial'), ('dag_run_id', 'manual__2023-12-20T21:05:39+01:00'), ('confirmed', 'false'), ('execution_date', '2023-12-20T20:05:39+00:00'), ('past', 'false'), ('future', 'false'), ('upstream', 'false'), ('downstream', 'true'), ('recursive', 'true'), ('only_failed', 'false'), ('task_id', 'show_params')]

Tracing where it comes it seems the grid-UI calls POST http://server/clear and GET http://server/confirm?...

@bbovenzi Do you know where this is coming from in GRID view? I am a noob (still) in the UI development with Grid.

**Comment by Rafnel** [comment] 2024-01-02 15:38
My team has also found this issue in 2.6.3. It can definitely cause a scare when trying to figure out what happened in a DAG. Any updates here?

**Comment by sktemkar16** [comment] 2024-01-02 23:45
Yes, it is an issue for us, as we have thousands of DAG's and identifying who cleared the task is very difficult from the audit logs.
Please let me know if this can be fixed or if we have an alternate solution.

cheers!

**Comment by jscheffl** [comment] 2024-01-03 11:20
Thanks @Rafnel and @sktemkar16 to respond back. Apache Airflow is an open source project, most work consist out of volunteers and only a few "full paid" developers are maintaining. There is no SLA behind fixing bugs or working on it.

If you have a dependency on it feel free to contribute a fix - if you have a commercial interest also it would be fine to hire an consultant or get professional support to contribute a fix. This is how open source software is working. Don't expect people are jumping on all bugs "for free" non-paid.

**Comment by potiuk** [comment] 2024-01-03 11:26
Yep. Would be great if someone could take that issue and fix it  - seems it should be rather simple but to fix one someone debugs and finds the root cause.

**Comment by potiuk** [comment] 2024-01-03 11:26
So ... volunteers are welcome :)

**Comment by im-perativa** [comment] 2024-01-22 02:47
@potiuk submitted a PR that hopefully can fix this issue

**Comment by jscheffl** [comment] 2024-01-29 21:14
Fixed in #36941

**Closed as completed by jscheffl** 2024-01-29 21:14 UTC
Labels: kind:bug, good first issue, area:UI
