### ISSUE TITLE
Label in front of TaskGroup breaks task dependencies

### ISSUE THREAD

**Issue by cb149** [apache/airflow#17469] opened 2021-08-06 11:22 UTC
**Apache Airflow version**: 2.1.0

**What happened**:

Using a Label infront of a TaskGroup breaks task dependencies, as tasks before the TaskGroup will now point to the last task in the TaskGroup.

**What you expected to happen**:

Task dependencies with or without Labels should be the same (and preferably the Label should be visible outside of the TaskGroup).
Behavior without a Label is as follows:

```python
with TaskGroup("tg1", tooltip="Tasks related to task group") as tg1:
        DummyOperator(task_id="b") >> DummyOperator(task_id="c")

DummyOperator(task_id="a") >> tg1
```
![without Taskgroup](https://user-images.githubusercontent.com/35238779/128502690-58b31577-91d7-4b5c-b348-4779c9286958.png)

**How to reproduce it**:

```python
with TaskGroup("tg1", tooltip="Tasks related to task group") as tg1:
        DummyOperator(task_id="b") >> DummyOperator(task_id="c")

    DummyOperator(task_id="a") >> Label("testlabel") >> tg1
```
![with TaskGroup](https://user-images.githubusercontent.com/35238779/128502758-5252b7e7-7c30-424a-ac3a-3f9a99b0a805.png)

**Comment by bbovenzi** [comment] 2021-08-09 10:44
I was able to replicate. It seems to be an issue with selecting the wrong `target_id` for a label. It should pick the first one in a group but instead it picks the last one. 

[See here](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L398)

**Comment by kaxil** [comment] 2021-11-01 16:59
@bbovenzi Do we have a fix for this?

**Comment by ashb** [comment] 2022-04-27 17:28
We are having to revert the PR that fixes this, so re-opening this issue

**Comment by eladkal** [comment] 2022-05-04 07:37
@avkirilishin would you redo the PR ?

**Comment by eladkal** [comment] 2022-09-03 08:52
Issue status:
A PR was raised to fix the issue https://github.com/apache/airflow/pull/21404 but was reverted due to regression.
A unit test was added to catch the missed case in https://github.com/apache/airflow/pull/23300

If anyone wants to pick it up feel free to comment

**Closed as completed** 2023-02-18 17:57 UTC
Labels: kind:bug, area:webserver, good first issue, _eol_affected_version:2.1
