### ISSUE TITLE
Allow Pools to be set via ENV

### ISSUE THREAD

**Issue by fritz-astronomer** [apache/airflow#18582] opened 2021-09-28 19:21 UTC
### Description

As a system/airflow admin - I prefer being able to see all the various configurations of my instance, and being able to version and audit them. 

Pools are a very important subsystem in Airflow - however they are currently only configurable via the UI and CLI. 

I would like to be able to configure Pools via ENV variables, as I am able to with configuration settings, connections, and variables. 

Something like `AIRFLOW_POOL_DEFAULT_SIZE = 128`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by SamWheating** [comment] 2021-09-30 16:05
I like this idea, but I'm not sure how it would work as Pools are read _and updated_ by the Airflow scheduler, whereas configuration, connections and variables from environment variables are read-only.

Maybe we could have something on scheduler start-up which checks for `AIRFLOW__POOL_*` environment variables and creates / updates pool sizes accordingly?

I'd be happy to work on this, but I think I need to understand the requirements better first. Could you expand on which aspects of pool configuration you want to manage via environment variables?

**Comment by fritz-astronomer** [comment] 2021-09-30 16:08
I'd imagine that'd be it - @SamWheating . Create and update upon startup, would be enough for most use-cases that I can imagine. I imagine it would need to be semantically the same as with Vars / Connections set via the ENV (read-only, unable to modify? I've never actually tried to modify a Var that was set via the ENV)

**Comment by SamWheating** [comment] 2021-09-30 16:22
So we _can_ modify an env var, but the issue is that these changes aren't persisted anywhere and will be wiped or reset on a server or container restart, hence its not really a reliable place for long-lived read-write values. 

So assuming we're doing something like:

```
On every scheduler start-up, check the environment for env vars like `AIRFLOW_POOL_<POOL_NAME>=<size>`

For every match, create or update the specified pool to the given size
```

A few uncertainties come to mind:

1) Are we OK with the pool being left there once the env var is removed?

2) Are we OK with the pool being reset to the env-var configured size after being manually updated via the CLI or UI? (since we'd be treating environment variables as the higher-priority source of truth)

**Comment by thcidale0808** [comment] 2021-10-01 20:32
I'm happy to contribute with this one. Can this be assigned to me?

**Comment by uranusjr** [comment] 2021-10-03 06:45
Go ahead!

**Comment by potiuk** [comment] 2021-10-03 21:13
Yeah. That is an interesting one - I am not 100% sure whether this is a good idea to do it this way, to be honest.

Should it be done by scheduler ? Webservers ?  Which one, if we have multiple of those? I think there is no good answer to that - similarly as in case of adding new users, I think it should be kept outside of existing airflow components. I feel we are trying to put some band-aid where we need a better-thought solution.

Similarly as we do not feel comfortable about running migrations automatically when we start airflow components, modifying the pools at startup of the "regular" components sounds like a bit too magical. 

There are some issues with that which might be very counter-intuitive when we try to implement all the cases  - including deletion/incremental updates.

However maybe there is a better solution to that. 

Maybe that is the right moment that we think about a separate "airflow config-sync" (maybe better name could be invented) kind of component, wich could take care about configuring all DB-related configuration from a code:

* runing migrations
* creating users
* creating pools
* possibly updating Airlfow Variables/Connections from exported files 
* maybe we have some other DB-related config that could come from outside too

I think that could nicely solve a number of problems we have (and which we tried to solve different for a number of different use cases - differently in the "user-community" chart, differently in the "official" chart, diferently in 'quick-start docker compose" and differently in the image.

Instead of running "commands" that we have now (airflow db upgrade, airflow users create etc.) it could use files to store desired configuration state and it could do everythig that is needed to bring the configuration to the state that is describe in the files. 

It would  serve similar purpose as the `terraform "state"` description - this would make the approach of "infrastrucure as a code" much easier and more straightforward. We could run such "config-sync" and make airflow depend on it being "ready" or "complete" in order to run and replace the "post-install" step of ours in the Helm chart if we make proper dependency management between components - same in docker-compose.

I saw a number of questions from users who wanted to do it (and some of the features of the user-community chart implemented were responding to that - not in a best way as there was no good support from Airflow). 

And if we make such "config-sync" a first-class citizen in Airflow, we might address the need of our users in elegant and manageable way.

Just a thought - I'd love what you think about it.

**Comment by BasPH** [comment] 2021-10-04 19:34
@fritz-astronomer FWIW pools can also be imported from a json file: https://stackoverflow.com/a/69255203/3066428

IMO if we support configuration via env vars, we should either support everything or nothing, so I'd opt for having pools configurable via env vars since we support env vars for everything else too.

@potiuk (thinking out loud) I think there are many ways the user experience around configuration could improve. E.g. connections and variables set via env vars could be listed in the UI and we could periodically sync configuration to e.g. find discrepancies in configuration between instances. Several things in Airflow are already import-able using a json file. I don't have great experience with terraform state, but how about we extend the importing functionality to make all things import-able from one single json file? The config sync could be another API endpoint?

**Comment by potiuk** [comment] 2021-10-05 17:55
> @potiuk (thinking out loud) I think there are many ways the user experience around configuration could improve. E.g. connections and variables set via env vars could be listed in the UI and we could periodically sync configuration to e.g. find discrepancies in configuration between instances. Several things in Airflow are already import-able using a json file. I don't have great experience with terraform state, but how about we extend the importing functionality to make all things import-able from one single json file? The config sync could be another API endpoint?

Sounds like a good idea, especially that it might actually open up possibility for something much more interesting (not sure if we want that) - namely reloading configuration provided outside of the DB without restarting Airflow. It would not be possible for all parameters, but I think that might be a good opportunity to refactor the "conf" part and make it truly independent from other parts of Airflow. Right now we have those nasty loops `conf -> models -> settings -> conf` which are creating all kinds of problems (for example cyclic imports when initializing secret backends). I'd very much support rewriting this part.

**Comment by BasPH** [comment] 2021-10-06 08:45
Yes; I always liked this hot reload functionality of Prometheus: https://prometheus.io/docs/prometheus/latest/configuration/configuration/. +1 for rewriting the configuration, it has other nasty problems e.g. https://github.com/apache/airflow/issues/8255

**Comment by thcidale0808** [comment] 2021-10-13 21:00
@fritz-astronomer are you happy with the scope/assumptions raised by @SamWheating here: https://github.com/apache/airflow/issues/18582#issuecomment-931473731 ?

**Comment by fritz-astronomer** [comment] 2021-10-13 21:02
Yea @thcidale0808 - I imagine that would fit the needs of the individuals I've talked to with this. The ENV does it's best to ADD or UPDATE pools. Users will be made aware that pools (like connections and variables) can also come from many sources, and if the env disappears, then it's on the user to remove the pool (which also doesn't feel like the worst "failure state" to me?)

**Comment by eladkal** [comment] 2022-02-11 08:31
PR: https://github.com/apache/airflow/pull/21223

**Comment by potiuk** [comment] 2022-02-15 22:50
Adding whole functionality of syncing env/state/db in case it can be replaced with 
```
airlfow pools import <file>
```
is a hard no for me.,

**Closed as completed by potiuk** 2022-02-15 22:50 UTC
Labels: kind:feature
