### ISSUE TITLE
Airflow v2.0.0b1 package doesnt include "api_connexion/exceptions"

### ISSUE THREAD

**Issue by anirudhbagri** [apache/airflow#12239] opened 2020-11-10 10:28 UTC
**Apache Airflow version**: 2.0.0b1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): NA

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): macOS
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Installed apache-airlfow==2.0.0b1 using pip. 
Running `airflow webserver` gave the following error:
```
Traceback (most recent call last):
  File "/Users/abagri/Workspace/service-workflows/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/Users/abagri/Workspace/service-workflows/venv/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/Users/abagri/Workspace/service-workflows/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 49, in command
    func = import_string(import_path)
  File "/Users/abagri/Workspace/service-workflows/venv/lib/python3.8/site-packages/airflow/utils/module_loading.py", line 32, in import_string
    module = import_module(module_path)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abagri/Workspace/service-workflows/venv/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 43, in <module>
    from airflow.www.app import cached_app, create_app
  File "/Users/abagri/Workspace/service-workflows/venv/lib/python3.8/site-packages/airflow/www/app.py", line 39, in <module>
    from airflow.www.extensions.init_views import (
  File "/Users/abagri/Workspace/service-workflows/venv/lib/python3.8/site-packages/airflow/www/extensions/init_views.py", line 25, in <module>
    from airflow.api_connexion.exceptions import common_error_handler
ModuleNotFoundError: No module named 'airflow.api_connexion.exceptions'
```

**What you expected to happen**:
Expect this command to start the webserver

**How to reproduce it**:
Install a fresh version of airflow, run `airflow db init` followed by `airflow webserver`

**Anything else we need to know**:

**Comment by potiuk** [comment] 2020-11-10 10:33
cc: @ashb @kaxil  -> looking at it

**Comment by anirudhbagri** [comment] 2020-11-10 10:36
I downloaded the packages externally from (here)[https://pypi.org/project/apache-airflow/2.0.0b1/#files], this one also doesn't contain anything except the `openapi` folder.

**Comment by kaxil** [comment] 2020-11-10 10:38
> I downloaded the packages externally from [here](https://pypi.org/project/apache-airflow/2.0.0b1/#files), this one also doesn't contain anything except the `openapi` folder.

What command did you run? `pip install apache-airflow==2.0.0b1` or did you download the tar.gz and run `pip install FILEPATH_TO_TAR`

**Comment by anirudhbagri** [comment] 2020-11-10 10:40
I first ran `pip install apache-airflow==2.0.0b1` and ran the command to get those errors.

Then to confirm, I downloaded the tar to check the contents. (didn't install the tar)

**Comment by potiuk** [comment] 2020-11-10 10:41
@ashb @kaxil -> indeed the problem is with implicit packages. The root cause is that `api_connexion` has no `__init__.py`

**Comment by kaxil** [comment] 2020-11-10 10:42
aah, we just need to add `__init__.py` file then, wonder why and how it got deleted / missing

**Comment by potiuk** [comment] 2020-11-10 10:44
It was never there - but the change with implicit packages, changed `find_namespace_packages` into `find_packages`

**Comment by kaxil** [comment] 2020-11-10 10:44
It was there, it got renamed here: https://github.com/apache/airflow/commit/b2a28d1590410630d66966aa1f2b2a049a8c3b32 / https://github.com/apache/airflow/pull/12082

**Comment by potiuk** [comment] 2020-11-10 10:46
AAAAAH Github rebase magic finding wrong files!

**Comment by potiuk** [comment] 2020-11-10 10:46
Bad me!

**Comment by potiuk** [comment] 2020-11-10 10:47
Sounds like b2 then

**Comment by ashb** [comment] 2020-11-10 10:48
@potiuk https://github.com/apache/airflow/pull/12082/files#r518885540

You also resolved this discussion of mine. This file rename was the cause of that problem.

**Comment by kaxil** [comment] 2020-11-10 10:48
Yeah, let's cut out beta2 today itself

**Comment by anirudhbagri** [comment] 2020-11-10 10:48
b2? :(

**Comment by ashb** [comment] 2020-11-10 10:50
Fix coming.

**Comment by potiuk** [comment] 2020-11-10 10:50
> @potiuk https://github.com/apache/airflow/pull/12082/files#r518885540
> 
> You also resolved this discussion of mine. This file rename was the cause of that problem.

Yep. Entirely my fault

**Comment by ashb** [comment] 2020-11-10 10:52
I missed it too! It happens, we're just unlucky in the timing

**Comment by kaxil** [comment] 2020-11-10 10:52
None of our tests caught it :(

**Comment by ashb** [comment] 2020-11-10 10:54
Our tests almost entirely operate on an "editable" install is why :(

**Comment by ashb** [comment] 2020-11-10 10:54
I'm going to rename Beta2 milestone to Beta3 (etc).

**Comment by potiuk** [comment] 2020-11-10 10:56
> Our tests almost entirely operate on an "editable" install is why :(

That's the next step we discussed with Ash that production image should also be build using packages/wheels. I will add it before beta. it will be rather impossible for CI, but since we have k8s test using the production image and it uses both - scheduler and webserver  it will be a very good test.

**Comment by potiuk** [comment] 2020-11-10 10:57
I also merged #12231  and will double test it now - also we can release sendgrid 1.0.0b2

**Comment by potiuk** [comment] 2020-11-10 10:59
The extras work perfectly from local installation now.

**Comment by potiuk** [comment] 2020-11-10 11:00
```
pip install ".[kubernetes]"

...

Collecting apache-airflow-providers-cncf-kubernetes; extra == "kubernetes"
  Downloading apache_airflow_providers_cncf_kubernetes-1.0.0b1-py3-none-any.whl (32 kB)
...
```

**Comment by ashb** [comment] 2020-11-10 11:00
Sendgrid we can do as a 1.0.0b1 on it's own. I'll do that right now.

**Comment by anirudhbagri** [comment] 2020-11-10 11:04
Although I get that `__init__.py` file was not present in the folder, why did `openapi` folder got into the package?
was it because `openapi` did not have `__init__.py` whereas `endpoints` and `schema` had `__init__.py` inside them?

**Comment by ashb** [comment] 2020-11-10 11:06
```
apache-airflow-2.0.0b1/airflow/api_connexion/
apache-airflow-2.0.0b1/airflow/api_connexion/openapi/
apache-airflow-2.0.0b1/airflow/api_connexion/openapi/v1.yaml
```

That is there because datafiles are included via a different mechanism to code files.

**Comment by kaxil** [comment] 2020-11-10 11:07
Yeah we include openapi files:

https://github.com/apache/airflow/blob/5912d0cae7033b3e2549280677dd60faa53be5e7/MANIFEST.in#L33
https://github.com/apache/airflow/blob/5912d0cae7033b3e2549280677dd60faa53be5e7/setup.py#L916

**Comment by anirudhbagri** [comment] 2020-11-10 11:08
Oh, Got it. (y). Thank you!

**Closed as completed** 2020-11-10 11:26 UTC
Labels: kind:bug

**Comment by ashb** [comment] 2020-11-10 13:06
Beta 2 had been pushed to pypi
