### ISSUE TITLE
Publish a container's port(s) to the host with DockerOperator

### ISSUE THREAD

**Issue by AndreGodinho7** [apache/airflow#27290] opened 2022-10-26 07:56 UTC
### Description

[`create_container` method](https://github.com/docker/docker-py/blob/bc0a5fbacd7617fd338d121adca61600fc70d221/docker/api/container.py#L370) has a `ports` param to open inside the container, and the `host_config` to [declare port bindings](https://github.com/docker/docker-py/blob/bc0a5fbacd7617fd338d121adca61600fc70d221/docker/api/container.py#L542). 

We can learn from [Expose port using DockerOperator](https://stackoverflow.com/questions/65157416/expose-port-using-dockeroperator) for this feature on DockerOperator. I have already tested it and works, also created a custom docker decorator based on this DockerOperator extension. 

### Use case/motivation

I would like to publish the container's port(s) that is created with DockerOperator to the host. These changes should also be applied to the Docker decorator.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2022-10-26 11:40
If you have a code suggestion you can always open a PR now need to submit issue first.
Assigned this issue to you

**Comment by eladkal** [comment] 2023-02-06 15:06
@AndreGodinho7 will you open a PR?

**Comment by 1995parham** [comment] 2023-03-22 07:39
Dear @eladkal, we can work on this if the issue is still unassign.

**Comment by Bowrna** [comment] 2023-03-22 07:58
@1995parham @eladkal i have been working on this issue and forgot to update here. i hope i will complete this weekend.

**Comment by 1995parham** [comment] 2023-03-22 08:12
Great :raised_hands:

**Comment by Bowrna** [comment] 2023-04-13 10:16
i will commit the changes done by this weekend and close it. Sorry for the delay in my end.

**Closed as completed** 2023-05-17 09:03 UTC
Labels: area:providers, kind:feature, good first issue, provider:docker
