### ISSUE TITLE
KPO ERROR - The conn_id `kubernetes_default` isn't defined

### ISSUE THREAD

**Issue by Santhin** [apache/airflow#31245] opened 2023-05-12 09:18 UTC
### Apache Airflow version

2.6.0

### What happened

After upgrading from 2.5.1 to 2.6.0, my dag stopped working 
```python
from pendulum import datetime, duration
from airflow import DAG
from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import (
    KubernetesPodOperator,
)

default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "start_date": datetime(2022, 1, 1),
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 1,
    "retry_delay": duration(minutes=5),
}

with DAG(
    dag_id="example_kubernetes_pod", schedule="@once", default_args=default_args
) as dag:
    k = KubernetesPodOperator(
        namespace="change_me",
        image="hello-world",
        name="airflow-test-pod",
        task_id="task-one",
        in_cluster=True,  # if set to true, will look in the cluster, if false, looks for file
        is_delete_operator_pod=True,
        get_logs=True,
    )
```

Error log
```log
[2023-05-12, 09:13:56 UTC] {pod.py:905} ERROR - The conn_id `kubernetes_default` isn't defined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 533, in execute_sync
    self.pod_request_obj = self.build_pod_request_obj(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 859, in build_pod_request_obj
    "airflow_kpo_in_cluster": str(self.hook.is_in_cluster),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 249, in is_in_cluster
    self.api_client  # so we can determine if we are in_cluster or not
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 257, in api_client
    return self.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 171, in get_conn
    in_cluster = self._coalesce_param(self.in_cluster, self._get_field("in_cluster"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 164, in _get_field
    if field_name in self.conn_extras:
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 147, in conn_extras
    connection = self.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `kubernetes_default` isn't defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 745, in patch_already_checked
    self.client.patch_namespaced_pod(
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 473, in client
    return self.hook.core_v1_client
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 261, in core_v1_client
    return client.CoreV1Api(api_client=self.api_client)
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 257, in api_client
    return self.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 171, in get_conn
    in_cluster = self._coalesce_param(self.in_cluster, self._get_field("in_cluster"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 164, in _get_field
    if field_name in self.conn_extras:
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 147, in conn_extras
    connection = self.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `kubernetes_default` isn't defined
[2023-05-12, 09:13:56 UTC] {taskinstance.py:811} DEBUG - Refreshing TaskInstance <TaskInstance: example_kubernetes_pod.task-one manual__2023-05-12T09:07:33.095624+00:00 [running]> from DB
[2023-05-12, 09:13:56 UTC] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 533, in execute_sync
    self.pod_request_obj = self.build_pod_request_obj(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 859, in build_pod_request_obj
    "airflow_kpo_in_cluster": str(self.hook.is_in_cluster),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 249, in is_in_cluster
    self.api_client  # so we can determine if we are in_cluster or not
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 257, in api_client
    return self.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 171, in get_conn
    in_cluster = self._coalesce_param(self.in_cluster, self._get_field("in_cluster"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 164, in _get_field
    if field_name in self.conn_extras:
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 147, in conn_extras
    connection = self.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `kubernetes_default` isn't defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 529, in execute
    return self.execute_sync(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 559, in execute_sync
    self.cleanup(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 704, in cleanup
    raise AirflowException(
airflow.exceptions.AirflowException: Pod None returned a failure:
remote_pod: None
```

### How to reproduce

Run my example dag on version 2.5.1 and 2.6.0

### Operating System

k8s

### Versions of Apache Airflow Providers

vanilla image 2.6.0-python3.8

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Airflow deployed with helm on namespace `change_me`
- chart version`1.9.0` 
- app version `2.5.3`

values
```yaml
# Airflow version (Used to make some decisions based on Airflow Version being deployed)
airflowVersion: "2.6.0"

# Airflow executor
executor: "KubernetesExecutor"

images:
  airflow:
    repository: apache/airflow
    tag: 2.6.0-python3.8
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2023-05-12 09:45
> After upgrading from 2.5.1 to 2.6.0, my dag stopped working

this is not a bug. When you update Airflow you need also look into depended packages. Depended packages can have breaking changes. in your case` cncf.kubernetes` had a major release with a breaking change. see the change log:
https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/index.html#id2

however to make things smother we added a fallback https://github.com/apache/airflow/pull/31187
it will be released in next provider cycle.

**Closed as not planned by eladkal** 2023-05-12 09:45 UTC
Labels: kind:bug, area:core, needs-triage
