### ISSUE TITLE
Can no longer pass a partial as callback in Airflow 2.10

### ISSUE THREAD

**Issue by jrderuiter** [apache/airflow#42032] opened 2024-09-05 14:24 UTC
### Apache Airflow version

2.10.0

### What happened?

Passing a partial from `functools.partial` to `on_success_callback` or `on_failure_callback` (either at the task or DAG level) results in the following error:

```
[2024-09-05, 14:15:02 UTC] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_callback_partial, task_id=hello_world, run_id=manual__2024-09-05T14:15:00.758095+00:00, execution_date=20240905T141500, start_date=20240905T141502, end_date=20240905T141502
[2024-09-05, 14:15:02 UTC] {standard_task_runner.py:124} ERROR - Failed to execute job 145 for task hello_world ('functools.partial' object has no attribute '__name__'; 53)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 358, in _run_raw_task
    _run_finished_callback(callbacks=ti.task.on_success_callback, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1554, in _run_finished_callback
    log.info("Executing %s callback", callback.__name__)
AttributeError: 'functools.partial' object has no attribute '__name__'. Did you mean: '__ne__'?
[2024-09-05, 14:15:02 UTC] {local_task_job_runner.py:261} INFO - Task exited with return code 1
``` 

### What you think should happen instead?

In previous versions of Airflow this worked fine and the partial was executed as any other function. 

The issue was likely introduced by changes to the task instance code which now tries to access `__name__` on the callback function, which doesn't exist in the case of a `partial` object:

```
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 358, in _run_raw_task
    _run_finished_callback(callbacks=ti.task.on_success_callback, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1554, in _run_finished_callback
    log.info("Executing %s callback", callback.__name__)
```

This code should probably be updated to fallback to use something other than `__name__` if the attribute doesn't exist.

### How to reproduce

The issue can be reproduced by running the following example in Airflow 2.10:

```python
from functools import partial

from airflow import DAG
from airflow.operators.python import PythonOperator
import pendulum


def _hello_world():
    print("Hello world!")


def _callback(status: str):
    print(f"Task finished with status: {status}")


with DAG(
    dag_id="test_callback_partial",
    schedule=None,
    start_date=pendulum.yesterday(),
) as dag:
    PythonOperator(
        task_id="hello_world", 
        python_callable=_hello_world,
        on_success_callback=[partial(_callback, status="success")],
        on_failure_callback=[partial(_callback, status="failure")]
    )
```

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Docker-Compose

### Deployment details

Deployed (for local development) via the default docker-compose setup of Airflow.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2024-09-05 14:37
duplicate of https://github.com/apache/airflow/issues/41563. Can you please @jrderuiter check it in the upcoming 2.10.1rc1 and report in [Status of testing of 2.10.1rc1](https://github.com/apache/airflow/issues/41956). Confirmation that the issue is fixed there will be much appreciated.

**Closed as completed by potiuk** 2024-09-05 14:37 UTC
Labels: kind:bug, duplicate, area:core, needs-triage
