### ISSUE TITLE
Airflow standalone command does not exit gracefully

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#19260] opened 2021-10-27 16:34 UTC
### Apache Airflow version

2.2.0 (latest released)

### Operating System

macOS

### Deployment

Virtualenv installation

### What happened

run `airflow standalone`

enter `ctrl+c`

hangs here:

```
webserver | 127.0.0.1 - - [27/Oct/2021:09:30:57 -0700] "GET /static/pin_32.png HTTP/1.1" 304 0 "http://localhost:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
^Cstandalone | Shutting down components
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2022-06-11 14:26
Seems that the fix was not effective and broke Triggerer job killing: https://github.com/apache/airflow/pull/23274#issuecomment-1148818199 

Reverting it, until we find a better fix (or wait fo python to fix it).

**Comment by dstandish** [comment] 2022-06-13 16:50
Ok @potiuk maybe we should just reopen and merge https://github.com/apache/airflow/pull/23271?

**Comment by potiuk** [comment] 2022-06-13 17:31
I think there is a PR opened - or maybe just merged about it.

**Comment by potiuk** [comment] 2022-07-14 12:17
I am not sure what has changed - but I cannot reproduce it any more @dstandish - if you can't as well, I propose to close it.

**Comment by SergiyKolesnikov** [comment] 2023-03-23 00:11
@potiuk I can still reproduce it with Airflow 2.5.2. Standalone hangs after Ctrl+C.

**Comment by potiuk** [comment] 2023-03-26 20:33
Yes woudl be nice if somoene diagnoses and fixes it. Maybe you @SergiyKolesnikov ?

**Comment by SergiyKolesnikov** [comment] 2023-07-07 10:20
I have looked at the running processes after hitting Ctrl-C. The webserver and scheduler processes were killed successfully, but the airflow triggerer process was still running. After I manually killed the triggerer process with `kill PID` the standalone command terminated normally.

I have also tested Airflow v2.6.2 and with this version Ctrl-C terminates the standalone command normally without any problems.

**Comment by potiuk** [comment] 2023-07-07 14:51
So I guess we should close that one.

**Closed as completed by potiuk** 2023-07-07 14:51 UTC
Labels: kind:bug, area:core

**Comment by DannyLee12** [comment] 2023-08-21 14:21
I have this issue on 2.6.3. FWIW.

**Comment by potiuk** [comment] 2023-08-22 18:49
So I heartily encourage you to post a new issue with all the details. commenting on a closed issue does not move a needle. And likely your issue @DannyLee12 is similar but not necessarily the same. 

Posting and issue with clear reproduction steps and logs showing the problem is the best way you can help those who would look at it to reproduce and maybe fix it. 

On the other hand, commenting on a closed issuse that apparently have been closed without providing all those details does not help anyone in diagnosing and fixing the issue.

I heartily encourage you to open a new issue and provide as much details and reproducible steps as you can.
