### ISSUE TITLE
DAGs are missing and deleted in Airflow 2.10.1

### ISSUE THREAD

**Issue by ldacey** [apache/airflow#42111] opened 2024-09-09 14:33 UTC
### Apache Airflow version

2.10.0

### If "Other Airflow 2 version" selected, which one?

2.10.1

### What happened?

I updated to Airflow 2.10.1 and the DAGs in my UI started to disappear. I checked the scheduler logs and it showed that the DAGs were not being found and were being deleted. I quickly reverted back to the working 2.10.0 image after that and I don't have the specific logs.

I am syncing the src folder in my repo as the dags_folder which also contains common scripts, hooks, operators, etc. The plugins_folder is backed into the image and only contains things which don't change often, like XCom backend.

Official Helm chart values:
```
config:
  core:
    dags_folder: /opt/airflow/dags/repo/src
    plugins_folder: /opt/airflow/plugins

dags:
  gitSync:
    enabled: true
    repo: https://gitlab.domain.com/dags.git
    branch: main
    rev: HEAD
    depth: 1
    subPath: src
```

This is my dags_folder structure:

```
src/
├── common
│   ├── __init__,py
├── dags
│   ├── __init__.py
│   ├── account_a
│   │   ├── example_a_dag.py
│   │   └── example_b_dag.py
│   └── account_x
├── hooks
│   ├── __init__.py
├── notifiers
│   ├── __init__.py
├── operators
│   ├── __init__.py
├── projects
│   ├── __init__.py
│   ├── account_a
│   │   ├── transform.py
│   │   └── schemas.py
│   └── account_x
└── sensors
    ├── __init__.py
```

My .airflowignore is in the src folder:

```
common/
notifiers/
operators/
sensors/
hooks/
projects/
```

### What you think should happen instead?

The DAGs should still be discovered between minor Airflow releases since nothing else changed.

### How to reproduce

Hopefully the structure of my setup above suffices.

I am using the Airflow constraints file when installing extras. linux/amd64 is the target platform used and 2.10.1 is the Airflow version I had trouble with.

```
    - docker build
      --file Dockerfile
      --pull
      --platform "${TARGET_PLATFORM}"
      --cache-from "${RELEASE_IMAGE}"
      --build-arg BUILDKIT_INLINE_CACHE=1
      --build-arg PYTHON_BASE_IMAGE="python:${PYTHON_VERSION}-slim-${DEBIAN_VERSION}"
      --build-arg AIRFLOW_VERSION="${AIRFLOW_VERSION}"
      --build-arg AIRFLOW_USE_UV="true"
      --build-arg AIRFLOW_UV_VERSION="${AIRFLOW_UV_VERSION}"
      --build-arg AIRFLOW_EXTRAS="async,docker,cncf.kubernetes,ftp,google,google_auth,http,microsoft.azure,odbc,postgres,sftp,ssh,statsd,openlineage"
      --build-arg AIRFLOW_CONSTRAINTS_REFERENCE="${CONSTRAINTS_VERSION}"
      --build-arg INSTALL_MYSQL_CLIENT="false"
      --build-arg INSTALL_MSSQL_CLIENT="true"
      --build-arg INSTALL_POSTGRES_CLIENT="true"
      --build-arg UPGRADE_TO_NEWER_DEPENDENCIES="true"
      --build-arg ADDITIONAL_RUNTIME_APT_DEPS="git graphviz procps vim odbc-postgresql python3-pybind11 python3-pyodbc libgeos-dev"
      --tag "${RELEASE_IMAGE}"
      "."
```

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jcrobak** [comment] 2024-09-09 14:37
I'm experiencing this issue with 2.10.1, too. I was able to add some logging and it appears that https://github.com/apache/airflow/pull/41433 is the culprit. If the value of `airflow config get-value core dags_folder` is a symlink, then the parameter `dag_directory` to `deactivate_stale_dags` will be the target of the symlink. This means that `os.path.commonpath(...)` doesn't find a match.

**Comment by potiuk** [comment] 2024-09-09 14:43
> I'm experiencing this issue with 2.10.1, too. I was able to add some logging and it appears that https://github.com/apache/airflow/pull/41433 is the culprit. If the value of airflow config get-value core dags_folder is a symlink, then the parameter dag_directory to deactivate_stale_dags will be the target of the symlink. This means that os.path.commonpath(...) doesn't find a match.

Ah yeah . That would definitely explain it !

**Comment by potiuk** [comment] 2024-09-09 14:43
cc: @utkarsharma2 -> I think we need a quick 2.10.2

**Comment by MCubek** [comment] 2024-09-09 14:50
Also experiencing this issue with 2.10.1 instance deployed with the helm chart and using gitsync. 
Symptoms include dags going missing while refreshing webserver ui and then, being unable to trigger dag runs and kubernetes executor task faults.
Webserver reported params missing in its stack trace, and the webserver ui reporting dags missing from dag bag when browsing running dags.

I have since reverted back to 2.10.0 after the issues my deployment experienced during the weekend, but will reproduce and send the full error logs if necessary.

**Comment by potiuk** [comment] 2024-09-09 14:52
The symlink is the most likely cause I think we will take it from there (thanks @MCubek @jcrobak ) - I think it will mean quic 2.10.2 - so we will appreciate -once we fix it, if you test release candidates we will produce.

**Comment by ephraimbuddy** [comment] 2024-09-09 14:58
> cc: @utkarsharma2 @ephraimbuddy -> I think we need a quick 2.10.2

Yeah. Looking into this

**Comment by jcrobak** [comment] 2024-09-09 15:26
here's a quick repro with docker-compose, in case you need it:

```
curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.10.1/docker-compose.yaml' 

sed -e '/\/opt\/airflow\/dags/ s/^#*/#/' < docker-compose.yaml

mkdir -p ./dags ./logs ./plugins ./config
echo -e "AIRFLOW_UID=$(id -u)" >| .env 

mkdir dags/example

cat << EOF >>| dags/example/airflow_dag.py
from datetime import datetime, timedelta

from airflow.models.dag import DAG
from airflow.operators.bash import BashOperator

with DAG(
    "joe-tutorial",
    description="A simple tutorial DAG",
    schedule=timedelta(days=1),
    start_date=datetime(2021, 1, 1),
    catchup=False,
    tags=["example"],
) as dag:
            t1 = BashOperator(
        task_id="print_date",
        bash_command="date",
    )

EOF


cat << EOF >> Dockerfile
FROM apache/airflow:2.10.1-python3.12
COPY --chown=airflow:root dags /opt/dags
RUN rmdir /opt/airflow/dags && ln -s /opt/dags/ /opt/airflow/dags

EOF


docker build . -t airflow:2.10.1-repro
echo -e "AIRFLOW_IMAGE_NAME=airflow:2.10.1-repro" >> .env 


docker-compose up
```

eventually you'll see a log line like:

```
airflow-scheduler-1  | [2024-09-09T15:23:14.923+0000] {manager.py:548} INFO - DAG joe-tutorial is missing and will be deactivated.
airflow-scheduler-1  | [2024-09-09T15:23:14.927+0000] {manager.py:560} INFO - Deactivated 1 DAGs which are no longer present in file.
airflow-scheduler-1  | [2024-09-09T15:23:14.933+0000] {manager.py:564} INFO - Deleted DAG joe-tutorial in serialized_dag table
```

**Comment by raphaelauv** [comment] 2024-09-09 15:47
same experience with 2.10.1 and 1 dagprocessor

[Screencast from 09-09-2024 17:43:19.webm](https://github.com/user-attachments/assets/a36e5f0b-a976-4dfa-801d-ebc5f2e350dd)

**Comment by kand617** [comment] 2024-09-09 16:52
I recently upgraded to 2.8 and am seeing a similar thing. 
DAG count suddenly goes to 0 and then slowly builds back up... Then after sometime back to 0...
Was just going to upgrade to 2.10 thinking it maybe better.

**Comment by zachliu** [comment] 2024-09-09 16:53
Just upgraded from 2.9.3 to 2.10.1

In my case (not using `gitSync`, DAG files are synced to a persisted EFS volume using the `rsync` cmd), DAGs are just disappearing from the UI. I haven't seen the "Deleted" logs...yet

**Comment by rflaquer-w2m** [comment] 2024-09-10 09:17
Same problem here. We were just doing the environment upgrade in PRO, two weeks ago we did it in PRE without problems. Then I saw that the process installed 2.10.1 instead of 2.10 and thank goodness I found this ticket. I forced the reinstallation of Airflow 2.10 and with that I have corrected the error:

pip install --force-reinstall -v "apache-airflow==2.10"

**Comment by banachkx** [comment] 2024-09-10 11:58
I think we have a similar problem at 2.10 - we did an upgrade to 2.10 on Friday. At some point after reloading the UI the dags disappeared. I rebuilt the whole docker from scratch, the whole base and volumes from scratch, but it didn't help. In the logs it shows that it found the dags, but it doesn't show them in the UI, not even the example ones.

**Comment by zachliu** [comment] 2024-09-10 17:00
I think there are actually two issues here with the same "disappearing dags" symptom
1. The symlink issue mentioned above. you'd also see the "Deactivated..." or "Deleted..." logs from the scheduler
2. A funny UI upgrade where the `Running` and `Failed` buttons are now persisted between UI re-loads. In other words, they act like a checkbox now. i need to "uncheck" it to see all DAGs 
   ![2024-09-10_12-50](https://github.com/user-attachments/assets/ad6bb997-4e50-4184-8401-ee992a8046af)
   ![2024-09-10_12-55](https://github.com/user-attachments/assets/82ba3e78-979f-4102-849f-7ad7525a9d02)

Since i don't use symlink on the dags folder, i belong to the second category :sweat_smile:

**Comment by smsm1-ito** [comment] 2024-09-11 09:38
> 2. A funny [UI upgrade](https://github.com/apache/airflow/pull/39701) where the `Running` and `Failed` buttons are now persisted between UI re-loads. In other words, they act like a checkbox now. i need to "uncheck" it to see all DAGs, which is not the case in `2.9.3`

The second issue should be dealt with in a separate ticket, though I think it's an expected behaviour change, however I have hit recursive redirect issue when editing the url to remove the running param.

**Comment by Bhargavjd** [comment] 2024-09-11 14:27
I upgraded to 2.10.1, the DAGs suddenly disappear from UIand sometime shows the missingdagbag error and if I refresh couple of times the DAGs are appearing again

**Comment by alaturqua** [comment] 2024-09-12 13:35
We just upgraded using official helm chart and version 2.10.1 and dags disappear as well.

Scheduler deletes and deactivates dags constantly even though dags are available and synced via GitSync.

**Comment by knoguchi** [comment] 2024-09-17 20:33
The problem is easily reproducible with `airflow standalone` with dags_folder config with a symlink that points a regular directory.

**Comment by thesuperzapper** [comment] 2024-09-17 21:35
@ephraimbuddy I see you just cut an [RC for 2.10.2](
https://github.com/apache/airflow/releases/tag/2.10.2rc1), was this absolutely critical breaking issue fixed in it?

If not, then we need to get a fix for this before cutting the final 2.10.2.

**Comment by ephraimbuddy** [comment] 2024-09-17 21:39
> @ephraimbuddy I see you just cut an [RC for 2.10.2](https://github.com/apache/airflow/releases/tag/2.10.2rc1), was this absolutely critical breaking issue fixed in it?
> 
> If not, then we need to get a fix for this before cutting the final 2.10.2.

Yes. It's the primary reason for this coming release. You can help to test it before the release.

**Comment by smsm1-ito** [comment] 2024-09-20 09:07
I've rolled the 2.10.2rc1 Docker image out to our internal environment and I'm no longer seeing this issue. All DAGs are loading as expected as per previous releases.

**Comment by Shlomixg** [comment] 2024-09-25 06:54
Still occurs in 2.10.2

**Comment by thesuperzapper** [comment] 2024-09-25 16:58
> Still occurs in 2.10.2

@Shlomixg can you clarify how you are using airflow?

E.g. are you using the community helm chart with git-sync, or something else?

**Comment by alaturqua** [comment] 2024-09-25 17:09
It is working for us now. Using official helm chart with gitsync and version 2.10.2.

**Comment by Shlomixg** [comment] 2024-09-26 09:21
> > Still occurs in 2.10.2
> 
> @Shlomixg can you clarify how you are using airflow?
> 
> E.g. are you using the community helm chart with git-sync, or something else?

We're using third-party helm chart with git-sync.

**Comment by ephraimbuddy** [comment] 2024-09-27 07:07
> > > Still occurs in 2.10.2
> > 
> > 
> > @Shlomixg can you clarify how you are using airflow?
> > E.g. are you using the community helm chart with git-sync, or something else?
> 
> We're using third-party helm chart with git-sync.

Can you reserialize your dags: `airflow dags reserialize`

**Comment by tukraus** [comment] 2024-09-27 07:30
Hi @ephraimbuddy, for us the problem seems fixed as well (using official helm chart + git sync). Could you clarify why this issue is still open and linked to the 2.10.3 milestone? Is another fix needed for similar problem in a different setup, or are you just awaiting several confirmations before closing this issue? Just to make up our minds on whether to roll out 2.10.2 or still wait a bit... Thanks!

**Comment by ephraimbuddy** [comment] 2024-09-27 08:30
> > > Still occurs in 2.10.2
> > 
> > 
> > @Shlomixg can you clarify how you are using airflow?
> > E.g. are you using the community helm chart with git-sync, or something else?
> 
> We're using third-party helm chart with git-sync.

Can you create another issue with the description of how to reproduce the issue? Closing this as completed

**Closed as completed by ephraimbuddy** 2024-09-27 08:30 UTC
Labels: kind:bug, area:helm-chart, area:core, needs-triage, area:DAG-processing

**Comment by bobir01** [comment] 2025-02-04 17:59
if any one facing the same issue just upgrade to 2.10.4 it is working with it
