### ISSUE TITLE
After upgrade from Airflow 2.2.4, grid disappears for some DAGs 

### ISSUE THREAD

**Issue by rotemseekingalpha** [apache/airflow#23588] opened 2022-05-09 13:37 UTC
### Apache Airflow version

2.3.0 (latest released)

### What happened

After the upgrade from 2.2.4 to 2.3.0, some DAGs grid data seems missing and it renders the UI blank

### What you think should happen instead

When I click the grid for a specific execution date, I expect to be able to click the tasks and view the log, render jinja templating, and clear status

### How to reproduce

Run an upgrade from 2.2.4 to 2.3.0 with a huge database (we have ~750 DAGs with a minimum of 10 tasks each).
In addition, we heavily rely on XCom.

### Operating System

Ubuntu 20.04.3 LTS

### Versions of Apache Airflow Providers

apache-airflow apache_airflow-2.3.0-py3-none-any.whl
apache-airflow-providers-amazon apache_airflow_providers_amazon-3.3.0-py3-none-any.whl
apache-airflow-providers-ftp apache_airflow_providers_ftp-2.1.2-py3-none-any.whl
apache-airflow-providers-http apache_airflow_providers_http-2.1.2-py3-none-any.whl
apache-airflow-providers-imap apache_airflow_providers_imap-2.2.3-py3-none-any.whl
apache-airflow-providers-mongo apache_airflow_providers_mongo-2.3.3-py3-none-any.whl
apache-airflow-providers-mysql apache_airflow_providers_mysql-2.2.3-py3-none-any.whl
apache-airflow-providers-pagerduty apache_airflow_providers_pagerduty-2.1.3-py3-none-any.whl
apache-airflow-providers-postgres apache_airflow_providers_postgres-4.1.0-py3-none-any.whl
apache-airflow-providers-sendgrid apache_airflow_providers_sendgrid-2.0.4-py3-none-any.whl
apache-airflow-providers-slack apache_airflow_providers_slack-4.2.3-py3-none-any.whl
apache-airflow-providers-sqlite apache_airflow_providers_sqlite-2.1.3-py3-none-any.whl
apache-airflow-providers-ssh apache_airflow_providers_ssh-2.4.3-py3-none-any.whl
apache-airflow-providers-vertica apache_airflow_providers_vertica-2.1.3-py3-none-any.whl

### Deployment

Virtualenv installation

### Deployment details

Python 3.8.10

### Anything else

For the affected DAGs, all the time

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rotemseekingalpha** [comment] 2022-05-09 13:45
[Video](https://youtu.be/BD91yCd6r68) that shows the problem

**Comment by jpipas** [comment] 2022-05-14 12:11
Just wanted to update, that this appears to only be happening for DAGs that have TaskGroups.  When viewing my "non-taskgroup" DAGs, the grid-view works as expected.  When trying to select individual tasks on a DAG with task groups (and therefore have expand/collapsible grid), clicking on an individual task the entire grid view disappears.

**Comment by ashb** [comment] 2022-05-17 20:00
Can someone give us a DAG and re-production steps please?

**Comment by bbovenzi** [comment] 2022-05-18 16:42
Also, what are the other js console errors aside from the get task endpoint? Even if that endpoint throws an error, the UI shouldn't crash

**Comment by rotemseekingalpha** [comment] 2022-05-19 11:52
I get first error message twice when then the second when the Grid view loads:
```
# First
VM35:1          
GET https://airflow2.seekingalpha.com/api/v1/dags/archiving_page_events/tasks 500
    (anonymous)                 @   VM35:1
    (anonymous)                 @   tree.ac7202f….js:2
    e.exports                   @   tree.ac7202f….js:2
    e.exports                   @   tree.ac7202f….js:2
    c.request                   @   tree.ac7202f….js:2
    r.forEach.c.<computed>      @   tree.ac7202f….js:2
    (anonymous)                 @   tree.ac7202f….js:2
    (anonymous)                 @   tree.ac7202f….js:2
    fetchFn                     @   tree.ac7202f….js:2
    s                           @   tree.ac7202f….js:2
    c                           @   tree.ac7202f….js:2
    t.fetch                     @   tree.ac7202f….js:2
    n.executeFetch              @   tree.ac7202f….js:2
    n.onSubscribe               @   tree.ac7202f….js:2
    t.subscribe                 @   tree.ac7202f….js:2
    (anonymous)                 @   tree.ac7202f….js:2
    Dl                          @   tree.ac7202f….js:2
    t.unstable_runWithPriority  @   tree.ac7202f….js:2
    Go                          @   tree.ac7202f….js:2
    Bl                          @   tree.ac7202f….js:2
    bl                          @   tree.ac7202f….js:2
    (anonymous)                 @   tree.ac7202f….js:2
    t.unstable_runWithPriority  @   tree.ac7202f….js:2
    Go                          @   tree.ac7202f….js:2
    Yo                          @   tree.ac7202f….js:2
    Xo                          @   tree.ac7202f….js:2
    xl                          @   tree.ac7202f….js:2
    is                          @   tree.ac7202f….js:2
    t.render                    @   tree.ac7202f….js:2
    (anonymous)                 @   tree.ac7202f….js:2
    n                           @   tree.ac7202f….js:2
    (anonymous)                 @   tree.ac7202f….js:2
    n                           @   tree.ac7202f….js:2
    (anonymous)                 @   tree.ac7202f….js:2
    (anonymous)                 @   tree.ac7202f….js:2
    (anonymous)                 @   tree.ac7202f….js:2
    (anonymous)                 @   tree.ac7202f….js:2

# Second
Error: Request failed with status code 500
    at e.exports (tree.ac7202f96db7173e9baf.js:2:141127)
    at e.exports (tree.ac7202f96db7173e9baf.js:2:297309)
    at XMLHttpRequest.E (tree.ac7202f96db7173e9baf.js:2:139518)
```
And finally, the following error twice when I click one of the tasks:
```
tree.ac7202f96db7173e9baf.js:2 
TypeError: Cannot read properties of undefined (reading 'tasks')
    at B_ (tree.ac7202f96db7173e9baf.js:2:739128)
    at ui (tree.ac7202f96db7173e9baf.js:2:228656)
    at Qu (tree.ac7202f96db7173e9baf.js:2:280737)
    at Pl (tree.ac7202f96db7173e9baf.js:2:268010)
    at jl (tree.ac7202f96db7173e9baf.js:2:267938)
    at Cl (tree.ac7202f96db7173e9baf.js:2:267801)
    at bl (tree.ac7202f96db7173e9baf.js:2:264788)
    at tree.ac7202f96db7173e9baf.js:2:214575
    at t.unstable_runWithPriority (tree.ac7202f96db7173e9baf.js:2:291432)
    at Go (tree.ac7202f96db7173e9baf.js:2:214352)
cu                          @ tree.ac7202f96db7173e9baf.js:2
n.callback                  @ tree.ac7202f96db7173e9baf.js:2
ma                          @ tree.ac7202f96db7173e9baf.js:2
gu                          @ tree.ac7202f96db7173e9baf.js:2
Il                          @ tree.ac7202f96db7173e9baf.js:2
t.unstable_runWithPriority  @ tree.ac7202f96db7173e9baf.js:2
Go                          @ tree.ac7202f96db7173e9baf.js:2
Tl                          @ tree.ac7202f96db7173e9baf.js:2
bl                          @ tree.ac7202f96db7173e9baf.js:2
(anonymous)                 @ tree.ac7202f96db7173e9baf.js:2
t.unstable_runWithPriority  @ tree.ac7202f96db7173e9baf.js:2
Go                          @ tree.ac7202f96db7173e9baf.js:2
Yo                          @ tree.ac7202f96db7173e9baf.js:2
Xo                          @ tree.ac7202f96db7173e9baf.js:2
Me                          @ tree.ac7202f96db7173e9baf.js:2
Yt                          @ tree.ac7202f96db7173e9baf.js:2
```

**Comment by ashb** [comment] 2022-05-19 15:19
Great thanks -- the second error is likely a side effect of the first.

What error appears in the webserver logs when you do the first action?

**Comment by jpipas** [comment] 2022-05-19 16:03
The web server error is what I posted above... ends with:

`AttributeError: 'dict' object has no attribute 'dump'`

I too am getting the same JS errors that @rotemseekingalpha is showing as well.  My theory about taskgroups however, appears wrong because it's also happening on "non-taskgroup" DAGs.  In my case they're "previously parsed" dags, and were there before the upgrade to 2.3.0 - so I assume there's something in the migration for these dags or that happened to them in the past that 2.3.0 just doesn't like.

**Comment by ashb** [comment] 2022-05-19 20:41
Do you have `task.params` or `dag.params` set to by any chance?

If someone can share with me a dag that exhibits this behaviour that would be very useful.

**Comment by rotemseekingalpha** [comment] 2022-05-20 07:12
@ashb we rely heavily on `task.params`

**Comment by ashb** [comment] 2022-05-20 12:28
I'll say it for the third time: we need a DAG that has this behavoiur to reproduce and fix it please.

**Comment by zachliu** [comment] 2022-05-25 15:24
@ashb steps to reproduce: https://github.com/apache/airflow/discussions/23908

**Comment by ashb** [comment] 2022-05-27 14:53
@zachliu  That grid view issue was caused by something else (removing a task from a DAG after it has run) to the 500 errors reported in this thread.

**Comment by maf-rnmourao** [comment] 2022-06-02 07:07
I noticed that when I log in, the problem doesn't occur. Probably it is some issue with permissions.
<img width="1724" alt="Screen Shot 2022-06-02 at 11 04 00 AM" src="https://user-images.githubusercontent.com/104142107/171572932-b3caf266-694e-41e1-8c45-894189d3b707.png">
<img width="1721" alt="Screen Shot 2022-06-02 at 11 07 05 AM" src="https://user-images.githubusercontent.com/104142107/171573096-79cd9c40-883d-45ed-8eb6-2a7052938051.png">

**Comment by maf-rnmourao** [comment] 2022-06-02 07:15
The issue seems to happen only when you are not logged in. It can be probably solved by customizing some permission.

**Not logged in:**
<img width="1724" alt="Screen Shot 2022-06-02 at 11 04 00 AM" src="https://user-images.githubusercontent.com/104142107/171574254-84d9ad01-5005-4428-807a-20192bf5fade.png">

**Logged in:**
<img width="1721" alt="Screen Shot 2022-06-02 at 11 07 05 AM" src="https://user-images.githubusercontent.com/104142107/171574280-42d44a8a-3326-41ff-a000-f4c5b2f567d9.png">

**Comment by bbovenzi** [comment] 2022-06-02 13:16
Got it. At least one set: We need to make sure an error on `/tasks` doesn't crash the UI

**Comment by NilsJPWerner** [comment] 2022-06-08 21:49
I'm having the same issue:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/10968348/172723414-cdf91d07-fde2-4ed2-aaab-e6044fcbc7e7.png">

**Comment by jpipas** [comment] 2022-06-13 20:24
We were able to determine that this issue was caused by a custom operator that erroneously had `params` as part of its `template_fields`.  Therefore any DAG that contained this operator would "flash" the grid - and then the subsequent API calls would fail - which then caused the grid to disappear.  After removing this "keyword" used by the baseoperator from `template_fields` the grids load properly now.

Before: `template_fields = ["sql_query", "s3_key","params"]`
After: `template_fields = ["sql_query", "s3_key"]`

**Comment by uranusjr** [comment] 2022-06-14 04:35
@jpipas Do you know what error the API is failing with? (May be available in web server logs.) Ideally the web server should be a bit more resilient to this kind of user errors.

**Comment by IonutArmeanu-work** [comment] 2022-06-16 13:35
I get the same error when I'm using AUTH_ROLE_PUBLIC = 'Admin' in webserver_config.py.
The /tasks endpoint fails with HTTP 401 ( Unauthorized )
![Screenshot 2022-06-16 at 14 34 20](https://user-images.githubusercontent.com/11160754/174081834-2f8f52fa-938a-45b0-9c66-98fb62b5bf7c.png)

**Comment by j-adamczyk** [comment] 2022-06-22 11:45
I get the same error, but Grid View disappears almost immediately after entering that page, without clicking anything. Also I have  small number of DAGs.

**Comment by ashb** [comment] 2022-06-24 13:14
> +1 on this one. I've also brought this up on: https://apache-airflow.slack.com/archives/CCQ7EGB1P/p1656075135345789

Have you tried with 2.3.2?

**Comment by cgadam** [comment] 2022-06-24 13:41
> > +1 on this one. I've also brought this up on: https://apache-airflow.slack.com/archives/CCQ7EGB1P/p1656075135345789
> 
> Have you tried with 2.3.2?

Yep, I'm actually reproducing this on `2.3.2`. Check footer below:

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/5420982/175547970-6647c116-3ec2-4c29-bef9-0097d847dc63.png">

**Comment by bbovenzi** [comment] 2022-06-24 14:06
Yes, I don't think we made the UI-side fix in time for 2.3.2 but it will be in 2.3.3

**Comment by cloventt** [comment] 2022-06-28 02:55
+1, I run Airflow behind an Nginx reverse proxy with `AUTH_ROLE_PUBLIC = 'Admin'
` set in the webserver config. I see 401 Unauthorized errors on the call to `api/v1/dags/<dag name>/tasks` which causes the grid to disappear.

**Comment by kobethuwis** [comment] 2022-09-21 10:40
@cloventt @rotemseekingalpha I'm using the official Airflow helm chart. Encountered the same error. In the chart, we use   `AUTH_ROLE_PUBLIC` = 'Admin'` as well.

Have been able to fix this error by adding the following to the chart:
`extraEnv: |
  - name: AIRFLOW__API__AUTH_BACKENDS
    value: "airflow.api.auth.backend.default"`

**Comment by cgadam** [comment] 2022-09-21 18:26
> @cloventt @rotemseekingalpha I'm using the official Airflow helm chart. Encountered the same error. In the chart, we use `AUTH_ROLE_PUBLIC = 'Admin'` as well as webserver config.
> 
> Have been able to fix this error by adding the following to the chart:
> 
> ```
> extraEnv: |
>   - name: AIRFLOW__API__AUTH_BACKENDS
>     value: "airflow.api.auth.backend.default"
> ```

@kobethuwis thank you for this tip! Adding `airflow.api.auth.backend.default` to `AIRFLOW__API__AUTH_BACKENDS` also made this issue to go away in my case! Nice workaround since we have this issue solved! Thanks!

**Comment by radiophysicist** [comment] 2023-06-23 10:13
We have the same problem in some DAGs (others working as expected) after upgrade from 1.0.15 to 2.5.3).
No errors both in browser console and webserver logs

**Comment by mjkonarski-b** [comment] 2023-06-26 16:17
I believe I found the root cause of the problem.

A new feature was introduced in 2.3.0 - "details drawer" in Grid View (https://github.com/apache/airflow/pull/22123). Under the hood in calls `/confirm` endpoint [here](https://github.com/apache/airflow/pull/22123/files#diff-b77ad76ebab03d48f0dab32af0c48b8cb23b3f4ba9b38222e423780e1f162859R33.). The problem is that this endpoint [requires](https://github.com/apache/airflow/blob/62a534dbc7fa8ddb4c249ade85c558b64d1630dd/airflow/www/views.py#L2586)  
`CAN_EDIT RESOURCE_DAG` and `CAN_EDIT RESOURCE_TASK_INSTANCE` permissions, which are obviously not granted to the Viewer role by default.

As a result the `/confirm` XHR call is redirected to the login page and returns its HTML content, which breaks the logic behind the "details drawer" and we get a blank page.

On top of that https://github.com/apache/airflow/pull/30373 introduced more improvements to the "details drawer" and now there's also a POST being sent to `/clear` which requires even more permissions.

**Closed as completed** 2023-08-03 08:29 UTC
Labels: kind:bug, area:API, area:UI, _eol_affected_version:2.3
