### ISSUE TITLE
Is there operator to create or update AWS DMS Serverless replication?

### ISSUE THREAD

**Issue by xudalei1977** [apache/airflow#43621] opened 2024-11-04 06:42 UTC
### Description

Is there operator to create or update AWS DMS Serverless replication?

### Use case/motivation

AWS DMS provide the Serverless replication which provide better effect for cost saving. so many customer want to use Airflow to create AWS DMS Serverless replication.

### Related issues

No.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2024-11-04 07:46
Duplicate of https://github.com/apache/airflow/issues/39954.
@ellisms is working on it.

Closing as duplicate

**Closed as not planned by eladkal** 2024-11-04 07:46 UTC
Labels: provider:amazon, area:providers, kind:feature, needs-triage
