### ISSUE TITLE
List Dag Run broken link to dag_run

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#40214] opened 2024-06-13 09:58 UTC
### Apache Airflow version

2.9.2

### What happened?

if I click on a dag_run on the list dag run webserver page

it always show the latest dag_run and not the dag_run I clicked on

### How to reproduce

```python
from airflow.operators.empty import EmptyOperator
from pendulum import today
from airflow import DAG

with DAG(
        dag_id='example',
        schedule_interval='0 0 * * *',
        start_date=today("UTC").add(days=-5)):
    EmptyOperator(task_id="nothing")

```

https://github.com/apache/airflow/assets/10202690/c2c59783-67cf-44e2-ab14-b1ef52d31bb0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vatsrahul1001** [comment] 2024-06-18 05:32
@raphaelauv I tried this and not able to reproduce this. Are you facing this for all of your DAG's?

**Comment by raphaelauv** [comment] 2024-06-18 08:08
you must set the filter first 

![image](https://github.com/apache/airflow/assets/10202690/ae43ea28-957b-426d-b74c-f3dbd5c7df3c)

I have the problem on google chrome and firefox

**Comment by vatsrahul1001** [comment] 2024-06-18 11:39
@raphaelauv I am able to repo thus

**Comment by pratyush369** [comment] 2024-06-21 09:07
Hi, I would like to work on this issue, I have done some initial debugging.

**Comment by ayush3singh** [comment] 2024-06-21 09:22
Hi, I would like to work on this issue, I have done some initial debugging. @potiuk  can you please assign it to me.

**Comment by potiuk** [comment] 2024-06-21 09:49
Sure

**Comment by laoni3634** [comment] 2024-06-28 07:05
When click on a dag_run in dag_run list page, the link is like below one. This link does not exist, so rediect to the latest one.
`https://localhost/pipelines/dags/transition_execute/graph?dag_run_id=dag_run_id`
When click on a grid in dag_detail page, the link is like below one. This link is correct.
`https://localhost/pipelines/dags/transition_execute/grid?dag_run_id=dag_run_id`

So I think the brief change is to change `https://localhost/pipelines/dags/transition_execute/graph?dag_run_id=dag_run_id` to 
`https://localhost/pipelines/dags/transition_execute/grid?dag_run_id=dag_run_id` (just replace graph with grid) when click on a dag_run in dag_run list page.

**Comment by romsharon98** [comment] 2024-08-02 08:49
Couldn't reproduce it on the main branch.
It's already has fixed by @bbovenzi here https://github.com/apache/airflow/pull/40241

**Closed as completed by romsharon98** 2024-08-02 08:49 UTC
Labels: kind:bug, good first issue, area:core, area:UI, _eol_affected_version:2.9

**Comment by raphaelauv** [comment] 2024-08-02 08:54
@romsharon98 the issue was open against version 2.9.2

and it was fix by https://github.com/apache/airflow/pull/40241 in version 2.9.3 ( that is part of the main branch )
