### ISSUE TITLE
Putting a task ON HOLD

### ISSUE THREAD

**Issue by afsalabdup** [apache/airflow#10044] opened 2020-07-29 09:47 UTC
Feature to put a future instance task ON HOLD is missing in Airflow.  Is there any way to achieve this functionality in Airflow. Appreciate any help.

**Comment by eladkal** [comment] 2020-07-29 13:50
How is that different than setting the DAG to off?

**Comment by afsalabdup** [comment] 2020-07-29 16:37
I want to put a specific task on hold, not whole dag.

**Comment by eladkal** [comment] 2020-11-03 12:51
Duplicate of https://github.com/apache/airflow/issues/9298

**Closed as completed by eladkal** 2020-11-03 12:51 UTC
Labels: kind:feature, duplicate
