### ISSUE TITLE
No log folder created by workers in AIRFLOW 2.1.0

### ISSUE THREAD

**Issue by abhishektrivedi-hs** [apache/airflow#16234] opened 2021-06-03 07:29 UTC
Hi Team,

We are frequently getting below error in airflow where the workers are not able to create the log folder. This usually happens when there is no execution for couple of hours or a new day. We have tried all the options available over the internet including the URL configuration with ip/hostname and we also increased the number of workers. We have also verified the local server for log generation but no luck.

We are using local executor in a linux server for a POC purpose.
 

*** Log file does not exist: /home/airflow/airflow/logs/dag_id/task_id/2021-06-03T06:49:13.619660+00:00/1.log 
*** Fetching from: http://:8793/log/dag_id/task_id/2021-06-03T06:49:13.619660+00:00/1.log
*** Failed to fetch log file from worker. Unsupported URL protocol ''

Any help would be appriciated. 

In order to resolve this issue we are restarting webserver and scheduler. But it works only for few hours.

Thanks
Abhishek

**Comment by oscarostlundgs** [comment] 2021-06-08 11:25
We have had a similar problem since upgrading to 2.1.0. 
We are running Airflow on k8s with a CeleryExecutor (prefork), with log files on a mounted PVC on the pod. 

We have also noticed some very undescriptive errors in the Celery Workers:
```
[2021-06-07` 17:45:21,496: ERROR/ForkPoolWorker-16] Task airflow.executors.celery_executor.execute_command[badb5448-f278-46a8-ac43-7503599bcf34] raised unexpected: AirflowException('Celery command failed on host: celery-workers-64bc8d594f-f7x9g')
Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/airflow/venv/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/airflow/venv/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 87, in execute_command
    _execute_in_fork(command_to_exec)
  File "/home/airflow/venv/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 98, in _execute_in_fork
    raise AirflowException('Celery command failed on host: ' + get_hostname())
airflow.exceptions.AirflowException: Celery command failed on host: celery-workers-64bc8d594f-f7x9g
```

We haven't been able to track down the root cause yet. Some older StackOverflow threads ([here](https://stackoverflow.com/questions/51775370/airflowexception-celery-command-failed-the-recorded-hostname-does-not-match-t) and [here](https://stackoverflow.com/questions/52263203/airflow-1-10-config-core-hostname-callable-how-to-set/52320661)) point to `hostname_callable` being a potential issue but haven't been able to test this hypothesis yet.

**Comment by damon09273** [comment] 2021-06-11 02:04
I got same error in 2.1.0 too, either CeleryExecutor and KubernetesCeleryExecutor.
I run Airflow by Kubernetes, and mounted a PV for the log directory.

**Comment by kaxil** [comment] 2021-06-22 12:13
duplicate of https://github.com/apache/airflow/issues/13692

**Closed as completed by kaxil** 2021-06-22 12:13 UTC
Labels: kind:bug, area:Scheduler, area:logging, _eol_affected_version:2.1
