### ISSUE TITLE
Ooops! Something bad has happened. When trying to load airflow 2.0.2

### ISSUE THREAD

**Issue by Maheshbbc** [apache/airflow#26899] opened 2022-10-05 19:17 UTC
### Apache Airflow version

Other Airflow 2 version

### What happened

Ooops!
Something bad has happened.
Python version: 3.7.10
Airflow version: 2.0.2
Node: redact
-------------------------------------------------------------------------------
Error! Please contact server admin.

### Operating System

Python version: 3.7.10 Airflow version: 2.0.2 Node: redact

### Deployment

MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2022-10-05 19:44
There is no information that would make it even close to understand what kind of problem it was. Closing.

**Comment by Maheshbbc** [comment] 2022-10-05 19:46
When I just try to open the Airflow UI it gives me. 
error as "Ooops!
Something bad has happened.
Please consider letting us know by creating a [bug report using GitHub](https://github.com/apache/airflow/issues/new/choose).

Python version: 3.7.10
Airflow version: 2.0.2
Node: redact
-------------------------------------------------------------------------------
Error! Please contact server admin."

**Comment by potiuk** [comment] 2022-10-05 19:46
If you want to report a issue - please provide all information including reproduction steps, logs etc explaining what the problem is

**Closed as not planned** 2022-10-05 19:46 UTC
Labels: kind:bug, area:core
