### ISSUE TITLE
Kubernetes executor fails to create worker pod in case longer dag/task are specified

### ISSUE THREAD

**Issue by p-id** [apache/airflow#13650] opened 2021-01-13 10:21 UTC
**Apache Airflow version**: 1.10.x, 2.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.18.8

**Environment**: Azure - AKS - ContainerD CRI-O

- **Cloud provider or hardware configuration**: Azure AKS
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS      
- **Kernel** (e.g. `uname -a`): 5.4.0-1031-azure
- **Install tools**: Docker runtime  - 19.3.12
- **Others**: ContainerD CRI-O

**What happened**: Worker pod stuck in 'ContainerCreating' state - no error propagated to Airflow K8s executor for a DAG containing a longer workflow-name and task-name get specified.

**What you expected to happen**: Worker-pod to success run OR task failure notification received due to K8s error

**How to reproduce it**: Run any dag/task with longer names - combined number of alphanumeric characters in dag/task name should be more than 214

**Anything else we need to know**: The error seems to occur due to pod sandbox creation failure. Each K8s pod gets a specific sandbox (directory). If the pod-id generated by Airflow Kubernetes executor is more than 214 characters, K8s also add suffix/prefix to generate a specific sandbox directory (prefix the K8s namespace and suffix a 36 character UUID using '_' as delimiter). This results in the sandbox directory name to cross '255' characters which is the maximum character (bytes) limit in most of the EXT FS based filesystem.

**Comment by potiuk** [comment] 2021-01-13 10:28
Closing as duplicate of #13189

**Closed as completed by potiuk** 2021-01-13 10:28 UTC
Labels: kind:bug, duplicate
