### ISSUE TITLE
New forced "Graph" view redirection breaks links from logs dag_run list table.

### ISSUE THREAD

**Issue by wpromatt** [apache/airflow#36884] opened 2024-01-19 04:58 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.3

### What happened?

It seems this new "graph" view redirection breaks links from a task's log or the dag_run list table view.

It seems the redirection doesn't work when the dag run you're trying to view is outside the default selected number of dag runs. Because we are always in "grid" view now technically, the dag_run needs to be one of the list of dag runs showed in the grid view (25 by default).

Link from task logs. Note how the "graph" button goes to `/dags/ninjacat_listener/graph?root=&execution_date=2024-01-17T21%3A08%3A00%2B00%3A00`.

<img width="1195" alt="Screenshot 2024-01-18 at 8 09 28 PM" src="https://github.com/apache/airflow/assets/10120896/d5a0e1a0-6069-40f2-8576-ce978dc7502b">

Since this particular dag run was like 200 or so dag_runs in the past, once redirected the graph shows without a selected run. I can only go there by manually adding `&num_runs=200` to the url that graph link sends you to.

Is there a way around this? Having that old link also specify the `&base_date=` param would help a bit. However, in another one of our use-cases we have a DAG that is triggered by a TON of other DAGs. The execution_date for these triggered runs varies only in microseconds, so we can have thousands of dag_runs with execution dates in the same minute or even second. Setting the `base_date` here wouldn't work. Is there a way to be able to link to the graph view of a DAG _without_ having to set `num_runs=2000` in this case?

Maybe I'm missing something obvious.

### What you think should happen instead?

There should be a way to link to the graph view of a "single" dag_run. When I click the graph button while viewing a task's logs or select a specific dag_run from the list dag runs view, I should be redirected somewhere where I can actually view the dag run.

### How to reproduce

Go to the `dagrun/list/` page, and select a dag_run that is more than the default number of runs in the past. You will see the page you are redirected to displays a graph with no selected dag_run.

<img width="1931" alt="image" src="https://github.com/apache/airflow/assets/10120896/b7a52520-1978-455e-b046-66f5ac448be3">

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by wpromatt** [comment] 2024-01-19 05:32
Mentioned the same on the PR introducing the forced redirect. https://github.com/apache/airflow/pull/32958

**Comment by potiuk** [comment] 2024-01-20 07:35
Closing as duplicate of #34723

**Closed as completed by potiuk** 2024-01-20 07:35 UTC
Labels: kind:bug, duplicate, area:core, needs-triage
