### ISSUE TITLE
backfill --mark_success is not working correctly

### ISSUE THREAD

**Issue by lamigud-handy** [apache/airflow#783] opened 2015-12-17 17:02 UTC
From what i can tell, when i run backfill with --mark_success (actually just "-m"),
tasks are run and executed (instead of just marked as succeeded).

This is an issue with 1.6.1.2, but it might have been an issue with previous builds as well.

Leo

**Comment by wil5for** [comment] 2015-12-21 23:32
Likely duplicate of issue #571

**Comment by r39132** [comment] 2015-12-22 00:16
Yes, I reported this issue on 1.5.1.

**Comment by r39132** [comment] 2016-02-10 06:57
Fixed. Closing.

**Closed as completed by r39132** 2016-02-10 06:57 UTC
