### ISSUE TITLE
Bad display of xcom values

### ISSUE THREAD

**Issue by Pad71** [apache/airflow#41673] opened 2024-08-22 12:08 UTC
### Apache Airflow version

2.10.0

### What happened?

When displaying primitive xcom values, an error message is displayed.

version 2.9.2.
![image](https://github.com/user-attachments/assets/2fbda2ba-6711-48c2-a064-26ce444361c9)

similar task in version 2.10.0
![image](https://github.com/user-attachments/assets/aee09e82-4dd2-43a8-8851-4d585941d210)

### What you think should happen instead?

value should be displayed correctly even if it is primitive and not json.

### How to reproduce

View the xcom in a task whose xcom values are not json

### Operating System

Kubernetes on Unix platform

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Pad71** [comment] 2024-08-22 12:57
Sometimes is xcom displayed that way (see pict below) . In version 2.9.2 it worked well.
![image](https://github.com/user-attachments/assets/060ffabe-9663-4cce-bce4-ba763bf2200e)

**Comment by potiuk** [comment] 2024-08-22 13:28
Duplicate of #41516  - scheduled to be fixed in 2.10.1

**Closed as completed by potiuk** 2024-08-22 13:28 UTC
Labels: kind:bug, duplicate, area:core, area:UI
