### ISSUE TITLE
REST API List Task Instance limit functioniality

### ISSUE THREAD

**Issue by frankbreetz** [apache/airflow#20725] opened 2022-01-06 16:30 UTC
### Apache Airflow version

2.2.2

### What happened

The following REST Call produces a body with 100 task instances (The default for the page_limit/limit value (I am not sure which is correct documentation mentions both, neither cause errors))
```

import requests
import json

url = "http://localhost:8080/api/v1/dags/~/dagRuns/~/taskInstances"

payload = json.dumps({
  "page_limit": 1,
  "limit": 1
})
headers = {
  'Authorization': 'Basic XXXXXXXXX',
  'Content-Type': 'application/json',
  'Cookie': 'session=XXXXXXX'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)
```

### What you expected to happen

A single task instance entry should be returned in the response from the REST Call

### How to reproduce

Run the script above and inspect the results( your DB should have 100+ task Instances)

You will get 100 task instance in the response when you should get just 1

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Astronomer

### Anything else

Perhaps the best fix for this would be to remove this REST Call and add limit/offset to the post call:
https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/get_task_instances_batch

getting all the task instances in a single REST call will overload some systems, so limit/offset allows you to incrementally load 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment] 2022-01-10 03:59
Assigned!

**Comment by ephraimbuddy** [comment] 2022-01-11 22:24
I think you are doing this the wrong way. The limits are params and not data, so this should work:

```
response = requests.request("GET", url, headers=headers, params=payload)
```

Or am I missing something?

**Comment by frankbreetz** [comment] 2022-01-13 17:51
@ephraimbuddy is correct! I would still argue there is a little discontinuity between the DagRun Call and the TaskInstance, The DagRun uses the body and TaskInstance uses the params

**Comment by ephraimbuddy** [comment] 2022-01-13 22:27
> @ephraimbuddy is correct! I would still argue there is a little discontinuity between the DagRun Call and the TaskInstance, The DagRun uses the body and TaskInstance uses the params

It's documented. You're talking about dagruns batch. It also uses POST instead of GET. It's so because we want to get a `batch` without overwhelming the server with requests. There's also a GET method for dagruns which applies limit in params.

Closing this for now since I think it's not a bug

**Closed as completed by ephraimbuddy** 2022-01-13 22:27 UTC
Labels: kind:bug, area:core
