### ISSUE TITLE
Manual DAG triggers with Logical Date in the Past trigger a second run when schedule is timedelta

### ISSUE THREAD

**Issue by jscheffl** [apache/airflow#33949] opened 2023-08-31 09:27 UTC
### Apache Airflow version

2.7.0

### What happened

Relates to investigation of #30327

When you define a DAG with a `schedule=datetime.timedelta(days=1)` and `catchup=False` and you manually trigger a run in the past (logical date in the past, e.g. a few days ago) then upon completion of the run another scheduled run is triggered - irrespective of a previous scheduled run was made just before (not a day ago)

### What you think should happen instead

A manual run should not trigger another run as the scheduling in general should follow the delta time definition of the DAG.

### How to reproduce

Use the following example DAG code and enable scheduling:
```
with DAG(
    dag_id="after_workday_delta_regression",
    start_date=pendulum.datetime(2023, 8, 1, tz="UTC"),
    catchup=False,
    schedule=datetime.timedelta(days=1),
    params={"test": 123}
):
    @task
    def test(ti: TaskInstance=None):
        print(ti.execution_date)
    test()
```

Wait a moment and see that one schedule is run automatically.
Then trigger a manual DAG run and set the execution date/logical date a few days into the past.
After execution you see a third run of the DAG just at the time of completion of the manual trigger as execution date. But the first execution was just a few moments before, not respecting the desired delta of 1 day.

### Operating System

Ubuntu 20.04 / Breeze Dev setup in Py 3.8 Container

### Versions of Apache Airflow Providers

not relevant

### Deployment

Other

### Deployment details

Started and tested with latest main branch and breeze.

### Anything else

I tried to find the root cause but was not able to locate it. Suspect it is rooted in scheduler_job_runner.py.
I'd supply a fix but was not able to fund the root cause. Expert knowledge is needed probably.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bisk1** [comment] 2023-09-01 09:00
I reproduced it locally and can confirm it. I would like to work on a fix for this.

After debugging scheduler it seems that the problem is with calculate_dagrun_date_fields function in dag.py. This method is invoked after completing either manual or scheduled run. Then it select the next `next_dagrun_data_interval` based on the date interval of the DAG run that was just completed. The issue here is that this DAG run might be in the past (as in this scenario) in which case it will incorrectly decide that there should be an extra run scheduled in another in the past (right after this one).

**Closed as completed** 2023-09-05 13:01 UTC
Labels: kind:bug, area:Scheduler, area:core
