### ISSUE TITLE
Clean Postgres database on Python3.10 gives foreign key error

### ISSUE THREAD

**Issue by kuikeelc** [apache/airflow#34859] opened 2023-10-11 08:02 UTC
### Apache Airflow version

2.7.1

### What happened

When running:

airflow tasks test DAG_NAME TASK_NAME

the task runs fine, but ends with the error message:

airflow.exceptions.AirflowException: Foreign key associated with column 'dag_run_note.user_id' could not find table 'ab_user' with which to generate a foreign key to target column 'id'

### What you think should happen instead

The error message shouldn't be there.

### How to reproduce

create a clean database in Postgres on Python3.10 on Mac OS X. You then get the error.

### Operating System

Mac OS X latest version

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.5.1
apache-airflow-providers-cncf-kubernetes==7.4.2
apache-airflow-providers-common-sql==1.7.0
apache-airflow-providers-ftp==3.5.0
apache-airflow-providers-google==10.6.0
apache-airflow-providers-http==4.5.0
apache-airflow-providers-imap==3.3.0
apache-airflow-providers-jdbc==4.0.1
apache-airflow-providers-mysql==5.2.1
-e git+ssh://git@github.com/onesecondbefore/osb-transfer.git@32e126f5d250cdceca4afb4cf9cbf8953ba9ece5#egg=apache_airflow_providers_onesecondbefore&subdirectory=providers/apache-airflow-providers-onesecondbefore
apache-airflow-providers-postgres==5.6.0
apache-airflow-providers-slack==7.3.2
apache-airflow-providers-snowflake==4.4.2
apache-airflow-providers-sqlite==3.4.3
apache-airflow-providers-ssh==3.7.1

### Deployment

Virtualenv installation

### Deployment details

It is on my local machine.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kuikeelc** [comment] 2023-10-13 20:21
Bug remains in Airflow v2.7.2

**Comment by kuikeelc** [comment] 2023-10-13 21:07
Duplicate issue of https://github.com/apache/airflow/issues/34109

**Comment by mujiannan** [comment] 2023-10-17 10:56
Even exists while using local sqlite db.

**Comment by kuikeelc** [comment] 2023-11-07 08:06
And the bug remains in v2.7.3.

**Comment by potiuk** [comment] 2023-11-07 12:11
THis is a duplicate of https://github.com/apache/airflow/issues/34109. There is no point on keeping several issues opened for the same issue.

**Closed as completed** 2023-11-07 12:10 UTC
Labels: kind:bug, area:core, needs-triage
