### ISSUE TITLE
Scheduler do not start on custom AIRFLOW_HOME path v.2.0.1

### ISSUE THREAD

**Issue by ghost** [apache/airflow#14297] opened 2021-02-18 18:31 UTC
Scheduler do not start on custom AIRFLOW_HOME path v.2.0.1
Scheduler Log cannot be updated in sqlite db on custom environment path.

**Comment by XD-DENG** [comment] 2021-02-18 20:15
Hi @milindgv94 , thanks for sharing the issue. But may you share your steps reproducing the issue? Ideally with:
- details about your setting up: OS, version of DB, etc.
- your sample commands to reproduce the issue (and the flags/options/configs)
- detailed trackbacks may help as well

**Comment by XD-DENG** [comment] 2021-03-03 10:49
Hi @milindgv94 , I tried but I cannot reproduce the issue you reported, as long as I made sure the same `AIRFLOW_HOME` env var is available to all the processes (CLI/webserver/scheduler etc.)

May you double-check from your end and share the details if you still have the issue you reported? Otherwise I would suggest to close this issue.

**Comment by XD-DENG** [comment] 2021-03-05 16:46
Hi @vikramkoka,  I would suggest to close this Issue given I cannot reproduce the issue and no further response from the Issue raiser. Do you agree?

**Comment by ashb** [comment] 2021-03-05 16:53
Yup, without any response from the OP we can't debug this.

**Comment by XD-DENG** [comment] 2021-03-05 16:56
Hi @milindgv94 , as discussed above, we will close this issue for now. 

If you can reproduce the issue & share the details, please feel free to re-open this. Thanks.

**Closed as completed by XD-DENG** 2021-03-05 16:56 UTC
Labels: kind:bug
