### ISSUE TITLE
Xcom view broken for non-JSON values

### ISSUE THREAD

**Issue by jkramer-ginkgo** [apache/airflow#41981] opened 2024-09-03 18:59 UTC
### Apache Airflow version

2.10.0

### What happened?

Non-JSON values are broken in the Xcom UI [screenshot attached]

Root cause is [this line](https://github.com/jscheffl/airflow/blob/5f5039a6531d9366ac7ffc9a05492b7a93bc8f87/airflow/www/static/js/api/useTaskXcom.ts#L66) from https://github.com/apache/airflow/pull/40640. Setting `stringify: false` results in JSON encoding which results in `TypeError: keys must be str, int, float, bool or None, not tuple` exception from `GET <Airflow URL>/api/v1/dags/<DAG>/dagRuns/<Run ID>/taskInstances/<Task ID>/xcomEntries/<Xcom name>?stringify=false` endpoint.

The PR's intention is to make the whole view JSON, so not sure if the intention is to error on non-JSON Xcom values, or if it should be updated to have clean fallback logic.

![Pasted Graphic 22](https://github.com/user-attachments/assets/5451cdb0-3475-4524-b504-ade4df4a3a98)

### How to reproduce

Create Xcom value that is non-JSON serializable (e.g. `{('201009_NB502104_0421_AHJY23BGXG (SEQ_WF: 138898)', None): 82359}`) and then try to view in UI Xcom tab

### Operating System

Linux (Ubuntu 22.04)

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2024-09-03 22:48
Duplicate of https://github.com/apache/airflow/pull/41605 fixed in https://github.com/apache/airflow/pull/41516 and available in 2.10.1rc1. Can you please double check if rc1 of 2.10.0 fixes the problem for you @jkramer-ginkgo - see https://github.com/apache/airflow/issues/41956 for links and details

**Comment by potiuk** [comment] 2024-09-03 22:48
Ideally pleasee comment in https://github.com/apache/airflow/issues/41956 when you confirm the problem is fixed.

**Closed as completed by potiuk** 2024-09-03 22:48 UTC
Labels: kind:bug, duplicate, area:core, area:UI, needs-triage

**Comment by jkramer-ginkgo** [comment] 2024-09-09 15:36
@potiuk would you be able to reopen or should I dupe this issue?

**Comment by potiuk** [comment] 2024-09-09 16:41
Idealy copy it - this is easier for our "release" process.

**Comment by jkramer-ginkgo** [comment] 2024-09-10 18:52
@potiuk Cloned here: https://github.com/apache/airflow/issues/42117
