### ISSUE TITLE
ValueError in airflow.utils.timeout.__enter__

### ISSUE THREAD

**Issue by pradhanpk** [apache/airflow#1050] opened 2016-02-21 20:21 UTC
Here's the traceback outputted by the webserver running in debug mode

> Traceback (most recent call last):
>   File "models.py", line 207, in process_file
>     with utils.timeout(30):
>   File "utils.py", line 621, in **enter**
>     signal.signal(signal.SIGALRM, self.handle_timeout)
> ValueError: signal only works in main thread

(The line numbers are with respect to adab0cf9de1081ec19db102bcea4405c629d0baf.)

This happens when I add a new dag to the dag folder and try to click through to the dag from the "Dag Runs" UI page, i.e., try to access an address like this one `http://localhost:9898/admin/airflow/graph?dag_id=some_dag`.

This code seems to be running afoul of this [signal module](https://docs.python.org/2/library/signal.html) rule:

> Some care must be taken if both signals and threads are used in the same program. The fundamental thing to remember in using signals and threads simultaneously is: always perform `signal()` operations in the main thread of execution. Any thread can perform an `alarm()`, `getsignal()`, `pause()`, `setitimer()` or `getitimer()`; only the main thread can set a new signal handler, and the main thread will be the only one to receive signals (this is enforced by the Python `signal` module, even if the underlying thread implementation supports sending signals to individual threads). This means that signals can’t be used as a means of inter-thread communication. Use locks instead.

**Comment by abridgett** [comment] 2016-04-06 15:38
this maybe a dupe of #899 as that was triggered on new dags as well

**Closed as completed** 2020-03-20 15:59 UTC
Labels: kind:bug
