### ISSUE TITLE
Delete DAG crashes

### ISSUE THREAD

**Issue by kylowrobelek** [apache/airflow#15381] opened 2021-04-15 12:45 UTC
**Apache Airflow version**: 2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: Dell Latitude
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS
- **Kernel** (e.g. `uname -a`): 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**: python 3.8.5
- **Others**: local development

**What happened**: When I click delete button (on UI admin panel) for the DAG, admin panel crashed

Traceback (most recent call last):
  File "/home/krzysztofwrobel/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/krzysztofwrobel/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/krzysztofwrobel/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/krzysztofwrobel/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/krzysztofwrobel/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/krzysztofwrobel/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/krzysztofwrobel/.local/lib/python3.8/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/home/krzysztofwrobel/.local/lib/python3.8/site-packages/airflow/www/decorators.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/home/krzysztofwrobel/.local/lib/python3.8/site-packages/airflow/www/views.py", line 1393, in delete
    delete_dag.delete_dag(dag_id)
  File "/home/krzysztofwrobel/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/krzysztofwrobel/.local/lib/python3.8/site-packages/airflow/api/common/experimental/delete_dag.py", line 54, in delete_dag
    for model in models.base.Base._decl_class_registry.values():  # noqa pylint: disable=protected-access
AttributeError: type object 'Base' has no attribute '_decl_class_registry

**What you expected to happen**: Delete DAG

**How to reproduce it**: Try to delete dag in admin panel

**Anything else we need to know**:

**Comment by eladkal** [comment] 2021-04-16 14:20
Duplicate of https://github.com/apache/airflow/issues/15354

**Closed as completed by eladkal** 2021-04-16 14:20 UTC
Labels: kind:bug, duplicate
