### ISSUE TITLE
When I set wait_for_downstream=True, the task will not wait, and a failure will be reported

### ISSUE THREAD

**Issue by pysenic** [apache/airflow#18229] opened 2021-09-14 07:59 UTC
Version: 2.1.3
OS: CentOS 7
Executor: CeleryExecutor

I update airflow to 2.1.3 from 1.10.15（New environment redeployment），I found the problem still unsolved，My dag args is:

```
default_args = {
    'owner': 'admin',
    'depends_on_past': True,
    'start_date': start_time,
    'wait_for_downstream': True,
    'on_failure_callback': failure_callback,
    'on_retry_callback': retry_callback,
    'retries': 1,
    'retry_delay': timedelta(seconds=60)
}
```
The DAG will be scheduled hourly

Assuming that task is  A >> B >> C >> D >> E >> F 

now A B C is success and D is running，the next batch task A B is success，i think the next batch task C will wait for run until the D is success, because set wait_for_downstream=True，In fact，the task C report a failure

```log
*** Reading local file: /home/hadoop/bi/log/airflow/dag_data_etl_1h/ods.session_logs/2021-09-13T06:03:00+00:00/2.log
[2021-09-14 15:22:04,492] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2021-09-14 15:22:04,501] {base_task_runner.py:62} DEBUG - Planning to run as the  user
[2021-09-14 15:22:04,503] {taskinstance.py:618} DEBUG - Refreshing TaskInstance <TaskInstance: dag_data_etl_1h.ods.session_logs 2021-09-13T06:03:00+00:00 [queued]> from DB
[2021-09-14 15:22:04,509] {taskinstance.py:656} DEBUG - Refreshed TaskInstance <TaskInstance: dag_data_etl_1h.ods.session_logs 2021-09-13T06:03:00+00:00 [queued]>
[2021-09-14 15:22:04,516] {taskinstance.py:918} DEBUG - <TaskInstance: dag_data_etl_1h.ods.session_logs 2021-09-13T06:03:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2021-09-14 15:22:04,516] {taskinstance.py:918} DEBUG - <TaskInstance: dag_data_etl_1h.ods.session_logs 2021-09-13T06:03:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2021-09-14 15:22:04,516] {taskinstance.py:918} DEBUG - <TaskInstance: dag_data_etl_1h.ods.session_logs 2021-09-13T06:03:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2021-09-14 15:22:04,524] {taskinstance.py:918} DEBUG - <TaskInstance: dag_data_etl_1h.ods.session_logs 2021-09-13T06:03:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: False, The tasks downstream of the previous task instance <TaskInstance: dag_data_etl_1h.ods.session_logs 2021-09-13 05:03:00+00:00 [success]> haven't completed (and wait_for_downstream is True).
[2021-09-14 15:22:04,524] {taskinstance.py:897} INFO - Dependencies not met for <TaskInstance: dag_data_etl_1h.ods.session_logs 2021-09-13T06:03:00+00:00 [queued]>, dependency 'Previous Dagrun State' FAILED: The tasks downstream of the previous task instance <TaskInstance: dag_data_etl_1h.ods.session_logs 2021-09-13 05:03:00+00:00 [success]> haven't completed (and wait_for_downstream is True).
[2021-09-14 15:22:04,525] {local_task_job.py:96} INFO - Task is not able to be run
```

There is no abnormality, the task is reported inexplicably wrong

![image](https://user-images.githubusercontent.com/20294807/133218204-bb31a20b-feee-454a-9cab-e66e20b8b18c.png)

Earlier this year, I also upgraded the 2.x version, but this problem has not been resolved.

_Originally posted by @pysenic in https://github.com/apache/airflow/discussions/18227_

**Comment by kosteev** [comment] 2021-09-16 08:03
I can reproduce it in Airflow 2.1.2.

Code of DAG:
```
default_args = {'wait_for_downstream': True, 'provide_context': False}
command = 'sleep 1'

with DAG(
    'test_downstream',
    start_date=datetime.datetime.now() - datetime.timedelta(hours=1),
    schedule_interval='*/1 * * * *',
    default_args=default_args,
    max_active_runs=100, dagrun_timeout=datetime.timedelta(minutes=60),
    catchup=True) as dag:

  start_task = BashOperator(
      task_id='start_task', bash_command=command, retries=3,
      trigger_rule='all_success', dag=dag)

  end_task = BashOperator(
      task_id='end_task', bash_command=command, retries=3,
      trigger_rule='all_success', dag=dag)

  for target_date in range(0, 2):
    bash_cmd_j000 = BashOperator(
        task_id='bash_cmd_j000_' + str(target_date),
        bash_command=command, retries=3,
        trigger_rule='all_success', dag=dag)
    bash_cmd_j001 = BashOperator(
        task_id='bash_cmd_j001_' + str(target_date),
        bash_command=command, retries=3,
        trigger_rule='all_success', dag=dag)
    bash_cmd_j002 = BashOperator(
        task_id='bash_cmd_j002_' + str(target_date),
        bash_command=command, retries=3,
        trigger_rule='all_success', dag=dag)
    bash_cmd_j003 = BashOperator(
        task_id='bash_cmd_j003_' + str(target_date),
        bash_command=command, retries=3,
        trigger_rule='all_success', dag=dag)

    start_task >> bash_cmd_j000 >> bash_cmd_j001 >> bash_cmd_j002 >> bash_cmd_j003 >> end_task
```

After some time some tasks are scheduled and marked as failed (and up_for_retry) with log message:
```
[2021-09-16 07:56:46,290] {taskinstance.py:887} INFO - Dependencies not met for <TaskInstance: test_downstream.bash_cmd_j001_0 2021-09-16T06:58:00+00:00 [queued]>, dependency 'Previous Dagrun State' FAILED: The tasks downstream of the previous task instance <TaskInstance: test_downstream.bash_cmd_j001_0 2021-09-16 06:57:00+00:00 [success]> haven't completed (and wait_for_downstream is True).
[2021-09-16 07:56:46,560] {local_task_job.py:96} INFO - Task is not able to be run
```

**Comment by kosteev** [comment] 2021-09-16 15:20
![image](https://user-images.githubusercontent.com/1017130/133639089-3540cfdf-8cd4-4b5c-ad4f-2c8f3eee200b.png)
After some testing it looks like the issue is in mini scheduler running in worker. So, somehow mini scheduler schedules a task that shouldn't be scheduled as it doesn't meet all dependency requirements (wait_for_downstream=True), and then it fails during start of execution because of it.

If I disable mini scheduler [scheduler]schedule_after_task_execution=False the issue is not reproduced anymore.
This is screenshot when mini scheduler disabled:
![image](https://user-images.githubusercontent.com/1017130/133639242-d069f8bc-813b-4f3d-b563-63d6b847aa1e.png)

CC: @ashb

**Closed as completed** 2021-09-17 14:07 UTC
Labels: priority:high
