### ISSUE TITLE
google-cloud-dlp dependency is out of date

### ISSUE THREAD

**Issue by stfines-clgx** [apache/airflow#26978] opened 2022-10-11 01:01 UTC
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

apache-airflow = "^2.4.1"
apache-airflow-providers-google = "^8.4.0"

### Apache Airflow version

2.4.1

### Operating System

Darwin C02CP187MD6R 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### Deployment

Docker-Compose

### Deployment details

Development environment

### What happened

Latest apache beam cannot be installed because of the out of date google-cloud-dlp dependency:
```

  Because apache-airflow-providers-google (8.4.0) depends on google-cloud-dlp (>=0.11.0,<2.0.0)
   and no versions of apache-airflow-providers-google match >8.4.0,<9.0.0, apache-airflow-providers-google (>=8.4.0,<9.0.0) requires google-cloud-dlp (>=0.11.0,<2.0.0).
  So, because python-template depends on both apache-airflow-providers-google (^8.4.0) and google-cloud-dlp (^3.9.2), version solving failed.

```

### What you think should happen instead

the apache beam google provider should install using a much more current version of google-cloud-dlp; as of the creation of the ticket it is 3.9.2

### How to reproduce

set up a project with the two providers above and attempt to install any beam with gcp extensions at the current version @2.42

I tested down to 2.40 with the same result

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2022-10-12 08:36
This is not a bug.
Many of google packages are not up to date, updating was an effort started a while ago https://github.com/apache/airflow/issues/12116

we can make progress in such issues only if users of google (like yourself) will raise PRs.
Feel free to raise one. The list of dependencies can be found on:
https://github.com/apache/airflow/blob/40d19b9ab89701126653d24d28e477e677f2ea97/airflow/providers/google/provider.yaml#L56-L119

I'm closing this issue because we are not going to have separated issue per package.

**Closed as completed by eladkal** 2022-10-12 08:36 UTC
Labels: provider:google, area:providers

**Comment by potiuk** [comment] 2022-10-23 00:09
And let me add to what @eladkal wrote  - @stfines-clgx - upgrading some dependencies is one of the best contributions you might provide - if your organisation wants to upgrade a dependency in a free software that is mostly maintained by voluntaries, spending your company resources to upgrade those deps is one of the best ways your organisation pays back (and easy way to become a contributor).

This is easy - open a pr with updating a dependncy in provider.yaml of google provider (airflow/providers/google/provider.yaml that @eladkal added ) - and update it and fix all the problems in unit tests etc. that are result of it. 

Happy to help to review and guide you on that. Looking forward to it!
