### ISSUE TITLE
Why does airflow skips a day for a daily dag?

### ISSUE THREAD

**Issue by bobfang1992** [apache/airflow#13910] opened 2021-01-26 08:29 UTC
I have a newly created daily dag and I have set it up yesterday (Jan. 25th), once it is loaded by airflow I can see it is run once (scheduled_2021-0124T00:00:00+00:00), and then I manually triggered it once just to see if it works and it did (manual_2021-01-25). 

Now time is 08:24 UTC Jan 26th. But I did not see any run for 01-25. I have used `airflow dags next-execution` and found out airflow is planning to execute the dag for 01-26 directly, possibly on 01-27 00:00 UTC. So it will skip 01-25 entirely.

I am wondering why this behaviour? Is there any reason behind this?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/SYbEf.png

**Comment by jedcunningham** [comment] 2021-01-28 04:51
This is a duplicate of #13434.

**Closed as completed** 2021-01-28 16:44 UTC
Labels: kind:bug
