### ISSUE TITLE
Using a timedelta object as a Schedule Interval with catchup=False causes the start_date to no longer be honored

### ISSUE THREAD

**Issue by mpeteuil** [apache/airflow#14969] opened 2021-03-23 22:11 UTC
**Apache Airflow version**: 1.8 - 2.0.1 (tested against 1.10.4, 1.10.15, 2.0.1)

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): N/A

**Environment**:

- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**: Python 2.7.16, 3.7.6 (I don't think this is a factor)

**What happened**:

There is an issue with the scheduling of DAGs that use a `timedelta` object as the DAG `schedule_interval` argument while also having `catchup` set to `False`. What happens is that if you have a DAG that meets that criteria then when it's turned on it will ignore the time component of the start date and just run immediately.

This was previously reported in [[AIRFLOW-1156]](https://issues.apache.org/jira/browse/AIRFLOW-1156) and was closed with https://github.com/apache/airflow/pull/8776 which fixed the two dag runs problem that was also mentioned in that issue.

**What you expected to happen**:

I expect it to behave the same as a DAG using a cron expression for the `schedule_interval` under otherwise same conditions (i.e. `catchup` still set to `False`).

I believe this is a result of how [`Dag#following_schedule` and `Dag#previous_schedule` are implemented](https://github.com/apache/airflow/blob/1.10.15/airflow/models/dag.py#L409-L463). I traced the `SchedulerJob#create_dag_run` method and I believe this is due to the `Dag` methods used in there.

**How to reproduce it**:

Create two dags with `catchup` set to `False` that are exactly the same except that one will use a `timedelta` object as the `schedule_interval` argument and the other will use a cron expression. Set a `start_date` of sometime in the past. Turn them both on and you should see the one with a `timedelta` as the `schedule_interval` has disregarded the time part of the `start_date` and used the current time when it started executing as the time part of the `execution_date`. The version using the cron expression will have used the time from the cron expression.

Example DAG:

```py
import datetime as dt

from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator

dag_params = {
    'dag_id': 'schedule_interval_bug_example_dag',
    'default_args':{
        'owner': 'Administrator',
        'depends_on_past': False,
        'retries': 0,
        'email': ['example@example.com']
    },
    'schedule_interval': dt.timedelta(days=1),
    'start_date': dt.datetime(year=2021, month=1, day=1, hour=11, minute=10),
    'catchup': False
}

with DAG(**dag_params) as dag:
    DummyOperator(task_id='start') >> DummyOperator(task_id='end')
```

For the cron version just change the `schedule_interval` to `10 11 * * *`.

Here's a screenshot of this happening on 2.0.1 (although the bug exists in much older versions as well). The expectation would be that the `execution_date` displayed for both of the DAGs should have a time of **11:10:00**.

![Screen Shot 2021-03-23 at 5 54 53 PM](https://user-images.githubusercontent.com/459756/112223902-eb452d00-8c00-11eb-9380-60ccc8577ccb.png)

**Anything else we need to know**:

I've only tested this on DAGs that have a 1 day schedule interval, but testing with other intervals could reveal if this is a problem at finer grained intervals or if it's isolated to daily runs. Based on what I saw in `Dag#following_schedule` and `Dag#previous_schedule` I suspect this would be a problem with shorter intervals as well.

Tested with the `SequentialExecutor` and `StandardTaskRunner`, which I don't _think_ are a factor, but it's certainly possible.

Happy to provide other details or help in any way.

**Comment by kaxil** [comment] 2021-03-24 01:56
I don't think it is a bug. When you use `schedule_interval=timedelta(minutes=5)` it just tell scheduler to run every 5 minutes. Now when `catchup=False`, it tells scheduler to run first as soon as it can and then every 5 mins from then onwards.

This is the main difference between Cron vs Timedelta. While Cron does not take account of "last time", timedetla is dependent on the "last time". For example Cron `0 1 * * *` just says perform an action everyday at 1 am.

**Comment by mpeteuil** [comment] 2021-03-24 12:53
@kaxil I can see what you are saying, but it's still a little confusing. I have always assumed that something like `schedule_interval=timedelta(minutes=5)` would be every 5 minutes using the start date and time as the base from which to start. I think what's confusing about it is that if I provide an hour and minute in the `datetime` object I pass as the `start_date`, then having that get ignored completely is not intuitive. I remember reading in the issues a long time ago something about confusion in needing to line up the cron expression with the `start_date` as well, which is somewhat related. Perhaps the `start_date` was always meant to be just a date and not contain any time at all though.

If what you say is the intended behavior, then I think it's worth making that more explicit in the documentation. I don't see anywhere in the docs where this is mentioned. In particular I would have expected to see something about it on one of these pages:

https://airflow.apache.org/docs/apache-airflow/stable/tutorial.html
https://airflow.apache.org/docs/apache-airflow/stable/concepts.html
https://airflow.apache.org/docs/apache-airflow/stable/scheduler.html
https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html

I don't mind having a go at that, unless you or someone else would like to. Feel free to point me in the right direction of where you think something like that would belong. My initial thought would be scheduler or dag_run docs.

**Comment by KayleMaster** [comment] 2021-03-29 07:12
I just encountered this issue at work today. It turns out I cannot write a DAG that runs every 6 hours from 11:30. I tried with cron `0 */6 * * *` but of course that runs 00:00/06:00 etc (that's expected behaviour). I switched to the obvious start_date + timedelta combo. But it turns out it just uses the DAG unpause time as the new start_date??? 
Now I have to go around and do stupid things like writing schedules like `30 11,17,23,5 * * *` instead of just writing `timedelta(hours=6)`  
For an application which is basically a glorified scheduler, Airflow seems it's not even doing a good job in that place too.

**Comment by kaxil** [comment] 2021-05-29 19:29
https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-39+Richer+scheduler_interval should cover this and a lot more cases

**Comment by fmv1992** [comment] 2021-06-17 12:48
I'm also running into this problem using airflow version `1.10.15`.

**Comment by eladkal** [comment] 2022-01-16 12:45
AIP 39 is now released so this should be resolved.
Closing for now as no action item here.

**Closed as completed by eladkal** 2022-01-16 12:45 UTC
Labels: kind:bug, area:Scheduler
