### ISSUE TITLE
googleCloudStorageDeleteOperator URL encode "/"

### ISSUE THREAD

**Issue by gfelot** [apache/airflow#10585] opened 2020-08-26 15:45 UTC
**Apache Airflow version**: 1.10.9

**What happened**:

I want to delete temporary file at the end of my DAG in a GCS bucket. When I add the list of values in the arguments `object` I get an error that the file is not found. The reason is the symbole **/** is URL encoded **%2F**.

```
gcs_delete_temp = GoogleCloudStorageDeleteOperator(
    task_id="gcs_delete_temp",
    bucket_name=f"super_bucket",
    objects=[
        "rte/temp/{{ macros.ds_add(ds, -10) }}_injectee.parquet",
        "rte/temp/{{ macros.ds_add(ds, -10) }}_soutiree.parquet"
    ]
)
```
I got the error:  

> google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/super_bucket/o/rte%2Ftemp%2F2020-07-25_injectee.parquet: Not Found

I tried to escape them but the **\** symbole is URL encoded too.

Is that a bug ? Or a feature ?

**Comment by duthades** [comment] 2020-11-03 15:44
Hi, I would like to attempt to solve this issue. Can you assign me?

**Comment by duthades** [comment] 2020-11-03 19:16
This behaviour is correct. ```\``` is encoded when it appears in either the object name or query string of a request URI. Other characters which are encoded can be found [here](https://cloud.google.com/storage/docs/request-endpoints#encoding).

As far as the error ```404``` is concerned, it is because either [bucket or object name was not found](https://cloud.google.com/storage/docs/xml-api/reference-status#404%E2%80%94not-found).

**Comment by duthades** [comment] 2020-11-09 14:08
@eladkal I think the ```kind:bug``` tag can be removed as it's not a bug.

**Comment by potiuk** [comment] 2020-11-09 14:19
So closing the issue then

**Closed as completed by potiuk** 2020-11-09 14:19 UTC
Labels: provider:google, good first issue
