### ISSUE TITLE
Airflow unable to reserialize deleted DAG file

### ISSUE THREAD

**Issue by spattnaik2311** [apache/airflow#21329] opened 2022-02-04 15:50 UTC
### Apache Airflow version

2.0.1

### What happened

I accidentally deleted an Airflow DAG file from the filesystem (Ubuntu - meant to use `cp` but used `mv` instead).
At the time of deletion, the DAG already had a few successes along with a running job.

I only realised this a few minutes later and immediately copied the DAG back (it was the same exact file content & name).
But while the DAG was visible in the UI and it showed the history including the running status, clicking on the DAG name returned `airflow.exceptions.SerializedDagNotFound: DAG 'sms_collections_report_dag' not found in serialized_dag table` error. I got the same error while trying to view the running job too. Waited for a few hours but still got the same error.

### What you expected to happen

I expected the DAG to get added back to the dag bag in the next scheduler run, but it didn't happen.

### How to reproduce

- Delete DAG from the Ubuntu filesystem (I used mv but rm might have same effect too).
- Add exact DAG back into the same dag folder with same previous name.
- Try to view DAG run details in Airflow UI

### Operating System

Ubuntu 18.04

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by GitSpree23** [comment] 2022-02-04 15:53
This issue was resolved with the help of @potiuk , thanks!

I simply added a new line (and removed a commented line just to be safe!) Waited for a couple of minutes for the scheduler to do its job, and my DAG was back!

Of note: the executing task in the DAG run seems to be stuck in queued state (logs are preserved)

**Comment by potiuk** [comment] 2022-02-04 17:07
Was it closed by mistake? I thnk my "solution" was really a workaround but that seems like a valid edge-case that we might want to take a look liek

**Comment by spru23** [comment] 2022-02-07 10:42
It got closed by mistake, yes ... let me know if you need any more info

**Comment by ephraimbuddy** [comment] 2022-04-05 21:31
I was not able to reproduce this in the current main and 2.2.5. The dag was added back at the next cycle of dag parsing. @spru23, I'm going to close this, feel free to let me know if you are able to reproduce this in 2.2.5 or main

**Closed as completed by ephraimbuddy** 2022-04-05 21:31 UTC
Labels: kind:bug, area:core

**Comment by ThR3742** [comment] 2024-01-09 14:50
I am in 2.2.2 and have the same issue ; is there a way to fix this ?
