### ISSUE TITLE
downstram task are not inintiated and get upstream fail state while the upstream task is marked as success

### ISSUE THREAD

**Issue by HammadASiddiqui** [apache/airflow#33432] opened 2023-08-16 08:20 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hi,

I am using the follwing default args for a dag where most of the time the success routine is getting invoked but sometimes the task gets completed and in the logs the following message appears but the on_success_callback function is not invoked and resultantly the downstream is not initiated and all the downstream task give upstream fail state.

PFB the two logs that I observe

for normal runs:
```
[2023-08-16, 06:40:41 UTC] {{taskinstance.py:1280}} INFO - Marking task as SUCCESS. dag_id=fleet_data_export, task_id=db_incremental_invoices, execution_date=20230815T100500, start_date=20230816T063536, end_date=20230816T064041
[2023-08-16, 06:40:41 UTC] {{local_task_job.py:154}} INFO - Task exited with return code 0
[2023-08-16, 06:40:41 UTC] {{base.py:79}} INFO - Using connection to: id: slack_alerts_low. Host: https://hooks.slack.com/services, Port: None, Schema: , Login: , Password: ***, extra: {}
[2023-08-16, 06:40:41 UTC] {{logging_mixin.py:109}} WARNING - /usr/local/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py:1941 DeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'logical_date' or 'data_interval_start' instead.
[2023-08-16, 06:40:41 UTC] {{base.py:79}} INFO - Using connection to: id: slack_alerts_low. Host: https://hooks.slack.com/services, Port: None, Schema: , Login: , Password: ***, extra: {}
[2023-08-16, 06:40:41 UTC] {{http.py:140}} INFO - Sending 'POST' to url: https://hooks.slack.com/services***
[2023-08-16, 06:40:46 UTC] {{local_task_job.py:264}} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

for runs with problem
```
[2023-08-15, 19:04:05 UTC] {{taskinstance.py:1280}} INFO - Marking task as SUCCESS. dag_id=fleet_data_export, task_id=db_incremental_invoices, execution_date=20230815T100500, start_date=20230815T185859, end_date=20230815T190405
```

default_args for the dag:
```
default_args = {
    "owner": "Hammad Siddiqui",
    "email_on_retry": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
    "on_failure_callback": slack_notify_failure,
    "on_success_callback": slack_notify_success
}
```

### What you think should happen instead

I think that the routine triggered via on_success_call_back should be executed everytime in a consistent manner

### How to reproduce

do not have much idea on how to reproduce it

### Operating System

using MWAA environment

### Versions of Apache Airflow Providers

I am using airflow 2.2.2 version

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2023-08-19 16:27
There is not enough information to be able to diagnose it. This is a very old version of Airflow and there were 1000s of fixes since that version. Also MWAA might introduce it's own problems. so hard to say what the problem is. It can also be that the tasks can be prematurely closed by whatever deployment was used in MWAA and it has no chances of markign the task as success. 

Unless you could provide more evidence (for example correlating soe other logs/ MWAA logs) . I can only give one advice -  Please upgrade to latest version that is available in MWAA and check if the problem is gone.

Converting it to discussion if more discussion is needed.

**Closed as completed** 2023-08-19 16:27 UTC
Labels: kind:bug, area:core, needs-triage
