### ISSUE TITLE
Latest Botocore breaks SQS tests

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#31087] opened 2023-05-05 11:31 UTC
### Body

Our tests are broken in main due to latest botocore failing SQS tests.

Example here: https://github.com/apache/airflow/actions/runs/4887737387/jobs/8724954226

```
E           botocore.exceptions.ClientError: An error occurred (400) when calling the SendMessage operation: 
<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type>
<Code>AWS.SimpleQueueService.NonExistentQueue</Code><Message>The specified queue does not exist for this wsdl version.</Message><Detail/></Error>
<RequestId>ETDUP0OoJOXmn0WS6yWmB0dOhgYtpdVJCVwFWA28lYLKLmGJLAGu</RequestId></ErrorResponse>

```

The problem seems to come from botocore not recognizing just added queue:

```
QUEUE_NAME = "test-queue"
QUEUE_URL = f"https://{QUEUE_NAME}"
```

Even if we replace it with the full queue name that gets returned by the "create_queue" API call to `moto`, it still does not work with latest botocore:

```
QUEUE_URL = f"https://sqs.us-east-1.amazonaws.com/123456789012/{QUEUE_NAME}"
```

Which indicates this likely a real botocore issue.

## How to reproduce:

1. Get working venv with `[amazon]` extra of Airlow (or breeze). Should be (when constraints from main are used):
```
root@b0c430d9a328:/opt/airflow# pip list  | grep botocore 
aiobotocore                            2.5.0
botocore                               1.29.76
```
3. `pip uninstall aiobotocore`
4. `pip install --upgrade botocore`

```
root@b0c430d9a328:/opt/airflow# pip list  | grep botocore 
botocore                               1.29.127
```

6. `pytest tests/providers/amazon/aws/sensors/test_sqs.py` 

Result:

```
===== 4 failed, 7 passed in 2.43s === 
```

----------------------------------

Comparing it to "success case":

When you run it breeze (with the current constrained botocore):

```
root@b0c430d9a328:/opt/airflow# pip list  | grep botocore 
aiobotocore                            2.5.0
botocore                               1.29.76
```

1, `pytest tests/providers/amazon/aws/sensors/test_sqs.py`

Result:

```
============ 11 passed in 4.57s =======
```

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by potiuk** [comment] 2023-05-05 11:35
Possibly you can help @ferruzzi @o-nikolas @vincbeck  captured it here. 

I tried to fix it thinking this is a test framework issue and debugged it a bit (hence I know what full queue URL is returned when "create_queue" is called with moto, but this is as far as I could get without knowing the internals and since I used the "full URL" in my tests, I believe this might be a real issue in botocore library (but here my "explore, debug and fix tests" approach hit some limit).

**Comment by o-nikolas** [comment] 2023-05-05 16:07
Just checking in now. The repro steps you have here has all the tests passing, I'd suspect something to be failing? Looking into it now

**Comment by pankajastro** [comment] 2023-05-05 16:10
https://github.com/apache/airflow/pull/31094

**Comment by potiuk** [comment] 2023-05-05 16:20
So. It is this https://github.com/getmoto/moto/issues/6286 -> thanks @pankajastro for finding

**Comment by potiuk** [comment] 2023-05-05 16:33
Those steps reproducibly failed for me @o-nikolas :D.. Maybe it is "if in amazon = works" :D

**Comment by ferruzzi** [comment] 2023-05-05 16:36
Following along on this.   It does appear that the issue is with the latest botocore version not playing well with the new SQS API.

**Comment by potiuk** [comment] 2023-05-05 16:37
Actually looks like it's just the new botocore does not play well with moto - https://github.com/boto/botocore/issues/2930 so it's not as bad (for AWS).

**Comment by o-nikolas** [comment] 2023-05-05 16:40
> Those steps reproducibly failed for me @o-nikolas :D.. Maybe it is "if in amazon = works" :D

From your steps above I see 11 passed? 
```
"Result:

============ 11 passed in 4.57s =======
```

**Comment by potiuk** [comment] 2023-05-05 16:42
> ===== 4 failed, 7 passed in 2.43s ===



> > Those steps reproducibly failed for me @o-nikolas :D.. Maybe it is "if in amazon = works" :D
> 
> From your steps above I see 11 passed?
> 
> ```
> "Result:
> 
> ============ 11 passed in 4.57s =======
> ```

But few steps above (with different botocore version):

===== 4 failed, 7 passed in 2.43s ===

**Comment by potiuk** [comment] 2023-05-05 16:43
I separate those two "fail/pass" scenario more visibly :)

**Comment by o-nikolas** [comment] 2023-05-05 16:48
Okay, cool, we should be able close this now (unless we want to keep it open until moto releases a fix).

The related celery+SQS issues wont affect any CI here.

**Comment by potiuk** [comment] 2023-05-05 17:38
Yeah, Let's keep it.

**Comment by potiuk** [comment] 2023-05-05 17:39
I am subscribing to the issues to get notified when they are fixed

**Comment by vincbeck** [comment] 2023-05-05 18:39
Or we can just not use moto in `tests/providers/amazon/aws/sensors/test_sqs.py`. Only 4 tests are using moto. [Personal opinion]I never liked moto anyway[/Personal opinion]

**Comment by potiuk** [comment] 2023-05-05 19:28
PR reverting the workaround: https://github.com/apache/airflow/pull/31103

**Closed as completed** 2023-05-05 20:32 UTC
Labels: provider:amazon, kind:meta, affected_version:main_branch
