### ISSUE TITLE
Connections do not save since Airflow 2.1.0

### ISSUE THREAD

**Issue by soltanianalytics** [apache/airflow#17064] opened 2021-07-18 12:30 UTC
**Apache Airflow version**: Various - between `2.0.2` and `2.1.2`

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): n.a.

**Environment**:
- Docker running on Win 10 or Ubuntu 18.04 or Ubuntu 20.04 using the images
  - `apache/airflow:2.0.2-python3.8`
  - `apache/airflow:2.1.0-python3.8`
  - `apache/airflow:2.1.1-python3.8`
  - `apache/airflow:2.1.2-python3.8`

**What happened**:

Since Airflow `2.1.0`, saving or changing connections using the UI does not work anymore. When creating a new connection or attempting to change an existing one, the click on the `Save` button does not do anything.

<details><summary>Step 1: Go the create connection page and fill out the form</summary>

![image](https://user-images.githubusercontent.com/46958547/126066884-1390f6bc-c9e3-4ea0-97a7-e1ca190dddec.png)

</details>

<details><summary>
Step 2: Click on `Save`. For a very short amount of time (milliseconds), the UI changes to one that seems to show `all` custom connection type extra fields (see next screenshot), and then reverts back to the previous layout, without any message or saving anything. Effectively, it is not possible to change existing or create new connections using the UI.
</summary>

![image](https://user-images.githubusercontent.com/46958547/126066957-9ac52c2d-5c4a-4d52-9b88-952568253089.png)

</details>

**What you expected to happen**:

<details><summary>I'd like to see this screen again</summary>

![image](https://user-images.githubusercontent.com/46958547/126066856-a28807e7-cd90-4e3c-8b94-7c76a6a97c96.png)

</details>

**How to reproduce it**:

It seems to me that if this was behavior was the case for everyone, this would have been picked up already. Likely, this is related to the fact that I am maintaining a provider package ([ewah](https://github.com/Gemma-Analytics/ewah)). Simply changing the base image to the Airflow `2.0.2` version makes it work as expected, and any version since `2.1.0` show this bug. I'm not sure how to best reproduce this other than using the ewah repository, building it locally and switching the image between those version, as I am doing.

**Anything else we need to know**:

There are a lot of custom connections in this package. While writing this issue down, I had the idea to check if I accidentally called two extra fields the same by copy pasting them, and that this may break something since `2.1.0`. I'll update this issue if I find something along those lines; either way, if that was the case, I'd prefer it to throw an error rather than have a hard to debug issue.

UPDATE: Negative, I went through all custom connections and found nothing of concern.

**Comment by potiuk** [comment] 2021-07-19 09:09
Interesting. Do you think it is enough to reproduce it by just installing ewah package in the Airlfow Image? If so - I might take a stab on it today/tomorrow

**Comment by soltanianalytics** [comment] 2021-07-19 09:56
I develop the package locally using the `docker-compose.yml` file. You _could_
1. Clone the whole repo locally
2. Run `docker-compose up`

This should work in principle. Then you can locally adjust the `Dockerfile` to use various base images of different versions and see if you can reproduce the bug.

Note:
- By default, I match port `8084` with the port `8080` in the image (I've got too much going on @ 8080 :D ), so you'd need to go to `localhost:8084` to view the UI
- The default credentials are `username=ewah` and `password=ewah`

**Comment by soltanianalytics** [comment] 2021-07-19 09:59
Among other things, I overwrite the entrypoint in my Docker image - could it be that something changed in the original entrypoint script between `2.0.2` and `2.1.0` that I need to adjust on my side?

**Comment by potiuk** [comment] 2021-07-19 10:04
> Among other things, I overwrite the entrypoint in my Docker image - could it be that something changed in the original entrypoint script between 2.0.2 and 2.1.0 that I need to adjust on my side?

One thing that did change in 2.1.0 was that you do not need 'apply_defaults" in operators any more, but it should just generate warning rather than change behaviour. It's really interesting :). Must be a side effect of some subtle change.

**Comment by soltanianalytics** [comment] 2021-07-19 10:58
I don't use the `apply_defaults` decorator either way, but good to know :)

**Comment by potiuk** [comment] 2021-07-23 16:02
OK @soltanianalytics - found the problem. In mongo and airflow operator you  are using SelectField  which is not supported by Connection Form. I will add some protection for that in future Airflow (see #17193) but for now what can help is if you replace it with  text field and add custom validator that will only allow specific values.

Since we are going to mostly rewrite UI (and this mechanism will likely change anyway in Airflow 3), there is little point in investing in fixing SelectField (unless you would like to invest a little time and add support for it for example).

**Comment by potiuk** [comment] 2021-07-23 16:03
Workaround provided. Closing in favour of more detailed #17193

**Closed as completed by potiuk** 2021-07-23 16:03 UTC
Labels: kind:bug

**Comment by soltanianalytics** [comment] 2021-07-23 16:47
Very interesting, thank you for the support!

>unless you would like to invest a little time and add support for it for example

What would be needed for that? Where should I start / where to look into?

I'll probably phase them out for now, though, thanks!

**Comment by potiuk** [comment] 2021-07-25 16:06
I think it's a bit how the SelectField is validated in  javascript which is run while submitting the form. From what I saw, there were some client-side pre-validation failures generated by FAB client-side. I do not know that much about it to dig into it (and taking into account future of Airlfow WebUI, it is probably not worth it) :).  The check I've done on the server side will prevent from similar problems for others (With VERY explicit WARNING message and failing to load custom connection), so I think it's good as it is :).
