### ISSUE TITLE
Add replace_microseconds argument to trigger dag cli

### ISSUE THREAD

**Issue by MrParosk** [apache/airflow#27519] opened 2022-11-05 14:40 UTC
### Description

At the moment it seems you can't trigger a dag with the CLI with the flag "replace_microseconds": 

https://github.com/apache/airflow/blob/9337aa92c082db36e82eb314585591394fe8ff27/airflow/cli/commands/dag_command.py#L145

However, this argument seems to be available in the "trigger_dag" function: 

https://github.com/apache/airflow/blob/9337aa92c082db36e82eb314585591394fe8ff27/airflow/api/common/trigger_dag.py#L103

The proposal is to add this flag, e.g: airflow dags trigger --replace_microseconds=False ...

I'm willing to implement this, just wanted to check if this is a changed that is okay

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by o-nikolas** [comment] 2022-11-07 18:54
I see no reason for not plumbing that through, but others may know of a historical reason for it.

Assigning the task to you for now :)

**Comment by uranusjr** [comment] 2022-11-07 19:00
Duplicate of #25836

**Closed as not planned by uranusjr** 2022-11-07 19:00 UTC
Labels: duplicate

**Comment by o-nikolas** [comment] 2022-11-07 20:48
> Duplicate of #25836. Please still feel free to work on this and add a comment in the other issue so we can re-assign.

+1 to this! (note: we can't assign it to you until you leave a comment @MrParosk)
