### ISSUE TITLE
Secret variable is not masked in “Task Instance Details”

### ISSUE THREAD

**Issue by mkalamcargurus** [apache/airflow#30356] opened 2023-03-29 17:15 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I set a secret as a variable and Airflow recognizes it as such and masks the value when trying to view the variables and when it is referenced in the logs. However, you can see the value when you click on “Task Instance Details” for a DAG that is using the variable. 
MWAA 2.4.3

### What you think should happen instead

The secret value should be masked.

### How to reproduce

Add secret as a variable, name it password.
Use the secret in a DAG, our example we were using it in the DAG overrides block. 
Run an instance of the given DAG and navigate to the overrides section under 'Task Instance Details"

### Operating System

MWAA

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon | 6.0.0 | Amazon integration (including Amazon Web Services (AWS)).
apache-airflow-providers-celery | 3.0.0 | Celery
apache-airflow-providers-common-sql | 1.2.0 | Common SQL Provider
apache-airflow-providers-ftp | 3.1.0 | File Transfer Protocol (FTP)
apache-airflow-providers-http | 4.0.0 | Hypertext Transfer Protocol (HTTP)
apache-airflow-providers-imap | 3.0.0 | Internet Message Access Protocol (IMAP)
apache-airflow-providers-postgres | 5.2.2 | PostgreSQL
apache-airflow-providers-sqlite | 3.2.1 | SQLite

### Deployment

Amazon (AWS) MWAA

### Deployment details

mwaa

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by maahir22** [comment] 2023-03-30 10:03
If triaged, I'd like to work on this issue. Please /assign.

**Comment by potiuk** [comment] 2023-03-30 12:12
Feel free. You will be triaging it while working on it. If we find out the issue is not there, we will close it.

**Comment by mkalamcargurus** [comment] 2023-03-30 12:48
I'd be happy to help provide more info/screenshots if you needed.

**Closed as completed** 2023-04-14 21:08 UTC
Labels: kind:bug, area:UI, _eol_affected_version:2.4
