### ISSUE TITLE
Task status is not updating during run within TaskGroup on UI

### ISSUE THREAD

**Issue by marchinho11** [apache/airflow#18779] opened 2021-10-06 17:35 UTC
### Apache Airflow version

2.1.4 (latest released)

### Operating System

Ubuntu 20.04.3 LTS (Focal Fossa)

### Versions of Apache Airflow Providers

apache-airflow-providers-apache-hive==2.0.0
apache-airflow-providers-cncf-kubernetes==2.0.2; python_version >= "3.6" and python_version < "4.0"
apache-airflow-providers-ftp==2.0.1; python_version >= "3.6" and python_version < "4.0"
apache-airflow-providers-http==2.0.1; python_version >= "3.6" and python_version < "4.0"
apache-airflow-providers-imap==2.0.1; python_version >= "3.6" and python_version < "4.0"
apache-airflow-providers-oracle==2.0.1
apache-airflow-providers-postgres==2.2.0
apache-airflow-providers-sqlite==2.0.1; python_version >= "3.6" and python_version < "4.0"
apache-airflow-providers-ssh==2.1.1

### Deployment

Virtualenv installation

### Deployment details

Dag `Graph UI`:
<img width="801" alt="bug1" src="https://user-images.githubusercontent.com/22302313/136254640-3a7be2b6-6fe1-4e34-9e15-b153ba7cf9a6.png">

Dag `Tree View` (same time):
<img width="737" alt="bug2" src="https://user-images.githubusercontent.com/22302313/136254753-9be9bd2a-e528-4058-afc8-ae472bdd87de.png">

### What happened

Statuses of `Tasks`: `'running'`, `'queued'` don't update inside TaskGroup. New task statuses appear only with reclick on `TaskGroup`.

### What you expected to happen

I expect that statuses of `Tasks` are actual. Withou reclick on `TaskGroup`

### How to reproduce

Create `TaskGroup` with `Task`, run `DAG`, close `DAG` window and u will see empty statuses of tasks.

### Anything else

Problem occurs always.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment] 2021-10-06 20:46
I believe this is a duplicate of #18369

**Closed as completed** 2021-10-06 23:25 UTC
Labels: duplicate
