### ISSUE TITLE
trigger dag not showing start time and end time in the tree view

### ISSUE THREAD

**Issue by roshankp** [apache/airflow#18365] opened 2021-09-20 05:53 UTC
### Apache Airflow version

2.1.3

### Operating System

macosx

### Versions of Apache Airflow Providers

apache-airflow==1!2.1.3+astro.1
apache-airflow-providers-amazon==2.1.0
apache-airflow-providers-celery==2.0.0
apache-airflow-providers-databricks==2.0.0
apache-airflow-providers-ftp==2.0.0
apache-airflow-providers-google==5.0.0
apache-airflow-providers-http==2.0.0
apache-airflow-providers-imap==2.0.0
apache-airflow-providers-microsoft-mssql==2.0.0
apache-airflow-providers-mysql==2.1.0
apache-airflow-providers-opsgenie==2.0.0
apache-airflow-providers-postgres==2.0.0
apache-airflow-providers-sftp==2.1.0
apache-airflow-providers-slack==4.0.0
apache-airflow-providers-snowflake==2.1.0
apache-airflow-providers-sqlite==2.0.0
apache-airflow-providers-ssh==2.1.0

### Deployment

Astronomer

### Deployment details

Astro version 2.1.3 

### What happened

Recently upgraded the platform to 2.1.3 and observed issues with TriggerDagRunOperator Operator. The child dag object when triggered from parent dag is not showing the start time in the tree view.
Also start time are showing up as null in dag_run table.

    trigger_profile = TriggerDagRunOperator(
        task_id='trigger_profile', trigger_dag_id='child_dag'
    )
 
![image](https://user-images.githubusercontent.com/32855276/133961379-c95610ec-6d7a-492b-9aa1-6f3381d29ffd.png)

### What you expected to happen

ideally it should display timestamp.

### How to reproduce

- create two DAGS.
- dag_main.py
- dag_child.py
- create an operator in dag_main.py
-     trigger_dag_child = TriggerDagRunOperator(
        task_id='trigger_profile', trigger_dag_id='dag_child'
    )
- check start time  in child dag

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bhavaniravi** [comment] 2021-09-20 11:33
Same as #18082. PR  #18226 should fix this

**Comment by eladkal** [comment] 2021-09-20 13:22
Duplicate of https://github.com/apache/airflow/issues/18082

**Closed as completed by eladkal** 2021-09-20 13:22 UTC
Labels: kind:bug, duplicate, area:core
