### ISSUE TITLE
Airflow Triggerer facing frequent restarts

### ISSUE THREAD

**Issue by shubhransh-eb** [apache/airflow#33647] opened 2023-08-23 07:27 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

We are using airflow version: 2.6.3

We have the metastore in aws.

At around 12:00 AM PST, we have around 150+ async sensor starting at same time. They act as our sensors to wait for upstream data. We have them waiting for around 6-12 hours daily. Now after the upgrade, after running for 4-5 days we see that triggerer get restarts automatically. 

On investigation wee found that the query used by triggerer to get list of trigger is taking lot of time, causing the triggerer to kill python code and hence restart.

We are able to resolve it after doing analyze command on `task_instance` table.

Query used
```
select
    `trigger`.id as trigger_id,
    `trigger`.classpath as trigger_classpath,
    `trigger`.kwargs as trigger_kwargs,
    `trigger`.created_date as trigger_created_date,
    `trigger`.triggerer_id as trigger_triggerer_id,
    task_instance_1.try_number as task_instance_1_try_number,
    job_1.id as job_1_id,
    job_1.dag_id as job_1_dag_id,
    job_1.state as job_1_state,
    job_1.job_type as job_1_job_type,
    job_1.start_date as job_1_start_date,
    job_1.end_date as job_1_end_date,
    job_1.latest_heartbeat as job_1_latest_heartbeat,
    job_1.executor_class as job_1_executor_class,
    job_1.hostname as job_1_hostname,
    job_1.unixname as job_1_unixname,
    trigger_1.id as trigger_1_id,
    trigger_1.classpath as trigger_1_classpath,
    trigger_1.kwargs as trigger_1_kwargs,
    trigger_1.created_date as trigger_1_created_date,
    trigger_1.triggerer_id as trigger_1_triggerer_id,
    dag_run_1.state as dag_run_1_state,
    dag_run_1.id as dag_run_1_id,
    dag_run_1.dag_id as dag_run_1_dag_id,
    dag_run_1.queued_at as dag_run_1_queued_at,
    dag_run_1.execution_date as dag_run_1_execution_date,
    dag_run_1.start_date as dag_run_1_start_date,
    dag_run_1.end_date as dag_run_1_end_date,
    dag_run_1.run_id as dag_run_1_run_id,
    dag_run_1.creating_job_id as dag_run_1_creating_job_id,
    dag_run_1.external_trigger as dag_run_1_external_trigger,
    dag_run_1.run_type as dag_run_1_run_type,
    dag_run_1.conf as dag_run_1_conf,
    dag_run_1.data_interval_start as dag_run_1_data_interval_start,
    dag_run_1.data_interval_end as dag_run_1_data_interval_end,
    dag_run_1.last_scheduling_decision as dag_run_1_last_scheduling_decision,
    dag_run_1.dag_hash as dag_run_1_dag_hash,
    dag_run_1.log_template_id as dag_run_1_log_template_id,
    dag_run_1.updated_at as dag_run_1_updated_at,
    task_instance_1.task_id as task_instance_1_task_id,
    task_instance_1.dag_id as task_instance_1_dag_id,
    task_instance_1.run_id as task_instance_1_run_id,
    task_instance_1.map_index as task_instance_1_map_index,
    task_instance_1.start_date as task_instance_1_start_date,
    task_instance_1.end_date as task_instance_1_end_date,
    task_instance_1.duration as task_instance_1_duration,
    task_instance_1.state as task_instance_1_state,
    task_instance_1.max_tries as task_instance_1_max_tries,
    task_instance_1.hostname as task_instance_1_hostname,
    task_instance_1.unixname as task_instance_1_unixname,
    task_instance_1.job_id as task_instance_1_job_id,
    task_instance_1.pool as task_instance_1_pool,
    task_instance_1.pool_slots as task_instance_1_pool_slots,
    task_instance_1.queue as task_instance_1_queue,
    task_instance_1.priority_weight as task_instance_1_priority_weight,
    task_instance_1.operator as task_instance_1_operator,
    task_instance_1.queued_dttm as task_instance_1_queued_dttm,
    task_instance_1.queued_by_job_id as task_instance_1_queued_by_job_id,
    task_instance_1.pid as task_instance_1_pid,
    task_instance_1.executor_config as task_instance_1_executor_config,
    task_instance_1.updated_at as task_instance_1_updated_at,
    task_instance_1.external_executor_id as task_instance_1_external_executor_id,
    task_instance_1.trigger_id as task_instance_1_trigger_id,
    task_instance_1.trigger_timeout as task_instance_1_trigger_timeout,
    task_instance_1.next_method as task_instance_1_next_method,
    task_instance_1.next_kwargs as task_instance_1_next_kwargs
from
    `trigger`
    left outer join (task_instance as task_instance_1 inner join dag_run as dag_run_1
                     on dag_run_1.dag_id = task_instance_1.dag_id and dag_run_1.run_id = task_instance_1.run_id) on `trigger`.id = task_instance_1.trigger_id
    left outer join `trigger` as trigger_1 on trigger_1.id = task_instance_1.trigger_id
    left outer join job as job_1 on job_1.id = trigger_1.triggerer_id
where
        `trigger`.id in
        (); -- list of ids
```

It takes around 5-6 mins and when run analyze command it takes less than 1 second.

The number of sensor is same before and after upgrade.

### How to reproduce

- Upgrade to V2.6.3
- Swapn 150 sensors and wait (It doesnt happen every time but only some days

### Operating System

NAME="Debian GNU/Linux" VERSION_ID="11" VERSION="11 (bullseye)"

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by shubhransh-eb** [comment] 2023-08-23 09:55
Also adding a screenshot of how query numbers changes before and after `analyze` command 

![image](https://github.com/apache/airflow/assets/114397831/2dafd7de-101f-447a-8a38-ab74e055fd68)

**Comment by potiuk** [comment] 2023-08-24 18:26
Thanks for the detailed analysis and the cost breakdown before/after. This is super helpful.

Looks like an index hint should be needed or smth like that. Very interesting one. I will mark it for 2.7.1 hoping maybe  someone will have time to fix it before

**Comment by eladkal** [comment] 2023-08-24 20:25
2.6.3 had a known issue with trigger health which was fixed in 2.7.0 https://github.com/apache/airflow/pull/33089
I wonder if its related?

**Comment by shubhransh-eb** [comment] 2023-08-25 07:11
Hello @potiuk  thank you for the reply.

For now is there a way we can solve this, other than regularly running the `analyze` command on the tables?

**Comment by potiuk** [comment] 2023-08-25 09:05
No idea. Because I do not know the reason yet.

**Comment by potiuk** [comment] 2023-08-25 09:05
Someone will have to take a look and investigate it

**Comment by shubhransh-eb** [comment] 2023-08-25 09:16
Sure, thanks for help though :)

**Comment by Taragolis** [comment] 2023-08-30 22:44
> Looks like an index hint should be needed or smth like that. Very interesting one. I will mark it for 2.7.1 hoping maybe someone will have time to fix it before

To be honest better have a rule not to use `IN` with any potential big dataset. It really makes most RDBMS unhappy.

For example in Postgres everything in `IN` become part of execution plan, and if it quite a big, then DB spend most of the time for parse, trying build multiple different plans, calculate costs over a lot of different and in the end chouse 'lets take something', and time spend for this analyze might be greater than even do FULL SEQ SCAN over couple of tables.

In general better to get rid of non constant sized IN filters (couple statuses for tasks and dags) and replace by other methods:
- [NOT] EXISTS, for SEMI-ANTI Joins over subqueries
- JOIN over VALUES, in this case execution plans shouldn't be crazy, it should supported in PG, MySQL8 and MsSQL (RIP), maybe something similar exists for SQLite
- Regular Joins :D

@shubhransh-eb  I guess you use MySQL backend? If so, I wonder which version?

**Comment by Taragolis** [comment] 2023-08-30 22:55
And I currently think how to optimize or get rid off magic wrapper 

https://github.com/apache/airflow/blob/32a490e2cf380f57b58f187497352bd4dd49e869/airflow/utils/sqlalchemy.py#L535

**Comment by shubhransh-eb** [comment] 2023-08-31 04:36
> > Looks like an index hint should be needed or smth like that. Very interesting one. I will mark it for 2.7.1 hoping maybe someone will have time to fix it before
> 
> To be honest better have a rule not to use `IN` with any potential big dataset. It really makes most RDBMS unhappy.
> 
> For example in Postgres everything in `IN` become part of execution plan, and if it quite a big, then DB spend most of the time for parse, trying build multiple different plans, calculate costs over a lot of different and in the end chouse 'lets take something', and time spend for this analyze might be greater than even do FULL SEQ SCAN over couple of tables.
> 
> In general better to get rid of non constant sized IN filters (couple statuses for tasks and dags) and replace by other methods:
> 
> * [NOT] EXISTS, for SEMI-ANTI Joins over subqueries
> * JOIN over VALUES, in this case execution plans shouldn't be crazy, it should supported in PG, MySQL8 and MsSQL (RIP), maybe something similar exists for SQLite
> * Regular Joins :D
> 
> @shubhransh-eb I guess you use MySQL backend? If so, I wonder which version?

Hello ,
we are using `Aurora MySQL`
Engine Version: `5.7.mysql_aurora.2.11.2`

**Comment by shubhransh-eb** [comment] 2023-09-12 07:17
Not sure how much help this will provide, but we are facing this issue now around every week or max to max once every two keep.

Just to mitigate the issue, we have added alerts on top of our database (mysql) to get alert if CPU spikes (Because of frequency restart of triggerer) and then we are able to manually run the `analyze` command

**Comment by Taragolis** [comment] 2023-09-12 19:46
First of all I would recommend considering possibility of upgrading to a new version of MySQL, [5.7 it is almost EOL](https://endoflife.date/mysql), even if Amazon would support MySQL 5.7 on Aurora there is big chance that Airflow would stop support MySQL 5.7 in versions which released after **31 Oct 2023**. That mean that further improvements in triggerer would not available. In additional 8.0 should provide better query analyser/planner. Just make sure that you test migration on snapshot of DB before doing this on prod database. 

---

Anyway, I inspected data transfers between Triggerer and TriggerJob, it might help someone (maybe it was me) who want to optimise this:
1. [Load Triggers](https://github.com/apache/airflow/blob/8918b435be8c683bbd6bb2ffa871dbd31d476f48/airflow/jobs/triggerer_job_runner.py#L374-L378)
2. [All associated IDs with current Triggerer](https://github.com/apache/airflow/blob/87b08ad0840a11d8cd5c0b5043d3a341b1a8f258/airflow/models/trigger.py#L200)
3. [Update Triggers](https://github.com/apache/airflow/blob/8918b435be8c683bbd6bb2ffa871dbd31d476f48/airflow/jobs/triggerer_job_runner.py#L641)
4. [Bulk Load Triggers](https://github.com/apache/airflow/blob/87b08ad0840a11d8cd5c0b5043d3a341b1a8f258/airflow/models/trigger.py#L99-L110) - Query which might make a problem in case of huge input dataset
5. Put data in different different dequeue

Seems like 1-4 might be executed in one query with additional overhead on captured data but it might reduce time to execute on DB side, however required additional filtration on client (Airflow) side.

**Comment by shubhransh-eb** [comment] 2023-09-13 03:54
Hello @Taragolis 
Sorry for confusion, we use mysql version `8.0.28`.
-----

Just wanted to confirm, what you are suggesting is the query used for triggers need to be updated to solve this, correct?

**Comment by potiuk** [comment] 2023-09-13 06:09
> Just wanted to confirm, what you are suggesting is the query used for triggers need to be updated to solve this, correct? 

Let me explain how I see the options we have here (I have not done a detailed analysis what is wrong - those are a bit intelligent guesses).

I am not sure you can do much more NOW than analysing the tables periodically until the code of Airlfow is updated (but maybe you can also attempt to PR some changes).

Likely we need to load at the steps involved and optimise the way DB is used. Running analyse frequently should likely help you (and likely you can even schedule it every day for example) - but I think fundamentally someone (maybe @Taragolis or someone else) needs to optimise the way how we run queries to get rid of the effect you see in case you have huge amount of triggers happening.

The root cause is - I believe - that when you add an delete a lot of data, at some point in time the built-in optimiser of MySQL gets confused about what is the fastest execution plan to get the data, and likely produces the plan that is not-at-all optimised - I think the main reason for that is that indexes are never rebuilt and they grow in size when data is often deleted and added and at some point of time the optimizer sees that the index size is so big, that it is better and faster to not use the index at all. 

This is why "analyze" helps, because it looks at the actual data left and allows the optimizer to find a better and more optimized way to read the data, it rebuilds the index and makes it way smaller, and then the optimizer will start using it again/

I see two ways you could approach it:

1) optimize the code (suggested by @Taragolis ) by running less number of queries  but then it has to be done carefully, not using the ever-growing indexes and maybe dropping the indexes altogether. But that would require to change the way how we are using the DB.

2) we could also add hinting to the query, that would always force the plan that we know is optimal (but there we need to figure out which query and what plan is best, and maybe there are cases where it's not really the best one. But fundamentally if the index will be ever growing, this will break as well.

3) we could possibly rebuild the indexes from airflow side (but that's tricky - when? What to do with other tasks running?) 

Those are a bit guesses - maybe @Taragolis who have done a bit more analysis can also confirm if my thinking is right.

**Comment by shubhransh-eb** [comment] 2023-09-13 06:13
Thanks for suggestions @potiuk , For now we run `analyze` command if we see there is some issue.
Thanks for the help :)

**Comment by Taragolis** [comment] 2023-09-13 09:36
> Those are a bit guesses - maybe @Taragolis who have done a bit more analysis can also confirm if my thinking is right.

To be honest I've had a look after I found this issue initially and I was lying in bed and check code thought browser on iPad and just forgot to write a message. That mean all findings need to be verified first, I assume that we use this approach:
- It works in most cases
- We do not have triggerer states in DB, maybe for some optimisation reason.

The problem also that we operate with `set` on client side (Airflow) for ids before send to DB backend and even similar queries might be not so similar for DB. But this my assumption.

> we could also add hinting to the query

I like a position of some postgres-vendor developer about hint, something like "Maybe we want to have a hints in vanilla postgres, but not by same way it implemented in Oracle but in our product we need implements some close related stuff to make people who migrate from OracleDB to our product". In general it comes from the fact that statistic in most cases better when especially if it comes to the  COB (Cost Base Optimisation) or next-gen of COB

The problem with hint that it fix "Here and Now" and it might work in particular this case, with particular this amount data, particular this indexes, particular this amount of memory, for particular this user and as soon as some of parameters changes the things could become worser or not improve if this hints not exists.

This is just my personal position: "Query hint it is a solution of last resort after you try all other last resort solutions"

> Sorry for confusion, we use mysql version 8.0.28.

That is nice. 

> For now we run analyze command if we see there is some issue.

@shubhransh-eb I'm not an expert on MySQL but is any configuration exists which might potentially turn on/off auto gathering table statistic (aka ANALYZE)? Or it maybe by design you should manually run ANALYZE time to time.
 
If compare to Postgres I know exactly that autoanalyze daemon run in background and if user turned off then high intensive workloads query become slower over time. But even with postgres autoanalyze daemon in some cases better manually run AMALYZE TABLE especially after huge delete + insert

**Comment by shubhransh-eb** [comment] 2023-09-13 09:45
>@shubhransh-eb I'm not an expert on MySQL but is any configuration exists which might potentially turn on/off auto gathering table statistic (aka ANALYZE)? Or it maybe by design you should manually run ANALYZE time to time.

I am not an expert in MySQL either, but from what I found out on internet, I dont think MySQL automatically runs analyze command, that could be the reason why we have to manually run it to make this work.

**Comment by shubhransh-eb** [comment] 2023-09-13 09:46
Also in this case, this issue happen when we have around 150 sensors start around same time (within a min)

**Comment by Taragolis** [comment] 2023-09-13 18:23
> I am not an expert in MySQL either, but from what I found out on internet, I dont think MySQL automatically runs analyze command, that could be the reason why we have to manually run it to make this work.

I think MySQL should run something to gathering statistics without it hardly possible to calculate costs for the queries. Manual ANALYZE in this case something like: "Forget everything you know about the table and collect new statistics". 
If you don't know probably you don't know how to turn it off, I've asked because it was quite popular to turn-off auto-vacuum daemon in Postgres years ago and got all side effects 🤣 

> this issue happen when we have around 150 sensors start around same time

That also could be a reason. Again not expert of MySQL and no idea how it handle multiple simultaneous connection. In Postgres it is quite expensive operation time+memory. So base recommendation it was use some connection pooler between DB and AIrflow, internally Airflow use SQLaclhemy pooler but it limited by single process, so better have something bettween since you use Managed MySQL on AWS, you might try to use [RDS Proxy](https://aws.amazon.com/rds/proxy/)

---

And last but not least also might be a reason fact that most of the deferrable operators not truly async, especially something like [TaskStateTrigger](https://github.com/apache/airflow/blob/8918b435be8c683bbd6bb2ffa871dbd31d476f48/airflow/triggers/external_task.py#L39), which might kept session for very long time and prevent gathering statistic from database, it should not be a problem on Postgres, but who know maybe this is a problem for MySQL. This one my assumption.

**Comment by shubhransh-eb** [comment] 2023-09-23 04:42
So we had an incident in morning, where `analyze` command didnt help as well. 

We had to run following commands to bring back the table
```
ALTER TABLE task_instance STATS_SAMPLE_PAGES=256;
analyze
```

Our hunch is since trigger_id is set to `null` when work is done, and by default mysql value of STATS_SAMPLE_PAGES is 20, stats calculation is affected. When you have huge table (in our case 5M rows in task_instance) and it run analyze command with such low STATS_SAMPLE_PAGES (with a lot of them having null), it caches cardinality in wrong way.

we have updated the value in our table and will analyze it, but this could be a solution to set page_size for this table to be higher so that it can handle this.

**Comment by shubhransh-eb** [comment] 2023-11-08 05:10
Hello,
Just wanted to know if we have any update on this?

**Comment by potiuk** [comment] 2023-11-08 08:37
There is no other source of information for that than public issues if there are no updates, it means that there are no updates, generally. Possibly at some point in time before the next release all similar performance related issues might be look at by somene, but since it is volunteer driven effort, it may or might not happen. But if somene would like to look at it and try to apply a remedy - it is open for anyone to look at and fix it. 

But since you asked, here is my advice and a bit of context

There is no "support" or "someone to fix it" in OSS project like this. The sofware you get is free, you pay 0 for it and you get it without any promises and guarantees of things being fixed or even looked at. 

If some people will dedicate some of their free time on fixing it, they will take a look and might attempt to diagnose and fix it, but there is no SLAs or promises it will be fixed. Often when issues relate to previous versions of airlfow and there are no signs of similar issues being common and affectng more people, it might not drag attentions of thsoe who are trying to prioritize where they spend their free time after hours and on weekends.

However this also means that new versions of Airflow often solve similar problems because they are fixed while fixing other issues.

So the most rreasonable approach if you would like to "refresh" an issue and increase a chance it will be looked at and time spent on it is to upgrade your installation to the latest release (we just released 2.7.3 so I recommend that) and report back - if you still observe the issue there, maybe there are addional logs and observation you have maybe more evidences you might find, or maybe (hopefully) you will upgrade and the issue will be solved in latest version (then you can report it back and we can close the issue.

That would by my recommendation for you.

**Comment by shubhransh-eb** [comment] 2023-11-08 08:39
Thank you for the input and advice @potiuk

**Comment by QuintenBruynseraede** [comment] 2023-11-28 21:10
@shubhransh-eb I believe we're seeing the same issue on Airflow 2.7.2, though we are using an RDS Postgres instance. I'm looking for a starting point to do some more investigation. 
Some facts:

- Our triggerer stops heartbeating after roughly 20 seconds (give or take two heartbeat periods), presumably after taking up a decent amount of triggers. After `cfg.triggerer_health_check_threshold`, the liveness probes start failing.
- During normal load we are running about 150 triggers as well
- Performing a postgres `ANALYZE task_instance;` (or any other table involved in your query) did not resolve the issue for us  
- I can only reproduce this issue on our Production environment which has about 7 million task instances in the metadata DB. On an empty environment a single triggerer handles up to 1000 triggers without any issue

How did you find out where the triggerer loop is spending a lot of time in your case? I'm not able to get anything from the debug logs except the fact that no more heartbeats happen.

**Comment by shubhransh-eb** [comment] 2023-11-29 03:56
@QuintenBruynseraede , 

From what I observe, every min triggerer runs a query to find the number of triggers that are running at a given time. If query doesnt return anything in 1 min, it tries 5 time and then it kills the pod of triggerer and this is a continuous cycle, that is why your  liveness probes checks are failing.

Before running analyze command we set `STATS_SAMPLE_PAGES` (its for mysql) as well to solve the issue.

From what we figured out, airflow databases added a triggerer id to task where it is required, but when task is done it removes that id maying that column value as null. Now if you have large table size (3-4M+) there are max 15-20 rows with that column and hence when you run analyze command it doesnt help much because cardinality is still off. 
We increase page size so that it scans more rows to find cardinality and hence temporarily solves the issue.

other than this, we are trying to keep size of table to be around 3M by daily deleting old entries. Now sure if these 2 steps can help you as well.

**Comment by QuintenBruynseraede** [comment] 2023-11-29 09:57
Thanks for the response. I ran the commands [in this article](https://www.shanelynn.ie/postgresql-find-slow-long-running-and-blocked-queries/) to show long-running queries, and saw a query very similar to the on in your original post. It only ran for up to 30 seconds, though.
I also ran 
```
alter table task_instance alter column trigger_id set statistics 10000;
ANALYZE task_instance;
```
to minimize sampling during table analysis. This did not fix my issue so far.

I'll try to clean up old records and report back here.

**Comment by tirkarthi** [comment] 2023-12-08 11:20
@shubhransh-eb Can you please add the previous version of Airflow where it worked fine? We upgraded from Airflow 2.3.4 to 2.7.2. We are also using mysql 8 and faced the query taking a long time even with 1 trigger running entry in one of the environments where db migration was done in place and has lot of records in other tables. In the other environment db migration was done on a backup and restored database with less records. We found that by trial and error to making dag_run to load lazily helped triggerer process to run fine though list trigger page in UI still hangs on trying to use it with active triggers. It loads fine without lazy loading when there is no trigger though. I am not sure if its relevant to you but the query mentioned in the issue description was the same in our case taking long time and thought to add it here.

https://github.com/apache/airflow/blob/4824ca7c5a1e532ae19899f4b0d48c3216c7c871/airflow/models/trigger.py#L99-L110

Lazy load dag_run

```python
    def bulk_fetch(cls, ids: Iterable[int], session: Session = NEW_SESSION) -> dict[int, Trigger]:
        """Fetch all the Triggers by ID and return a dict mapping ID -> Trigger instance."""
        query = session.scalars(
            select(cls)
            .where(cls.id.in_(ids))
            .options(
                joinedload("task_instance").lazyload("dag_run"),
                joinedload("task_instance.trigger"),
                joinedload("task_instance.trigger.triggerer_job"),
            )
        )
        return {obj.id: obj for obj in query}
```

**Comment by shubhransh-eb** [comment] 2023-12-11 05:20
Hello @tirkarthi 
Thanks for reply, in our case we migrated from `2.5.1` to `2.6.3`

**Comment by QuintenBruynseraede** [comment] 2024-01-02 13:53
For what it's worth, I managed to fix this issue by cleaning up some old records from the `trigger` table. The table only had 88 rows, of which none were old than ±2 months. After cleaning up 27 records older than 1 month, the triggerers started heartbeating reliably again and are no longer restarting.

From 2.8.0 onwards `airflow db clean` has the option to clean that table (see https://github.com/apache/airflow/pull/34908). I just did it manually in a postgres shell.

**Comment by arunravimv** [comment] 2024-05-05 04:26
Hi Airflow Community, we faced the same issue on Airflow 2.7.3 (using AWS RDS MySql 8.0.35). For large airflow deployments with 1000s of active dags and large volume of records in TI table we think that this query is not making use of ti_trigger_id index. Here is a snapshot of MySQL explain forcing it work on all rows in TI table.

<img width="1528" alt="Screenshot 2024-05-05 at 12 19 30 PM" src="https://github.com/apache/airflow/assets/8220318/d9f6873a-acc9-4ec1-be71-0986fd82355c">

**Comment by arunravimv** [comment] 2024-06-20 07:55
Hi @eladkal , 

We've implemented a patch in which selectinload has supplanted joinedload during the bulk loading of Triggers. This alteration has led to a notable enhancement in performance. The SQL analysis outcomes, for both before and after the modification, are appended herewith. If this transformation appears acceptable, I'd be happy to initiate a Pull Request (PR) for more extensive dialogue.

<img width="911" alt="Screenshot 2024-06-20 at 3 49 07 PM" src="https://github.com/apache/airflow/assets/8220318/294b3de1-3e10-4b5b-8d9b-a2a863b3ae40">


#### joinedload
Airflow Code Snippet
```py
query = session.scalars(
    select(cls)
    .where(cls.id.in_(ids))
    .options(
        joinedload("task_instance"),
        joinedload("task_instance.trigger"),
        joinedload("task_instance.trigger.triggerer_job"),
    )
)
```

Explain Analyze
```sql
-> Nested loop left join  (cost=101 rows=95) (actual time=0.22..0.359 rows=3 loops=1)
    -> Nested loop left join  (cost=67.8 rows=95) (actual time=0.21..0.348 rows=3 loops=1)
        -> Nested loop left join  (cost=34.6 rows=95) (actual time=0.204..0.338 rows=3 loops=1)
            -> Filter: (`trigger`.id in (969,968,984))  (cost=1.36 rows=3) (actual time=0.049..0.0565 rows=3 loops=1)
                -> Index range scan on trigger using PRIMARY over (id = 968) OR (id = 969) OR (id = 984)  (cost=1.36 rows=3) (actual time=0.048..0.0545 rows=3 loops=1)
            -> Nested loop inner join  (cost=35.9 rows=31.7) (actual time=0.0915..0.0932 rows=1 loops=3)
                -> Index lookup on task_instance_1 using ti_trigger_id (trigger_id=`trigger`.id)  (cost=8.97 rows=31.7) (actual time=0.0716..0.0731 rows=1 loops=3)
                -> Single-row index lookup on dag_run_1 using dag_run_dag_id_run_id_key (dag_id=task_instance_1.dag_id, run_id=task_instance_1.run_id)  (cost=0.251 rows=1) (actual time=0.0194..0.0195 rows=1 loops=3)
        -> Single-row index lookup on trigger_1 using PRIMARY (id=task_instance_1.trigger_id)  (cost=0.251 rows=1) (actual time=0.00301..0.00305 rows=1 loops=3)
    -> Single-row index lookup on job_1 using PRIMARY (id=trigger_1.triggerer_id)  (cost=0.251 rows=1) (actual time=0.00316..0.00321 rows=1 loops=3)
```


#### selectinload
Airflow Code Snippet
```py
query = session.scalars(
    select(cls)
    .where(cls.id.in_(ids))
    .options(
        selectinload("task_instance"),
        joinedload("task_instance.trigger"),
        joinedload("task_instance.trigger.triggerer_job"),
    )
)
```

Explain Analyze
```sql
-> Nested loop inner join  (cost=5.26 rows=3) (actual time=0.0895..0.362 rows=3 loops=1)
    -> Nested loop left join  (cost=4.21 rows=3) (actual time=0.065..0.313 rows=3 loops=1)
        -> Nested loop left join  (cost=3.16 rows=3) (actual time=0.0521..0.298 rows=3 loops=1)
            -> Index range scan on task_instance using ti_trigger_id over (trigger_id = 968) OR (trigger_id = 969) OR (trigger_id = 984), with index condition: (task_instance.trigger_id in (969,968,984))  (cost=2.11 rows=3) (actual time=0.0399..0.273 rows=3 loops=1)
            -> Single-row index lookup on trigger_1 using PRIMARY (id=task_instance.trigger_id)  (cost=0.283 rows=1) (actual time=0.00755..0.00759 rows=1 loops=3)
        -> Single-row index lookup on job_1 using PRIMARY (id=trigger_1.triggerer_id)  (cost=0.283 rows=1) (actual time=0.00454..0.00458 rows=1 loops=3)
    -> Single-row index lookup on dag_run_1 using dag_run_dag_id_run_id_key (dag_id=task_instance.dag_id, run_id=task_instance.run_id)  (cost=0.283 rows=1) (actual time=0.016..0.016 rows=1 loops=3)
```

**Comment by eladkal** [comment] 2024-06-20 10:51
> I'd be happy to initiate a Pull Request (PR) for more extensive dialogue.

That would be best

**Comment by tirkarthi** [comment] 2024-06-29 17:14
@arunravimv We are also facing an issue where the trigger entry is inserted into the table but took 20-30 seconds to be picked up by triggerer itself causing delays between trigger creation and trigger being actually executed. We are using MySQL with large number of task instances and active dags. I was wondering by performance improvement did this patch help with reducing the delay or any other specific performance issue?

Thanks

**Comment by arunravimv** [comment] 2024-07-01 04:54
@tirkarthi we are able to load trigger based poll almost immediately (1-2 seconds), but I think this also depends on a lot of parameters like db configuration/load and the number of concurrent triggers and trigger processes you are running.

**Comment by josephangbc** [comment] 2024-07-04 07:45
Hi @eladkal, we have raised PR #40487. Could you help us to review it? Thank you!

**Closed as completed** 2024-09-18 17:36 UTC
Labels: kind:bug, area:performance, area:core, _eol_affected_version:2.6
