### ISSUE TITLE
execution date is missing from Task Instance tooltip

### ISSUE THREAD

**Issue by renzepost** [apache/airflow#32503] opened 2023-07-10 21:02 UTC
### Apache Airflow version

main (development)

### What happened

It seems [this](https://github.com/apache/airflow/commit/e16207409998b38b91c1f1697557d5c229ed32d1) commit has made the task instance execution date disappear from the task instance tooltip completely:
![image](https://github.com/apache/airflow/assets/18099224/62c9fec5-9e02-4319-93b9-197d25a8b027)
Note the missing `Run: <execution date>` between Task_id and Run_id.
I think there's a problem with the task instance execution date, because it's always `undefined`. In an older version of Airflow (2.4.3), I can see that the tooltip always shows the **current** datetime instead of the actual execution date, which is what the author of the commit identified in the first place I think.

### What you think should happen instead

The tooltip should properly show the task instance's execution date, not the current datetime (or nothing). There's a deeper problem here that causes `ti.execution_date` to be `undefined`.

### How to reproduce

Run the main branch of Airflow, with a simple DAG that finishes a run successfully. Go to the Graph view of a DAG and hover over any completed task with the mouse.

### Operating System

Ubuntu 22.04

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by utkarsharma2** [comment] 2023-07-11 07:12
@renzepost [commit](https://github.com/apache/airflow/commit/e16207409998b38b91c1f1697557d5c229ed32d1) seems to just have added the check in case the `execution_date` is not present. I don't think it's the cause of the issue.

**Comment by utkarsharma2** [comment] 2023-07-11 08:33
@renzepost You can refer to `run_id` after `manual__` as it's basically the same information as `exetution_date` which was changed in the PR - https://github.com/apache/airflow/pull/17719

**Comment by utkarsharma2** [comment] 2023-07-11 09:23
Based on the Slack thread - https://apache-airflow.slack.com/archives/CCWHRNBK7/p1689064000858439

Summary on the thread - Since a user can override the ru_id it is not reliable to lean on run_id always, for the same reason we can introduce another field in taskinstance`logical_date` which can hold this information and display it in UI. 

PR to override `run_id` - https://github.com/apache/airflow/pull/21851

**Comment by tirkarthi** [comment] 2023-07-11 17:13
The task instance is converted to dict using alchemy_to_dict but execution_date is not a column and a proxy to task_instance. So after forming the dict execution_date attribute value can be updated in the dict. I can raise a PR for this.

https://github.com/apache/airflow/blob/12d62e62c483a8f97119c3afe470ba06e250ea9a/airflow/www/utils.py#L84

**Comment by utkarsharma2** [comment] 2023-07-12 06:17
@tirkarthi Sure assigned it to you.

**Closed as completed** 2023-07-25 06:53 UTC
Labels: kind:feature, good first issue, area:core, area:UI
