### ISSUE TITLE
Add __init__.py to providers dir for mypy compatibility

### ISSUE THREAD

**Issue by Tonkonozhenko** [apache/airflow#16812] opened 2021-07-05 12:20 UTC
Currently, I'm running the next command to make mypy working correctly

```
touch /home/airflow/.local/lib/python3.8/site-packages/airflow/providers/__init__.py
```

Could you add this file by default or advice and I'll make PR?
I'm not familiar with the providers' architecture and I don't know where to add this hook.

**Comment by uranusjr** [comment] 2021-07-05 12:38
`airflow.providers` is a namespace package, and it should not contain a `__init__.py`. Mypy should be able to work with a namespace package, so either we are not configuring Mypy correctly, or this is a bug in Mypy. Either way, the issue should not be resolved by adding a `__init__.py`.

**Comment by mik-laj** [comment] 2021-07-05 13:10
This is a known issue and I recommend that you run mypy with a script that has a workaround for this.
https://github.com/apache/airflow/blob/b251d22fffad63124eec5246b80035408b543704/scripts/in_container/run_mypy.sh#L24-L27

**Comment by ashb** [comment] 2021-07-07 10:30
Close, won't fix. By design.

**Closed as completed by ashb** 2021-07-07 10:30 UTC
Labels: kind:bug
