### ISSUE TITLE
Close open connections for deferrable SFTPSensor

### ISSUE THREAD

**Issue by Christopher-Gentle** [apache/airflow#39922] opened 2024-05-29 21:14 UTC
### Apache Airflow Provider(s)

sftp

### Versions of Apache Airflow Providers

4.10.0

### Apache Airflow version

2.7.2

### Operating System

Amazon Linux

### Deployment

Amazon (AWS) MWAA

### What happened

While a fix was implemented for methods: list_directory, read_directory and get_files_and_attrs_by_pattern; The fix was left off of the get_mod_time method.

`ssh_conn = await self._get_conn()
sftp_client = await ssh_conn.start_sftp_client()`

When a user tries to use the SFTPSensor operator, using path/newer_than, it will open a connection and remain open.

### What you think should happen instead

Implement context/resource management in method get_mod_time for the ssh_conn.

This will close the sftp-server on the remote host.

### How to reproduce

`sense_sftp_file = SFTPSensor(
            task_id=f"sense_sftp_file",
            sftp_conn_id="sftp_default_id",
            path="/tmp/test.txt",
            poke_interval=120,
            newer_than="{{  (macros.datetime.utcnow() - macros.timedelta(hours=24)) }}",
            timeout=timedelta(hours=1),
            deferrable=True,
        )`

### Anything else

Anytime this operator is used with path and newer_than parameters.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2024-05-30 00:39
Marked it as good-first-issue. Feel free to implement a fix as PR (this is the most certain way to get it fixed) -  if you want to get it fixed - otherwise it will have to wait for someone to pick it and fix it.

**Comment by pateash** [comment] 2024-05-31 13:02
@eladkal could you please assign this to me.

**Comment by pateash** [comment] 2024-05-31 14:08
The issue is in both **deferrable=True** and normal mode.
even if the file is found, Sensor keeps running


![image](https://github.com/apache/airflow/assets/16856802/97c7d601-b0fc-4737-8f52-6a8a002d2764)

**Closed as completed** 2024-06-07 12:54 UTC
Labels: kind:bug, area:providers, good first issue, provider:sftp
