### ISSUE TITLE
Airflow clear does not respect start_date parameter?

### ISSUE THREAD

**Issue by mtustin-handy** [apache/airflow#799] opened 2015-12-22 05:34 UTC
This command will clear all instances for all time, and not just those that follow 2015-10-22

```
/airflow/bin/airflow clear -t ingest_  --start_date='2015-10-22' data_pipeline
```

**Comment by r39132** [comment] 2015-12-23 00:11
Try `airflow clear data_pipeline -s 2015-10-22 -e 2015-10-22` if you just want to clear one day. If you want to clear more than one day, then try something like `airflow clear data_pipeline -s 2015-10-22 -e 2015-10-24`. If you run an hourly DAG, then you can also do `airflow clear data_pipeline -s 2015-10-22T00:00:00 -e 2015-10-22T23:00:00` to clear 24 hours for one day.

**Comment by r39132** [comment] 2015-12-23 00:14
Also, it would help if you reported your version. I am running the latest master as of a 5 days ago, so I have a pretty fresh copy.

**Comment by r39132** [comment] 2016-02-10 06:55
I am running the following for the code listed on https://gist.github.com/r39132/b22671d0293cd7740b38
`airflow clear -t foo_1 -s 2016-02-04T00:50:00 test_s3_sensor`

The command shows me : 

```
You are about to delete these 8 tasks:
<TaskInstance: test_s3_sensor.foo_1 2016-02-04 00:50:00 [success]>
<TaskInstance: test_s3_sensor.foo_1 2016-02-04 00:51:00 [success]>
<TaskInstance: test_s3_sensor.foo_1 2016-02-04 00:52:00 [success]>
<TaskInstance: test_s3_sensor.foo_1 2016-02-04 00:53:00 [success]>
<TaskInstance: test_s3_sensor.foo_1 2016-02-04 00:54:00 [success]>
<TaskInstance: test_s3_sensor.foo_1 2016-02-04 00:55:00 [success]>
<TaskInstance: test_s3_sensor.foo_1 2016-02-04 00:56:00 [success]>
<TaskInstance: test_s3_sensor.foo_1 2016-02-04 00:57:00 [success]>
```

Which is correct according to the Tree View below :

<img width="901" alt="screenshot 2016-02-09 22 51 26" src="https://cloud.githubusercontent.com/assets/581734/12940608/b981436e-cf7f-11e5-8b44-0d15e71572ea.png">

When I choose `yes`, my tree view looks like the picture below with 8 new blank squares appearing in the `foo_1` task only for the dates displayed above:
<img width="890" alt="screenshot 2016-02-09 22 53 19" src="https://cloud.githubusercontent.com/assets/581734/12940632/f8275aea-cf7f-11e5-870d-c3dcbf51f266.png">

I cannot reproduce your bug and am therefore closing.

**Closed as completed by r39132** 2016-02-10 06:55 UTC
