### ISSUE TITLE
color of task state in task tries doesn't work for retries

### ISSUE THREAD

**Issue by schlichterer** [apache/airflow#42018] opened 2024-09-05 08:20 UTC
### Apache Airflow version

2.10.0

### What happened?

The task try color does not display for tasks that result from retries. 
![tempsnip](https://github.com/user-attachments/assets/faa85de0-f5e6-48d0-94b1-084668f5bca3)
Task try no.2 originally failed and created a retry. 3-8 failed and created retries but show no state color. Task try no.9 finally succeded which changed the color for task no.2 to success which actually failed.

### What you think should happen instead?

I think the color should represent the actual task try state.

### How to reproduce

Enable retries on the dag and let a task fail on purpose. 

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by raphaelauv** [comment] 2024-09-05 08:47
duplicate of https://github.com/apache/airflow/issues/41742 ?

**Comment by schlichterer** [comment] 2024-09-05 09:20
Yes sorry thank you I didn't find that one.

**Closed as completed** 2024-09-05 09:20 UTC
Labels: kind:bug, area:core, area:UI, needs-triage
