### ISSUE TITLE
Clearing a Mapped Task (with Downstream included) clears all Downstream tasks instead of mapped downstream tasks

### ISSUE THREAD

**Issue by gavinhonl** [apache/airflow#41278] opened 2024-08-06 08:35 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.2

### What happened?

If a mapped task is Cleared (with Downstream), all downstream tasks are cleared.

Clearing from the parent task. UI correctly shows 'All mapped tasks' for Map Index with the expected 1598 affected tasks:
![image](https://github.com/user-attachments/assets/606ab098-ed66-4174-bf4f-f4b790e27177)

Clearing the Mapped task. UI correctly shows the Map Index ie. 0 but the number of affected tasks are 1523:
![image](https://github.com/user-attachments/assets/06255fa5-cc77-46e6-83c7-fac66d661d34)
This equals the first scenario (a total of 1598 tasks) minus the number of Mapped tasks (76) plus the mapped task being cleared itself.
![image](https://github.com/user-attachments/assets/b4bbad13-7d80-4547-98d3-bf46bc1831b8)

### What you think should happen instead?

I would expect only mapped tasks with the same Map Index and/or direct downstream tasks to be affected when a Mapped task is Cleared (with Downstream). In this specific scenario it would be equal to 24 affected tasks.

### How to reproduce

Clear a mapped task (with Downstream included) and observe the number of affected tasks.

### Operating System

Ubuntu 22.0.4

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

AWS EKS

### Anything else?

100% Reproducible

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by harjeevanmaan** [comment] 2024-08-06 11:33
I would like to work on this issue. Similar issue raised here:  #40543

**Comment by gavinhonl** [comment] 2024-08-07 04:21
@harjeevanmaan - Thanks, no issues on my end.

**Comment by eladkal** [comment] 2024-08-07 19:57
@bbovenzi this is somehow related to issue I discussed with you about clearing procedure of specific index with this index downstream

**Comment by shahar1** [comment] 2024-12-14 07:10
In a short delay - closing this issue as duplicate of #40543.
If any of you want to continue working on it, please ask for assignment there.

**Closed as not planned by shahar1** 2024-12-14 07:10 UTC
Labels: kind:bug, area:core, area:dynamic-task-mapping
