### ISSUE TITLE
Airflow + AWS SES HTTP Api: Error Invalid type for parameter Source, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

### ISSUE THREAD

**Issue by tl-soonam-panda** [apache/airflow#16938] opened 2021-07-12 09:32 UTC
**Apache Airflow version**: v2.0.1
**Executor** : KubernetesExecutor
**Environment**: Kubernetes-cluster

**What happened**:

I am trying to configure airflow to send an email using AWS SES(HTTP not SMTP) email backend. The configuration is done according to https://airflow.apache.org/docs/apache-airflow/stable/howto/email-config.html. But I always get an error "Invalid type for parameter Source".  
This comes from AWS API where it validates the input source/from-email parameter, which should not be null. But, the airflow email API does not send this parameter code snippet below(ref: https://github.com/apache/airflow/blob/main/airflow/utils/email.py). So my question is how to send the source/from-email parameter. Is there any configuration parameter airflow config file or it takes from AWS IAM credential. I am using AWS IAM credential set with AIRFLOW__EMAIL__EMAIL_CONN_ID parameter in airflow.

1. Try to configure SES HTTP API backend from airflow
2. Create one EmailOperator and pass all the parameters.(There is from_email parameter actually)
3. Internally the backed will be loaded and aws/ses.py will be called and the error will be thrown.

**Comment by uranusjr** [comment] 2021-07-14 02:03
I think this is the same as #16166?

**Comment by potiuk** [comment] 2021-07-19 20:43
Duplicate of #16166

**Closed as completed by potiuk** 2021-07-19 20:43 UTC
Labels: kind:bug, duplicate
