### ISSUE TITLE
GoogleCampaignManagerReportSensor not working correctly on API Version V4

### ISSUE THREAD

**Issue by jel476** [apache/airflow#29538] opened 2023-02-14 15:13 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hello,

My organization has been running Airflow 2.3.4 and we have run into a problem in regard to the Google Campaign Manager Report Sensor. The purpose of this sensor is to check if a report has finished processing and is ready to be downloaded. If we use API Version: v3.5 it works flawlessly. Unfortunately, if we use API Version v4, the sensor malfunctions. It always succeeds regardless of whether the report is ready to download or not. This causes the job to fail downstream because it makes it impossible to download a file that it is not ready.

At first this doesn't seem like a big problem in just using v3.5. However, Google announced that they are going to only let you use API version v4 starting in a week. Is there a way we can get this resolved 😭? 

Thanks!

### Operating System

linux?

### Deployment

Composer

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2023-02-14 18:13
There are several google services that require attention
https://github.com/apache/airflow/issues/27292

PRs are welcome. This is one of the cases that best auited to be handled by a user of the service / someone from Google

**Comment by jel476** [comment] 2023-02-14 18:20
Google support linked me to this issues forum 🥺

**Comment by eladkal** [comment] 2023-02-14 18:47
> Google support linked me to this issues forum 🥺

That is unfortunate.
This is open source project people contribute on their free will so as i said PRs are welcome.
@lwyszomi maybe you can ping someone in Google to take this task before planned deprecation? I'm willing to assist with cutting RC version for Google provider as soon as fix is merged but someone will need to take this take and implement it.

**Comment by eladkal** [comment] 2023-02-14 18:50
BTW @jel476 I should have asked first. Which sensor are you referring to? I don't see Google ads sensor in the project. can you please link to the relevant file?

**Comment by lwyszomi** [comment] 2023-02-16 06:56
@eladkal we are working on some of deprecations, and this is also in our plans to fix soon.

**Comment by eladkal** [comment] 2023-04-15 13:29
@jel476 fix is in https://github.com/apache/airflow/pull/30598 by @VladaZakharova 
It will be available in the next provider release.

From what I see in the fix the issue is only with the default value of `api_version` thus nothing prevents you from using version 4 of the api with older versions of the google provider simply pass the version you use explicitly.

**Closed as completed** 2023-04-15 13:34 UTC
Labels: provider:google, area:providers, good first issue, kind:task
