### ISSUE TITLE
Provide official airflow chart 

### ISSUE THREAD

**Issue by eugene-chernyshenko** [apache/airflow#8270] opened 2020-04-13 17:22 UTC
Could you please provide official chart for your image.

The stable/airflow chart was created for image puckel/docker-airflow.

There are specific features in the puckel/docker-airflow entrypoint you don't have

such as 
https://github.com/puckel/docker-airflow/blob/master/script/entrypoint.sh#L13
https://github.com/puckel/docker-airflow/blob/master/script/entrypoint.sh#L57

So your image won't work with stable/airflow correctly

**Comment by rcjsuen** [comment] 2020-04-13 19:54
@eugene-chernyshenko There is an [ongoing discussion](https://lists.apache.org/thread.html/r55b09d63a809428c20ca3317801cad5a86ac939478e0dbd8e93f0fee%40%3Cdev.airflow.apache.org%3E) about this on the dev@airflow.apache.org mailing list.

**Comment by potiuk** [comment] 2020-04-14 13:18
Indeed. We are working on the helm chart with @dimberman and there already few suggestions on the changes that will need to be added to the image/helm chart, some of them also being discussed for example in this slack discussion: https://apache-airflow.slack.com/archives/CQAMHKWSJ/p1586556315075700

Would you mind describing the use case that you would like to be handled this way?

Some context: just linking to specific lines in Puckel is not enough - the idea is that we want to implement use cases that people want to have - not necessarily in the same way Puckel image/helm chart addressed so far. Rather than copying everything from Puckel/current help chart has, we decided to start from basics and add things as our users will tell us need (but sometimes in a different way that might be easier for community to manage).

So .. How would you explain your use case @eugene-chernyshenko?

**Comment by ashb** [comment] 2020-04-16 16:56
We are actively working on making https://github.com/astronomer/airflow-chart/ suitable for wider use

**Comment by jacobhjkim** [comment] 2020-06-26 05:27
Can we close this since https://github.com/apache/airflow/tree/master/chart this was merged?

**Comment by potiuk** [comment] 2020-06-26 09:05
I think we have a few things to fix/update  and we will close it when we release 1.10.11 with the official chart in

**Comment by ryw** [comment] 2020-11-30 18:46
Moved milestone to 2.1 since we won't release official Helm chart with 2.0.

**Comment by kaxil** [comment] 2021-02-17 00:29
Duplicate of https://github.com/apache/airflow/issues/10752

**Closed as completed by kaxil** 2021-02-17 00:29 UTC
Labels: kind:feature, area:helm-chart
