### ISSUE TITLE
Datasets tab/information not visible in UI

### ISSUE THREAD

**Issue by nickhealy** [apache/airflow#43685] opened 2024-11-05 10:15 UTC
### Apache Airflow version

2.10.2

### What happened?

I am using an admin role that has full permissions over datasets. When I press on button to view more detail about a detaset, it flickers on for a second and then says I do not have permission. I also do not see any "Dataset" tab in my UI. 

https://github.com/user-attachments/assets/4f8e5b12-cec8-4e05-b0c9-b11d3d6e0ade

### What you think should happen instead?

From reading the docs, I understand that there should be a Dataset tab visible for me to view. I also have all of the permissions I need. I am using the demo DAGS from airflow. 

### How to reproduce

Run a webserver, run scheduler, use one of the dataset-based example DAGS. 

### Operating System

Mac OS Sonoma 14.7.1

### Versions of Apache Airflow Providers

Providers info
apache-airflow-providers-common-compat | 1.2.1 
apache-airflow-providers-common-io     | 1.4.2 
apache-airflow-providers-common-sql    | 1.18.0
apache-airflow-providers-fab           | 1.4.1 
apache-airflow-providers-ftp           | 3.11.1
apache-airflow-providers-http          | 4.13.1
apache-airflow-providers-imap          | 3.7.0 
apache-airflow-providers-smtp          | 1.8.0 
apache-airflow-providers-sqlite        | 3.9.0 

### Deployment

Other

### Deployment details

Running locally in a conda environment

### Anything else?

server logs: 

```
127.0.0.1 - - [05/Nov/2024:04:14:29 -0600] "GET /datasets?uri=s3%3A%2F%2Fdag1%2Foutput_1.txt HTTP/1.1" 302 197 "http://localhost:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
127.0.0.1 - - [05/Nov/2024:04:14:29 -0600] "GET /home HTTP/1.1" 200 42995 "http://localhost:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"
127.0.0.1 - - [05/Nov/2024:04:14:30 -0600] "POST /last_dagruns HTTP/1.1" 200 2 "http://localhost:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by andysouthcombe** [comment] 2024-11-05 16:39
We have a similar issue.  Since upgrading to 2.10.2 the datasets menu tab is no longer visible.  When I try to browse directly to the datasets url (<airflow base url>/datasets) I get an "access is denied" message.  I've verified my user's role still has the relevant dataset permissions using the Airflow CLI.  I've tested locally and found:

- Airflow versions 2.10.0 and 2.10.1 display the datasets menu tab normally
- Airflow versions 2.10.2 and 2.10.3 no longer display the datasets tab

So it looks like something broke in 2.10.2 or there was some behaviour change that isn't obvious from the release notes.

**Comment by vatsrahul1001** [comment] 2024-11-05 17:19
@nickhealy @andysouthcombe what version of `apache-airflow-providers-fab` you are using?

**Comment by andysouthcombe** [comment] 2024-11-05 19:12
Looks like apache-airflow-providers-fab==1.4.1 for me

**Comment by andysouthcombe** [comment] 2024-11-05 19:16
Looks like upgrading that to 1.5 might fix the issue for me.   We installed airflow 2.10.2 with poetry and we ended up with 1.4.1, but upgrading to apache-airflow-providers-fab==1.5 has made the datasets tab reappear

**Comment by vatsrahul1001** [comment] 2024-11-06 04:16
Yes `1.5 ` has the fix

**Comment by vatsrahul1001** [comment] 2024-11-06 04:16
Closing this as confirmed upgrading to `apache-airflow-providers-fab==1.5` fixed the issue

**Closed as completed by vatsrahul1001** 2024-11-06 04:16 UTC
Labels: kind:bug, pending-response, area:core, area:UI, area:data-aware-scheduling
