### ISSUE TITLE
Search Function Not Working in Airflow UI

### ISSUE THREAD

**Issue by buu-nguyen** [apache/airflow#33895] opened 2023-08-29 16:59 UTC
### Apache Airflow version

2.7.0

### What happened

Actual Behavior:
Upon entering a keyword in the search bar, no search results are shown, and the UI remains unchanged. The search function seems to be non-responsive.
You can see in the address bar, `undefined` appears instead of valid value.
<img width="1427" alt="step-1" src="https://github.com/apache/airflow/assets/17428690/10da4758-a614-48c8-a926-6bc69f8595f1">
<img width="1433" alt="step-2" src="https://github.com/apache/airflow/assets/17428690/be8912f2-e49e-40ca-86f7-1803b516482e">

### What you think should happen instead

Expected Behavior:
When I use the search function in the Airflow UI, I expect to see a list of results that match the entered keyword. This should help me quickly locate specific DAGs or tasks within the UI.

### How to reproduce

Steps to Reproduce:
1. Log in to the Airflow UI.
2. Navigate to the "Connections" list view by clicking on the "Connections" link in the navigation menu or by directly visiting the URL: <your_airflow_ui_url>/connection/list/.
3. Attempt to use the search function by entering a keyword.
4. Observe that no search results are displayed, and the search appears to do nothing.

### Operating System

MacOS

### Deployment

Other

### Deployment details

Standalone Airflow via official Quickstart documentation

### Anything else

I encounter this issue since `Airflow 2.6.0`. It was fine on `Airflow 2.5.3`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by SamWheating** [comment] 2023-08-29 18:47
I have replicated this issue in Breeze on main, it looks like the `contains` and `equal to` filters are broken on both connections and dagruns page (likely others too, but I didn't check everywhere). 

Feel free to assign to me and I'll keep investigating.

**Comment by Usiel** [comment] 2023-08-30 04:04
In the meantime, here's a workaround for people who depend on this: Replace the `undefined` part with the corresponding filter op index. For example, to do "run_id contains needle" you replace the invalid query param `"_flt_undefined_dag_id=needle"` with `"_flt_2_dag_id=needle"`. Why 2 in this case? Because "contains" is the 2nd operation in the list (0 based index).

**Comment by SamWheating** [comment] 2023-08-30 17:29
I have done some looking and I think that this is due to this change:
https://github.com/dpgaspar/Flask-AppBuilder/pull/2039/files

Which was created in response to another airflow issue:
https://github.com/apache/airflow/issues/31156

So anytime we change the filter (i.e, selecting the non-default filter type) the changeOperation function returns `undefined` rather than a correct filter index, which is why we end up with `_flt_undefined_` in the form data.

Verified this by setting a breakpoint and then getting the index the old way and the new way:
```
e.value
> '2'
$(e.target).val()
> undefined
```

We could just open a revert in FAB, but I want to ensure that we don't re-introduce the original issue.

**Comment by VVildVVolf** [comment] 2023-08-30 18:51
That's weird, since I see vice versa for 2.7.0
<img width="1005" alt="image" src="https://github.com/apache/airflow/assets/5997744/e82682f5-94e6-45d2-b7ff-985fd63c96cb">
```.val()``` looks still recommended way to get the value: https://github.com/select2/select2/blob/9ce61fd297fd2922fe771debea8b24dfd219a49a/src/js/select2/core.js#L536

Possibly I am doing something wrong, will take a look deeply.

**Comment by SamWheating** [comment] 2023-08-30 19:15
Ah, looks like this was fixed in https://github.com/dpgaspar/Flask-AppBuilder/pull/2079, which was released in 4.3.4

I have confirmed that this fixes things by upgrading FAB in breeze and then restarting the webserver.

**Closed as completed** 2023-08-31 06:03 UTC
Labels: kind:bug, good first issue, area:UI, affected_version:main_branch
