### ISSUE TITLE
Negsignal.SIGKILL error on macOS

### ISSUE THREAD

**Issue by mariuszliksza-kinesso** [apache/airflow#10435] opened 2020-08-20 21:52 UTC
**Apache Airflow version**:
1.10.9

**Environment**:
macOS Catalina, 10.15.6

**What happened**:
When I am running my workflow in Apache Airflow using docker (especially using Local Executor) I am sometimes getting this error: **INFO - Task exited with return code Negsignal.SIGKILL** 
This usually appears when the task consumes a lot of CPU resources. 
I have tried to set the limit in docker-compose yaml file for CPUS and memory but it did not help. 
The same process works fine on Windows/Linux machines of my colleagues. 

**What you expected to happen**:
I would like to understand why it happens only on macOS and how can I handle that. 

**How to reproduce it**:
I can share the code that is always failing with the above issue when I am using Local Executor but it just works when I switch to Sequential Executor. 

**Anything else we need to know**:

**Comment by nasir-bhanpuri** [comment] 2020-09-15 20:05
I am running into a similar issue with Airflow 1.10.10 using Docker on macOS.

**Comment by mariuszliksza-kinesso** [comment] 2020-09-16 06:22
One update: 
My process does not always work, even with Sequential Executor. There are 1-2 tasks that usually fail and return code Negsignal.SIGKILL. Please help as I can't run this process on my local machine due to that error.

**Comment by hsahovic** [comment] 2020-09-16 14:27
I'm running into the same issue using [astronomer](https://www.astronomer.io/)'s local dev environment, which uses Airflow 1.10.7, on macOS Catalina 10.15.6.
I'm going to test other versions of airflow supported by astronomer.

**Comment by hsahovic** [comment] 2020-09-16 15:26
Updating Airflow to 1.10.10 seems to have resolved the issue.

**Comment by mariuszliksza-kinesso** [comment] 2020-09-17 09:52
Hmm, I have upgraded to version 1.10.12 and does not work for me.

**Comment by mariuszliksza-kinesso** [comment] 2020-09-17 10:59
I have upgraded to 1.10.12 and still the same issue :(

**Comment by mariuszliksza-kinesso** [comment] 2020-09-17 14:32
Update: 
This process does not work on Windows using docker. So it seems that it only works on Linux.

**Comment by hsahovic** [comment] 2020-09-23 15:29
I encountered this issue - again - on another pipeline, using Airflow 1.10.10. Increasing docker resources resolved it.

**Comment by popovpa** [comment] 2020-10-16 07:29
We have same behavior.
Our environment: k8s, airflow 1.10.12 (in 1.10.9 was such error as well)
Sometimes watching: Task exited with return code Negsignal.SIGKILL

**Comment by chsk-code** [comment] 2020-11-10 19:46
I have the same issue. My airflow(1.10.12) is running on AWS ECS(Fargate).
`INFO - Task exited with return code Negsignal.SIGKILL`

**Comment by darwinyip** [comment] 2020-11-10 19:59
Experiencing the same on 1.10.12 running on AWS ECS(EC2).

**Comment by vikramkoka** [comment] 2020-11-20 02:03
@mariuszliksza-kinesso, Can you please share the procedure to reproduce this issue? Including the code.

**Comment by pbotros** [comment] 2020-11-20 18:59
This is also happening to me on AWS EC2 instances with airflow 1.10.12, ubuntu 18.04.5. It's not consistent but I've just started seeing it with some newly written tasks that use high %s of CPU & GPU for sustained periods. Will hunt for something that can reproduce that.

**Comment by ashb** [comment] 2020-11-20 23:12
Are you also using a lot of memory? On Linux check `dmesg` or syslog and see if the OOMKiller is killing processes.

**Comment by pbotros** [comment] 2020-11-20 23:37
That's likely - indeed, switching to an EC2 instance with more RAM and running fewer concurrent tasks seems to have stopped it so far. Unfortunately I can't confirm since the logs are now gone, but I bet you're right. TIL about overcommit! https://www.etalabs.net/overcommit.html

**Comment by ashb** [comment] 2020-11-24 10:01
I'm going to close this then -- if you have anyone has any more details we can look in to this -- commend (probably mention me directly) and I'll re-open this ticket.

**Closed as completed by ashb** 2020-11-24 10:01 UTC
Labels: kind:bug, pending-response, area:core

**Comment by nielspedersen** [comment] 2021-01-07 12:21
It's not completely related, but I had a different error message and Google lead me here. So in the hopes that it will help anyone in my boat:

I was/am having this issue on macOS Mojave version 10.14.6 running airflow locally and trying to get it to run tasks on Amazon ECS/Fargate.

In the logs, I'd get the error:

```
{local_task_job.py:102} INFO - Task exited with return code Negsignal.SIGABRT
```

After a lot of Google, someone suggested trying to `$ export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`, and that seems to have worked.

The airflow scheduler running locally also hints at this: 

```
objc[70653]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[70653]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

Sorry for commenting at a closed issue, but I hope this can help anyone having the same error

**Comment by potiuk** [comment] 2021-01-07 13:16
Nice! Thanks @nielspedersen . It is great you did it!

**Comment by jjjchens235** [comment] 2021-01-23 00:45
I am running into a similar issue with Airflow 1.20.00 using Docker on macOS.
I ended up allocating more default memory to each docker container in Docker Desktop per this link, and  it fixed it for me:
https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container

**Comment by imsheth** [comment] 2021-03-07 14:11
This doesn't solve the issue with DockerOperator on Mac with airflow 1.10.12

**Comment by ignacioparicio** [comment] 2021-06-24 11:54
I got the same error on an EC2 instance with Ubuntu 20.04, Airflow 2.1.0, scheduler running locally. The cause was insufficient memory. I diagnosed it by running `sudo dmesg`:
```
Out of memory: Killed process 1282 (airflow task ru) total-vm:698780kB, anon-rss:186120kB, file-rss:628kB, shmem-rss:0kB, UID:1000 pgtables:964kB oom_score_adj:0
```

**Comment by trsilva32** [comment] 2021-08-11 02:27
> I have the same issue. My airflow(1.10.12) is running on AWS ECS(Fargate).
> `INFO - Task exited with return code Negsignal.SIGKILL`

I'm facing the same issue on Airflow (mwaa), any solution for that, but it works fine in one env not the other,

**Comment by raburgos** [comment] 2021-11-01 06:04
Hi there! 

Im using MacOs Catalina 10.15.5; trying to run custom hook (using jdbchook) with python3.8/airflow 2.0 on virtual environment.

I search all over internet and try export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES in any possible way. But dont work to me. 

If anyone have another solution it would be awesome!

Thanks in advance!

**Comment by nickrinaldi88** [comment] 2022-02-05 14:14
Hi all, This issue has me banging my head. It occurs for some dags, but not others. 

`export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`

does not work for me, neither does maximizing my docker resources. 

I'm not in the state to update airflow, as my company uses 1.10.13, and we won't upgrade until later in the year.

If anyone has a personal solution that worked for them, let me know! 

BTW, I'm using SequentialExecutor

**Comment by potiuk** [comment] 2022-02-05 14:35
SIGKILL can be cause by multiple reasons - most likely it's one of the libraries you use, not Airflow.  I doubt migrating to newer version of Airlfow will help if this is one of your libraries. 

What I can recommend you - if it's MacOS, use your "local" airflow on a virtual machine with Linux or remote machine. MacOS is NOT officially supported as execution environment (it's OK to use it for Airlfow development though). Only Linux is good to work.

BTW. Sequential Executor should never be used except for development. You seem to be doing everything to have troubles, Sequential Executor, MacOS, Airflow 1.10 which is "dead" for more than 7months. I am sorry to say, but you need to deal with consequences of your choices. Maybe accept the fact that you should follow the "supported" path of Airflow. That would be smart way to approach it.

**Comment by nickrinaldi88** [comment] 2022-02-05 16:47
I have my local airflow being hosted on docker.

I am in development, and I'm using Sequential Executor. 

As I said, I'm a mere employee of my company, and am limited to the choices our team has made. I'm not a liberty to make an executive changes to our production Airflow.

Simply posting here if anyone's had any other fixes. Thanks for your help though.

**Comment by potiuk** [comment] 2022-02-05 16:56
> Simply posting here if anyone's had any other fixes. Thanks for your help though.

Sure. But saying 'I have SIGKILL" is nowehere nearly being specicific SIGKILL is basically symptom that something forcefully killed your process. There are many reasons this can happen. And getting help without providing any details of the circumstances is extremely unlikely to even understand if anyone has any other fixes, because this one is specific to what you try to do in your DAGs I am afraid.

And it **might** be related to the fact that you use MacOS (which is not really supported because many libraries might simply not work there and it will provide "DIFFERENT" environment from what your employer uses (unless they use MacOS to run Airlfow).  My suggestion was to switch to Virtualenv with Linux directly, or remote machine with Linux.

I just think you are shooting yourself in a foot a bit, but this is just advice. Treat it as a present - you can do whatever you want with it - ignore or apply or adapt to your case.

**Comment by karanalang** [comment] 2024-06-10 22:19
I'm seeing the same issue on GCP Composer, the job is running on Dataproc Serverless batches and Composer version is 2.6.6 (Airflow - 2.5.3) .. job completes file but i still get error -> Task exited with error Negsignal.SIGKILL

**Comment by potiuk** [comment] 2024-06-11 12:11
> I'm seeing the same issue on GCP Composer, the job is running on Dataproc Serverless batches and Composer version is 2.6.6 (Airflow - 2.5.3) .. job completes file but i still get error -> Task exited with error Negsignal.SIGKILL

You need to track the root cause of it - it's outside of Airlfow. SIGKILL is always a sign that something terrible happened and the task was killed in "hard" way. But the nature of this error is that you can't get more information about the cause, because sigkill is always causing immediate shutdown of a process and you have no chance to do anything with it. So you should try to guess what triggers it, look at the logs of K8S in GCP Composer and see if you can figure out what task and why is causing it, but you will not get more "generic" help with it. You can also open an issue to the Composer team, because they might have some additional insights.

Usually things like excessive memory usage, resources, or even hardware errors, deadlocks on accessing resources are root cause of the issues - sometimes bugs in libraries and code you are using.

**Comment by roa-sh** [comment] 2025-01-03 20:27
I'm facing the same issue within a DAG on `Amazon Managed Workflows for Apache Airflow` (MWAA). The DAG triggers a SageMaker Processing Job which just copies some files. 

The thing is that logs for the task (the task that creates the AWS SM processing job) on Airflow throws me the `Negsignal.SIGKILL` error.
But I was very surprised when I checked the processing job at Sage Maker and it was fully completed.

![image](https://github.com/user-attachments/assets/c63dea28-b4cc-47df-a980-7a83f3a00d32)
