### ISSUE TITLE
DAG action views should only show DAGs a user can edit

### ISSUE THREAD

**Issue by jhtimmins** [apache/airflow#12301] opened 2020-11-12 01:08 UTC
The DAG view only shows DAGs that a user has view access to. The action views should only show DAGs the user can edit, even though they're all showing up right now.

**Comment by potiuk** [comment] 2020-12-07 10:01
Hey @jhtimmins @ashb @kaxil -> something that we should fix for rc1 I guess?

**Comment by ashb** [comment] 2020-12-07 12:04
@potiuk Not a _hard_ requirement -- this isn't a regression from 1.10.x with RBAC so doesn't have to in the RC.

**Comment by Jorricks** [comment] 2021-06-22 08:41
I thought this as well @jhtimmins, however, all permissions for modifying Task Instances or modifying Dag Runs as of today require `dag_read` permissions on the DAG and the corresponding action permission.
Hence, if we only change it for this view, we would make the whole implementation very inconsistent.
Please take a look [at the Access Control page of Airflow](https://airflow.apache.org/docs/apache-airflow/stable/security/access-control.html#dag-level-permissions)

It feels to me as in that case the whole `dag_edit` base_permission is useless in this case.
I would propose to completely change the following items(copied from the link above) to require `DAGS.can_edit` where it currently says `DAGS.can_read` privileges.

Action | Permissions | Minimum Role
-- | -- | --
Clear Task Instance | DAGs.can_read, DAG Runs.can_read, Task Instances.can_edit | User
Triggers Task Instance | DAGs.can_read, Task Instances.can_create | User
Clear DAG | DAGs.can_read, Task Instances.can_delete | User
Clear DAG Run | DAGs.can_read, Task Instances.can_delete | User
Mark DAG as blocked | Dags.can_read, DAG Runs.can_read | User
Mark DAG Run as failed | Dags.can_read, DAG Runs.can_edit | User
Mark DAG Run as success | Dags.can_read, DAG Runs.can_edit | User
Mark Task as failed | DAGs.can_read, Task Instances.can_edit | User
Mark Task as success | DAGs.can_read, Task Instances.can_edit | User

**Comment by Jorricks** [comment] 2021-06-24 15:29
Proposed the corresponding change here #16634

**Comment by kaxil** [comment] 2021-09-14 11:51
Is this still true in 2.1.3 (or latest main) @jhtimmins @Jorricks ?

**Comment by Jorricks** [comment] 2021-09-14 11:59
Yes @kaxil. My PR is still waiting to be merged. https://github.com/apache/airflow/pull/16634

**Comment by uranusjr** [comment] 2021-09-26 08:04
I'll close this since #16634 has since been merged.

**Closed as completed by uranusjr** 2021-09-26 08:04 UTC
Labels: kind:bug, area:auth
