### ISSUE TITLE
Invalid DAG count is shown on Airflow UI when zero DAGs are present

### ISSUE THREAD

**Issue by deeptansh** [apache/airflow#34100] opened 2023-09-05 07:11 UTC
### Apache Airflow version

2.7.0

### What happened

When Example DAGs are disabled from using `docker-compose.yaml` file, and no DAGs are present in the dags folder, its still showing the DAG count of Example dags on screen as 53 ( No DAGs are present on UI)

<img width="1484" alt="Airflow_Dag_Count" src="https://github.com/apache/airflow/assets/11991059/e818e2be-ac02-4728-b6ee-f1239404833a">

### What you think should happen instead

- After updating value for parameter `AIRFLOW__CORE__LOAD_EXAMPLES` to false, its removing all DAGs from UI
- **DAG Count should also get updated to zero(0)**

### How to reproduce

- Download 2.7.0 docker compose file available at ('https://airflow.apache.org/docs/apache-airflow/2.7.0/docker-compose.yaml')
- Create folder structure using data available [here](https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user) 
- Create an airflow deployment using above mentioned steps
- Initialize Airflow using `docker compose up airflow-init ` 
- Start Airflow application using `docker compose up` command 
- Airflow started with 53 Example dags
- DAG count still shows 53
- Stop Airflow application using `docker compose down` command 
- Updated parameter `AIRFLOW__CORE__LOAD_EXAMPLES: 'true'` to `AIRFLOW__CORE__LOAD_EXAMPLES: 'false'` in docker-compose.yaml file
- Start Airflow application using `docker compose up` command 
- Airflow started with zero(0) Example dags
- DAG count still shows 53 but no DAGs are there on the screen

<img width="1484" alt="Airflow_Dag_Count" src="https://github.com/apache/airflow/assets/11991059/e818e2be-ac02-4728-b6ee-f1239404833a">

### Operating System

macos Ventura 13.4.1 (c) (22F770820d)

### Deployment

Docker-Compose

### Deployment details

Docker compose file -> 'https://airflow.apache.org/docs/apache-airflow/2.7.0/docker-compose.yaml'
Create folder structure using data available [here](https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user) 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment] 2023-09-05 07:29
- Duplicate of: #33698
- Should be fixed by: #33778 in Airflow 2.7.1

**Closed as completed by Taragolis** 2023-09-05 07:29 UTC
Labels: kind:bug, duplicate, area:core
