### ISSUE TITLE
Logs not visible in UI even though they exist 

### ISSUE THREAD

**Issue by rchojn** [apache/airflow#10203] opened 2020-08-06 16:21 UTC
**Apache Airflow version**:
1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.18.3

**Environment**:
Kubernetes cluser 

**What happened**:
During dag execution I am not able to see logs 

> *** Log file does not exist: /opt/airflow/logs/example_dag/python_print_date_152/2019-01-01T00:00:00+00:00/1.log
*** Fetching from: htttp://fi-airflow-worker-97bcfb76-jdwj7:8793/log/example_dag/python_print_date_152/2019-01-01T00:00:00+00:00/1.log
*** Failed to fetch log file from worker. HTTPConnectionPool(host='fi-airflow-worker-97bcfb76-jdwj7', port=8793): Max retries exceeded with url: /log/example_dag/python_print_date_152/2019-01-01T00:00:00+00:00/1.log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6409dfcd10>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**What you expected to happen**:
See logs from dag execution in UI no only from command line

**Comment by mingruWei** [comment] 2020-09-23 00:31
I have the same problem.Do you solve that?

**Comment by eladkal** [comment] 2021-05-14 05:04
duplicate of https://github.com/apache/airflow/issues/15571

**Closed as completed by eladkal** 2021-05-14 05:04 UTC
Labels: kind:bug, area:logging, duplicate
