### ISSUE TITLE
WebUI does not show "Task Tries" items after rerun on MappedOperators

### ISSUE THREAD

**Issue by AutomationDev85** [apache/airflow#42357] opened 2024-09-20 08:29 UTC
### Apache Airflow version

2.10.1

### What happened?

We are running a Airflow 2.10.1 instance an facing the issue that the "Task Tries" fields are missing on Mapped Operator tasks:
![image](https://github.com/user-attachments/assets/474858c7-5107-47d0-af7d-80bfd62d4a19)

On Normal Operators it is working fine:
![image](https://github.com/user-attachments/assets/edfcfb10-2e58-462f-9626-6bdb70f70e68)

Any one else has the problem? I´m not sure it was working in 2.10. or not but in 2.9.3 it was working.

### How to reproduce

Clean task state of Mapped Operator task and check the "Task Tries" items of the WebUI.

### Operating System

Debian GNU/Linux 12

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment] 2024-09-20 21:50
I did a regressionin breeze with DAG `example_dynamic_task_mapping_with_no_taskflow_operators` and can confirm:

Airflow 2.9.3:

![image](https://github.com/user-attachments/assets/826acb78-0147-40c6-b74e-6a509d5a84dc)

Airflow 2.10.0:

![image](https://github.com/user-attachments/assets/260f029b-80d4-415b-89bd-ff2da06dece4)

Airflow 2.10.1:

![image](https://github.com/user-attachments/assets/15f843f6-cd00-4371-8900-2191ffde5796)

...it seems the header "Task Tries" is added but the buttons to switch are missing. For the task details this is degrading to state of 2.9.3 but for logs this blocks UI access to logs for runs which are not the last if multiple tries :-(

...and just now the release of 2.10.2 :-( Can confirm that the bug is also in 2.10.2

**Comment by jscheffl** [comment] 2024-09-20 22:00
With some triaging through the release notes... PR #41483 seems to be the fix that caused the side effect. Manually reverting the commit 5dcc2ada1bd753b7a4b183062d3f5954af076a97 fixes _this_ problem but re-adds the refresh issue we had in 2.10.0. ...and damn it was myself testing and did not check the mapped tasks.

@AutomationDev85 are you willing to supply a patch for the views of mapped tasks for a future 2.10.3?

**Comment by jx2lee** [comment] 2024-09-29 01:45
Could i take this issue? if possible, please assign to me and try it!

**Comment by jscheffl** [comment] 2024-10-30 21:19
Ah, just checked for this and was hoping it is in 2.10.3... but still not fixed :-(

**Comment by potiuk** [comment] 2024-10-31 16:35
> Could i take this issue? if possible, please assign to me and try it!

You know what's the fastest way @jscheffl :stuck_out_tongue:  ?

**Comment by jscheffl** [comment] 2024-10-31 20:03
> > Ah, just checked for this and was hoping it is in 2.10.3... but still not fixed :-(
> 
> You know what's the fastest way @jscheffl 😛 ?

Yeah... the fastest way is always... fix it yourself! Probably gonna do this. I was losing track and actually we have an "everyday problem" as the UI history is broken... was just not following-up, lese I would have fixed already... but now too late for 2.10.3 :-( (Except if other major bugs will be found...)

**Closed as completed** 2024-11-01 00:17 UTC
Labels: kind:bug, good first issue, area:core, area:UI, area:dynamic-task-mapping
