### ISSUE TITLE
Airflow task instances disappearing, unable to restart

### ISSUE THREAD

**Issue by lihan** [apache/airflow#34082] opened 2023-09-04 17:26 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

This happens on `v2.6.2`, but likely also on other earlier versions.

Following are the bug observations:

* Task instances from already successful dag runs went disappearing (Refer to below screenshot). The dag run itself stays successful (green block), but there was no task instances exist in the meta database.
* Attempt to click "Clear existing tasks" dag run to retry the dag, but there was again no task instances created, and the dag run state transitioned from queued to succeed immediately
* Same thing happens if click "Queue up new tasks" button, the dag run immediately went back to normal state
![image](https://github.com/apache/airflow/assets/655051/ca11735d-2426-49e1-ba2a-710d6d21014b)

* This issue happened after https://github.com/apache/airflow/issues/32596

Also see a video recording.

https://github.com/apache/airflow/assets/655051/9c27cc32-8e30-4153-a7e7-eeac9a2cf58a

### How to reproduce

I cannot easily reproduce this locally, but it happens on production env.

### Operating System

Docker python 3.9

### Deployment

Other Docker-based deployment

### Deployment details

Unlikely relate to the deployment.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2023-09-04 17:32
Can you please check if the DagRun in question has no Task Instance entries? That would confirm that the root cause is https://github.com/apache/airflow/pull/32684

**Comment by lihan** [comment] 2023-09-04 17:38
Yes, dag_run object exists in the meta DB, but no associated task instances.

**Comment by hussein-awala** [comment] 2023-09-04 17:40
You can check [my comment](https://github.com/apache/airflow/pull/32684#issuecomment-1705569449), you can edit the query I provided to clean your history, you just need to detect the empty dag runs, delete them, then recreate them using the backfill command.

**Comment by potiuk** [comment] 2023-09-04 18:08
Closing as duplicate. Good we have it as it will serve as a guide for others who will have similar issue.

**Closed as completed by potiuk** 2023-09-04 18:08 UTC
Labels: kind:bug, duplicate, area:core
