### ISSUE TITLE
airflow throws error: airflow.exceptions.SerializedDagNotFound: DAG 'dns-basic-1min' not found in serialized_dag table

### ISSUE THREAD

**Issue by trollhe** [apache/airflow#15607] opened 2021-04-30 01:39 UTC
hi,team:

   i deployment airflow 2.0.2 in docker by docker-compose,airflow service start just 1 minute have many dags,bug 1 minute after dag is none,and throws bellow error:

   already share dag folder to webservice/scheduler/flower container

![image](https://user-images.githubusercontent.com/41068725/116637904-b498ca00-a997-11eb-8ca2-428f0ff821cd.png)
![image](https://user-images.githubusercontent.com/41068725/116638004-ead64980-a997-11eb-96cd-cf5becd7a743.png)

```
Python version: 3.8.5
Airflow version: 2.0.2
Node: airflow-webserver
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/airflow/www/auth.py", line 34, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/www/decorators.py", line 97, in view_func
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/www/decorators.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/www/views.py", line 1876, in tree
    dag = current_app.dag_bag.get_dag(dag_id)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 181, in get_dag
    self._add_dag_from_db(dag_id=dag_id, session=session)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 237, in _add_dag_from_db
    raise SerializedDagNotFound(f"DAG '{dag_id}' not found in serialized_dag table")
airflow.exceptions.SerializedDagNotFound: DAG 'dns-basic-1min' not found in serialized_dag table
```

**Comment by trollhe** [comment] 2021-04-30 01:42
only webserver and schedule service in one container,else have the error.but need modify  dag file,i don`t know how can serialized_dag after dag file modify.

**Comment by kaxil** [comment] 2021-04-30 11:29
Are you generating the DAG Dynamically? Can you post your DAG here please

**Comment by hsnprsd** [comment] 2021-05-16 11:19
I'm getting the same error right now.

**Comment by carlinix** [comment] 2021-06-23 11:49
I'm getting the same error. My dags are dynamic.

**Comment by kaxil** [comment] 2021-06-23 13:01
@carlinix @hsnprsd Which Airflow version? Can you give us an example of how you generate DAGs for us to reproduce

**Comment by warrenstephens** [comment] 2021-07-06 17:21
Using airflow 2.1.1 with docker-compose as well.

I would love to be able to clean out this DAG 'tutorial' stuff, but I have no idea where the "serialized dag table" is!  How do I get to it?

```
airflow-webserver_1  | 172.20.0.1 - - [06/Jul/2021:17:15:43 +0000] "GET /object/task_instances?dag_id=annotate_dug&execution_date=2021-07-02T21%3A19%3A24.504747%2B00%3A00 HTTP/1.1" 200 4564 "http://localhost:8080/graph?dag_id=annotate_dug" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
airflow-webserver_1  | [2021-07-06 17:15:45,148] {app.py:1891} ERROR - Exception on /object/task_instances [GET]
airflow-webserver_1  | Traceback (most recent call last):
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
airflow-webserver_1  |     response = self.full_dispatch_request()
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
airflow-webserver_1  |     rv = self.handle_user_exception(e)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
airflow-webserver_1  |     reraise(exc_type, exc_value, tb)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
airflow-webserver_1  |     raise value
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
airflow-webserver_1  |     rv = self.dispatch_request()
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
airflow-webserver_1  |     return self.view_functions[rule.endpoint](**req.view_args)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/www/auth.py", line 34, in decorated
airflow-webserver_1  |     return func(*args, **kwargs)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/www/decorators.py", line 60, in wrapper
airflow-webserver_1  |     return f(*args, **kwargs)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/www/views.py", line 2611, in task_instances
airflow-webserver_1  |     dag = current_app.dag_bag.get_dag(dag_id)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 65, in wrapper
airflow-webserver_1  |     return func(*args, session=session, **kwargs)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 178, in get_dag
airflow-webserver_1  |     self._add_dag_from_db(dag_id=dag_id, session=session)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 234, in _add_dag_from_db
airflow-webserver_1  |     raise SerializedDagNotFound(f"DAG '{dag_id}' not found in serialized_dag table")
airflow-webserver_1  | airflow.exceptions.SerializedDagNotFound: DAG 'tutorial' not found in serialized_dag table
```

**Comment by kaxil** [comment] 2021-07-06 17:56
@warrenstephens Check for the `tutorial` dag entry in `dag` table too. These tables are in Metadata DB (Postgres or MySQL) depending on what you are using in your docker-compose

**Comment by warrenstephens** [comment] 2021-07-06 18:57
I fought my way into the running docker container as the "airflow" user, and listed the tables, one of which was "dag", selected * from dag, which showed 3 dag_id values -- none of which were "tutorial" -- they were the dags that I expected.

So where is the "tutorial" dag?

For those playing along at home, here is how I got into the running postgres container:
```
docker exec -it roger_postgres_1 /bin/bash
```
where I found "roger_postgres_1" by running "docker ps" at the command line.

**Comment by kaxil** [comment] 2021-07-06 19:08
Can you post the code of your DAG with dag_id `annotate_dug`

**Comment by warrenstephens** [comment] 2021-07-06 19:15
Alrighty!
```
from airflow.models import DAG
from airflow.operators.bash_operator import BashOperator
from airflow.operators.dummy_operator import DummyOperator

from dug_helpers.dug_utils import DugUtil, get_topmed_files, get_dbgap_files
from roger.dag_util import default_args, create_python_task

DAG_ID = 'annotate_dug'

""" Build the workflow's tasks and DAG. """
with DAG(
    dag_id=DAG_ID,
    default_args=default_args,
    schedule_interval=None
) as dag:

    """Build workflow tasks."""
    intro = BashOperator(task_id='Intro',
                         bash_command='echo running tranql translator && exit 0',
                         dag=dag)
    # make_kg_tagged = create_python_task(dag, "create_kgx_files", DugUtil.make_kg_tagged)

    # Unzip and get files, avoid this because
    # 1. it takes a bit of time making the dag itself, webserver hangs
    # 2. Every task in this dag would still need to execute this part
    # making it redundant
    # 3. tasks like intro would fail because they don't have the data dir mounted.

    get_topmed_files = create_python_task(dag, "get_topmed_data", get_topmed_files)
    extract_db_gap_files = create_python_task(dag, "get_dbgab_data", get_dbgap_files)

    annotate_topmed_files = create_python_task(dag, "annotate_topmed_files", DugUtil.annotate_topmed_files)
    annotate_db_gap_files = create_python_task(dag, "annotate_db_gap_files", DugUtil.annotate_db_gap_files)

    make_kg_tagged = create_python_task(dag, "make_tagged_kgx", DugUtil.make_kg_tagged)

    dummy_stepover = DummyOperator(
        task_id="continue",
    )
    intro >> [get_topmed_files, extract_db_gap_files] >> dummy_stepover >>\
    [annotate_topmed_files, annotate_db_gap_files] >> make_kg_tagged


```

**Comment by warrenstephens** [comment] 2021-07-06 19:20
Didn't find "tutorial" in the serialized_dag table either.

Here is what shows up in the docker-compose window:

![image](https://user-images.githubusercontent.com/15000847/124655160-7c1cdd00-de6d-11eb-9d72-2757b2b2fa32.png)

**Comment by warrenstephens** [comment] 2021-07-06 19:28
This is from the annotate.py.log.  Looks like some sort of bizarre import error to me.
```
[2021-07-06 16:23:52,806] {scheduler_job.py:182} INFO - Started process (PID=40) to work on /opt/airflow/dags/annotate.py
[2021-07-06 16:23:52,810] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/annotate.py for tasks to queue
[2021-07-06 16:23:52,828] {logging_mixin.py:104} INFO - [2021-07-06 16:23:52,828] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/annotate.py
[2021-07-06 16:24:22,863] {logging_mixin.py:104} INFO - [2021-07-06 16:24:22,856] {timeout.py:36} ERROR - Process timed out, PID: 40
[2021-07-06 16:24:22,916] {logging_mixin.py:104} INFO - [2021-07-06 16:24:22,873] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/annotate.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annotate.py", line 5, in <module>
    from dug_helpers.dug_utils import DugUtil, get_topmed_files, get_dbgap_files
  File "/opt/airflow/dags/dug_helpers/dug_utils.py", line 21, in <module>
    from roger.core import Util
  File "/opt/airflow/dags/roger/core.py", line 14, in <module>
    from bmt import Toolkit
  File "/home/airflow/.local/lib/python3.8/site-packages/bmt/__init__.py", line 1, in <module>
    from bmt.toolkit import Toolkit
  File "/home/airflow/.local/lib/python3.8/site-packages/bmt/toolkit.py", line 5, in <module>
    from biolinkml.meta import SchemaDefinition, Element, Definition, ClassDefinition, SlotDefinition
  File "/home/airflow/.local/lib/python3.8/site-packages/biolinkml/meta.py", line 16, in <module>
    from biolinkml.utils.metamodelcore import empty_list, empty_dict, bnode
  File "/home/airflow/.local/lib/python3.8/site-packages/biolinkml/utils/metamodelcore.py", line 9, in <module>
    from ShExJSG.ShExJ import IRIREF, PN_PREFIX
  File "/home/airflow/.local/lib/python3.8/site-packages/ShExJSG/__init__.py", line 1, in <module>
    from ShExJSG.SchemaWithContext import Schema
  File "/home/airflow/.local/lib/python3.8/site-packages/ShExJSG/SchemaWithContext.py", line 3, in <module>
    from ShExJSG import ShExJ
  File "/home/airflow/.local/lib/python3.8/site-packages/ShExJSG/ShExJ.py", line 55, in <module>
    class PN_PREFIX(jsg.JSGString):
  File "/home/airflow/.local/lib/python3.8/site-packages/ShExJSG/ShExJ.py", line 56, in PN_PREFIX
    pattern = jsg.JSGPattern(r'({PN_CHARS_BASE})((({PN_CHARS})|\.)*({PN_CHARS}))?'.format(PN_CHARS=PN_CHARS.pattern, PN_CHARS_BASE=PN_CHARS_BASE.pattern))
  File "/home/airflow/.local/lib/python3.8/site-packages/pyjsg/jsglib/jsg_strings.py", line 18, in __init__
    self.pattern_re = re.compile(pattern, flags=re.DOTALL)
  File "/usr/local/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.8/sre_compile.py", line 768, in compile
    code = _code(p, flags)
  File "/usr/local/lib/python3.8/sre_compile.py", line 604, in _code
    _compile_info(code, p, flags)
  File "/usr/local/lib/python3.8/sre_compile.py", line 590, in _compile_info
    charset, hascased = _optimize_charset(charset)
  File "/usr/local/lib/python3.8/sre_compile.py", line 312, in _optimize_charset
    charmap[i] = 1
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/annotate.py after 30.0s, PID: 40
[2021-07-06 16:24:22,925] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/annotate.py
[2021-07-06 16:24:23,127] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/annotate.py took 30.356 seconds
[2021-07-06 16:24:54,072] {scheduler_job.py:182} INFO - Started process (PID=50) to work on /opt/airflow/dags/annotate.py
```

**Comment by warrenstephens** [comment] 2021-07-06 21:33
Fixed the bizarre import error, and the DAG error still occurs -- which starts only after I login to the localhost:8080 interface.
```
airflow.exceptions.SerializedDagNotFound: DAG 'tutorial' not found in serialized_dag table
```

**Comment by warrenstephens** [comment] 2021-07-07 12:38
@kaxil **I found the issue!**  

It turns out that I had a minimized window open with the `http://localhost:8080/graph?dag_id=tutorial` in it!  This was from doing the tutorial walkthru days prior with some other folks.

Now that I have closed that window the Airflow webserver exception no longer occurs (as shown in the screenshot above).

I guess that the minimized window was reconnecting to airflow and attempting to get info on the tutorial dag that it assumed was still serialized.

**Comment by potiuk** [comment] 2021-07-07 12:51
Closing it then.

**Closed as completed by potiuk** 2021-07-07 12:51 UTC
Labels: kind:bug, pending-response, area:core

**Comment by warrenstephens** [comment] 2021-07-07 12:54
Airflow webserver should probably handle the request without generating an Exception.

**Comment by potiuk** [comment] 2021-07-07 14:22
> Airflow webserver should probably handle the request without generating an Exception.

Why do you think so ? Could you please elaborate? 

I think showing an exception in logs is a good idea if someone sends a wrong request that triggers it. This is the default behaviour is some bad formed. wrong parameter, etc is sent, allowing to debug the problem when it happens.  I do not honestly imagine better way of handling it. It gives a nice stack trace showing where it came from (and that it was generated by the UI). I think it's fair to expect that when a window from earlier version of the application runs in the background might have some "invalid" data cached (as it was in this case) that might trigger some exception - and it was totally unexpected (thus exception seems appropriate rather than handling it as a "normal" behaviour).

Do you have some concrete proposal how to improve such cases?

**Comment by warrenstephens** [comment] 2021-07-12 12:52
I guess it is my misunderstanding -- as I am new to airflow in the first place.  The error looked to me as if the airflow webserver itself was crashing, rather than something on the user side.  To me it is not at all clear that the error came from the UI.  It appears that other people are similarly confused.

In a broader sense, it seems to me that when an error of "X not found" happens in most applications then no exception is generated, merely an error message stating that "X was not found".

I do not see in the exception that was generated what would lead me to understand what was actually happening.

**Comment by potiuk** [comment] 2021-07-12 18:10
> In a broader sense, it seems to me that when an error of "X not found" happens in most applications then no exception is generated, merely an error message stating that "X was not found".

Absolutely agree, it this is "expected" error. I.e. if there is an action from a user or known reason/flow that leads to it, you can  - and should - provide a description and remediation,

Conversely, if something is the result of some totally unexpected condition which is likely a bug in the software or bug in migration process that was not possible to handle - it is virtually impossible to predict that it can happen.  The statement that "all errors "SHOULD" be handled without generating an exception"  takes the simplistic point of view that every single flow in the program is checked an handled and software is bug free. Which is not only not reasonable expectation it is also virtually impossible to prove from the software engineering point of view.

**Comment by neilharia7** [comment] 2021-07-29 15:50
I'm getting the same error with dynamic dags while running with airflow's docker-compose with `apache/airflow:2.1.2-python3.9`

` Traceback (most recent call last):
airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1531, in _do_scheduling
airflow-scheduler_1  |     self._schedule_dag_run(dag_run, active_runs_by_dag_id.get(dag_run.dag_id, set()), session)
airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1702, in _schedule_dag_run
airflow-scheduler_1  |     dag = dag_run.dag = self.dagbag.get_dag(dag_run.dag_id, session=session)
airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 67, in wrapper
airflow-scheduler_1  |     return func(*args, **kwargs)
airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 186, in get_dag
airflow-scheduler_1  |     self._add_dag_from_db(dag_id=dag_id, session=session)
airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 258, in _add_dag_from_db
airflow-scheduler_1  |     raise SerializedDagNotFound(f"DAG '{dag_id}' not found in serialized_dag table")
airflow-scheduler_1  | airflow.exceptions.SerializedDagNotFound: DAG 'cross-sell-v3-new' not found in serialized_dag table
`

**Comment by kaxil** [comment] 2021-07-29 15:58
> I'm getting the same error with dynamic dags while running with airflow's docker-compose with `apache/airflow:2.1.2-python3.9`
> 
> ```
> Traceback (most recent call last):
> airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1531, in _do_scheduling
> airflow-scheduler_1  |     self._schedule_dag_run(dag_run, active_runs_by_dag_id.get(dag_run.dag_id, set()), session)
> airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1702, in _schedule_dag_run
> airflow-scheduler_1  |     dag = dag_run.dag = self.dagbag.get_dag(dag_run.dag_id, session=session)
> airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 67, in wrapper
> airflow-scheduler_1  |     return func(*args, **kwargs)
> airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 186, in get_dag
> airflow-scheduler_1  |     self._add_dag_from_db(dag_id=dag_id, session=session)
> airflow-scheduler_1  |   File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 258, in _add_dag_from_db
> airflow-scheduler_1  |     raise SerializedDagNotFound(f"DAG '{dag_id}' not found in serialized_dag table")
> airflow-scheduler_1  | airflow.exceptions.SerializedDagNotFound: DAG 'cross-sell-v3-new' not found in serialized_dag table
> ```

Please post your DAG file, it won't be possible for us in any way to help without it

**Comment by neilharia7** [comment] 2021-07-29 16:17
@kaxil 

```
import datetime as dt
import json

import boto3
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import PythonOperator, BranchPythonOperator
from tasks_functions.custom_functions import customized_function
from zeus.config import *
from zeus.utils import *

default_args = {
	'owner': 'neilharia7',
	'start_date': dt.datetime(2020, 6, 26),
	'retries': 1,
	'retry_delay': 30
}

# fetch Dags from s3 bucket
s3_client = boto3.client('s3', region_name='ap-south-1')
flag, dag_information = False, dict()
try:
	dag_information = json.loads(
		s3_client.get_object(Bucket=Config.AWS.S3.bucket_name, Key=Config.AWS.S3.key_path)['Body'].read())
	if dag_information:
		flag = True
except Exception as e:
	print(f'No dags registered {e}')


def number_of_keys(obj):
	"""
	# check if the number of keys are greater than 1
	:param obj:
	:return:
	"""
	if isinstance(obj, dict):
		return True if len([k for k, v in obj.items()]) > 1 else False
	
	if isinstance(obj, list):
		return True if len(obj) > 1 else False


if flag:
	
	for dag_data in dag_information.get('dag_structure', list()):
		dag_registry = {
			'owner': default_args.get('owner'),
			'start_date': dt.datetime(2020, 6, 26),
			'retries': dag_data.get('retries', default_args.get('retries')),
			'retry_delay': dt.timedelta(seconds=dag_data.get('retry_delay', default_args.get('retry_delay'))),
			'max_retry_delay': dt.timedelta(seconds=dag_data.get('max_retry_delay', 3600)),
			'retry_exponential_backoff': dag_data.get('exponential_retry', True)
		}
		
		with DAG(
				dag_id=dag_data.get('name', dag_data.get('dag_id')),
				default_args=dag_registry,
				schedule_interval=dag_data.get('scheduler', None)
		) as dag:
			
			# reverse mapping
			data_list = dag_data.get('data', list())[::-1]
			
			task_register = [dynamic_task_composer(task_data, dag) for task_data in data_list]
			reverse_dict = {"data": data_list}
			
			task_len = len(task_register)
			
			# dynamic mapping
			for child_idx, child_info in enumerate(reverse_dict['data']):
				if child_info.get('parent_task'):  # check if there are any parents of this task
					for parent_idx, parent_info in enumerate(dag_data.get('data')):
						
						if parent_info.get('task_name') in child_info.get('parent_task'):
							task_register[child_idx] << task_register[task_len - parent_idx - 1]
			
			# dynamic dag registration
			globals()[dag_data.get('dag_id')] = dag
```

**Comment by kaxil** [comment] 2021-07-30 00:22
@neilharia7 The problem for you seems like `cross-sell-v3-new` DAG does not exist when Airflow parses it sometimes, which is why Airflow removes it from the `serialized_dag` table. Increase `[processor_poll_interval](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#processor-poll-interval)` if you want to increase the interval on how frequently Airflow should parse your DAG

**Comment by christine-le** [comment] 2021-09-02 19:19
Just wanted to chime in to say we ran into the exact same error under pretty similar set up as @neilharia7 with a set of dynamic dags. Setting processor_poll_interval to 30 seconds (up from the default of 1 second) resolved the error for us.

We may play around with this number a bit and see if we can reduce this number a bit. We have a couple thousand dags, many of which are dynamically generated, so may just need more time for parsing.

Details of our set up:
Python 3.6
Airflow 2.0.2

**Comment by Chikkl** [comment] 2023-05-14 13:44
Please help me

`import airflow
from datetime import timedelta
from airflow import DAG
from airflow.operators.postgres_operator import PostgresOperator
from airflow.utils.dates import days_ago
import pandas as pd
from datetime import datetime, timedelta
from airflow.operators.python import PythonOperator, BranchPythonOperator
from random import randint
from airflow.operators.bash import BashOperator
import requests
import json
import time
import os
from datetime import datetime
from datetime import timedelta
import psycopg2
import pandas as pd
from sqlalchemy import create_engine, VARCHAR, INT, Boolean, ARRAY


args={'owner': 'airflow'}
headers = {"useragent": "Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US)"}

create_table_sql_query = """CREATE TABLE IF NOT EXISTS vacaniec(
                    id VARCHAR(9),
                    premium Boolean,
                    name VARCHAR(100),
                    area VARCHAR(50),
                    salary INT,
                    type VARCHAR(50),
                    address VARCHAR(300),
                    metro VARCHAR(40),
                    experience VARCHAR(50),
                    schedule VARCHAR(50),
                    employment VARCHAR(50),
                    department VARCHAR(100),
                    contacts VARCHAR(100),
                    key_skills VARCHAR[],
                    professional_roles VARCHAR(100),
                    employer VARCHAR(200), 
                    url VARCHAR(300),
                    published_at VARCHAR(100)
                    )"""


def get_id_appended_vac():
    qq = "select id from vacaniec"
    df = pd.read_sql(qq)
    if df.empty:
        return []
    
    return set(i[0] for i in df.values)


def change_time(time):
    return "T".join(time.split())+"+1000"

def date_to(time=False):
    if time:
        time = datetime.strptime(" ".join(time[:19].split("T")), '%Y-%m-%d %H:%M:%S')
        return change_time(str(time + timedelta(minutes=30)))
    else:
        return change_time(str(datetime.now()).split(".")[0])

def date_from():
    return change_time(str(datetime.now() - timedelta(minutes=30)).split(".")[0])


class ParserRU():
    """Класс представляет необходимый набор функционала для сбора данных через API с сайта hh.ru
    Каждая функция содержит краткое описание того, что она делает."""
    
    PROFESSIONAL_ROLES = ['156', '160', '10', '12', '150', '25', '165', '34', '36', '73', '155', '96',
                              '164', '104', '157', '107', '112', '113', '148', '114', '116', '121', '124', '125', '126']
    ALL_NEED_ROLES = ('156', '160', '10', '12', '150', '25', '165', '34', '36', '73', '155', '96',
                              '164', '104', '157', '107', '112', '113', '148', '114', '116', '121', '124', '125', '126')
    EXP = ["noExperience", "between1And3", "between3And6", "moreThan6"]

    vacaniecc = []

    @staticmethod
    def get_time(t = time.localtime()) -> str:
        """Функция возвращает текущее время"""
        current_time = time.strftime("%H : %M : %S", t)
        return current_time

    @staticmethod
    def get_areas() -> list:
        """Функция для получения всех зон для парсинга (включает в себя все субъекты РФ и два города федерального значения [Москва, Санкт-Петербург])"""
        req = requests.get('https://api.hh.ru/areas', headers=headers)
        req.close()
        js_obj = json.loads(req.content.decode())
        areas = []
        for element in js_obj:
            for i in range(len(element['areas'])):
                if element['areas'][i]["parent_id"] == '113':                     # Проверка на принадлежность стране
                    if len(element['areas'][i]['areas']) != 0:                      # Если у зоны есть внутренние зоны
                        areas.append([element['areas'][i]['id'],
                                    element['areas'][i]['name']])
                    # else:                                                                # Если у зоны нет внутренних зон
                    #     areas.append([element['areas'][i]['id'],
                    #                   element['areas'][i]['name']])
        return areas
    
    
    def get_vacancies_per_page(self, page:int = 0, area:str = '1', prof_role:str = '156', exp = ("noExperience", "between1And3", "between3And6", "moreThan6"),
                                period:bool = False) -> list:
        """Функция для получения всех вакансий с определённой страницы"""
        period = period
        params={
            "area":area,
            "professional_role":prof_role,
            "only_with_salary":True,
            "page":page,
            "employment":("full", "part","probation"),
            "experience":("noExperience", "between1And3", "between3And6", "moreThan6"),
            "per_page":100
        }
        if period:
            params["date_from"] = date_from()
            params["date_to"] = date_to()
            req = requests.get('https://api.hh.ru/vacancies/', params, headers=headers)
            data = req.content.decode()
            req.close()
        return data

    @staticmethod
    def get_vacancies_with_specific_id(id:str, retry:int=5) -> list:
        ''' Функция для получения определённой вакансии по её id'''
        try:
            req = requests.get(f'https://api.hh.ru/vacancies/{id}', headers=headers)
        except Exception as ex:
             return
        else:
             return req

    
    def vacancies_saver(self, page: int, area: list, role: str, dop_num:int = 0, period:bool = False) -> None:
        """Функция сохраняет полученные вакансии с определённой страницы в отдельный файл с расширением .json"""
        js_objs = self.vacaniecc
        js_obj = json.loads(self.get_vacancies_per_page(page, area, role, period=period))
        for i in range(len(js_obj["items"])):
                        
                        id = js_obj["items"][i]["id"]

                        req = self.get_vacancies_with_specific_id(id)

                        if req:
                            
                            obj = json.loads(req.content.decode())

                            vacancie = {                                #Словарь хранит в себе список всех необходимых нам полей из получаемой вакансии
                                "id":obj["id"],
                                "premium":obj["premium"],
                                "name":obj["name"],
                                "area":obj["area"],
                                "salary":obj["salary"],
                                "type":obj["type"],
                                "address":obj["address"],
                                "experience":obj["experience"],
                                "schedule":obj["schedule"],
                                "employment":obj["employment"],
                                "department":obj["department"],
                                "contacts":obj["contacts"],
                                "key_skills":obj["key_skills"],
                                "professional_roles":obj["professional_roles"],
                                "employer":obj["employer"],
                                "url":obj["alternate_url"],
                                "published_at":obj["published_at"],
                                "working_days":obj["working_days"],
                                "working_time_intervals":obj["working_time_intervals"],
                                "working_time_modes":obj["working_time_modes"]
                            }

                            js_objs.append(vacancie)
                            req.close()
                            
                            time.sleep(0.6)
                        else:
                            continue

        if (js_obj["pages"] - page) <= 1:
            return str(js_objs)

    
    def start_parsing(self, period):
        """Конечная функция. Координирует работу всех остальных функций. Для начала она получает список всех зон.
        После чего начинает перебирать все вакансии в этой зоне и обрабатывает их исходя из выполняемых условий."""
        print(f"Время начала сбора данных {self.get_time()}")
        areas = [["1", "Москва"], ["2", "Санкт-петербург"]]
        areas.extend(self.get_areas())
        self.ALL_AREAS = tuple([i[0] for i in areas])

        total_vacancies = 0                  # Переменная хранит в себе кол-во всех вакансий
        area_list_id = 1                    # Переменная хранит в себе кол-во пройденных зон

        vac1 = json.loads(self.get_vacancies_per_page(0, self.ALL_AREAS, self.ALL_NEED_ROLES, period=period))
        count_vacancies1 = vac1['found']
        print(count_vacancies1)
        pages1 = vac1['pages']
        if count_vacancies1 > 2000:
            for area in areas:
                area_id, area_name = area[0], area[1]
                vac = json.loads(self.get_vacancies_per_page(0, area_id, self.ALL_NEED_ROLES, period=period))
                count_vacancies = vac['found']
                pages = vac['pages']
                print('[{0}/{1}] Область: {2} ({3}) - Вакансий: {4}'.format(area_list_id, len(areas), area_name, area_id, count_vacancies))
                    
                if count_vacancies > 2000:                           # Если вакансий по запросу больше 2к, разбиваем этот запрос на подзапросы по специализации
                    dop_num = 0
                    for role in self.PROFESSIONAL_ROLES:
                        need_vac = json.loads(self.get_vacancies_per_page(0, area_id, role, period=period))
                        c_v= need_vac['found']
                        pag = need_vac['pages']
                        if c_v > 2000:                              # Если вакансий по запросу больше 2к, разбиваем этот запрос на подзапросы по опыту
                            for exp in self.EXP:
                                exp_vac = json.loads(self.get_vacancies_per_page(0, area_id, role, exp, period=period))
                                page_exp = exp_vac['pages']
                                for page in range(page_exp):
                                    self.vacancies_saver(page, area_id, role, dop_num, period=period)
                                    time.sleep(0.5)
                                    dop_num+=1
                                time.sleep(0.5)
                            time.sleep(0.5)
                        else:
                            for page in range(pag):
                                self.vacancies_saver(page, area_id, role, dop_num, period=period)
                                time.sleep(0.5)
                                dop_num+=1
                            time.sleep(0.5)
                    time.sleep(0.5)
                else:                                               # Иначе собираем все вакансии, по всем специализациям сразу
                    role = self.ALL_NEED_ROLES
                    for page in range(pages):
                        self.vacancies_saver(page, area_id, role, period=period)
                        time.sleep(0.5)
                    time.sleep(0.5)

                area_list_id+=1
                total_vacancies+=count_vacancies


                if count_vacancies != 0:
                    print(f"Добавленно {count_vacancies} вакансий")
        else:
            for page in range(pages1):
                self.vacancies_saver(page, self.ALL_AREAS, self.ALL_NEED_ROLES, period=period)
                time.sleep(0.5)
            
            total_vacancies+=count_vacancies1

        print(f"Вакансии собраны, всего {total_vacancies}", end="\n\n")
        return json.dumps(self.vacaniecc, indent=4, ensure_ascii=False)

default_args = {
    'owner': 'airflow',    
    #'start_date': airflow.utils.dates.days_ago(2),
    # 'end_date': datetime(),
    # 'depends_on_past': False,
    #'email': ['airflow@example.com'],
    #'email_on_failure': False,
    # 'email_on_retry': False,
    # If a task fails, retry it once after waiting
    # at least 5 minutes
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}


parser = ParserRU()

with DAG(
    dag_id = "demo_etl",
    default_args=args,
    # schedule_interval='0 0 * * *',
    schedule_interval='@once',	
    dagrun_timeout=timedelta(minutes=60),
    description='use case of psql operator in airflow',
    start_date = airflow.utils.dates.days_ago(1)
) as dag_psql:
    start_pars = PythonOperator(
        task_id="start_pars",
        python_callable = parser.start_parsing(True),
        )
    
    create_table = PostgresOperator(
    sql = create_table_sql_query,
    task_id = "create_table_task",
    postgres_conn_id = "con_app_db"
    )

    get_id_vac = PostgresOperator(
        sql = get_id_appended_vac,
        task_id = "get_id_appended_vac",
        postgres_conn_id = "con_app_db"
        )

    create_table >> [get_id_vac, start_pars] 





if __name__ == "__main__":
        dag_psql.cli()
`
