### ISSUE TITLE
Task of dag stuck in queued state forever when using kubernetes executor, and triggered with a future execution date

### ISSUE THREAD

**Issue by madcolonel10** [apache/airflow#12089] opened 2020-11-04 12:38 UTC
**Airflow version: 1.10.12**
```python
import random
import string

import requests
from airflow import DAG
from airflow.contrib.sensors.python_sensor import PythonSensor
from airflow.operators.dummy_operator import DummyOperator
from datetime import datetime

dag = DAG(
    dag_id='newDebugDag',
    description='A simple tutorial DAG',
    schedule_interval=None,
    start_date=datetime(2020, 10, 30, 0, 0)
)

start = DummyOperator(task_id='run_this_first', dag=dag)


def wait_for_approval(dag_run, **context):
    software_id = dag_run.conf.get("softwareId", "Some Software Id")
    print("polling status for softwareId:{}".format(software_id))
    response = requests.get('https://5f8582eec29abd0016190be2.mockapi.io/api/v1/status')
    print(response.json())
    context["task_instance"].xcom_push(key="approverId", value="visardan-" + random.choice(string.ascii_letters))
    return response.json()[0]['status']


wait_for_approval = PythonSensor(
    task_id="wait_for_approval_debug",
    python_callable=wait_for_approval,
    dag=dag,
    poke_interval=30,
    provide_context=True,
    executor_config={"KubernetesExecutor": {"image": "apache/airflow:1.10.12-python3.6"}}
)

start >> wait_for_approval
```

```json
{
    "run_id":"run-eventId109bnfghak2",
    "conf":{
        "softwareId":"something"
    },
    "execution_date": "2020-11-04 10:38:43" //any future execution date
}
```

The first task executes fine (dummy start task) but the dag is stuck at second task. I can see the worker pod spun up and getting completed but the task status never gets updated and ui still says queued and dag is always in running state due to this.

![Screen Shot 2020-11-04 at 5 02 22 PM](https://user-images.githubusercontent.com/25412835/98112292-f7398800-1ec7-11eb-978d-ada384b0ac81.png)

![Screen Shot 2020-11-04 at 5 04 47 PM](https://user-images.githubusercontent.com/25412835/98112298-fbfe3c00-1ec7-11eb-8cea-a1699d5b03cc.png)

**Comment by grepthat** [comment] 2021-02-11 08:03
duplicate of https://github.com/apache/airflow/issues/13542 ? Are you still seeing this in Airflow 2.0 ?

**Comment by JieChenAtPonyai** [comment] 2021-03-11 14:22
I met a similar issue. After investigation, I find the root cause is the the worker pod does not update the status of task to RUNNING due to this dependence [RunnableExecDateDep](https://github.com/apache/airflow/blob/master/airflow/ti_deps/deps/runnable_exec_date_dep.py) is not met. So this task is stuck in queued state.
I think enabling [allow_trigger_in_future])https://github.com/apache/airflow/blob/f2558cdd55ee4900c7f7f0c300354c742cd38d8c/airflow/config_templates/default_airflow.cfg#L928) can resolve it.

**Closed as completed** 2022-05-28 21:17 UTC
Labels: kind:bug, area:Scheduler, provider:cncf-kubernetes
