### ISSUE TITLE
"duplicate key value violates unique constraint "dag_run_dag_id_execution_date_key" when triggering a DAG

### ISSUE THREAD

**Issue by kaojunsong** [apache/airflow#15150] opened 2021-04-02 07:33 UTC
**Apache Airflow version**:
2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.14

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

[2021-04-02 07:23:30,513] [ERROR] app.py:1892 - Exception on /api/v1/dags/auto_test/dagRuns [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_run_dag_id_execution_date_key"
DETAIL:  Key (dag_id, execution_date)=(auto_test, 1967-12-13 20:57:42.043+01) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/response.py", line 103, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/api_connexion/security.py", line 47, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/api_connexion/endpoints/dag_run_endpoint.py", line 231, in post_dag_run
    session.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "dag_run_dag_id_execution_date_key"
DETAIL:  Key (dag_id, execution_date)=(auto_test, 1967-12-13 20:57:42.043+01) already exists.

[SQL: INSERT INTO dag_run (dag_id, execution_date, start_date, end_date, state, run_id, creating_job_id, external_trigger, run_type, conf, last_scheduling_decision, dag_hash) VALUES (%(dag_id)s, %(execution_date)s, %(start_date)s, %(end_date)s, %(state)s, %(run_id)s, %(creating_job_id)s, %(external_trigger)s, %(run_type)s, %(conf)s, %(last_scheduling_decision)s, %(dag_hash)s) RETURNING dag_run.id]
[parameters: {'dag_id': 'auto_test', 'execution_date': datetime.datetime(1967, 12, 13, 19, 57, 42, 43000, tzinfo=Timezone('UTC')), 'start_date': datetime.datetime(2021, 4, 2, 7, 23, 30, 511735, tzinfo=Timezone('UTC')), 'end_date': None, 'state': 'running', 'run_id': 'dag_run_id_zstp_4435_postman11', 'creating_job_id': None, 'external_trigger': True, 'run_type': <DagRunType.MANUAL: 'manual'>, 'conf': <psycopg2.extensions.Binary object at 0x7f07b30b71e8>, 'last_scheduling_decision': None, 'dag_hash': None}]

**What you expected to happen**:
The second trigger success

**How to reproduce it**:
 Trigger a dag with the following conf:

`{
"dag_run_id": "dag_run_id_zstp_4435_postman",
"execution_date": "1967-12-13T19:57:42.043Z",
"conf": {}
}`

Then trigerring the same dag only with a different dag_run_id:

`{
"dag_run_id": "dag_run_id_zstp_4435_postman111",
"execution_date": "1967-12-13T19:57:42.043Z",
"conf": {}
}`

**Anything else we need to know**:

**Comment by kaxil** [comment] 2021-04-02 20:35
The DagRun table has the following constraints:

https://github.com/apache/airflow/blob/83d702c345f8f4ce16d32268f4f83ee508fea676/airflow/models/dagrun.py#L96-L97

which is why you can't create / trigger a DagRun that violates it i.e. you can't trigger a DAG with same execution_date or with same run_id.

**Comment by kaojunsong** [comment] 2021-04-02 23:51
@kaxil Thanks for your reply. I got your point, but the client gets a 500 HTTP code now, and I think it better if it returns 400 or 409 or any other suitable code.

**Comment by kaxil** [comment] 2021-04-03 00:12
> @kaxil Thanks for your reply. I got your point, but the client gets a 500 HTTP code now, and I think it better if it returns 400 or 409 or any other suitable code.

Agreed.

cc @ephraimbuddy

**Comment by vikramcse** [comment] 2021-04-03 06:11
@kaxil I would like to work on this issue

**Comment by ephraimbuddy** [comment] 2021-04-03 06:27
> @kaxil I would like to work on this issue

@vikramcse I have assigned it to you

**Comment by vikramcse** [comment] 2021-04-03 08:27
Hi @kaxil and @ephraimbuddy 

I am able to reproduce the issue and tried to resolve it.

Below is the error message returned by the `/dagRuns` api. My question is does the below returned message detail text is correct?
please let me know if it needs some change.

```javascript
{
    "detail": "DAGRun with DAG ID: 'taskflow', DAGRun ID: 'dag_run_id_zstp_4435_postman and DAGRun ExecutionDate '2021-04-03 07:50:16.317733+00:00' already exists",
    "status": 409,
    "title": "Conflict",
    "type": "http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/stable-rest-api-ref.html#section/Errors/AlreadyExists"
}
```

Thank You

**Comment by ephraimbuddy** [comment] 2021-04-03 10:39
> Hi @kaxil and @ephraimbuddy
> 
> I am able to reproduce the issue and tried to resolve it.
> 
> Below is the error message returned by the `/dagRuns` api. My question is does the below returned message detail text is correct?
> please let me know if it needs some change.
> 
> ```js
> {
>     "detail": "DAGRun with DAG ID: 'taskflow' and DAGRun ExecutionDate '2021-04-03 07:50:16.317733+00:00' already exists",
>     "status": 409,
>     "title": "Conflict",
>     "type": "http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/stable-rest-api-ref.html#section/Errors/AlreadyExists"
> }
> ```
> 
> Thank You

Yes. It is good. Make a PR then if there are any suggestions, we would give

**Closed as completed** 2021-04-06 14:05 UTC
Labels: kind:bug, area:API, good first issue

**Comment by gshand-beta** [comment] 2022-05-05 19:24
> The DagRun table has the following constraints:
> 
> https://github.com/apache/airflow/blob/83d702c345f8f4ce16d32268f4f83ee508fea676/airflow/models/dagrun.py#L96-L97
> 
> which is why you can't create / trigger a DagRun that violates it i.e. you can't trigger a DAG with same `execution_date` or with same `run_id`.

Seems strange to have that unique constraint. If two DAG runs have different run_ids, why not let them run at the same time? 

Can anyone provide context as to why that constraint is necessary?

If you're invoking DAG runs from multiple processes running concurrently, it's pretty easy to run into this issue. I'd classify this as a bug, as expected behavior is that Airflow should be able to tolerate concurrent invocations.

**Comment by potiuk** [comment] 2022-05-09 13:47
> Seems strange to have that unique constraint. If two DAG runs have different run_ids, why not let them run at the same time?

Because historically execution date was the key not run_id. This has since been removed and in Airflow 2.2 the primary key is run_id and execution_date is just a field. See the changelo. https://airflow.apache.org/docs/apache-airflow/2.2.4/changelog.html#airflow-2-2-0-2021-10-11

**Comment by GolikovAndrey** [comment] 2023-10-30 12:55
> > Seems strange to have that unique constraint. If two DAG runs have different run_ids, why not let them run at the same time?
> 
> Because historically execution date was the key not run_id and the whole datamodel was based on execution_date being part of foreign key in multiple tables. This has since been removed and in Airflow 2.2 the primary key is run_id and execution_date is just a field. See the changelog https://airflow.apache.org/docs/apache-airflow/2.2.4/changelog.html#airflow-2-2-0-2021-10-11

Now we have Airflow v. 2.6.3, but I still see field execution_date in constrained fields (uniqueness constraint).
![image](https://github.com/apache/airflow/assets/61521604/22d25cfc-7ae7-4c1d-9982-4e6681a8712d)

**Comment by potiuk** [comment] 2023-10-30 18:37
> Now we have Airflow v. 2.6.3, but I still see field execution_date in constrained fields (uniqueness constraint).

You read my answer wrongly. I never said it has been removed - I just explained that it's not part of the primary key.

The fact that run_id has been added and switched to primary key does not mean that unique execution date has been removed. There are backwards compatiblity reasons that make it more difficult. I believe there were some discussions about removing that limitation and I think there is a general consensus it could be removed, but all the consequences of it has not been yet hashed out in discussion (depending on how deep of a change it will be it might be enough to have PR for that or maybe it will need an AIP (Airlfow Improvement Proposal -  https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals) 

If you woudl like to lead that effort @GolikovAndrey - feel free to start discussion on devlist (this kind of change requires it) - see https://airflow.apache.org/community/ . As everything in our project - such change can be lead by anyone who feels like they need it - and starting with outlining your proposal and describing the consequences you think it will have is a good start.

**Comment by GolikovAndrey** [comment] 2023-10-31 07:56
> > Now we have Airflow v. 2.6.3, but I still see field execution_date in constrained fields (uniqueness constraint).
> 
> You read my answer wrongly. I never said constraint have been removed - I just explained that it's not part of the primary key.
> 
> The fact that run_id has been added and switched to primary key does not mean that unique execution date has been removed. There are backwards compatiblity reasons that make it more difficult. I believe there were some discussions about removing that limitation and I think there is a general consensus it could be removed, but all the consequences of it has not been yet hashed out in discussion (depending on how deep of a change it will be it might be enough to have PR for that or maybe it will need an AIP (Airlfow Improvement Proposal - https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)
> 
> If you woudl like to lead that effort @GolikovAndrey - feel free to start discussion on devlist (this kind of change requires it) - see https://airflow.apache.org/community/ . As everything in our project - such change can be lead by anyone who feels like they need it - and starting with outlining your proposal and describing the consequences you think it will have is a good start.

Thank you for reply and explanation!

Unfortunately, at the moment I am not at the level of a developer to try to suggest or make changes to such a large project.

**Comment by potiuk** [comment] 2023-10-31 09:37
>  Unfortunately, at the moment I am not at the level of a developer to try to suggest or make changes to such a large project.

 Sure. Always worth trying. We are relying on ~ 2700 contributors to develop airflow so it's always worth trying to see if someone who cares about a feature would like to contribute it
