### ISSUE TITLE
Break up airflow-providers-google-cloud into sub providers

### ISSUE THREAD

**Issue by radumas** [apache/airflow#43049] opened 2024-10-15 18:56 UTC
### Description

Currently there is one package to install if you want to manage connections to Google Cloud,  `apache-airflow-providers-google`, this package contains dependencies for Google services including:

> -  [Google Ads](https://ads.google.com/)
> -  [Google Cloud (GCP)](https://cloud.google.com/)
> -  [Google Firebase](https://firebase.google.com/)
> -  [Google LevelDB](https://github.com/google/leveldb/)
> -  [Google Marketing Platform](https://marketingplatform.google.com/)
> -  [Google Workspace](https://workspace.google.com/) (formerly Google Suite)

Breaking up this overarching package into its components could streamline installation for people who are just concerned with a component. I haven't looked into the structure/code for this component so I have no idea how complicated this is! 

### Use case/motivation

Currently we are pulling data from the Google Sheets API, and we want to be managing the necessary connection using a Google Connection. However, this does entail installing 48 google packages. We would like a leaner installation and also to reduce the complexity of our installations in case this leads to conflicts in installation.

### Related issues

Maybe this? https://github.com/apache/airflow/issues/31370

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2024-10-15 21:51
Duplicate of https://github.com/apache/airflow/issues/15933 - if you would like to attempt to do it feel free - but it's 3 years and  it's not yet done, as it requires quite an effort. If you would like to do it - feel free @radumas - otherwise it will have to wait for someone who will take on the task.

Closing as duplicate.

**Closed as completed by potiuk** 2024-10-15 21:51 UTC
Labels: provider:google, area:providers, kind:feature, needs-triage
