### ISSUE TITLE
Form validation needed for conn_id input in Connections section

### ISSUE THREAD

**Issue by MahmoudFettal** [apache/airflow#30794] opened 2023-04-21 14:46 UTC
### What happened

When entering a conn_id in the Connections section, there is currently no form validation in place. This allows users to input a conn_id with a space at the end for example, which results in errors when running tasks. The error message displayed states that the connection doesn't exist, which can be misleading and time-consuming to debug.

### What you think should happen instead

Form validation should be added to the Connections section to prevent conn_id inputs with trailing spaces from being saved and instead save the conn_id without the trailing spaces.

### How to reproduce

- Go to the Connections section of the application.
- Enter a conn_id with a space at the end.
- Save the form or attempt to run a task with the conn_id.

### Operating System

Linux - Ubuntu 20.04

### Versions of Apache Airflow Providers

2.5.1

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pankajastro** [comment] 2023-04-21 15:54
maybe duplicate https://github.com/apache/airflow/issues/29836

**Comment by eladkal** [comment] 2023-04-21 16:42
Closing as duplicate of https://github.com/apache/airflow/issues/29836
PRs are welcome! feel free to raise any code suggestion directly (no submitting of issue is required) simply describe the change in the PR itself

**Closed as not planned by eladkal** 2023-04-21 16:42 UTC
Labels: kind:bug, area:core, needs-triage
