### ISSUE TITLE
Celery 5.0

### ISSUE THREAD

**Issue by mik-laj** [apache/airflow#11301] opened 2020-10-06 11:30 UTC
Hello,,

The [new Celery 5.0](https://docs.celeryproject.org/en/stable/whatsnew-5.0.html) has been released and we may consider migrating to this version. I don't know if it has to happen now, if we should wait for version 5.1 or do it now. I am creating this ticket to track this version.

To process this issue, we should consider the consequences of this update, update the CLI calls, update API calls, and test these versions thoroughly.

@auvipy Can you tell a little more about this release? Is this release stable enough to update our project to these versions?  What consequences could this update have?

**Comment by wolfrubin** [comment] 2020-10-07 20:08
On this subject. I've been setting up airflow for the first time and I was trying to run the celery worker using `airflow worker` with Celery 5.0 and have ran into issues that I resolved by downgrading my installed Celery version to 4.4.7. I am running airflow 1.10.12.

As far as I can tell it's to do with the Celery migration to use click for their cli instead of their custom one. I can try and find the stacktrace if you'd like and add it as an issue?

**Comment by turbaszek** [comment] 2020-10-07 20:23
> As far as I can tell it's to do with the Celery migration to use click for their cli instead of their custom one. I can try and find the stacktrace if you'd like and add it as an issue?

@wolfrubin that would be helpful!

**Comment by wolfrubin** [comment] 2020-10-07 20:44
@turbaszek you've beaten me to it. The second one was the stack trace I was getting before downgrading to 4.4.7.

**Comment by parayaluyanta** [comment] 2020-11-28 02:00
`5.0.2 (singularity)` did not work for me as well. Downgrading to `4.4.7` did.

```bash
apache-airflow==1.10.9
celery==4.4.7
celery[rabbitmq]==4.4.7
```

**Comment by auvipy** [comment] 2020-11-28 04:21
celery 5.0-5.0.2 has several regressions. should wait for 5.0.3 at least to test

**Comment by super017** [comment] 2020-12-10 02:22
> 芹菜`5.0.2 (singularity)`在气流方面对我也不起作用`1.10.9`。
> 
> ```shell
> 尾-f /var/log/airflow/airflow-worker-stderr---supervisor-josn515o.log 
>      return f（* args，** kwargs）
>   File “ /usr/local/lib/python3.6/site-packages/ airflow / bin / cli.py “，第1395行，在worker中
>     worker = worker.worker（app = celery_app）
>   文件” /usr/local/lib/python3.6/site-packages/click/core.py “，第829行，在__call__中
>     返回self.main（* args，** kwargs）
>   文件“ /usr/local/lib/python3.6/site-packages/click/core.py ”，线781，在主
>     用self.make_context（PROG_NAME，ARGS，**另计）为CTX：
>   文件“ /usr/local/lib/python3.6/site-packages/click/core.py ”，线路698，在make_context 
>     ctx = Context（自己，info_name = info_name，parent = parent，**额外）
> TypeError：__ init __（）获得了意外的关键字参数' app '
> ```
> 
> 降级为`4.4.7`。
> 
> ```shell
> apache-airflow == 1.10.9
> 芹菜== 4.4.7
> 芹菜[rabbitmq] == 4.4.7
> ```
Two days ago when I was in the configuration airflow also appears this question,and my solution is 
`pip install apache-airflow
pip install apache-airflow[mysql]
pip install apache-airflow[celery] `

accorfing to dependency,the version of celery is 4.4.7

**Comment by super017** [comment] 2020-12-10 02:24
> celery `5.0.2 (singularity)` did not work for me as well with airflow `1.10.9`.
> 
> ```shell
> tail -f /var/log/airflow/airflow-worker-stderr---supervisor-josn515o.log 
>     return f(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 1395, in worker
>     worker = worker.worker(app=celery_app)
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 781, in main
>     with self.make_context(prog_name, args, **extra) as ctx:
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 698, in make_context
>     ctx = Context(self, info_name=info_name, parent=parent, **extra)
> TypeError: __init__() got an unexpected keyword argument 'app'
> ```
> 
> Downgrading to `4.4.7` did.
> 
> ```shell
> apache-airflow==1.10.9
> celery==4.4.7
> celery[rabbitmq]==4.4.7
> ```

Two days ago when I was in the configuration airflow also appears this question,and my solution is
> pip install apache-airflow
> pip install apache-airflow[mysql]
> pip install apache-airflow[celery]

accorfing to dependency,the version of celery is 4.4.7

**Comment by auvipy** [comment] 2020-12-10 05:01
celery==5.0.4 released so new testing could be started

**Comment by potiuk** [comment] 2020-12-10 13:47
> celery==5.0.4 released so new testing could be started

Cool!

**Comment by yeago** [comment] 2020-12-20 06:14
likely related https://groups.google.com/forum/embed/#!topic/celery-users/sfU1Bzsxn8c

**Comment by xangxiong** [comment] 2021-02-04 16:20
For anyone who is experiencing this issue, here is how I changed my airflow worker commands to bypass Airflow for now.

Previously:
/usr/local/bin/airflow worker --log-file "${LOG_FILE}" --queues "${AIRFLOW_CELERY_QUEUE}" --celery_hostname "${AIRFLOW_CELERY_HOSTNAME}" -c "${AIRFLOW_CELERY_INSTANCES}"

Current with Celery 5.0.5:
/usr/local/bin/celery --app airflow.executors.celery_executor worker -Q "${AIRFLOW_CELERY_QUEUE}" -c "${AIRFLOW_CELERY_INSTANCES}" --logfile "${LOG_FILE}" --hostname "${AIRFLOW_CELERY_HOSTNAME}"

Hopefully this helps you if you are on Airflow 1.10.X.

**Comment by auvipy** [comment] 2021-06-01 12:51
this should be celery 5.1 now

**Closed as completed** 2021-08-27 12:49 UTC
Labels: area:Scheduler, kind:feature

**Comment by NiklasBeierl** [comment] 2021-09-09 08:10
Still experiencing this with:
```
apache-airflow==2.1.3
apache-airflow-providers-celery==2.1.0
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-sqlite==2.0.1
celery==5.1.2
```
I am not sure if it should be resolved? Maybe #17397 is not part of any release yet?

**Comment by NiklasBeierl** [comment] 2021-09-09 09:14
So after much pain and agony, I was able to get up and running again by fixing the flower version to:
```
flower==0.9.7
``` 
This worked with airflow 2.1.3 and 2.0.2.
If you are trying to apply this fix be careful to install flower AFTER airflow, since installing airflow will bump flower to 1.0.0.

**Comment by potiuk** [comment] 2021-09-09 10:13
Interesting. The Celery 5 support is coming only in Airflow 2.2. There were some changes needed to convert airflow to work with the new celery and flower - https://github.com/apache/airflow/pull/17397/files so I am not really sure if what you have now @NiklasBeierl  will work for all cases.
