### ISSUE TITLE
Chart should not create Redis secrets while using the KubernetesExecutor

### ISSUE THREAD

**Issue by slmg** [apache/airflow#30420] opened 2023-04-01 18:58 UTC
### Official Helm Chart version

1.8.0 (latest released)

### Apache Airflow version

2.5.1

### Kubernetes Version

1.21.14

### Helm Chart configuration

```yaml
# values.yaml

executor: "KubernetesExecutor"
```

### Docker Image customizations

None.

### What happened

The [redis secrets](https://github.com/apache/airflow/blob/2.5.1/chart/templates/secrets/redis-secrets.yaml) got created

### What you think should happen instead

Given all the resources defined in [./chart/templates/redis](https://github.com/apache/airflow/tree/2.5.1/chart/templates/redis) contain the below condition, it does not seem right to me to get Redis secrets created in the context of the `KubernetesExecutor`. 

```go
{{- if and .Values.redis.enabled (or (eq .Values.executor "CeleryExecutor") (eq .Values.executor "CeleryKubernetesExecutor")) }}
```

Redis secrets might have been missed when this condition was added, because they are located in a different folder?

### How to reproduce

Render helm templates
```sh
helm template test apache-airflow/airflow --version 1.8.0 --values values.yaml > rendered.yaml
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment] 2023-04-01 21:41
@slmg assigned you

**Comment by amoghrajesh** [comment] 2023-05-02 04:03
Is anyone actively working on this issue @hussein-awala @slmg?
I would not mind fixing this if nobody is working on this now :)

**Comment by hussein-awala** [comment] 2023-05-02 08:46
@amoghrajesh there is an open PR #30423, you can read the comments and join the discussion

**Comment by amoghrajesh** [comment] 2023-05-22 18:35
I was checking the discussions @hussein-awala. Looks like the PR has gone stale.

**Comment by amoghrajesh** [comment] 2023-06-26 10:30
@hussein-awala continuing the effort which went stale here: https://github.com/apache/airflow/pull/32141 in a new PR. Take a look when you have some time, it is a simple conditional added

**Comment by amoghrajesh** [comment] 2023-07-13 05:17
As per discussions on this issue itself and the PR: https://github.com/apache/airflow/pull/32141, this looks to be how it is designed and it is expected behaviour here. Closing the issue as expected behaviour.

**Closed as completed by amoghrajesh** 2023-07-13 05:17 UTC
Labels: kind:bug, good first issue, area:helm-chart
