### ISSUE TITLE
Airflow CLI command "dags list" command returning unexpected output

### ISSUE THREAD

**Issue by Mrhacktivist** [apache/airflow#37228] opened 2024-02-07 16:52 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.5.1

### What happened?

Airflow CLI command "dags list" command returning unexpected output containing "Sample operation result: <Task(DatabricksSqlOperator): select_data>
Sample operation type: <class 'airflow.providers.databricks.operators.databricks_sql.DatabricksSqlOperator'>" in its response

### How to reproduce

It's  getting returned in specific environment only. Tried in other environments with same version and there is no such output

### Operating System

amazon linux 2

### Deployment

Amazon (AWS) MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment] 2024-02-07 21:34
Can you please post some more details about the unexpected details?
Can you please post the full CLI you used?
Also if possible the full output would be good. Redacted as well.
Can you please tell us whether the reported operators are used in your DAGs (assuming yes)?
Can you check whether the same is happening on the most recent version of Airflow?

**Comment by potiuk** [comment] 2024-02-08 13:06
Well, those messages come from your DAG or configuraiton (local settings) while the dags are being parsed. Just don't print output to stdout in your DAGs when they are parsed. 

Look for the places where your DAGs write those messages. The problem is that parsing DAG executes your code so if you do something in your code to use stderr, this creates the problem.

We currently suppress logs and warnings for all commands that return any json output with decorator below - but it does not suppress stuff that you print manually in your dags using `print()`

Generally it's a good practice to use logging facilities to print diagnostics info rather than printing to stdout directly. 

```
def suppress_logs_and_warning(f: T) -> T:
    """Suppress logging and warning messages in cli functions."""

    @functools.wraps(f)
    def _wrapper(*args, **kwargs):
        _check_cli_args(args)
        if args[0].verbose:
            f(*args, **kwargs)
        else:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                logging.disable(logging.CRITICAL)
                try:
                    f(*args, **kwargs)
                finally:
                    # logging output again depends on the effective
                    # levels of individual loggers
                    logging.disable(logging.NOTSET)

    return cast(T, _wrapper)
```

**Comment by potiuk** [comment] 2024-02-08 13:06
Closing as invalid.

**Closed as completed** 2024-02-08 13:06 UTC
Labels: kind:bug, invalid, area:CLI, pending-response, needs-triage
