### ISSUE TITLE
Can't install latest soda-core (soda-core-postgres)

### ISSUE THREAD

**Issue by semcha** [apache/airflow#33721] opened 2023-08-25 10:03 UTC
### Apache Airflow version

2.7.0

### What happened

Get error when install latest soda-core-postgres on Airflow 2.7.0.
```
ERROR: Cannot install apache-airflow==2.7.0 and soda-core==3.0.48 because these package versions have conflicting dependencies.

The conflict is caused by:
    apache-airflow 2.7.0 depends on opentelemetry-api==1.15.0
    soda-core 3.0.48 depends on opentelemetry-api~=1.16.0
```

### What you think should happen instead

Up opentelemetry-api to 1.16.0

### How to reproduce

`pip install -U apache-airflow==2.7.0 soda-core-postgres==3.0.48`

### Operating System

MacOS 13.5

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by semcha** [comment] 2023-08-25 10:27
https://github.com/sodadata/soda-core/blob/99dda9547bc7aa6202f20f9be25ad0f00ebb9cd6/soda/core/setup.py#L17

**Comment by eladkal** [comment] 2023-08-25 11:58
duplicate of https://github.com/apache/airflow/issues/33577

**Closed as not planned by eladkal** 2023-08-25 11:58 UTC
Labels: kind:bug, duplicate, area:core, needs-triage
