### ISSUE TITLE
Airflow 2.1.0 - after upgrade admin role does not have permissions to add/edit/delete on users view

### ISSUE THREAD

**Issue by Walderman** [apache/airflow#16715] opened 2021-06-29 15:57 UTC
**Apache Airflow version**:
2.1.0

**Environment**:

- **Cloud provider or hardware configuration**:
-  AWS ECS EC2 mode. RDS PostgreSQL for DB.
- **OS** (e.g. from /etc/os-release):
- RedHat
- - **Other**
- LDAP authentication enabled

**What happened**:
We upgraded from 2.0.1 to 2.1.0 and now when i go to Users view (as admin). I cannot see delete/edit/add buttons - if i try to simply navigate by chaniging url from Users/list to Users/edit/1 for example I get Access Denied as per FAB.
I checked underlying permission tables and from what i can see Admin Role does not have those permissions anymore there.

I tried deleting all permissions and with :
```sql
delete from dbo.ab_permission_view_role
delete from "dbo"."ab_permission_view" 
```
and then re-run airflow sync-perms 
this did not help.

loks like the default permissions settings are now defaulting to read-only even for admin on users tab.

the following query:
```sql
select abv.permission_id, abv.view_menu_id, avm.name as view_name, ap.name as permission_name
from "dbo"."ab_permission_view"  abv
inner join dbo.ab_view_menu avm
on abv.view_menu_id = avm.id
inner join dbo.ab_permission ap
on abv.permission_id = ap.id
WHERE
    avm.name = 'Users'
```
returns only one row with can_read under permission_name

not sure if this is related, but i can see this change in 2.1.0
https://github.com/apache/airflow/pull/13856/commits

**What you expected to happen**:
Users with Admin role can still fully edit Users view.

**How to reproduce it**:
Best i can say: just upgrade from 2.0.1 to 2.1.0

**Comment by jedcunningham** [comment] 2021-06-29 16:50
Thanks for the report @Walderman!

Duplicate of #16202

**Closed as completed by jedcunningham** 2021-06-29 16:50 UTC
Labels: kind:bug, duplicate
