### ISSUE TITLE
Bug count dags

### ISSUE THREAD

**Issue by khmelevskiy** [apache/airflow#33912] opened 2023-08-30 10:08 UTC
### Apache Airflow version

2.7.0

### What happened

If someone rename dag, than count became +1.
At the moment I have two times less dags, than I see in web ui.
Past version(2.6.2) worked without this problem.

On the screenshot you can see the place I am writing about:

<img width="379" alt="image" src="https://github.com/apache/airflow/assets/7830755/9eb09bfb-349a-4814-98f2-b3c2c2551442">

### How to reproduce

Build 2.7.0 (python 3.10) and write some dags and later rename it.

### Operating System

mac os 13.5.1

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment] 2023-08-30 10:20
- Duplicate of: #33698
- Should be fixed by: #33778 in Airflow 2.7.1

**Closed as completed by Taragolis** 2023-08-30 10:20 UTC
Labels: kind:bug, duplicate, area:core
