### ISSUE TITLE
Airflow DAG graph is not drawing the run_id passed as argument

### ISSUE THREAD

**Issue by fbmatilla** [apache/airflow#30602] opened 2023-04-12 14:32 UTC
### Apache Airflow version

2.5.3

### What happened

Through the Web Interface: If we look for a specific DAG run id (before the last 25 runs) and we try to access the graph:

![image](https://user-images.githubusercontent.com/108265743/231487554-6bfdea62-f12e-429a-8c22-d38069280123.png)

A the details of a different RUNID are really appearing:

![image](https://user-images.githubusercontent.com/108265743/231488495-0b373749-251e-48e5-a40b-51927b64ecda.png)

Looks like the issue is related to the fact that the RUNID passed as argument is not in the combobox of the default selected runs:

![image](https://user-images.githubusercontent.com/108265743/231489608-ede9f530-250e-42c9-8a3d-09f046a5b9ce.png)

### What you think should happen instead

The execution details of the run id passed as argument should be shown.

### How to reproduce

Just follow the steps described in the "What happened" section.

### Operating System

Ubuntu 20.04.5

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==7.3.0
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-cncf-kubernetes==5.2.2
apache-airflow-providers-common-sql==1.3.4
apache-airflow-providers-databricks==4.0.0
apache-airflow-providers-docker==3.5.1
apache-airflow-providers-elasticsearch==4.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-google==8.11.0
apache-airflow-providers-grpc==3.1.0
apache-airflow-providers-hashicorp==3.3.0
apache-airflow-providers-http==4.2.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-microsoft-azure==5.2.1
apache-airflow-providers-microsoft-mssql==3.3.2
apache-airflow-providers-mysql==4.0.2
apache-airflow-providers-odbc==3.2.1
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-redis==3.1.0
apache-airflow-providers-sendgrid==3.1.0
apache-airflow-providers-sftp==4.2.4
apache-airflow-providers-slack==7.2.0
apache-airflow-providers-snowflake==4.0.4
apache-airflow-providers-sqlite==3.3.1
apache-airflow-providers-ssh==3.5.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment] 2023-04-15 15:12
I can't reproduce on 2.5.3 :thinking: can you share the webserver log when you refresh the page?

**Comment by fbmatilla** [comment] 2023-04-17 06:54
Hi Hussein,

Sure. To be able to reproduce it, it is important to access a RunId that is not included in combobox of the latest 25:

![image](https://user-images.githubusercontent.com/108265743/232405905-93d36650-7e65-4d8e-bcf3-c5e0d29719bb.png)

In this new example, we are trying to access the run id ES_2023-04-10T09:00:03.594297, however this one CL_2023-04-14T13:00:11.808718 is really appearing.


This are the webserver logs at that time:
[ewok-webserver-775db7bf4d-p8m5z.log](https://github.com/apache/airflow/files/11247131/ewok-webserver-775db7bf4d-p8m5z.log)

**Comment by robi-ng** [comment] 2023-04-18 01:33
I'm facing the same issue with Airflow 2.5.3.

**Comment by fbmatilla** [comment] 2023-05-19 07:24
Hi, this is still happening in 2.5.3, we should keep it open. Thx.

**Comment by sbrinkhorst** [comment] 2023-05-26 12:42
We're facing the same issue. I upgraded from 2.5.1 to 2.5.3 earlier this week. I think the problem was introduced in 2.5.2, at least I still saw it when I downgraded our acceptance environment to that version. 

After clicking around a bit we found the following:

In the `List Dag Run` table there are two columns you can click on: `Dag Id` and `Run Id`

If you click on the dag name in the `Dag Id` column it actually adds the execution date to the url and that typically takes you to the DAG you're looking for:
```
https://example.com/dags/your-dag/graph?execution_date=2023-05-26+10%3A01%3A31.066801%2B00%3A00
```

In the `Run Id` column it also adds the DAG ID to the URL as well:
```
https://example.com/dags/your-dag/graph?run_id=manual_2023-05-26T10%3A01%3A30.964UTC&execution_date=2023-05-26+10%3A01%3A31.066801%2B00%3A00
```

It seems that the date selector for the execution date is not filled correctly if you also provide the run_id, and then it defaults to now. Then it tries to look up your run_id, which only succeeds if your run is in the table (so that will be if it in the 25 most recent runs). You can see in the screenshot @fbmatilla provided that the execution_date from the URL does not match the UI. 

So I would describe the issue as "DAG graph view does not use execution_date from URL correctly if dag_run is also provided".

The `List Task Instance` table has the same issue when clicking on the Run Id, that issue was already present for a longer time. (There the Dag Id column doesn't have the execution_date in the URL but you can go via the Task Id column.) Has something been done to make these lists more consistent, but now it is consistently wrong?

**Comment by hussein-awala** [comment] 2023-05-26 13:42
I just tested it with 2.6.1 and it seems to work normally.

I created this dag:
```python
import pendulum

from airflow import DAG
from airflow.operators.empty import EmptyOperator

with DAG(
    "debug_dag_run",
    start_date=pendulum.datetime(2023, 5, 1),
    schedule_interval="@daily",
    catchup=True,
):
    EmptyOperator(task_id="empty_task")
```
which created 25 runs, and I triggered 3 runs manually (28 in total).
![Screenshot from 2023-05-26 15-13-36](https://github.com/apache/airflow/assets/21311487/17d6d75b-092a-485e-8a56-3a7c02b3f149)

When I choose a run before the last 25 runs, the select list is updated to have just this run_id, and the selected graph is updated to the desired run:
![Screenshot from 2023-05-26 15-13-52](https://github.com/apache/airflow/assets/21311487/0d03d94d-a497-4df1-bd4a-63487c67684a)
![Screenshot from 2023-05-26 15-13-56](https://github.com/apache/airflow/assets/21311487/c002fd29-4a88-4f8e-8c08-f07d74ff81a8)

I will close the issue as completed.
I let you test with 2.6.1, and we can reopen it if you still have the same issue.

**Closed as completed by hussein-awala** 2023-05-26 13:42 UTC
Labels: kind:bug, good first issue, duplicate, pending-response, area:core, _eol_affected_version:2.5

**Comment by sbrinkhorst** [comment] 2023-05-26 15:11
Thank you. If I test it locally with that version it works for me again too. We will do the actual upgrade in the next few weeks, but I see no reason why it should not work there.

**Comment by sbrinkhorst** [comment] 2023-06-03 12:42
Our most used DAG ran close to 90,000 times in the last 30 days, so it is not really feasible for us to rely on increasing the nr of dag runs. We will just upgrade to the new version.

**Comment by hterik** [comment] 2023-10-03 05:53
Similar problem present in 2.7.1 https://github.com/apache/airflow/issues/34723

**Comment by fbmatilla** [comment] 2023-11-13 08:35
Hi,

confirmed, this is happening again in version 2.7.2, can we open this bug again, please?

Thanks.

**Comment by potiuk** [comment] 2023-11-13 09:01
> Hi,
> 
> confirmed, this is happening again in version 2.7.2, can we open this bug again, please?
> 
> Thanks.

Why do you want to reopen it @fbmatilla since this is apparently duplicate of https://github.com/apache/airflow/issues/34723 as @hterik noticed ? Or is it different? Can you take a close look and explain?

**Comment by fbmatilla** [comment] 2023-11-13 09:04
Absolutely right. Sorry, I did not see that. Thanks @potiuk.

**Comment by shlomiken** [comment] 2025-03-11 09:48
This happens in 2.9.1 as well - the whole drill down from one specific run into multiple runs idea is bad.
you want to troubleshoot fast and not look at 25-1000 runs. 
also like said above - we run throusands of dags a day , its not possible to view them all in this view
