### ISSUE TITLE
Scheduler not exiting after SIGTERM with KubeExecutor

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#11982] opened 2020-10-30 19:05 UTC
**Apache Airflow version**: 2.0.0a2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): v1.15.12

**Environment**:
- **OS** (e.g. from /etc/os-release): CentOS 7

**What happened**:

When using KubernetesExecutor, a single SIGTERM doesn't result in the scheduler actually exiting cleanly. However, it will exit after receiving a second SIGTERM.

The same behavior happens if you have an exception in the scheduler. An easy way to replicate it is to raise in `pod_mutation_hook`.

In practice, this means the scheduler doesn't get restarted by K8s after encountering a exception. Or, when terminating the scheduler pod, it sticks around until k8s ultimately sends it a SIGKILL after its grace period is up.

**What you expected to happen**:

The scheduler to exit after a single SIGTERM.

**How to reproduce it**:
The easiest way to reproduce it is to simply send a SIGKILL to your KubernetesExecutor scheduler pod:

```
$ kubectl exec {scheduler_pod_name} kill 1
```

Note, the pod stays running, while the logs report:

```
[2020-10-30 17:34:09,581] {scheduler_job.py:794} INFO - Exiting gracefully upon receiving signal 15
[2020-10-30 17:34:10,586] {process_utils.py:97} INFO - Sending Signals.SIGTERM to GPID 59
[2020-10-30 17:34:10,879] {process_utils.py:63} INFO - Process psutil.Process(pid=59, status='terminated', exitcode=0, started=
'17:33:23') (59) terminated with exit code 0
[2020-10-30 17:34:10,882] {process_utils.py:97} INFO - Sending Signals.SIGTERM to GPID 59
[2020-10-30 17:34:10,882] {scheduler_job.py:1329} INFO - Exited execute loop
```

Issue another `kill`:
```
$ kubectl exec {scheduler_pod_name} kill 1
```

And the pod will be restarted by k8s.

If you can't reproduce it, let me know and I'll try and get something running on kind.

**Anything else we need to know**:

The same behavior happens if you have an exception in the scheduler. An easy way to replicate it is to raise in a `pod_mutation_hook`.

**Comment by jedcunningham** [comment] 2020-10-30 19:06
@dimberman

**Comment by ashb** [comment] 2020-12-02 21:05
@jedcunningham So I haven't tested your _exact_ scenario, but Im not able to reproduce the scheduler not stopping when given a SIGTERM.

What docker image are you using? What is your entrypoint? Are you able to test with beta3 and see if the problem persists?

**Comment by jedcunningham** [comment] 2020-12-03 21:59
We are using a `centos:8` based image (though it was happening with `centos:7` also). No entrypoint, a straight `airflow scheduler`. Yes, still happens in beta3.

Another way to observer this is with `kubectl delete pod`, which sends a sigterm and (by default) if the container hasn't exited in 30s k8s sends a sigkill. So you can swap my "exec kill 1" with a naive delete pod and if the old pod sticks around for 30s you've ran across this issue. Airflow would never have exited (from what I've seen), k8s just comes along and forces it. e.g:
`date; kubectl delete pods {scheduler_pod} --grace-period=120; date`
(^ adjust the grace period as desired)
(Also only reproduces without dumb-init - more on that later)

With breeze:
```
$ ./breeze kind-cluster start
$ ./breeze kind-cluster deploy
$ ./breeze kind-cluster shell
$ kubectl get pods
$ kubectl exec -i -t {scheduler_pod} bash
// note: background then foreground so the pid is printed
# airflow scheduler & fg

// Now, in another shell
$ ./breeze kind-cluster shell
$ kubectl exec -i -t {scheduler_pod} bash
# kill {pid from above}
// note, it doesn't actually exit
# kill {pid from above}
// now it exits
```

Now, dumb-init might be why you aren't able to replicate. By default, dumb-init forwards signals to ALL childen, not just the direct child:
https://github.com/Yelp/dumb-init#session-behavior

If sigterm is sent to them all, it exits cleanly:
```
# dumb-init -- airflow scheduler & fg
```

However, if you toggle `--single-child`, you still see the same behavior:
```
# dumb-init --single-child -- airflow scheduler & fg
```

Seems like airflow should cleanly exit with a sigterm to just the primary process.

**Comment by ashb** [comment] 2020-12-04 11:35
Tested like this:

```
docker run --rm --entrypoint bash apache/airflow:master-python3.6-ci -c 'airflow db upgrade && exec airflow scheduler'
```

verified that scheduler is pid 1:

```
airflow ❯ docker exec -ti pensive_williamson ps -efw
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0 13 11:34 ?        00:00:04 /usr/local/bin/python /usr/local/bin/airflow scheduler
root          43       1  0 11:34 ?        00:00:00 airflow scheduler -- DagFileProcessorManager
root          78       0  0 11:34 pts/0    00:00:00 ps -efw
```

Sending pid1 a SIGTERM:

```
airflow ❯ docker exec -ti pensive_williamson kill -TERM 1
```

And then scheduler logs

```
[2020-12-04 11:34:18,234] {scheduler_job.py:1247} INFO - Starting the scheduler
[2020-12-04 11:34:18,234] {scheduler_job.py:1252} INFO - Processing each file at most -1 times
[2020-12-04 11:34:18,237] {dag_processing.py:250} INFO - Launched DagFileProcessorManager with pid: 43
[2020-12-04 11:34:18,238] {scheduler_job.py:1757} INFO - Resetting orphaned tasks for active dag runs
[2020-12-04 11:34:18,240] {settings.py:52} INFO - Configured default timezone Timezone('UTC')
[2020-12-04 11:34:18,247] {dag_processing.py:518} WARNING - Because we cannot use more than 1 thread (parsing_processes = 2 ) when using sqlite. So we set parallelism to 1.
[2020-12-04 11:35:05,817] {scheduler_job.py:752} INFO - Exiting gracefully upon receiving signal 15
[2020-12-04 11:35:06,820] {process_utils.py:95} INFO - Sending Signals.SIGTERM to GPID 43
[2020-12-04 11:35:06,994] {process_utils.py:61} INFO - Process psutil.Process(pid=43, status='terminated', exitcode=0, started='11:34:18') (43) terminated with exit code 0
[2020-12-04 11:35:06,995] {process_utils.py:95} INFO - Sending Signals.SIGTERM to GPID 43
[2020-12-04 11:35:06,995] {scheduler_job.py:1302} INFO - Exited execute loop
```

And it does exit.

**Comment by jedcunningham** [comment] 2020-12-04 16:37
That isn't using KubernetesExecutor though, right? (Sorry, maybe I should have made that more prominent...)

**Comment by ashb** [comment] 2020-12-04 16:46
Oh, sorry! Right I'll try that.

**Comment by jedcunningham** [comment] 2021-02-03 01:11
@ashb, finally got back to this... I noticed that KubeExecutors end method isn't being called. I naively tried this:

```
--- a/airflow/jobs/scheduler_job.py
+++ b/airflow/jobs/scheduler_job.py
@@ -1286,13 +1286,12 @@ class SchedulerJob(BaseJob):  # pylint: disable=too-many-instance-attributes
                 )
                 models.DAG.deactivate_stale_dags(execute_start_time)
 
-            self.executor.end()
-
             settings.Session.remove()  # type: ignore
         except Exception:  # pylint: disable=broad-except
             self.log.exception("Exception when executing SchedulerJob._run_scheduler_loop")
         finally:
             self.processor_agent.end()
+            self.executor.end()
             self.log.info("Exited execute loop")
 
     @staticmethod
 ```

This allowed it to exit, though I'm sure there are some scenarios where this may be lacking 🤠 Tests pass though 🤷‍♂️

**Comment by jedcunningham** [comment] 2021-02-04 00:34
LocalExecutor behaves differently with that change as it gets stuck on `self.queue.join()`:
https://github.com/apache/airflow/blob/master/airflow/executors/local_executor.py#L338

So I guess is waiting for the running tasks to finish the desired behavior or not?

**Comment by ashb** [comment] 2021-02-04 15:48
> So I guess is waiting for the running tasks to finish the desired behavior or not?

No, probably not -- we probably want to kill them.

Or if we want to be advanced. the first ^c lets them finish, but a second ^c kills them and exits sooner. (THis is what Celery does for instance.)

**Comment by dimberman** [comment] 2021-02-04 18:04
@jedcunningham would you be able to make PR for the fix you tried? I'm glad to help get you set up with our CI env and get it merged :)

**Comment by jedcunningham** [comment] 2021-02-04 22:53
@dimberman, draft PR opened with what I have so far. At least lacking some documentation on the changed behavior.

@ashb, conveniently the "advanced" behavior is how it functions, though we probably could (should?) handle it gracefully instead of being uncaught like it is now. It's the same as the existing behavior just behind a second signal now.

**Comment by dimberman** [comment] 2021-02-05 19:23
@jedcunningham looks good to me! Please rebase on master to get tests running and then we can merge.

**Comment by dimberman** [comment] 2021-03-30 15:59
Hey @jedcunningham is this one close to done?

**Comment by jedcunningham** [comment] 2021-04-06 21:56
@dimberman, got the tests green (finally!).

**Closed as completed** 2021-04-11 11:56 UTC
Labels: kind:bug, priority:medium, provider:cncf-kubernetes
