### ISSUE TITLE
Add google-cloud-run python client to GCP requirements

### ISSUE THREAD

**Issue by VinceLegendre** [apache/airflow#29643] opened 2023-02-20 17:53 UTC
### Description

Implementing CRUD operations for Google Cloud Run Jobs would be much easier if we were able to use the official python client.
As of today (Feb 20th 2023), google-cloud-run library cannot be installed as it breaks dependencies.

This subject was mentioned in a PR aiming at executing existing Cloud Run Jobs : https://github.com/apache/airflow/pull/28525

Useful links:
- https://cloud.google.com/python/docs/reference/run/latest
- https://pypi.org/project/google-cloud-run/

### Use case/motivation

Implement CRUD and execution operations for Cloud Run Jobs

### Related issues

https://github.com/apache/airflow/issues/24730

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2023-02-20 22:59
Feel free to attempt it

**Comment by r-richmond** [comment] 2023-02-22 16:40
>As of today (Feb 20th 2023), google-cloud-run library cannot be installed as it breaks dependencies.

May be worth trying again as https://github.com/apache/airflow/pull/29644 was merged which removed the protobuf limit.

**Comment by VinceLegendre** [comment] 2023-04-07 12:33
While this was discussed in https://github.com/apache/airflow/pull/28525, some guidance on how to tackle this issue would be much appreciated :slightly_smiling_face: 

@r-richmond I tried to install the Python client within my local environment, but ended up with incompatibility errors.

**Comment by potiuk** [comment] 2023-04-19 01:01
This should be done after (or even during  #30067). This should unblock depdendencies.

**Comment by eladkal** [comment] 2023-08-19 10:25
duplicate of https://github.com/apache/airflow/issues/24730

**Closed as not planned by eladkal** 2023-08-19 10:25 UTC
Labels: provider:google, area:providers, kind:feature, good first issue, duplicate
