### ISSUE TITLE
when default_timezone is changed to non utc, backfill/dag test is not working

### ISSUE THREAD

**Issue by Qiuzhuang** [apache/airflow#16552] opened 2021-06-21 06:16 UTC
When I configure my default_timezone as Asia/Shanghai and kick off backfill command,  it throws exceptions: 

    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/dagrun.py", line 181, in refresh_from_db
    DR.run_id == self.run_id,
  File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3500, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

Changing back to default timezone works again.

**Comment by eladkal** [comment] 2021-07-04 08:31
can you please add reproduce example? What airflow version are you using?

**Comment by Qiuzhuang** [comment] 2021-07-04 08:52
Hi Eladkal, both versions 2.0.1 and newest 2.1 have this issue. Here is the related issue: https://github.com/apache/airflow/issues/14249#issuecomment-866756616.

To proproduce issue, simply change airflow.cfg and chage default_timezone = utc to default_timezone = Asia/Shanghai, then run backfill command and you would see the error.  Then switch this timezone to default utc, backfill should be working again.

Thanks!

**Comment by eladkal** [comment] 2021-07-04 09:16
So it's a duplicate of https://github.com/apache/airflow/issues/14249 isn't it?

**Comment by Qiuzhuang** [comment] 2021-07-04 10:11
> So it's a duplicate of #14249 isn't it?

Yes, I think so.

**Comment by eladkal** [comment] 2021-07-04 10:30
So closing this one. lets have all relevant into in https://github.com/apache/airflow/issues/14249

**Closed as completed by eladkal** 2021-07-04 10:30 UTC
Labels: kind:bug, duplicate, pending-response
