### ISSUE TITLE
Airflow Scheduler Crashing 2.4.2

### ISSUE THREAD

**Issue by lihan** [apache/airflow#27259] opened 2022-10-25 12:03 UTC
### Apache Airflow version

2.3.2 AND 2.4.2

### What happened

* Was running on version 2.3.2, out of sudden, scheduler keeps crashing and restarting. Upgrading to 2.4.2 does not resolve the issue.
* It appears that one particular pipeline cannot updated to be successful (after all tasks succeeded)

## Symptom 1

This is when trying to mark the pipeline success (Either manually or by the Airflow Scheduler). The traceback log appears in both the webserver as well as the scheduler. Marking the dag failure does not cause error.
At this time, access

 the dag detail view of this dag works. (See attached video as well)

https://user-images.githubusercontent.com/655051/197767297-f75be8e1-1fab-49ce-be0d-2f4aec793cdf.mov

![image](https://user-images.githubusercontent.com/655051/197766815-1f921ca1-39bd-4bfa-8119-cc53c4fb33a1.png)

## Symptom 2

* Upgraded to version 2.4.2
* Trying to recover the issue with `airflow dags reserialize` (on version 2.4.2), the command succeeded but did not resolve the issue.
* The error shows up when access the detail view of the dag. Below query returns 2 records.
```
select *
from dag
where dag_id = 'my_problem_dag';

The result of this query is

"dag_id","is_paused","is_subdag","is_active","last_parsed_time","last_pickled","last_expired","scheduler_lock","pickle_id","fileloc","owners","description","default_view","schedule_interval","root_dag_id","next_dagrun","next_dagrun_create_after","max_active_tasks","has_task_concurrency_limits","max_active_runs","next_dagrun_data_interval_start","next_dagrun_data_interval_end","has_import_errors","timetable_description"
"payment_premium_bdr_weekly_v1","false","false","true","2022-10-25 10:37:24.499861 +00:00",,,,,"/opt/airflow/dags/reports_gen/reporting_parser.py","airflow",,"grid","""0 6 * * 1""",,"2022-10-17 06:00:00.000000 +00:00","2022-10-24 06:00:00.000000 +00:00","5","false","5","2022-10-17 06:00:00.000000 +00:00","2022-10-24 06:00:00.000000 +00:00","false","At 06:00, only on Monday"
"payment_premium_bdr_weekly_v1","false","false","true","2022-10-25 10:36:11.583820 +00:00",,,,,"/opt/airflow/dags/reports_gen/reporting_parser.py","airflow",,"grid","""0 6 * * 1""",,"2022-10-24 06:00:00.000000 +00:00","2022-10-31 06:00:00.000000 +00:00","5","false","5","2022-10-24 06:00:00.000000 +00:00","2022-10-31 06:00:00.000000 +00:00","false","At 06:00, only on Monday"

```

```
File "/home/airflow/.local/lib/python3.8/site-packages/airflow/www/templates/airflow/grid.html", line 22, in top-level template code
    {% from 'appbuilder/loading_dots.html' import loading_dots %}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/www/templates/airflow/dag.html", line 30, in top-level template code
    {% set dag_is_paused = dag.get_is_paused() %}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 1126, in get_is_paused
    return session.query(DagModel.is_paused).filter(DagModel.dag_id == self.dag_id).scalar()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2879, in scalar
    ret = self.one()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2856, in one
    return self._iter().one()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1190, in one
    return self._only_one_row(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 613, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when exactly one was required
```

## Symptom 3

Most importantly, the scheduler loop exited, and crashes very often due to that the scheduler trying to update dag run result, but no row was affected.

### What you think should happen instead

* We were running 2.3.2 for a while and had no problem.
* The problematic pipeline was not modified for the last six months

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

Not related to this, but here is the list

```apache-airflow-providers-amazon==5.0.0
apache-airflow-providers-cncf-kubernetes==4.3.0
apache-airflow-providers-common-sql==1.1.0
apache-airflow-providers-docker==3.1.0
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-google==8.3.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-mysql==3.2.0
apache-airflow-providers-opsgenie==4.0.0
apache-airflow-providers-postgres==5.2.0
apache-airflow-providers-redis==3.0.0
apache-airflow-providers-sftp==4.0.0
apache-airflow-providers-slack==5.1.0
apache-airflow-providers-sqlite==3.2.0
apache-airflow-providers-ssh==3.1.0
```

### Deployment

Other Docker-based deployment

### Deployment details

Were using official Docker image on GKE

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment] 2022-10-25 13:17
Can you share the DAG? It seems somehow you are having duplicate dag_id

**Comment by lihan** [comment] 2022-10-25 19:04
@ephraimbuddy The dag that caused duplication is no special to other dags, just a dag with a few PythonOperators in it.

**Comment by lihan** [comment] 2022-10-31 23:00
@ephraimbuddy 

* Doing `airflow dags list` would cause error that multiple rows returned for the single dag. 
* ```select dag_id, count(*)
from dag
group by 1
having count(*) > 1;``` This also returns some dag_ids have multiple rows which violates the DB constraint, as the dag_id has the unique index on it.

**Comment by tanvn** [comment] 2022-11-02 05:29
@lihan 
Hi, may I know which kind of database are you using (and on which this issue happens) ?
I tried to reproduce this bug by executing an INSERT sql into MySQL database but since in `dag` table, `dag_id` is the primary key so it threw an error.
If you know other ways to reproduce this issue, please share it, I would greatly appreciate it. 🙇 
(I checked https://github.com/apache/airflow/issues/27300 as well but it seems the cause is also  because of duplicated `dag_id` in `dag` table).

**Comment by lihan** [comment] 2022-11-02 10:23
@tanvn 
My Airflow was deployed on Google Cloud CloudSQL (Postgres 13)

* My Postgres starts emitting a lot more error messages on primary key duplicate after upgrade to 2.3.3 (See attached screenshots)
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/655051/199463273-0a796e83-edd3-4853-b31a-dd457bcfa9fb.png">

* What I did was to remove the duplicates in the `dag` table manually, and rebuilt index on dags table

* After doing the re-index, the issue is gone, no more error messages from the Postgres as well

**Comment by tanvn** [comment] 2022-11-02 10:56
@lihan 
Thank you for your information!
> My Postgres starts emitting a lot more error messages on primary key duplicate after upgrade to 2.3.3 

May I know from which version did you update to 2.3.3 ? was it 2.3.2 ?

I am using Airflow 2.1.4 with MySQL 8 and I have tested upgrading to 2.4.2 and confirmed that the primary key constraint is available on both database schema for Airflow 2.1.4 and 2.4.2 so technically I am unable to reproduce this bug unless I drop the constraint manually.

I think this means there was a time when the constraint was removed from `dag` table and it made the insertion of records with duplicate `dag_id` become possible 🤔

**Comment by lihan** [comment] 2022-11-04 21:28
@tanvn 

It was 2.3.2 before the upgrade.

**Comment by lihan** [comment] 2022-11-06 10:34
@tanvn 

I received an email from Google Cloud SQL which they confirmed that one recent upgrade (starting 21 Oct 2022) caused corrupted index, the timing matches my issue, so I highly suspect the duplicate was caused by this incident.

**Comment by potiuk** [comment] 2022-11-06 13:19
Ah. that would explain it then. closing.

**Closed as completed by potiuk** 2022-11-06 13:19 UTC
Labels: kind:bug, area:core

**Comment by tanvn** [comment] 2022-11-07 01:54
@lihan
Thank you so much for the information!
