### ISSUE TITLE
Can't locate revision identified by 'c804e5c76e3e'

### ISSUE THREAD

**Issue by MuslimBeibytuly** [apache/airflow#32481] opened 2023-07-10 07:36 UTC
### Apache Airflow version

2.6.2

### What happened

error, have no idea why

### How to reproduce

airflow db upgrade
airflow db check-migrations --migration-wait-timeout 60

### Operating System

python:3.10.10-slim - docker image

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==8.1.0
apache-airflow-providers-celery==3.2.0
apache-airflow-providers-cncf-kubernetes==7.0.0
apache-airflow-providers-common-sql==1.5.1
apache-airflow-providers-ftp==3.4.1
apache-airflow-providers-http==4.4.1
apache-airflow-providers-imap==3.2.1
apache-airflow-providers-postgres==5.5.0
apache-airflow-providers-sqlite==3.4.1
```

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

helm in k8s

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kelechi2020** [comment] 2023-07-10 10:45
I was not able to reproduce same error using the specified apache and python versions.
```
docker run -iqt --rm  apache/airflow:slim-2.6.2-python3.10 bash

airflow@d8391d64a915:/opt/airflow$ airflow db upgrade
DB: sqlite:////opt/airflow/airflow.db
Performing upgrade with database sqlite:////opt/airflow/airflow.db
[2023-07-10T10:43:13.952+0000] {migration.py:213} INFO - Context impl SQLiteImpl.
[2023-07-10T10:43:13.952+0000] {migration.py:216} INFO - Will assume non-transactional DDL.
[2023-07-10T10:43:13.953+0000] {migration.py:213} INFO - Context impl SQLiteImpl.
[2023-07-10T10:43:13.953+0000] {migration.py:216} INFO - Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> c804e5c76e3e
Upgrades done
airflow@d8391d64a915:/opt/airflow$ airflow db check-migrations --migration-wait-timeout 60
airflow@d8391d64a915:/opt/airflow$ 
```

**Comment by potiuk** [comment] 2023-07-10 16:46
Likely you downgraded your airflow accidentally when installed other packages. 

See the note in https://airflow.apache.org/docs/docker-stack/build.html#adding-new-pypi-packages-individually and examples how to avoid it (always add `apache-airflow==<YOUR_AIRFLOW_VERSION` when you are installing other packages, otherwise `pip` might choose to downgrade your airflow. Just follow the practices explained there.

Closing as invalid unless there are more insights.

**Closed as completed by potiuk** 2023-07-10 16:46 UTC
Labels: kind:bug, invalid, area:core, needs-triage
