### ISSUE TITLE
Airflow fetch log from wrong host. "Failed to fetch log file from worker. 404 NOT FOUND."

### ISSUE THREAD

**Issue by ORuteMa** [apache/airflow#28718] opened 2023-01-04 07:12 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow Version：2.2.0
![image](https://user-images.githubusercontent.com/30034544/210500988-cd5aa793-3bfb-4208-8d77-2f9b88b5b608.png)
In my Airflow deployment, I found Airflow can't fetch attempts 4's log, it was trying to fetch the log from core-2, but the task instance is actually running on core-3.
![image](https://user-images.githubusercontent.com/30034544/210501382-43723377-a61e-49eb-8521-3a284c56a0ec.png)
Is this a known issue? And it has already been fix? If so, please tell me which version should I use to prevent this issue.

I use Celery Executor.

### What you think should happen instead

Airflow fetch log file from core-3.

### Operating System

Debian GNU/Linux 10 (buster)

### Deployment

Virtualenv installation

### Deployment details

I have 4 ec2 nodes, and I assign role for them. 1 master, 3 cores. Webserver deploy on master-1, scheduler / celery-worker deploy on every node.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment] 2023-01-04 07:20
What is your deployment? There is too little information to infer anything.

**Comment by ORuteMa** [comment] 2023-01-04 07:28
I have 4 ec2 nodes,  and I assign role for them. 1 master, 3 cores. Webserver deploy on master-1, scheduler / celery-worker deploy on every node.

**Comment by ORuteMa** [comment] 2023-01-04 07:42
@uranusjr I have already updated my deployment, is it detailed enough? 🙏

**Comment by potiuk** [comment] 2023-01-04 11:55
Can you please migrate to latest version @ORuteMa ? You are using a very old version of Airflow that was followed by~ 15 releases of Airflow with multiple hundreds of bug fixes.

I vaguely recall (but this is hard to be 100% sure) similar issues have been solved already. Not only Airflow [2.5.0](https://airflow.apache.org/docs/apache-airflow/2.5.0/release_notes.html) has literally multiple hundreds of fixes implemented comparing to 2.2.0 but also even if you try to run 2.2.* line only - 2.2.0 has follow up 2.2.* that ONLY contain bugfixes and nothing else, so you should - at the very least - upgrade to 2.2.5 - running 2.2.0 makes literally no sense knowing that there were hundreds of bugs fixed in 2.2.1-2.2.5 for that line.

The only way you will get a fix is to upgrade to 2.5 (we never release fixes to past lines of Airlfow - all the bugfixes are coming in latest version - the next (and only) bugfix version will be 2.5.1 - so you will have to upgrade anyway to 2.5.1 if a fix is needed. By upgrading to 2.5.0 you might find that the problem is gone in which case you save a lot of time for investigation - both for yourself and people who want to help you.

Also if you want to check if your problem is actually fixed before you upgrade - you can look at the release notes and possibly you will find related PRs solving it. But I strongly encourage you to just upgrade, that will save a lot of time for you.

Provisionally closing this one until @ORuteMa re-tests it in latest version. Please comment here if you observe similar behaviour there.

**Closed as completed by potiuk** 2023-01-04 11:55 UTC
Labels: kind:bug, area:core

**Comment by ORuteMa** [comment] 2023-01-04 12:13
@potiuk Thank you very much. We actually considered moving to the latest version, but this issue https://github.com/apache/airflow/issues/21225 might be a threat for our workload, we even dare not to upgrade to higher 2.2.x version.

**Comment by ORuteMa** [comment] 2023-01-04 12:14
For now, we can check the log from the right node. It is just a little inconvenient for us. It is better than tasks stuck in queued.

**Comment by potiuk** [comment] 2023-01-04 12:59
This issue is not something that is a general problem. It happens for some users and it is not even sure it is only appearing in that version.

Did you test if it is a problem for you ? I presume you have a staging system (this is always a good idea) that you vmcan test migration on.


There are hundreds other issues which (if you are afraid of them) might prevent you from migrating ever.

What makes you so much afraid of that particular issue?

**Comment by ORuteMa** [comment] 2023-01-04 15:20
Thank you, I will test my dag on the latest version.

**Comment by ORuteMa** [comment] 2023-03-14 08:10
@potiuk  I believe I have identified the root cause of this issue. When using the Celery executor, each task retry is assigned to a different host. Additionally, during each run of the task, it refreshes itself from the database using 'taskinstance.refresh_from_db'. It then changes the hostname field and persists the change. As a result, we lose track of which host was used in the previous retry. Therefore, I suggest that we add a new table to record the information of different task runs. I am willing to submit a PR.
