### ISSUE TITLE
Dag Import error in UI with unreal message Airflow 2.02

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#15649] opened 2021-05-04 08:52 UTC
I have just updated from Airflow 1.10.14 to Airflow 2.0.2 and I am getting an error of this kind in a lot of dags. I have several python scripts in python files in my dags subfolders. Here is the error I get in the UI:

![Captura de pantalla 2021-05-04 a las 10 49 49](https://user-images.githubusercontent.com/11339132/116980382-74eb1e80-acc6-11eb-87cd-d1060736094c.png)

However, the code of the DAG is the following:
```
from utilities.files import get_arguments_python_script
dag_route, dag_name, ts = get_arguments_python_script()
dag_globals = Variable.get('variables_secret', deserialize_json=True)
```

I am using airflow with docker-compose (official image) and I have already restarted it several times and the error persists. Moreover, if I click on the DAG, I can successfully enter it and even run the script. Also, in the logs of the containers of the webserver and the scheduler, there are no error logs

**Comment by uranusjr** [comment] 2021-05-04 09:23
Can you upload the DAG file (verbatim, not copy-and-pasted) somewhere? I’m guessing the file contains some weird characters and cannot be correctly parsed.

**Comment by codenamestif** [comment] 2021-05-05 12:43
I confirm the issue. It looks like there is some kind of partial import. Especially when there are 2 files and one file has import on another one.

**Comment by codenamestif** [comment] 2021-05-05 12:52
@uranusjr it's not about parsing the file for sure. I have python file with some constants. I've got the error after adding more constants there. The old ones were resolved with no problems, but new ones were not.

**Comment by codenamestif** [comment] 2021-05-07 08:36
Also, looks like the issue was introduced in 2.0.2. Because migration back on 2.0.1 seems to solve the issue.

**Comment by potiuk** [comment] 2021-05-07 08:53
@codenamestif can you paste the fragment of the `s3_adyen.py` file  that is reported as wrong?

Looking at the error description and the piece of code printed, it almost looks like the end of line after the python_script() was somehow stripped out.

**Comment by potiuk** [comment] 2021-05-07 08:57
Maybe this is the usual Windows/Linux EOL problem CR/LF?

**Comment by JavierLopezT** [comment] 2021-05-07 09:16
> Also, looks like the issue was introduced in 2.0.2. Because migration back on 2.0.1 seems to solve the issue.

I can confirm that with 2.0.1 I did not have the issue with the exact same file. 

Also, I am getting other errors. For instance, I have a query in a python file and there is an error on the UI saying that:
`"table relation does not exist"`
And I don't think that there should be any SQL checking before executing a dag. 

Furthermore, I had to change the way I passed parameters to my python files because with `sys.argv[1]` I obtained in the UI errors of kind IndexError (that I didn't have way back in 1.10.14: https://apache-airflow.slack.com/archives/C0146STM600/p1617278017105300

And I had an ImportError as well: https://apache-airflow.slack.com/archives/C0146STM600/p1617788878119200

I think that there is definitely something not working as intended in the new scheduler. I am using Airflow with the official Docker image, by the way.

**Comment by potiuk** [comment] 2021-05-07 09:28
> Also, I am getting other errors. For instance, I have a query in a python file and there is an error on the UI saying that:

I am afraid we will need to get more details and verbatim file to be able to investigate. Do you have a possibility of running again 2.0.1 -> 2.0.2 without disrupting  your current installation (for example by copying your database) and proividing some more details: verbatim file, more information about your deployment/database used etc.) + detailed list of stactraces/errors/log file errors you have.

It looks like you have some specific environment (are your files edited/stored on windows maybe)? 

Otherwise it is simply very difficult to reproduce.

**Comment by potiuk** [comment] 2021-05-07 09:31
Additional question: Are you sure you migrated the `DB` before running new version of Airflow ?

**Comment by JavierLopezT** [comment] 2021-05-07 09:36
> > Also, I am getting other errors. For instance, I have a query in a python file and there is an error on the UI saying that:
> 
> I am afraid we will need to get more details and verbatim file to be able to investigate. Do you have a possibility of running again 2.0.1 -> 2.0.2 without disrupting your current installation (for example by copying your database) and proividing some more details: verbatim file, more information about your deployment/database used etc.) + detailed list of stactraces/errors/log file errors you have.
> 
> It looks like you have some specific environment (are your files edited/stored on windows maybe)?
> 
> Otherwise it is simply very difficult to reproduce.

Thanks for your interest. My files are edited in Mac with Pycharm. I have just tested Airflow 2.0 versions with a local docker-compose in my mac, with Postgres and Local Executor, and the exact same files work with Airflow 1.10.14 perfectly. 

I did migrate the DB. I changed the version of Postgres in the docker-compose from 11.5 to 13 and I had to do on my Mac 

```
brew upgrade postgresql
brew postgresql-upgrade-database
```

After that, I entered the container and run the upgrade db, getting a successful message:
`docker exec -it airflow_scheduler_1 bash --> airflow db upgrade`

I had done the db upgrade twice, but in 2.0.0 and 2.0.2 I have not been free of errors, with the exact same files all the time. I will try to upload verbatim files. Thanks again

**Comment by JavierLopezT** [comment] 2021-05-07 10:18
You can find the files here @potiuk @uranusjr:

https://github.com/JavierLopezT/airflow_2.02_error

**Comment by uranusjr** [comment] 2021-05-13 09:10
I tried the files in a fresh Airflow installation and could not reproduce the error. So (assuming the files are verbatim, which I’m unsure of since Git performs some text processing by default), this is likely an issue with your local setup (probably database?) and not a bug in Airflow itself.

**Comment by JavierLopezT** [comment] 2021-05-26 15:45
I have upgraded the Dockerfile to 2.1.0, made `docker system prune -af` and `airflow db reset` as well as `airflow db init` several times. I don't have anymore the error in the first post, but I do have one very similar:
![Captura de pantalla 2021-05-26 a las 17 38 34](https://user-images.githubusercontent.com/11339132/119690595-1d198080-be4a-11eb-849b-4c24b35204a9.png)
And the DAG works perfectly fine:
![Uploading Captura de pantalla 2021-05-26 a las 17.38.24.png…]()

**Comment by JavierLopezT** [comment] 2021-05-27 10:26
Another error
![Captura de pantalla 2021-05-27 a las 12 24 04](https://user-images.githubusercontent.com/11339132/119810641-818a1d80-bee6-11eb-951d-a8570d9aa05b.png)

The code is:
![Captura de pantalla 2021-05-27 a las 12 25 34](https://user-images.githubusercontent.com/11339132/119810771-a67e9080-bee6-11eb-8fc0-5aa734dad285.png)

I don't think this error should happen. For me, it seems that the scheduler is trying to execute somehow the query before actually running it, but I don't think this import error is useful at all and I don't see how this could be related to my local deployment. 

Any ideas? Thanks

**Comment by potiuk** [comment] 2021-05-27 11:15
Are you running the "get_pandas_df" at the top-level of your DAG file? if so, then yes - scheduler will try to execute it while parsing the DAG. DAG is "imported" and "executed" by the scheduler regularly. All the processing should happen in the operator's "execute()'' methods (either operators you use or the custom operators you write).

**Comment by JavierLopezT** [comment] 2021-05-27 11:27
> Are you running the "get_pandas_df" at the top-level of your DAG file? if so, then yes - scheduler will try to execute it while parsing the DAG. Python DAG file is "imported" and "executed" by the scheduler regularly. All the processing should happen in the operator's "execute()'' methods (either operators you use or the custom operators you write).

No, nothing is in the DAG file but the definition of the operators, as the best practices state. The `get_pandas_df` is in a python file that is executed by a custom BashOperator.

**Comment by ashb** [comment] 2021-05-27 11:41
Is the code where you have `redshift =` in the `py_get_query.py` file? If so the scheduler is still going to parse all python files to look for dags, and parsing = running any and all code at the top level of the file.

You can either add the non-dag python files to the .airflowignore file https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html?highlight=airflowignore#loading-dags

Or better yet would be to not place non-DAG files in the dags folder and place them somewhere else in the Python include path.

**Closed as completed by ashb** 2021-05-27 11:41 UTC
Labels: kind:bug, area:core
