### ISSUE TITLE
Each log line coming twice in task logs on airflow 2.4.2

### ISSUE THREAD

**Issue by bharatk-meesho** [apache/airflow#27852] opened 2022-11-23 08:25 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I am running airflow 2.4.2 in EKS 1.22 with minor tweaks to official helm chart. I am observing in UI, in task logs each log line is coming twice. Attaching a screen-shot below of the issue. As visible here all log lines are repeated twice in task log file. 

<img width="1736" alt="Screenshot 2022-11-23 at 1 51 39 PM" src="https://user-images.githubusercontent.com/95409716/203499788-5e6dd417-1a25-46e0-aa5a-73c0d56bdc3b.png">

### What you think should happen instead

Each log line should be coming once in task logs, this is important as task logs will take twice the space as required.

### How to reproduce

Should be able to reproduce by running any dag on airflow 2.4.2 with official helm chart on EKS v1.22 and observing task logs.

### Operating System

PRETTY_NAME=“Debian GNU/Linux 11 (bullseye)” NAME=“Debian GNU/Linux” VERSION_ID=“11” VERSION=“11 (bullseye)” VERSION_CODENAME=bullseye ID=debian

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2022-11-23 09:41
Duplicate of #27345 fixed in 2.4.3. Please upgrade.

**Closed as completed by potiuk** 2022-11-23 09:41 UTC
Labels: kind:bug, duplicate, area:core
