### ISSUE TITLE
Eventlet with CeleryExecutor not working in Airflow 1.10.9 version

### ISSUE THREAD

**Issue by sriramachegondi** [apache/airflow#8288] opened 2020-04-14 03:04 UTC
**Apache Airflow version**: 1.10.9

**Environment**: 

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): ubuntu 18.04
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: Eventlet with CeleryExecutor not working in Airflow 1.10.9 version
[log.txt](https://github.com/apache/airflow/files/4472893/log.txt)
I notice when I tried switching celery pool option to eventlet the worker doesn’t seem to be picking up tasks.

Attached the snippet of logs.

**What you expected to happen**:

**How to reproduce it**: Start the airflow celery workers with Eventlet

**Anything else we need to know**: Attached the logs

**Comment by khyurri** [comment] 2020-04-14 08:18
Hi, sriramachegondi

I'll try to reproduce this bug

**Comment by khyurri** [comment] 2020-04-14 14:19
Can't reproduce at `1.10.10`. 

airflow.cfg (non default values)

```
sql_alchemy_conn = mysql://airflow:airflow@127.0.0.1:3306/airflow
pool = eventlet
executor = CeleryExecutor
broker_url = redis://redis:6379/1
result_backend = db+mysql://airflow:airflow@127.0.0.1:3306/airflow
```

Dag: `dags/test_dag.py`

schedule_interval='*/2 * * * *'

---

1. Are you running both `airflow scheduler` and `airflow worker`? 
2. Can you send your `airflow.cfg`?

**Comment by turbaszek** [comment] 2020-04-16 06:06
Duplicate of https://github.com/apache/airflow/issues/8023

**Closed as completed by turbaszek** 2020-04-16 06:06 UTC
Labels: kind:bug
