### ISSUE TITLE
Couldn't open Calendar tab of DAG after triggering DAG

### ISSUE THREAD

**Issue by akrava** [apache/airflow#29453] opened 2023-02-09 23:36 UTC
### Apache Airflow version

2.5.1

### What happened

After triggering any DAG and trying to open Calendar tab I see this:
![image](https://user-images.githubusercontent.com/13131083/217962405-d82f6058-0799-468b-84a7-b519685c626a.png)

Here is the logs:
```
[2023-02-09T23:19:27.482+0000] {app.py:1741} ERROR - Exception on /dags/dtap_dag_with_bash/calendar [GET]
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/.local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/www/auth.py", line 47, in decorated
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/www/decorators.py", line 166, in view_func
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/www/decorators.py", line 125, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/www/views.py", line 2756, in calendar
    if curr_info.logical_date <= prev_logical_date:
TypeError: can't compare offset-naive and offset-aware datetimes
```

### Operating System

Ubuntu 20.04.5

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by pierrejeambrun** [comment] 2023-02-13 19:28
I believe this is a duplicate of https://github.com/apache/airflow/issues/29227. Closing for now, feel free to reopen if the issue is different.

**Closed as completed by pierrejeambrun** 2023-02-13 19:28 UTC
Labels: kind:bug, area:webserver, good first issue, _eol_affected_version:2.5
