### ISSUE TITLE
UPDATE statement on table 'dag' expected to update 1 row(s); 0 were matched.

### ISSUE THREAD

**Issue by tooptoop4** [apache/airflow#11714] opened 2020-10-21 12:06 UTC
airflow 1.10.12, mysql 5.7 metastore, rbac, no serialized dags, intermittent error found twice in the logs:

[2020-10-15 12:28:14,502] {scheduler_job.py:167} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/ec2-user/venv/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 159, in _run_file_processor
    pickle_dags)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 1609, in process_file
    dag.sync_to_db()
  File "/home/ec2-user/venv/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/airflow/models/dag.py", line 1543, in sync_to_db
    session.commit()
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/ec2-user/venv/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1028, in _emit_update_statements
    % (table.description, len(records), rows)
sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'dag' expected to update 1 row(s); 0 were matched.

**Comment by vikramkoka** [comment] 2020-11-17 17:41
Is this is a duplicate of 11715?

**Comment by ashb** [comment] 2021-02-25 11:34
Closing due to no response. We can reopen this if we get more details

**Closed as completed by ashb** 2021-02-25 11:34 UTC
Labels: kind:bug, pending-response, area:core
