### ISSUE TITLE
`airflow db upgrade` Failed to write serialized DAG

### ISSUE THREAD

**Issue by troyharvey** [apache/airflow#26834] opened 2022-10-03 02:49 UTC
### Apache Airflow version

2.4.1

### What happened

Running `airflow db upgrade` on an Airflow installation with 100 DAGs fails with this error:

```
ERROR [airflow.models.dagbag.DagBag] Failed to write serialized DAG: /usr/local/airflow/dags/REDACTED.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 615, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 146, in write_dag
    session.query(literal(True))
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(REDACTED) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, data_compressed, last_updated, dag_hash, ...
```

### What you think should happen instead

`airflow db upgrade` should successfully reserialize DAGs at the end of the upgrade just like the `airflow dags reserialize` command.

### How to reproduce

1. Upgrade to `airflow 2.4.1` on an existing codebase
2. Run `airflow db upgrade`

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==5.1.0
apache-airflow-providers-celery==3.0.0
apache-airflow-providers-cncf-kubernetes==4.3.0
apache-airflow-providers-common-sql==1.2.0
apache-airflow-providers-datadog==3.0.0
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-postgres==5.2.1
apache-airflow-providers-redis==3.0.0
apache-airflow-providers-sendgrid==3.0.0
apache-airflow-providers-sftp==4.0.0
apache-airflow-providers-slack==5.1.0
apache-airflow-providers-sqlite==3.2.1
apache-airflow-providers-ssh==3.1.0
```

### Deployment

Other Docker-based deployment

### Deployment details

k8s deployment

### Anything else

Fails consistently in these two scenarios:

1. Run db upgrade only:

        airflow db upgrade

1. Run along with reserialize

        airflow dags reserialize --clear-only
        airflow db upgrade

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by troyharvey** [comment] 2022-10-03 03:08
@uranusjr @potiuk @kaxil 👋  Tagging you here because you were involved in this PR: https://github.com/apache/airflow/pull/24518

**Comment by DMilmont** [comment] 2022-10-05 19:15
We are also experiencing this issue on Airflow 2.4.1. We have ~900 DAGs and running airflow on the official Helm chart. Because the helm chart runs the migration job on each deploy, and the job takes upwards of 20 minutes, this has stopped us from being able to use the latest release.

**Comment by troyharvey** [comment] 2022-10-05 20:36
Thanks @DMilmont. We've "disabled" our k8s upgrade job as a temporary workaround using this command:

```
        # Running airflow db upgrade on every deployment is slow because it reserializes all DAGs.
        # Use the dry run flag `--show-sql-only` to see if there are any available migrations to run.
        # When there are no migrations to run the output says "No migrations to apply."
        # When there are migrations to run the output says "Running upgrade."
        command:
          - sh
          - -c
          - >-
            airflow db upgrade --show-sql-only |
            grep --quiet "Running upgrade" &&
            airflow db upgrade
            || true
```

**Comment by DMilmont** [comment] 2022-10-05 21:24
Thanks for sharing @troyharvey I think we are going to do the same.

**Comment by uranusjr** [comment] 2022-10-06 07:53
Instead of associating the issue to reserialising, IMO it is not a good idea in the first place to run `airflow db upgrade` from multiple instances against the same database. The workaround above is OK-ish since it practically avoids running the command repeatedly, although may still be suspective to race conditions in edge cases (depending on how you set things up).

As for the SQL error, I think it should enough to simply add some sort of `ON CONFLICT` clause to make the reserialisation step just skip duplicated rows. PRs welcomed.

**Comment by uranusjr** [comment] 2022-10-06 07:55
Also it may be a good idea for us to add something like `airflow db up-to-date-check` (pending command name bikeshedding) that checks whether the database needs upgrading. This would be much more reliable than grepping stdout.

**Comment by potiuk** [comment] 2022-10-06 16:44
It's already there `airflow db check-migrations`

**Comment by uranusjr** [comment] 2022-10-06 17:11
Ah so `airflow db check-migrations -t 0 || airflow db upgrade || true` would work then.

**Comment by potiuk** [comment] 2022-10-06 17:12
(I think even -t 0 is not needed)

**Comment by stephenonethree** [comment] 2022-10-18 17:13
I got this on Airflow 2.4.0. At first I ran `airflow db upgrade` to finish my install (just on my laptop since this is a local installation) and it was fine, but I noticed some warnings unrelated to this topic that came up when parsing my DAGs, stuff related to roles not existing etc. So I fixed my issue with roles and ran `airflow dags reserialize` again to check if those other warnings were gone, and that's when I started seeing this message.

**Comment by HadarSha** [comment] 2022-11-06 09:36
We have also been experiencing it on Airflow 2.4.0, is there any target version in which this is to be resolved?

**Comment by potiuk** [comment] 2022-11-06 13:17
@HadarSha  - could you explain how you get to the issue and add more logs and explain the circumstances when it happened (what DAGS you had etc.)? 

Without that I think it will never be solved, because I think it lacks a clear reproduction steps - there is some reason why it failed but without the input of users who experienced it it's not possible to fix.

Can you please help us to understand what the problem is and provide more evidences? That is a way how fixing it can be sped up.

**Comment by HadarSha** [comment] 2022-11-06 13:36
@potiuk Unfortunately we have since rolled back to 2.3.4, particularly due to this very issue, so actual logs may be hard to come by.

I will share our deployment and steps that led to the issue, however:

* We are using Airflow on Kubernetes (AWS EKS) with Airflow's Official Helm Chart
* 4 Airflow Schedulers running at all times (for HA and performance reasons - maybe it's an issue with the `airflow db upgrade` command in this context?)
* Metadata DB is PostgreSQL on AWS RDS (i.e. not part of K8s cluster), accessed via a `PgBouncer` pod in the cluster (comes as part of the helm chart I believe)
* The Executor is CeleryKubernetesExecutor, with RabbitMQ as the broker/backend
* Some workers are always up (Celery) and some are autoscaled with HPA
* We have some ~200 DAGs currently, delivered to the pods via `git-sync` containers on each of the Airflow services

The steps we performed were as follows:

1. Verify no DAGs are running
2. Update Airflow package from 2.3.4 to 2.4.0 (we also updated provider packages, I believe) from one of the pods (e.g. Airflow Webserver), using pip
3. Run `airflow db upgrade` so as to upgrade the metadata DB tables, schemas etc. before actually updating the rest of the Airflow components (schedulers, workers, etc.) to 2.4.0
4. Command would run for about a minute and eventually fail with the exact same error as the issue opener attached.
5. I think that `airflow dags reserialize` would give a similar error, which forced us to downgrade back to 2.3.4 and ditch the 2.4.0 version for the time being.

I apologize for not being able to provide more detailed logs/explanations, perhaps if we tried again at some point (maybe with the current version or thereabout) we could reproduce it - though in its essence it's very similar, if not identical, to what the author of this issue had already attached.

**Comment by potiuk** [comment] 2022-11-06 13:53
Thanks @HadarSha.

> I apologize for not being able to provide more detailed logs/explanations, perhaps if we tried again at some point (maybe with the current version or thereabout) we could reproduce it - though in its essence it's very similar, if not identical, to what the author of this issue had already attached.

It would be great if you try with 2.4.2 - particularly https://github.com/apache/airflow/pull/27030 from 2.4.2 improved dag collection time and overhead and while unlikely to solve the problem. it will speed up the upgrade time.

 > Update Airflow package from 2.3.4 to 2.4.0 (we also updated provider packages, I believe) from one of the pods (e.g. Airflow Webserver), using pip
> Run airflow db upgrade so as to upgrade the metadata DB tables, schemas etc. before actually updating the rest of the Airflow components (schedulers, workers, etc.) to 2.4.0

Do I understand correctly that you did not shutdown the schedulers and they were running in parallell to the upgrade command? If so then THIS is the reason of your problem. You should never, ever run any component of airlfow while running `airflow db upgrade` - same as trying to run several `airflow db upgrade` commands. This WILL cause problems, this is also why we have `airflow db check-migrations` command in init containers for all our components in our Helm Chart.

The right sequence of doing migration is:

1) Stop all airflow components
2) Upgrade ALL airflow components
3) Run (one and only one instance of) `airflow db upgrade` 
4) Start all components


Step 3 can be achieved easily in fully-automated upgrade process where you would not have to do any manual sequence of operations. If you add `airflow db check-migrations` as init containers (or just command to run before the component starts). If you upgraded all components before, this command will wait until `airflow db upgrade` completes.

**Comment by DMilmont** [comment] 2022-11-07 21:12
Today we upgraded to airflow 2.4.2 - we did not notice this issue during the migration this time around. 

We are using the official helm chart, so the migration occurred on deploy via the migration job.
We run 900 + dags currently

When we upgraded to airflow 2.4.1 the migration took >20 minutes. 
After upgrading to airflow 2.4.2 the migration took < 2 minutes. 

If there are other data points needed I am happy to help provide some.

**Comment by potiuk** [comment] 2022-11-07 21:22
Cool. I will close it then - we might re-open if it happens for somoene else.

**Closed as completed by potiuk** 2022-11-07 21:22 UTC
Labels: kind:bug, good first issue, area:upgrade, _eol_affected_version:2.4

**Comment by vrychkov-repay** [comment] 2023-11-14 14:37
@potiuk, this issue returned in 2.7.3 scheduler, running from the official helm chart 1.11.0 with 2.7.3 image. Migration job (performing upgrade) was successful (no PendingRollbackError on insert to serialized_dag). We tried with 1 and 3 scheduler replicas.

**Comment by potiuk** [comment] 2023-11-17 00:01
Can you post more details ? Ideally in a new Issue descrining in detail your log and configuration and circumstances? I have hard time understanding your scenario and problem. Opening new issue will help to see it fresh (for someone who is going to take a look without someone trying to figure out which parts of the orignal issue to connect with which part of your description.
