### ISSUE TITLE
MWAA - / in users

### ISSUE THREAD

**Issue by bob-skowron** [apache/airflow#42262] opened 2024-09-16 20:52 UTC
Bringing this to a top level issue. As jaklan noted below, any thoughts on how we could manage users in MWAA given this limitation? I've also reached out to AWS to get their thoughts.

Thanks!

              Sorry for bumping the old issue, but maybe you have a quick answer for that - AWS [added support for REST API in MWAA](https://aws.amazon.com/blogs/big-data/introducing-amazon-mwaa-support-for-the-airflow-rest-api-and-web-server-auto-scaling/), but the problem is - usernames in MWAA start with `assumed-role/` prefix, so they contain slash.

Is there any way to use `/users` endpoints not to receive `The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.` error?

Neither `/users/assumed-role/foobar` nor `/users/assumed-role%2Ffoobar` seems to work.

_Originally posted by @jaklan in https://github.com/apache/airflow/issues/20063#issuecomment-2128914451_

**Comment by eladkal** [comment] 2024-09-18 07:14
The issue is not a bug in the open source but a problem in MWAA. I notified the MWAA team about your report but I suggest you will also contact the AWS support directly they might provide more information.

Closing as not open source bug.

**Closed as not planned by eladkal** 2024-09-18 07:14 UTC
Labels: provider:amazon, area:API

**Comment by eladkal** [comment] 2024-09-18 07:42
I see MWAA already has open issue for it in thier socker image
https://github.com/aws/amazon-mwaa-docker-images/issues/127
