### ISSUE TITLE
Sagemaker contrib module - should be independant

### ISSUE THREAD

**Issue by shlomiken** [apache/airflow#10007] opened 2020-07-26 11:54 UTC
Hi
we are heavy users of sagemaker through airflow , and one thing that bothers us and cause a lot of dependency issues in deployment is that one needs to install the sagemaker SDK in order to submit a training job to sagemaker.
as described here in details https://sagemaker.readthedocs.io/en/stable/workflows/airflow/using_workflow.html

although the operators comes from the airflow contrib package , some of the configuration comes from sagemaker SDK
for example `training_config` as described above.
please make sure this contrib package is independent. (currently it bring scypi, numpy and other good stuff with it)

**Comment by mik-laj** [comment] 2020-07-26 12:29
Hello,
During Airflow installation, the user selects which additional libraries they want to install.
https://airflow.readthedocs.io/en/latest/installation.html
If it does not install a module that requires numpy it will not be used.
For Airflow 1.10.111, `aws` extra requires `boto3~=1.10` only.

Can you provide more details to help us understand the problem?

**Comment by mik-laj** [comment] 2020-07-26 12:37
Oh. I think I understand. The Sagemaker SDK requires bumpy. 
https://github.com/aws/sagemaker-python-sdk/blob/master/setup.py#L38
So I think it is best to create a ticket in that project so that they don't use this dependency.

You can also isolate this library by installing it in a separate virtual environment.
https://airflow.readthedocs.io/en/1.10.11/_api/airflow/operators/python_operator/index.html?highlight=PythonVirtualenvOperator#airflow.operators.python_operator.PythonVirtualenvOperator

**Comment by shlomiken** [comment] 2020-07-26 14:12
> Oh. I think I understand. The Sagemaker SDK requires numpy.
> https://github.com/aws/sagemaker-python-sdk/blob/master/setup.py#L38
> So I think it is best to create a ticket in that project so that they don't use this dependency.
> 
> You can also isolate this library by installing it in a separate virtual environment.
> https://airflow.readthedocs.io/en/1.10.11/_api/airflow/operators/python_operator/index.html?highlight=PythonVirtualenvOperator#airflow.operators.python_operator.PythonVirtualenvOperator

The problem is NOT with sagemaker SDK and its dependencies. the problem is that several Sage maker operators (which are part of airflow codebase) require you to install sagemaker SDK. and by that expose you to libraries you don't need or conflict with your deployment.
it also make the package very big - where it should be very light. 
i thought this is the project that the contribution of sagemaker is being done - isn't it ?

**Comment by mik-laj** [comment] 2020-07-26 14:37
> i thought this is the project that the contribution of sagemaker is being done - isn't it ?

SageMaker contributors are not an active part of this community

I still think it will be difficult to fix this problem on the Airflow core. We only integrate a ready-made SDK and if the official SDK requires dependencies, this SDK should be improved to limit the number of needed dependencies. We can look for an alternative unofficial SDK, but the unofficial SDK may be the source of other problems e.g. missing features.

Besides, Airflow does not require a Sagemaker SDK and it doesn't use the Sagemaker SDK anywhere. You can also prepare the config file manually based on the boto3 documentation.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_hyper_parameter_tuning_job
or 
You can prepare the config in another environment and save it to a JSON file, and then load these config in the DAG file.
Here is an example of how you use this operators without Sagemaker SDK
https://github.com/apache/airflow/blob/master/tests/providers/amazon/aws/operators/test_sagemaker_tuning.py#L40-L115

**Comment by shlomiken** [comment] 2020-07-26 15:36
@mik-laj - thank you for the detailed answer, we will surely look into the option of creating the configuration ourselves.
i was under the impression that we must use sagemaker SDK objects - as described in their documentation.
thanks again .
this issue can be closed.
Shlomi

**Comment by mik-laj** [comment] 2020-07-26 18:10
@shlomiken If my solution works, maybe you would like to describe it in the tutorial? The documentation for this service is not complete and it is worth improving it so that other users do not make this mistake.
Here are guides for other AWS services.
https://airflow.readthedocs.io/en/latest/howto/operator/amazon/aws/index.html

**Comment by shlomiken** [comment] 2020-07-27 17:34
@mik-laj - well it would not take us a day to test :-) we need to refactor quite a bit ,
also i think on sagemaker part this is shortcoming ,as we loose all validations made on the configuration.
BUT - if we do happen to refactor this , i promise to write the doc.
thanks

**Comment by mik-laj** [comment] 2020-08-09 18:52
@shlomiken Is there any progress here?

**Comment by shlomiken** [comment] 2020-08-09 20:54
Hi @mik-laj , unfortunately we don't have the capacity now to refactor this. we decided to install sagemaker as it worked till now.
this means that the use case of working with packaged zip files which contain sagemaker is a problem - so we actually install it separately on target machines. (botocore also have a problem working in packaged zips)
i still think that the SageMaker operators could provide this easy to use configuration object instead of the full blown package , but this is sagemaker issue i guess.

**Comment by mik-laj** [comment] 2020-08-09 20:58
I close the ticket because the problem is no longer with Airflow, but with the Sagemaker SDK.

@shlomiken Thank you for sharing your experience about this operator.

**Comment by eladkal** [comment] 2021-03-14 09:00
@mik-laj You mention you wanted to close this issue but it's still open. Do we have a task here?

**Closed as completed** 2021-03-14 10:20 UTC
Labels: provider:amazon, kind:feature
