### ISSUE TITLE
'Access is Denied' errors are for the previous page

### ISSUE THREAD

**Issue by swalkowski** [apache/airflow#12237] opened 2020-11-10 09:51 UTC
**Apache Airflow version**: 1.10.12

**Environment**:

- **Cloud provider or hardware configuration**: Google Cloud Composer (tweaked environment running Airflow RBAC UI)

**What happened**:

In Airflow RBAC UI, when switching between pages, 'Access is Denied' error message actually indicates missing permissions on the previously visited page.

I understand the basic scenario for which this behavior has been designed:

- I try to go to a page to which I don't have access, I am redirected to the home page, which shows 'Access is Denied', so I conclude that I don't have access to the page that I tried to open.

But the interactions which end up in showing 'Access is Denied' are not always that simple, and this is where it gets confusing to show the message on a different page than the one to which the user had no access:

- When I'm an Admin and go to List Users, click Edit record on my user, change my role from Admin to Viewer, click Save, I am redirected to the home page, which shows a green 'Changed Row' message and a red 'Access is Denied'.
    - This is a confusing signal. Did the role assignment succeed or not? Which access was denied if I didn't try to open any page? (I know the messages come from successful user record update and unsuccessful load of List Users page to which I'm redirected after clicking Save - but not every user may realize this.)
    
![Changed Row - Access is Denied](https://user-images.githubusercontent.com/12511618/98655992-6e47a400-2340-11eb-9eae-a903e4f1a8c0.png)

- When I don't have `can varimport on VariableModelView` permission and go to Variables page, choose a file, click Import Variables, I am redirected to the home page, which shows 'Access is Denied'.
    - How do I know which permissions I was missing? I might think that I didn't have permission to the file, which is not the case.

- In Airflow 1.10.10 we've also observed a situation in which removing some permissions (from the current user's role) required for asynchronous work on the homepage, loading the homepage, and going to an unrelated page (like List Roles) resulted in showing a completely unexpected 'Access is Denied' message in that unrelated page.
    - This was the most confusing behavior but I'm not able to reproduce it in Airflow 1.10.12. Here, the asynchronous work on one page resulted in accumulating 'Access is Denied' message in the background, and showing it on the next page visited, no matter what the next page was.

I guess this behavior may be built deeply into Flask-AppBuilder and hard to change. But it's still a UX concern for Airflow.

**What you expected to happen**:

'Access is Denied' error should clearly indicate which page or its fragment it refers to.

**How to reproduce it**:

Follow the setup and steps described in 'What happened' section.

+cc @ryanahamilton @k-jakub

**Comment by potiuk** [comment] 2020-11-10 10:01
Indeed, that seems like a pretty confusing thing - possibly also something that we can address for 2.0 and I'd be glad to cherry-pick it to 1.10 if (again :) ) this could be an easy fix.

I think this is not the best idea to show details of why there is "access denied" - from a security point of view, showing details of access problem might be a clue for an attacker - but, from earlier discussions - this is not too big of a problem here. The user has already access to the UI so possibly showing at least "which" page the "Access Denied" error is about is not really a big problem. @ryanahamilton @jhtimmins  (since you were working a lot on the permissions recently) -> WDYT? Would that make sense to add some extra information to the "AccessDenied" error to tell at least which resource/page it is about? 

I think improving the "flow" might be quite a bit more difficult and Access Denied might still show up in another page (due to redirections) but at least showing what the "Access Denied" was all about might be a "good-enough" solution.

**Comment by potiuk** [comment] 2020-11-30 09:17
Hey @ryanahamilton @jhtimmins -> any feedback here? Maybe that's something we can fix before 2.0 :)?

**Comment by ashb** [comment] 2020-11-30 13:25
This is sort of just "how flashed messages work in Flask" -- my gut reaction says this isn't an easy fix, and it is deep in the bowls if Flask _and_ FAB. :(

**Comment by potiuk** [comment] 2020-11-30 19:24
:(. So should we wait for UI rewrite? BTW. Is this is still planned after the 2.0 refresh :)  ? Sounds like we have decent UI now.

**Comment by ashb** [comment] 2020-12-01 19:55
Probably easier. If we weren't doing a rewrite I have idea how we could do it, but it would involve a large replacement to the `flash()` guts and FABs permission handling that seems not worth it right now

**Comment by ClassyLion** [comment] 2021-08-11 08:04
I'm running latest version of Airflow - 2.1.2, and I'm seeing thie "Access is denied" error when I log into Airflow.

**Comment by uranusjr** [comment] 2021-08-11 08:13
Maybe it would be possible to show what page exactly is emitting the message? For example *Accessed is Denied for http://myserver/foo/bar* fels like an OK-ish stopgap.

**Comment by ClassyLion** [comment] 2021-08-11 08:27
It shows up only on the initial home page of Airflow after logging in. If I go to a different page it disappears and when I go back to the homepage, it does not show anymore. I have admin access to Airflow deployment, so I'm not really sure what would show the "Access is Denied". And checking logs, nothing shows up with permissions or access issues.

This is how it looked now:
![image](https://user-images.githubusercontent.com/24903212/128996100-c1087452-a2b1-4323-bcd1-595d6af8872a.png)

**Comment by debimishra89** [comment] 2021-09-08 17:15
I am too getting access is denied error after login. 
I am not even able to logout. It throws the same "access denied" issue on the homepage.

**Comment by eladkal** [comment] 2023-02-06 12:44
Duplicate of https://github.com/apache/airflow/issues/15601#issuecomment-1030828147
Since this seems to be more FAB issue + no new reports since Airflow 2.1 I'm closing this issue.

**Closed as not planned by eladkal** 2023-02-06 12:44 UTC
Labels: kind:bug, area:webserver, _eol_affected_version:2.1
