### ISSUE TITLE
Connection password not being masked in default logging

### ISSUE THREAD

**Issue by raajpackt** [apache/airflow#16614] opened 2021-06-23 12:17 UTC
```
from airflow.hooks.base_hook import BaseHook
Basehook.get_connection('my_connection_id')
```

The second line prints out my connection details including the connection password in Airflow logs. Earlier connection passwords were masked by default.

https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/hooks/base.html

The above statement is run for logging. Is there a way to disable to logging to not print Connection password in my logs?

**Comment by potiuk** [comment] 2021-06-23 20:06
unless you have custom logging configuration, the connection credentials should be masked by default: https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/index.html?highlight=masking#masking-sensitive-data

Can you share more info please on your logging configuration and fields that seem to be not masked cc: @ashb

**Comment by potiuk** [comment] 2021-06-28 11:09
Hello. Until we have the response here - a number of problems with masking of logging has been addresses in 2.1.1 airflow (which is going to be released in 1-2 days likely). Closing it for now until more information is provided.

**Closed as completed** 2021-06-28 11:11 UTC
Labels: kind:bug, pending-response

**Comment by JonnyWaffles** [comment] 2022-01-22 17:19
Hi @potiuk and team, I am on 2.1.3 of Airflow and seeing the same. A simple connection test executing `hook.get_conn()` is logging my client_secret password when logging is set to INFO. I see the following code where the redactor does not receive a name for the key as a second argument, simply the text value of the password

https://github.com/apache/airflow/blob/d5cafc901158ec4d10f86f6d0c5a4faba23bc41e/airflow/hooks/base.py#L69-L79

If I test the redactor myself it returns my password

```python
from airflow.utils.log.secrets_masker import _secrets_masker
m = _secrets_masker()
m.redact("<MY CLIENT SECRET VALUE>")
```
I don't know if this is expected or not but my client secret (provided to the connection uri as a password) is being leaked when I run my simple connection test via pytest.

I have not modified the log settings other than to set `AIRFLOW__LOGGING__LOGGING_LEVEL=INFO`.

**Comment by JonnyWaffles** [comment] 2022-01-22 17:30
I found another related issue https://github.com/apache/airflow/issues/16558, perhaps the problem is execution of hooks within `pytest`? How do I configure the redactor to redact regardless of where it is being executed?

**Comment by JonnyWaffles** [comment] 2022-01-22 17:36
Sorry last follow up, adding the following code to my pytest conftest.py resolves the above
```python
from airflow import settings
settings.MASK_SECRETS_IN_LOGS = True
```
I gotta say I am surprised by this behavior. I did not expect the secrets to show up in the pytest logs by default.

**Comment by potiuk** [comment] 2022-01-22 18:20
Glad that you sorted it out.

> I gotta say I am surprised by this behavior. I did not expect the secrets to show up in the pytest logs by default.

The logs are redacted specifically to account for task logs for users and  UI visibility. This is by design, deliberate and documneted.

Comment in our code:

```
# By default this is off, but is automatically configured on when running task
# instances
MASK_SECRETS_IN_LOGS = False
```

Our documentation is very clear about this behaviour:

https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/mask-sensitive-values.html

> Airflow will by default mask Connection passwords and sensitive Variables and keys from a Connection’s extra (JSON) field when they appear in **Task logs**, in the **Variable** and in the **Rendered fields views** of the UI.

So I do not find it surprising really. 

Also It would be quite unreasonble and possibly even not possible to expect that secret masking is "general feature" enabled whenever you run python interpreter and perform an entrypoint that might or might not initialize secret masking (this is what your expectation is about pretty much). This is a feature of "airflow" application, and not "running arbitrary part of airflow code".
