### ISSUE TITLE
`ALL_DONE` trigger rule not respected in TaskFlow API for upstream failures

### ISSUE THREAD

**Issue by ZouhirSarrar** [apache/airflow#23942] opened 2022-05-26 16:01 UTC
### Apache Airflow version

2.3.0

### What happened

Hello!

I'm using taskflow api for my dag and was trying to run the last task even if the previous task failed, I used `@task(trigger_rule=TriggerRule.ALL_DONE)` but i still got the ending task failed too.

<img width="213" alt="image" src="https://user-images.githubusercontent.com/38496723/170526480-131e6ed4-e2a0-4711-9328-2326f94885e3.png">

The UI confirms that I declared the trigger_rule "all_done"
<img width="218" alt="image" src="https://user-images.githubusercontent.com/38496723/170526766-72ba0eb7-2525-4d60-a8c3-ab3dd700d88b.png">

### How to reproduce

This is the whole code
```
import logging
import pendulum
from airflow.decorators import task, dag
from airflow.utils.trigger_rule import TriggerRule


@dag(
    schedule_interval=None,
    start_date=pendulum.datetime(2021, 5, 10, tz="UTC"),
    catchup=False,
)
def taskflow_trigger():
    @task()
    def first_task():
        return "first_task"

    @task
    def second_task(value):
        return "second_task"

    @task
    def task_to_fail(value):
        data = {"test": 1}
        val = data["not_here"]
        return val

    @task(trigger_rule=TriggerRule.ALL_DONE)
    def end(value):

        return "yes"

    op_1 = first_task()
    op_3 = task_to_fail(op_1)
    op_2 = second_task(op_1)
    end([op_3, op_2])

taskflow_trigger = taskflow_trigger()
```

### Operating System

"Debian GNU/Linux 11 (bullseye)

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment] 2022-05-26 17:27
IMO this should be expected. The `end` task is expecting an input from the `task_to_fail` output but the latter task has failed and doesn't produce an `XComArg`. The `end` task does _actually_ run so the trigger rule is respected, but fails with:
```bash
airflow.exceptions.AirflowException: XComArg result from task_to_fail at taskflow_trigger with key="return_value" is not found!
```

What would you expect the behavior to be in this scenario?

**Comment by ZouhirSarrar** [comment] 2022-05-26 18:53
> 

i want the end task to continue working

**Comment by z-sarrar** [comment] 2022-05-27 08:53
I did this and it worked for me
`[op_2, op_3] >> join()`

**Comment by josh-fell** [comment] 2022-06-13 19:56
A [similar issue was raised](https://github.com/apache/airflow/issues/24338) when upstream tasks are skipped. The point of "the downstream should not run if any of its depended upstream XCom values fail to resolve" (in [this comment](https://github.com/apache/airflow/pull/24401#issuecomment-1153215501)) was brought up again. 

@uranusjr curious for your take on this issue generally.

I feel that, as this issue is written, the consensus is that a downstream TaskFlow task should not execute if a dependent, upstream `XCom` cannot be found.

**Comment by mariotaddeucci** [comment] 2022-06-13 23:24
I have the same issue, after upgrading from 2.1.3 to 2.3.2, some dags with the trigger rule all_done, starting to raises this exception

**Comment by uranusjr** [comment] 2022-06-14 03:53
Since an XCom push can never be None[^1], we can probably just set the value to None in this case. Combining this with #24401, we probably need to do some additional checks in `XComArg.resolve()` to take account the current task’s trigger rule, and resolve to None when appropriate.

[^1]: A design decision I didn’t agree with but that ship sailed long ago.

**Comment by ashb** [comment] 2022-07-06 08:50
Duplicate of #24338 (It's the same underlying cause)

**Closed as completed by ashb** 2022-07-06 08:50 UTC
Labels: kind:bug, area:core
