### ISSUE TITLE
add support for dataset triggers with an or condition

### ISSUE THREAD

**Issue by alonahmias** [apache/airflow#36973] opened 2024-01-23 15:15 UTC
### Description

I want to be able to schedule a dag with an or condition between the datasets
For example i have the following datasets:
dataset_a
dataset_b
I want my dag to be scheduled when dataset_a was changed or when dataset_b was changed and not wait for both of them to change
I don't really know if this feature was not introduced for a reason but if so i would love to hear the reason

### Use case/motivation

Let's say i have a DAG that write table a to my database and changes the dataset_a and a different DAG that writes table b to my database and changes  dataset_b.
In addition i have a third DAG that aggregates data from table a and table b.
This means that i want the table to be updated as soon as each one of the other tables was updated.
I can create a DAG for each dataset but then if both of the tables arrive at the same time i would have a lock on the aggregated table.

### Related issues

I couldn't any related issues

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dirrao** [comment] 2024-01-23 17:05
@alonahmias 
Can you share the airflow version?

**Comment by alonahmias** [comment] 2024-01-23 17:48
Currently im using airflow 2.5.2 but we're soon upgrading to version 2.8.1 but still i didn't see any documentation about it

**Comment by dstandish** [comment] 2024-01-25 15:27
Hi, @sunank200 and I are working on this presently. But this seems to be duplicate of https://github.com/apache/airflow/issues/34534

duplicates https://github.com/apache/airflow/issues/34534

**Closed as not planned by dstandish** 2024-01-25 15:27 UTC
Labels: kind:feature, duplicate, pending-response, area:data-aware-scheduling
