### ISSUE TITLE
Trigger Config, Trigger Config Template

### ISSUE THREAD

**Issue by CreedsCode** [apache/airflow#17307] opened 2021-07-29 09:24 UTC
Make it possible to create a Trigger config template, and make it possible to enforce the configuration.

**Use case / motivation**

The use case would be to make ETL Batch jobs configurable, for the use case: Of getting data from a specific time, a DAG that depends on a givin input. like a list of ID's a email, So an extraction from a db can be taken out of Airflow and the result are getting send per mail. 

**Are you willing to submit a PR?**

No

**Related Issues**

Didn't find anything that follows the idea.

**Comment by mik-laj** [comment] 2021-07-30 00:02
It is related? https://github.com/apache/airflow/pull/17100

**Comment by CreedsCode** [comment] 2021-07-30 05:24
Yes!

**Comment by potiuk** [comment] 2021-08-02 19:42
duplicate of #17100

**Closed as completed by potiuk** 2021-08-02 19:42 UTC
Labels: kind:feature, duplicate
