### ISSUE TITLE
Jumping tasks in grid 

### ISSUE THREAD

**Issue by fokmess** [apache/airflow#27523] opened 2022-11-05 21:15 UTC
### Apache Airflow version

2.4.2

### What happened

Some tasks can be reordering during run in grid

![Jumping_Tasks](https://user-images.githubusercontent.com/61796911/200141120-888e70ff-cd91-4498-ab56-b96cde40d448.gif)

<img width="322" alt="Снимок экрана 2022-11-06 в 00 02 24" src="https://user-images.githubusercontent.com/61796911/200141268-e79530b5-2d75-4512-81d8-102cf484f706.png">
<img width="368" alt="Снимок экрана 2022-11-06 в 00 02 19" src="https://user-images.githubusercontent.com/61796911/200141269-d1854f9e-6280-400a-8b13-affa40573c97.png">

### How to reproduce

When i start generating tasks from query on postgreSQL and run any dag this bug show up

### Operating System

Ubuntu 20.04.5 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-common-sql==1.0.0
apache-airflow-providers-elasticsearch==4.2.1
apache-airflow-providers-ftp==3.0.0
apache-airflow-providers-google==8.1.0
apache-airflow-providers-http==3.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-postgres==5.0.0

### Deployment

Virtualenv installation

### Anything else

Every run on random tasks groups

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment] 2022-11-07 16:24
I'll look into this. Quick question, does this happen for all of your dags or only specific ones?

**Comment by bbovenzi** [comment] 2022-11-09 16:28
Ahh ok. @ashb I remember that you wrote up the task ordering logic. Sounds like there might be an issue parsing the tasks for programmatically generated DAGs?

Also, this is probably a duplicated of https://github.com/apache/airflow/issues/23542

**Comment by ashb** [comment] 2022-11-09 17:55
Maybe we need to add a "fallback" sort to sort by task_id as a last resort so that the order is stable.

**Comment by pierrejeambrun** [comment] 2022-11-13 14:04
@fokmess I see that you are willing to make a PR to fix this, I am assigning you. :smile: 

Don't hesitate to ask for some pointers if needed

**Comment by ashb** [comment] 2022-11-16 16:34
I've got a fix for this, in working out where the problem was I have found that the fix is one line of code (and a new test)

**Comment by ashb** [comment] 2022-11-17 11:04
I'm actually not sure about my fix. Yes it does make the sort order stable, but right now the order _should_ be using the "file definition order" -- i.e. tasks added to the dag first appear in the sort first. And that "feels" like a better default sort for most people that forcing it to use task_id sorting

@fokmess What is the "input" for your dynamic DAG? Is it based on something that might be "unordered" (though please note that dicts in python from 3.6+ are always ordered by insertion order, so anything like loading json or yaml from a file will also be ordered)

**Comment by ashb** [comment] 2022-11-17 11:05
Ah:

> When i start generating tasks from query on postgreSQL and run any dag this bug show up

So yeah, I guess we need to decide if this is something we should change in Airflow, or is the right fix here to be say "add an `ORDER BY` to your query to generate it in a stable order"

I'm leaning towards the later.

**Comment by potiuk** [comment] 2022-11-17 11:24
> So yeah, I guess we need to decide if this is something we should change in Airflow, or is the right fix here to be say "add an ORDER BY to your query to generate it in a stable order"

> I'm leaning towards the later.

Agree - sorting by "deifinition order" is generally way better than alphabetic sorting in DAGs. We have similar issue about sorting the template_fields - https://github.com/apache/airflow/issues/27026#issuecomment-1316958468 where I believe we should keep "natural order" not sorting nor parameterisation. Everywhere where DAG Author (or DAG Generating programmer if it is from a DB) this gives the user full control over the order it will appear in UI without adding any new options and parameters. If they want to sort those alphabetically - they can still do it at writing/generation time. Nothing blocks them from doing so.

**Comment by pierrejeambrun** [comment] 2022-11-17 19:13
Removing the `area:UI` for `area:webserver` as this is most likely where changes will happen (if any)

**Comment by ashb** [comment] 2022-11-19 11:20
Chaning my idea of a fix from code fix to documentation against `docs/apache-airflow/howto/dynamic-dag-generation.rst`

**Comment by JCoder01** [comment] 2022-11-28 16:56
I'm seeing this behavior too in a couple of my dags. I don't load anything from a database, and the dags generated just using `with Dag(...) as dag:`

**Comment by bt-** [comment] 2022-11-28 20:57
I am running into the same thing with my DAG. I have the tasks within my TaskGroups dynamically generated based on a list parsed from a yaml file. After watching more closely, it is my TaskGroups that move around in the grid view. The tasks within the TaskGroup aren't moving.

**Comment by JCoder01** [comment] 2022-11-28 21:53
Taking a longer look at mine, I'm seeing the same thing. This occurs on a dag with a task group, when the task group is expanded the task group and downstream tasks move around. It alternates between being correctly ordered and the expanded task group and the downstream tasks appearing before the completed upstream tasks.

**Comment by NilsJPWerner** [comment] 2022-12-14 19:00
I have the same issue as @JCoder01. When the task groups are expanded they reorder constantly. I can post a smaller example that show the behavior.

**Comment by NilsJPWerner** [comment] 2022-12-14 20:36
```python
with DAG(
  #misc
) as dag:
    run_id = "{{ dag_run.conf.get('run_id') or data_interval_end.int_timestamp }}"
    updater = create_updater_tasks(run_id)
    morning_block = create_morning_block_tasks()
    updater >> morning_block


def create_updater_tasks(run_id: str):
    track_matching = StataOperator(name="track_matching")

    with TaskGroup("create_expost_data_with_wps") as create_expost_data_group:
        DummyOperator(task_id="do_stuff_1")

    with TaskGroup("create_exante_data") as create_exante_data_group:
        DummyOperator(task_id="do_stuff_2")

    merge_expost_exante_data = StataOperator(name="merge_expost_exante_data", )

    start_updater = DummyOperator(task_id="start_updater")
    end_updater = DummyOperator(task_id="end_updater")

    start_updater >> track_matching
    track_matching >> create_expost_data_group >> merge_expost_exante_data
    track_matching >> create_exante_data_group >> merge_expost_exante_data >> end_updater
    return end_updater

def create_morning_block_tasks():
    with TaskGroup("morning_block") as morning_block_tasks:
        DummyOperator(task_id="do_stuff_3")
```
And here are some examples of it jumping around
<img width="333" alt="Screen Shot 2022-12-14 at 3 34 53 PM" src="https://user-images.githubusercontent.com/10968348/207708328-d9c69074-0b74-4a94-9b15-29605d90b2ba.png">
<img width="271" alt="Screen Shot 2022-12-14 at 3 35 15 PM" src="https://user-images.githubusercontent.com/10968348/207708343-2593375f-fc72-4199-9aa2-573ced39023b.png">

**Comment by potiuk** [comment] 2022-12-30 12:37
FYI @ashb @bbovenzi - the example above changes the diagnosis a bit. Seems that this is not only when there are dynamic DAGs and lack of ordering of task creation (which I agree is not a bug on Airflow but a bug in DAG generation). Seems that this cases is also something that might be caused by lack of consistent ordering when there are multiple TaskGroups.  Marked it for 2.5.1 as this one seems like esy fix for that case.

**Comment by JCoder01** [comment] 2023-05-01 12:43
@NilsJPWerner, @fokmess, are you still seeing this? I'm on 2.5.3 and the ordering seems consistent now.

**Comment by potiuk** [comment] 2023-05-01 21:15
closing as fixed. We can reopen just in case.

**Closed as completed by potiuk** 2023-05-01 21:15 UTC
Labels: good first issue, kind:documentation, pending-response, area:UI
