### ISSUE TITLE
SFTP Sensor fails to locate file

### ISSUE THREAD

**Issue by eladkal** [apache/airflow#27418] opened 2022-10-31 18:33 UTC
### Body

issue is described in PR https://github.com/apache/airflow/pull/25705
the author of the PR abandon it so anyone can try to submit a fix to the issue.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

**Comment by Bowrna** [comment] 2022-11-01 09:11
could I try fixing this issue @eladkal ?

**Comment by potiuk** [comment] 2022-11-01 11:53
Feel Free.

**Comment by potiuk** [comment] 2022-12-05 16:29
Closing as duplicate of #28121 (and the other being more complete)

**Closed as completed by potiuk** 2022-12-05 16:29 UTC
Labels: kind:bug, good first issue, duplicate
