### ISSUE TITLE
Custom timetable causes crash using airflow test

### ISSUE THREAD

**Issue by barskern** [apache/airflow#19578] opened 2021-11-13 23:18 UTC
### Apache Airflow version

2.2.1 (latest released)

### Operating System

Arch Linux

### Versions of Apache Airflow Providers

None relevant

### Deployment

Virtualenv installation

### Deployment details

A local installation for development purposes.

### What happened

Following the tutorial for custom timetable (https://airflow.apache.org/docs/apache-airflow/stable/howto/timetable.html) causes a error when the dag is run using `airflow tasks test example_after_workday_timetable_dag 2021-11-14`.

```
[[34m2021-11-14 00:18:34,874[0m] {[34mdagbag.py:[0m500} INFO[0m - Filling up the DagBag from /home/oruud/Programming/homecloud_data_pipeline[0m
[[34m2021-11-14 00:18:34,902[0m] {[34mtaskinstance.py:[0m1035} INFO[0m - Dependencies all met for <TaskInstance: sbanken_etl.extract None [None]>[0m
[[34m2021-11-14 00:18:34,906[0m] {[34mtaskinstance.py:[0m1035} INFO[0m - Dependencies all met for <TaskInstance: sbanken_etl.extract None [None]>[0m
[[34m2021-11-14 00:18:34,906[0m] {[34mtaskinstance.py:[0m1239} INFO[0m - 
--------------------------------------------------------------------------------[0m
[[34m2021-11-14 00:18:34,906[0m] {[34mtaskinstance.py:[0m1240} INFO[0m - Starting attempt 1 of 1[0m
[[34m2021-11-14 00:18:34,906[0m] {[34mtaskinstance.py:[0m1241} INFO[0m - 
--------------------------------------------------------------------------------[0m
[[34m2021-11-14 00:18:34,906[0m] {[34mtaskinstance.py:[0m1260} INFO[0m - Executing <Task(_PythonDecoratedOperator): extract> on 2021-11-01T00:00:00+00:00[0m
[[34m2021-11-14 00:18:34,934[0m] {[34mtaskinstance.py:[0m1701} ERROR[0m - Task failed with exception[0m
Traceback (most recent call last):
  File "/home/oruud/Programming/airflow/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    context = self.get_template_context(ignore_param_exceptions=False)
  File "/home/oruud/Programming/airflow/airflow/models/taskinstance.py", line 1790, in get_template_context
    data_interval = dag.get_run_data_interval(dag_run)
  File "/home/oruud/Programming/airflow/airflow/models/dag.py", line 658, in get_run_data_interval
    return self.infer_automated_data_interval(run.execution_date)
  File "/home/oruud/Programming/airflow/airflow/models/dag.py", line 679, in infer_automated_data_interval
    raise ValueError(f"Not a valid timetable: {self.timetable!r}")
ValueError: Not a valid timetable: <airflow.example_dags.plugins.workday.AfterWorkdayTimetable object at 0x7faf394aaaf0>
[[34m2021-11-14 00:18:34,935[0m] {[34mtaskinstance.py:[0m1268} INFO[0m - Marking task as FAILED. dag_id=sbanken_etl, task_id=extract, execution_date=20211101T000000, start_date=20211113T231834, end_date=20211113T231834[0m
```

### What you expected to happen

I expected it to work.

### How to reproduce

Run the code from the tutorial, e.g. the following dag with this command:

```
airflow tasks test example_etl_dag 2021-11-14
```

```python
from airflow.decorators import dag, task

from airflow.example_dags.plugins.workday import AfterWorkdayTimetable

@dag(
    start_date=datetime(2020, 1, 1),
    timetable=AfterWorkdayTimetable(),
)
def example_etl():
    @task()
    def extract():
        pass

    extract()

example_etl_dag = example_etl()
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vaci** [comment] 2021-11-20 13:59
I see a similar issue when attempting to run a task using a custom Timetable, as it is then not possible to render templates in an operator.

The problem is caused by this code, which specifically checks for certain sub-classes of Timetable:
https://github.com/apache/airflow/blob/2.2.1/airflow/models/dag.py#L652

**Comment by uranusjr** [comment] 2021-11-20 16:23
Is this an entirely new DAG, or are you changing an existing DAG to use a custom timetable?

**Comment by potiuk** [comment] 2021-11-20 16:29
Hmm @uranusjr - maybe I am missing something but I believe we simply did not plug calling `infer_data_interval` from custom timetables. I cannot find a single place where it would be called, and I believe it should be use for Custom Timetables to infer the interval for manual/test/out-of-bands runs. 

I believe we simply lost it while implementation - even if it is nicely described in the docs. :)

**Comment by uranusjr** [comment] 2021-11-20 16:56
The root problem is that `airflow dag test` is not running anything out-of-band; it triggers full-blown backfill runs, and there’s absolutely no way to distinguish those runs from backfill runs triggered by the executor. I mentioned that in #18473 and #18758; the current behaviour of this command is a big odd-ball in the big picture and does not really make sense fundamentally.

**Comment by potiuk** [comment] 2021-11-20 17:01
But this case is `airflow tasks test` not the `airlfow dag tests` (and I do agree dag tests is not good).

For tasks test I thin the data interval should be inferred as in the docs, and regardles from the error reported with task tests I think `infer_data_interval` not being called at all in our code is quite a bit worrying.

**Comment by uranusjr** [comment] 2021-11-20 17:14
Oh! I misread then, and identified the problem wrong. But the root issue is somewhat similar though. In both cases, the command would find an existing DAG run, and re-run either one ti or all tis in it.

The problem is that, if a DAG run was created before the timetable was changed, the run will not be able to infer a meaningful data interval. Before 2.2, a DAG run only has `execution_date`, and the data interval needs to be inferred, but _the inferring logic should be based on the previous schedule definition_ because that’s what scheduled that run, but that schedule no longer exists. Furthermore, a custom timetable is not capable of inferring a data interval from a logical date, because there’s no such interface on the timetable right now, and that’s due to this idea not making logical sense in the first place—a DAG run’s logical date and data interval are conceptually independent.

So unless we change the semantic for `dags test` and `tasks test` (which is not trivial), we either need to “invent” something to tie logical date to data interval and give up their independency (with long term consequences), or we need to…give up, in a sense. When we hit the situation, we can show a friendly-ish message explaining how this does not work (the run you’re trying to trigger was created before Airflow 2.2 and is not compatible with custom timetables), and provide a solution for the user to get out of this. The easiest solution would be to simply delete that run and re-trigger it on Airflow 2.2, or we could potentially provide a script for the user to “migrate” that existing run to 2.2.

**Comment by potiuk** [comment] 2021-11-20 17:24
> So unless we change the semantic for `dags test` and `tasks test` (which is not trivial),

Why don't we add "data-interval' to `dags test` and `tasks tests` command to specify it manually ? Those are tests commands for user to try things out, they could add data interval there and we could provide a helpful explanation and hint what data interval they should add if they don't specify them for Custom timetable. 

> The easiest solution would be to simply delete that run and re-trigger it on Airflow 2.2, or we could potentially provide a script for the user to “migrate” that existing run to 2.2.

But I think in this case the run does not even exist - so we have nothing to delete. `airflow tasks test` I believe does not even look nor modify DagRun table - as I remember (and commented in #18758) `dags tests` and `tasks tests` should not leave any traces in the DB in DagRun table (even if `dags tests` conceptually run backfill, it used DebugExecutor and - as far as I remember at least, did not rely on the DB entries). Or at least that was the intention..

**Comment by uranusjr** [comment] 2021-11-20 17:28
> Why don't we add `data-interval` to `dags test` and `tasks tests` command to specify it manually?

That works for me as well, as a variant to the “give up” solution.

**Comment by potiuk** [comment] 2021-11-20 17:29
What still worries me - why we have the `infer_data_interval` documentaed by not used @uranusjr :) ?

**Comment by uranusjr** [comment] 2021-11-20 17:35
Because `infer_data_interval` is for inferring manual runs, and `test` commands run backfill runs! There are conceptually no way to infer a data interval for an automated (i.e. scheduled or backfill) run from a logical date, as I mentioned above.

**Comment by potiuk** [comment] 2021-11-20 17:38
Yeah. yeah I understand that - but it doesn't seem to be used in the code AT ALL (or maybe I missed it when searching). I just could not find a single call to the `infer_data_interval` in the whole Airflow codebase.

**Comment by uranusjr** [comment] 2021-11-21 05:55
Oooooh. Good catch, because the function is actually named wrong in the example! The correct function name is in fact `infer_manual_data_interval`.

https://github.com/apache/airflow/blob/9517342b727b977bcc7a99197c802bc084584c5d/airflow/timetables/base.py#L160-L167

**Comment by potiuk** [comment] 2021-11-21 09:06
Ahhh ! That explains everything :)

**Comment by eladkal** [comment] 2022-01-17 22:20
fixed in https://github.com/apache/airflow/pull/19735

**Closed as completed by eladkal** 2022-01-17 22:20 UTC
Labels: kind:bug, area:core, _eol_affected_version:2.2
