### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Yaro1** [apache/airflow#12732] opened 2020-12-01 10:56 UTC
[https://airflow.readthedocs.io/en/stable/_modules/airflow/hooks/dbapi_hook.html#DbApiHook.get_records](url)

In the method description said, that get_records can take string and list of the strings. But it can execute only string, not list. The method doesn't even check is it a list or is it a string.

**Comment by potiuk** [comment] 2020-12-01 11:02
Hey @Yaro1. Would you mind adding a PR fixing it ? I am happy to review it.

**Comment by Yaro1** [comment] 2020-12-01 11:09
Yeah, i would like to solve this issue, if i understand you right.

**Comment by potiuk** [comment] 2020-12-01 11:10
Yep!

**Comment by Yaro1** [comment] 2020-12-01 11:13
Can you please assign it on me?

**Comment by eladkal** [comment] 2020-12-01 13:43
Closing as it's duplicate of https://github.com/apache/airflow/issues/9957

**Closed as completed** 2020-12-01 13:43 UTC
Labels: kind:bug, duplicate
