### ISSUE TITLE
Airflow 2.7.3: Mapped task group no longer works as expected

### ISSUE THREAD

**Issue by Ahmed-Khaled-CS** [apache/airflow#35541] opened 2023-11-08 22:06 UTC
### Apache Airflow version

2.7.3

### What happened

Hello folks,

I have a use case that doesn't work anymore after the release of the new version 2.7.3.
I have done some investigation and found that is related to this [PR](https://github.com/apache/airflow/pull/34337) as I have reverted this locally and run some tests it worked as expected.

Please find below how to reproduce the issue.

Cc @ephraimbuddy 
Thanks.

### How to reproduce

Below is the DAG code:

```
def dag():

    @task
    def make_list():
        return [4, 42, 2]

    @task
    def double(n):
        if n == 42:
            raise AirflowSkipException("42")
        return n*2

    @task
    def last(n):
        print(n)

    @task_group
    def group(n: int) -> None:
        last(double(n))

    list = make_list()
    group.expand(n=list)

dag()

```

Running this DAG with the 2.7.3 version, will give you the  result below:

<img width="1058" alt="Screenshot 2023-11-08 at 22 58 07" src="https://github.com/apache/airflow/assets/114393790/f2199d4d-f283-485e-8860-f53b0db29e3f">

<img width="2160" alt="Screenshot 2023-11-08 at 22 58 22" src="https://github.com/apache/airflow/assets/114393790/8c84335f-eb9e-4829-b679-55d84da21625">

<img width="2160" alt="Screenshot 2023-11-08 at 22 58 30" src="https://github.com/apache/airflow/assets/114393790/df5eeeef-08f6-474b-8944-8a53bd2e30a1">

As you can see, the status of the last task is skipped and the map index 0 and 1  was not launched.
You will obtain the same issue with AirflowFailException instead of AirflowSkipException and the status of the last task will be failed.

In the other hand, if you run the same DAG with the 2.7.2 version (or without the changes in the provided PR above), you will get the result below which is the correct one:

<img width="843" alt="Screenshot 2023-11-08 at 22 53 06" src="https://github.com/apache/airflow/assets/114393790/d518dfde-81eb-4a45-81f9-9bba3a57b3da">

<img width="2116" alt="Screenshot 2023-11-08 at 22 53 31" src="https://github.com/apache/airflow/assets/114393790/8686c7bd-9803-4ab5-934f-ce4560c4de7a">

<img width="2116" alt="Screenshot 2023-11-08 at 22 53 40" src="https://github.com/apache/airflow/assets/114393790/ff6448b3-a63e-40fe-8f71-41ab6571998c">

### Operating System

linux

### Deployment

Docker-Compose

### Deployment details

[Airflow Breeze](https://github.com/apache/airflow/blob/main/BREEZE.rst#id13)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Ahmed-Khaled-CS** [comment] 2023-11-14 12:34
Hello @ephraimbuddy, @uranusjr, and @eladkal ,
could you please confirm that it is a regression after the commit of this [PR](https://github.com/apache/airflow/pull/34337) ?

I'm pining you as you have contributed on this PR and hopefully that you have an idea about my issue 😄 

thank you.

**Comment by ephraimbuddy** [comment] 2023-11-14 12:56
I saw this behaviour change and mentioned it [here](https://github.com/apache/airflow/pull/34337#issuecomment-1721605099) but I guess, I acted fast in merging(though waited for some weeks). 

The issue is that the task has to wait for all the upstream tasks to be done before proceeding. Now, when proceeding, [this](https://github.com/astronomer/airflow-private/blob/84f4b7abaf1903066ef24d56d1ef66b494a244e8/airflow/ti_deps/deps/trigger_rule_dep.py#L373) check will be true as one is skipped and the ti would be marked as skipped.

@uranusjr , Do you think we should apply the first [commit](https://github.com/apache/airflow/pull/34337/commits/a5fe590322f8e08454564e9edb8c9528e9453e9b)?

**Comment by uranusjr** [comment] 2023-11-15 08:55
I also mentioned in that commit that the fix may not work right either though. I feel we should revert the PR entirely and investigate a correct fix altogether.

**Comment by eladkal** [comment] 2023-11-25 09:01
> I feel we should revert the PR entirely and investigate a correct fix altogether.

Can we set a unit test to catch the problematic case thus when we try new approach we would be able to see if it passes or not?

**Comment by potiuk** [comment] 2023-12-30 11:21
I believe now we have test so we can re-do attempt to fix it?

**Comment by eladkal** [comment] 2023-12-30 15:45
@potiuk i think https://github.com/apache/airflow/pull/36462 handles it?

**Comment by potiuk** [comment] 2023-12-30 17:42
Not sure :). Have not looked at it .

**Comment by shahar1** [comment] 2024-06-15 09:17
I'm closing this issue, as the original PR (#34337) that caused it was [reverted](https://github.com/astronomer/airflow/commit/b4321bb0947cec5c8ba17382f8fe1dfc3f8cfed4).
I'm trying to work on an improved version of the original PR, and I'll ensure that this issue doesn't reproduce.

**Closed as completed by shahar1** 2024-06-15 09:17 UTC
Labels: kind:bug, area:core
