### ISSUE TITLE
Backfill API endpoint

### ISSUE THREAD

**Issue by huymq1710** [apache/airflow#32642] opened 2023-07-17 09:46 UTC
### Description

The proposed feature is to enhance the functionality of the Airflow Backfill API endpoint. This improvement would allow users to specify a date range for backfilling DAG runs, enabling more granular control over the execution of historical tasks.

### Use case/motivation

Currently, there is no direct backfill API endpoint.

A workaround is possible by triggering a `backfilling_dag` via the API and using dag_run.conf to pass in parameters such as `start_date`, `end_date`, and `dag_id` for the required backfill (dag_to_be_backfilled).
- https://forum.astronomer.io/t/backfill-with-rest-api/2232

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2023-07-17 10:55
Duplicate of https://github.com/apache/airflow/issues/18816

**Closed as not planned by eladkal** 2023-07-17 10:55 UTC
Labels: kind:feature, needs-triage
