### ISSUE TITLE
Searching task instances by state doesn't work

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#31156] opened 2023-05-09 14:40 UTC
### Apache Airflow version

2.6.0

### What happened

After specifying a state such as "Equal to" "failed", the search doesn't return anything but resetting the whole page (the specified filter is gone)

https://github.com/apache/airflow/assets/14293802/5fb7f550-c09f-4040-963f-76dc0a2c1a53

### How to reproduce

Go to "Browse" tab -> click "Task Instances" -> "Add Filter" -> "State" -> "Use anything (equal to, contains, etc)" -> Click "Search"

### Operating System

Debian GNU/Linux 10 (buster)

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by VVildVVolf** [comment] 2023-05-10 23:04
Looking into it.

**Comment by VVildVVolf** [comment] 2023-05-11 10:17
The problem is related to `flask-appbuilder`. To be precise, [it's usage of select2](https://github.com/dpgaspar/Flask-AppBuilder/blob/6bda240422e4100bd2e223b0b7ff52c09f18ddef/flask_appbuilder/static/appbuilder/js/ab_filters.js#L143):

You can see in address bar, after clicking "Search", the address would became `/taskinstance/list/?_flt_undefined_state=failed`. But if you change it manually to something like `/taskinstance/list/?_flt_3_state=failed`, you will see that everything works fine. So, the problem does not look on airflow side.

Please, correct me if you see different picture.

I created [a PR for fba](https://github.com/dpgaspar/Flask-AppBuilder/pull/2039) according to [select2's recommendation](https://github.com/select2/select2/blob/4de1d236e602149a5c78d35899b49b3989b94107/src/js/select2/core.js#LL519C10-L519C75), but not sure if it will be merged (at least soon).

On the other hand, looks like it [might hard to update fba for the airflow itself](https://github.com/apache/airflow/blob/60536152b2466dcfab6a7323ae58beb0867caad1/README.md?plain=1#L384-L385).

@potiuk, can we theoretically upgrade fba to 4.3.1? looks like [fba already has some changes of this point](https://github.com/dpgaspar/Flask-AppBuilder/commit/5529e9a7ab6c42a1f90c25ae7f876e0f9bf19b4b#diff-22f5f0ee59615804cfa9a64e69a21b144c0a94405782d0240c203bcfddc78f5d), but honesly not sure if it does fix the problem itself yet (because of P.S. bellow).
P.S. I tried to check 4.3.1 locally (PR: https://github.com/apache/airflow/pull/31203), but breeze says that there is a restriction to use 4.3.1 instead of 4.3.0. I have not found yet how to disable it, if you would provide a hint - it will be very helpfull :)

**Comment by pankajastro** [comment] 2023-05-15 05:46
I think we can close this one since https://github.com/apache/airflow/pull/31203 has merged

**Comment by potiuk** [comment] 2023-05-15 08:48
U liked the PR and closing this one then.

**Closed as completed by potiuk** 2023-05-15 08:48 UTC
Labels: kind:bug, area:core, needs-triage
