### ISSUE TITLE
Trigger rule one_success with dynamic task mapping

### ISSUE THREAD

**Issue by rubenbriones** [apache/airflow#29202] opened 2023-01-27 20:08 UTC
### Apache Airflow version

2.5.1

### What happened

When modifying the trigger rule of a dynamic task mapping to ONE_SUCCESS, the task only creates one task mapped, and not all the N mapped task that it should create. If i leave the trigger rule to the default ALL_SUCCESS, everything works fine.

### What you think should happen instead

I want to set the ONE_SUCCESS trigger rule so that the mapped tasks that succeed keep executing theirs downstream tasks, no matter what other tasks have failed.

### How to reproduce

```py
import pendulum
from airflow.decorators import dag, task


@dag(
    schedule="0 0 * * MON-FRI",
    start_date=pendulum.datetime(2023, 1, 1, tz="UTC"),
    catchup=False,
    max_active_runs=1,
)
def etl():

    @task
    def get_symbols():
        res = [('A', 1, 111), ('B', 2, 222)]
        return res

    @task
    def extract(symbol_info, data_interval_end=None):
        # Do some work...
        return symbol_info

    @task(trigger_rule="one_success")
    def transform(symbol_info, data_interval_end=None):
        # Do some work...
        return symbol_info

    @task(trigger_rule="one_success")
    def load(symbol_info, data_interval_end=None):
        # Do some work...
        return symbol_info

    # DAG
    symbols = get_symbols()
    raw_symbols_data = extract.expand(symbol_info=symbols)
    clean_symbols_data = transform.expand(symbol_info=raw_symbols_data)
    load.expand(symbol_info=clean_symbols_data)


symbols_ib()
```

### Operating System

Ubuntu 20.04.5 LTS

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment] 2023-01-27 20:59
Hi @rubenbriones!

Do you have another reproducible case? I'm unable to observe the same behavior.

```py
import pendulum
from airflow.decorators import dag, task


@dag(
    schedule="0 0 * * MON-FRI",
    start_date=pendulum.datetime(2023, 1, 1, tz="UTC"),
    catchup=False,
    max_active_runs=1,
)
def etl():

    @task
    def get_symbols():
        res = [('A', 1, 111), ('B', 2, 222)]
        return res

    @task
    def extract(symbol_info, data_interval_end=None):
        # Do some work...
        return symbol_info

    @task(trigger_rule="one_success")
    def transform(symbol_info, data_interval_end=None):
        # Do some work...
        return symbol_info

    @task(trigger_rule="one_success")
    def load(symbol_info, data_interval_end=None):
        # Do some work...
        return symbol_info

    # DAG
    symbols = get_symbols()
    raw_symbols_data = extract.expand(symbol_info=symbols)
    clean_symbols_data = transform.expand(symbol_info=raw_symbols_data)
    load.expand(symbol_info=clean_symbols_data)


etl()  # <- only updated the call here.
```
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48934154/215195938-41e0d484-f771-4785-b2f1-27cfe1c26f67.png">

In the code from the screenshot, can you confirm that nothing reduces the number of mapped tasks from 32 to 1 between the `extract` and `transform` tasks?

**Comment by rubenbriones** [comment] 2023-01-27 23:17
Hi @josh-fell , thank you very much for your quick response. Sorry, but I just saw that it was my fault that I was not updated to the latest version 2.5.1, and I was on 2.5.0. I have updated and now everything works OK with ONE_SUCCESS trigger_rule.

Thanks, and sorry for the inconvenience.

**Comment by rubenbriones** [comment] 2023-01-29 09:19
Hello again, although I thought that with version 2.5.1 the problem was solved, it seems that it is not quite like that, and that it depends on the execution time of the tasks. Since in the MWE that I put it is true that everything goes well, but if I add a `sleep(X)` in each of the tasks I have the problem that I commented:

```py
import time
import pendulum
from airflow.decorators import dag, task


@dag(
    schedule="0 0 * * MON-FRI",
    start_date=pendulum.datetime(2023, 1, 1, tz="UTC"),
    catchup=True,
    max_active_runs=1,  # <-- I have tried removing this, and the problem persists. 
)
def etl_sleep():

    @task
    def get_symbols():
        res = [('A', 1, 111), ('B', 2, 222), ('C', 3, 333)]
        return res

    @task
    def extract(symbol_info, data_interval_end=None):
        # Do some work...
        time.sleep(symbol_info[1])
        return symbol_info

    @task(trigger_rule="one_success")
    def transform(symbol_info, data_interval_end=None):
        # Do some work...
        return symbol_info

    @task(trigger_rule="one_success")
    def load(symbol_info, data_interval_end=None):
        # Do some work...
        return symbol_info

    # DAG
    symbols = get_symbols()
    raw_symbols_data = extract.expand(symbol_info=symbols)
    clean_symbols_data = transform.expand(symbol_info=raw_symbols_data)
    load.expand(symbol_info=clean_symbols_data)


etl_sleep()
```

Looking at the logs I see that with the above code the first task to finish, mapped from `extract`, logs the following:
`[2023-01-29, 09:05:08 UTC] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check`

Or even I have seen some cases in which all the tasks log `0 downstream tasks scheduled`, although the next `transform` task is executed, but only for one mapped index, and not for the 3 that it should.

On the other hand, if I remove the sleep, the first task to finish does log the 3 subsequent `transform` tasks, one for each mapped index:

`[2023-01-29, 09:14:44 UTC] {taskinstance.py:2578} INFO - 3 downstream tasks scheduled from follow-on schedule check`

----
Airflow Version: [v2.5.1](https://pypi.python.org/pypi/apache-airflow/2.5.1)
Git Version: .release:2.5.1+49867b660b6231c1319969217bc61917f7cf9829

**Comment by rubenbriones** [comment] 2023-01-29 09:41
Maybe this [_TODO_](https://github.com/apache/airflow/blob/main/airflow/models/taskinstance.py#L2284) is related to this issue?

**Comment by hussein-awala** [comment] 2023-01-29 18:50
For me it is not a bug, where with `one_success` trigger rule, we execute the task as soon as at least one parent succeeds, and we do not wait for all parents to be done.
In your case the parent tasks are the mapped tasks, so after the success of one of the mapped task, we wait until the next scheduling task, and we take the output of the finished mapped tasks (we have at least one), then we map a task for each output, and the same for the next task.
For your use case, I suggest using the Dynamic Mapping Task Group, to have an etl pipeline for each `symbol` independent of others:
```python
import pendulum
from airflow.decorators import dag, task, task_group


@dag(
    schedule="0 0 * * MON-FRI",
    start_date=pendulum.datetime(2023, 1, 1, tz="UTC"),
    catchup=False,
    max_active_runs=1,
)
def etl_dag():

    @task
    def get_symbols():
        res = [('A', 1, 111), ('B', 2, 222)]
        return res

    @task_group()
    def etl_tg(symbol):
        @task
        def extract(symbol_info, data_interval_end=None):
            # Do some work...
            return symbol_info
        @task
        def transform(symbol_info, data_interval_end=None):
            # Do some work...
            return symbol_info

        @task
        def load(symbol_info, data_interval_end=None):
            # Do some work...
            return symbol_info
        raw_symbols_data = extract(symbol_info=symbols)
        clean_symbols_data = transform(symbol_info=raw_symbols_data)
        return load(symbol_info=clean_symbols_data)

    # DAG
    symbols = get_symbols()
    etl_tg(symbols)

etl_dag()
```

**Comment by eladkal** [comment] 2023-01-31 18:52
I agree with @hussein-awala explnation thus Im closing this issue

**Closed as not planned by eladkal** 2023-01-31 18:52 UTC
Labels: kind:bug, area:core

**Comment by DaveMoreau** [comment] 2024-11-19 22:28
Should there be an expand in the example @hussein-awala gave?

```
    symbols = get_symbols()
    etl_tg.expand(symbols)
```

The update might be useful for people investigating fanning out with expand and there is still a lack of good documentation on organizing more complex fan outs using expand.
