### ISSUE TITLE
Used slots number is greater than the slots threshold fixed

### ISSUE THREAD

**Issue by krazavet** [apache/airflow#1057] opened 2016-02-22 10:43 UTC
Hello,

I have an issue when scheduling some jobs on Airflow. I have limited the number of slots using the UI and created my BashOperators with the same pool name.
However, after several days of runs (without any similar problems), the number of used slots is exceeding the limit as you can see in the screen shot below.

![alt tag](http://img15.hostingpics.net/pics/941853screenshot.png)

How could it be possible that the number of used slots exceeds the number of slots specified ?

**Comment by seibert** [comment] 2016-02-22 16:52
I have noticed this same problem when backfilling a date range with a large number of jobs, some of which shared a pool.

**Comment by mistercrunch** [comment] 2016-02-22 17:21
Which version are you both running? I think this might be addressed in `master`...

**Comment by seibert** [comment] 2016-02-22 17:32
1.6.2

**Comment by seibert** [comment] 2016-02-22 17:32
will try master later today

**Comment by krazavet** [comment] 2016-02-22 17:34
1.6.2 as well

**Comment by r39132** [comment] 2016-02-22 18:05
I saw this issue on the 1.6.2. release version but do not see it in master. I would love to know if you still see it on master.

**Comment by seibert** [comment] 2016-03-09 21:17
I can confirm that I still see this issue (or a similar one) as of master from 16 days ago (forgot to write down the git hash).

In my case it appears to be related to backfilling when there is a task that uses a pool.  My main scheduler is a LocalExecutor and if it is running while I'm backfilling a particular DAG, I'll see the pool oversubscribed. I can work around the problem with this sequence of steps:
- Shut down scheduler
- Use airflow backfill to queue up all the tasks (these tasks share a pool)
- Kill the backfill (which is now waiting for the jobs to complete)
- Start the main scheduler again and watch it start running the queued jobs

**Comment by seibert** [comment] 2016-03-09 22:33
Actually, spoke too soon.  I'm seeing it still exceeding the pool limit.  It's running 8 jobs in a pool with a size of 6.

**Comment by r39132** [comment] 2016-03-23 06:54
The CLI backfill and the scheduler are in fact 2 separate processes and both `schedule` work. As a result, both can read the current queue size and result in oversubscription of the queue. There is a https://github.com/airbnb/airflow/wiki/Roadmap item for this under `Backfill offers a parallel code path to scheduling`

**Comment by syvineckruyk** [comment] 2016-04-10 17:28
+1 facing this as well due to our use of subdags

**Comment by bolkedebruin** [comment] 2016-05-08 13:23
This is being tracked in Jira now.

**Closed as completed by bolkedebruin** 2016-05-08 13:23 UTC
Labels: kind:bug

**Comment by r39132** [comment] 2016-05-09 06:13
@bolkedebruin Do you have the Jira number?

**Comment by bolkedebruin** [comment] 2016-05-09 06:41
AIRFLOW-72 and AIRFLOW-41
