### ISSUE TITLE
Enable keys linked to TaskInstance map_index

### ISSUE THREAD

**Issue by matthewblock** [apache/airflow#24644] opened 2022-06-24 19:42 UTC
#### Background

The new Dynamic Task Mapping feature adds the attribute `map_index` to the `TaskInstance` class. When viewing information for a single mapped task instance, you must select based on this `map_index`, e.g. an integer value `0`, `1`, `2`, ... `n`.

However, task instances can be mapped based on an iterable data type using the `.expand()` - using  a slightly modified [Airflow Simple Mapping example](https://airflow.apache.org/docs/apache-airflow/2.3.0/concepts/dynamic-task-mapping.html#simple-mapping), on a list:

```
added_values = add_one.expand(x=['truck', 'car', 'bicycle'])
```

It is a challenge to view the log for the task instance `add_one` that used the input `'truck'`. In the UI, there is no indication of the element at that index, only the index. In practice, you must click through **all** task instances `[0, 1, 2]` to find the truck log.

#### Proposal

- Parameter for `TaskInstance` that maps `map_index` to a value with meaning i.e. the list element at index `map_index`
- UI updated to show list element, if parameter is provided

### Use case/motivation

I would like the UI to indicate the input element value for each mapped task instance, not the index `map_index`. This will make it easier to navigate mapped task instances. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment] 2022-06-25 03:47
Duplicate of #23020. This feels straightforward in the simplest cases, but can become unweildly quickly. Inputs are much welcomed.

**Closed as not planned by uranusjr** 2022-06-25 03:47 UTC
Labels: kind:feature
