### ISSUE TITLE
Airflow 1.10.7 logs from S3 won't load, just hanging

### ISSUE THREAD

**Issue by aarrtteemmuuss** [apache/airflow#8770] opened 2020-05-07 18:27 UTC
**Apache Airflow version**: 1.10.7

**Environment**: python 3.7, running locally

**What happened**:

I have following configuration in airflow.cfg: 

`remote_logging = True`
`remote_log_conn_id = "S3Connection"`
`remote_base_log_folder = s3://bucket/logs`
`encrypt_s3_logs = False`

I have setup connection in UI with type S3 and following settings: 
`{"aws_access_key_id":"xxx", "aws_secret_access_key": "xxx"}`

Executor is LocalExecutor. Scheduler is able to write logs to S3, but when I open UI to look for task's logs, I can see its just hanging and nothing is happening. The spin spins forever and I can't even see that is the error. 

`http://127.0.0.1:8080/admin/airflow/get_logs_with_metadata?dag_id=example_bash_operator&task_id=run_after_loop&execution_date=2020-05-07T18%3A08%3A51.232255%2B00%3A00&try_number=1&metadata=null` - returns Empty Response Error and nothing works.

Am I doing something wrong? Because S3 configuration is not good documented and I see bunch of reports that it is not working. 

**What you expected to happen**:

I expected logs to be pulled from S3 and shown in UI admin.

**How to reproduce it**:

Install airflow 1.10.7 locally and run any example dag with remote settings enables for S3 bucket.

**Comment by feluelle** [comment] 2020-05-15 11:10
Can you try adding `"region":"your-s3-region"` to the extras and see if this helps?
Or remove the parenthesis from `remote_log_conn_id = "S3Connection"` -> S3Connection. So `S3Connection` is your connection id?

**Comment by feluelle** [comment] 2020-05-15 11:13
You are not using RBAC, right?

**Comment by aarrtteemmuuss** [comment] 2020-05-15 13:18
@feluelle Not using RBAC because it is local setup, not in K8S cluster. 
I have tried adding region and removing quotes - same result, I am actually able to write like I said, but not able to read from S3.

**Comment by aarrtteemmuuss** [comment] 2020-05-15 13:22
@feluelle I am actually using RBAC in k8s cluster, and there I am not even able to write to S3. How are RBAC and S3 logs related?

**Comment by ashb** [comment] 2020-06-03 08:56
@aarrtteemmuuss See also #9118 -- can you try the debug steps there and see if it gives any indication of the problem.

**Comment by eladkal** [comment] 2021-04-16 18:31
@aarrtteemmuuss Since there are no reproduce steps to check the issue and there has been significant changes since you reported the issue I'm closing this.

If you are still experiencing problems after verifying against Airflow 2 + Amazon provider please let us know.

**Closed as completed by eladkal** 2021-04-16 18:31 UTC
Labels: kind:bug, provider:amazon
