### ISSUE TITLE
cannot import name 'resolve_types' from 'attr'

### ISSUE THREAD

**Issue by sephethus** [apache/airflow#12924] opened 2020-12-08 16:33 UTC
**Apache Airflow version**: 1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: Local PC
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04
- **Kernel** (e.g. `uname -a`): 5.4.0-56-generic #62-Ubuntu SMP
- **Install tools**: docker-compose using https://github.com/puckel/docker-airflow
- **Others**:

**What happened**:

Webserver will not start due to airflow error: ImportError: cannot import name 'resolve_types' from 'attr' (/usr/local/lib/python3.7/site-packages/attr/__init__.py)

**What you expected to happen**: 

Webserver start to test dags locally

**How to reproduce it**:

Use the docker-compose container above https://github.com/puckel/docker-airflow.git
Ubuntu 20.04
Run docker-compose up

Error occurs every single time.

Things already tried:

Modified dockerfile to include constraints for Python 3.7 container: --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.7.txt"

Added cattrs==1.0.0

Downgraded pip==20.2.4

Added attrs

None of the above suggestions are working. Anyone able to reproduce this and help solve?

**Comment by turbaszek** [comment] 2020-12-08 22:03
Duplicate of #11965

**Closed as completed by turbaszek** 2020-12-08 22:03 UTC
Labels: kind:bug

**Comment by turbaszek** [comment] 2020-12-08 22:07
Also I would suggest to consider using community supported docker:
```
docker pull apache/airflow:1.10.12-python3.6
```
