### ISSUE TITLE
Scheduler errors when using MSSQL as the backend database

### ISSUE THREAD

**Issue by aneesh-joseph** [apache/airflow#9926] opened 2020-07-22 08:31 UTC
**Apache Airflow version**: 1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

Set MSSQL as the sql connection backend  and examine the airflow scheduler logs

```
[2020-07-22 08:27:16,334] {settings.py:306} DEBUG - Disposing DB connection pool (PID 7714)
Process DagFileProcessor1036-Process:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '1'. (102) (SQLExecDirectW)")
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 159, in _run_file_processor
    pickle_dags)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 1593, in process_file
    paused_dag_ids = models.DagModel.get_paused_dag_ids(dag_ids=dagbag.dag_ids)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 1808, in get_paused_dag_ids
    .filter(DagModel.dag_id.in_(dag_ids))
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '1'. (102) (SQLExecDirectW)")
[SQL: SELECT dag.dag_id AS dag_dag_id 
FROM dag 
WHERE dag.is_paused IS 1 AND dag.dag_id IN (?)]
[parameters: ('test-dag',)]
(Background on this error at: http://sqlalche.me/e/13/f405)

````

**Anything else we need to know**:

**Comment by aneesh-joseph** [comment] 2020-07-22 09:47
got around it by using

```
sed -i 's/DagModel.is_paused.is_(True)/DagModel.is_paused == True/g' /home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py
```

**Comment by potiuk** [comment] 2020-07-22 10:05
Airflow does not support MSSQL officially. Maybe you would like to add tests/support for it in CI @apache/airflow-committers ? WDYT? I think MSSQL comes rather often in the discussions/issues and maybe it's worth to consider official support for it?

**Comment by aneesh-joseph** [comment] 2020-07-22 10:31
sure thing , would love to create a PR  to add MSSQL  into the  CI tests if that's ok

**Comment by Fokko** [comment] 2020-07-22 10:34
Adding it to the CI would be a first step. Curious what we will encounter. I'm all for it.

**Comment by potiuk** [comment] 2020-07-22 11:07
Please @aneesh-joseph  - let's see how we are doing in MS world. And BTW on Github Actions we can even run tests in Windows environment ;)

**Comment by kaxil** [comment] 2020-07-22 11:48
I am against this. We can start supporting many database and maintain many or use/recommend the ones we are very sure about.

As it is MySql has the deadlock issues since a good amount of time, if we start supporting MSSQL we will encounter more issues that we need to solve. 

My opinion would be too only officially support Postgres and MySQL. If users want to use other database they can do it, if they are willing to create a PR and fix it we should definitely accept it. But I am definitely against adding more databases to our test suite.

**Comment by potiuk** [comment] 2020-07-22 12:00
@kaxil - why not try to see how we are doing with the tests first? Maybe that on its own will discourage us from further steps?

Or maybe we find that we have only some limited area to address and maybe we can raise the discussion on devlist and userlist to see how many people are actually already using MSSQL (I have the feeling that people are doing this already - judging from a number of questions and people only reporting rather small issues). 

Maybe it's a good opportunity to run a survey about the DB used which we missed last time?

 We can tie it with the Summit Attendees and get much more meaningful results. I'd only ask those questions:

* What is the DB you are using in production? 
* What is the DB you are using in testing/development?
* Which version? 
* Do you plan migration to different version soon, if yes when and which version?
* If you are not limited to MySQL/Postgres/Sqlite - is there any other SQL Database you would like Airflow to support and why? 


J.

**Comment by kaxil** [comment] 2020-07-22 12:07
> @kaxil - why not try to see how we are doing with the tests first? Maybe that on its own will discourage us from further steps?
> 
> Or maybe we find that we have only some limited area to address and maybe we can raise the discussion on devlist and userlist to see how many people are actually already using MSSQL (I have the feeling that people are doing this already - judging from a number of questions and people only reporting rather small issues).
> 
> Maybe it's a good opportunity to run a survey about the DB used which we missed last time?
> 
> We can tie it with the Summit Attendees and get much more meaningful results. I'd only ask those questions:
> 
> * What is the DB you are using in production?
> * What is the DB you are using in testing/development?
> * Which version?
> * Do you plan migration to different version soon, if yes when and which version?
> * If you are not limited to MySQL/Postgres/Sqlite - is there any other SQL Database you would like Airflow to support and why?
> 
> J.

I am happy for you to take the discussion on the dev list :) - My main concern is we should not try to support everything that users ask for. We need to improve and fix the things that we are already using. MySQL support needs to be improved. Our CI suite is already too big, adding more - means maintaining more. The same time and effort could be used on the core functionalities.

**Comment by kaxil** [comment] 2020-07-22 12:10
And again I am just talking about officially supporting it since SqlAlchemy does support it. Sqlalchmey is a tool designed for supporting and adding more DB specific features. I would rather we or someone who is interested in specific DB help improve those functionalities in SQLAlchemy as that would help the larger community including Airflow.

**Comment by kaxil** [comment] 2020-07-22 12:19
Bear in mind we already need to test Airflow with newer versions of Postgres and MySQL too

Postgres-version: [9.6, 10]
Mysql-version: [5.7]

Soon we should add support for Postgres 12 (maybe drop 9.6 - separate discussion)

Should we add support for MySQL 8 since it was GA since **19 April 2018**

The test suite will keep on increasing.

Same with MSSQL - if we say yes, what versions do we support, should we add support to more versions. The test matrices will keep on increasing.

My recommendation would be to support Postgres and MySQL and improve the support across multiple versions like I mentioned above.

**Comment by potiuk** [comment] 2020-07-22 12:22
I would indeed like to use the survey (I think this is the only way) to just query and ask the community what are their preferences - we do not need to submit to the preferences - but I think right now we have very little data to make conscious decision on all the points you raised (which versions to support, which one drop). I think asking is no harm :).

**Comment by aneesh-joseph** [comment] 2020-07-24 15:56
I have raised a [PR](https://github.com/apache/airflow/pull/9973) to include mssql support with breeze( `./breeze --backend=mssql` )  .This should hopefully make it easier to test locally if anyone wants to contribute fixes for mssql compatibility.

**Comment by kaxil** [comment] 2020-07-24 16:56
Thanks @aneesh-joseph , appreciate it :)

**Comment by jarkkorantala** [comment] 2020-07-27 16:49
Here's another pull request to address this particular issue with SQL Server:
https://github.com/apache/airflow/pull/10019

**Comment by jarkkorantala** [comment] 2020-07-28 09:44
> Here's another pull request to address this particular issue with SQL Server:
> #10019

Looks like #9973 already includes my change. Closing as a duplicate.

**Comment by saryeHaddadi** [comment] 2021-05-03 11:48
Concerning this issue. The part of the query triggering the error is :
`WHERE dag.is_paused IS 1`

As part of [Ms-SQL Doc](https://docs.microsoft.com/fr-fr/sql/t-sql/queries/is-null-transact-sql?view=sql-server-ver15), the IS operator is only to be used with [NULL / NOT NULL].
So, I assume that replacing this part by `dag.is_paused = 1` would fix the issue.

--
As a side node, my company is full Microsoft, and as many companies we need a flexible orchestrator like Airflow. We would also like to have Ms-SQL officially supported. I read the discussion and understood that you can add support for all what users ask for, but I wanted to say it.

We are Okay with Python based tool, Python being the Data Science language, and [Microsoft recently announced](https://devblogs.microsoft.com/python/supporting-the-python-community/) that they "are committed to supporting Python as a first-class language across our products and services."

But in term of internal compentencies, DB management, and IT coherence, we have big reticences to bring in another DB technology.

**Comment by saryeHaddadi** [comment] 2021-05-03 20:50
Hi friends, I can bring you some informations on: `what versions do we support, should we add support to more versions.`

1. In general, ms-sql is quite robust in term of newer versions, in the sense that newer versions do not break old ones, especially since SQL Server 2008-R2.
2. Whatever SQL Server version you are running, you can set, on a Database basis, the [Compatibility Level to a prior version](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-transact-sql-compatibility-level). E.g. for an instance of SQL Server 2016, having multiple DBs inside it, you can set one DB to kind of run with the code/syntax/rules of SQL Server 2012, another with the code/syntax/rules of SQL Server 2014, etc.

→ Targeting an older version of SQL Server = newer versions can generally run it. If anything, the user can always set the compatibility level of his newer SQL Server to target an older version, and the issue is solved.

3. Today, there are still people running older version of (SQL Server 2000!), but those would be for legacy business applications. For an app like Airflow, you can assume that people will use a server not hosting those kind of legacy applications.
4. The easiest would be to test on SQL Server 2016. Having Airflow working on SQL Server 2016 would be super! And I think that all ms-sql folks will get by this. I am not aware of any break since SQL Server 2016 to the last released version (SQL Server 2019).
5. For the sake of informations, here are some major changes with older verions in term of syntax:
- SQL Server 2014: does not support for XML/Json data types, nor some functions such as string splitting, has less support on columnar indexes.
- SQL Server 2012: not aware of major change compared to SQL Server 2014. Don't support columnar indexes.
- SQL Server 2008R2: this version doesn't support analytical functions (count() over (partition by...)).
- There is no point to go further, I don't think that anyone will install Airflow on SQL Server 2008.

Given that Airflow is a 'new' technology, I think that people will modernize themself anyway if using it. SQL Server 2016 is fine for testing.

---
I reflected this afternoon, [as part of the StackOverFlow 2020 surver](https://insights.stackoverflow.com/survey/2020#technology-databases-all-respondents4), SQL Server is the third most used Database, not far away from Postgre.

If we talk only of Relation Databases, the major ones are : MySQL, Postgre, SQL Server, Oracle, MariaDB (DB2 almost not used, and mainly used for legacy mainframe, and SQL lite not a good fit for Airflow Production).

MySQL-MariaDB are kind of similar, the latter is a fork of the other.
Both Postgre & Oracle runs on PL/SQL, even though their might be differences in term of isolation level support.
There remains just SQL Server alone. So there are points of supporting it for the sake of completness of RDBMS support.

However, this has a technical/humain cost, add on that the fact that the Python ecosystem/developpers are more used with Postgre/MySQL. I hope the community will succeed in achieving their major Airflow milestones so that this may give some room & time to add support to SQL Server.

**Closed as completed** 2021-10-08 07:24 UTC
Labels: area:MetaDB, invalid
