### ISSUE TITLE
Details tab blank for Mapped Tasks

### ISSUE THREAD

**Issue by tanmaykansara** [apache/airflow#36690] opened 2024-01-09 16:55 UTC
### Apache Airflow version

2.8.0

### What happened?

The details tab in previous versions had the information about number of tasks running/scheduled/ etc... In 2.8 it is blank

### What you think should happen instead?

Information about tasks running/scheduled/queued should be shown, along with success and failed numbers.

### How to reproduce

![image](https://github.com/apache/airflow/assets/119540699/09a9c202-9cc6-4e34-ab93-401b128e1d72)
When on the mapped tasks task, go to the details tab

### Operating System

EKS Amazon AMI

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by aritra24** [comment] 2024-01-09 19:32
@tanmaykansara could you share any specific steps to repro? I do not see this behaviour on using the [sample](https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/example_dags/example_dynamic_task_mapping.html) dag here on latest main.

**Comment by tanmaykansara** [comment] 2024-01-09 20:02
HI,
here is the code snippet that I can share:

`
def get_work_items_task():
        logger.info(f"secret_name:{secret_name}")
        logger.info(f"bucket={bucket}")
        social_posts_list = []

        # Dynamically import the SQL based on the variable 'sql_to_use'
        sql_module = importlib.import_module(f'includes.sql.update_social_posts.{sql_to_use}')
        if not hasattr(sql_module, 'sql'):
            raise ImportError(f"No SQL found in module {sql_to_use}")
        sql = getattr(sql_module, 'sql')
        logger.info(f"Additional Params:{additional_params}")
        results = snowflake_helpers.select_data_from_snowflake(secret_name, sql, additional_params, dag_id=dag_id, calling_function_name="get_work_items_task")
        chunks = generic_helpers.split_results_into_batches(results, concurrency, batch_size)
        return chunks
@task(multiple_outputs=True, executor_config=executor_config_template, execution_timeout=timedelta(seconds=task_execution_timeout))
    def ingest_data_task(batch):
        logger.info(f"len(batch)={len(batch)}")
        logger.info(batch_size)
        logger.info(f"batch:{batch}")

        

        # Iterate over the 'batch' sequence in increments of 'batch_size'
        for data in batch:
            try:
                id = data[0]
                platform_post_id = data[1]
                platform_url = data[2]
                handle_name = data[3]
                next_scheduled_update = data[4]

                platform_code = ""
                if ('instagram.com' in platform_url):
                    url_short_parts = platform_url.rstrip('/').split('/')
                    platform_code = url_short_parts[-1]

                # ingest social media feed data from the platform for this social post.
                social_ingest_helpers.ingest_social_post_data(
                   bunch_of_params
                )
            except Exception as ex:
                exception_message = str(ex)
                exception_name = ex.__class__.__name__
                stack_trace = traceback.format_exc()

                error_logger.add_error_to_list(
                    error_logger.create_error_entry
                    (
                        "ERROR", dag_id, 
                        "ingest_data_task",
                        error_logger_name,
                        exception_message, exception_name, stack_trace,
                        json.dumps(data)
                ))
        
            #Log all errors to Snowflake that have already been added to the error_loggers internal list of errors.
            error_logger.log_errors_to_snowflake(core_database, secret_name)

        return {
            'status': 'complete'
        }`

`get_work_items = get_work_items_task()
    ingest_data = ingest_data_task.partial().expand(batch=get_work_items)`
    
    When I see the details tab of the mapped task, it is blank. In 2.7, I did see the stats for the job. 
    Hope this helps

**Comment by eladkal** [comment] 2024-01-09 20:06
duplicate of https://github.com/apache/airflow/issues/36481
it's already solved in main and will be fixed in 2.8.1

**Closed as not planned by eladkal** 2024-01-09 20:06 UTC
Labels: kind:bug, pending-response, area:core, needs-triage
