### ISSUE TITLE
show_trigger_form_if_no_params allows to trigger without params even when params required

### ISSUE THREAD

**Issue by kmehkeri** [apache/airflow#37379] opened 2024-02-13 09:37 UTC
### Apache Airflow version

2.8.1

### What happened?

For show_trigger_form_if_no_params=False (default) the trigger form is only shown when any params are present.

I wanted to have an option to override logical date for a paramless DAG, so I set show_trigger_form_if_no_params=True. However now, instead of just showing the form, clicking on trigger displays a small combo "Trigger DAG" / "Trigger DAG w/ config".

### What you think should happen instead?

Trigger form should be always shown. Just as the option says.

### How to reproduce

Set how_trigger_form_if_no_params=False in configuration. Trigger DAG from UI.

### Operating System

Using official Airflow Docker image in standalone mode

### Versions of Apache Airflow Providers

Standard as of official Docker image.

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by kmehkeri** [comment] 2024-02-13 10:53
Hm... I just realized this is a reverse of #33392. 

If a trigger form was shown for DAGs that have params it was important for me and my users to get exactly same experience with paramless DAGs - even if there are no params they can just have a quick look and confirm triggering. And sometimes I want to override logical date or run id.

However having that selection: with or without config... they're confused. Sometimes triggering a DAG that requires params without params just because it was the first choice in the combo. It's way better to just show the form where it's clear what params are needed, if any.

I will surely educate users, but I would still argue about at least having third option for this setting. I would be happy to contribute if you agree it's a good way to proceed. The only concern I could have is switching the option from simple boolean to three-state.

**Comment by Taragolis** [comment] 2024-02-13 11:47
If I understand correctly than https://github.com/apache/airflow/pull/37063 should resolve which should be part of Airflow 2.8.2.

I've check in `main`, if you try to trigger DAGRun without the parameters and parameters are mandatory, then it redirect to form.

**Comment by Taragolis** [comment] 2024-02-13 11:55
> I will surely educate users, but I would still argue about at least having third option for this setting. I would be happy to contribute if you agree it's a good way to proceed. The only concern I could have is switching the option from simple boolean to three-state.

If you see how it could be improved feel free to raise a PR, (see [Contributions Docs](https://github.com/apache/airflow/tree/main/contributing-docs)). Discussion around some implementation would be better rather than abstract.

**Comment by jscheffl** [comment] 2024-02-14 22:28
Yes, agree to @Taragolis - this seems to be 99% a duplicate of #36843 which is fixed in 2.8.2.

Also take note that the logical date and run_id fiel now has moved into the lower "generated configuration" section as it was confusing most users.

If you want more or specific things, then current functions cal always be extended via a contribution if it is generic and can be used by others as well. This is how the form feature initially was introduced.

**Closed as completed by jscheffl** 2024-02-14 22:28 UTC
Labels: kind:bug, duplicate, area:UI
