### ISSUE TITLE
Prioritize tasks based on execution_date

### ISSUE THREAD

**Issue by PrincipalsOffice** [apache/airflow#24381] opened 2022-06-10 18:14 UTC
### Description

A config that lets the scheduler choose tasks with the latest/oldest execution_date to run first. Or perhaps a way to dynamically assign pool slots based on the execution_date could also work.

### Use case/motivation

Sometimes the same task can have multiple task instances from different dag runs queued and occupying pool slots. The task instance from the most recent dag run could have a higher priority than the older ones. Currently there is no way to prioritize that.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2022-06-12 11:37
duplicate of https://github.com/apache/airflow/issues/9176

**Closed as not planned by eladkal** 2022-06-12 11:37 UTC
Labels: kind:feature, duplicate

**Comment by PrincipalsOffice** [comment] 2022-06-20 18:53
@eladkal So currently there is no walkaround to prioritize tasks from the latest dag_run?

**Comment by potiuk** [comment] 2022-06-20 20:14
> @eladkal So currently there is no walkaround to prioritize tasks from the latest dag_run?

No.
