### ISSUE TITLE
Unable to pass {username} with slashes to Airflow REST API

### ISSUE THREAD

**Issue by wilsonhooi86** [apache/airflow#39887] opened 2024-05-28 05:45 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.8.1

### What happened?

MWAA has [announced ](https://aws.amazon.com/blogs/big-data/introducing-amazon-mwaa-support-for-the-airflow-rest-api-and-web-server-auto-scaling/)that we can now use Airflow REST API. The goal is to use [REST API Patch User](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/patch_user) to add/remove users' roles programmatically. 

MWAA create username with a prefix of `assumed-role/` for each user login. Example {username}: `assumed-role/user1` . 

API Template URL: https://airflow.apache.org/auth/fab/v1/users/assumed_role/{username}
Actual URL: https://airflow.apache.org/auth/fab/v1/users/assumed_role/assumed-role/user1

As we call the Airflow REST API https://airflow.apache.org/auth/fab/v1/users/assumed_role/assumed-role/user1 , it will show below error:

```
{
"detail": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.",
"status": 404,
"title": "Not Found",
"type": "about:blank"
}
```
We believe the REST API render the slash as an URL path. 

Question is, can we enhance the Airflow REST API to accept slashes in URL parameter?

### What you think should happen instead?

Airflow REST API able to accept slashes in URL parameter. Example:
username: `assumed-role/user1`
https://airflow.apache.org/auth/fab/v1/users/assumed-role/user1

### How to reproduce

Please refer to What Happened? section

### Operating System

MWAA

### Deployment

Amazon (AWS) MWAA

### Deployment details

I am not sure that this issue is specific to the service provider.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment] 2024-05-31 15:16
> Airflow REST API able to accept slashes in URL parameter. Example:

It shouldn't. `/` have a special meaning for separate paths in URI.
Instead of that it should work with url-encoded values, did you try to provide `assumed-role%2Fuser1` instead?

**Comment by wilsonhooi86** [comment] 2024-06-18 04:17
> > Airflow REST API able to accept slashes in URL parameter. Example:
> 
> It shouldn't. `/` have a special meaning for separate paths in URI. Instead of that it should work with url-encoded values, did you try to provide `assumed-role%2Fuser1` instead?

Hi @Taragolis , yes, I tried to pass in as `assumed-role%2Fuser1`  but it still parse as "/" in the url and produce the same error as below:

```
{
"detail": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.",
"status": 404,
"title": "Not Found",
"type": "about:blank"
}
```

**Comment by jaklan** [comment] 2024-07-26 19:16
@Taragolis any hints how to resolve that issue? Also encounter that problem on MWAA because of `assumed-role/` prefix

**Comment by uranusjr** [comment] 2024-08-02 02:39
IIRC this is a restriction in WSGI and shared by many Python web frameworks, including Flask (backing Airflow) https://github.com/pallets/flask/issues/900

There’s probably no good way to resolve this from the webserver level.

**Comment by jaklan** [comment] 2024-08-02 03:58
@uranusjr if usernames wish slashes are not supported by API (and won't be), they should be simply not supported at all then

**Comment by uranusjr** [comment] 2024-08-07 10:07
I just checked and it seems like even ASGI frameworks have this issue too. ASGI has since added `raw_path` to support this, but FastAPI is not using it when routing requests. (More accurately, Starlette is the layer that actually handles routing.) So I think we’ll have to consider this as impossible at least for the foreseeable future.

I’ll close this and propose a PR to add a note in the documentation.

**Closed as not planned by uranusjr** 2024-08-07 10:07 UTC
Labels: kind:bug, area:API, pending-response, area:core

**Comment by uranusjr** [comment] 2024-08-07 10:12
The problem is the username can be supplied from anywhere (the auth manager is pluggable), and the username is only unusable from the REST API. I anticipate many people are already using those usernames “just fine” from the Airflow UI, and disallowing them would break all their setups.
