### ISSUE TITLE
SFTPHook cannot download large files

### ISSUE THREAD

**Issue by randr97** [apache/airflow#16286] opened 2021-06-06 10:44 UTC
**Apache Airflow version**: 2.0.1 (Should apply to previous versions and later ones as well)

**Environment**:

- **Cloud provider or hardware configuration**: AWS, EC2 c5.xlarge
- **OS** (e.g. from /etc/os-release): ubuntu 18.04

**What happened**:
In `airflow.providers.sftp.hooks.sftp.SFTPHook`, when we try to download a file greater than 18 MiB, the download keeps happening forever and never gets completed.

**What you expected to happen**:
The download should have completed in seconds but did not. A file less than 18MiB gets downloaded in few seconds.
Looks like this is an underlying issue in the `paramiko` library. 
Attaching a bunch of issues on paramiko's git and stackoverflow -
1. https://github.com/paramiko/paramiko/issues/926
2. https://stackoverflow.com/questions/12486623/paramiko-fails-to-download-large-files-1gb
3. https://stackoverflow.com/questions/3459071/paramiko-sftp-hangs-on-get

**How to reproduce it**:
1. Create a large file size > 18MiB
2. Dump it in an SFTP server
3. Use airflow SFTPHook to download it
4. You should be able to see the task run forever

**Anything else we need to know**:
I after exploring found a solution to the problem and have fixed it in my project but if the community can dive deep it would be great.
Link to the solution is - https://gist.github.com/vznncv/cb454c21d901438cc228916fbe6f070f
This gist is by @vznncv and credits to him for coming up with a solution.

**Comment by potiuk** [comment] 2021-06-06 12:16
Maybe we should consider rewriting the hook using Twisted? It sems all APIs needed are there https://twistedmatrix.com/documents/current/api/twisted.conch.ssh.filetransfer.FileTransferClient.html, Twisted seems to be a bit more modern with the async approach and the bug in paramiko seems to be around since 2017.

**Comment by randr97** [comment] 2021-06-06 12:29
@potiuk that would be definitely a good place to start. How do you want to go about this? I would definitely want to contribute to this.

**Comment by potiuk** [comment] 2021-06-06 12:43
> @potiuk that would be definitely a good place to start. How do you want to go about this? I would definitely want to contribute to this.

I do not think there is anything special needed. Just rewrite the Hook/Operator, starting with replacing the twisted library in setup.py deps instead of paramiko/sftp. Then we can relase a major release of SFTP provider with it. That's pretty much it :)

**Comment by randr97** [comment] 2021-06-06 12:57
@potiuk will take some time out and start working on the PR. Thanks

**Comment by malthe** [comment] 2021-06-14 11:51
@potiuk what about https://github.com/ParallelSSH/parallel-ssh#sftp – ?

**Comment by ashb** [comment] 2021-06-14 12:18
I'd probably caution against introducing twisted -- with Python 3.6/3.7+ the built in asyncio can do most of twisted without the need for a large external dependency.

**Comment by potiuk** [comment] 2021-06-14 12:37
Agree with @ashb . Parallel-ssh looks better as well. Seems rather popular from the number of forks, has very little number of dependencies (gevent, python-ssh2). Not super active (but what activity you'd expect from such library?).

**Comment by uranusjr** [comment] 2021-06-15 12:27
Note that parallel-ssh is not small either (mainly because it ships it own copy of `libssh` and `libssh2`).

```
$ pip wheel -w tw twisted
...
$ pip wheel -w ps parallel-ssh
...
$ du -s tw ps
4336    tw
18132   ps
```

Parallel-ssh is over four times larger than Twisted if dependencies are considered.

**Comment by potiuk** [comment] 2021-06-15 17:30
Hmm :( tough choice :)

**Comment by malthe** [comment] 2021-06-15 19:53
@uranusjr you can build it from source, against system-provided libraries.

**Comment by randr97** [comment] 2021-06-27 15:51
I think this solution [Link](https://gist.github.com/vznncv/cb454c21d901438cc228916fbe6f070f) can be a fix without really changing any libraries... Have been using it for sometime and haven't gotten into any issues till now! What do you guys think?

**Comment by potiuk** [comment] 2022-07-03 13:44
Seems that the issue might be closed in the upcoming sftp provider.

**Closed as completed by potiuk** 2022-07-03 13:44 UTC
Labels: kind:bug, area:providers

**Comment by agreenburg** [comment] 2023-01-23 21:00
I'm still encountering this issue with the new provider (which uses paramiko).

I see some workarounds in this thread but the issue is still open: https://github.com/paramiko/paramiko/issues/926
