### ISSUE TITLE
Issue with fetching log file via download button

### ISSUE THREAD

**Issue by amirsh-mb** [apache/airflow#32800] opened 2023-07-24 10:29 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Every time i try to press the download button in a specific task log page, the entire web server crashes
Probably due to log file being too large
```
Jul 24 10:17:30 ip-172-31-64-75 systemd[1]: airflow-webserver.service: A process of this unit has been killed by the OOM killer.
Jul 24 10:18:01 ip-172-31-64-75 systemd[1]: airflow-webserver.service: Failed with result 'oom-kill'.
Jul 24 10:18:01 ip-172-31-64-75 systemd[1]: airflow-webserver.service: Consumed 8min 6.981s CPU time.
Jul 24 10:18:06 ip-172-31-64-75 systemd[1]: airflow-webserver.service: Scheduled restart job, restart counter is at 1.
Jul 24 10:18:06 ip-172-31-64-75 systemd[1]: Stopped Airflow webserver daemon.
Jul 24 10:18:06 ip-172-31-64-75 systemd[1]: airflow-webserver.service: Consumed 8min 6.981s CPU time.
```

### How to reproduce

Happens every time i click the download button on a specific task which is probably has the biggest logs

### Operating System

Ubuntu 22.04.2 LTS

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by phanikumv** [comment] 2023-07-25 07:21
cc @bbovenzi

**Comment by amir-brightdata** [comment] 2023-07-25 15:18
Hi, here is a bit of info:
- If you are talking about the server's physical memory it was 4GB at the start but since we got that error we increased it to 16GB but it still happened, and if you are talking about configuration limits, we haven't tweaked anything so its probably default.
-We are storing the logs on s3 but this issue is when loading the log from the local storage.
- our logs are usually 50MB but this one was 1GB somehow, usually the worst we experienced are just 2 minute load times, never crashes.

**Comment by jens-scheffler-bosch** [comment] 2023-07-31 20:06
Okay, I can re-produce this problem. I created an artificial large log file with ~110MB. First I copied it many/multiple times from the same "real" log file and saw that logs are sorted by time stamp.
Then I created a dummy content w/o timestamp large log volume of ~110MB and could re-produce the root cause.

Root cause for file served logs (might be similar in other log handlers) is in: airflow/utils/log/file_task_handler.py:_interleave_logs()
This function tries to merge different log files (if found with the same file pattern) and therefore loads all file content and sorts the lines. For (very) large log files this causes a very high CPU and memory load. I could see memory of the webserver Python process is going up by ~factor 6 of the original log volume., So my flash webserver peaked from 390MB to 990 MB of memory.
If not memory will kill with, with ~1GB log file I assume this is killing the web worker because of timeout in flask.

Same code is walked irrespective of logs streaming is made to Web UI (You can see the browser with ~100MB also takes a while to render the page :-D) but also when downloading the log. FileTaksHandler does not just stream the file burt really sorts and merges the content.

So: I assume this sorting&merging is a nice feature for UI but does not scale. In case of large log file the "raw" file must be streamed to just pass the data through _or_ log download must be limited - else this might be an option to make a DoS on the webserver when authenticated.

**Comment by jens-scheffler-bosch** [comment] 2023-07-31 21:03
Duplicate of #31105

**Closed as completed** 2023-08-01 20:10 UTC
Labels: kind:bug, area:webserver, duplicate, area:UI
