### ISSUE TITLE
If the DAG contains Tasks Goups, Graph view does not properly display tasks statuses

### ISSUE THREAD

**Issue by enguerranchevalier** [apache/airflow#18369] opened 2021-09-20 09:27 UTC
### Apache Airflow version

2.1.4 (latest released)

### Operating System

Linux/Debian

### Deployment

Official Apache Airflow Helm Chart

### What happened

When upgrading to latest release (2.1.4) from 2.1.3, Graph View does not properly display tasks statuses.

See:

![image](https://user-images.githubusercontent.com/12841394/133980917-678a447b-5678-4225-b172-93df17257661.png)

All these tasks are in succeed or failed status in the Tree View, for the same Dag Run.

### What you expected to happen

Graph View to display task statuses.

### How to reproduce

As I can see, DAGs without tasks groups are not affected. So, probably just create a DAG with a task group. I can reproduce this with in local with the official docker image (python 3.8).

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by enguerranchevalier** [comment] 2021-09-20 09:32
Maybe it's related to `https://github.com/apache/airflow/pull/17821`?

**Comment by bbovenzi** [comment] 2021-09-21 09:19
I'm trying to replicate this issue without success. Could you provide a bit more info?

- It is a running dag run and Is auto-refresh on?
- Are task groups closed when loading the page and you are expanding them or are they already expanded on page load?
- Does manually refreshing the page change anything?

**Comment by enguerranchevalier** [comment] 2021-09-21 16:37
Hello @bbovenzi, thanks for your response!

* Bug appears both with running or non-running DAGs;
* Task groups are opened when loading the page, and indeed, the bug does not occur when task groups are closed when loading the graph view;
* Manually refreshing the page does not change this behaviour.

I also notice that the tooltip is not displayed on the concerned tasks.
When I close and re-open the task group, the status is displayed immediately (see below).

![Uploading Peek 21-09-2021 18-35.gif…]()

**Comment by Limess** [comment] 2021-09-23 10:38
We're also experiencing this issue since upgrading. Closing and opening a task group fixes the issue as suggested.

**Comment by foldvari** [comment] 2021-09-24 15:29
If there are multiple task groups in the workflow, you need to close all of them to get back the statuses.

**Comment by bbovenzi** [comment] 2021-09-27 09:39
I'm still having issues replicating this on my end. I have one hunch though, what browsers are people experiencing this on?

**Comment by foldvari** [comment] 2021-09-27 11:11
> I'm still having issues replicating this on my end. I have one hunch though, what browsers are people experiencing this on?

I can reproduce both in Edge (93.0.961.52) and Chrome (94.0.4606.61) 64-bit.

Steps I use to reproduce:

1. Pick a DAG with multiple task groups and has a run already.
2. Open the most recent run in Graph mode.
3. Open two task groups. You see the status colors.
4. Refresh the screen while those task groups are open. Status colors disappear. (Not necessarily all but most of them.)
5. Close all the open task groups to get back the status colors again.

**Comment by enguerranchevalier** [comment] 2021-09-27 13:21
Having this issue with `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0 `.

@bbovenzi @foldvari On my side, the problem also appears with only one task group within the DAG.

**Comment by bbovenzi** [comment] 2021-09-28 15:26
It doesn't appear to be a browser issue. Could you provide a sample DAG that this happens on? I'm sorry, I'm still unable to get this happening locally with any of my Task Group DAGs

**Comment by davidcaron** [comment] 2021-09-29 01:12
We had the same issue in most of our dags (most have task groups, but I didn't realise it could be related)

I think the problem was introduced in https://github.com/apache/airflow/pull/17821/commits/abc68d05ab3d579afa4c2bbbb5cdb701a7ecd7e9 

https://github.com/apache/airflow/blob/21870080e90fed06f6a617ce05c338c276106d71/airflow/www/static/js/graph.js#L473

When I change this line to `continue` instead of `return`, it fixes the issue. I'm not so sure what that implies as the intention of the PR was to improve performance and I'm not familiar enough with the code to comment about that.

**Comment by JCoder01** [comment] 2021-09-29 02:56
@bbovenzi 
Clone repo
run `./breeze start-airflow --load-example-dags --use-airflow-version 2.1.4`
enable example_task_group and wait for dag to run
open up graph view
expand task group
refresh page

![image](https://user-images.githubusercontent.com/651639/135195380-73ec64b0-4ba5-4fb4-ad95-5ac04337fc83.png)

**Comment by bbovenzi** [comment] 2021-09-29 07:12
@davidcaron yeah, that appears to be it. Do you want to open a PR to change it to `continue`?

**Closed as completed** 2021-09-29 16:30 UTC
Labels: kind:bug, area:core, area:UI
