### ISSUE TITLE
Task ID copy button copying wrong ID

### ISSUE THREAD

**Issue by ByPort** [apache/airflow#34846] opened 2023-10-10 12:22 UTC
### Apache Airflow version

2.7.1

### What happened

The Task ID copy button in Grid View copies the first Task ID copied until the page refresh

### What you think should happen instead

The corresponding Task ID should be copied

### How to reproduce

1. Go to Grid view and open any task
2. Click the copy button in front of the Task ID
3. The ID in the clipboard is correct
4. Open another task
5. (optional) Copy any stuff to reset the clipboard
6. Click the copy button again
7. The ID in the clipboard is the ID from Step 2

In any other task, the first Task ID (from Step 2) will be copied until the page is refreshed

### Operating System

Mac OS (ARM)

### Deployment

Docker-Compose

### Anything else

It occurs every time in the latest Chrome browser

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Adaverse** [comment] 2023-10-12 22:19
Nice catch. The problem is that the component responsible for copying won't re-render (which is the expectation looking at the current code). Hence we need to explicitly set the value that needs to be copied when it changes. Will raise a PR.

**Comment by AchimGaedkeLynker** [comment] 2023-12-20 09:18
Any chance resolving this soon?

**Comment by potiuk** [comment] 2023-12-20 11:03
> Any chance resolving this soon?

There is a PR linked it seems - commenting there, helping with reviews, cherry-picking and testing and confirming that it works is the best way you can help with getting it out faster (In case what you are really asking about is  "how can I help to speed it up?")  @AchimGaedkeLynker

**Comment by AchimGaedkeLynker** [comment] 2023-12-20 19:35
Will try my best on my weakest domain of software engineering: JS in web browsers.

**Closed as completed** 2024-01-16 22:10 UTC
Labels: kind:bug, good first issue, area:UI, _eol_affected_version:2.7
