### ISSUE TITLE
initdb command failed with table exists error

### ISSUE THREAD

**Issue by hangelwen** [apache/airflow#988] opened 2016-02-11 00:25 UTC
When I run airflow initdb, I got the following error. I installed version 1.6.2 from pypi. Could someone help? Thanks.

[2016-02-11 00:17:28,990] {**init**.py:36} INFO - Using executor SequentialExecutor
DB: sqlite:////home/jlei/airflow/airflow.db
[2016-02-11 00:17:29,103] {utils.py:275} INFO - Creating tables
INFO  [alembic.migration] Context impl SQLiteImpl.
INFO  [alembic.migration] Will assume non-transactional DDL.
INFO  [alembic.migration] Running upgrade 1b38cef5b76e -> 2e541a1dcfed, task_duration
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 15, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/airflow/bin/cli.py", line 385, in initdb
    utils.initdb()
  File "/usr/local/lib/python2.7/site-packages/airflow/utils.py", line 168, in initdb
    upgradedb()
  File "/usr/local/lib/python2.7/site-packages/airflow/utils.py", line 282, in upgradedb
    command.upgrade(config, 'heads')
  File "/usr/local/lib/python2.7/site-packages/alembic/command.py", line 165, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/site-packages/alembic/script.py", line 390, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/site-packages/alembic/util.py", line 243, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/site-packages/alembic/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/usr/local/lib/python2.7/site-packages/airflow/migrations/env.py", line 74, in <module>
    run_migrations_online()
  File "/usr/local/lib/python2.7/site-packages/airflow/migrations/env.py", line 69, in run_migrations_online
    context.run_migrations()
  File "<string>", line 7, in run_migrations
  File "/usr/local/lib/python2.7/site-packages/alembic/environment.py", line 742, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/site-packages/alembic/migration.py", line 309, in run_migrations
    step.migration_fn(**kw)
  File "/usr/local/lib/python2.7/site-packages/airflow/migrations/versions/2e541a1dcfed_task_duration.py", line 26, in upgrade
    existing_nullable=True)
  File "/usr/local/lib/python2.7/contextlib.py", line 24, in **exit**
    self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/alembic/operations.py", line 320, in batch_alter_table
    impl.flush()
  File "/usr/local/lib/python2.7/site-packages/alembic/batch.py", line 74, in flush
    batch_impl._create(self.impl)
  File "/usr/local/lib/python2.7/site-packages/alembic/batch.py", line 199, in _create
    op_impl.create_table(self.new_table)
  File "/usr/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 181, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 105, in _exec
    return conn.execute(construct, _multiparams, *_params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 895, in _execute_ddl
    compiled
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (OperationalError) table _alembic_batch_temp already exists u'\nCREATE TABLE _alembic_batch_temp (\n\ttask_id VARCHAR(250) NOT NULL, \n\tdag_id VARCHAR(250) NOT NULL, \n\texecution_date DATETIME NOT NULL, \n\tstart_date DATETIME, \n\tend_date DATETIME, \n\tduration FLOAT, \n\tstate VARCHAR(20), \n\ttry_number INTEGER, \n\thostname VARCHAR(1000), \n\tunixname VARCHAR(1000), \n\tjob_id INTEGER, \n\tpool VARCHAR(50), \n\tqueue VARCHAR(50), \n\tpriority_weight INTEGER, \n\toperator VARCHAR(1000), \n\tqueued_dttm DATETIME, \n\tPRIMARY KEY (task_id, dag_id, execution_date)\n)\n\n' ()

**Comment by r39132** [comment] 2016-02-11 02:36
Can you verify that your airflow home is set correctly in the ENV var? I suspect this is caused by 2 different set of migrations running from 2 different airflow installs. 

Also, is your issue resolved by a `airflow resetdb`? If you have a fresh install, `airflow resetdb` will likely resolve it. 

-s

**Comment by r39132** [comment] 2016-02-15 20:15
Closing for lack of activity. Please ping me (cc me) if you have more information.

**Closed as completed by r39132** 2016-02-15 20:15 UTC
Labels: Can't Reproduce
