### ISSUE TITLE
Calendar error in Tutorial DAG

### ISSUE THREAD

**Issue by bervel** [apache/airflow#29553] opened 2023-02-15 09:06 UTC
### Apache Airflow version

2.5.1

### What happened

Once you run the Tutorial DAG, it' calendar tab does not open, returns an error.

From system out:
```
airflow-airflow-webserver-1  | Traceback (most recent call last):
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
airflow-airflow-webserver-1  |     response = self.full_dispatch_request()
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
airflow-airflow-webserver-1  |     rv = self.handle_user_exception(e)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
airflow-airflow-webserver-1  |     rv = self.dispatch_request()
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
airflow-airflow-webserver-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/auth.py", line 47, in decorated
airflow-airflow-webserver-1  |     return func(*args, **kwargs)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/decorators.py", line 166, in view_func
airflow-airflow-webserver-1  |     return f(*args, **kwargs)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/decorators.py", line 125, in wrapper
airflow-airflow-webserver-1  |     return f(*args, **kwargs)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
airflow-airflow-webserver-1  |     return func(*args, session=session, **kwargs)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/views.py", line 2756, in calendar
airflow-airflow-webserver-1  |     if curr_info.logical_date <= prev_logical_date:
airflow-airflow-webserver-1  | TypeError: can't compare offset-naive and offset-aware datetimes
airflow-airflow-webserver-1  | 172.18.0.1 - - [15/Feb/2023:09:04:55 +0000] "GET /dags/tutorial/calendar HTTP/1.1" 500 1544 "http://localhost:8080/dags/tutorial/grid" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
```

### How to reproduce

Run Tutorial, open Calendar tab.

### Operating System

Ubuntu (WSL)

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by josh-fell** [comment] 2023-02-15 15:27
Hi @bervel, this is a duplicate of #29227. Closing this issue, but please let us know if you are experiencing this issue with a different scenario.

**Closed as not planned by josh-fell** 2023-02-15 15:27 UTC
Labels: kind:bug, area:core
