### ISSUE TITLE
apache-airflow installed from pip fails with sqlalchemy (1.4.6)

### ISSUE THREAD

**Issue by ghost** [apache/airflow#15371] opened 2021-04-14 15:41 UTC
**Apache Airflow version**:  2.0.1

**Environment**:

- **Cloud provider or hardware configuration**:  Google Cloud Platform Compute Engine
- **OS** (e.g. from /etc/os-release): NAME="Ubuntu" VERSION="20.04.2 LTS (Focal Fossa)"
- **Kernel** (e.g. `uname -a`): Linux finance-airflow 5.4.0-1041-gcp #44-Ubuntu SMP Fri Mar 26 03:53:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: pip

**What happened**:

Installed with usual `pip install apache-airflow` which installed `sqlalchemy 1.4.6`, since `apache-airflow 2.0.1` requires `sqlalchemy<2,>=1.3.18`

Ran:

`airflow db init` 

`from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/home/foo/airflow/.direnv/python-3.8.5/lib/python3.8/site-packages/sqlalchemy/orm/query.py)`

**What you expected to happen**:

Initializing `sqlite3` database for testing

**How to reproduce it**:

`pip install apache-airflow` on Ubuntu 20.04.2 LTS

**Anything else we need to know**:

Downgraded `sqlalchemy` via `pip install --upgrade sqlalchemy==1.3.18`, which lets database initialize, but one expects dependencies to be handled by `setup.py`. Suggest updating `setup.py` for `apache-airflow` version in `pypi`.

**Comment by ashb** [comment] 2021-04-14 15:57
Duplicate of #14811 -- and see https://github.com/apache/airflow/issues/14811#issuecomment-802250526 specifically

**Comment by ashb** [comment] 2021-04-14 15:57
(And this has already been pinned in setup.py for what will be 2.0.2)

**Closed as completed by ashb** 2021-04-14 15:57 UTC
Labels: kind:bug
