### ISSUE TITLE
Need a backfill endpoint in REST API

### ISSUE THREAD

**Issue by Felix-neko** [apache/airflow#35266] opened 2023-10-30 08:54 UTC
### Description

Hi folks! And thank you for your great product.

Please, can you add a backfill endpoint in your REST API? We really need this, because its rather tricky to get access to airflow scheduler server to run backfill command in its console.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment] 2023-10-30 09:12
- Duplicate of: https://github.com/apache/airflow/issues/18816

**Closed as completed by Taragolis** 2023-10-30 09:12 UTC
Labels: kind:feature, duplicate

**Comment by potiuk** [comment] 2023-10-30 13:14
Also if you badly need it - consider contributing it @Felix-neko or your company paying someone to work on it (maybe your company employee or sponsoring someone who is familiar with Airflow contribution).

If you look at the linked issue, having a backfill implemented in UI or through REST API basically means turning one of the components of Airflow into a robust "runner" of such backfill request.  This is rather complex feature requiring likely Airflow Improvement Proposal to be proposed, approved and voted and rather complex/robust implementation of backed (handling all the edge cases like restarting components, handling deadlocks and a number of cases that need to be detailed in the AIP).

So finding a way how to contribute back for the free software is a great idea (certainly one that might speed up the time needed to do so).
