### ISSUE TITLE
dagrun_timeout is broken!

### ISSUE THREAD

**Issue by kretes** [apache/airflow#990] opened 2016-02-11 08:15 UTC
Full environment is at https://github.com/kretes/docker-airflow/tree/airflow-scheduler-hang-up

A. code

```
from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators import BashOperator, DummyOperator

dag = DAG("MYDAG",
          default_args={"owner" : "me",
                        "start_date":datetime.now() - timedelta(minutes=100)},
          schedule_interval='*/3 * * * *',
          concurrency=6,
          dagrun_timeout=timedelta(minutes=4)
          )

def command():
    return "echo {{ params.myparam }} {{ (execution_date - macros.timedelta(hours = 1)).strftime('%Y/%m/%d %H %M') }} 2>&1 >> /tmp/logs"

run_this_last = DummyOperator(task_id='run_this_last', dag=dag)

firstTask = BashOperator(
        task_id='first',
        bash_command=command(),
        params= {"myparam":"1"},
        dag=dag)
secondTask = BashOperator(
        task_id='second',
        bash_command=command(),
        params= {"myparam":"2"},
        dag=dag)

firstTask.set_downstream(secondTask)
secondTask.set_downstream(run_this_last)
```

B. DAG:
![dag_view](https://cloud.githubusercontent.com/assets/1224887/12971756/e01af87e-d09e-11e5-98ba-2bafe3f714a1.png)

C. I start airflow (whole environment with docker)

D. after some time scheduler stops executing full dag:
![dag_tree_failed](https://cloud.githubusercontent.com/assets/1224887/12971829/927e2202-d09f-11e5-9d47-f3bf50cde276.png)

logs from the first 'error' run:

```
scheduler_1 | [2016-02-11 08:09:03,024] {jobs.py:507} INFO - Prioritizing 0 queued jobs
scheduler_1 | [2016-02-11 08:09:03,031] {models.py:197} INFO - Importing /usr/local/airflow/dags/thourly.py
scheduler_1 | [2016-02-11 08:09:03,034] {models.py:284} INFO - Loaded DAG <DAG: MYDAG>
scheduler_1 | [2016-02-11 08:09:03,063] {models.py:2156} INFO - Checking state for <DagRun MYDAG @ 2016-02-11 08:06:00: scheduled__2016-02-11T08:06:00, externally triggered: False>
scheduler_1 | [2016-02-11 08:09:03,065] {jobs.py:455} INFO - Getting list of tasks to skip for active runs.
scheduler_1 | [2016-02-11 08:09:03,067] {jobs.py:470} INFO - Checking dependencies on 3 tasks instances, minus 0 skippable ones
scheduler_1 | [2016-02-11 08:09:03,077] {base_executor.py:34} INFO - Adding to queue: airflow run MYDAG first 2016-02-11T08:06:00 --local -sd DAGS_FOLDER/thourly.py 
scheduler_1 | [2016-02-11 08:09:03,109] {jobs.py:633} INFO - Done queuing tasks, calling the executor's heartbeat
scheduler_1 | [2016-02-11 08:09:03,110] {jobs.py:636} INFO - Loop took: 0.088226 seconds
scheduler_1 | [2016-02-11 08:09:03,111] {models.py:222} INFO - Finding 'running' jobs without a recent heartbeat
scheduler_1 | [2016-02-11 08:09:03,111] {models.py:228} INFO - Failing jobs without heartbeat after 2016-02-11 08:06:48.111842
scheduler_1 | [2016-02-11 08:09:03,115] {celery_executor.py:62} INFO - [celery] queuing ('MYDAG', 'first', datetime.datetime(2016, 2, 11, 8, 6)) through celery, queue=default
worker_1    | [2016-02-11 08:09:03,424] {__init__.py:36} INFO - Using executor CeleryExecutor
worker_1    | [2016-02-11 08:09:03,962] {__init__.py:36} INFO - Using executor CeleryExecutor
scheduler_1 | [2016-02-11 08:09:08,031] {jobs.py:507} INFO - Prioritizing 0 queued jobs
scheduler_1 | [2016-02-11 08:09:08,036] {models.py:197} INFO - Importing /usr/local/airflow/dags/thourly.py
scheduler_1 | [2016-02-11 08:09:08,038] {models.py:284} INFO - Loaded DAG <DAG: MYDAG>
scheduler_1 | [2016-02-11 08:09:08,088] {jobs.py:455} INFO - Getting list of tasks to skip for active runs.
scheduler_1 | [2016-02-11 08:09:08,088] {jobs.py:470} INFO - Checking dependencies on 0 tasks instances, minus 0 skippable ones
worker_1    | Logging into: /usr/local/airflow/logs/MYDAG/first/2016-02-11T08:06:00
scheduler_1 | [2016-02-11 08:09:08,115] {jobs.py:633} INFO - Done queuing tasks, calling the executor's heartbeat
scheduler_1 | [2016-02-11 08:09:08,115] {jobs.py:636} INFO - Loop took: 0.091296 seconds
scheduler_1 | [2016-02-11 08:09:08,116] {models.py:222} INFO - Finding 'running' jobs without a recent heartbeat
scheduler_1 | [2016-02-11 08:09:08,116] {models.py:228} INFO - Failing jobs without heartbeat after 2016-02-11 08:06:53.116813
scheduler_1 | [2016-02-11 08:09:13,022] {jobs.py:507} INFO - Prioritizing 0 queued jobs
scheduler_1 | [2016-02-11 08:09:13,029] {models.py:197} INFO - Importing /usr/local/airflow/dags/thourly.py
scheduler_1 | [2016-02-11 08:09:13,031] {models.py:284} INFO - Loaded DAG <DAG: MYDAG>
scheduler_1 | [2016-02-11 08:09:13,062] {jobs.py:455} INFO - Getting list of tasks to skip for active runs.
scheduler_1 | [2016-02-11 08:09:13,062] {jobs.py:470} INFO - Checking dependencies on 0 tasks instances, minus 0 skippable ones
scheduler_1 | [2016-02-11 08:09:13,085] {jobs.py:633} INFO - Done queuing tasks, calling the executor's heartbeat
scheduler_1 | [2016-02-11 08:09:13,085] {jobs.py:636} INFO - Loop took: 0.06762 seconds
scheduler_1 | [2016-02-11 08:09:13,086] {models.py:222} INFO - Finding 'running' jobs without a recent heartbeat
scheduler_1 | [2016-02-11 08:09:13,087] {models.py:228} INFO - Failing jobs without heartbeat after 2016-02-11 08:06:58.087064
```
1. Airflow marks DAG as 'failed' with no information in logs nor in UI

**Comment by kretes** [comment] 2016-02-11 08:54
One possible reason for that *might be in https://github.com/airbnb/airflow/blob/master/airflow/jobs.py#L373  where dag is being failed - but is that code ok? In my case there was no actual timeout

There should be at least some logging about the reason of failing the DAG stored in the 'DagRun' object to be viewed in the GUI. and of course in logs.

**Comment by kretes** [comment] 2016-02-11 09:14
I think I can add more to this hypothesis.
Doing 'select \* from dag_run;' on this environment I can see all dag_runs' start_dates are the same - calculated when the dag file was first parsed.
This makes code for timeout verification notice timeout and the dag is failed...

Does this reasoning make sense?

**Comment by r39132** [comment] 2016-02-11 23:14
I have your code running locally against sqllite and sequential executor.

I modified `command` to print out the execution date (not the hour before the execution date):

```
def command():
    return "echo {{ params.myparam }} {{ (execution_date).strftime('%Y/%m/%d %H %M') }} 2>&1 >> /tmp/logs_1"
```

The output looks normal. 

```
sid-as-mbp:dags siddharth$ tail -f /tmp/logs_1
1 2016/02/11 11 58
1 2016/02/11 12 00
1 2016/02/11 12 03
2 2016/02/11 11 58
1 2016/02/11 12 06
2 2016/02/11 12 00
1 2016/02/11 12 09
2 2016/02/11 12 03
1 2016/02/11 12 12
2 2016/02/11 12 06
1 2016/02/11 12 15
2 2016/02/11 12 09
```

<img width="689" alt="screenshot 2016-02-11 13 43 08" src="https://cloud.githubusercontent.com/assets/581734/12991734/6f6b91de-d0c5-11e5-9424-94eac037952b.png">

**Comment by r39132** [comment] 2016-02-11 23:25
Wait.. I might be seeing an issue.  Can you restart your webserver and tell me if this goes away?

I'm seeing the following on the webserver...
```
[2016-02-11 14:25:30,595] {models.py:295} INFO - Loaded DAG <DAG: test_regex_1>
[2016-02-11 14:25:30,595] {models.py:204} INFO - Importing /Users/siddharth/Projects/airflow/dags/test_s3_sensor.py
[2016-02-11 14:25:30,615] {models.py:295} INFO - Loaded DAG <DAG: test_s3_sensor>
[2016-02-11 14:25:30,616] {models.py:204} INFO - Importing /Users/siddharth/Projects/airflow/dags/testdruid.py
[2016-02-11 14:25:30,616] {models.py:295} INFO - Loaded DAG <DAG: test_druid>
[2016-02-11 15:12:31 -0800] [77157] [CRITICAL] WORKER TIMEOUT (pid:80323)
[2016-02-11 15:12:31 -0800] [77157] [CRITICAL] WORKER TIMEOUT (pid:80308)
[2016-02-11 15:12:31 -0800] [77157] [CRITICAL] WORKER TIMEOUT (pid:80309)
[2016-02-11 15:12:31 -0800] [77157] [CRITICAL] WORKER TIMEOUT (pid:80310)
[2016-02-11 15:12:31 -0800] [80323] [INFO] Worker exiting (pid: 80323)
[2016-02-11 15:12:31 -0800] [80308] [INFO] Worker exiting (pid: 80308)
[2016-02-11 15:12:31 -0800] [80309] [INFO] Worker exiting (pid: 80309)
[2016-02-11 15:12:31 -0800] [80310] [INFO] Worker exiting (pid: 80310)
[2016-02-11 15:12:31 -0800] [80986] [INFO] Booting worker with pid: 80986
[2016-02-11 15:12:31 -0800] [80987] [INFO] Booting worker with pid: 80987
[2016-02-11 15:12:31 -0800] [80988] [INFO] Booting worker with pid: 80988
[2016-02-11 15:12:31 -0800] [81006] [INFO] Booting worker with pid: 81006
[2016-02-11 15:12:31,828] {__init__.py:36} INFO - Using executor SequentialExecutor
[2016-02-11 15:12:31,838] {__init__.py:36} INFO - Using executor SequentialExecutor
[2016-02-11 15:12:31,881] {__init__.py:36} INFO - Using executor SequentialExecutor
[2016-02-11 15:12:31,965] {__init__.py:36} INFO - Using executor SequentialExecutor
[2016-02-11 15:12:32,605] {models.py:126} INFO - Filling up the DagBag from /Users/siddharth/Projects/airflow/dags
```
and

```
usr/local/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py:572: SAWarning: Can't resolve label reference 'execution_date desc'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
```

I think I saw the tree view frozen. When I restarted the webserver, it refreshed as all green.

**Comment by r39132** [comment] 2016-02-11 23:30
Also, BTW, I don't use the dag_timeout, but the logic you pointed me is suspicious indeed.
-s

**Comment by kretes** [comment] 2016-02-12 08:13
@r39132 the webserver didn;t have any hiccup here, so we didn't try to mess with him. Furthermore the problem looks deeply inside scheduler, the logs from scheduler say the same.

and yes the dag_timeout is necessary to reproduce the issue - we removed this param on production and everything goes well since then.

**Comment by r39132** [comment] 2016-02-13 06:51
Hi @kretes,
Ok. So, can you confirm a few things for me, since I am unable to reproduce this issue. Are you getting the error because your tasks are taking longer than 4 minutes to run? I don't use celery and am wondering if the combined times of running and some necessary heart beating is exceeding the 4 minutes you have set as a timeout.

**Comment by kretes** [comment] 2016-02-15 09:14
@r39132 no the tasks are simple echos they complete in a few seconds including scheduling overhead.

I think the problem comes from the place in the code I pointed out. It would be good to add some better status for dag fail 'timeouted' instead of a general 'failed' to be sure, though.

When doing 'select \* from dag_run'
I see entries that have start date set to the moment I first 'deployed' this DAG. Therefore the dag run will be timeouted.

Did you try to reproduce the issue by cloning the repo I prepared and running docker-compose there?

**Comment by kretes** [comment] 2016-02-15 09:55
I switched executor to 'local' and the same happens.
First a few dag runs go well but then they freeze (it first happens when dag run ends after a specified dag timeout added to a first start_date of first dag run. see the example when dag timeout was set to 1 minute:

![airflowdagruns](https://cloud.githubusercontent.com/assets/1224887/13045254/9a01ebcc-d3d2-11e5-80f5-34445f8778b8.png)

**Comment by r39132** [comment] 2016-02-15 23:06
Are you running in UTC everywhere?

**Comment by r39132** [comment] 2016-02-16 04:00
I ran your code and reproduced it on the LocalExecutor. Interestingly, I was not able to reproduce it on the SequentialExecutor....

<img width="927" alt="screenshot 2016-02-16 03 59 41" src="https://cloud.githubusercontent.com/assets/581734/13066831/c323b258-d461-11e5-9570-d7f6cc41296c.png">

**Comment by kretes** [comment] 2016-02-16 09:20
I didn't try with the SequentialExecutor,
I'm really happy that you were able to reproduce this issue finally ;-)

**Comment by r39132** [comment] 2016-02-16 16:17
If you can find and fix the bug, I'd be happy to review a PR.

**Comment by r39132** [comment] 2016-02-17 03:37
Here is what I have found. 

I have a modified piece of code (modified from what @kretes) provided. Here is the code : 

```
from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators import BashOperator, DummyOperator

dag = DAG("MYDAG_5",
          default_args={"owner" : "me",
                        "start_date":datetime.now()},
          schedule_interval='*/1 * * * *',
          dagrun_timeout=timedelta(minutes=4)
          )

def command():
    return "echo {{ params.myparam }} {{ (execution_date).strftime('%Y/%m/%d %H %M') }} 2>&1 >> /tmp/logs"

run_this_last = DummyOperator(task_id='run_this_last', dag=dag)

firstTask = BashOperator(
        task_id='first',
        bash_command=command(),
        params= {"myparam":"1"},
        dag=dag)
secondTask = BashOperator(
        task_id='second',
        bash_command=command(),
        params= {"myparam":"2"},
        dag=dag)

firstTask.set_downstream(secondTask)
secondTask.set_downstream(run_this_last)
```

I loaded this new DAG around `02-17T03:22:47.319562`

When the DAG starts, it fails due to the DAGRUN_TIMEOUT!
<img width="610" alt="screenshot 2016-02-17 03 26 06" src="https://cloud.githubusercontent.com/assets/581734/13099028/3682376e-d526-11e5-8eb0-5929d8eea9e7.png">

Looking at the DAG run view, I see the following : 
<img width="889" alt="screenshot 2016-02-17 03 26 59" src="https://cloud.githubusercontent.com/assets/581734/13099041/58d51570-d526-11e5-904f-20c0037956c3.png">

As you can see, it has failed almost immediately after starting. Each and every run fails!

Looking at the DAG run table, I see the following : 
<img width="888" alt="screenshot 2016-02-17 03 28 42" src="https://cloud.githubusercontent.com/assets/581734/13099069/938d0628-d526-11e5-867e-21ba736c0ed8.png">

It looks like the problem is that the start date is set 8 hours behind the execution date!

I loaded the DAG `02-17T03:22:47.319562` and my schedule is minutely, but the start_dates are set to '2016-02-16 19:23:02.289377', which is 8 hours behind the current datetime and also behind the execution_date.

I am running everything in UTC, except the database! My database is running in PST.

```
sid-as-mbp:r39132_airflow siddharth$ !psql
psql -h localhost -U siddharth airflow
psql (9.4.1)
Type "help" for help.

airflow=# select CURRENT_TIMESTAMP;
             now              
------------------------------
 2016-02-16 19:34:40.06475-08
(1 row)
```

So, it looks like start_date is set based on the DB TZ, while the execution_date is set using TZ where airflow is executing

**Comment by r39132** [comment] 2016-02-17 03:53
I've confirmed and fixed this. Our stage and prod envs are on UTC, but my laptop used to be on PST. It's now also on GMT/UTC, and now so is my local postgresql instance. 

After changing my DB TZ and restarting scheduler and webserver, it works.

<img width="893" alt="screenshot 2016-02-17 03 52 56" src="https://cloud.githubusercontent.com/assets/581734/13099438/06bf371c-d52a-11e5-9a92-dc122f597479.png">

**Comment by r39132** [comment] 2016-02-17 04:01
@kretes I suspect this is also happening to you. Closing for now. If this is not the issue, then ping me to reopen.

If you use Postgres 9.4, you can change the TZ by
`airflow=# ALTER DATABASE airflow  SET timezone TO 'Etc/GMT';`
The logout of the DB and relogin:

```
airflow=# select CURRENT_TIMESTAMP;
              now              
-------------------------------
 2016-02-17 03:59:46.934656+00
(1 row)
```

**Closed as completed by r39132** 2016-02-17 04:01 UTC
Labels: kind:bug

**Comment by kretes** [comment] 2016-02-18 09:52
From my point of view having an implicit requirement of run in UTC, and introducing weird bugs when it is not running like that instead of 'forcing' this as this is internal DB configuration is a bug.
I see https://github.com/airbnb/airflow/issues/1015 is tracked so hopefully it will be solved

**Comment by r39132** [comment] 2016-02-19 01:10
Agreed. It's a bug. We are looking for contributors as well, so feel free to pick issues off the list.

**Comment by r39132** [comment] 2016-02-19 01:12
Also, we need to make running in UTC an explicit requirement until we can fix the code to not care.
