### ISSUE TITLE
Support for SLA in Mapped Tasks

### ISSUE THREAD

**Issue by amolsr** [apache/airflow#36887] opened 2024-01-19 07:20 UTC
### Description

![image](https://github.com/apache/airflow/assets/38129418/fce3048d-6d1d-497e-a114-9f5d6da20189)

### Use case/motivation

We need to use the SLA with the mapped tasks. Since the SLA is the core feature of Airflow, every other task instance should respect that.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment] 2024-01-19 13:10
This is a duplicate of [#35275](https://github.com/apache/airflow/issues/35275).

**Closed as not planned by RNHTTR** 2024-01-19 13:10 UTC
Labels: kind:feature, duplicate
