### ISSUE TITLE
Airflow users/list/ is very slow

### ISSUE THREAD

**Issue by ayush-san** [apache/airflow#31340] opened 2023-05-17 06:59 UTC
### Apache Airflow version

2.6.1

### What happened

After upgrading to airflow 2.6 we started seeing slowness while opening `users/list/` and `roles/list/`. It takes around ~1min to open any of these pages. 

### What you think should happen instead

Ideally these pages shouldn't take much time to load

### How to reproduce

Not sure how to reproduce this 😕 

### Operating System

Debian GNU/Linux

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==7.1.0
apache-airflow-providers-apache-druid==3.3.1
apache-airflow-providers-apache-hive==5.1.1
apache-airflow-providers-apache-livy==3.2.0
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-cncf-kubernetes==6.1.0
apache-airflow-providers-common-sql==1.4.0
apache-airflow-providers-docker==3.6.0
apache-airflow-providers-elasticsearch==4.3.3
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-google==10.0.0
apache-airflow-providers-grpc==3.1.0
apache-airflow-providers-hashicorp==3.3.1
apache-airflow-providers-http==4.3.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-jdbc==3.3.0
apache-airflow-providers-microsoft-azure==6.0.0
apache-airflow-providers-mongo==3.1.1
apache-airflow-providers-mysql==4.0.2
apache-airflow-providers-neo4j==3.2.1
apache-airflow-providers-odbc==3.2.1
apache-airflow-providers-pagerduty==3.1.0
apache-airflow-providers-papermill==3.1.0
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-presto==4.2.1
apache-airflow-providers-redis==3.1.0
apache-airflow-providers-sendgrid==3.1.0
apache-airflow-providers-sftp==4.2.4
apache-airflow-providers-slack==7.2.0
apache-airflow-providers-snowflake==4.0.5
apache-airflow-providers-sqlite==3.3.2
apache-airflow-providers-ssh==3.4.0
apache-airflow-providers-tableau==4.0.0
apache-airflow-providers-trino==4.3.1

### Deployment

Other Docker-based deployment

### Deployment details

We run airflow on AWS ECS. 

### Anything else

After doing a fresh install of airflow 2.6.1, we noticed this error.

We have around 2-3k dags and 131 custom roles. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ayush-san** [comment] 2023-05-17 07:01
![Screenshot 2023-05-17 at 11 52 20 AM](https://github.com/apache/airflow/assets/57655135/5f0d48d9-9e1c-4a02-a74c-7a0601bdeee3)
![Screenshot 2023-05-17 at 11 54 06 AM](https://github.com/apache/airflow/assets/57655135/aeae81f2-dc70-4365-bafa-a75e6ffc46e8)

**Comment by hussein-awala** [comment] 2023-05-17 09:24
What version are you upgrading from?

**Comment by ayush-san** [comment] 2023-05-17 09:48
We upgraded from 1.10.12 but the migration script was breaking in our case since we were on a very old version. So we did a fresh install of 2.6.1

**Comment by tirkarthi** [comment] 2023-05-17 15:11
I was checking the overall flow over how flask-appbuilder renders the template. I commented out the search box in the template and the page was faster. I searched for "slow" in the repo and found this issue. Then related fields were created/changed and roles that listed other users/roles from DB. So I tried removing the columns in code and then found that search_exclude_columns is exposed through which it can be configured.

Related issue for search column : https://github.com/dpgaspar/Flask-AppBuilder/issues/796
https://github.com/dpgaspar/Flask-AppBuilder/issues/875

**Comment by tirkarthi** [comment] 2023-05-18 07:34
Can you please also try adding "roles" to the search_exclude_columns list? It also hits database and might improve performance if you don't need to filter by roles using search.

**Comment by ayush-san** [comment] 2023-05-19 05:24
We do filter by roles on the user page and will check for other fields which we can remove from the search

**Comment by ayush-san** [comment] 2023-05-19 09:02
After removing the following fields, the page load time is now <2s

CustomRoleModelView - 
```python
search_exclude_columns = ["permissions", "user"]
```

MultiResourceUserMixin 
```python
search_exclude_columns = ["created_by", "updated_by", "created", "changed", "password", "created_on", 
"changed_on", "changed_by", "last_name", "last_login", "login_count", "fail_login_count"]
```

<p align="center">
  <img  width="45%" alt="light" src="https://github.com/apache/airflow/assets/57655135/6622a7db-9bf0-4464-a5c6-345ac6690230">
  <img width="45%" alt="dark" src="https://github.com/apache/airflow/assets/57655135/814e5999-dd69-4ddf-b9e6-80c60b6fde84">
</p>

**Comment by tirkarthi** [comment] 2023-05-19 17:25
i find this odd and maybe I am missing something here but changing the lazy loading method to select gives noticeable improvement. Maybe changing permissions to use "select" might give a similar improvement. As per sqlalchemy docs select would result in a query per access that looks inefficient to selectin/joined since roles are displayed in the page that should trigger a query per entry, It was initially select and was later changed to joined and then to selectin in below commits.

https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html

### Changed to selectin

commit d7d2b49f29af007ff7f386a405cd1ba882a1818e
Author: Ash Berlin-Taylor <ash@apache.org>
Date:   Fri Apr 8 22:24:26 2022 +0100

    Speed up `has_access` decorator by ~200ms (#22858)
    
    
    Using the ORM to create all the Role, Permission, Action and Resource
    objects, only to throw them all away _on every request_ is slow. And
    since we are now using the API more and more in the UI it's starting to
    get noticeable
    
    This changes the `user.perm` property to issue a custom query that
    returns the tuple of action_name, permission_name we want, bypassing the
    ORM object inflation entirely, and since `user.roles` isn't needed in
    most requests we no longer eagerly load that.
    
    * Fix tests
    
    Caching issues that only crop up in tests (but not ever a problem in the
    request life cycle of webserver

### Changed to joined

commit 3e9828022b03b60d9e112f1f64340a528c8407e3
Author: James Timmins <james@astronomer.io>
Date:   Fri Feb 4 09:09:52 2022 -0800


```patch
diff --git a/airflow/www/fab_security/sqla/models.py b/airflow/www/fab_security/sqla/models.py
index 5c83588801..08faecdb25 100644
--- a/airflow/www/fab_security/sqla/models.py
+++ b/airflow/www/fab_security/sqla/models.py
@@ -155,7 +155,7 @@ class User(Model):
     last_login = Column(DateTime)
     login_count = Column(Integer)
     fail_login_count = Column(Integer)
-    roles = relationship("Role", secondary=assoc_user_role, backref="user", lazy="selectin")
+    roles = relationship("Role", secondary=assoc_user_role, backref="user", lazy="select")
     created_on = Column(DateTime, default=datetime.datetime.now, nullable=True)
     changed_on = Column(DateTime, default=datetime.datetime.now, nullable=True)
```

```
In [1]: from airflow.utils.session import create_session

In [2]: from airflow.www.fab_security.sqla.models import User, Role

# With lazy="selectin"

In [5]: %timeit with create_session() as session: session.query(User).all()
77.1 ms ± 8.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

# With lazy="select"

In [4]: %timeit with create_session() as session: session.query(User).all()
3.25 ms ± 49.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



```

**Comment by tirkarthi** [comment] 2023-05-19 17:42
One possible assumption is that search fields created, changed, created_by and changed_by query User but don't need roles thus efficient when using select but the page needs to access roles for each user in the main table. Meanwhile if selectin is used then the main table is speed up but search with changed*, created* makes it slower which can be disabled. Also when page_size is 100 the result reverses since select causes every row to hit db and for 100 rows its efficient to have selectin that performs only 2 queries with user fetch and an in query to fetch roles. Rather than changing lazy loading method which could affect other parts like this I guess it's better to have search to exclude changed*, created* .

```
# lazy='selectin'
In [5]: %timeit with create_session() as session: [user.roles for user in session.query(User).all()]
68.2 ms ± 8.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

# lazy='select' . Exclude created*, changed* fields and the render causes each entry
In [4]: %timeit with create_session() as session: [user.roles for user in session.query(User).all()]
319 ms ± 4.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by potiuk** [comment] 2023-11-29 00:07
Hey here @tirkarthi @ayush-san  - I assume that the issue still remains in Airflow 2.7. Can you please confirm that the fixes you applied by patching fix it too ? Maybe we could manage to incorporate it in Airflow 2.8 ? Happy to help with reviewing if you would consider a PR or maybe I could implement smth if I got a bit more information on where you got with that?

**Comment by tirkarthi** [comment] 2023-11-29 16:55
@potiuk The issue exists in main branch too. We have this fixed internally and we don't use columns like created, created_by, changed_by etc. The issue is that fields like created_by is a relationship field to user model so while loading the user page all users are loaded and since created_by is a relationship to load the autocomplete options a query is done to fetch every user. When there are 100 users then 100 users to list. 100 queries for each of created, created_by, changed_by etc are done causing lot of slowness as users increase. This is an issue from flask-appbuilder and the fix we use is like a workaround to not load these fields by excluding them since they are never useful to us but other users might need these fields and that's why a PR was never created from my end. 

Another approach would be to change joined strategy in the models but that might cause slowness in other pages/queries.

Some related issues from flask-appbuilder : 

https://github.com/dpgaspar/Flask-AppBuilder/issues/2073
https://github.com/dpgaspar/Flask-AppBuilder/issues/796
https://github.com/dpgaspar/Flask-AppBuilder/issues/875

**Comment by dpgaspar** [comment] 2024-02-23 14:02
note: https://github.com/dpgaspar/Flask-AppBuilder/issues/2073 as been fixed on FAB and will be included on 4.4.1

**Comment by potiuk** [comment] 2024-02-23 14:52
> note: [dpgaspar/Flask-AppBuilder#2073](https://github.com/dpgaspar/Flask-AppBuilder/issues/2073) as been fixed on FAB and will be included on 4.4.1

Oh. Fantastic. Thanks for that note @dpgaspar . I am gearing up to add FAB 4.4.1 added for the upcoming 2.9.0. Also As of 2.9.0 - which is really cool - we are going to have separate FAB provider and we will be able to upgrade FAB independently from Airflow upgrades, which makes the integration with FAB much, much better :)

**Comment by sunank200** [comment] 2024-05-28 06:45
It looks like we have already upgraded to FAB 4.5.0. https://github.com/apache/airflow/pull/39851

**Comment by sunank200** [comment] 2024-05-28 07:21
![Screenshot 2024-05-28 at 1 04 46 PM](https://github.com/apache/airflow/assets/8670962/2187a8d2-01ab-4dc0-94e6-5138f720f442)
I tested the load time after FAB 4.5.0 and it look like this issue should be fixed now.

**Closed as completed** 2024-05-28 08:03 UTC
Labels: area:performance, pending-response, area:UI, upstream-dependency
