### ISSUE TITLE
Python operators are printing more than one task log at a time

### ISSUE THREAD

**Issue by rustikk** [apache/airflow#21982] opened 2022-03-03 23:16 UTC
### Apache Airflow version

main (development)

### What happened

When using the python operator on scheduled runs the task logs are repeating multiple times. This issue doesn't occur when using the web UI to trigger the dags
![Screen Shot 2022-03-03 at 4 24 09 PM](https://user-images.githubusercontent.com/17841735/156669983-52513284-81c7-4943-9f3d-1043f7159dfa.png)

### What you expected to happen

I expected the task details for each task to show only one print out of that tasks logs

### How to reproduce

```
from airflow.models import DAG
from airflow.operators.python import PythonOperator

from datetime import datetime, timedelta

dag_name = "test_uri_generation"

def dummy_check4bugs():
    pass

with DAG(
    dag_id=dag_name,
    start_date=datetime(2021,1, 1),
    schedule_interval=timedelta(days=30, hours=12),
) as dag:

    t0 = PythonOperator(
        task_id="add_conn",
        #python_callable=add_conn,
        python_callable=dummy_check4bugs,
    )

    t1 = PythonOperator(
        task_id="check_uri_generation",
        #python_callable=check_uri_gen,
        python_callable=dummy_check4bugs,
    )
t0 >> t1
```

### Operating System

Docker

### Deployment

Docker-Compose

### Deployment details

Airflow Breeze

### Anything else

This bug occurs every time though only on scheduled runs and the first dag that runs typically repeats the logs the most.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by TreyYi** [comment] 2022-03-04 06:51
@potiuk @rustikk ,

Can I be assigned for this issue? I know what the problem is, but still thinking of how to resolve it.

**Comment by uranusjr** [comment] 2022-03-04 09:18
Go ahead a submit a PR!

**Comment by amoghrajesh** [comment] 2023-07-08 04:13
This doesn't have an active assignee. I will take this up and fix it

**Comment by amoghrajesh** [comment] 2023-07-09 05:40
I tried reproducing with the given DAG but i am unable to. Tried minute wise scheduling but the results don't show this.
@treyyi can you confirm that this is still an issue, or we can close this issue.

**Comment by amoghrajesh** [comment] 2023-07-27 13:54
Closing this issue as "not reproducible". Feel free to reopen if you can reproduce it

**Closed as completed by amoghrajesh** 2023-07-27 13:54 UTC
Labels: kind:bug, good first issue, affected_version:main_branch
