### ISSUE TITLE
ZendeskHook call for Ticket Tags endpoint

### ISSUE THREAD

**Issue by jlazarevicm** [apache/airflow#8507] opened 2020-04-22 00:54 UTC
Each zendesk call expects to have next_page in response:
        `next_page = results['next_page']`
This is not true for endpoint like this:
`https://{subdomain}.zendesk.com/api/v2/tickets/{ticket_id}/tags.json` 
So I got error when I tried to call this with zendesk call function.

**Apache Airflow version**: 1.10.3

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): -

**Environment**: local

- **Cloud provider or hardware configuration**: 2.5Ghz Intel Core i7, 16GB
- **OS** (e.g. from /etc/os-release): macOS Mojave
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
 
  File "workspace/lumos_airflow/dags/extensions/hooks/lumos_zendesk_hook.py"
    response = self.call(end_point)
  File "workspace/lumos_airflow/venv/lib/python3.5/site-packages/airflow/hooks/zendesk_hook.py", line 79, in call
    next_page = results['next_page']
KeyError: 'next_page'

**How to reproduce it**:

Invoke call function for zendesk ticket comments endpoint. 

**Anything else we need to know**:

Every time .

**Comment by jeffolsi** [comment] 2020-04-27 08:51
This is not a bug
You need to set `get_all_pages=False`
https://github.com/apache/airflow/blob/master/airflow/providers/zendesk/hooks/zendesk.py#L60

**Comment by potiuk** [comment] 2020-04-27 09:26
Closing as it is invalid as explained by @jeffolsi  (thanks!)

**Closed as completed by potiuk** 2020-04-27 09:26 UTC
Labels: kind:bug, invalid

**Comment by jlazarevicm** [comment] 2020-05-04 18:24
@jeffolsi I think you are not right. Event though if we set `get_all_pages=False` it doesn't change the fact that this line (prior than checking if `get_all_pages` is set to `False`): https://github.com/apache/airflow/blob/caa60b1141ac02cdde1c33464be9adca114c2ed5/airflow/providers/zendesk/hooks/zendesk.py#L81
expects result to have `next_page`. You should probably change it to: `results.get('next_page')`
