### ISSUE TITLE
Docker image 2.0.1 is broken (docker-compose up airflow-init fails)

### ISSUE THREAD

**Issue by josevnz** [apache/airflow#15312] opened 2021-04-09 21:57 UTC
**Apache Airflow version**: 2.0.1

**Environment**:

- **Cloud provider or hardware configuration**: Intel(R) Core(TM)2 CPU         T5600  @ 1.83GHz
- **OS** (e.g. from /etc/os-release): Fedora release 30 (Thirty)
- **Kernel** (e.g. `uname -a`): Linux macmini2 5.6.13-100.fc30.x86_64 #1 SMP Fri May 15 00:36:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: docker-ce 19.03.12

**What happened**:

```
# This fails
docker-compose up airflow-init
```

**What you expected to happen**:

```
attaching to airflow_airflow-init_1
airflow-init_1       | DB_BACKEND=postgresql+psycopg2
airflow-init_1       | DB_HOST=postgres
airflow-init_1       | DB_PORT=5432
airflow-init_1       | 
airflow-init_1       | 2.0.1
airflow_airflow-init_1 exited with code 0

```

**How to reproduce it**:

```
mkdir airflow
cd airflow/
curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.0.1/docker-compose.yaml'
less docker-compose.yaml 
mkdir ./dags ./logs ./plugins
echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env
docker-compose up airflow-init
```

And then

```
airflow-init_1       | [SQL: INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES (%(dttm)s, %(dag_id)s, %(task_id)s, %(event)s, %(execution_date)s, %(owner)s, %(extra)s) RETURNING log.id]
airflow-init_1       | [parameters: {'dttm': datetime.datetime(2021, 4, 9, 19, 23, 18, 600441, tzinfo=Timezone('UTC')), 'dag_id': None, 'task_id': None, 'event': 'cli_upgradedb', 'execution_date': None, 'owner': 'default', 'extra': '{"host_name": "c52642517587", "full_command": "[\'/home/airflow/.local/bin/airflow\', \'db\', \'upgrade\']"}'}]
airflow-init_1       | (Background on this error at: http://sqlalche.me/e/13/f405)
airflow-init_1       | DB: postgresql+psycopg2://airflow:***@postgres/airflow
airflow-init_1       | [2021-04-09 19:23:19,317] {db.py:674} INFO - Creating tables
airflow-init_1       | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
airflow-init_1       | INFO  [alembic.runtime.migration] Will assume transactional DDL.
airflow-init_1       | /entrypoint: line 192:    12 Illegal instruction     (core dumped) airflow db upgrade
airflow-init_1       | 
airflow-init_1       | airflow command error: argument GROUP_OR_COMMAND: `airflow upgradedb` command, has been removed, please use `airflow db upgrade`, see help above.
airflow-init_1       | usage: airflow [-h] GROUP_OR_COMMAND ...
irflow-init_1       | /entrypoint: line 129:    21 Illegal instruction     (core dumped) airflow users create --username "${_AIRFLOW_WWW_USER_USERNAME="admin"}" --firstname "${_AIRFLOW_WWW_USER_FIRSTNAME="Airflow"}" --lastname "${_AIRFLOW_WWW_USER_LASTNME="Admin"}" --email "${_AIRFLOW_WWW_USER_EMAIL="airflowadmin@example.com"}" --role "${_AIRFLOW_WWW_USER_ROLE="Admin"}" --password "${local_password}"
airflow-init_1       | 
airflow-init_1       | airflow command error: argument GROUP_OR_COMMAND: `airflow create_user` command, has been removed, please use `airflow users create`, see help above.

```

**Anything else we need to know**:

There is a workaround, use the previous image :+1: 

```
export AIRFLOW_IMAGE_NAME=apache/airflow:2.0.0
docker-compose up airflow-init
```

**Comment by potiuk** [comment] 2021-04-10 14:31
I cannot reproduce it Everything works fine for me. 

For me it looks like if you have - most likely - very very old host machine (I understand this is macmini is really old and has no AVX instructions supported. If your mac mini was released in 2006/2007 it has Core Solo processor, that has no AVX support I am afraid and it is old enough for us to not worry about it.

Here is the root cause:

```
airflow-init_1       | /entrypoint: line 192:    12 Illegal instruction     (core dumped) airflow db upgrade
```

and a
```
irflow-init_1       | /entrypoint: line 129:    21 Illegal instruction     (core dumped) airflow users create --username 
```

This looks very similarly to this error:

https://tech.amikelive.com/node-887/how-to-resolve-error-illegal-instruction-core-dumped-when-running-import-tensorflow-in-a-python-program/

You can follow this is and run the command `more /proc/cpuinfo | grep flags` in any docker container and compare it with mine. For example: `docker run -it --entrypoint /bin/bash apache/airflow:2.0.1 -c 'more /proc/cpuinfo | grep flags'`. 

Mine:
```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
```

The root cause of the problem is likely that one of Airflow dependencies (I guess pandas or numpy) switched to support newer version of instructions which your old mac mini does not support.

If this is the case, I am afraid we will not be able to do much if that's the case, you can try to build your own version of the image where you downgrade pandas/numpy but

**Closed as completed by potiuk** 2021-04-10 14:31 UTC
Labels: kind:bug, invalid

**Comment by josevnz** [comment] 2021-04-10 15:11
Hello,

Thanks for looking into this. Yes, this is a very Very VERY old machine where I managed to get Fedora running. I tried on a much more recent hardware and the containers work as expected.

For example, this are the flags of a much newer CPU (AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx, 2100MHz 64 bits)

```
Linux dmaf5 5.11.11-200.fc33.x86_64 #1 SMP Tue Mar 30 16:53:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall sev_es fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
```

You are right. I managed to run Airflow on bare-metal and without the Celery executor, which is perfect for my use case (until the old machine burns :-)).

Thanks!
