### ISSUE TITLE
Cannot see full task name at tree view page when task name is long

### ISSUE THREAD

**Issue by humit0** [apache/airflow#19362] opened 2021-11-02 08:44 UTC
### Apache Airflow version

2.2.0

### Operating System

Centos 7

### Deployment

Other 3rd-party Helm chart

### What happened

I could not see full task name, when task name is too long.

![image](https://user-images.githubusercontent.com/8676247/139811585-ce905fde-1d8d-465e-ab9f-c31c905bc13d.png)

### What you expected to happen

Needs to space between task name and task run history

![image](https://user-images.githubusercontent.com/8676247/139811813-b869833b-de01-4961-9fda-3d6e0c3558b2.png)

Or, limit redered task name length and see full name when hover on task name

### Anything else

`sqaureX` is independent of task name.
https://github.com/apache/airflow/blob/2.2.0/airflow/www/static/js/tree.js#L78

Calculating `squareX` with pre-rendered task name length by using below code looks good for me.

https://stackoverflow.com/a/35373030
```js
var BrowserText = (function () {
    var canvas = document.createElement('canvas'),
        context = canvas.getContext('2d');

    /**
     * Measures the rendered width of arbitrary text given the font size and font face
     * @param {string} text The text to measure
     * @param {number} fontSize The font size in pixels
     * @param {string} fontFace The font face ("Arial", "Helvetica", etc.)
     * @returns {number} The width of the text
     **/
    function getWidth(text, fontSize, fontFace) {
        context.font = fontSize + 'px ' + fontFace;
        return context.measureText(text).width;
    }

    return {
        getWidth: getWidth
    };
})();
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment] 2021-11-03 14:12
Duplicate of #17717

This is also fixed in #18675

**Closed as completed by bbovenzi** 2021-11-03 14:12 UTC
Labels: kind:bug, area:core
