### ISSUE TITLE
on_failure_callback is not called when task is manually marked as failed

### ISSUE THREAD

**Issue by FFCMSouza** [apache/airflow#38935] opened 2024-04-11 14:18 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.7.1

### What happened?

on_failure_callback is not called when task is terminated externally.
A similar issue was reported in https://github.com/apache/airflow/issues/25297 and fixed in https://github.com/apache/airflow/pull/29743.
I saw that the code change to call the on_failure_callback in this cases is no longer present on [version 2.7.1](https://github.com/apache/airflow/blob/2.7.1/airflow/models/taskinstance.py#L1620).
After which on_failure_callback is no longer called when SIGTERM is received

As you can see from the screenshots bellow the function was never called, the logs are never printed.
![image](https://github.com/apache/airflow/assets/68713515/22126d1a-2b71-4716-a4b1-cef6cf473a80)
![image](https://github.com/apache/airflow/assets/68713515/e07c4ba3-76f4-4b23-a647-a921fa249f28)
![image](https://github.com/apache/airflow/assets/68713515/66a3122d-1804-48cd-bda7-752353df21cc)
![image](https://github.com/apache/airflow/assets/68713515/2a92a25a-6ac0-4fba-8675-61912ab9fa4e)

### What you think should happen instead?

on_failure_callback should be called when task fails including when the task was manually marked as failed.

### How to reproduce

Create a dag task with an on_failure_callback configured, start and then mark the task as failed. You can see from the log that the function was never called.

### Operating System

debian

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by FFCMSouza** [comment] 2024-04-11 18:26
I saw that on version 1.9.0, thats already a different type of exception for this cases.
I believe that the following change could be made to fix that behavior:
`            except (AirflowFailException, AirflowSensorTimeout, AirflowTaskTerminated) as e:
                # If AirflowFailException is raised, task should not retry.
                # If a sensor in reschedule mode reaches timeout, task should not retry.
                self.handle_failure(e, test_mode, context, force_fail=True, session=session)
                session.commit()
                raise
            except (AirflowTaskTimeout, AirflowException) as e:
                if not test_mode:
                    self.refresh_from_db(lock_for_update=True, session=session)
                # for case when task is marked as success/failed externally
                # or dagrun timed out and task is marked as skipped
                # current behavior doesn't hit the callbacks
                if self.state in State.finished:
                    self.clear_next_method_args()
                    session.merge(self)
                    session.commit()
                    return None
                else:
                    self.handle_failure(e, test_mode, context, session=session)
                    session.commit()
                    raise`

**Comment by ephraimbuddy** [comment] 2024-04-12 19:18
This behaviour is documented in the code https://github.com/apache/airflow/blob/5f6f4a5f4654d64efb4c0cabb6e0e054d13a2e0f/airflow/models/taskinstance.py#L2594-L2597.

So it's not a bug

**Comment by FFCMSouza** [comment] 2024-04-12 19:31
Yes, I saw that. So there is no intention to change this behavior?
To me this doesn't make sense, marking a task as failed should trigger the failure callback.
If that's the case, is there any workaround to do this? I'm trying to use the on_kill method to do this, does it make sense to you?

**Comment by ephraimbuddy** [comment] 2024-04-14 18:58
> Yes, I saw that. So there is no intention to change this behavior? To me this doesn't make sense, marking a task as failed should trigger the failure callback. If that's the case, is there any workaround to do this? I'm trying to use the on_kill method to do this, does it make sense to you?

There are no plans to change the behaviour at the moment. Also, I don't know why you would want the callback to run when you intentionally failed a task

**Comment by FFCMSouza** [comment] 2024-04-14 23:19
> There are no plans to change the behaviour at the moment. Also, I don't know why you would want the callback to run when you intentionally failed a task

In my case, I use Airflow as an orchestrator to run Spark applications (spark-sql and spark-submit). When a task has failed or is marked as failed, in addition to notifying that the task has failed, I need to make sure that the corresponding step has been canceled in Spark. Most of the time, when a task actually fails, the cancel step operation is unnecessary, but this is not the case when a task is marked as failed.

I don't think it's such a rare scenario, plus similar issues have been opened before. I believe this behavior change would be very welcome in future Airflow releases.

**Comment by FFCMSouza** [comment] 2024-04-14 23:41
Anyway, I managed to find a way to solve my problem overwriting the `on_kill` method in my spark operator.
The only downside is that the `on_kill` method doesn't have access to the task context. To solve this problem, I created local variables on the `execute` method with the context information I need.

```
def on_kill(self):
    logging.info('starting on_kill')
    cancel_step(self.project, self.dag_name, self.run_id, self.task_id)
```
    def execute(self, context):
        self.log.info("starting SparkToDataLake.execute")

        self.dag_name = context.get('task_instance').dag_id
        self.run_id = context.get('run_id')
        self.task_id = context.get('task_instance').task_id + str(context.get('task_instance').map_index)
![image](https://github.com/apache/airflow/assets/68713515/132a1c57-f738-44c2-b4ef-053c3d8787e2)

PS: The `on_kill` method is also called on the `AirflowTaskTimeout` exception.

**Comment by ephraimbuddy** [comment] 2024-04-15 06:38
I think it might be worth it if you can create a feature request and explain how necessary this issue is, the use cases because I see it, that it's not required because the user is performing a manual action on the UI, what's the need to run the callback when same callback can be a task instead.

closing since it's not a bug

**Closed as completed by ephraimbuddy** 2024-04-15 06:38 UTC
Labels: kind:bug, area:core, needs-triage

**Comment by NewtonChutney** [comment] 2025-01-28 11:40
Have come across the same use case today.. 
To kill yarn processes upon manually marking as failed.

**Comment by ephraimbuddy** [comment] 2025-01-29 15:02
> Have come across the same use case today.. To kill yarn processes upon manually marking as failed.
> 
> [@FFCMSouza](https://github.com/FFCMSouza) thanks for your suggestion and code snippet!
> 
> [@ephraimbuddy](https://github.com/ephraimbuddy) maybe add an FAQ for on_failure_callback vs operator on_kill?

@NewtonChutney , Airflow is a community project. Feel free to contribute this FAQ in the way you think would be helpful. Let me know if you need assistance

**Comment by NewtonChutney** [comment] 2025-04-05 06:23
If I understand properly, the teardown feature should fix such issues?
https://github.com/apache/airflow/pull/45530
