### ISSUE TITLE
GCSToBQ operator does not respect `project_id` in deferrable mode with impersonation chain.

### ISSUE THREAD

**Issue by nathadfield** [apache/airflow#32093] opened 2023-06-23 12:06 UTC
### Apache Airflow version

2.6.2

### What happened

When using the `GCSToBigQueryOperator` in deferrable mode with an impersonation_chain service account which has a  default project_id that is different from the project_id specified in the operator arguments, a failure occurs. 

```
[2023-06-23, 11:38:37 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 447, in execute_complete
    raise AirflowException(event["message"])
airflow.exceptions.AirflowException: 404, message='Not Found: {\n  "error": {\n    "code": 404,\n    "message": "Not found: Job king-cdmr-etl-sandbox:airflow_apptweak_king_itunes_connect_channels_load_active_devices_to_bq_2023_06_22T07_00_00_00_00_4842808969d21632ecbb76ffca48aabd",\n    "errors": [\n      {\n        "message": "Not found: Job king-cdmr-etl-sandbox:airflow_apptweak_king_itunes_connect_channels_load_active_devices_to_bq_2023_06_22T07_00_00_00_00_4842808969d21632ecbb76ffca48aabd",\n        "domain": "global",\n        "reason": "notFound"\n      }\n    ],\n    "status": "NOT_FOUND"\n  }\n}\n', url=URL('https://www.googleapis.com/bigquery/v2/projects/king-cdmr-etl-sandbox/jobs/airflow_apptweak_king_itunes_connect_channels_load_active_devices_to_bq_2023_06_22T07_00_00_00_00_4842808969d21632ecbb76ffca48aabd')
```

I believe this happens because, although the BigQuery job to insert data, is raised against `self.project_id`  in  [_submit_job](https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py#L303), when in deferrable mode it tries to find the job within the project in [self.hook.project_id](https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py#L432).

It is possible that that the default project_id assigned to the impersonation chain service account is different to the project_id specified to the operator.

In the above error, you can see that the error says that it cannot find the job_id `airflow_apptweak_king_itunes_connect_channels_load_active_devices_to_bq_2023_06_22T07_00_00_00_00_4842808969d21632ecbb76ffca48aabd` in the project `king-cdmt-etl-sandbox`.

In fact this job_id was created successfully in the project `king-coredatasets-sandbox`

<img width="604" alt="Screenshot 2023-06-23 at 12 40 39" src="https://github.com/apache/airflow/assets/967119/488ea8e2-e447-46b1-814e-419402639a76">

### What you think should happen instead

I think that we should modify the call to `self.defer` to receive `self.project_id` rather than `self.hook.project_id`

### How to reproduce

I haven't quite got the exact steps to reproduce but I will submit a PR for review soon.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

apache-airflow-providers-google==10.0.0

### Deployment

Astronomer

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bhagany** [comment] 2023-06-23 18:49
Thank you for submitting this -- I have been procrastinating filing an issue of my own about this inconsistent handling of project ids.  I believe the problems with changes to `GCSToBigQueryOperator` and `BigQueryToGCSOperator` extend further than the case you've raised, and are caused by [these changes](https://github.com/apache/airflow/pull/30053/files).  Would you be willing to talk about the larger set of issues as well?  I see the PR you submitted and I think your change is a good one, but I think more are needed.

**Comment by bhagany** [comment] 2023-06-23 18:50
Somewhat inconveniently, I am only a few hours away from a 2-week vacation, so my responses may be delayed

**Comment by bhagany** [comment] 2023-06-23 19:12
^ I decided to file one, just to get my thoughts down

**Comment by nathadfield** [comment] 2023-06-29 08:57
`BigQueryGetDataOperator` also has this same problem

**Comment by eladkal** [comment] 2023-07-08 11:16
@nathadfield @avinashpandeshwar
I guess https://github.com/apache/airflow/pull/32232 did not cover `GCSToBigQueryOperator`
can you look into it and raise PR?

**Comment by avinashpandeshwar** [comment] 2023-07-09 02:44
@eladkal [Fix to GCSToBigQueryOperator](https://github.com/apache/airflow/pull/32232/files#diff-875bf3d1bfbba7067dc754732c0e416b8ebe7a5b722bc9ac428b98934f04a16f) for deferrable mode was addressed in https://github.com/apache/airflow/pull/32232, or did you mean for `BigQueryGetDataOperator`?

**Comment by eladkal** [comment] 2023-07-09 06:03
> or did you mean for BigQueryGetDataOperator?

Yes sorry.. I meant to `BigQueryGetDataOperator`

**Comment by avinashpandeshwar** [comment] 2023-07-10 05:32
@eladkal This current issue seems to be solved via https://github.com/apache/airflow/pull/32232 and could be closed. And I couldn't find another issue for `BigQueryGetDataOperator` specifically to link a PR. Should I create an issue first, or just provide a standalone PR here?

**Comment by eladkal** [comment] 2023-07-10 06:12
> @eladkal This current issue seems to be solved via #32232 and could be closed. And I couldn't find another issue for `BigQueryGetDataOperator` specifically to link a PR. Should I create an issue first, or just provide a standalone PR here?

Just open a PR and link to this issue as related

**Comment by avinashpandeshwar** [comment] 2023-07-10 06:54
@nathadfield @bhagany For `BigQueryGetDataOperator`, seems the project_id param is reserved for table's (storage) project. This conflicts with the convention followed across other operators where project_id stands for compute (job) project. I was wondering a reasonable approach is to have a separate optional `table_project_id` to provide the storage project (defaults to hook project_id), and use project_id (defaults to hook project_id) to submit the job. Do let me know your thoughts on this.

cc @eladkal

**Comment by eladkal** [comment] 2023-07-10 07:12
I think it's best to raise a PR with what you believe is the best course of action and explain the pros/cons in the PR description. Its easier to have this discussion where we see the code and scope of changes

**Comment by eladkal** [comment] 2023-07-27 07:44
Resolved in https://github.com/apache/airflow/pull/32488 and https://github.com/apache/airflow/pull/32232

**Closed as completed by eladkal** 2023-07-27 07:44 UTC
Labels: kind:bug, provider:google, area:providers
