### ISSUE TITLE
Calendar page doesn't load when using a timedelta DAG schedule

### ISSUE THREAD

**Issue by timecommunication** [apache/airflow#29227] opened 2023-01-30 01:32 UTC
### Apache Airflow version

2.5.1

### What happened

/calendar page give a problem, here is the capture

![屏幕截图 2023-01-30 093116](https://user-images.githubusercontent.com/19165258/215369479-9fc7de5c-f190-460c-9cf7-9ab27d8ac355.png)

### Operating System

Ubuntu 22.04.1 LTS

### Versions of Apache Airflow Providers

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

### Deployment

Other

### Deployment details

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2023-01-30 09:46
Could you please share your dag that causes it (mostly the schedule that is used for it ?)

**Comment by timecommunication** [comment] 2023-01-31 06:17
```python
# -*- coding: utf-8 -*-

# The DAG object; we'll need this to instantiate a DAG
from airflow import DAG

# Operators; we need this to operate!
from airflow.operators.python import PythonOperator

from datetime import datetime, timedelta
from textwrap import dedent

import time

with DAG(
    'demo-dag-python',
    # These args will get passed on to each operator
    # You can override them on a per-task basis during operator initialization
    default_args={
        'depends_on_past': False,

        # alert email receiver list
        'email': [
            '...@...com',
        ],

        'email_on_failure': True,
        'email_on_retry': False,
        'retry_delay': timedelta(seconds=5),
        'owner': 'demo'
    },
    description='only a demo with print func',
    schedule_interval=timedelta(hours=8),
    start_date=datetime(2022, 8, 1),
    catchup=False,
    tags=['demo', 'python', 'only-print-func', 'with-doc'],
) as dag:

    def write_some_code():

        print('do something in this func')
        print('start')
        print('end')


    def last_print():
        
        time.sleep(30)

        print('------ the finish line --------')

    task1 = PythonOperator(
        task_id='demo-task-node-1',
        python_callable=write_some_code,
        retries=3,
    )

    task2 = PythonOperator(
        task_id='demo-task-node-2',
        python_callable=last_print,
        retries=3,
    )
    
    task3 = PythonOperator(
        task_id='demo-task-node-3',
        python_callable=last_print,
        retries=3,
    )

    task1.doc_md = dedent("""
# task1

........
"""
    )

    dag.doc_md = __doc__  # providing that you have a docstring at the beginning of the DAG
    dag.doc_md = """
# dag doc
    
...
"""

    task3.set_upstream([task1, task2])
```

**Comment by potiuk** [comment] 2023-01-31 09:23
Sounds like a UI calendar view bug cc: @bbovenzi @pierrejeambrun

**Comment by melisekm** [comment] 2023-01-31 13:04
It seems like #28411 introducted `datetime.min` in [here](https://github.com/apache/airflow/blob/b5b1fae2dfe92751d6aaaace00009ce29625095b/airflow/www/views.py#L2883), which is timezone naive and can't be compared to logical date that is timezone aware. Maybe it can be replaced with `DateTime.min`.

**Comment by josh-fell** [comment] 2023-01-31 13:31
@timecommunication Thanks for the reproducible case. 

Definitely can confirm that this occurs with a timedelta `schedule` arg (either `datetime.timedelta` or `dateutil.relativedelta.relativedelta`), but not when using a cron interval.

**Comment by josh-fell** [comment] 2023-01-31 13:33
@melisekm Right on! You are more than welcome to open a PR. Seems like you know what the issue is. Would you like me to assign this to you?

**Comment by melisekm** [comment] 2023-01-31 13:35
> @melisekm Right on! You are more than welcome to open a PR. Seems like you know what the issue is. Would you like me to assign this to you?

No thanks. Good luck!

**Closed as completed** 2023-02-14 17:06 UTC
Labels: kind:bug, area:core, area:UI, _eol_affected_version:2.5
