### ISSUE TITLE
Kill task instances that haven't been able to heartbeat for a while

### ISSUE THREAD

**Issue by dimberman** [apache/airflow#7926] opened 2020-03-27 23:16 UTC
**Description**

A task run by the LocalTaskJob periodically updates a timestamp to indicate that the task is still alive and running. If the task is unable to update this timestamp for a long time (for example, due to DB connection errors), the scheduler may reschedule the task to run again. In such a case, it's possible that two instances of the task are running. The task can monitor the time since last heartbeat and kill itself to prevent such cases.

**Use case / motivation**

**Related Issues**

Moved here from https://issues.apache.org/jira/browse/AIRFLOW-374

**Comment by paolaperaza** [comment] 2020-09-02 23:25
@dimberman FYI Looks like this is a duplicate of: https://github.com/apache/airflow/issues/7925

**Closed as completed** 2020-09-30 00:55 UTC
