### ISSUE TITLE
Error "No module named 'airflow.providers.mysql"

### ISSUE THREAD

**Issue by mpzfm1** [apache/airflow#15648] opened 2021-05-04 08:38 UTC
Im installing airflow like this:

RUN useradd airflow

ENV AIRFLOW_VERSION="2.0.1"
ENV PYTHON_VERSION="3.8"
ENV CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade apache-airflow-providers-google
RUN pip3 install wheel oauth2client "apache-airflow [google, gcp, postgres,celery,redis,ssh,sftp]==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"

RUN mkdir -p /opt/airflow && chown -R airflow:airflow /opt
USER airflow

CMD ["airflow"]

The "problem" is that im receiving every time WARNING like this: 

 {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.cloud_sql.CloudSQLHook' from 'apache-airflow-providers-google' package: No module named 'airflow.providers.mysql'                            

 {providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.cloud_sql.CloudSQLDatabaseHook' from 'apache-airflow-providers-google' package: No module named 'airflow.providers.mysql'                    

{providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.cloud_sql.CloudSQLHook' from 'apache-airflow-providers-google' package: No module named 'airflow.providers.mysql'                          

{providers_manager.py:295} WARNING - Exception when importing 'airflow.providers.google.cloud.hooks.cloud_sql.CloudSQLDatabaseHook' from 'apache-airflow-providers-google' package: No module named 'airflow.providers.mysql

I dont know the reason becouse im using postgresql...

Im trying to locate providers_manager.py in order to change the log level (as i have seen in other post) but the file doesnt exits in /opt/airflow.... 

Any recomendations??

thanks in advance.

**Comment by potiuk** [comment] 2021-05-04 08:46
You can install mysql extra and the warning will disappear.  It will install (small) mysql provider and additional mysql libraries.

```
RUN pip3 install wheel oauth2client "apache-airflow [google, mysql, postgres,celery,redis,ssh,sftp]==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"
```

The problem is that mysql provider is used by google one (optional dependency).  I will make some changes in a future version of Airfow/provider's manager to remove the warnings coming from optional providers if those are not installed.

BTW. Few fixes to your setup:
1) remove gcp extra - it is deprecated version of `google`
2) you do not need to install the google provider separately. The 'google` extra will install it automatically.

**Comment by mpzfm1** [comment] 2021-05-04 09:22
> You can install mysql extra and the warning will disappear. It will install (small) mysql provider and additional mysql libraries.
> 
> ```
> RUN pip3 install wheel oauth2client "apache-airflow [google, mysql, postgres,celery,redis,ssh,sftp]==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"
> ```
> 
> The problem is that mysql provider is used by google one (optional dependency). I will make some changes in a future version of Airfow/provider's manager to remove the warnings coming from optional providers if those are not installed.
> 
> BTW. Few fixes to your setup:
> 
> 1. remove `gcp` extra - it is deprecated version of `google`
> 2. you do not need to install the google provider separately. The 'google` extra will install it automatically.

Thanks, i changed dockerfile but when i build it fails:


Collecting mysqlclient<1.4,>=1.3.6
  Downloading mysqlclient-1.3.14.tar.gz (91 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nrkv9j4j/mysqlclient_dc6d7e9833cb46158c77938dcf30b032/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nrkv9j4j/mysqlclient_dc6d7e9833cb46158c77938dcf30b032/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o0kdkjv6
         cwd: /tmp/pip-install-nrkv9j4j/mysqlclient_dc6d7e9833cb46158c77938dcf30b032/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nrkv9j4j/mysqlclient_dc6d7e9833cb46158c77938dcf30b032/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-nrkv9j4j/mysqlclient_dc6d7e9833cb46158c77938dcf30b032/setup_posix.py", line 53, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-nrkv9j4j/mysqlclient_dc6d7e9833cb46158c77938dcf30b032/setup_posix.py", line 28, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f7/a2/1230ebbb4b91f42ad6b646e59eb8855559817ad5505d81c1ca2b5a216040/mysqlclient-1.3.14.tar.gz#sha256=3981ae9ce545901a36a8b7aed76ed02960a429f75dc53b7ad77fb2f9ab7cd56b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Cannot install apache-airflow[celery,google,mysql,postgres,redis,sftp,ssh]==2.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    apache-airflow[celery,google,mysql,postgres,redis,sftp,ssh] 2.0.1 depends on mysqlclient<1.4 and >=1.3.6; extra == "mysql"
    The user requested (constraint) mysqlclient==1.3.14

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies


Besides, why i cant find providers_manager.py into /opt/airflow folder???

**Comment by uranusjr** [comment] 2021-05-04 09:26
Not sure what image you’re using but you probably need to install MySQL client headers. On Ubuntu for example you need to `apt install libmysqlclient-dev`.

**Comment by mpzfm1** [comment] 2021-05-04 09:47
> Not sure what image you’re using but you probably need to install MySQL client headers. On Ubuntu for example you need to `apt install libmysqlclient-dev`.

Im using FROM ubuntu:20.04

Why not install like : apt-get install mysql-client ¿?¿?? instead libmysqlclient-dev

**Comment by mpzfm1** [comment] 2021-05-04 09:58
I think there is some issue with the packages, installing from the url: 

https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.8.txt

it includes mysqlclient==1.3.14
 
and the error message is:

The conflict is caused by:
apache-airflow[celery,google,mysql,postgres,redis,sftp,ssh] 2.0.1 depends on mysqlclient<1.4 and >=1.3.6; extra == "mysql"
The user requested (constraint) mysqlclient==1.3.14

**Comment by potiuk** [comment] 2021-05-04 10:32
The "conflict" message is misleading. The error is caused by inabilty to install 1.3.14 (lack of binary libraries as @uranusjr mentioned). You need to install it and we even have the right script in the official image. It works for Debian Buster, but should be very similar for Ubuntu.

https://github.com/apache/airflow/blob/master/scripts/docker/install_mysql.sh

**Comment by potiuk** [comment] 2021-05-04 10:43
Also I'd heartily recommend using the official airflow image instead of building your own. 

It is heavily optimized for size (based on 'slim' version of debian buster, uses multi-staging approach where "build-essentials" are not included in the final image) also it supports mysql client installation and works out-of-the-box:

`apache/airflow:2.0.1-python3.8`

Also, if you want to customize it and use less number of extras than the default, you can customize the image as described in https://airflow.apache.org/docs/docker-stack/build.html#customizing-the-image including some examples.

In your case what should work is get the latest version of airflow sources from master or `v-2-0-stable` branch and run::

``
docker build . \
    --build-arg PYTHON_BASE_IMAGE="python:3.8-slim-buster" \
    --build-arg AIRFLOW_VERSION="2.0.1" \
    --build-arg AIRFLOW_EXTRAS="google,mysql,postgres,celery,redis,ssh,sftp" \
    --tag "your-image"
```

Also I'd really recommend to move to Airflow 2.0.2 instead of 2.0.1.

**Comment by potiuk** [comment] 2021-05-04 10:48
BTW. Just built such customized image and it is 766 MB total (uncompressed), which is rather small for airflow image (the Airflow reference image is ~950 MB) :

`dive your-image`

```
│ Image Details ├─────────────────
                                  
                                  
Total Image size: 766 MB          
Potential wasted space: 32 MB     
Image efficiency score: 96 %      
```

**Comment by mpzfm1** [comment] 2021-05-04 12:25
thanks all of you for the suggestions. Last thing, how about i cant find the file providers_manager.py ?¿ into /opt (installation folder) i just have:

airflow@airflow-webserver-2021040503-7d777c8759-l89qf:~/airflow$ ls
airflow-webserver.pid  airflow.cfg  logs  unittests.cfg  webserver_config.py

Thanks.

**Comment by potiuk** [comment] 2021-05-04 13:16
FYI. The 'providers_manager.py" can be found in airflow installation. In the official Airflow Image (where airflow is installed with `--user` flag) you will find it in /home/airflow/.local . If you install Airflow with regular 'pip install` you will find it in one of the folders returned by `python -m site`.

**Comment by eladkal** [comment] 2021-08-08 12:17
@potiuk do we have a task on this issue?

**Comment by potiuk** [comment] 2021-08-08 12:30
I do not think there is anything to do on airflow side. This was a problem with custom docker image that did not have all dependencies to install mysql. Taking into account that there is already the official image which has all that is needed (And can even be taken as a base) I think we should close the issue.

**Closed as completed by potiuk** 2021-08-08 12:30 UTC
