### ISSUE TITLE
Unable to delete task instance

### ISSUE THREAD

**Issue by aaur0** [apache/airflow#955] opened 2016-02-04 23:03 UTC
I have airflow setup in my local machine and uses the default sqllite database backed. It seems that delete task instance button doesn't seem to be working.  It fails with the following error :

```

Ooops.

                          ____/ (  (    )   )  \___
                         /( (  (  )   _    ))  )   )\
                       ((     (   )(    )  )   (   )  )
                     ((/  ( _(   )   (   _) ) (  () )  )
                    ( (  ( (_)   ((    (   )  .((_ ) .  )_
                   ( (  )    (      (  )    )   ) . ) (   )
                  (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )
                  ( (  (   ) (  )   (  ))     ) _)(   )  )  )
                 ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )
                  (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )
                 ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )
                  ((  (   )(    (     _    )   _) _(_ (  (_ )
                   (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)
                   ((__)        \\||lll|l||///          \_))
                            (   /(/ (  )  ) )\   )
                          (    ( ( ( | | ) ) )\   )
                           (   /(| / ( )) ) ) )) )
                         (     ( ((((_(|)_)))))     )
                          (      ||\(|(|)|/||     )
                        (        |(||(||)||||        )
                          (     //|/l|||)|\\ \     )
                        (/ / //  /|//||||\\  \ \  \ _)
-------------------------------------------------------------------------------
Node: L-SB8T2TQG3Q-M
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/flask_admin/model/base.py", line 1668, in delete_view
    model = self.get_one(id)
  File "/Library/Python/2.7/site-packages/flask_admin/contrib/sqla/view.py", line 959, in get_one
    return self.session.query(self.model).get(tools.iterdecode(id))
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 831, in get
    return self._get_impl(ident, loading.load_on_ident)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 864, in _get_impl
    return fallback_fn(self, key)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident
    return q.one()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 2693, in one
    ret = list(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
    None, None)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 582, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/Library/Python/2.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 601, in process
    raise TypeError("SQLite DateTime type only accepts Python "
StatementError: (exceptions.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input. [SQL: u'SELECT task_instance.task_id AS task_instance_task_id, task_instance.dag_id AS task_instance_dag_id, task_instance.execution_date AS task_instance_execution_date, task_instance.start_date AS task_instance_start_date, task_instance.end_date AS task_instance_end_date, task_instance.duration AS task_instance_duration, task_instance.state AS task_instance_state, task_instance.try_number AS task_instance_try_number, task_instance.hostname AS task_instance_hostname, task_instance.unixname AS task_instance_unixname, task_instance.job_id AS task_instance_job_id, task_instance.pool AS task_instance_pool, task_instance.queue AS task_instance_queue, task_instance.priority_weight AS task_instance_priority_weight, task_instance.operator AS task_instance_operator, task_instance.queued_dttm AS task_instance_queued_dttm \nFROM task_instance \nWHERE task_instance.task_id = ? AND task_instance.dag_id = ? AND task_instance.execution_date = ?'] [parameters: [{'%(4624730576 param)s': u'test1', '%(4624729104 param)s': u'daily_traffic', '%(4624730896 param)s': u'2015-08-01 00:00:00'}]]
```

**Comment by r39132** [comment] 2016-02-06 01:01
Please provide more information : 
1. Version (`git log` output if you `git pull` and run `python setup.py install`)
2. Steps to reproduce

**Comment by r39132** [comment] 2016-02-06 01:07
I just reproduced this!

It's happening on a recent version of MASTER

```
commit 4230394c619c07e0cd8b3dd8a855697d0262b2d6
Merge: 8e84d15 206681f
Author: Maxime Beauchemin <maximebeauchemin@gmail.com>
Date:   Wed Feb 3 08:58:41 2016 -0800

    Merge pull request #945 from criccomini/master

    Add documentation to gcs_download_operator

commit 8e84d151b129dd7ecf4f03b15f2f1ff2ce62b7f6
Merge: 2735524 4220576
Author: Maxime Beauchemin <maximebeauchemin@gmail.com>
Date:   Wed Feb 3 08:44:33 2016 -0800

    Merge pull request #947 from r39132/master

    Encrypt Variables if Fernet key provided

```

**Comment by r39132** [comment] 2016-02-06 01:10
The date bind param should probably not be a string :  u'2015-08-01 00:00:00'

**Comment by mistercrunch** [comment] 2016-02-06 01:39
Right, sqlite doesn't autocast like other dbs do. We've wacked some of these bugs already. it's just a patter of parsing the string into a datetime.

**Comment by aaur0** [comment] 2016-02-06 01:46
If no-one else is not working on it. I can patch this and send out a pull request

**Comment by r39132** [comment] 2016-02-06 01:51
I was looking into it, but be my guest:-) I'm still figuring out the SQLAlchemy ORM stuff.

**Comment by aaur0** [comment] 2016-02-06 01:54
If you are already on it. You can take it.  I am new to codebase , so it will take me sometime to fix it.

**Comment by r39132** [comment] 2016-02-06 02:11
@mistercrunch I guess you are referring to https://github.com/airbnb/airflow/commit/c4d0fe93ed8185114364984e5eafa1b1fc404a0c#diff-6ff6b61554e53188d97c129ed40256cd as a previous squashing of this sort of bug. So, it's on the WTF side that I need to convert a stringified datetime into a pythodatetime?

**Comment by r39132** [comment] 2016-02-06 02:52
Hmn.. looking for where `https://airflow.ep.stage.agari.com/admin/taskinstance/delete/` is handled.. I see the POST payload for id passing a tuple, in which the execution date is a 3rd parameter and it's a string.

**Comment by r39132** [comment] 2016-02-06 03:20
@aaur0 I'm new as well. I might poke at this a little next week, but don't let that stop you.

**Comment by mistercrunch** [comment] 2016-02-06 07:27
I'm positive that this is a `flask-admin` bug, not an Airflow bug. It's most likely limited to sqlite.

It's related to the fact that the pk is a composite that include a datetime.

**Comment by r39132** [comment] 2016-02-11 02:33
This was also reported on https://github.com/airbnb/airflow/issues/849. The main reason to fix this is really for supporting development and testing. No one will actually use SQLLite for anything business critical.

**Comment by r39132** [comment] 2016-02-29 08:08
As mentioned on https://github.com/airbnb/airflow/issues/1069, this is a wontfix since it is likely a bug in SQLAlchemy's support of SQLite and because we recommend folks to move to a DB similar to what they would use in QA and Production envs.

**Closed as completed by r39132** 2016-02-29 08:08 UTC

**Comment by mistercrunch** [comment] 2016-03-09 13:12
https://github.com/flask-admin/flask-admin/issues/1226
