### ISSUE TITLE
Support for one_success_all_done trigger_rule

### ISSUE THREAD

**Issue by guim4dev** [apache/airflow#19748] opened 2021-11-22 15:28 UTC
### Description

Currently, there is support only for one_success trigger_rule, which starts the task instance the moment after one of the upstream tasks succeeds. The idea for the new trigger_rule is to wait for all upstream tasks to be done and at least one of them succeed. 

### Use case/motivation

The use case is to allow a OR-like behavior to trigger_rules.
Maybe even XOR-like behavior could be added as a second extra trigger_rule.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2021-11-22 15:39
Duplicate of #17010 - please discuss it there.

**Comment by potiuk** [comment] 2021-11-22 15:40
(and read the discussion - this case is already supported).

**Closed as completed by potiuk** 2021-11-22 15:39 UTC
Labels: kind:feature
