### ISSUE TITLE
update google-video-intelligence dependency in google provider

### ISSUE THREAD

**Issue by mohittalele** [apache/airflow#26207] opened 2022-09-07 12:04 UTC
### Description

Currently google cloud provider restricts the version of google-video-intellegiance library to >=1.7.0,<2.0.0. 
However this version old and latest available version is 2.8.1. 
This is also mentioend as one of the - [ToDos ](https://github.com/apache/airflow/blob/00fd789258b48d92b16294b598956db271bc7b3d/airflow/providers/google/provider.yaml#L65)

### Use case/motivation

Version >2.0.0 offers features and v2.0.0 is couple of years old.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2022-09-07 21:32
Feel free to attempt to do so.

**Comment by eladkal** [comment] 2023-01-26 17:05
Duplicate of https://github.com/apache/airflow/issues/28045

**Closed as not planned by eladkal** 2023-01-26 17:05 UTC
Labels: provider:google, area:providers, kind:feature, good first issue, duplicate
