### ISSUE TITLE
Can't see logs during reps, status(up_for_retry)

### ISSUE THREAD

**Issue by AncientEvil96** [apache/airflow#31536] opened 2023-05-25 07:07 UTC
### Apache Airflow version

2.6.1

### What happened

When a task goes into replay no logs are displayed.

### How to reproduce

'retries': 2,
'retry_delay': timedelta(minutes=1)
Install attributes and create an error in the task.

### Operating System

ubuntu 20

### Versions of Apache Airflow Providers

don't needet 

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hussein-awala** [comment] 2023-05-25 13:15
I cannot reproduce the issue with 2.6.1. If you still encounter the problem and believe there might be a bug, please feel free to provide additional information about your setup and a complete example of a DAG that exhibits the issue. With that information, we can consider reopening the ticket.
I close it for now.

**Closed as not planned by hussein-awala** 2023-05-25 13:15 UTC
Labels: kind:bug, Can't Reproduce, area:core, needs-triage
