### ISSUE TITLE
Scheduler has NO HEARTBEAT after manual trigger. Scheduler revives after 15mins and begins task

### ISSUE THREAD

**Issue by pingdink** [apache/airflow#10614] opened 2020-08-27 20:44 UTC
**Apache Airflow version**:
1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", │
BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}                                                       
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"169db3bff4b5fb7722e967c5b6356713f05f15ed", GitTreeState:"clean", │
BuildDate:"2020-04-03T16:14:09Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}  

**Environment**:
- **Cloud provider or hardware configuration**:
azure - that's all I know
- **OS** (e.g. from /etc/os-release):
ubuntu
- **Kernel** (e.g. `uname -a`):
???

**What happened**:
Scheduler has no heartbeat after manual trigger for 15 mins. The CPU usage spikes and then drops to 1m. 

**What you expected to happen**:
I expected my Dag manual trigger to trigger and run the task right away

**How often does this problem occur? Once? Every time etc?**
Not after a scheduler restart. But almost everytime after 10 minutes from restart and manual trigger.

**Any relevant logs to include? Put them here in side a detail tag:**
No logs showing any issue that I can find.

**Comment by eladkal** [comment] 2021-06-11 10:48
This issue is reported against an old Airflow version. The scheduler was refactored significantly since then.
Please check if the issue is present in 2.1.0 and if so please comment with reproduce steps.
For now I'm closing this issue

**Closed as completed by eladkal** 2021-06-11 10:48 UTC
Labels: kind:bug
