### ISSUE TITLE
DAG parameters form updates only on blur

### ISSUE THREAD

**Issue by SnirBroshi** [apache/airflow#44739] opened 2024-12-06 19:06 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.10.2

### What happened?

When triggerring a DAG and updating some parameter, the DAG ran with the old value that param had.

### What you think should happen instead?

If I change the value of some textbox in the DAG parameters and press Enter, the DAG should use the value I filled in.

### How to reproduce

- Create a DAG with some param
- In the web UI click "Trigger DAG"
- in the "DAG conf Parameters" form, fill in some value in some textbox and press Enter (without first unfocusing the textbox)
- The DAG will run with the parameter set to the value it had before, and ignore the value you tried to set

It's easiest to see when you set the param to be required but have no default value, then pressing Enter will error and let you refill the form.

### Operating System

Ubuntu 22.04

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by NotWearingPants** [comment] 2024-12-06 22:13
Duplicate of #42157 (which was fixed in the next minor)

**Closed as completed by NotWearingPants** 2024-12-06 22:13 UTC
Labels: kind:bug, area:core, area:UI, needs-triage
