### ISSUE TITLE
Snowflake Provider - Hook's support for not providing a region is broken when using SQLAlchemy

### ISSUE THREAD

**Issue by mattpolzin** [apache/airflow#20032] opened 2021-12-04 00:26 UTC
### Apache Airflow Provider(s)

snowflake

### Versions of Apache Airflow Providers

Versions 2.2.x (since https://github.com/apache/airflow/commit/0a37be3e3cf9289f63f1506bc31db409c2b46738).

### Apache Airflow version

2.2.1

### Operating System

Debian GNU/Linux 10 (buster)

### Deployment

Other 3rd-party Helm chart

### Deployment details

Bitnami Airflow Helm chart @ version 8.0.2

### What happened

When connecting to Snowflake via SQLAlchemy using the Snowflake Hook, I get an error that the URL is not valid because my Snowflake instance is in US West 2 (Oregon) which means I don't provide a region explicitly. Snowflake's documentation says:
> If the account is located in the AWS US West (Oregon) region, no additional segments are required and the URL would be xy12345.snowflakecomputing.com

The error is that `xy12345..snowflakecomputing.com` is not a valid URL (note the double-dot caused by the lack of a region).

### What you expected to happen

I expect the connection to be successful.

### How to reproduce

You can use the default snowflake connection if you have one defined and see this problem with the following one-liner:
```shell
python -c 'from airflow.providers.snowflake.hooks.snowflake import SnowflakeHook; SnowflakeHook().get_sqlalchemy_engine().connect()'
```

### Anything else

Fortunately I imagine the fix for this is just to leave the region URL component out when `region` is `None` here: https://github.com/apache/airflow/commit/0a37be3e3cf9289f63f1506bc31db409c2b46738#diff-2b674ac999a5b938fe5045f6475b0c5cc76e4cab89174ac448a9e1d41a5c04d5R215.

Using version `2.1.1` of the Snowflake provider with version `2.2.1` of Airflow is currently a viable workaround so for now I am just avoiding the update to the provider.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2021-12-04 14:40
Why don't you submit a PR with a fix @mattpolzin ?

**Comment by mattpolzin** [comment] 2021-12-04 16:19
I appreciate the encouragement! I've got a lot of projects in progress right now so I don't think I'll find time to get set up here as well.

**Comment by potiuk** [comment] 2021-12-04 16:25
I marked it as good-first-issue, so maybe someone else will pick it up then !

**Comment by harishkrao** [comment] 2021-12-05 04:36
Is this available to pick up and implement?

**Comment by potiuk** [comment] 2021-12-05 22:05
Sure @harishkrao . Assigned you.

**Comment by potiuk** [comment] 2021-12-05 22:05
But maybe @mik-laj would like to do it firsst - so agree between yourselves ;)

**Comment by harishkrao** [comment] 2021-12-06 02:13
Thank you for getting back @potiuk. @mik-laj how would you like to proceed?

**Comment by mik-laj** [comment] 2021-12-06 02:16
Feel free to create a PR.  I will take care of the review.

**Comment by harishkrao** [comment] 2021-12-07 04:52
Great, I will do so. Thank you.

**Comment by harishkrao** [comment] 2021-12-08 07:47
@mik-laj I have made the change, I have a question on the unit tests. They are failing because the connection sends the region name. Do you have a suggestion on how to test without a region name?
https://github.com/harishkrao/airflow/blob/sqlalchemy-snowflake-region/tests/providers/snowflake/hooks/test_snowflake.py#L94

**Comment by mik-laj** [comment] 2021-12-08 09:35
@harishkrao  Hi. I improved the tests yesterday and I think now it will be easy to write the missing test. See: https://github.com/apache/airflow/pull/20095
Now all you have to do is add a test case here.
https://github.com/apache/airflow/blob/545ca59ba9a0b346cbbf28cc6958f9575e5e6b0b/tests/providers/snowflake/hooks/test_snowflake.py#L76-L95
To build a URL, we shouldn't use `string.format`. Instead of it, we should use `snowflake.sqlalchemy.URL`. See: https://github.com/snowflakedb/snowflake-sqlalchemy#connection-parameters
The main problem with concatenation is the problem with handling of special characters due to the lack of URL-encoding.

**Comment by harishkrao** [comment] 2021-12-09 03:57
Thank you @mik-laj. I will write the test cases based on the new tests you pushed yesterday. 
Also thank you for the SQL Alchemy URL build link. I will use it to construct the URI.

**Comment by harishkrao** [comment] 2021-12-09 07:47
@mik-laj 
Made the below changes, running pytests pending, will let you know after running them tomorrow:
https://github.com/harishkrao/airflow/blob/fix-sqlalchemy-snowflake-region/airflow/providers/snowflake/hooks/snowflake.py#L216-L239
https://github.com/harishkrao/airflow/blob/fix-sqlalchemy-snowflake-region/tests/providers/snowflake/hooks/test_snowflake.py#L268-L279

**Comment by harishkrao** [comment] 2021-12-10 21:54
@mik-laj How did you manage dependencies when running pytests?
I am facing `WARNING - Exception when importing 'airflow.providers.snowflake.hooks.snowflake.SnowflakeHook' from 'apache-airflow-providers-snowflake' package: No module named 'sqlalchemy.sql.roles'`

**Comment by mik-laj** [comment] 2021-12-11 01:22
Breeze

**Comment by mik-laj** [comment] 2021-12-11 07:49
You can also use constraint files. See: https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html

**Comment by potiuk** [comment] 2021-12-11 17:57
See also complete description here: https://github.com/apache/airflow/blob/main/TESTING.rst#airflow-unit-tests @harishkrao

**Comment by harishkrao** [comment] 2021-12-11 22:26
Thank you @mik-laj and @potiuk, I will proceed.

**Comment by harishkrao** [comment] 2021-12-12 22:04
I narrowed down the scope of our issue here. Once I am inside the virtual environment, and I try to import the same SQLAlchemy package, I run into the same error:
`root@66ecbec1a1f0:/opt/airflow# python
Python 3.8.12 (default, Nov 17 2021, 17:26:17) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from snowflake.sqlalchemy import URL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/snowflake/sqlalchemy/__init__.py", line 25, in <module>
    from . import base, snowdialect
  File "/usr/local/lib/python3.8/site-packages/snowflake/sqlalchemy/base.py", line 17, in <module>
    from .custom_commands import AWSBucket, AzureContainer, ExternalStage
  File "/usr/local/lib/python3.8/site-packages/snowflake/sqlalchemy/custom_commands.py", line 14, in <module>
    from sqlalchemy.sql.roles import FromClauseRole
ModuleNotFoundError: No module named 'sqlalchemy.sql.roles'
`
It looks like there is a bug with SQLAlchemy 1.3.24, which is a dependency for Flask-AppBuilder. See [1621](https://github.com/dpgaspar/Flask-AppBuilder/issues/1621) and [953](https://github.com/pallets/flask-sqlalchemy/issues/953).

If you have some time spare, can one of you please try to import this package in your local venv and let me know if you face the same issue? @potiuk @mik-laj 
This package is not being used anywhere else in the entire airflow repository.

**Comment by mik-laj** [comment] 2021-12-13 00:55
@harishkrao See: https://github.com/snowflakedb/snowflake-sqlalchemy/issues/234
To use URL class, you need to run:
```
python -m pip install snowflake-sqlalchemy==1.2.4 sqlalchemy==1.3.24
```
Unfortunately, Snowflake incorrectly marked the version requirements in one release of `snowflake-sqlalchemy` and after fixing the problem, they didn't mark the release as yanked, so pip downloads invalid dependency versions

**Comment by mik-laj** [comment] 2021-12-13 01:12
I pushed a fix: https://github.com/apache/airflow/pull/20245

**Comment by harishkrao** [comment] 2021-12-13 01:32
Thanks very much for letting me know and for pushing the fix @mik-laj :) I will use the above versions.

**Comment by harishkrao** [comment] 2021-12-13 04:28
@mik-laj any suggestions to overcome celery dependency issues?
Searched the forum and online and found no open bugs related to it.
`Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 33, in <module>
    sys.exit(load_entry_point('apache-airflow', 'console_scripts', 'airflow')())
  File "/usr/local/bin/airflow", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pri/airflow/airflow/__main__.py", line 28, in <module>
    from airflow.cli import cli_parser
  File "/home/pri/airflow/airflow/cli/cli_parser.py", line 33, in <module>
    from airflow.executors import celery_executor, celery_kubernetes_executor
  File "/home/pri/airflow/airflow/executors/celery_executor.py", line 37, in <module>
    from celery import Celery, Task, states as celery_states
ModuleNotFoundError: No module named 'celery'`

**Comment by mik-laj** [comment] 2021-12-13 04:37
```bash
AIRFLOW_VERSION=main
PYTHON_VERSION="$(python --version | cut -d " " -f 2 | cut -d "." -f 1-2)"
CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
pip install celery --constraint "${CONSTRAINT_URL}"
```
See: https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html

**Comment by harishkrao** [comment] 2021-12-13 05:39
My apologies for asking again, I am contributing to this repo for the first time. Will follow this and install the dependencies. Thank you for the help and patience @mik-laj.

**Comment by harishkrao** [comment] 2021-12-15 16:16
Just an info - I am working on this, my laptop crashed, so I have to setup the environment in another laptop and continue, will get back soon.

**Comment by harishkrao** [comment] 2021-12-20 09:23
Environment is configured, working on this, will get back in a day or two.

**Comment by harishkrao** [comment] 2021-12-22 05:57
Made changes for the [fix](https://github.com/harishkrao/airflow/commit/f4f499e589ace7cccf307bab12b4aa5d3c641af9). Preparing the PR now.

**Comment by mik-laj** [comment] 2021-12-26 08:44
@harishkrao Do you need help with preparing a PR?

**Comment by harishkrao** [comment] 2021-12-26 21:43
@mik-laj Thank you for offering help, I will follow the steps in the guide and get back to you soon.

**Comment by harishkrao** [comment] 2021-12-27 03:14
Just opened a PR, thank you for reviewing @mik-laj!

**Closed as completed** 2021-12-28 12:54 UTC
Labels: kind:bug, area:providers, good first issue, provider:snowflake

**Comment by new-php** [comment] 2025-03-25 18:36
After pulling my hair out for days with this exact Snowflake URL issue, this post was a lifesaver! That double-dot bug is so subtle but completely breaks everything. Here's what worked for me:

    Quick Fix: Confirmed rolling back to snowflake-provider 2.1.1 works as a temporary solution (pip install apache-airflow-provider-snowflake==2.1.1)

    Alternative Approach: Found that explicitly setting region=us-west-2 in the connection extras (even though Oregon shouldn't need it) also resolves it

    Pro Tip: For anyone setting up fresh, make sure to use the full connection string format:
    account.user@xy12345.us-west-2.snowflakecomputing.com
    (Yes, even for Oregon - seems counterintuitive but prevents issues)

Question for OP: Did you find any other workarounds before discovering the provider version fix? I'm curious if modifying the hook directly would've worked.

— DataPipesDreamer (Running Airflow 2.3 with Snowflake since 2021)

P.S. For new users hitting this, don't forget to[ pip install apache-airflow](https://docs.vultr.com/how-to-install-apache-airflow-on-ubuntu-24-04) [google,snowflake] with the latest constraints file - dependency management is half the battle!
New chat
