### ISSUE TITLE
Scheduler never retry tasks in up_for_retry state.

### ISSUE THREAD

**Issue by krisskross** [apache/airflow#1077] opened 2016-02-25 08:30 UTC
When tasks fail and are marked as "up_for_retry" in the UI the scheduler never picks them up and retries them? I'm only able to backfill them using the command line.

One other thing is that the "Dag Run" status in the Tree View doesn't reset to "success" after a sucessful backfill?

**Comment by mistercrunch** [comment] 2016-02-25 15:45
DagRun status is for the scheduler only, backfill is unaware of it and doesn't alter it.

I'm not sure why your `up_for_retry` tasks aren't getting picked up. Are you sure you waited for the whole duration of the `retry_interval`?

**Comment by krisskross** [comment] 2016-02-26 19:57
Unable to reproduce. Closing.

**Comment by r39132** [comment] 2016-02-29 08:35
I wasn't aware that the backfill does not reset/edit DagRun. That seems unintuitive to me as my understanding was that the backfill and run commands delegate to executors and that DagRun reflected work executors did, not work the scheduler needs to do. It makes sense now because I know the internals of the code, but it actually doesn't make sense to a user of the system. 

DagRuns should be a complete view of what has or will be executed. cc @mistercrunch @criccomini 

I'm changing this issue's title to reflect what I think is a bug/enhancement.

**Comment by krisskross** [comment] 2016-02-29 21:29
Actually, I may have reproduced the issue. Could it be because `retries` are set to 0? If so the behavior is still surprising since we force the retry?

(retires are dealt by the task itself)

**Comment by r39132** [comment] 2016-02-29 21:48
Hi @krisskross 

In reading this issue, I am encountering conflicting reports. 

On one hand, you report `When tasks fail and are marked as "up_for_retry" in the UI the scheduler never picks them up and retries them?` and on the other hand, you report `Actually, I may have reproduced the issue. Could it be because retries are set to 0? If so the behavior is still surprising since we force the retry?`

So, if you are running the release version, there was a known bug in which we had infinite retries, though that only happened if the retries was set to a number above 0. If retries was set to 0, then no retries would happen -- that is by design since you are asking for 0 retries. At this point, I need a pretty clear definition of the issue. If you want a finite number of retries, set the count above 0 and run the latest code. If you are okay with running infinite retries until success, then set the value above 0 and run the release version (1.6.2). If you don't want retries, set it to 0 on any version.

**Comment by krisskross** [comment] 2016-02-29 21:56
Yes, i'm toying around with airflow 1.6.2 at the moment to see if it fits our needs. So I might have confused two different dags. I will try retries = 1. Thanks.

**Comment by r39132** [comment] 2016-02-29 22:13
Cool. I will close this then and open a separate issue to track backfill tracking in dag runs.

**Closed as completed by r39132** 2016-02-29 22:13 UTC

**Comment by krisskross** [comment] 2016-03-01 08:50
Unfortunately, setting `retries` to 1 as global default did not help. Here's my dag.

``` py
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2016, 2, 24),
    'retries': 1,
    'retry_delay': timedelta(minutes=5)
}

t1 = BashOperator(
  task_id='LogLagCheck',
  execution_timeout=timedelta(minutes=15),
  bash_command="java -jar task.jar Task {{ execution_date }}",
  dag=dag)
```

**Comment by mistercrunch** [comment] 2016-03-02 08:45
Do you have an `airflow scheduler` process running?

**Comment by krisskross** [comment] 2016-03-02 09:09
Yes. Also, backfills works fine.

**Comment by thibault-ketterer** [comment] 2016-03-05 21:14
Sorry to interrupt Is there a fix for the infinite retry behavior ?

edit : found it : -> airbnb_prod
https://github.com/airbnb/airflow/commit/4d015a5c43e4861b7771dd94b5963c6b75679316

**Comment by krisskross** [comment] 2016-03-24 08:50
I have been able to test this a bit more. 

We have a situation where all `retries` for a task have been exhausted by the scheduler/worker and task status set to `failed`. Some tasks of same `dag_run` were successful. We thought that setting a task status to `up_for_retry` in the UI would give the failed task another retry but it doesn't. The parent `dag_run` have status `failed` which might be the reason the task is not retried?

Is this behavior correct and if so, what is our alternatives for repairing the failed task? Ideally, we would like both task and dag_run status to be `success` afterwards.
