### ISSUE TITLE
All the task cells in the same row are showing same state (latest state)

### ISSUE THREAD

**Issue by ming-zhang-SN** [apache/airflow#24630] opened 2022-06-24 08:27 UTC
### Apache Airflow version

2.3.2 (latest released)

### What happened

For latest version (2.3.2) Airflow, on grid view UI all the task cells in the same row are showing same state(latest state):
![Untitled](https://user-images.githubusercontent.com/90807339/175493927-de8ca6fc-94d2-4441-8281-5c4f492c836c.png)

In the response json of `grid_data` API we can see all the instances have the same data except `run_id`.
<img width="783" alt="Screen Shot 2022-06-24 at 17 17 29" src="https://user-images.githubusercontent.com/90807339/175494318-489bed6b-e149-4d98-9339-3283dcaa0ee9.png">

I think the `children` were same for all the instances here, which caused the problem:
https://github.com/apache/airflow/blob/2.3.2/airflow/www/views.py#L300

### What you think should happen instead

Each task cell should show correct data.

### Operating System

Ubuntu 19.10

### Deployment

Other 3rd-party Helm chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by bbovenzi** [comment] 2022-06-24 13:16
Duplicate of https://github.com/apache/airflow/issues/24410 and fixed in https://github.com/apache/airflow/pull/24327

**Closed as completed by bbovenzi** 2022-06-24 13:16 UTC
Labels: kind:bug, area:core
