### ISSUE TITLE
Logs suppressed when impersonation is enabled

### ISSUE THREAD

**Issue by sarthakhaikerwalsaxena** [apache/airflow#19376] opened 2021-11-02 23:53 UTC
### Apache Airflow version

2.2.1 (latest released)

### Operating System

RHEL 7.9

### Deployment

Virtualenv installation

### What happened

When user impersonation is enabled in 2.2.1, the complete task logs are not printed. Here is a dummy DAG which was used:

```
from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.utils.dates import days_ago
from airflow.models import Variable
from airflow.operators.python_operator import PythonOperator


args = {
    'owner': 'airflow',
}

default_args = {
    'run_as_user':'ssaxen3',
}

with DAG(
    dag_id='sanity_check',
    schedule_interval=None,
    start_date=days_ago(1),
    tags=['platform'],
	default_args=default_args,

) as dag:

    sanity_check = BashOperator(
        task_id='sanity_check',
        bash_command='echo "Hello"'
)

    sanity_check 

if __name__ == "__main__":
    dag.cli()
	
```

The output logs of the task is:

```
*** Reading local file: /opt/airflow/logs/sanity_check/sanity_check/2021-11-02T23:14:35.304756+00:00/1.log
[2021-11-03, 10:14:38 UTC] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sanity_check.sanity_check manual__2021-11-02T23:14:35.304756+00:00 [queued]>
[2021-11-03, 10:14:38 UTC] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sanity_check.sanity_check manual__2021-11-02T23:14:35.304756+00:00 [queued]>
[2021-11-03, 10:14:38 UTC] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-03, 10:14:38 UTC] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-03, 10:14:38 UTC] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-03, 10:14:38 UTC] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): sanity_check> on 2021-11-02 23:14:35.304756+00:00
[2021-11-03, 10:14:38 UTC] {base_task_runner.py:141} INFO - Running on host: #######
[2021-11-03, 10:14:38 UTC] {base_task_runner.py:142} INFO - Running: ['sudo', '-E', '-H', '-u', 'ssaxen3', 'airflow', 'tasks', 'run', 'sanity_check', 'sanity_check', 'manual__2021-11-02T23:14:35.304756+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/sanity_check.py', '--cfg-path', '/tmp/tmpyzph5jvu', '--error-file', '/tmp/tmphf058_7k']
[2021-11-03, 10:14:39 UTC] {base_task_runner.py:122} INFO - Job 3: Subtask sanity_check [[34m2021-11-03, 10:14:39 UTC[0m] {[34mdagbag.py:[0m500} INFO[0m - Filling up the DagBag from /opt/airflow/dags/sanity_check.py[0m
[2021-11-03, 10:14:40 UTC] {base_task_runner.py:122} INFO - Job 3: Subtask sanity_check [[34m2021-11-03, 10:14:40 UTC[0m] {[34mexample_kubernetes_executor_config.py:[0m171} WARNING[0m - Could not import DAGs in example_kubernetes_executor_config.py: No module named 'kubernetes'[0m
[2021-11-03, 10:14:40 UTC] {base_task_runner.py:122} INFO - Job 3: Subtask sanity_check [[34m2021-11-03, 10:14:40 UTC[0m] {[34mexample_kubernetes_executor_config.py:[0m172} WARNING[0m - Install kubernetes dependencies with: pip install apache-airflow['cncf.kubernetes'][0m
[2021-11-03, 10:14:40 UTC] {base_task_runner.py:122} INFO - Job 3: Subtask sanity_check Running <TaskInstance: sanity_check.sanity_check manual__2021-11-02T23:14:35.304756+00:00 [running]> on host #####
[2021-11-03, 10:14:40 UTC] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-03, 10:14:40 UTC] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**It does not echo the word "Hello" in the logs.** 

### What you expected to happen

When the same DAG was tested in Airflow 2.1.4 the output is as expected and the word gets printed. 

```
*** Reading local file: /opt/airflow/logs/sanity_check/sanity_check/2021-11-02T23:43:55.201973+00:00/1.log
[2021-11-03 10:43:57,156] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: sanity_check.sanity_check 2021-11-02T23:43:55.201973+00:00 [queued]>
[2021-11-03 10:43:57,161] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: sanity_check.sanity_check 2021-11-02T23:43:55.201973+00:00 [queued]>
[2021-11-03 10:43:57,161] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-11-03 10:43:57,161] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-11-03 10:43:57,161] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-11-03 10:43:57,169] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): sanity_check> on 2021-11-02T23:43:55.201973+00:00
[2021-11-03 10:43:57,169] {base_task_runner.py:133} INFO - Running on host: #######
[2021-11-03 10:43:57,169] {base_task_runner.py:134} INFO - Running: ['sudo', '-E', '-H', '-u', 'ssaxen3', 'airflow', 'tasks', 'run', 'sanity_check', 'sanity_check', '2021-11-02T23:43:55.201973+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/sanity_check.py', '--cfg-path', '/tmp/tmpn0fcvxa_', '--error-file', '/tmp/tmpkm5wvg5h']
[2021-11-03 10:43:58,485] {base_task_runner.py:114} INFO - Job 6: Subtask sanity_check [[34m2021-11-03 10:43:58,484[0m] {[34mdagbag.py:[0m496} INFO[0m - Filling up the DagBag from /opt/airflow/dags/sanity_check.py[0m
[2021-11-03 10:43:58,532] {base_task_runner.py:114} INFO - Job 6: Subtask sanity_check [[34m2021-11-03 10:43:58,528[0m] {[34mexample_kubernetes_executor_config.py:[0m175} WARNING[0m - Could not import DAGs in example_kubernetes_executor_config.py: No module named 'kubernetes'[0m
[2021-11-03 10:43:58,533] {base_task_runner.py:114} INFO - Job 6: Subtask sanity_check [[34m2021-11-03 10:43:58,528[0m] {[34mexample_kubernetes_executor_config.py:[0m176} WARNING[0m - Install kubernetes dependencies with: pip install apache-airflow['cncf.kubernetes'][0m
[2021-11-03 10:43:58,644] {taskinstance.py:1252} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=sanity_check
AIRFLOW_CTX_TASK_ID=sanity_check
AIRFLOW_CTX_EXECUTION_DATE=2021-11-02T23:43:55.201973+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-02T23:43:55.201973+00:00
[2021-11-03 10:43:58,645] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-03 10:43:58,645] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo "Hello"']
[2021-11-03 10:43:58,650] {subprocess.py:74} INFO - Output:
[2021-11-03 10:43:58,651] {subprocess.py:78} INFO - Hello
[2021-11-03 10:43:58,651] {subprocess.py:82} INFO - Command exited with return code 0
[2021-11-03 10:43:58,663] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=sanity_check, task_id=sanity_check, execution_date=20211102T234355, start_date=20211102T234357, end_date=20211102T234358
[2021-11-03 10:43:58,671] {base_task_runner.py:114} INFO - Job 6: Subtask sanity_check Running <TaskInstance: sanity_check.sanity_check 2021-11-02T23:43:55.201973+00:00 [running]> on host ######
[2021-11-03 10:43:58,795] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-11-03 10:43:58,804] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

### How to reproduce

The issue can be reproduced only when impersonation is enabled. 

### Anything else

When the echo in bash command is replaced by something else like ""touch /tmp/file.txt", the file gets created. This means that the command does get executed but the result is not printed in the logs. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sarthakhaikerwalsaxena** [comment] 2021-11-03 03:43
Note that the logs from "subprocess.py" are not displayed.

**Comment by ebacal** [comment] 2021-11-24 17:58
I see same behavior with empty value  of default_impersonation =
When change logging_level = CRITICAL or anything but INFO - no log displayed at all 
v:2.2.2

**Comment by plockaby** [comment] 2021-12-09 01:58
I think that I know the issue but I'm not confident in my solution.

Roughly, the problem is that normally tasks are called using using `os.fork` and the task is called from within the existing airflow environment. When you use impersonation then a new airflow process is created and wrapped with sudo. That new process is run basically by calling `sudo -u myuser airflow tasks run ....`. When airflow is called in that way it captures the logs and puts them .... somewhere. I am not sure where.

I was able to get logs to appear in the user interface with this change, but I do not think it is the correct way to fix this so I haven't submitted a PR for it. Still, I wanted to kickstart this bug/regression.

```
diff --git a/airflow/task/task_runner/base_task_runner.py b/airflow/task/task_runner/base_task_runner.py
index 5551508f4..ac0333a38 100644
--- a/airflow/task/task_runner/base_task_runner.py
+++ b/airflow/task/task_runner/base_task_runner.py
@@ -49,6 +49,8 @@ class BaseTaskRunner(LoggingMixin):
         self._task_instance = local_task_job.task_instance

         popen_prepend = []
+        popen_append = []
+
         if self._task_instance.run_as_user:
             self.run_as_user = self._task_instance.run_as_user
         else:
@@ -58,6 +60,7 @@ class BaseTaskRunner(LoggingMixin):
                 self.run_as_user = None

         self._error_file = NamedTemporaryFile(delete=True)
+        popen_append += ['--error-file', self._error_file.name]

         # Add sudo commands to change user if we need to. Needed to handle SubDagOperator
         # case using a SequentialExecutor.
@@ -77,6 +80,7 @@ class BaseTaskRunner(LoggingMixin):
             # propagate PYTHONPATH environment variable
             pythonpath_value = os.environ.get(PYTHONPATH_VAR, '')
             popen_prepend = ['sudo', '-E', '-H', '-u', self.run_as_user]
+            popen_append = ['--interactive']

             if pythonpath_value:
                 popen_prepend.append(f'{PYTHONPATH_VAR}={pythonpath_value}')
@@ -99,7 +103,7 @@ class BaseTaskRunner(LoggingMixin):
                 pool=local_task_job.pool,
                 cfg_path=cfg_path,
             )
-            + ["--error-file", self._error_file.name]
+            + popen_append
         )
         self.process = None
```

**Comment by ashb** [comment] 2021-12-09 15:22
@plockaby I have a feeling the problem might be, that without that `--interactive` arg the logs are written to a file that is owned by the other user (but that airflow can't read). Are you able to confirm if my hunch is correct?

**Comment by plockaby** [comment] 2021-12-09 18:51
Well, I only started examining Airflow for use at my job like two weeks ago so my knowledge of it is beginner at best. I looked at the logs here:

/opt/airflow/logs/example/run_this_as_nobody/2021-12-09T17:59:48.763174+00:00

The directory and the file are owned by the "airflow" user, not by the "nobody" user. And the logs just say:

```
[2021-12-09 18:00:16,944] {base_task_runner.py:124} INFO - Job 185: Subtask run_this_as_nobody [2021-12-09 18:00:16,944] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/repo/dags/example.py
[2021-12-09 18:00:16,962] {base_task_runner.py:124} INFO - Job 185: Subtask run_this_as_nobody /usr/local/lib/python3.9/site-packages/airflow/providers/cncf/kubernetes/backcompat/backwards_compat_converters.py:67 DeprecationWarning: This module is deprecated. Please use `kubernetes.client.models.V1VolumeMount`.
[2021-12-09 18:00:16,963] {base_task_runner.py:124} INFO - Job 185: Subtask run_this_as_nobody /usr/local/lib/python3.9/site-packages/airflow/providers/cncf/kubernetes/backcompat/backwards_compat_converters.py:55 DeprecationWarning: This module is deprecated. Please use `kubernetes.client.models.V1Volume`.
[2021-12-09 18:00:17,143] {base_task_runner.py:124} INFO - Job 185: Subtask run_this_as_nobody Running <TaskInstance: example.run_this_as_nobody scheduled__2021-12-09T17:59:48.763174+00:00 [running]> on host worker-75dcd98d8c-w9648
```

I can find nothing else under `/opt/airflow/logs` that references this task outside of that directory. When I enable interactive then that log file looks like this:

```
[2021-12-09 18:10:28,173] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody [2021-12-09 18:10:28,172] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/repo/dags/example.py
[2021-12-09 18:10:28,196] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody /usr/local/lib/python3.9/site-packages/airflow/providers/cncf/kubernetes/backcompat/backwards_compat_converters.py:67 DeprecationWarning: This module is deprecated. Please use `kubernetes.client.models.V1VolumeMount`.
[2021-12-09 18:10:28,197] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody /usr/local/lib/python3.9/site-packages/airflow/providers/cncf/kubernetes/backcompat/backwards_compat_converters.py:55 DeprecationWarning: This module is deprecated. Please use `kubernetes.client.models.V1Volume`.
[2021-12-09 18:10:28,321] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody Running <TaskInstance: example.run_this_as_nobody manual__2021-12-09T18:10:10.414374+00:00 [running]> on host worker-566447d44b-6x8hq
[2021-12-09 18:10:28,322] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody [2021-12-09 18:10:28,321] {taskinstance.py:1427} INFO - Exporting the following env vars:
[2021-12-09 18:10:28,322] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody AIRFLOW_CTX_DAG_OWNER=airflow
[2021-12-09 18:10:28,322] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody AIRFLOW_CTX_DAG_ID=example
[2021-12-09 18:10:28,322] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody AIRFLOW_CTX_TASK_ID=run_this_as_nobody
[2021-12-09 18:10:28,322] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody AIRFLOW_CTX_EXECUTION_DATE=2021-12-09T18:10:10.414374+00:00
[2021-12-09 18:10:28,322] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-09T18:10:10.414374+00:00
[2021-12-09 18:10:28,324] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody [2021-12-09 18:10:28,323] {subprocess.py:62} INFO - Tmp dir root location:
[2021-12-09 18:10:28,324] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody  /tmp
[2021-12-09 18:10:28,324] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody [2021-12-09 18:10:28,324] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'id']
[2021-12-09 18:10:28,334] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody [2021-12-09 18:10:28,334] {subprocess.py:85} INFO - Output:
[2021-12-09 18:10:28,338] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody [2021-12-09 18:10:28,337] {subprocess.py:89} INFO - uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)
[2021-12-09 18:10:28,338] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody [2021-12-09 18:10:28,338] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-09 18:10:28,373] {base_task_runner.py:128} INFO - Job 192: Subtask run_this_as_nobody [2021-12-09 18:10:28,373] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=example, task_id=run_this_as_nobody, execution_date=20211209T181010, start_date=20211209T181026, end_date=20211209T181028
```

Better options than `--interactive` would be great! I tried to dig in to where airflow was actually writing the logs by looking at `_capture_task_logs` in `airflow/cli/commands/task_command.py`and I got as far as figuring out that it was writing logs to an instance of `<Logger airflow.models.taskinstance.TaskInstance (INFO)>` but not any farther than that.

**Comment by ashb** [comment] 2021-12-09 19:07
K, so I think the problem is that the subprocess can't re-open the log file to write logs to it, and the downside to `--interactive` is that we get `INFO - Job 192: Subtask run_this_as_nobody` prefixed on everyline.

Could you try adding the log file to the `sudo chown` invocatoin (and `chown` it back at the end!)? For now just hack in a hard coded file and see if that fixes the problem, and if it does I can direct you on how to get the correct filename.

**Comment by plockaby** [comment] 2021-12-09 21:08
The log files are already world writable (666). I modified file_task_handler.py to make the log directory also be 777 (as it is currently 775) and that didn't make any impact.

**Comment by plockaby** [comment] 2021-12-09 22:55
A follow-up: I had file_task_handler.py write every time it opened a log file and which log file and the pid that tried to do it. e.g. they would create a file called "/tmp/pidXX" and contain the name of the directory or directories that they tried to open. The pid of the process running in sudo never tried to open the log file for the task it was running and in fact never tried to open any log file using file_task_handler.py.

**Comment by sarthakhaikerwalsaxena** [comment] 2022-02-09 09:22
Is #19028 expected to resolve this issue as well?

**Comment by plockaby** [comment] 2022-02-09 21:02
> Is #19028 expected to resolve this issue as well?

Unfortunately they are unrelated.

**Comment by sarthakhaikerwalsaxena** [comment] 2023-02-04 00:54
The issue is no longer reproducible in version 2.5.1. Have there been any other changes which could have fixed this?

**Comment by eladkal** [comment] 2023-02-06 12:41
Closing as can't reproduce. If someone is experiencing issues please open a new bug report

**Closed as not planned by eladkal** 2023-02-06 12:41 UTC
Labels: kind:bug, Can't Reproduce, area:core, _eol_affected_version:2.2
