### ISSUE TITLE
Airflow 1.10.15 pulls in sqlalchemy 1.4.6 which breaks it

### ISSUE THREAD

**Issue by cris-b** [apache/airflow#15273] opened 2021-04-08 10:58 UTC
**Apache Airflow version**: 1.10.15

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **OS** (e.g. from /etc/os-release): Redhat 8.3

**What happened**:

Installed airflow with pip, it picked up sql alchemy 1.4.6 as a dependency.

This causes airflow to fil to run as flask-admin 1.5.4 is not compatible with sqlalchemy 1.4.  flask-admin 1.5.6 is however.

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 26, in <module>
    from airflow.bin.cli import CLIFactory
  File "/usr/local/lib/python3.8/site-packages/airflow/bin/cli.py", line 82, in <module>
    from airflow.www.app import (cached_app, create_app)
  File "/usr/local/lib/python3.8/site-packages/airflow/www/app.py", line 42, in <module>
    from airflow.www.blueprints import routes
  File "/usr/local/lib/python3.8/site-packages/airflow/www/blueprints.py", line 25, in <module>
    from airflow.www import utils as wwwutils
  File "/usr/local/lib/python3.8/site-packages/airflow/www/utils.py", line 40, in <module>
    import flask_admin.contrib.sqla.filters as sqlafilters
  File "/usr/local/lib/python3.8/site-packages/flask_admin/contrib/sqla/__init__.py", line 2, in <module>
    from .view import ModelView
  File "/usr/local/lib/python3.8/site-packages/flask_admin/contrib/sqla/view.py", line 18, in <module>
    from flask_admin.contrib.sqla.tools import is_relationship
  File "/usr/local/lib/python3.8/site-packages/flask_admin/contrib/sqla/tools.py", line 4, in <module>
    from sqlalchemy.ext.declarative.clsregistry import _class_resolver
ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.clsregistry'

**What you expected to happen**:

setup.py has a dependency on sqlalchemy=~1.3 so should not pull 1.4

**How to reproduce it**:

pip install "apache-airflow < 2.0"
airflow version

<above python trace>

the pip install log shows:

Collecting sqlalchemy~=1.3
  Downloading SQLAlchemy-1.4.6-cp38-cp38-manylinux2014_x86_64.whl (1.5 MB)

How often does this problem occur? Once? Every time etc?

Every time.

**Comment by eladkal** [comment] 2021-04-08 11:42
Duplicate of https://github.com/apache/airflow/issues/14811

**Closed as completed by eladkal** 2021-04-08 11:42 UTC
Labels: kind:bug, duplicate
