### ISSUE TITLE
`TaskInstance::log_url`'s webpage does not provide a link or mechanism to view the DAG run

### ISSUE THREAD

**Issue by AetherUnbound** [apache/airflow#39179] opened 2024-04-22 20:00 UTC
### Apache Airflow version

2.9.0

### What happened?

See https://github.com/WordPress/openverse/issues/4177 for a specific case.

When viewing a URL generated by `TaskInsatnce::log_url`, this directs the user to a `/log` page. This page has the DAG ID and the enable/disable switch at the top, but no link to get to the DAG's grid or graph view. Additionally, the `schedule` information in the top right of the page will always show as `Schedule: False` on the `/log` page, even if the DAG has a schedule.

https://github.com/apache/airflow/blob/b0e96131251c416f4d32ba60343ef3a6ecdb2346/airflow/models/taskinstance.py#L1786-L1798

The "Log Url" that shows up in the "Task Instances" browse page of the webserver apparently uses a link to the grid view rather than `/log` directly. This seems to be because it's constructed directly:

https://github.com/apache/airflow/blob/b0e96131251c416f4d32ba60343ef3a6ecdb2346/airflow/www/views.py#L5186-L5205

### What you think should happen instead?

It would be helpful if the `/log` page (and thus the link generated by `TaskInstance::log_url`) had a way to view the entire DAG in the graph & grid views. So much work has been done on the new DAG view (which rocks!) - that would be the ideal view to be directed to IMO rather than a standalone log page that requires navigation to the DAGs list then navigation to the DAG _then_ navigation to the right DAG run and task in order to actually view the failure in the context of the entire DAG.

### How to reproduce

Run a task which prints out `ti.log_url`, then visit that URL and observe that there's no way to navigate back to the DAG.

### Operating System

Official docker image

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment] 2024-04-22 21:27
I believe this is a duplicate of #39023 -- @AetherUnbound let me know if you'd like me to assign you to that one!

**Closed as not planned by RNHTTR** 2024-04-22 21:27 UTC
Labels: kind:bug, area:core, needs-triage

**Comment by AetherUnbound** [comment] 2024-04-22 21:45
Ah, it is indeed! And sure! I've commented there, please go ahead and assign it to me 😄
