### ISSUE TITLE
DAGs remain in the UI after renaming the dag_id in the same python file

### ISSUE THREAD

**Issue by wolfier** [apache/airflow#11901] opened 2020-10-28 01:41 UTC
**Apache Airflow version**: 1.10.12

**What happened**:

When I rename the dag_id, the new dag_id shows up in the UI but the old dag_id does not disappear and remains in the UI. 

**What you expected to happen**:

When Airflow [lists out the python files](https://github.com/apache/airflow/blob/1.10.12/airflow/utils/file.py#L105-L161) and tries to [deactivate the deleted dags during dag processing](https://github.com/apache/airflow/blob/1.10.12/airflow/utils/dag_processing.py#L951-L955), the old DAG's file location is still in the list of the alive DAG location because the new DAG is now defined in the old DAG's python file. Even when you manually set is_active to False in the metastore, the dag processing process will set it back to True.

This happens whether or not DAG serialization is enabled.

**How to reproduce it**:

I was able to reproduce it by following these steps:
1. Add a python file in the dags folder and initialize the DAG
2. Verify the dag shows up in the UI
3. Change the dag_id in the same file to something else
4. Verify the new dag shows up in the UI
5. Both the old DAG and the new DAG are visible on the UI as well as the metadata db.

```
➜  dags pwd
/Users/alan/projects/astro/dags
➜  dags ls
wow.py
```
```python
from datetime import datetime

from airflow.models import DAG


dag = DAG(
    dag_id='yay',
    schedule_interval='@once',
    start_date=datetime(2020, 1, 1),
    catchup=False
)
```

In the screenshot, both DAGs are marked as active but there only one DAG defined in `wow.py`.
<img width="1502" alt="Screen Shot 2020-10-27 at 6 31 40 PM" src="https://user-images.githubusercontent.com/5952735/97380092-8cfb6480-1883-11eb-8315-1b386ffb00d8.png">

**Anything else we need to know**:

**Comment by kaxil** [comment] 2020-11-20 21:50
This needs fixing in Master and is not that critical, so will fix it in 2.0.0

**Comment by potiuk** [comment] 2020-12-07 10:10
Hey @kaxil @ashb - are we going to fix it ? Or maybe it already is fixed with the serialization ?

**Comment by mattforbes-gr** [comment] 2021-02-09 23:53
I believe this is still an issue with serialized dags. We are dynamically generating dags and had to resort to randomizing our dag py file name to force stale serialized dags to be deleted.

**Comment by ashb** [comment] 2021-02-10 12:03
> Hey @kaxil @ashb - are we going to fix it ? Or maybe it already is fixed with the serialization ?

No, still remains to be fixed.

**Comment by leonsmith** [comment] 2021-03-01 18:17
Started to debug this a little.

I’m thinking the problem is the wrong assumption that you can set is_active=True on any dags with the same file path.
So the fix should be patching out the else statement here:
https://github.com/apache/airflow/blob/1.10.12/airflow/models/dag.py#L1917

I think `is_active` is set to `True` when the we call the DagBag `sync_to_db` method in the when parsing the dags.

Going to run a bit of a test & will update to see if that resolves the issue

**Comment by HaloKo4** [comment] 2021-03-01 18:21
if the expected behavior is to remove/rename the old dag_id how are we expected to read its past logs?
This will require to also modify files in the disk otherwise they will be unaccessable.

**Comment by kaxil** [comment] 2021-03-01 18:26
For now, you will have to just use a different file for the new (or renamed) DAG.

**Comment by leonsmith** [comment] 2021-03-02 15:49
So this also effects dynamic dags.


```python
from datetime import datetime

from airflow.models import DAG

numbers = {1, 2, 3}

for number in numbers:
    dag = DAG(
        dag_id=f'dag_{number}',
        schedule_interval='@once',
        start_date=datetime(2020, 1, 1),
        catchup=False
    )
```

and then you switched numbers to a different set say "{1, 2}"
`dag_3` will always appear as active still.

**Comment by jhtimmins** [comment] 2021-05-06 05:39
Hi @wolfier are you interested in submitting a fix for this?

**Comment by PeterLambe** [comment] 2021-05-07 17:13
This bug is affecting our instance as well. Is there a workaround? Is it safe to press "Delete DAG" on the old DAG from the ui?

**Comment by wolfier** [comment] 2021-05-08 04:59
I'm down to investigate what @leonsmith has pointed but for the master branch.

**Comment by PeterLambe** [comment] 2021-05-10 15:35
Confirming that pressing "Delete DAG" on the old DAG will remove it from the metadata tables properly

**Comment by SamWheating** [comment] 2021-07-20 00:02
👋 Hey there, I was looking into this issue a bit today and it looks like the code which deactivates stale DAGs will never be reached if the value of `scheduler.num_runs` isn't set. 

From the source code:
https://github.com/apache/airflow/blob/3234527284ce01db67ba22c544f71ddaf28fa27e/airflow/jobs/scheduler_job.py#L652-L664

So that call to `run_scheduler_job` will only every break the loop _if_ the value of `scheduler.num_runs` is set (the default is -1, for an infinite loop):

https://github.com/apache/airflow/blob/2fea4cdceaa12b3ac13f24eeb383af624aacb2e7/airflow/jobs/scheduler_job.py#L756-L762

Is this intended behaviour, or something that should be fixed / better documented?

**Comment by SamWheating** [comment] 2021-07-20 00:12
But even then, as @leonsmith identified, a renamed DAG will be marked as active again on the next pass:
https://github.com/apache/airflow/blob/3234527284ce01db67ba22c544f71ddaf28fa27e/airflow/models/dag.py#L2476-L2497

Is the assumption that 1 file corresponds to 1 DAG still valid? That would contradict patterns such as the [DAG factory](https://github.com/ajbosco/dag-factory) which load many DAGs from a single `.py` file. 

Anyways, maybe we should be leaving DAGs as deactivated if they haven't been parsed in a given interval? I'm happy to submit a fix for this and I'll have some time in the next few days, however I'd like some guidance from the maintainers on what is the intended behaviour / what are the supported patterns before I start 😄

**Closed as completed** 2021-09-18 19:52 UTC
Labels: kind:bug, area:core
