### ISSUE TITLE
SFTP Sensor fails to locate file

### ISSUE THREAD

**Issue by RishuGuru** [apache/airflow#28121] opened 2022-12-05 15:15 UTC
### Apache Airflow version

2.5.0

### What happened

While creating SFTP sensor I have tried to find a file under directory. But I was getting error as Time Out, not found.
So after debugging code found that there is a issue with [poke function](https://airflow.apache.org/docs/apache-airflow-providers-sftp/stable/_modules/airflow/providers/sftp/sensors/sftp.html#SFTPSensor.poke).

As after getting matched file we are trying to find last modified time of the file using [self.hook.get_mod_time](https://airflow.apache.org/docs/apache-airflow-providers-sftp/stable/_modules/airflow/providers/sftp/hooks/sftp.html#SFTPHook.get_mod_time) which take full path (path + filename) and we are giving only filename as arguments.

### What you think should happen instead

I have solved that issue by adding path with filename and then calling [self.hook.get_mod_time](https://airflow.apache.org/docs/apache-airflow-providers-sftp/stable/_modules/airflow/providers/sftp/hooks/sftp.html#SFTPHook.get_mod_time) function.

Here is modified code,
```

def poke(self, context: Context) -> bool:
        self.hook = SFTPHook(self.sftp_conn_id)
        self.log.info("Poking for %s, with pattern %s", self.path, self.file_pattern)

        if self.file_pattern:
            file_from_pattern = self.hook.get_file_by_pattern(self.path, self.file_pattern)
            if file_from_pattern:
                '''actual_file_to_check = file_from_pattern'''
                actual_file_to_check = self.path + file_from_pattern
            else:
                return False
        else:
            actual_file_to_check = self.path

        try:
            mod_time = self.hook.get_mod_time(actual_file_to_check)
            self.log.info("Found File %s last modified: %s", str(actual_file_to_check), str(mod_time))
        except OSError as e:
            if e.errno != SFTP_NO_SUCH_FILE:
                raise e
            return False
        self.hook.close_conn()
        if self.newer_than:
            _mod_time = convert_to_utc(datetime.strptime(mod_time, "%Y%m%d%H%M%S"))
            _newer_than = convert_to_utc(self.newer_than)
            return _newer_than <= _mod_time
        else:
            return True

```

### How to reproduce

You can get same issue by creating a DAG as mentioned 

```
with DAG(
        dag_id='sftp_sensor_dag',
        max_active_runs=1,
        default_args=default_args,
) as dag:
 file_sensing_task = SFTPSensor(
        task_id='sensor_for_file',
        path= "Weekly/11/",
        file_pattern = "*pdf*,
        sftp_conn_id='sftp_hook_conn',
        poke_interval=30
    )
```

### Operating System

Microsoft Windows [Version 10.0.19044.2251]

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2022-12-05 15:57
Nice catch

**Comment by eladkal** [comment] 2022-12-05 16:02
Duplicate of https://github.com/apache/airflow/issues/27418 ?

**Comment by RishuGuru** [comment] 2022-12-05 16:23
yes @eladkal

**Comment by potiuk** [comment] 2022-12-05 16:28
This one is more complete - I will close the other one :) (sorry @eladkal )

**Closed as completed** 2023-02-13 23:12 UTC
Labels: kind:bug, good first issue, area:core

**Comment by andreeaciupe** [comment] 2023-09-06 13:15
is this issues solved? I can reproduce it using  apache-airflow-providers-sftp==4.2.1 and apache-airflow-providers-sftp==4.1.0

**Comment by eladkal** [comment] 2023-09-06 17:27
> is this issue solved? 

Did you check the change log? it will tell you in what version the PR was released.
