### ISSUE TITLE
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query'

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [apache/airflow#14818] opened 2021-03-16 02:36 UTC
**Apache Airflow version**: 2.0.1

**What happened**:

I'm seeing the following when running migrations in Airflow using [SQLAlchmey 1.4.0](https://pypi.org/project/sqlalchemy/1.4.0/):
```
Traceback (most recent call last):
  File "/home/runner/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/cli/commands/db_command.py", line 31, in initdb
    db.initdb()
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/utils/db.py", line 549, in initdb
    upgradedb()
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/utils/db.py", line 684, in upgradedb
    command.upgrade(config, 'heads')
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/migrations/env.py", line 108, in <module>
    run_migrations_online()
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/migrations/env.py", line 102, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 548, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/command.py", line 283, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/script/base.py", line 365, in _upgrade_revs
    revs = list(revs)
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/script/revision.py", line 916, in _iterate_revisions
    uppers = util.dedupe_tuple(self.get_revisions(upper))
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/script/revision.py", line 457, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/script/revision.py", line 640, in _resolve_revision_number
    self._revision_map
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/util/langhelpers.py", line 234, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/script/revision.py", line 156, in _revision_map
    for revision in self._generator():
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/script/base.py", line 115, in _load_revisions
    script = Script._from_filename(self, vers, file_)
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/script/base.py", line 904, in _from_filename
    module = util.load_python_file(dir_, filename)
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/runner/.local/lib/python3.7/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/migrations/versions/82b7c48c147f_remove_can_read_permission_on_config_.py", line 28, in <module>
    from airflow.www.app import create_app
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/www/app.py", line 38, in <module>
    from airflow.www.extensions.init_views import (
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/www/extensions/init_views.py", line 29, in <module>
    from airflow.www.views import lazy_add_provider_discovered_options_to_connection_form
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/www/views.py", line 96, in <module>
    from airflow.www import auth, utils as wwwutils
  File "/home/runner/.local/lib/python3.7/site-packages/airflow/www/utils.py", line 27, in <module>
    from flask_appbuilder.models.sqla.interface import SQLAInterface
  File "/home/runner/.local/lib/python3.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 16, in <module>
    from sqlalchemy_utils.types.uuid import UUIDType
  File "/home/runner/.local/lib/python3.7/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/home/runner/.local/lib/python3.7/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/home/runner/.local/lib/python3.7/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/home/runner/.local/lib/python3.7/site-packages/sqlalchemy_utils/functions/database.py", line 11, in <module>
    from .orm import quote
  File "/home/runner/.local/lib/python3.7/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/home/runner/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py)
```

Downgrading to [1.3.23](https://pypi.org/project/sqlalchemy/1.3.23/) resolves this issue.

**How to reproduce it**:

```
apache-airflow[crypto,celery,amazon,mysql,jdbc,password,redis,slack,snowflake,ssh,google,databricks,mongo,zendesk,papermill,salesforce]==2.0.1
iniconfig==1.1.1
sqlparse==0.4.1
google-api-python-client===1.12.8
google-auth==1.27.0
google-api-core==1.26.0
avro-python3==1.10.0
databricks-connect==7.3.8
matplotlib==3.3.4
scikit-learn==0.24.1
ipykernel==5.4.3
flower==0.9.5
```

**Comment by stijndehaes** [comment] 2021-03-16 07:38
I am running into a similar issue with airflo 1.10.14.

```
 Traceback (most recent call last):
	   File "scripts/test_airflow.py", line 15, in <module>
	     db.initdb()
	   File "/home/runner/work/lighthouse-datafy/lighthouse-datafy/data-plane/airflow/build/venv/lib/python3.7/site-packages/airflow/utils/db.py", line 345, in initdb
	     dag.sync_to_db()
	   File "/home/runner/work/lighthouse-datafy/lighthouse-datafy/data-plane/airflow/build/venv/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
	     return func(*args, **kwargs)
	   File "/home/runner/work/lighthouse-datafy/lighthouse-datafy/data-plane/airflow/build/venv/lib/python3.7/site-packages/airflow/models/dag.py", line 1507, in sync_to_db
	     from airflow.models.serialized_dag import SerializedDagModel
	   File "/home/runner/work/lighthouse-datafy/lighthouse-datafy/data-plane/airflow/build/venv/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 35, in <module>
	     from airflow.serialization.serialized_objects import SerializedDAG
	   File "/home/runner/work/lighthouse-datafy/lighthouse-datafy/data-plane/airflow/build/venv/lib/python3.7/site-packages/airflow/serialization/serialized_objects.py", line 40, in <module>
	     from airflow.www.utils import get_python_source
	   File "/home/runner/work/lighthouse-datafy/lighthouse-datafy/data-plane/airflow/build/venv/lib/python3.7/site-packages/airflow/www/utils.py", line 40, in <module>
	     import flask_admin.contrib.sqla.filters as sqlafilters
	   File "/home/runner/work/lighthouse-datafy/lighthouse-datafy/data-plane/airflow/build/venv/lib/python3.7/site-packages/flask_admin/contrib/sqla/__init__.py", line 2, in <module>
	     from .view import ModelView
	   File "/home/runner/work/lighthouse-datafy/lighthouse-datafy/data-plane/airflow/build/venv/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 18, in <module>
	     from flask_admin.contrib.sqla.tools import is_relationship
	   File "/home/runner/work/lighthouse-datafy/lighthouse-datafy/data-plane/airflow/build/venv/lib/python3.7/site-packages/flask_admin/contrib/sqla/tools.py", line 4, in <module>
	     from sqlalchemy.ext.declarative.clsregistry import _class_resolver
	 ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.clsregistry'
```
Downgrading also fixes the problem

**Comment by eladkal** [comment] 2021-03-16 10:25
Duplicate of https://github.com/apache/airflow/issues/14811

**Closed as completed by eladkal** 2021-03-16 10:25 UTC
Labels: kind:bug, duplicate
