### ISSUE TITLE
Airflow 2.1.0 delete dag_run when trigger sla 

### ISSUE THREAD

**Issue by penggongkui** [apache/airflow#16934] opened 2021-07-12 03:45 UTC
when sla happen, not always delete the dag_run, but it happen very frequently

when dag_run is deleted, my unfinished task will not schedule

mysql version: 8
executor: celery
with multi scheduler

if need anything else info please let me know

also, sometimes will call the sla callback twice(it is not the big problem)

**Comment by penggongkui** [comment] 2021-07-12 11:23
after dig the mysql binlog, find out it is not delete, it update the dag_run.dag_id to null
![image](https://user-images.githubusercontent.com/49138427/125279480-91e74200-e346-11eb-9594-f43815d9887a.png)

**Comment by penggongkui** [comment] 2021-07-12 11:32
[2021-07-12 00:01:20,754] {scheduler_job.py:396} INFO - Running SLA Checks for data_daily
[2021-07-12 00:01:22,501] {scheduler_job.py:474} INFO - Calling SLA miss callback

**Comment by penggongkui** [comment] 2021-07-12 11:32
[2021-07-12 00:01:20,754] {scheduler_job.py:396} INFO - Running SLA Checks for data_daily
[2021-07-12 00:01:22,501] {scheduler_job.py:474} INFO - Calling SLA miss callback

**Comment by penggongkui** [comment] 2021-07-12 11:34
following is the schedule log, so i think something happened between scheduler_job.py:396 and scheduler_job.py:474

[2021-07-12 00:01:20,754] {scheduler_job.py:396} INFO - Running SLA Checks for data_daily
[2021-07-12 00:01:22,501] {scheduler_job.py:474} INFO - Calling SLA miss callback

**Comment by penggongkui** [comment] 2021-07-12 12:51
find the same issue #16896 ,

https://github.com/apache/airflow/blob/2.1.0/airflow/jobs/scheduler_job.py#L461

this line will use the same logic with delete taskinstance

**Comment by ashb** [comment] 2021-07-14 08:32
Duplicate of #16934

**Comment by uranusjr** [comment] 2021-07-14 08:39
@ash This is #16934, did you tag the wrong issue?

**Comment by ashb** [comment] 2021-07-14 09:11
🤦🏻

**Comment by ashb** [comment] 2021-07-14 09:12
Duplicate of #16896

**Closed as completed by ashb** 2021-07-14 09:12 UTC
Labels: kind:bug
