### ISSUE TITLE
Skipping dag runs on established daily DAG

### ISSUE THREAD

**Issue by isaac-florence** [apache/airflow#28293] opened 2022-12-11 19:49 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow 2.4.3, running on Kubernetes with High-Availability Scheduler (2 pods). Database is postgres 10.21

I have a dag that has been running for two months with this timetable: `timetable=CronTriggerTimetable("40 5 * * *", timezone = 'UTC')` (which has not changed). It has run reliably every day as expected however yesterday it simply did not run. I have checked for errors and there were none, and checking the scheduler logs (on both pods) it appears no evaluation of the dag run was done in either scheduler instance. in the cli inspecting the next 60 run execution dates indicates there is no problem with the timetable's interpretation

My suspiscion is that a race condition in the `SELECT ... FOR UPDATE` of the database may have prevented either scheduler executing the DAG. Is this possible? Otherwise how can this have happened? 

### What you think should happen instead

The dag should have run as it always has previously

### How to reproduce

I wish I knew! I can't work it out.

### Operating System

RedHat Enterprise Linux 8

### Versions of Apache Airflow Providers

2.4.3

### Deployment

Other Docker-based deployment

### Deployment details

High availability schedulers (n=2) on OpenShift Kubernetes. Postgres database (version 10.21

### Anything else

This has happened once before, just under a month ago, on the same DAG.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2022-12-27 20:21
Duplicate of https://github.com/apache/airflow/issues/27399

**Closed as completed by potiuk** 2022-12-27 20:21 UTC
Labels: kind:bug, duplicate, area:core
