### ISSUE TITLE
"what scheduled this task instance" in a TaskInstance's context?

### ISSUE THREAD

**Issue by toryhaavik** [apache/airflow#1111] opened 2016-03-03 21:33 UTC
I have a workflow where a step in the DAG gathers a bunch of statistics and facts about the current state of the data and delivers a nice email to people who are interested in seeing it.  What doesn't work so well is when I run a backfill for a month's worth of data and spam everyone with 30 emails.

It would be nice to be able to distinguish between regularly scheduled runs and backfill runs in the context passed into a python function or Operator's `execute` method.  This way, I could add logic that said, if this is a backfill, don't send emails.

Is this something that can be achieved in another manner?  If not, is it something that is interesting to others?  Thanks!

**Comment by mistercrunch** [comment] 2016-03-04 05:06
I agree that the context should expose an `is_backfill` boolean for people to use. In the meantime, the way we've been doing this is adding custom logic in DAGs themselves. Say if you were to add you own `is_backfill = False` at the top of your DAG, you could alter it when running backfill to set that temporarily to True. Based on this new flag, you can change anything in your DAG at will in your script, like skipping that email sending task for instance.

**Comment by toryhaavik** [comment] 2016-03-04 16:29
Cool, thanks for the workaround.  Another similar piece of information that would be cool to propagate into the task execution code is whether `-f/--force` was included in the invocation, because we have some systems that also have this notion and it would make sense to pass the flag as far as it needs to go.  Is that also useful to you/others?

I haven't gotten around to getting a dev version of Airflow setup, but this is pretty compelling for us, so I think I'll try to work on it soon.  I'd imagine a new argument(s) to the `run(...)` method [here](https://github.com/airbnb/airflow/blob/master/airflow/bin/cli.py#L73) would be a good place to start?

**Comment by toryhaavik** [comment] 2016-03-04 20:53
This is probably a dumb question, but I have little experience with SQLAlchemy.  I have created a new column for the TaskInstance Model, how do I get airflow to change the database schema?  Initial tests complain about a lack of that column in the db, which is understandable.  I'll be happy to add some more documentation on the CONTRIBUTING page. Thanks!

**Comment by r39132** [comment] 2016-03-13 21:44
@mistercrunch Do you have an example? Are you proposing that we alter this manually? In this case, we cannot run both backfill and current runs in unison?

**Comment by toryhaavik** [comment] 2016-03-13 22:24
Something like setting `IS_BACKFILL=True` at the top of the dag file and then using `if IS_BACKFILL:...` in the task logic.  Yes, you can't run scheduled and back filled tasks at the same time so the other option is separate dags.

**Comment by mistercrunch** [comment] 2016-03-13 23:02
Since the backfill is orchestrated locally, you just alter that variable before running the command.

**Comment by r39132** [comment] 2016-03-14 01:35
Hmn.. right. but the issue is that with LocalExecutor running locally as well, unless I disable the DAG, the scheduler will be running in parallel with the backfill and will also see that variable change.. and unfortunately, execute the wrong code path.

**Comment by mistercrunch** [comment] 2016-03-14 03:59
@r39132 well you need a dev environment somewhere, that's where this would be taking place

**Comment by bolkedebruin** [comment] 2016-05-08 13:29
Please track AIRFLOW-20 for this. Closing here

**Closed as completed by bolkedebruin** 2016-05-08 13:29 UTC
