### ISSUE TITLE
"next" query parameter is ignored on login redirect

### ISSUE THREAD

**Issue by zbstof** [apache/airflow#10199] opened 2020-08-06 14:35 UTC
**Apache Airflow version**: 2.0.0.dev0, built from HEAD master branch

**Environment**: don't know, maybe kubernetes

**What happened**:
1. Log out of airflow.
2. Try to navigate directly to https://airflow.mycorp.com/variables/list (for example from browser bookmarks)
2a. URL should become `https://airflow.mycorp.com/login/?next=https%3A%2F%2Fairflow.mycorp.com%2Fvariable%2Flist%2F`
3. Enter username/password, hit enter
4. Browser sends POST request to `https://airflow.mycorp.com/login/?next=https%3A%2F%2Fairflow.mycorp.com%2Fvariable%2Flist%2F`
5. Response is returned with status code 302 and LOCATION header `https://airflow.mycorp.com/`

**What you expected to happen**:

5. Response is returned with status code 302 and LOCATION header `https://airflow.mycorp.com/variables/list`

**Anything else we need to know**:

Reproduces every time

**Comment by eladkal** [comment] 2022-01-05 18:11
I'm not able to reproduce this on latest main:

![2022-01-05_20-07-04](https://user-images.githubusercontent.com/45845474/148267066-c344197d-3ce0-4ae2-b6f1-3c5079a891bb.gif)


Closing as can't reproduce.

**Closed as completed by eladkal** 2022-01-05 18:11 UTC
Labels: kind:bug, Can't Reproduce, area:webserver
