### ISSUE TITLE
Airflow scheduler memory continue to increase using docker image apache/airflow:2.1.0

### ISSUE THREAD

**Issue by MADJIYoucef** [apache/airflow#16332] opened 2021-06-08 16:24 UTC
I have a problem with scheduler memory that continue to increase when i am using docker image. 
I am using Celery Executor
![image](https://user-images.githubusercontent.com/14239278/121222326-bf902580-c886-11eb-851f-dd78ea5fa43d.png)
Any solution ?? 
Thanks in advance

**Comment by jedcunningham** [comment] 2021-06-08 20:08
Thanks for reporting this @MADJIYoucef.

Duplicate of #14924

**Closed as completed by jedcunningham** 2021-06-08 20:08 UTC
Labels: kind:bug, duplicate
