### ISSUE TITLE
Add a textbox in the UI for each DAG that can be used to write a comment related to a DAG

### ISSUE THREAD

**Issue by SangwanP** [apache/airflow#18437] opened 2021-09-22 16:51 UTC
### Description

A textbox is added to the UI next to each DAG to write/modify information regarding the DAG directly in the UI.

### Use case/motivation

I work on a team and currently we are unable to relay information regarding a DAG through the UI. For example: reason why a maintainer temporarily disabled a particular DAG.
The _DAG doc_md_ is not very useful in this case since that lives in code - which has to go through a review process. It is a better candidate for displaying lasting information in our case.
In general, this feature can be used to display/modify any information regarding a DAG.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2021-09-22 18:35
There was an ongoing work here: https://github.com/apache/airflow/pull/17181 on similar thing, but it was abandoned. Maybe you would like to teke-over and complete it @SangwanP ?

**Comment by potiuk** [comment] 2021-09-22 18:36
And the issue is described here as well https://github.com/apache/airflow/pull/17181

**Comment by potiuk** [comment] 2021-09-22 18:37
I mark it as duplicate of #1781 and close - but you can work on it @San if you would like to get it.

**Closed as completed by potiuk** 2021-09-22 18:37 UTC
Labels: kind:feature, duplicate

**Comment by SangwanP** [comment] 2021-09-22 19:29
@potiuk - Okay, I'll try to get to it. Just a question - I see that the scope of the linked issue is quite large (notes for multiple tasks accessible from multiple places), I assume there is no issue if I _only_ work on the 'Dag notes' functionality of that issue?
