### ISSUE TITLE
auto refresh does not work in grid mode

### ISSUE THREAD

**Issue by rotemseekingalpha** [apache/airflow#26173] opened 2022-09-06 06:00 UTC
### Apache Airflow version

2.3.4

### What happened

Upgraded to Airflow 2.3.4 from Airflow 2.3.3.
Ran a DAG.
Auto refresh keeps turning off in grid mode.
Works in graph mode.

### What you think should happen instead

auto refresh should work the same way it did in previous versions (and/or graph mode)

### How to reproduce

Run a dag with multiple steps on Airflow 2.3.4 and monitor progress using grid mode.

### Operating System

Ubuntu 20.04.5 LTS

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon     @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_amazon-5.0.0-py3-none-any.whl
apache-airflow-providers-common-sql @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_common_sql-1.1.0-py3-none-any.whl
apache-airflow-providers-ftp        @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_ftp-3.1.0-py3-none-any.whl
apache-airflow-providers-http       @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_http-4.0.0-py3-none-any.whl
apache-airflow-providers-imap       @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_imap-3.0.0-py3-none-any.whl
apache-airflow-providers-mongo      @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_mongo-3.0.0-py3-none-any.whl
apache-airflow-providers-mysql      @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_mysql-3.2.0-py3-none-any.whl
apache-airflow-providers-pagerduty  @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_pagerduty-3.0.0-py3-none-any.whl
apache-airflow-providers-postgres   @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_postgres-5.2.0-py3-none-any.whl
apache-airflow-providers-redis      @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_redis-3.0.0-py3-none-any.whl
apache-airflow-providers-sendgrid   @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_sendgrid-3.0.0-py3-none-any.whl
apache-airflow-providers-slack      @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_slack-5.1.0-py3-none-any.whl
apache-airflow-providers-sqlite     @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_sqlite-3.2.0-py3-none-any.whl
apache-airflow-providers-ssh        @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_ssh-3.1.0-py3-none-any.whl
apache-airflow-providers-vertica    @ file:///home/airflow/deploy/wheelfreeze/wheels/apache_airflow_providers_vertica-3.2.0-py3-none-any.whl
```

### Deployment

Virtualenv installation

### Deployment details

Python 3.8.13

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by joao-aguilera-c** [comment] 2022-09-06 18:42
Just adding, this is the error on gif:

![auto-refresh_not_working](https://user-images.githubusercontent.com/68448759/188713926-6b72a0bd-24bb-4574-b7d0-42efa1d08177.gif)

**Comment by Gollum999** [comment] 2022-09-07 12:44
Duplicate of #25949.
Broken by #25042, fixed by #25950.

**Closed as completed** 2022-09-07 19:53 UTC
Labels: kind:bug, area:UI

**Comment by pauloventurab** [comment] 2023-08-18 10:26
Hello Guys, I would like to reopen this issue. It is not working on 2.6.3 as well. The same gift explain my issue.

**Comment by potiuk** [comment] 2023-08-18 10:57
> Hello Guys, I would like to reopen this issue. It is not working on 2.6.3 as well. The same gift explain my issue. Tell me if you need something else from me.

Can you please open a new issue with more information, your own recording what happens and some details (maybe errors you see in the console). The issue has been fixed - this is likely a different issue that looks similar, but we will never know until you submit all the details (Note that many people do not have that issue, so you likely experience something specific to your case, that's why it's a different issue).

Generally speaking - the rule of thumb is tha twe are not reopening issues that have been already closed and we have good reason to believe the root cause of it has been fixed. Especially if there are new evidences that can be used to diagnose it.

Please open a new issue and add some evidences there.
