### ISSUE TITLE
celery_executor.py remove_running got an unexpected keyword

### ISSUE THREAD

**Issue by asmasehlii** [apache/airflow#40099] opened 2024-06-06 15:06 UTC
### Apache Airflow version

2.9.1

### What happened?

airflow/providers/celery/executors/celery_executor.py got an expected keyword running_remove: 
![image](https://github.com/apache/airflow/assets/99139747/ff5437a3-9f6d-4017-a777-4a62dec58e42)
so tasks were stacked at scheduled state 

### How to reproduce

remove the last argument resolve the problem

### Operating System

linux

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vatsrahul1001** [comment] 2024-06-06 15:29
duplicate of https://github.com/apache/airflow/issues/40097

**Comment by vatsrahul1001** [comment] 2024-06-07 05:05
Fix https://github.com/apache/airflow/pull/40012/files

**Comment by vatsrahul1001** [comment] 2024-06-10 04:46
@asmasehlii can we close this issue as this is fixed in https://github.com/apache/airflow/pull/40012/files

1. Celery provider 3.7.2rc1 will be released before Airflow 2.9.2
2. Celery provider 3.7.1 is yanked

**Comment by asmasehlii** [comment] 2024-06-10 07:12
and removing the last argument here : super().change_state(key, state, info, remove_running=remove_running)
solve the problem or no ? i mean i changed it like this :  super().change_state(key, state, info) and it's working right now

**Comment by potiuk** [comment] 2024-06-10 08:10
This issue is solved in the last Celery Provider (3.7.2) also 3.7.1 has been yanked. Upgrade to 3.7.2 to fix it.

**Closed as completed** 2024-06-10 08:10 UTC
Labels: kind:bug, duplicate, pending-response, area:core
