### ISSUE TITLE
Backfill/execution_date from UI

### ISSUE THREAD

**Issue by pavel-lexyr** [apache/airflow#14854] opened 2021-03-17 15:51 UTC
**Description**

A way to manipulate `execution_date`, or triggering backfills/catchups from the Web GUI is proposed.

**Use case / motivation**

Web UI and the CLI interface have separate privileges and responsibilities. CLI is mostly geared towards maintenance of the Airflow system itself - while the Web GUI is intended for users using Airflow to manage tasks. Backfill is aligned with the second more closely - it makes no sense that it's not available through the web interface.

[The sentiment is shared by multiple users.](https://github.com/AnkurChoraywal/airflow-backfill-util)

**Are you willing to submit a PR?**

No.

**Related Issues**

Not that I know of.

**Comment by eladkal** [comment] 2021-11-22 12:43
I believe this is depended on having an endpoint first https://github.com/apache/airflow/issues/18816

**Comment by uranusjr** [comment] 2021-11-25 09:28
I understand the need to trigger backfills from the UI, but what do you mean by “manimupating execution_date”?

**Comment by pavel-lexyr** [comment] 2021-11-25 18:26
> I understand the need to trigger backfills from the UI, but what do you mean by “manipulating execution_date”?

Running a backfill for a date before the DAG start date, for example. Some way to set it from GUI.

**Comment by uranusjr** [comment] 2021-11-25 18:35
So basically replicating what’s possible from the CLI, right? If that’s the case, #18816 is our main blocker for this.

**Comment by potiuk** [comment] 2022-10-10 06:15
Closing as essentially duplicate of #18816

**Closed as completed by potiuk** 2022-10-10 06:15 UTC
Labels: kind:feature, area:backfill
