### ISSUE TITLE
GCP Cloud Run Operator?

### ISSUE THREAD

**Issue by brucearctor** [apache/airflow#31447] opened 2023-05-21 13:21 UTC
### Description

There is a great Operator for Cloud Functions:  https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/cloud/functions.html  

But, if needing a bit more compute/control than the functions runtime supports, utilizing Cloud Run could be ideal.  

### Use case/motivation

Looking to be able to trigger Cloud Run jobs from Airflow akin to Cloud Functions [ when needing to compute slightly larger things that don't work with Functions ].  

### Related issues

I did not see any related issues.

Hoping for some comment on whether this would be welcomed.  If nobody else would address, but would be a welcomed contribution, then I am happy to dig into contributing.  

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2023-05-21 13:23
Duplicate of https://github.com/apache/airflow/issues/24730

**Closed as not planned by eladkal** 2023-05-21 13:23 UTC
Labels: kind:feature, duplicate, needs-triage

**Comment by eladkal** [comment] 2023-05-21 13:28
feel free to help with reviewing the current PR to add the requested functionality https://github.com/apache/airflow/pull/28525

**Comment by brucearctor** [comment] 2023-05-21 13:52
Hi @eladkal -- are you sure that this is a duplicate, and that #28525 addresses this?  It appears both are about CloudRunJobs [ https://cloud.google.com/run/docs/create-jobs ] which is related albeit different from Cloud Run [ https://cloud.google.com/run/docs/overview/what-is-cloud-run ]?  From what I recall about CloudRunJobs [ has been awhile, but I opted to not bother using ], it can be used for jobs, but is more specialized in what it can do [ read: less flexible ] than Cloud Run.
