### ISSUE TITLE
Airflow some filters not working in 2.6.1 version

### ISSUE THREAD

**Issue by Raul824** [apache/airflow#31466] opened 2023-05-23 00:22 UTC
### Apache Airflow version

2.6.1

### What happened

To manage multiple dags we use browse -> dag runs / task instances
To clear or marking as failed for multiple tasks and dags.

We were using filters in 2.5.x versions which were logical date, start date and dag id contains to clear specific set of dags specific instances.

We upgraded to 2.6.1 and added pgbouncer as well.

Now it seems apart from first filter conditions none are working.
Some examples are 
"starts with" work 

And most of the filters which are not working shows filt_undefined in the url.

?_flt_undefined_state=failed (if anything is selected apart from first filter condition)

As a workaround if i put ?_flt_2_dag_id=DWH it shows all dag_id which contains DWH.

due to ?_flt_undefined it seems the filters are also not showing after you click on add filter again.

### How to reproduce

Go to browse -> dag runs/task_instances.

Add any filter and use any filter condition other than first and click on search.
In the url you will see flt_undefined and dag record count will be same.

### Operating System

Red Hat Enterprise Linux 8

### Versions of Apache Airflow Providers

2.6.1

### Deployment

Docker-Compose

### Deployment details

postgres 13
pgbouncer 1.18

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment] 2023-06-02 13:44
This looks like a flask-appbuilder issue https://github.com/dpgaspar/Flask-AppBuilder/issues/2004 . Can you please share the flask-appbuilder version? `pip freeze | grep -i flask`

**Comment by eladkal** [comment] 2023-06-02 19:04
> This looks like a flask-appbuilder issue https://github.com/dpgaspar/Flask-AppBuilder/issues/2004 . Can you please share the flask-appbuilder version? pip freeze | grep -i flask

There may be something else going on because this issue reported as fixed in Flask-AppBuilder 4.3.1 but @hussein-awala  reported the issue is reproducible on main branch which already has `Flask-AppBuilder==4.3.1`

**Comment by tirkarthi** [comment] 2023-06-03 02:22
I was unable to reproduce this on main branch. Downgrading flask-appbuilder I was able to reproduce this. Since the patch is there let me debug the values that flask-appbuilder constructs in my virtual environment.

**Comment by tirkarthi** [comment] 2023-06-03 02:25
The PR that did the upgrade also mentions the same issue.

https://github.com/apache/airflow/pull/31203
https://github.com/apache/airflow/issues/31156

**Comment by pankajastro** [comment] 2023-06-03 11:20
right, `flask-appbuilder` upgrade PR should fix this and it is in 2.6.2 release milestone.

**Comment by hussein-awala** [comment] 2023-06-03 11:53
> There may be something else going on because this issue reported as fixed in Flask-AppBuilder 4.3.1 but @hussein-awala reported the issue is reproducible on main branch which already has Flask-AppBuilder==4.3.1

@eladkal I couldn't reproduce the issue anymore using the main branch. It's possible that the CI image was not up to date at the time of my testing. We can consider this task as completed and close it.

**Closed as completed** 2023-06-03 11:54 UTC
Labels: kind:bug, area:webserver, priority:high, affected_version:main_branch
