### ISSUE TITLE
Log links in grid view

### ISSUE THREAD

**Issue by NilsJPWerner** [apache/airflow#28163] opened 2022-12-06 15:39 UTC
### Description

In the log view urls are automatically converted to links. This doesn't happen in the logs in grid view. It would be great if that behavior was matched. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by adarsha-samsung** [comment] 2022-12-07 05:27
@potiuk,  can I take up this task ?

**Comment by potiuk** [comment] 2022-12-07 07:40
Feel free

**Comment by MohammadWasi** [comment] 2022-12-20 08:41
Hi Can you please provide more details/screenshots.
I can’t find the log view in UIw

**Comment by tirkarthi** [comment] 2024-02-01 05:11
This looks like a duplicate of https://github.com/apache/airflow/issues/35280

**Comment by bbovenzi** [comment] 2024-02-01 17:10
Closed by https://github.com/apache/airflow/pull/36816

**Closed as completed by bbovenzi** 2024-02-01 17:10 UTC
Labels: kind:feature, good first issue, area:UI
