### ISSUE TITLE
MySQL image compatibilty issue for linux/arm64

### ISSUE THREAD

**Issue by arvindeybram** [apache/airflow#16158] opened 2021-05-29 11:37 UTC
**Apache Airflow version**:

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: M1 Chipset / linux/arm architecture
- **OS** (e.g. from /etc/os-release): Big Sur 11.3.1
- **Kernel** (e.g. `uname -a`): 
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**: I thought the image for MySQL would be pulled

 docker image needs to be updated incase of arm architecture

**How to reproduce it**: Running development script in MacBook m1 chipset 

**Anything else we need to know**:

**Comment by potiuk** [comment] 2021-05-29 11:42
We have no support yet for arm bu tit is coming. Duplicate of #15635

**Closed as completed by potiuk** 2021-05-29 11:42 UTC
Labels: kind:bug
