### ISSUE TITLE
Not showing "Last Run" on Airflow Web UI

### ISSUE THREAD

**Issue by Yeonghobyun** [apache/airflow#21141] opened 2022-01-27 06:31 UTC
### Apache Airflow version

2.1.4

### What happened

After upgrading to airflow 1.10.10 to 2.1.4, I cannot see 'Last Run' column value on dags page on airflow web ui.

### 
![image](https://user-images.githubusercontent.com/30676005/151303105-a7c4b8fe-cdd5-4b84-817e-33318d6355cb.png)

Why does this happen?

### What you expected to happen

It seems to be a problem with the version of the sources ​​related to airflow.

Or, I think it may be the cause of not executing "airflow db init" while upgrading to 2.1.4.

### How to reproduce

1. Install airflow version 1.10.10
2. Upgrade airflow to 2.1.4

### Operating System

Linux

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by PApostol** [comment] 2022-01-27 11:17
I have faced the same issue when upgrading from 2.0.2 to 2.1.4, but it was resolved after upgrading again to 2.2.3.

**Comment by Yeonghobyun** [comment] 2022-01-28 01:09
> I have faced the same issue when upgrading from 2.0.2 to 2.1.4, but it was resolved after upgrading again to 2.2.3.

Is there any way to fix the source other than upgrading to 2.2.3?
We are just upgrading airflow 2.1.4 in production environment.
Upgrading to 2.2.3 is burdensome.

**Comment by potiuk** [comment] 2022-01-28 14:46
Unforttunately not. That was quite a big fix involving quite a number of change that was only implemented and released in 2.2.0 https://github.com/apache/airflow/pull/17732. It was to big to be cherry-picked to 2.1 and it is not likely it will ever will.

I think your best bet is to migrate to upcoming 2.2.4 (it is going to be relased in a week or so). There are a number of other, small fixes implemtned in 2.2 line that it will allow you to take advantage of.

Closing as duplicate of #17732

**Closed as completed by potiuk** 2022-01-28 14:46 UTC
Labels: kind:bug, area:UI

**Comment by zj1081923** [comment] 2023-07-06 02:15
@Yeonghobyun  I get same error on 2.6.2 version.
Did you resolve this issue?

**Comment by potiuk** [comment] 2023-07-06 08:57
> @Yeonghobyun I have same error on version 2.6.2

Thenm I think it's a different issue, and you should raise it wth all details as separate issue explaining circumstances, details and likely logs and screenshots.
