### ISSUE TITLE
please bring back sdist releases to pypi repo.

### ISSUE THREAD

**Issue by eldernewborn** [apache/airflow#13498] opened 2021-01-05 21:57 UTC
Since release of 2.0.0 the sdist / *.tar.gz release is not present in pypi package repo. This will prevent automated pipelines from ingesting the release and generating customized wheels that is usually the process in bigger companies.

Considering that we already have the tooling to create sdist packages as part of CI code present in the codebase, Please kindly re-instate sdist as part of generic release process and make sdist available as part of pypi artifacts.

Thanks
-Ali

**Comment by ashb** [comment] 2021-01-05 22:49
Close as duplicate of #13467

**Closed as completed by ashb** 2021-01-05 22:49 UTC
Labels: kind:feature
