### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by codecakes** [apache/airflow#32783] opened 2023-07-23 11:13 UTC
### Apache Airflow version

2.6.3

### What happened

Running `airflow db upgrade` or `airflow standalone` runs into this issue.

airflow db upgrade
```bash

DB: sqlite:///./airflow/airflow.db
Performing upgrade with database sqlite:///./airflow/airflow.db
[2023-07-23T13:01:02.882+0200] {migration.py:213} INFO - Context impl SQLiteImpl.
[2023-07-23T13:01:02.884+0200] {migration.py:216} INFO - Will assume non-transactional DDL.
[2023-07-23T13:01:02.885+0200] {migration.py:213} INFO - Context impl SQLiteImpl.
[2023-07-23T13:01:02.885+0200] {migration.py:216} INFO - Will assume non-transactional DDL.
...
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

airflow standalone
```bash
airflow standalone
standalone | Starting Airflow Standalone
standalone | Checking database is initialized
...
line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### What you think should happen instead

Trying to follow https://airflow.apache.org/docs/apache-airflow/stable/start.html should get airflow standalone up and running as described in the doc.

### How to reproduce

Setup poetry environment where platform is  **Darwin Kernel Version 22.5.0** on **Python 3.11.3** then setup AIRFLOW_HOME  like:

```bash
echo $AIRFLOW_HOME 
./airflow
```

The `pyproject.toml` that is updated for this environment from standard template:

```toml


[tool.poetry.dependencies]
python = "^3.11"
cython="^3.0.0"
pandas = {version="2.0.3", extras=["performance", "excel", "feather", "parquet"]}

[tool.poetry.dev-dependencies]
jupyterlab="4.0.3"
ipython="8.14.0"
ipython-suggestions="1.0.0"
isort = "5.12.0"
yapf = "0.40.1"
black = "23.7.0"

[tool.poetry.group.airflow]
optional=true

[tool.poetry.group.airflow.dependencies]
apache-airflow = { version = "2.6.3", extras=["postgres"], python="^3.11" }
psycopg = {version="3.1.9", extras = ["binary"]}
```

Then run `airflow standalone`

### Operating System

Mac OSX 13.4 (22F66)

### Versions of Apache Airflow Providers

Only apache-airflow = { version = "2.6.3", extras=["postgres"], python="^3.11" }

### Deployment

Other Docker-based deployment

### Anything else

I ran a python3 shell in poetry env:

```python3
>>> import sqlalchemy as sa
>>> sa.create_engine('sqlite:///./airflow/airflow.db')
Engine(sqlite:///./airflow/airflow.db)
>>> engine = sa.create_engine('sqlite:///./airflow/airflow.db')
>>> engine.connect(close_with_result=True)
<sqlalchemy.engine.base.Connection object at 0x103a3f010>
>>> sqlite_conn = engine.connect(close_with_result=True)
>>> sqlite_conn
<sqlalchemy.engine.base.Connection object at 0x103a8d050>
```
I don't see any connection issues there.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2023-07-23 12:32
Your AIRLFOW_HOME is wrongly specified. It should be absolute path not relative. For example "/home/user/airflow". Otherwise it's meaning depends on what the current working directory is and depending on how you start airflow it might change. Never use relative paths this way - this is general Unix feature, not airflow issue.

Closing as invalid. 

For the future - please follow what you are told when you opened the issue and open discussion instead. Discussions are foreseen for asking for help and troubleshooting your problems, only use it when you are relatively sure it is alrflow problem and not your environment issue. If in doubt - open discussion, then if you find out that it is airflow issue you can open a new one, or we can convert it into an issue. Creating issue unnecessarily increases the burden on maintainers who often are contributing in their free time to airfllow so that you can use it for free - and creating issues unnecessarily drags them away from improving airflow.

Please be mindful of that.

**Closed as completed by potiuk** 2023-07-23 12:32 UTC
Labels: kind:bug, invalid, area:core, needs-triage

**Comment by codecakes** [comment] 2023-07-23 16:32
In the following excerpts taken from the link, whether absolute path is necessary isn't explicitly mentioned [here](https://airflow.apache.org/docs/apache-airflow/stable/start.html)

> Set Airflow Home (optional):


> Airflow requires a home directory, and uses ~/airflow by default, but you can set a different location if you prefer. The AIRFLOW_HOME environment variable is used to inform Airflow of the desired location. This step of setting the environment variable should be done before installing Airflow so that the installation process knows where to store the necessary files.


While setting the `$AIRFLOW_HOME` value absolute path, it throws the error:

```bash

standalone | Starting Airflow Standalone
standalone | Checking database is initialized
Traceback (most recent call last):
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/bin/airflow", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 52, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/airflow/cli/commands/standalone_command.py", line 50, in entrypoint
    StandaloneCommand().run()
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/airflow/cli/commands/standalone_command.py", line 66, in run
    self.initialize_database()
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/airflow/cli/commands/standalone_command.py", line 176, in initialize_database
    db.initdb()
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/airflow/utils/db.py", line 718, in initdb
    _create_db_from_orm(session=session)
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/airflow/utils/db.py", line 703, in _create_db_from_orm
    _create_flask_session_tbl(engine.url)
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/airflow/utils/db.py", line 697, in _create_flask_session_tbl
    db.create_all()
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 4930, in create_all
    bind._run_ddl_visitor(
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3237, in _run_ddl_visitor
    with self.begin() as conn:
         ^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3153, in begin
    conn = self.connect(close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akul/Library/Caches/pypoetry/virtualenvs/ingest-facility-processor-7CA4xpJk-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)

```


> For the future - please follow what you are told when you opened the issue and open discussion instead. 

Where am I told? This is mentioned neither while [opening the issue ](https://github.com/apache/airflow/issues/new/choose) nor in the [description in Triage process](https://github.com/apache/airflow/blob/main/ISSUE_TRIAGE_PROCESS.rst)

**Comment by potiuk** [comment] 2023-07-24 00:00
> While setting the $AIRFLOW_HOME value absolute path, it throws the error:

Then I do not know, unfortunately, but I suggest to try the recommended (and only supported) way of installing airflow from PyPI. Airflow does not support poetry as installation as clearly stated here:

https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html 

> While there are some successes with using other tools like [poetry](https://python-poetry.org/) or [pip-tools](https://pypi.org/project/pip-tools/), they do not share the same workflow as pip - especially when it comes to constraint vs. requirements management. Installing via Poetry or pip-tools is not currently supported. If you wish to install airflow using those tools you should use the constraints and convert them to appropriate format and workflow that your tool requires.

Ufortunately, the error does not give enough information to investigate more. Possibly the directory you set airflow to uses some filesystem that is not supported by sqlite, or maybe you have no permissions to write to the directory - there might be many reasons. You have not mentioned where you set AIRFLOW_HOME to - maybe there is a typo, or space for example, or maybe you are running it in docker and your filesystem is mounted to it (you mentioned docker) - I believe it will not work if you try to use sqlite on a mounted filesstem in Docker on MacOS because of filesystem limitations. But this is a guess based on your "docker" mentioning, you have not mentioned you are running 

I just tried it on MacOS without AIRFLOW_HOME on linux

<img width="987" alt="Screenshot 2023-07-24 at 01 48 13" src="https://github.com/apache/airflow/assets/595491/4bc70087-e525-4801-9ca8-13920de559a7">

And with:

<img width="987" alt="Screenshot 2023-07-24 at 01 48 13" src="https://github.com/apache/airflow/assets/595491/b9a3b1a2-e882-42e1-9d66-acb6b7efaa42">

And have no probimes.

I suggest you try a few other ways:

* try without poetry following regular venv
* unset AIRFLOW_HOME and try it 
* change it to another filesystem
* avoid special characters in it

If you still can't make it works, try maybe providing soms details and do some more investigation. Remember that those issues and forums are free forums where people in their free time try to help other people like you to solve the problem with the software they got for free thanks to the free, volunteer work of thousands of people. They might help if they see they can easily reproduce their problem..

> In the following excerpts taken from the link, whether absolute path is necessary isn't explicitly mentioned [here](https://airflow.apache.org/docs/apache-airflow/stable/start.html)

Feel free to add if you think it is needed. Airflow community welcome any improcments to our docs. Airflow is created by > 2500 people most of them volunteers who spend their nights and weekends and contribute for free so that people like you can use it for free. And they are also creating and updating documentation when they see somethign that migh need an improvement and can help people like them - who might have different assumption. It's super easy. Just open the docs page, hit "suggest a change on this page" and PR will be open. If you think that might help others. That would be great help for the community.

> Where am I told? This is mentioned neither while [opening the issue ](https://github.com/apache/airflow/issues/new/choose)nor in the [description in Triage process](https://github.com/apache/airflow/blob/main/ISSUE_TRIAGE_PROCESS.rst)

1. Ask the question or get support link leads to it:

<img width="1309" alt="Screenshot 2023-07-24 at 01 33 16" src="https://github.com/apache/airflow/assets/595491/c7889025-7a21-421a-9828-b983ec183664">

2. In the issue template right when you fill it in and it contains lilnk to dicussion above the reproducible case:

<img width="1014" alt="Screenshot 2023-07-24 at 01 26 40" src="https://github.com/apache/airflow/assets/595491/aa33a892-27d2-446f-800d-a92cc13cd5be">


I will convert this issue to discussion  - maybe you can provide more results of your investigation.
