### ISSUE TITLE
front - admin menu - drop-down non deterministic

### ISSUE THREAD

**Issue by raphaelauv** [apache/airflow#39135] opened 2024-04-19 14:27 UTC
### Apache Airflow version

2.9.0

### What happened?

My user is Admin in airflow

![image](https://github.com/apache/airflow/assets/10202690/612469e5-1bb9-4dd4-9393-292c7c5a79e6)

but most of the time I can't see all the admin menu drop-down but only Plugins

![Screenshot from 2024-04-19 16-21-32](https://github.com/apache/airflow/assets/10202690/89ed609f-315f-4f0a-9499-52a0b5debb95)

after multiple F5 I can see all the admin menu 

![Screenshot from 2024-04-19 16-21-44](https://github.com/apache/airflow/assets/10202690/9a41be55-e0bf-4322-be02-59be6ddb0276)

and if I F5 again it go back to only Plugins

### How to reproduce

I can't reproduce it with the simple docker compose of the airflow project

it's maybe related to the fact that the problematic airflow deployment is setup with an LDAP 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment] 2024-04-19 20:49
Also have seen this a couple of times since 2.9.0 in our environment. Still have no clue about the root cause and how to fix. Ideas welcome.

**Comment by kahlstrm** [comment] 2024-04-23 08:50
We also are encountering the same issue, will try to look around if I can find a fix for this.

**Comment by kahlstrm** [comment] 2024-04-23 11:02
After some digging, it seems like this could have been introduced by https://github.com/apache/airflow/pull/36871, but not entirely sure of reproducing, as for some reason cannot reproduce it in dev environment.

**Comment by potiuk** [comment] 2024-04-24 12:22
I think I found the reason (cc: @vincbeck). It required multiple users with different permissions using the same server gunicorn worker, that's why likely it was difficult to reproduce on dev server.

Fix here: https://github.com/apache/airflow/pull/39229

**Comment by potiuk** [comment] 2024-04-24 12:24
cc: @jscheffl @raphaelauv -> maybe you could try to apply the fix in your env to double check if my guess was right?

**Closed as completed** 2024-04-24 17:09 UTC
Labels: kind:bug, area:auth, area:core, area:UI

**Comment by jscheffl** [comment] 2024-04-24 20:47
@potiuk Will try a regression the next days, might need a moment. But we are also using OAUTH and it smells very probable that the correction fixes it... THANKS!
