### ISSUE TITLE
Applying labels to task groups shows a cycle in the graph view for the dag

### ISSUE THREAD

**Issue by rustikk** [apache/airflow#19785] opened 2021-11-23 18:39 UTC
### Apache Airflow version

2.2.2

### Operating System

Docker (debian:buster)

### Versions of Apache Airflow Providers

N/A

### Deployment

Astronomer

### Deployment details

run airflow with this dag

```python3
with DAG(
    dag_id="label_bug_without_chain"
) as dag:

    with TaskGroup(group_id="group1") as taskgroup1:
        t1 = DummyOperator(task_id="dummy1")
        t2 = DummyOperator(task_id="dummy2")
        t3 = DummyOperator(task_id="dummy3")
    
    t4 = DummyOperator(task_id="dummy4")

chain([Label("branch three")], taskgroup1, t4,)
```

### What happened

expanded task views look like they have cycles

<img width="896" alt="Screen Shot 2021-11-22 at 2 33 49 PM" src="https://user-images.githubusercontent.com/17841735/143083099-d250fd7e-963f-4b34-b544-405b51ee2859.png">

### What you expected to happen

The task group shouldn't display as if it has loops in it.

### How to reproduce

View the dag shown in the deployment details.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2021-11-23 19:59
cc @bbovenzi

**Comment by bbovenzi** [comment] 2021-12-02 14:18
Related: #19899

I think we will remove the blue dots entirely as they seem to cause confusion and weird issues.

**Comment by eladkal** [comment] 2022-07-04 15:39
@bbovenzi I tried to reproduce this issue and It seems like now this DAG is breaking the Grid view:
![Screen Shot 2022-07-04 at 18 35 18](https://user-images.githubusercontent.com/45845474/177185631-95fa5f3b-4255-4de7-aca2-fe8630e7a2c3.png)


Removing the line: `chain([Label("branch three")], taskgroup1, t4,)`
makes the Grid view works:
![Screen Shot 2022-07-04 at 18 38 37](https://user-images.githubusercontent.com/45845474/177185811-a54b2bdc-c871-4284-9d9f-ad219c922ad2.png)

**Comment by ashb** [comment] 2022-07-04 20:32
Is there a stack trace in the webserver logs? (It looks like the API call failed with a 500)

**Comment by ephraimbuddy** [comment] 2022-07-04 21:17
For the above dag, writing the chain as below works:
```python
chain([Label("branch three")], [taskgroup1], t4)
```
or 
```python
chain(Label("branch three"), taskgroup1, t4)
```

**Comment by ephraimbuddy** [comment] 2022-07-04 21:20
> Is there a stack trace in the webserver logs? (It looks like the API call failed with a 500)

Yes. Here's the stacktrace:
```log
[2022-07-04 21:18:55+0000 929ms] {app.py:1456} ERROR - Exception on /object/grid_data [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/airflow/airflow/www/auth.py", line 46, in decorated
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/www/views.py", line 3628, in grid_data
    'groups': dag_to_grid(dag, dag_runs, session),
  File "/opt/airflow/airflow/www/views.py", line 409, in dag_to_grid
    return task_group_to_grid(dag.task_group, dag_runs, grouped_tis)
  File "/opt/airflow/airflow/www/views.py", line 361, in task_group_to_grid
    task_group_to_grid(child, dag_runs, grouped_tis) for child in task_group.topological_sort()
  File "/opt/airflow/airflow/utils/task_group.py", line 450, in topological_sort
    raise AirflowDagCycleException(f"A cyclic dependency occurred in dag: {self.dag_id}")
airflow.exceptions.AirflowDagCycleException: A cyclic dependency occurred in dag: label_bug_without_chain
```

**Comment by ashb** [comment] 2022-07-05 09:41
I'm not sure this is a bug -- or at least not a bug in the UI.

On 2.2.5:

```
IIn [1]: from datetime import datetime
   ...: 
   ...: from airflow.models.baseoperator import chain
   ...: from airflow.operators.dummy import DummyOperator
   ...: from airflow.utils.edgemodifier import Label
   ...: from airflow.utils.task_group import TaskGroup
   ...: from airflow import DAG
   ...: 
   ...: 
   ...: DEFAULT_ARGS = {"depends_on_past": False, "retries": 2}
   ...: 
   ...: with DAG(
   ...:     dag_id="label_bug_without_chain",
   ...:     start_date=datetime(2022, 5, 20, 0),
   ...:     default_args=DEFAULT_ARGS,
   ...: ) as dag:
   ...: 
   ...:     with TaskGroup(group_id="group1") as taskgroup1:
   ...:         t1 = DummyOperator(task_id="dummy1")
   ...:         t2 = DummyOperator(task_id="dummy2")
   ...:         t3 = DummyOperator(task_id="dummy3")
   ...: 
   ...:     t4 = DummyOperator(task_id="dummy4")
   ...: 
   ...: chain([Label("branch three")], taskgroup1, t4)
   ...: 
In [2]: taskgroup1.upstream_list
Out[2]: 
[<Task(DummyOperator): group1.dummy1>,
 <Task(DummyOperator): group1.dummy3>,
 <Task(DummyOperator): group1.dummy2>]
```

The task group is marked as depending on it self. The bug is that we don't detect the cycle earlier during the DAG parsing process!

**Comment by ashb** [comment] 2022-07-05 09:54
Not to mention this DAG is invalid -- a label must be _between_ two nodes, it can't be at the start of one.

**Comment by eladkal** [comment] 2022-07-05 10:34
could be but the end result of Grid view crash is not desired.
If not valid state why it doesn't raise broken dag?

**Comment by ashb** [comment] 2022-07-05 10:35
The example code given in the OP doesn't quite match the picture they showed (missing the start task)

**Comment by ashb** [comment] 2022-07-05 10:37
```python
from datetime import datetime

from airflow.models.baseoperator import chain
from airflow.operators.dummy import DummyOperator
from airflow.utils.edgemodifier import Label
from airflow.utils.task_group import TaskGroup
from airflow import DAG


DEFAULT_ARGS = {
    'depends_on_past': False,
    'retries': 2
}

with DAG(
    dag_id="label_bug_without_chain",
    start_date=datetime(2022, 5, 20, 0),
    default_args=DEFAULT_ARGS,
) as dag:

    start = DummyOperator(task_id="sleep_3_seconds")

    with TaskGroup(group_id="group1") as taskgroup1:
        t1 = DummyOperator(task_id="dummy1")
        t2 = DummyOperator(task_id="dummy2")
        t3 = DummyOperator(task_id="dummy3")

    t4 = DummyOperator(task_id="echo_done")

chain(start, [Label("branch three")], taskgroup1, t4)
```

The issue is still shows up with this dag though.

**Closed as completed** 2022-07-05 15:40 UTC
Labels: kind:bug, area:core, area:UI, _eol_affected_version:2.2
