### ISSUE TITLE
Inconsistency around python 3.11 support

### ISSUE THREAD

**Issue by etr2460** [apache/airflow#34689] opened 2023-09-29 16:15 UTC
### What do you see as an issue?

On https://airflow.apache.org/docs/apache-airflow/stable/start.html, it says python 3.11 is not tested, but in https://github.com/apache/airflow#requirements 3.11 appears to be tested and supported. This inconsistency is confusing.

### Solving the problem

Update the docs page to show 3.11 as supported

### Anything else

I looked into the code, but it seems like the start page is already updated to show 3.11 as supported. Perhaps we need a new deploy of the docs site?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Taragolis** [comment] 2023-09-29 16:29
Duplicate of https://github.com/apache/airflow/issues/34574
Documentation will change after next Airflow release

**Closed as completed by Taragolis** 2023-09-29 16:29 UTC
Labels: kind:bug, kind:documentation, duplicate, needs-triage

**Comment by etr2460** [comment] 2023-09-29 16:32
Ah thanks. i searched for issues with 3.11 in the title, but didn't check the closed ones
