### ISSUE TITLE
Airflow Webserver returns incorrect HTTP Error Response for custom REST API endpoints 

### ISSUE THREAD

**Issue by PadmajaPeri** [apache/airflow#26375] opened 2022-09-13 21:56 UTC
### Apache Airflow version

Other Airflow 2 version

### What happened

We are using Airflow 2.3.1 Version. Apart from Airflow provided REST endpoints, we are also using the airflow webserver to host our own application REST API endpoints. We are doing this by loading our own blueprints and registering Flask Blueprint routes within the airflow plugin. 

Issue: Our Custom REST API endpoints are returning incorrect HTTP Error response code of 404 when 405 is expected (Invoke the REST API endpoint with an incorrect HTTP method, say POST instead of PUT) . This was working in airflow 1.x but is giving an issue with airflow 2.x

Here is a sample airflow plugin code . If the '/sample-app/v1' API below is invoked with POST method, I would expect a 405 response. However, it returns a 404. 

I tried registering a blueprint error handler for 405 inside the plugin, but that did not work.

```
test_bp = flask.Blueprint('test_plugin', __name__)

@test_bp.route(
    '/sample-app/v1/tags/<tag>', methods=['PUT'])
def initialize_deployment(tag):
    """
    Initialize the deployment of the metadata tag

    :rtype: flask.Response
    """
    return 'Hello, World'

class TestPlugin(plugins_manager.AirflowPlugin):
    name = 'test_plugin'
    flask_blueprints = [test_bp]
```

### What you think should happen instead

Correct HTTP Error response code should be returned.

### How to reproduce

Issue the following curl request after loading the plugin - 

curl -X POST "http://localhost:8080/sample-app/v1/tags/abcd" -d '' 

The response will be 404 instead of 405.

### Operating System

Ubuntu

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2022-09-18 22:54
I think the problem is because connexion has a custom handler set for both 404 and 405 methods that in case of a call that does not match the API URL, will return `not_found` i.e. 404 - even if originally it was 405:

https://github.com/apache/airflow/blob/main/airflow/www/extensions/init_views.py#L190

```

    @app.errorhandler(404)
    @app.errorhandler(405)
    def _handle_api_error(ex):
        if request.path.startswith(base_path):
            # 404 errors are never handled on the blueprint level
            # unless raised from a view func so actual 404 errors,
            # i.e. "no route for it" defined, need to be handled
            # here on the application level
            return common_error_handler(ex)
        else:
            return views.not_found(ex)
```

I marked it as a "good first issue" and hopefully somoene will take care of it, but I think the most sure way to get it "quickly" by you is to try to fix it on your side and submit a PR fixing it @PadmajaPeri - this is quite a niche case and while it is technically 'not correct' to return 404 in this case, it is not likely to be a problem for many users, so it might be, it won't be fixed as quickly. But this one seems to be rather easy to fix for you - since you know Flask/Python and you should be able to even get it locally tested (and deploy a modified Airflow version with the fix) before you submit a PR with the fix.

WDYT? Easy way to become one of > 2100 contributors to Airflow - mostly people like you who had a problem and ended up with contributing a fix.

**Comment by dakshin-k** [comment] 2022-10-02 05:57
Hi @potiuk , could I be assigned to this issue please?

Also, I have a couple questions on how to go about this, would be good to get an opinion from someone who knows the codebase better:

1. Is [this](https://github.com/apache/airflow/blob/0da49935000476b1d1941b63d0d66d3c58d64fea/tests/api_connexion/test_error_handling.py) the right place to go about adding a test for this? 
2. What is the expected behaviour for a 405 error? I'm guessing we want to use the `common_error_handler` function so it'll return a JSON response instead of a view

**Comment by potiuk** [comment] 2022-10-02 11:17
> * Is [this](https://github.com/apache/airflow/blob/0da49935000476b1d1941b63d0d66d3c58d64fea/tests/api_connexion/test_error_handling.py) the right place to go about adding a test for this?

I believe so. Also manual testing should be done.

> * What is the expected behaviour for a 405 error? I'm guessing we want to use the `common_error_handler` function so it'll return a JSON response instead of a view

Not really - I think we want to simply implement `view.method_not_allowed` method similar to `view.not_found` and split the `_handle_api_error` into two methods - `_handle_api_not_found` and `_handle_method_not_allowed` - decorated separate with errorhandler(404), errorhandler(405) respectively. That should do the job IMHO.

**Closed as completed** 2022-10-18 12:50 UTC
Labels: kind:bug, area:webserver, good first issue, _eol_affected_version:2.3
