### ISSUE TITLE
SSH Hook Help- No authentication methods available

### ISSUE THREAD

**Issue by levysaar** [apache/airflow#8490] opened 2020-04-21 13:32 UTC
Hey friends,

This is more of a help request rather than an issue/bug.

We try to migrate our airflow from 1.8 to 1.10, but we seem to have issues with configuring SSH connections.

I created the exact same connection settings from the 1.8 to 1.10
on 1.8 we had only the host and username configured and it worked flawlessly
but now on 1.10, when I use the exact same connection I get the following error:

`[2020-04-21 00:53:14,229] {taskinstance.py:1128} ERROR - SSH operator error: No authentication methods available
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/lib/python2.7/site-packages/airflow/contrib/operators/ssh_operator.py", line 177, in execute
    raise AirflowException("SSH operator error: {0}".format(str(e)))
AirflowException: SSH operator error: No authentication methods available`

The DAG itself is a small test DAG like the example here:
```import airflow
from airflow import DAG
from airflow.contrib.hooks.ssh_hook import SSHHook
from airflow.contrib.operators.ssh_operator import SSHOperator

default_args = { ... }

dag = DAG(
    'test', #dag_id
    default_args=default_args,
    description='A test dag',
    schedule_interval='0 1 * * *'
)

sshHook = SSHHook(ssh_conn_id='my-connection-id')

ssh_test = SSHOperator(
	task_id="ssh_test",
	command="/home/remote_ssh_test.bash {{ ds }} ",
	ssh_hook=sshHook,
	dag=dag
)
```

Since I saw in the code that the new version now using Paramiko, 
I've tried playing with the extra variables in the connection, but nothing seems to work,

I hope someone might be able to help me with even the smallest hint/suggestion

Thank you very much,
Saar

**Comment by dolfinus** [comment] 2020-10-30 12:10
It look like the issue is connected with usage of python2.7.

I'm using Airflow 1.10.12.
SSHConnection has empty `password` field but I stored path to SSH key in `extra` field:
```
'{"key_file": "/tmp/some/key/file"}'
```

If I call `conn.extra_dejson` using python2.7 I receive empty dict, that's why SSH connection is not established - there is no password and no key file.
But everything is fine then I use python3.6, dict is parsed correctly.

There are some error lines in log:
```
INFO     airflow.hooks.base_hook:base_hook.py:89 Using connection to: id: d8d61b557f3946939338e0baa24891ca. Host: 127.0.0.1, Port: 41605, Schema: None, Login: f15b63a1eb7f4a8891641c1daaba32d7, Password: None, extra: None
ERROR    airflow.models.connection.Connection:connection.py:344 No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/airflow/models/connection.py", line 342, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
I've tried to print `extra` field value by patching SSHHook: 
airflow/models/connection.py
```python
    @property
    def extra_dejson(self):
        """Returns the extra property by deserializing json."""
        obj = {}
        if self.extra:
            print(self.extra) # this line was added
            try:
                obj = json.loads(self.extra)
            except Exception as e:
                self.log.exception(e)
                self.log.error("Failed parsing the json for conn_id %s", self.conn_id)

        return obj
```

This what I see in log:
```
b'{"key_file": "/tmp/some/key/file"}'
```

It looks like json module in python2.7 cannot load byte string. The corresponding issue that I've found (https://bugs.python.org/issue10976) is fixed in python3.6 or above.

For me, it's not the end of the world, python2.7 support was optional and I've just got rid of it.
And also python2.7 is not maintained since January 2020, so it lloks like this issue will never be solved. Use python3 instead.

**Comment by eladkal** [comment] 2020-11-24 13:17
Since this bug seems to be Python 2.7 only I'm closing the issue.

**Closed as completed by eladkal** 2020-11-24 13:17 UTC
Labels: kind:bug, area:providers
