### ISSUE TITLE
`on_failure_callback` on DAG level is not executed

### ISSUE THREAD

**Issue by gh4n** [apache/airflow#16983] opened 2021-07-14 05:58 UTC
**Apache Airflow version**:  2.0.1 and 2.1.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):  1.20.4

**Environment**:

- **Cloud provider or hardware configuration**: AWS EKS
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux
- **Kernel** (e.g. `uname -a`):  Linux 5.4.117-58.216.amzn2.x86_64

**What happened**:

Airflow dag failed and `on_failure_callback` was not triggered. 
Logs were also not shown which may be related to issue https://github.com/apache/airflow/issues/13692.

In the worker pod logs I get the following error messages:

```
Failed to execute task local variable 'return_code' referenced before assignment.
Failed to execute task [Errno 2] No such file or directory: '/tmp/tmp7l296jgg'.                                                                                  
Task airflow.executors.celery_executor.execute_command[24d3f5c5-bf58-4aad-bf2a-c10b2781a2b2] raised unexpected: 
AirflowException('Celery command failed on host: 
Traceback (most recent call last):                                                                                                                                                                                  
  File "/home/airflow/.local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task                                                                                                              
    R = retval = fun(*args, **kwargs)                                                                                                                                                                               
  File "/home/airflow/.local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__                                                                                                      
    return self.run(*args, **kwargs)                                                                                                                                                                                
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/celery_executor.py", line 87, in execute_command                                                                                         
    _execute_in_fork(command_to_exec)                                                                                                                                                                               
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/celery_executor.py", line 98, in _execute_in_fork                                                                                        
    raise AirflowException('Celery command failed on host: ' + get_hostname())                                                                                                                                      
airflow.exceptions.AirflowException: Celery command failed on host: hotdoc-airflow-worker-0.hotdoc-airflow-worker.hotdoc-airflow-staging.svc.cluster.local
```
 

**What you expected to happen**:

I expected the callback function to be called and executed.
It sounds like the `null` hostname issue contributed to this happening but I am not familiar enough with Airflow internals to say for sure. I had a dig through the source code and it looks like some queries are made to list out tasks and other metadata.
https://github.com/apache/airflow/blob/b0f7f91fe29d1314b71c76de0f11d2dbe81c5c4a/airflow/models/dag.py#L822

**How to reproduce it**:

Create a dag with a function that fails and an error callback function

```python
import sys
from datetime import datetime
from airflow import DAG
from airflow.models import Variable
from airflow.operators.python_operator import PythonOperator

def on_failure(ctx):
    print('hello world')
    print(ctx)

def always_fails():
    sys.exit(1)

dag = DAG(
    dag_id='always_fails',
    description='dag that always fails',
    schedule_interval=None,
    catchup=False,
    start_date=datetime(2021,7,12),
    on_failure_callback=on_failure
)

task = PythonOperator(task_id='test-error-notifier', python_callable=always_fails, dag=dag)
```

Run the dag and check if the `on_failure_callback` is called.

**Comment by ephraimbuddy** [comment] 2021-07-14 07:35
Can you test this on airflow 2.1.1?

**Comment by trucnguyenlam** [comment] 2021-07-14 08:26
@ephraimbuddy I can confirm that the issue exists on 2.1.1

**Comment by trucnguyenlam** [comment] 2021-07-14 11:27
I think the root cause is from this [call](https://github.com/apache/airflow/blob/6ab00bfcfdfe1213928281527f32ca31b77cce1b/airflow/jobs/scheduler_job.py#L1062)
apparently callback is disabled.

**Comment by samgans** [comment] 2021-07-14 18:50
If you are not going to make a PR for this, I can try to make an investigation and fix this.

**Comment by trucnguyenlam** [comment] 2021-07-14 19:35
@samgans I might not have time to investigate more on this issue, but it might be more complicated than it sounds, my comment above is only the surface, underneath it's more about message passing in multiple processes of `DagFileProcessorProcess`. Please try to make more investigation on this, thanks.

**Comment by gh4n** [comment] 2021-07-14 22:57
@ephraimbuddy  Will your PR https://github.com/apache/airflow/pull/15172 released with 2.1.2 fix this issue?

**Comment by uranusjr** [comment] 2021-07-15 02:52
@trucnguyenlam Callback execution is disabled here, but that disabled callback is returned as the second value here (`callback_to_run`). That callback is then passed on for execution later, via `_send_dag_callbacks_to_processor` on the next line. So I don’t think that’s the cause.

**Comment by trucnguyenlam** [comment] 2021-07-15 07:13
@uranusjr yeah, I also came to that conclusion yesterday but didn't have time to go further, the callback somehow lost on the connection to DagFileProcessorProcess afterward.

**Comment by trucnguyenlam** [comment] 2021-07-16 07:52
@uranusjr how is it going with the investigation?

**Comment by samgans** [comment] 2021-07-16 22:17
**UPD**:

I have been testing the interaction and found that if we are passing the callable to the `on_failure_callback` DAG parameter directly, it doesn't work. But if we are configuring the `on_failure_callback` using default_args dictionary, the callback is getting called.

Continue review...

**Comment by ephraimbuddy** [comment] 2021-07-18 11:43
The `on_failure_callback` is a task argument and not DAG level argument. 
The correct dag is:
```
import sys
from datetime import datetime
from airflow import DAG
from airflow.models import Variable
from airflow.operators.python_operator import PythonOperator

def on_failure(ctx):
    print('hello world')
    print(ctx)

def always_fails():
    sys.exit(1)

dag = DAG(
    dag_id='always_fails',
    description='dag that always fails',
    schedule_interval=None,
    catchup=False,
    start_date=datetime(2021,7,12),
)

task = PythonOperator(task_id='test-error-notifier', python_callable=always_fails,on_failure_callback=on_failure, dag=dag)
```

**Comment by trucnguyenlam** [comment] 2021-07-18 12:00
@ephraimbuddy I think there is some misleading here, it is a valid argument for a DAG object

https://github.com/apache/airflow/blob/16564cad6f2956ecb842455d9d6a6255f8d3d817/airflow/models/dag.py#L267

**Comment by ephraimbuddy** [comment] 2021-07-18 13:20
Oops

**Comment by ephraimbuddy** [comment] 2021-07-18 14:10
So this too works fine, however, the logs end in :
``$AIRFLOW_HOME/logs/scheduler/latest/PROJECT/DAG_FILE.py.log``
as stated here:
https://github.com/apache/airflow/blob/938510f2ca8dfbf95b332971f4b087653d444d0f/airflow/models/dag.py#L829-L830

I tested with your dag. Let me know what you think

**Comment by trucnguyenlam** [comment] 2021-07-18 14:19
@ephraimbuddy thanks for providing more information, I will check out the log location if it's executed, could you also let me know if there is a way to log those in the main scheduler log (only if it's applicable)?

**Comment by ephraimbuddy** [comment] 2021-07-18 14:39
I'm not sure there's a way to get the log into the main scheduler log, however, you can ask on Discussion or slack

**Comment by trucnguyenlam** [comment] 2021-07-19 20:07
@ephraimbuddy I checked the location of the log, the callback does get handled. So it is technically working for me. Thanks.

**Comment by ephraimbuddy** [comment] 2021-07-19 22:18
Cool. Let's close the issue then

**Closed as completed by ephraimbuddy** 2021-07-19 22:18 UTC
Labels: kind:bug, _eol_affected_version:2.1
