### ISSUE TITLE
Dynamic Task Mapping demo output many warnings.

### ISSUE THREAD

**Issue by AndrewTsao** [apache/airflow#26792] opened 2022-09-30 01:18 UTC
### Apache Airflow version

2.4.0

### What happened

From v2.4.0，I run dynamic task mapping example, got many warnings.

```py
from airflow import DAG
from airflow.decorators import task
import pendulum as pl

with DAG(
    dag_id='test-dynamic-tasks', 
    description='测试动态task的注册告警',
    schedule=None,
    start_date=pl.today().add(days=-1),
) as dag:

    @task
    def sum_it(values):
        print(sum(values))

    @task
    def add_one(i):
        return i + 1

    added_values = add_one.expand(i = [1,2])
    sum_it(added_values)
```

Warnings like this.
```
[2022-09-30, 09:11:29 CST] {taskmixin.py:205} WARNING - Dependency <Mapped(_PythonDecoratedOperator): add_one>, sum_it already registered for DAG: test-dynamic-tasks
[2022-09-30, 09:11:29 CST] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): sum_it>, add_one already registered for DAG: test-dynamic-tasks
[2022-09-30, 09:11:29 CST] {taskmixin.py:205} WARNING - Dependency <Mapped(_PythonDecoratedOperator): add_one>, sum_it already registered for DAG: test-dynamic-tasks
[2022-09-30, 09:11:29 CST] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): sum_it>, add_one already registered for DAG: test-dynamic-tasks
[2022-09-30, 09:11:29 CST] {taskmixin.py:205} WARNING - Dependency <Mapped(_PythonDecoratedOperator): add_one>, sum_it already registered for DAG: test-dynamic-tasks
[2022-09-30, 09:11:29 CST] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): sum_it>, add_one already registered for DAG: test-dynamic-tasks
[2022-09-30, 09:11:29 CST] {taskmixin.py:205} WARNING - Dependency <Mapped(_PythonDecoratedOperator): add_one>, sum_it already registered for DAG: test-dynamic-tasks
[2022-09-30, 09:11:29 CST] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): sum_it>, add_one already registered for DAG: test-dynamic-tasks
[2022-09-30, 09:11:29 CST] {taskmixin.py:205} WARNING - Dependency <Mapped(_PythonDecoratedOperator): add_one>, sum_it already registered for DAG: test-dynamic-tasks
[2022-09-30, 09:11:29 CST] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): sum_it>, add_one already registered for DAG: test-dynamic-tasks
```

### Operating System

CentOS Linux release 7.9.2009 (Core)

### Versions of Apache Airflow Providers

airflow-code-editor                      7.0.0
apache-airflow                           2.4.0
apache-airflow-providers-celery          3.0.0
apache-airflow-providers-common-sql      1.1.0
apache-airflow-providers-ftp             3.1.0
apache-airflow-providers-http            4.0.0
apache-airflow-providers-imap            3.0.0
apache-airflow-providers-microsoft-psrp  2.0.0
apache-airflow-providers-microsoft-winrm 3.0.0
apache-airflow-providers-mysql           3.2.0
apache-airflow-providers-redis           3.0.0
apache-airflow-providers-samba           4.0.0
apache-airflow-providers-sftp            4.0.0
apache-airflow-providers-sqlite          3.2.0
apache-airflow-providers-ssh             3.1.0

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment] 2022-09-30 02:17
Duplicate of #26599

**Closed as not planned by uranusjr** 2022-09-30 02:17 UTC
Labels: duplicate
