### ISSUE TITLE
Tooltips not show up in Safari

### ISSUE THREAD

**Issue by weitian** [apache/airflow#10279] opened 2020-08-10 17:50 UTC
**Apache Airflow version**: 1.10.10

**What happened**:

The tooltips of a task instance does not show up in Safari browser (Version 13.1.2 (15609.3.5.1.3)).
But it works on chrome browser (Version 84.0.4147.89).

**Anything else we need to know**:

How often does this problem occur? Once? Every time etc?
happens every time

**Comment by alexbegg** [comment] 2020-09-02 21:49
It shows up fine for me in 1.10.11 in Safari. I was going to check with 1.10.10 using Breeze but I am having an issue building 1.10.10, so maybe someone else can try and reproduce this in 1.10.10.

**Comment by alexbegg** [comment] 2020-09-02 23:01
I was able to reproduce the problem, partially, but only when RBAC UI was not enabled. I noticed that in Safari the only tooltips that is not working is the ones for the circles for the recent tasks or DAG runs. The (i)s and the right "Links" icons all show a tooltip. On Chrome all the tooltips work.

**Comment by ashb** [comment] 2020-09-30 15:12
If this only applies to non-RBAC UI then this is less important - the old UI isn't under active development and only receiving critical bug fixes only.

PR to fix this should target v1-10-stable if someone wants to tackle this

**Comment by eladkal** [comment] 2021-01-27 20:05
Since this is an issue only in the non-RBAC UI which is deprecated in Airflow 1.10.X and removed entirely in Airflow 2.0
I see no value in fixing this bug which has very little impact if any.

Closing this issue. If someone believe otherwise please comment.

**Closed as completed by eladkal** 2021-01-27 20:05 UTC
Labels: kind:bug, area:webserver, won't fix, priority:low
