### ISSUE TITLE
The previous dag_run is scheduled instead of the current

### ISSUE THREAD

**Issue by 0xR** [apache/airflow#1092] opened 2016-02-29 14:00 UTC
I have DAG scheduled at 12 and 5 am: `0 0,5 * * *`. For some reason airflow runs the 5am instance of the previous day on 12 am and the 12 am instance of the same day on 5 am. 

This is what my logging says:

```
[2016-02-27 00:00:01,281] {local_executor.py:29} INFO - LocalWorker running airflow run my_dag start 2016-02-26T05:00:00 --local -sd DAGS_FOLDER/my_dag.py 
[2016-02-27 05:00:01,305] {local_executor.py:29} INFO - LocalWorker running airflow run my_dag start 2016-02-27T00:00:00 --local -sd DAGS_FOLDER/my_dag.py 
[2016-02-28 00:00:01,285] {local_executor.py:29} INFO - LocalWorker running airflow run my_dag start 2016-02-27T05:00:00 --local -sd DAGS_FOLDER/my_dag.py 
[2016-02-28 05:00:01,276] {local_executor.py:29} INFO - LocalWorker running airflow run my_dag start 2016-02-28T00:00:00 --local -sd DAGS_FOLDER/my_dag.py 
[2016-02-29 00:00:01,282] {local_executor.py:29} INFO - LocalWorker running airflow run my_dag start 2016-02-28T05:00:00 --local -sd DAGS_FOLDER/my_dag.py 
[2016-02-29 05:00:01,275] {local_executor.py:29} INFO - LocalWorker running airflow run my_dag start 2016-02-29T00:00:00 --local -sd DAGS_FOLDER/my_dag.py 
```

I don't think this is expected behavior. I can provide additional information if it's needed.

**Comment by 0xR** [comment] 2016-03-01 08:42
I changed the scheduling to `1 0,5 * * *` to check whether te issue is related to changing of the date at 12 am. However it doesn't fix the issue. This is what happened today:

```
[2016-03-01 00:01:03,294] {local_executor.py:29} INFO - LocalWorker running airflow run my_dag start 2016-02-29T05:01:00 --local -sd DAGS_FOLDER/my_dag.py
[2016-03-01 05:01:03,283] {local_executor.py:29} INFO - LocalWorker running airflow run my_dag start 2016-03-01T00:01:00 --local -sd DAGS_FOLDER/my_dag.py 
```

**Comment by r39132** [comment] 2016-03-23 06:31
Hi @0xR 
What is your expectation here? 

Refer to https://pythonhosted.org/airflow/scheduler.html#scheduling-triggers

Specifically,
"Note that if you run a DAG on a schedule_interval of one day, the run stamped 2016-01-01 will be trigger soon after 2016-01-01T23:59. In other words, the job instance is started once the period it covers has ended."

An example cron schedule could be `0,15,30,45 * * * * *`, which means to run every 15 minutes.
So, 
- at `12:15:01`, the `12:00` run would start
- at `12:30:01`, the `12:15` run would start
- at `12:45:01`, the `12:30` run would start
- at `13:00:01`, the `12:45` run would start

Now, when you specified `0 0,5 * * *`, this worked as intended.

```
[2016-02-27 00:00:01,281] {local_executor.py:29} INFO - LocalWorker running airflow run my_dag start 2016-02-26T05:00:00 --local -sd DAGS_FOLDER/my_dag.py 
[2016-02-27 05:00:01,305] {local_executor.py:29} INFO - LocalWorker running airflow run my_dag start 2016-02-27T00:00:00 --local -sd DAGS_FOLDER/my_dag.py 
[2016-02-28 00:00:01,285] {local_executor.py:29} INFO - LocalWorker running airflow run my_dag start 2016-02-27T05:00:00 --local -sd DAGS_FOLDER/my_dag.py 
```

At `2016-02-27 00:00:01,281`, the period starting at `2016-02-26T05:00:00` was covered (or closed), meaning that `2016-02-26T05:00:00` could be scheduled.

Hope this makes sense. But, I'm closing this as NAB. If you have further questions, find me on [gitter](https://gitter.im/airbnb/airflow) 
-s

**Closed as completed by r39132** 2016-03-23 06:31 UTC

**Comment by 0xR** [comment] 2016-03-23 08:54
Ok I think I understand what is going on. However it makes templating the day before the execution day impossible. What I did to work around the issue is make 2 dags: 1 runs at 1am and 2 run at 5am. This way I know the execution date is the day before the actual run date. Knowing that I can use `{{ tomorrow_ds}}` as the current date in my template. 

I guess I am missing a template variable which has the date / time on which the dags scheduled to run. This dat will be different from the date of the data the dag run covers.
