### ISSUE TITLE
Pools have disappeared from the Admin menu

### ISSUE THREAD

**Issue by csp33** [apache/airflow#39204] opened 2024-04-23 13:35 UTC
### Apache Airflow version

2.9.0

### What happened?

`Pools` item is not shown in admin menu.
<img width="1018" alt="image" src="https://github.com/apache/airflow/assets/28935464/db983725-33f5-4c5c-91f2-3586751a6aa3">

However, I can still access the interface entering the URL `<webserver>/pool/list`
<img width="1715" alt="image" src="https://github.com/apache/airflow/assets/28935464/d5a89bcc-2467-495c-9538-612011a46df8">

My user has the `Admin` role 
<img width="612" alt="image" src="https://github.com/apache/airflow/assets/28935464/c95fb5d0-090f-4068-be67-5a0297157d21">
which can do everything related to `Pools`
<img width="1684" alt="image" src="https://github.com/apache/airflow/assets/28935464/92de9156-70df-43d0-b02c-81efbf722edf">

### What you think should happen instead?

Pools should be displayed in the `Admin` menu, just like before

### How to reproduce

1. Install Airflow 2.9.0
2. Try to find `Pools` in the `Admin` menu.

### Operating System

Airflow in Kubernetes

### Deployment

Official Apache Airflow Helm Chart

### Anything else?

We're using GitHub login.
In local (user/password login) the `Pools` option still appears in the `Admin` menu.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by RNHTTR** [comment] 2024-04-23 15:03
Is there anything unique about your environment? I'm able to see Admin -> Pools on 2.9.0

<img width="195" alt="image" src="https://github.com/apache/airflow/assets/25823361/3c44cfdf-80da-4002-ac0d-07925c7aae00">

**Comment by csp33** [comment] 2024-04-23 15:17
In production we're using the GitHub login.
In local (where we have the user/pwd login) I can still see the Pools menu 🤔 

Added to the issue description, thanks!

**Comment by vargacypher** [comment] 2024-04-23 15:47
We're facing the same problem reported by @csp33 , but not only with pools.
Sometimes we just see **'configuration'** in admin tab, and sometimes it appers again all tabs (pools,variables etc...).
![image](https://github.com/apache/airflow/assets/77084039/28dc4c3d-09b4-4270-92b5-d5947295fbe9)

Obs: Webserver and Scheduller logs  doesn't show any error that appers to be related with that.

**Comment by potiuk** [comment] 2024-04-24 10:24
Duplicate of #39135 - seems that it is some kind of race conndition when OAUTH/LDAP authentication is used - and likely related to the optimisation implemented in https://github.com/apache/airflow/pull/36871 but could not find the reason yet. cc: @vincbeck

**Comment by potiuk** [comment] 2024-04-24 10:54
> In production we're using the GitHub login. In local (where we have the user/pwd login) I can still see the Pools menu 🤔
> 
> Added to the issue description, thanks!

What's your Github integration configuration @csp33 (Without secrets?) ?

**Comment by csp33** [comment] 2024-04-24 11:17
> > In production we're using the GitHub login. In local (where we have the user/pwd login) I can still see the Pools menu 🤔
> > Added to the issue description, thanks!
> 
> What's your Github integration configuration @csp33 (Without secrets?) ?

This is my `webserver_config.py` :

```python
        import os
        from typing import Dict, Any, List, Union

        from airflow.www.security import AirflowSecurityManager
        from flask_appbuilder import expose
        from flask_appbuilder.security.manager import AUTH_OAUTH
        from flask_appbuilder.security.views import AuthOAuthView

        AUTH_TYPE = AUTH_OAUTH
        AUTH_USER_REGISTRATION = True
        AUTH_USER_REGISTRATION_ROLE = "Viewer"
        PERMANENT_SESSION_LIFETIME = 1800


        OAUTH_PROVIDERS = [
            {
                "name": "github",
                "icon": "fa-github",
                "token_key": "access_token",
                "remote_app": {
                    "client_id": os.getenv("GITHUB_OAUTH_APP_ID"),
                    "client_secret": os.getenv("GITHUB_OAUTH_APP_SECRET"),
                    "api_base_url": "https://api.github.com",
                    "client_kwargs": {"scope": "read:user, read:org"},
                    "access_token_url": "https://github.com/login/oauth/access_token",
                    "authorize_url": "https://github.com/login/oauth/authorize",
                    "request_token_url": None,
                },
            },
        ]

        class CustomAuthRemoteUserView(AuthOAuthView):
            @expose("/logout/")
            def logout(self):
                """Delete access token before logging out."""
                return super().logout()


        class GithubAuthorizer(AirflowSecurityManager):
            authoauthview = CustomAuthRemoteUserView

            def get_oauth_user_info(
                    self, provider: str, resp: Any
            ) -> Dict[str, Union[str, List[str]]]:
                remote_app = self.appbuilder.sm.oauth_remotes[provider]
                me = remote_app.get("user")
                user_data = me.json()
                username = user_data["login"]

                try:
                    name_surname_list = user_data['name'].split(" ", 1)
                    first_name = name_surname_list[0]
                    last_name = name_surname_list[1]
                except Exception:
                    first_name = last_name = "unknown"

                return {
                    "username": username,
                    "email": user_data["email"],
                    "first_name": first_name,
                    "last_name": last_name,
                }

        SECURITY_MANAGER_CLASS = GithubAuthorizer
```

**Comment by potiuk** [comment] 2024-04-24 11:46
Absolutely cannot reproduce - even with your settings:

Questions:

* How did you make your user "Admin" after it's been registered as user? 
* Do you have more than one webserver instances running? Are you sure they are all restarted/upgraded to 2.9.0?
* Can you see (at least few times while you are seeing missing Admin menus) what are the users and their roles using `airflow users list` command (see below) - does it change?
* Is it possible that you have `AUTH_SYNC_ROLES_AT_LOGIN = True` set in all or some of your webservers ?  
* Is it possible that you have two users created with different usernames like this ?

airflow users list

````
id | username      | email                        | first_name | last_name | roles       
===+===============+==============================+============+===========+=============
1  | github_potiuk | github_potiuk@email.notfound |            |           | Admin       
2  | potiuk        | jarek@potiuk.com             | Jarek      | Potiuk    | Viewer                                                                                      
```

**Comment by csp33** [comment] 2024-04-24 12:12
Now the Pools option always appear, but the Variables, connections, etc. are the ones that randomly show when I refresh the page 😮 
![image](https://github.com/apache/airflow/assets/28935464/9e95673b-0cd6-4e70-a358-bb35d4b7455d)
![image](https://github.com/apache/airflow/assets/28935464/21947111-139f-41b7-b60f-a1aae657c1d4)


I have 2 webservers and in both I'm recognised as an Admin. The output is the same when I can see the options and when I can't.

![image](https://github.com/apache/airflow/assets/28935464/341c065c-fd45-46f9-9b41-12f73dcb8fc6)
![image](https://github.com/apache/airflow/assets/28935464/31e429ec-7e13-4afe-9b60-26d3164ee460)


In the profile page I can confirm that I'm logged in as admin
![image](https://github.com/apache/airflow/assets/28935464/ea002171-3eab-49d3-8ca9-c582bf90ce18)
![image](https://github.com/apache/airflow/assets/28935464/1027426a-6cf5-4c8b-86a3-3b61e8d42854)


> How did you make your user "Admin" after it's been registered as user?

I can't remember right now. Maybe I used the CLI to perform `airflow users add-role`. After that, all the roles have been granted from the `List Users` page.

> Do you have more than one webserver instances running? Are you sure they are all restarted/upgraded to 2.9.0?

All of them are fresh pods using 2.9.0 image.

> Can you see (at least few times while you are seeing missing Admin menus) what are the users and their roles using airflow users list command (see below) - does it change?

Command output is the same (see above)

> Is it possible that you have AUTH_SYNC_ROLES_AT_LOGIN = True set in all or some of your webservers ?

No, that is not set anywhere

> Is it possible that you have two users created with different usernames like this ?

Checked it and that doesn't happen

Thanks for the help!

**Comment by potiuk** [comment] 2024-04-24 12:21
I think I found the reason (cc: @vincbeck). It required multiple users with different permissions using the same server gunicorn worker, that's why likely it was difficult to reproduce on dev server. 

Fix here: https://github.com/apache/airflow/pull/39229

**Closed as completed** 2024-04-24 17:09 UTC
Labels: kind:bug, area:UI, _eol_affected_version:2.9
