### ISSUE TITLE
Tasks pods are getting stuck in scheduled state after open slot parallelism count is reached 

### ISSUE THREAD

**Issue by amrit2196** [apache/airflow#42383] opened 2024-09-20 18:59 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.10.0

### What happened?

I recently upgraded my airflow version from 2.5.3 to 2.10.0 in our environment, and the parallelism count is set to 32 with three schedulers in place, so what happens is that when more than 96 tasks run, whenever a new task is scheduled after that, it gets stuck in scheduled state, with the open slot count being zero, even though the previous tasks that ran have completed and have been cleared.

### What you think should happen instead?

The open slot count should increase when the tasks are completed and the tasks queued up should be scheduled

### How to reproduce

Just tried it by upgrading the changes and running 5 or 6 dags with 10 task in each dag and parallelism set to 32 for each scheduler. Point to be noted is that the same set of dag works fine when it was running in airflow version 2.5.3

### Operating System

Redhat linux

### Versions of Apache Airflow Providers

 apache-airflow-providers-postgres==5.12.0 \
           apache-airflow-providers-apache-hive==8.2.0 \
           apache-airflow-providers-amazon==8.28.0 \
           apache-airflow-providers-cncf-kubernetes==8.4.1 \
           apache-airflow-providers-apache-livy==3.9.0 \
           apache-airflow-providers-presto==5.6.0 \
           apache-airflow-providers-http==4.13.0 \
           apache-airflow-providers-trino==5.8.0 \
           apache-airflow-providers-snowflake==5.7.0 \
           apache-airflow-providers-salesforce==5.8.0 \
           apache-airflow-providers-papermill==3.8.0 \
           apache-airflow-providers-google==10.22.0 \
           apache-airflow-providers-celery==3.8.1 \
           apache-airflow-providers-redis==3.8.0 \
           apache-airflow-providers-dbt-cloud==3.10.0 \
           apache-airflow-providers-openlineage==1.11.0 \

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment] 2024-09-20 21:04
Can you create and post an example DAG to reproduce?
I am a bit courious what effect might bring this bug to you. There are maybe hundreds of installations using 2.10 already and it would be a major bug if nobody has detected this, a moment before we release 2.10.2.

Can you tell which executor you are using?

**Comment by amrit2196** [comment] 2024-09-20 23:17
We are using kubernetes executor , but for task pod deletion we run a cronjob to delete task pods, which was working fine in 2.5.3, but not in this one

**Comment by amrit2196** [comment] 2024-09-20 23:18
We are currently running a simple tag with multiple tasks with sleep and checking a get request in each tasks

**Comment by jscheffl** [comment] 2024-09-21 16:35
So to be able to understand this - and most likely it is something in the environment - I request that you inspect the scheduler logs. In recent versions there should be logs emitted when the scheduler is at the parallelism limit. Can you check for this?

Can you also please post an example DAG with which it is easy to reproduce? Then we could test it as regression.

**Comment by amrit2196** [comment] 2024-10-09 17:18
@jscheffl  The issue we are facing is , assume a scenario where the task pod runs and the base container gets completed and the side cars are terminated immediately along with the base container, the task event are properly sent to the kubernetes executor, whereas when I add a delay logic in termination of side cars, the information is not sent to the executor even though the containers are terminated and the pod is deleted after the delay. This results in parallelism count reaching to 0. I can see messages like skipping event for this task pod as the event has been already sent as well.

This happens even with a simple hello world dag:

from airflow import DAG
from airflow.operators.python_operator import PythonOperator
from datetime import datetime

# Define a simple Python function that will print "Hello, World!"
def hello_world():
    print("Hello, World!")

# Define the default arguments for the DAG
default_args = {
    'owner': 'airflow',
    'start_date': datetime(2024, 10, 8),  # Update to the current date or earlier
    'retries': 1,
}

# Instantiate the DAG
with DAG(
    dag_id='hello_world_dag',
    default_args=default_args,
    schedule_interval=None,  # Set to None to disable scheduled runs
    catchup=False,  # Don't backfill or run previous missed schedules
) as dag:

    # Define a task that uses PythonOperator to run the hello_world function
    hello_world_task = PythonOperator(
        task_id='print_hello_world',
        python_callable=hello_world,
    )

    # Define the task dependencies
    hello_world_task

**Comment by FleischerT** [comment] 2024-10-11 08:26
We seem to be experiencing the same issue, or at least a very similar one: After restarting the Airflow pods in Kubernetes, everything operates normally for a while, but then suddenly no additional tasks are executed. The logs display the following message:

'Executor parallelism limit reached. 0 open slots'

However, no tasks are actually running at that point. This issue has only arisen for us since upgrading to version 2.10.

**Comment by potiuk** [comment] 2024-11-05 16:26
Airflow 2.10.3 is now out an it has fix #42932 that is likely to fix the problems you reported, please <author> upgrade, check if it fixed your problem and report back @amrit2196 @FleischerT ?

**Comment by FleischerT** [comment] 2024-11-21 16:22
@potiuk So far, it seems that the problem is fixed with the new release! If it appears again, then I will create a new issue.

**Comment by potiuk** [comment] 2024-11-22 21:48
> @potiuk So far, it seems that the problem is fixed with the new release! If it appears again, then I will create a new issue.

Thanks for confirming @FleischerT !

**Closed as completed by potiuk** 2024-11-22 21:48 UTC
Labels: kind:bug, area:Scheduler, pending-response, area:core, provider:cncf-kubernetes, needs-triage
