### ISSUE TITLE
airflow is not accepting configuration from Admin UI

### ISSUE THREAD

**Issue by vikramcse** [apache/airflow#16810] opened 2021-07-05 11:23 UTC
**Apache Airflow version**: 2.1.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): NO

**Environment**: local (docker + ubuntu)

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`):  linux

**What happened**:
airflow is not accepting configuration from Admin UI

when I submit a DAG configuration from UI, it is giving me error `Invalid JSON configuration, must be a dict`

![image](https://user-images.githubusercontent.com/1611331/124464058-56320280-ddb1-11eb-9cba-4656263761ba.png)

the same workflow is working in airflow 2.1.0 version
I think this issue occurred in this PR https://github.com/apache/airflow/pull/15057 

**What you expected to happen**:
Airflow admin should accept the conf from UI and trigger the dag

**How to reproduce it**:
It can be reproduced for all cases, we have to put any valid JSON into the configuration window on a DAG 

**Willing to submit PR**
YES

**Comment by potiuk** [comment] 2021-07-05 11:43
Can't use my PC at the moment but it does look awfully a lot like we need to release 2.1.2 with a fix if it is confirmed @ashb @kaxil @jhtimmins

**Comment by ashb** [comment] 2021-07-05 11:44
Agreed, will confirm.

**Comment by potiuk** [comment] 2021-07-05 12:58
I have a fix (conf-> run_conf) - likely bad cherry-pick. Looking at why it has not been caught by the test_harness (the tests for dag triggering seem to pass :(.

**Comment by kaxil** [comment] 2021-07-05 13:07
Looks like we already had a fix: https://github.com/apache/airflow/pull/16648

**Comment by potiuk** [comment] 2021-07-05 13:11
Yep. That's it. Also it has not been caught in the tests because the test was quarantined. Looks like we need to take a close look at the quarantined tests and fix them.

**Comment by kaxil** [comment] 2021-07-05 13:53
I have cherry-picked it to v2-1-stable and v2-1-test, we will cut a 2.1.2 release which should be available to the users by the end of this week.

Until then, please use the API or CLI to trigger dags.

**Comment by vikramcse** [comment] 2021-07-05 13:57
yes I will use the api till then
thanks @potiuk and @kaxil for checking this issue 👍

**Comment by ashb** [comment] 2021-07-07 10:31
Closing this issue as the fix is merged and it will be released soon.

**Closed as completed by ashb** 2021-07-07 10:31 UTC
Labels: kind:bug, priority:high
