### ISSUE TITLE
airflow webserver error when updated to airflow 2.0

### ISSUE THREAD

**Issue by Anjali-bisht** [apache/airflow#13971] opened 2021-01-29 08:05 UTC
**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: MAC
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: PIP3
- **Others**:

**What happened**:

**Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.9.0
Airflow version: 2.0.0
Node: 192-168-1-101.tpgi.com.au
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/usr/local/lib/python3.9/site-packages/flask/sessions.py", line 379, in save_session
    response.set_cookie(
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/base_response.py", line 468, in set_cookie
    dump_cookie(
  File "/usr/local/lib/python3.9/site-packages/werkzeug/http.py", line 1217, in dump_cookie
    raise ValueError("SameSite must be 'Strict', 'Lax', or 'None'.")
ValueError: SameSite must be 'Strict', 'Lax', or 'None'.**

**How to reproduce it**:

**Anything else we need to know**:

**Comment by turbaszek** [comment] 2021-01-29 10:42
Shouldn't https://github.com/apache/airflow/pull/11873 fix it @kaxil ?

**Comment by potiuk** [comment] 2021-01-29 11:31
Can you run `pip check` ? and report what you see?

**Comment by potiuk** [comment] 2021-01-29 11:37
Also no matter what. The problem you might have is that you are using Python 3.9. Python 3.9 is NOT officially supported yet by Airflow. You need to downgrade Python to 3.8 @Anjali-bisht.

Please also follow the installation guide http://airflow.apache.org/docs/apache-airflow/stable/installation.html when you install airflow. You need to run Airflow with the right `--constraint` flag if you want to make sure all dependencies are installed in proper versions.

I am closing this issue as invalid for now (Python 3.9) - please try with Python 3.8 (and recommended installation method) if you still see a problem please report additional information here including `pip check` and we will reopen it if we see that the problem still persist.

**Comment by turbaszek** [comment] 2021-01-29 12:44
@potiuk I installed airflow from master using constraints and Python 3.6 and I faced the same issue

**Comment by kaxil** [comment] 2021-01-29 13:13
> @potiuk I installed airflow from master using constraints and Python 3.6 and I faced the same issue

Can you try with just Airflow 2.0.0 too --- that seems weird -- unless a recently merged change did something or due to a new version of some library. Any who I will also test and report back later today

**Comment by kurtqq** [comment] 2021-01-29 13:52
I reported this several hours ago as well in https://github.com/apache/airflow/issues/11871
i still see this error when opening the webserver using breeze with master if I select SQLite as database.
I don't see this for MySQL / PostgreSql

**Comment by potiuk** [comment] 2021-01-29 18:34
Wohoo. needs more investigation then :)

**Comment by kaxil** [comment] 2021-01-29 19:31
I was not able to reproduce this with breeze:

This is what I ran and worked fine
```
 ./breeze start-airflow  --backend sqlite --python 3.6  --force-pull-images
```

**Comment by gdevanla** [comment] 2021-01-31 19:50
I observe the same issue. Here is what I think the issue is:

In previous versions of airflow, the `cookie_samsite` value in the config file was allowed to be `empty`.  But, looks like it required from Airflow 2.0.0 onwards.  Setting that value to `lax` or `Strict`should resolve this issue, I think.

**Comment by kaxil** [comment] 2021-02-01 15:17
@Anjali-bisht / @turbaszek / @kurtqq Can you folks try changing the value to `Lax` and see if that works for you?

https://github.com/apache/airflow/blob/master/UPDATING.md#the-default-value-for-webserver-cookie_samesite-has-been-changed-to-lax

**Comment by jhtimmins** [comment] 2021-02-04 22:49
@kaxil @potiuk @gdevanla Isn't this because migrating from 1.X to 2.0 requires the 2.0 config file (plus whatever custom configs you have), but if Airflow already has a `.config` file from 1.X, the 2.0 won't be used?

**Comment by kaxil** [comment] 2021-02-10 12:16
Yes that is true @jhtimmins . If the config is already there the user needs to update to `Lax` which is the current default.

We could actually add a check to make it easier. Let me see if I can reproduce this with a 1.10.x config

**Comment by turbaszek** [comment] 2021-02-10 16:15
@kaxil I can confirm that setting `Lax` solved the issue (sorry for late response)

**Comment by kaxil** [comment] 2021-02-10 23:33
https://github.com/apache/airflow/pull/14183 should take care of this for users migrating from 1.10.x to 2.0.x with same config

**Closed as completed** 2021-02-11 00:20 UTC
Labels: kind:bug, area:webserver, invalid, pending-response
