### ISSUE TITLE
Unable to log to Azure PVC

### ISSUE THREAD

**Issue by jagusztinl** [apache/airflow#15482] opened 2021-04-22 08:24 UTC
**Apache Airflow version**:
2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
Openshift 4.5 on Azure

**Environment**:
Azure PVC

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Installed Airflow 2.0.1 to OKD, on Azure, defined Azure PVC, fileshare to store the logs

[Yesterday 9:18 PM] 
    Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 225, in task_run
    ti.init_run_context(raw=args.raw)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1987, in init_run_context
    self._set_context(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 54, in _set_context
    set_context(self.log, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 174, in set_context
    handler.set_context(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_task_handler.py", line 56, in set_context
    local_loc = self._init_file(ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_task_handler.py", line 258, in _init_file
    os.chmod(full_path, 0o666)
PermissionError: [Errno 1] Operation not permitted: '/opt/airflow/logs/example_bash_operator/runme_0/2021-04-20T00:00:00+00:00/1.log'
 

**What you expected to happen**:
Write logs to PVC

Permission problem, Airflow do not handle well cloud storage
**How to reproduce it**:

**Anything else we need to know**:

**Comment by janvaca92** [comment] 2021-05-03 08:23
We have faced the same issue. The problem is that Azure fileshare does not allowed changing file permissions via os.chmod. With the managed disks is possible but they require ReadWriteOnce and its is not suitable for Airflow logs pvc.

**Comment by uranusjr** [comment] 2021-05-04 10:34
I *guess* it's not entirely unreasonable to simply skip the chmod call (and log a warning) if it fails.

**Comment by eladkal** [comment] 2021-12-01 06:57
> I _guess_ it's not entirely unreasonable to simply skip the chmod call (and log a warning) if it fails.

looks like we already do that but not for permission errors
https://github.com/apache/airflow/blob/f6dca1fa5e70ef08798adeb5a6bfc70f41229646/airflow/utils/log/file_task_handler.py#L277-L281

**Comment by uranusjr** [comment] 2021-12-01 07:01
`PermissionError` is a subclass of `OSError`, so this should cover it. But I think this needs to cover the `open().close()` line above so it catches permission errors to the _parent_ directory.

**Comment by uranusjr** [comment] 2021-12-01 07:03
Oh actually, the try-catch was added in 2.1. So we should close this.

**Closed as completed by uranusjr** 2021-12-01 07:03 UTC
Labels: kind:bug, area:logging, area:core

**Comment by eladkal** [comment] 2021-12-01 07:06
Ah right! great then :)

**Comment by ijaniszewski** [comment] 2025-07-28 10:00
Hi!

It does not throw an error anymore, but still logs a warning (which will eventually disappear after sometime). Its really annonying. I tried to change the ownership of `logs` dir (as `root`), but while `chown` appeared to run (exit code 0), it had no effect. As it is Azure fileshare, it cannot be done. Is there any update on this maybe?
