### ISSUE TITLE
connexion 3.0.0 breaks standalone deployment

### ISSUE THREAD

**Issue by vtrbraga** [apache/airflow#35390] opened 2023-11-02 23:23 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

I had [connexion](https://github.com/spec-first/connexion) unpinned in my Airflow standalone local environment, and after a docker image cache flush, I couldn't get the environment back up.
After some investigation, I traced the issue to this the new connexion 3.0.0 release. Pinning that package to `2.14.2 `solves the issue and the environment loads just fine.

Airflow init traceback
```
airflow_1  | Traceback (most recent call last):
airflow_1  |   File "/usr/local/bin/airflow", line 8, in <module>
airflow_1  |     sys.exit(main())
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/__main__.py", line 48, in main
airflow_1  |     args.func(args)
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/cli/cli_parser.py", line 52, in command
airflow_1  |     return func(*args, **kwargs)
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/standalone_command.py", line 48, in entrypoint
airflow_1  |     StandaloneCommand().run()
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/standalone_command.py", line 64, in run
airflow_1  |     self.initialize_database()
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/standalone_command.py", line 183, in initialize_database
airflow_1  |     appbuilder = cached_app().appbuilder
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/www/app.py", line 167, in cached_app
airflow_1  |     app = create_app(config=config, testing=testing)
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/www/app.py", line 151, in create_app
airflow_1  |     init_api_connexion(flask_app)
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/www/extensions/init_views.py", line 216, in init_api_connexion
airflow_1  |     connexion_app = App(__name__, specification_dir=spec_dir, skip_error_handlers=True, options=options)
airflow_1  | TypeError: FlaskApp.__init__() got an unexpected keyword argument 'skip_error_handlers'
```

### What you think should happen instead

Airflow should enforce the connexion dependency `<3.0.0` so package managers won't pick up the new major release, which [contains breaking changes by design](https://github.com/spec-first/connexion/issues/1781)

### How to reproduce

Regular Airflow standalone deployment locally using docker.

python==3.10.13
connexion==3.0.0 (auto-pulled by airflow dependency when rebuilding image, wasn't in my `requirements.txt`)
airflow==2.5.1

### Operating System

Ubuntu 22.04.3 LTS

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==7.1.0
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-common-sql==1.3.3
apache-airflow-providers-dbt-cloud==2.3.1
apache-airflow-providers-docker==3.4.0
apache-airflow-providers-ftp==3.3.0
apache-airflow-providers-http==4.1.1
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-jdbc==3.3.0
apache-airflow-providers-microsoft-mssql==3.3.2
apache-airflow-providers-microsoft-winrm==3.1.1
apache-airflow-providers-odbc==3.2.1
apache-airflow-providers-pagerduty==3.1.0
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-redis==3.1.0
apache-airflow-providers-sendgrid==3.1.0
apache-airflow-providers-sftp==4.2.1
apache-airflow-providers-snowflake==4.0.2
apache-airflow-providers-sqlite==3.3.1
apache-airflow-providers-ssh==3.4.0

### Deployment

Docker-Compose

### Deployment details

- `Makefile` to include environment variables and call `docker-compose`
- `entrypoint.sh` to call `airflow standalone`
- custom dockerfile to install requirements

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2023-11-02 23:36
Duplicate of #35375, connexion already limited in 2.7.3 but you are also not installing airflow properly - the  only installation method that is recommended by Airflow maintainers would have prevented you (it's specifically designed to protect users against newly relesead breaking packages to break airflow). You should adapt your installation methods to follow our recommendations. https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html

**Closed as completed by potiuk** 2023-11-02 23:36 UTC
Labels: kind:bug, area:core, needs-triage
