### ISSUE TITLE
Add dark theme, by @prefers-color-theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [apache/airflow#31864] opened 2023-06-13 05:25 UTC
### What do you see as an issue?

For many users - difficult to read from the white background. Especially at low light conditions.

### Solving the problem

By leveraging this CSS media query https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2023-06-13 09:07
Closing as duplicate of https://github.com/apache/airflow/issues/11334
This is indeed something we are looking into and it's planned as part of AIP-38

**Closed by eladkal** 2023-06-13 09:07 UTC
Labels: kind:bug, kind:documentation, needs-triage

**Comment by potiuk** [comment] 2023-06-13 10:44
> But this is about documentation pages.

So it should be added to "airlfow-site" project - because this is where we keep our documentation website theme and everything.
