### ISSUE TITLE
Logs using @task.virtualenv in Kubernetes

### ISSUE THREAD

**Issue by leoneuwald** [apache/airflow#34865] opened 2023-10-11 14:54 UTC
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hey.

We are running Airflow 2.6.3 in K8s, and when we use the decorator @task.virtualenv, the logs aren't printed (S3 remote or Pod output).

I tried this https://github.com/apache/airflow/issues/27012#issuecomment-1361342168, but it also doesn’t work.

### What you think should happen instead

The logs should be printed in the Pod output or written in the S3 remote.

### How to reproduce

```
from airflow.decorators import task, dag

@dag(default_args={
        'owner': 'data',
        'start_date': '2023-07-07'
    },
    schedule_interval=None,
    max_active_runs=1,
    catchup=False,
    tags=['test'])
def test_virtualenv():

    @task.virtualenv(
        task_id='test_log_virtual_env',
    )
    def test_log_virtual_env():
        import logging
        logger = logging.getLogger(__name__)
        logger.setLevel(logging.INFO)
        logger.info('Start log')

    @task
    def test_log():
        import logging
        logger = logging.getLogger(__name__)
        logger.setLevel(logging.INFO)
        logger.info('Start log')

    test_log() >> test_log_virtual_env()


test_virtualenv_dag = test_virtualenv()
```

Run the following DAG in Airflow deployed in Kubernetes and check that we only see the `Start log`, in the test_log task. The test_log_virtual_env does not print anything.

### Operating System

K8s

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jens-scheffler-bosch** [comment] 2023-10-11 21:50
Just to double-check, are you able to make a regression on Airflow 2.7.1?

**Comment by leoneuwald** [comment] 2023-10-12 16:48
> Just to double-check, are you able to make a regression on Airflow 2.7.1?

No, I'm not. :/

**Comment by jens-scheffler-bosch** [comment] 2023-10-12 19:49
@leoneuwald Okay, I did a regression in my local Airflow test env with version 2.7.2 in Celery as well as deployed your example DAG and used the standard `example_python_operator` DAG in Breeze Kubernetes deployment. In all these environments logs are showing up as expected.
I have no S3 backend and used local Pod output only. But as the virtualenv logs are just mixed in the other logs I don't see a difference to other tasks at the end.
Therefore I am closing this issue, seems to be a local artifact. Not able to reproduce. I assume is related to your local setup

**Comment by jens-scheffler-bosch** [comment] 2023-10-12 19:50
> No, I'm not. :/

Feel free to provide more notes or re-open if you re-tested with a different setup.

**Closed as completed by jens-scheffler-bosch** 2023-10-12 19:49 UTC
Labels: kind:bug, Can't Reproduce, needs-triage
