### ISSUE TITLE
Make run-config accessible in DagRun details view

### ISSUE THREAD

**Issue by awildturtok** [apache/airflow#17161] opened 2021-07-22 13:29 UTC
**Description**

I would like to have the run-config available for inspection in the dag details.

**Use case / motivation**

Figuring out what was used to trigger a dag, partially for reuse, but also to introspect what went wrong. It's currently possible to use the REST-API for that but a step removed, and our users of Airflow aren't supposed to use APIs.

**Are you willing to submit a PR?**

With enough guidance yes.

**Comment by kaxil** [comment] 2021-07-22 22:07
Isn't this duplicate of the other issue you created: https://github.com/apache/airflow/issues/17085 ?

**Comment by awildturtok** [comment] 2021-07-23 07:14
No, my prior issue was to get better feedback on job-submission, this is to see what was submitted.

`curl -X GET "http://localhost:9091/api/v1/dags/$DAG_ID/dagRuns/$DAG_RUN_ID" -H "accept: application/json" | jq '.conf' ` is how we access it at the moment. Or some of our validating tasks mentioned in #17085 log it.

**Comment by gutomotta** [comment] 2021-07-27 14:16
That would be a very useful feature!

Btw I didn't know I could use that endpoint as a workaround, thanks!

**Comment by uranusjr** [comment] 2021-07-28 06:58
What do you mean by “DagRun details view”? We currently only have a table of DagRuns (`http://localhost:28080/dagrun/list/`), and that table already has a **Conf** column.

**Comment by kaxil** [comment] 2021-07-28 07:09
I **guess** there are referring to Dag Details page on UI:
![image](https://user-images.githubusercontent.com/8811558/127279283-fdff2ff2-6569-42e4-932c-420956716046.png)

However, that page is "DAG Details" view not DagRun details @awildturtok . It shouldn't contain DagRun details apart from summaries / counts of DagRun status.

Like @uranusjr mentioned, we already have a Table of DagRuns which has a conf column which you can use to check what was passed.
![image](https://user-images.githubusercontent.com/8811558/127279109-bb1beefb-292a-4a74-8771-f62c037baa71.png)

**Comment by kaxil** [comment] 2021-07-28 07:10
(I am going to close this one as the feature is already there -- we can re-open if you think you need something else)

**Closed as completed by kaxil** 2021-07-28 07:10 UTC
Labels: kind:feature, area:UI

**Comment by awildturtok** [comment] 2021-07-28 13:41
I didn't know about the listing of DagRuns+Config. I was looking for exactly that. It's a bit hidden so maybe placing it a bit more prominent when in dag-view would help?

**Comment by potiuk** [comment] 2021-07-28 13:52
The problem with DagView is that it is not "DagRun" view - and it's the DagRun that has relation to conf not the Dag.. There might be different conf for every run potentially.

**Comment by potiuk** [comment] 2021-08-01 22:51
> I didn't know about the listing of DagRuns+Config. I was looking for exactly that. It's a bit hidden so maybe placing it a bit more prominent when in dag-view would help?

I welcome you to propose a PR for that. You can easily open a PR to documentation by using "Suggest a change on this page" button (bottom-left of each page of our documentation) without having any develipment environment, using the GitHub UI.  Probably, as person who struggled with it you know best where you'd be looking for it! This is one of the best and easiest way to contribute back in-return for the free software you get :)
