### ISSUE TITLE
Function arg list mismatch between provider code and main code when using AWS SES

### ISSUE THREAD

**Issue by zachliu** [apache/airflow#21878] opened 2022-02-28 21:48 UTC
### Apache Airflow version

2.2.4 (latest released)

### What happened

After setting up alert emails using AWS SES as instructed [here](https://airflow.apache.org/docs/apache-airflow/stable/howto/email-config.html#send-email-using-aws-ses), I received the following error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2103, in email_alert
    send_email(self.task.email, subject, html_content)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/email.py", line 57, in send_email
    return backend(
TypeError: send_email() got multiple values for argument 'from_email'
```

### What you expected to happen

the `send_email` method in https://github.com/apache/airflow/blob/d94fa378305957358b910cfb1fe7cb14bc793804/airflow/providers/amazon/aws/utils/emailer.py#L25-L37 doesn't match the invocation of the `backend` method in https://github.com/apache/airflow/blob/ee9049c0566b2539a247687de05f9cffa008f871/airflow/utils/email.py#L57-L70 

in the former (provider-amazon), the `from_email` is the first positional argument. However in the latter (main airflow), `from_email` is misplaced as a keyword argument.

### How to reproduce

1. Use `Airflow 2.2.4` with `providers-amazon/3.0.0`
2. Observe the log from a failed DAG

### Operating System

Amazon Linux 2

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon 3.0.0

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by uranusjr** [comment] 2022-02-28 22:33
Looks like this is introduced in 1543dc28f4a2f1631dfaedd948e646a181ccf7ee. I think we should fix this (by moving the `from_email` argument to the correct place), and also use this chance to 1. convert `send_email` _caller_ to always use keyword arguments.

**Comment by potiuk** [comment] 2022-03-01 08:36
I beleive that it has been fixed in 3.0.0 (the issue was raised here https://github.com/apache/airflow/issues/21671  and I thought I fixed it in https://github.com/apache/airflow/pull/21681).

What is exactly your configuration @zachliu? Do you have maybe a connection setup with "from_email" extra? That could explain the duplicate from_email entry.

**Comment by potiuk** [comment] 2022-03-01 08:38
Ah no... I see  the problem :(

**Comment by potiuk** [comment] 2022-03-01 08:49
Ah yeah. My fix has not yet been released when 2.2.4 has been released simply. It will be fixed in the release I am about to release today. Maybe (I will see how many changes we have) since this is quite an important problem, we might even update constraints and re-generate images for 2.2.4 to include the new amazon provider with the fix.

**Comment by potiuk** [comment] 2022-03-01 08:50
Closing as duplicate of #21681

**Closed as completed by potiuk** 2022-03-01 08:50 UTC
Labels: kind:bug, area:core

**Comment by zachliu** [comment] 2022-03-01 14:39
@potiuk great, thanks! eagerly waiting for `providers-amazon-3.0.1` :grin:

**Comment by potiuk** [comment] 2022-03-01 14:58
Yeah. I merge a few last changes and I will be ready to prepare the relase. Loking forward to helping testing it @zachliu :smile:

**Comment by potiuk** [comment] 2022-03-15 15:41
See #22264  - it contains information about the release candidate and link to instructions on how to test it

**Comment by repl-mike-roest** [comment] 2022-03-15 15:43
Awesome yep @potiuk let me see what I can do to help out on things
