### ISSUE TITLE
Failed to build Docker image using Dockerfile in master branch 

### ISSUE THREAD

**Issue by msk-psp** [apache/airflow#15790] opened 2021-05-12 05:21 UTC
apache Airflow version

2.0.2

Environment

Configuration: Dockerfile
OS (e.g. from /etc/os-release): ubuntu 16.04
Install tools: sudo docker build -t airflow-with-browser .

What happened:

I Can't build a docker image using Dockerfile in master branch 
The python package dependency error occurred while building a image

<img width="1871" alt="스크린샷 2021-05-12 오후 2 16 16" src="https://user-images.githubusercontent.com/23733661/117922125-f416cd00-b32c-11eb-84e2-40bfec7c16f0.png">

```
The conflict is caused by:
    connexion[flask,swagger-ui] 2.6.0 depends on connexion 2.6.0 (from https://files.pythonhosted.org/packages/a7/27/d8258c073989776014d49bbc8049a9b0842aaf776f462158d8a885f8c6a2/connexion-2.6.0-py2.py3-none-any.whl#sha256=c568e579f84be808e387dcb8570bb00a536891be1318718a0dad3ba90f034191 (from https://pypi.org/simple/connexion/) (requires-python:>=3.6))
    The user requested (constraint) connexion==2.7.0
```

I think there a version mismatching between connexion[flask, swagger-ui] and connexion.. 

![스크린샷 2021-05-12 오후 2 19 43](https://user-images.githubusercontent.com/23733661/117922342-4526c100-b32d-11eb-9d47-4257bca1efb0.png)

What you expected to happen:

Succeed to build a Airflow image

To Replicate:
git clone https://github.com/apache/airflow
cd airflow
sudo docker build -t airflow-with-browser .

**Comment by potiuk** [comment] 2021-05-12 06:10
I think master constraints are not refreshed recently. Let me do that now.

**Comment by potiuk** [comment] 2021-05-12 08:09
I can reproduce it but it is really strange. I will have to take a closer look at it. Seems that all is legit and "airflow 2.0.2" installs properly with the 2.0.2 constraints but for some reason it falls back to connexion 2.6.0 in our image where it should (and it's been like that for quite a while) use 2.0.7.

**Comment by msk-psp** [comment] 2021-05-12 08:20
> I can reproduce it but it is really strange. I will have to take a closer look at it. Seems that all is legit and "airflow 2.0.2" installs properly with the 2.0.2 constraints but for some reason it falls back to connexion 2.6.0 in our image where it should (and it's been like that for quite a while) use 2.0.7.

**Comment by potiuk** [comment] 2021-05-12 08:31
@uranusjr - maybe you can have some ideas before I dig deeper ?

It's easy reproducible with `docker build --build-arg AIRFLOW_VERSION="2.0.2" -t airflow-with-browser .` . Seems that the right (2.0.2) constraints are used, and they contain connexion 2.7.0 but for some reason in the middle of installation PIP downloads and starts looking for matching versions of packages for `connexion 2.6.0`  - really, really strange.

**Comment by potiuk** [comment] 2021-05-12 08:33
And constraints SHOULD contain all package with fixed versions (including provider packages). The only reason that comes to my mind - if some package version was removed from PyPI, then PIP could start looking for another version and this could cause a "chain reaction"?

**Comment by uranusjr** [comment] 2021-05-12 11:56
Pip’s conflict reporting doesn’t work very well when the conflict involves extras, unfortunately. When you see a conflict with extras, it’s usually not the package itself that’s causing the conflict 😞 I do have plan to improve it if I have the time. I’ll try to dig deeper what exactly is the cause.

**Comment by uranusjr** [comment] 2021-05-12 12:49
I think I’ve got it.

```
distribution                              dependency
====================================================================================================
(root)                                    apache[...]
apache[google]==2.0.2                     pandas-gbq<0.15.0
pandas-gbq==0.14.1                        google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1
google-cloud-bigquery[bqstorage]==1.28.0  google-cloud-bigquery-storage<2.0.0dev,>=1.0.0
                                          pyarrow<2.0dev,>=1.0.0
```

But the constraints have

```
google-cloud-bigquery-storage==2.4.0
pyarrow==2.0.0
```

Completely unrelated to `connextion` 😓

**Comment by potiuk** [comment] 2021-05-12 13:22
Aaaargh ... I thought we will be good with pyarrow.  Ithe problem is I think only with Py21 then and it i gone for master/upcoming 2.1 i will check if specifying PIP version helps

**Comment by potiuk** [comment] 2021-05-12 13:31
Confirmed. It works when you switch to PIP 20.2.4

```
docker build --build-arg AIRFLOW_VERSION="2.0.2" --build-arg AIRFLOW_PIP_VERSION=20.2.4 -t airflow-with-browser .
``` 

I will update the documentation to make it clear that you need to add the build arg when build pre-2.1 images.

**Comment by potiuk** [comment] 2021-05-12 14:53
OK. I fixed in the upcoming #15802 - I added automated fallback to PIP 20.2.4 when pre-2.1 version of Airflow is built using the newer image (both 1.10* and 2.0.*). Once this is merged you will not have to specify the PIP_VERSION @msk-psp

**Comment by potiuk** [comment] 2021-05-12 14:53
Thanks for reporting in @msk-psp !

**Comment by potiuk** [comment] 2021-05-12 14:54
And thanks @uranusjr for help !

**Comment by msk-psp** [comment] 2021-05-12 15:09
@potiuk thank you for your fast responding ^^*

**Closed as completed** 2021-05-14 12:10 UTC
Labels: kind:bug
