### ISSUE TITLE
Task Duration Bug: Doesn't respect number of runs

### ISSUE THREAD

**Issue by kaxil** [apache/airflow#8166] opened 2020-04-06 17:22 UTC
The "number of runs" is set to 5, however, there's a month worth of taskinstances on this plot. It used to be exactly 5 dots in the previous versions. I have pinpointed the issue to the following method: https://github.com/apache/airflow/blob/1.10.10rc3/airflow/models/dag.py#L820-L821 -- it returns may more taskinstances than limited by `start_date`

![image](https://user-images.githubusercontent.com/8811558/78551458-aa8cb200-77fd-11ea-94a1-7adea7eac659.png)

>Task Duration and Task Tries plots for the same dag, thought that might be helpful 

![image](https://user-images.githubusercontent.com/8811558/78551699-05bea480-77fe-11ea-8eca-22c114fb5b45.png)

![image](https://user-images.githubusercontent.com/8811558/78551705-0820fe80-77fe-11ea-8c58-b229c9d1dcc1.png)

From @KostyaEsmukov :

>I believe it was fine in 1.10.9. Not 100% sure, but, like, 99% :)

Need to verify if it is a new bug in 1.10.10rc3

**Comment by ashb** [comment] 2020-04-06 17:23
I can't reproduce this on 1.10.10rc3 - it does change the number of runs shown @KostyaEsmukov.

Do you have a large number of manually triggered runs in between scheduled runs? This may be the cause of this behaviour, as the chart shows anything from base_date to 25 scheduled runs earlier, and has done that since basically for ever from what I can tell.

**Comment by kaxil** [comment] 2020-04-06 17:26
Here is the below screenshot with default of 25 runs:

![image](https://user-images.githubusercontent.com/8811558/78586917-1b4ec100-7834-11ea-996c-1edae5194696.png)

When I change it to 5:

![image](https://user-images.githubusercontent.com/8811558/78586955-2dc8fa80-7834-11ea-8691-cf1a9717bc9b.png)

**Comment by ashb** [comment] 2020-04-06 17:32
I've confirmed that this is caused by manually triggered runs, and the same behaviour has existed since 1.10.3 (the earliest version I could easily run) - I suspect it goes back even further

So this one is not a regression.

**Comment by KostyaEsmukov** [comment] 2020-04-06 17:56
> I've confirmed that this is caused by manually triggered runs,

Could you please elaborate on what exactly do you mean by a manually triggered run?
- If that's an external dagrun, then this is absolutely not the case for the pics from my installation, all dagruns were scheduled.
- If that's a task instance restart, then that installation might have had some taskinstances cleared or marked as failed, but their execution_date does not change from the scheduled one, and I don't see how that could break the "number of runs" setting.

> So this one is not a regression.

I believe the number of runs was respected in 1.10.9.

I'll try to debug on that installation and see if I can find the cause.

**Comment by ashb** [comment] 2020-04-06 18:00
If you are able to provide me with a dump of your `dag` and `task_instance` tables (or the whole DB apart from connections and variables tables) that would help if you aren't able to debug it yourself.

**Comment by KostyaEsmukov** [comment] 2020-04-06 18:02
I'm sorry but I cannot do that. I'll try myself

**Comment by KostyaEsmukov** [comment] 2020-04-06 18:37
I took a dag with 5 minutes interval (not the one on the pictures).

And the reason for it generating way more points than the "number of runs" param is, I think, the following:

```
>>> dag._schedule_interval
datetime.timedelta(days=1)
>>> dag.schedule_interval
datetime.timedelta(seconds=300)
```

Because of that the `dag.date_range` (https://github.com/apache/airflow/blob/1.10.10rc3/airflow/www_rbac/views.py#L1647) function returns taskinstances with 1 day interval instead of 5 minutes interval.

Looking further... The root cause of that desynchronization between the properties is still unclear to me.

**Comment by KostyaEsmukov** [comment] 2020-04-06 18:45
Looks like it is related to dag serialization:

```
>>> dagbag = models.DagBag(settings.DAGS_FOLDER, store_serialized_dags=True)
>>> dag = dagbag.get_dag("<...mydag...>")
>>> dag._schedule_interval
datetime.timedelta(days=1)
>>> dag.schedule_interval
datetime.timedelta(seconds=300)


>>> dagbag = models.DagBag(settings.DAGS_FOLDER, store_serialized_dags=False)
>>> dag = dagbag.get_dag("<...mydag...>")
>>> dag._schedule_interval
datetime.timedelta(seconds=300)
>>> dag.schedule_interval
datetime.timedelta(seconds=300)
```

**Comment by KostyaEsmukov** [comment] 2020-04-06 18:53
Okay, I guess I found out why they desynchronize:
- serialized dag calls DAG's inititalizer with default daily timedelta: https://github.com/apache/airflow/blob/1.10.10rc3/airflow/serialization/serialized_objects.py#L539
- and then sets just the public `schedule_interval` attribute during deserialization: https://github.com/apache/airflow/blob/1.10.10rc3/airflow/serialization/serialized_objects.py#L559

So I guess you were right to say that this is not a regression in 1.10.10. Probably I just missed that when I switched on dags serialization.

**Comment by kaxil** [comment] 2020-04-06 18:56
Thanks for confirming and digging into it.

**Comment by KostyaEsmukov** [comment] 2020-04-06 18:59
Although this is not a regression in 1.10.10, the issue is still here, so shouldn't the bug be kept open?

**Comment by kaxil** [comment] 2020-04-06 19:01
> Although this is not a regression in 1.10.10, the issue is still here, so shouldn't the bug be kept open?

Oops yes, I will fix it in Airflow Master

**Comment by KostyaEsmukov** [comment] 2020-04-06 19:59
The following little (but dirty) patch fixes the issue for me:

```
diff --git a/airflow/serialization/serialized_objects.py b/airflow/serialization/serialized_objects.py
index 0c73946e7..5602f5c98 100644
--- a/airflow/serialization/serialized_objects.py
+++ b/airflow/serialization/serialized_objects.py
@@ -541,7 +541,8 @@ class SerializedDAG(DAG, BaseSerialization):
         """Deserializes a DAG from a JSON object.
         """

-        dag = SerializedDAG(dag_id=encoded_dag['_dag_id'])
+        schedule_interval = cls._deserialize(encoded_dag['schedule_interval'])
+        dag = SerializedDAG(dag_id=encoded_dag['_dag_id'], schedule_interval=schedule_interval)

         for k, v in encoded_dag.items():
             if k == "_downstream_task_ids":
--
2.25.0
```

A thought towards a better fix: maybe instead of calling `setattr` on a `SerializedDAG` instance the `encoded_dag` arguments should be passed as kwargs to the `SerializedDAG` initializer?

**Closed as completed** 2020-04-09 18:45 UTC
Labels: kind:bug, area:webserver, area:serialization
