### ISSUE TITLE
Airflow fails to initdb with cattrs 1.1.0

### ISSUE THREAD

**Issue by tdbabas** [apache/airflow#11965] opened 2020-10-30 09:48 UTC
**Apache Airflow version**:

1.10.12

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

N/A

**Environment**:

- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): Centos 7
- **Kernel** (e.g. `uname -a`): 3.10.0-229.el7.x86_64
- **Install tools**: pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
- **Others**:

**What happened**:

Following the instructions [here](http://airflow.apache.org/docs/stable/start.html), I encountered an issue at the `airflow initdb` stage:

```
[xxx@xxx ~]# airflow initdb
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 26, in <module>
    from airflow.bin.cli import CLIFactory
  File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 94, in <module>
    api_module = import_module(conf.get('cli', 'api_client'))  # type: Any
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/site-packages/airflow/api/client/local_client.py", line 24, in <module>
    from airflow.api.common.experimental import delete_dag
  File "/usr/local/lib/python3.6/site-packages/airflow/api/common/experimental/delete_dag.py", line 26, in <module>
    from airflow.models.serialized_dag import SerializedDagModel
  File "/usr/local/lib/python3.6/site-packages/airflow/models/serialized_dag.py", line 35, in <module>
    from airflow.serialization.serialized_objects import SerializedDAG
  File "/usr/local/lib/python3.6/site-packages/airflow/serialization/serialized_objects.py", line 28, in <module>
    import cattr
  File "/usr/local/lib/python3.6/site-packages/cattr/__init__.py", line 1, in <module>
    from .converters import Converter, GenConverter, UnstructureStrategy
  File "/usr/local/lib/python3.6/site-packages/cattr/converters.py", line 16, in <module>
    from attr import fields, resolve_types
ImportError: cannot import name 'resolve_types'
```

**What you expected to happen**:

I expected the Airflow DB to be initialised as per the instructions. 

**How to reproduce it**:

On a fresh installation, follow the Quick Start guide until the `apache initdb` stage.

**Anything else we need to know**:

Investigation suggests that this was caused by a Python dependency; specifically `cattrs==1.1.0`, which was released yesterday (2020-10-29). Downgrading `cattrs` manually to 1.0.0 does fix the issue and allows the Airflow database to be initialised:

```
[xxx@xxx ~]# pip3 install cattrs==1.0.0
Collecting cattrs==1.0.0
  Downloading https://files.pythonhosted.org/packages/17/5b/6afbdaeb066ecf8ca28d85851048103ac80bb169491a54a14bd39823c422/cattrs-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: attrs>=17.3 in /usr/local/lib/python3.6/site-packages (from cattrs==1.0.0)
Installing collected packages: cattrs
  Found existing installation: cattrs 1.1.0
    Uninstalling cattrs-1.1.0:
      Successfully uninstalled cattrs-1.1.0
Successfully installed cattrs-1.0.0
[xxx@xxx ~]# airflow initdb            
DB: sqlite:////path/to/airflow.db
[2020-10-30 09:36:05,431] {db.py:378} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e3a246e0dc1, current schema
INFO  [alembic.runtime.migration] Running upgrade e3a246e0dc1 -> 1507a7289a2f, create is_encrypted
/usr/local/lib/python3.6/site-packages/alembic/ddl/sqlite.py:44: UserWarning: Skipping unsupported ALTER for creation of implicit constraintPlease refer to the batch mode feature which allows for SQLite migrations using a copy-and-move strategy.
...
Done.
```

**Comment by cgddrd** [comment] 2020-10-30 10:29
Can confirm we're experiencing this as part of our production stack (auto scaling actions are now failing) - a hotfix would be greatly appreciated.

**Comment by kaxil** [comment] 2020-10-30 11:04
You can use the following for now, this will be fixed in 1.10.13

```pip install apache-airflow==1.10.12 \
 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.7.txt"
```

**Comment by cgddrd** [comment] 2020-10-30 11:37
Many thanks @kaxil

**Comment by kaxil** [comment] 2020-10-30 13:27
https://github.com/apache/airflow/pull/11969 -- This PR will be included in 1.10.13 and should fix this issue too

**Closed as completed** 2020-10-30 15:14 UTC
Labels: kind:bug

**Comment by jodmoreira** [comment] 2020-11-02 00:14
> You can use the following for now, this will be fixed in 1.10.13
> 
> ```shell
> pip install apache-airflow==1.10.12 \
>  --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.7.txt"
> ```

It worked! Thanks!

**Comment by zachliu** [comment] 2020-11-03 15:13
@jodmoreira oh how i envy you, the constraint file `constraints-3.8.txt` doesn't work for my `1.10.12` :crying_cat_face: https://github.com/apache/airflow/issues/8467#issuecomment-720712897

**Comment by kaxil** [comment] 2020-11-03 15:26
> @jodmoreira oh how i envy you, the constraint file `constraints-3.8.txt` doesn't work for my `1.10.12` 😿 [#8467 (comment)](https://github.com/apache/airflow/issues/8467#issuecomment-720712897)

Just update both `attrs` and `cattrs` that too should work.

or just downgrade `cattrs`

**Comment by potiuk** [comment] 2020-11-04 07:55
Yeah. Constraints file does not work if you already have higher version installed.

**Comment by zachliu** [comment] 2020-11-04 17:52
@kaxil @potiuk ah, i'm sorry i didn't describe it clearly :sweat_smile: 
the constraint file `constraints-3.8.txt` did solve the `attr` and/or `cattrs` issue, but in order to use it i had to do the following changes due to https://github.com/apache/airflow/issues/8467#issuecomment-720712897:

original:
```
oauthlib==3.1.0
requests-oauthlib==1.3.0
```
my updates:
```
oauthlib==2.1.0
requests-oauthlib==1.1.0
```

**Comment by dark-spark2** [comment] 2020-11-05 12:21
@kaxil can I bump:
can I change attrs to higher version( attrs==20.1.0 ) for airflow 1.10.12?

**Comment by canerakin111** [comment] 2020-11-07 03:49
> You can use the following for now, this will be fixed in 1.10.13
> 
> ```shell
> pip install apache-airflow==1.10.12 \
>  --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.7.txt"
> ```

Thanks a lot!

**Comment by mmgithub123** [comment] 2020-11-09 07:44
great! 
I have the some question，
when i use pip3 install cattrs==1.0.0.
 fix my problem

**Comment by gaj995** [comment] 2020-11-11 18:47
> You can use the following for now, this will be fixed in 1.10.13
> 
> ```shell
> pip install apache-airflow==1.10.12 \
>  --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.7.txt"
> ```
Didn't work for me :(

**Comment by potiuk** [comment] 2020-11-11 19:23
> Didn't work for me :(

What do you mean by 'didn't work"? Can you please provide some specifics on what you tried and how it did not work?

**Comment by gaj995** [comment] 2020-11-12 14:07
> > Didn't work for me :(
> 
> What do you mean by 'didn't work"? Can you please provide some specifics on what you tried and how it did not work @gaj995 ?

Here is the error I am getting. I use the pip method that @kaxil posted above. 

On Ubantu 20.04.1
Python 3.8.5

`Traceback (most recent call last):
  File "/home/gaj995/.local/bin/airflow", line 25, in <module>
    from airflow.configuration import conf
  File "/home/gaj995/.local/lib/python3.8/site-packages/airflow/__init__.py", line 50, in <module>
    from airflow.models import DAG  # noqa: E402
  File "/home/gaj995/.local/lib/python3.8/site-packages/airflow/models/__init__.py", line 21, in <module>
    from airflow.models.baseoperator import BaseOperator, BaseOperatorLink  # noqa: F401
  File "/home/gaj995/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1116, in <module>
    @attr.s(auto_attribs=True)
AttributeError: module 'attr' has no attribute 's'`

**Comment by kaxil** [comment] 2020-11-12 14:59
@gaj995 

Since you are using Python 3.8 use the following:

```
pip install apache-airflow==1.10.12 \
 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.8.txt"
```

> > > Didn't work for me :(
> > 
> > 
> > What do you mean by 'didn't work"? Can you please provide some specifics on what you tried and how it did not work @gaj995 ?
> 
> Here is the error I am getting. I used the pip method that @kaxil posted above.
> 
> On Ubantu 20.04.1
> Python 3.8.5
> 
> ```
> `Traceback (most recent call last):
>   File "/home/gaj995/.local/bin/airflow", line 25, in <module>
>     from airflow.configuration import conf
>   File "/home/gaj995/.local/lib/python3.8/site-packages/airflow/__init__.py", line 50, in <module>
>     from airflow.models import DAG  # noqa: E402
>   File "/home/gaj995/.local/lib/python3.8/site-packages/airflow/models/__init__.py", line 21, in <module>
>     from airflow.models.baseoperator import BaseOperator, BaseOperatorLink  # noqa: F401
>   File "/home/gaj995/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1116, in <module>
>     @attr.s(auto_attribs=True)
> AttributeError: module 'attr' has no attribute 's'`
> ```

**Comment by potiuk** [comment] 2020-11-12 15:28
Good catch @kaxil!

**Comment by vinaymor002** [comment] 2020-11-26 10:50
Getting error with python 3.9.0 

`ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/xf/hwq0q8rn56xcd_830x9q24c40000gn/T/tmpk9hup6wq
       cwd: /private/var/folders/xf/hwq0q8rn56xcd_830x9q24c40000gn/T/pip-install-9jhr51fl/pandas`

Used below command
`pip install apache-airflow==1.10.12  --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.8.txt"`

**Comment by potiuk** [comment] 2020-11-26 12:06
> Getting error with python 3.9.0
> 
> `ERROR: Command errored out with exit status 1: command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/xf/hwq0q8rn56xcd_830x9q24c40000gn/T/tmpk9hup6wq cwd: /private/var/folders/xf/hwq0q8rn56xcd_830x9q24c40000gn/T/pip-install-9jhr51fl/pandas`
> 
> Used below command
> `pip install apache-airflow==1.10.12 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.8.txt"`

Python 3.9 has known problems with dependencies - we are not supporting it yet. This will happen after 2.0.

**Comment by rajnathsah** [comment] 2020-12-01 05:23
This issue seems to be fixed in 1.10.13.

**Comment by potiuk** [comment] 2020-12-01 08:50
Yep. And in 1.10.14 we have improved constraints that are not going to be broken (they pass 'pip check;)

**Comment by sephethus** [comment] 2020-12-03 17:04
Nothing works in this entire thread, nothing. I'm using docker-compose up to create a local instance and it all fails. 1.10.13, adding cattrs and attrs and upping the version of oauthlib and requests-oauthlib, nothing works, period. What now?

**Comment by potiuk** [comment] 2020-12-03 17:34
> Nothing works in this entire thread, nothing. I'm using docker-compose up to create a local instance and it all fails. 1.10.13, adding cattrs and attrs and upping the version of oauthlib and requests-oauthlib, nothing works, period. What now?

There is a known bug with the latest PiP that was released two days ago. You probably hit the problem described here: https://github.com/pypa/pip/issues/9203

The new version of PIP has MANY problems and broke a lot of other projects. For now the best course of action is to downgrade Pip to 20.2.4 version (this is what we did in official docker images and this is what is recommended in 1.10.14 documentation (release candidate will be there shortly soon).

**Comment by noelmcloughlin** [comment] 2020-12-06 01:08
> The new version of PIP has MANY problems and broke a lot of other projects.

I never use PyPi pip because OS distributions provide stable `python-pip, python2-pip, python3-pip` packages so I use those. This means NEVER running `pip install --upgrade pip`  because that installs PyPi pip ontop distribution python-pip and things breaking horribly when packages get installed in different pip library locations (a  great fustration).  I'd recommend Airflow adopts the same policy.

**Comment by noelmcloughlin** [comment] 2020-12-06 01:30
> when i use pip3 install cattrs==1.0.0.

Beware of cattrs 1.n.n hell with Python 3.9 (i.e. archlinux).
-  https://github.com/Tinche/cattrs/issues/100      
-  https://github.com/aws/aws-cdk/issues/11043 

"ImportError: cannot import name '_Union' from 'typing'"
ImportError: cannot import name 'resolve_types' from 'attr'

**Comment by potiuk** [comment] 2020-12-06 16:38
>  I'd recommend Airflow adopts the same policy because this philosophy works great for me. 

Unfortunately, It is beyond of our control when it comes to our users. We have no physical capacity to force our users to use our preferred installation method. So we better try it ourselves and . We have to assume our users installed latest PIP (which the cannot for now as stated in #12838 which is currently. And in many toolchains where Airflow is installed people build Airflow Images automatically and running the PyPI pip. Including our image which is currently pinned to 20.2.4.

> Beware of cattrs 1.n.n hell with Python 3.9 (i.e. archlinux).

Yep. This is one of the reasons why [Python 3.9 is not officially supported yet by Airflow](https://github.com/apache/airflow/blob/master/README.md#requirements)

**Comment by sephethus** [comment] 2020-12-07 15:42
> > Nothing works in this entire thread, nothing. I'm using docker-compose up to create a local instance and it all fails. 1.10.13, adding cattrs and attrs and upping the version of oauthlib and requests-oauthlib, nothing works, period. What now?
> 
> There is a known bug with the latest PiP that was released two days ago. You probably hit the problem described here: [pypa/pip#9203](https://github.com/pypa/pip/issues/9203)
> 
> The new version of PIP has MANY problems and broke a lot of other projects. For now the best course of action is to downgrade Pip to 20.2.4 version (this is what we did in official docker images and this is what is recommended in 1.10.14 documentation (release candidate will be there shortly soon).

According to my pip3 --version I'm on 20.0.2 so that can't be the issue.

**Comment by jesperbruunhansen** [comment] 2020-12-10 09:08
Unfortunately nothing is the thread works for me :(

I've tried installing Airflow with the command mentioned by @kaxil, but I still get the error.
The error persists in python3.7 as well as python3.8 for me.

Pip: 20.2.4
Python: 3.8.6
OS: MacOS 10.15.6

Error when running `airflow initdb`:
```
ImportError: cannot import name 'resolve_types' from 'attr' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/attr/__init__.py)
```
I've also tried to install the 1.10.13 and 1.10.14rc's, but the error stills persists

**Comment by potiuk** [comment] 2020-12-10 13:44
Are you trying to develop Airflow or run it for "production" on MacOS? We do not support MacOS as "execution" environment" - only Linux systems are supported for 'running' Airflow', MacOS in our case is only supported as development environment. 

It looks like a Mac-only thing, so if you are using MacOS to develop airflow and you can use dockerised development environment  instead, while we manage to pin-point it? (.

On MacOS we also have Breeze that provides a fully-featured docker-based dev environment that works flawlessly with MacOS as well. We fully support it and there is plenty of documentation and movies on how to use Breeze for development purpose including 'start-airflow' command that automatically spins of running airflow scheduler + webserver + command line from your local sources. 

BTW. If you have migrated to BigSur, this might be the root cause of the problem. Usually the "POSIX" development environment has lots of problems with the new releases of MacOS. It usually takes couple of months and few releases of patches + some releases of brew and other dev environments to get it working. Again Breeze is your best bet there as it is "stable" environment. As on as you have Docker and Docker-compose, it will work on MacOS/Linux and even WSL2 for Windows in similar way.
