### ISSUE TITLE
Airflow doesn't show an error when there are DAGs with the same ID

### ISSUE THREAD

**Issue by keu** [apache/airflow#29321] opened 2023-02-02 15:12 UTC
### Apache Airflow version

2.5.1

### What happened

Create two files with DAGs
Both DAGs must have the same ID
Airflow will constantly update DAG structure/code resulting in dozens of weird behaviors and errors:
- wrong DAG visualization
- wrong DAG code
- errors about missing tasks from time to time

### What you think should happen instead

Airflow should show an error to the user and disable both DAGs.

### How to reproduce

1. Create two files with DAGs
2. Both DAGs should have the same ID

### Operating System

Ubuntu 22.04

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by michaelmicheal** [comment] 2023-02-06 03:28
As I understand it, as part of DAG processing, when the scheduler sees new a definition for an existing DAG, it overwrites regardless of the path. While this is by design, my team's stakeholders face this quite a bit where user's have duplicate files, with slightly different versions of a DAG. It's not obvious, and if you rely on a GCS or S3 DAG bucket that is abstracted from users/developers, it can be hard to diagnose.

One solution could be:
If the DAG processor sees an existing DAG defined in a file under a different path, we re-process the file under the old path, and see if the DAG is still defined there. If the DAG is still defined under the old path, we add an import error.


Feel free to assign this to me.

**Comment by eladkal** [comment] 2023-02-06 15:26
@michaelmicheal see https://github.com/apache/airflow/issues/19525#issuecomment-977818865 for more information

Closing as duplicate of https://github.com/apache/airflow/pull/17891 @michaelmicheal if you'd like to work on it please comment on that issue so we can assign you

**Closed as not planned by eladkal** 2023-02-06 15:26 UTC
Labels: kind:bug, area:core
