### ISSUE TITLE
Webserver error: 'NoneType' object has no attribute 'last_loaded'

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#11060] opened 2020-09-21 16:16 UTC
**Apache Airflow version**:

Master branch.

**Environment**:
```
./breeze --python 3.7 --backend postgres --db-reset  restart
```

**What happened**:

Webserver returned this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/airflow/airflow/www/decorators.py", line 126, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/opt/airflow/airflow/www/decorators.py", line 61, in wrapper
    return f(*args, **kwargs)
  File "/opt/airflow/airflow/utils/session.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/www/views.py", line 2119, in refresh
    dag = current_app.dag_bag.get_dag(dag_id)
  File "/opt/airflow/airflow/models/dagbag.py", line 191, in get_dag
    is_expired = (orm_dag.last_expired and dag.last_loaded < orm_dag.last_expired)
AttributeError: 'NoneType' object has no attribute 'last_loaded'
```

**What you expected to happen**:

To see no error but DAG view.

**How to reproduce it**:
```shell
./breeze --python 3.7 --backend postgres --db-reset  restart
# then
export AIRFLOW__CORE__DAGS_FOLDER=airflow/providers/google/cloud/example_dags
airflow scheduler -D
airflow webserver -w 1 -D
```

Create a user, go to webserver, turn on `example_gcp_dataproc` and trigger it.
After few seconds you should see a nuclear cloud under this address: `http://0.0.0.0:28080/refresh?dag_id=example_gcp_dataproc`

**Anything else we need to know**:

N/A

**Comment by turbaszek** [comment] 2020-09-21 16:16
@kaxil or @mik-laj any ideas?

**Comment by kaxil** [comment] 2020-09-21 17:25
hmm - Will take a look after the dev call

**Comment by turbaszek** [comment] 2020-09-21 17:49
> hmm - Will take a look after the dev call

Thanks Kaxil! Let me know if you were able to replicate the issue

**Comment by kaxil** [comment] 2020-09-21 23:55
![image](https://user-images.githubusercontent.com/8811558/93832654-44420180-fc6e-11ea-8542-9db59eb37f3a.png)


I wasn't able to reproduce this issue

**Comment by turbaszek** [comment] 2020-09-22 08:44
@kaxil have ou waited utill the task will be executed? In my case, the error appeared once the task was executed

**Comment by yuqian90** [comment] 2020-09-22 11:23
I did the same steps described, triggered a dagrun and waited till some tasks executed. I could not reproduce the webserver error.

I did get an error in the `create_cluster` TaskInstance log, but that's probably because of my setup:
```
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

**Comment by kaxil** [comment] 2020-09-22 11:45
> @kaxil have ou waited utill the task will be executed? In my case, the error appeared once the task was executed

Same like @yuqian90 my task failed because I didn't have the creds set up but even after the failure I was able to browse across the views.

**Comment by turbaszek** [comment] 2020-09-22 12:02
Hm, interesting I will clean up my environment and will do some tests

**Comment by eladkal** [comment] 2021-04-02 15:14
@turbaszek can we close this issue ?

**Closed as completed** 2021-12-30 00:08 UTC
Labels: kind:bug, Can't Reproduce, area:webserver
