### ISSUE TITLE
SparkKubernetes operator doesn't collect main container logs by default

### ISSUE THREAD

**Issue by eylonronen** [apache/airflow#38535] opened 2024-03-27 14:11 UTC
### Apache Airflow Provider(s)

cncf-kubernetes

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==8.0.0

### Apache Airflow version

2.8.2

### Operating System

-

### Deployment

Official Apache Airflow Helm Chart

### What happened

When looking at the "logs" tab of a task using the SparkKubernetesOperator we get the following line:
"container base whose logs were requested not found in the pod our-pod-name"
The reason for it is that by default KubernetesOperator only collects logs for the BASE_CONTAINER_NAME container, which defaults to "base" in KubernetesOperator, even though the container created in SparkKubernetesOperator is called "spark-kubernetes-driver"

### How to reproduce

Simply use this operator and enter the "logs" tab

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2024-03-31 10:47
Duplicate of https://github.com/apache/airflow/issues/37681

**Closed as not planned by eladkal** 2024-03-31 10:47 UTC
Labels: kind:bug, area:providers, duplicate, needs-triage
