### ISSUE TITLE
Can't view running tasks logs using KubernetesExecutor.

### ISSUE THREAD

**Issue by hsnprsd** [apache/airflow#16001] opened 2021-05-22 21:14 UTC
**Description**

I want to be able to see logs for running tasks in airflow web UI when I'm using "KubernetesExecutor".
Airflow tries to read logs of worker pod which does not contain my task logs because "airflow tasks run" command redirects all stdout/stderr to log file.

Here is what I see when I try to read logs of running tasks:
```
*** Falling back to local log
*** Trying to get logs (last 100 lines) from worker pod datainfraexporterhourlydagwaitforpublishedpostdump.a825336790e24b40ad43b2411ef617c5 ***

BACKEND=postgres
DB_HOST=divar-infra-db-cluster-master-service.skubel-76f219d5-eb73-4f23-96b3-a8cf4ab4f00a
DB_PORT=5432

[[34m2021-05-22 19:00:30,157[0m] {[34mdagbag.py:[0m451} INFO[0m - Filling up the DagBag from /git/airflow/dags/data_infra/exporter/hourly.py[0m
```

**Use case / motivation**

It's not convenient to wait for tasks to finish in order to read their logs.

**Are you willing to submit a PR?**

I can help.

**Related Issues**

I don't think so.

**Comment by andormarkus** [comment] 2021-05-23 09:41
Hi @hsnprsd 
Please can you share your logs configuration?

**Comment by hsnprsd** [comment] 2021-05-23 09:48
Here it is:
AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: s3://airflow-logs
AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: airflow-logs
AIRFLOW__LOGGING__REMOTE_LOGGING: "True"

But it does not matter. I tested it without remote logging and it does not work.

**Comment by hsnprsd** [comment] 2021-05-23 09:50
I came up with a solution today.
I changed the default logging config class like this:

```
import sys
from copy import deepcopy

from airflow.config_templates.airflow_local_settings import DEFAULT_LOGGING_CONFIG

LOGGING_CONFIG = deepcopy(DEFAULT_LOGGING_CONFIG)

LOGGING_CONFIG["handlers"]["custom_console"] = {
    "class": "logging.StreamHandler",
    "formatter": "airflow",
    "stream": sys.__stdout__,
}
LOGGING_CONFIG["loggers"]["airflow.task"]["handlers"].append("custom_console")
```

**Comment by andormarkus** [comment] 2021-05-23 09:54
If you are using remote logging then "Note that logs are only sent to remote storage once a task is complete (including failure); In other words, remote logs for running tasks are unavailable (but local logs are available)." [source](https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/logging-tasks.html)

**Comment by hsnprsd** [comment] 2021-05-23 09:55
@andormarkus I said. It does not work without remote logging either.

**Comment by asimerel** [comment] 2021-05-23 10:25
Hi @andormarkus ,
I have the same problem, it is not about remote logging. Remote logs are available after the task completed as expected.
The logs are not available while the task is running with KubernetesExecutor from UI because UI is looking for pod logs of the kubernetes pod that running "airflow task run" command. But that pod doesn't expose task logs to console. So UI only see Filling up the DagBag log like @hsnprsd attached on the first messeage until the task is completed and logs retrieved from remote.

**Comment by jherrmannNetfonds** [comment] 2021-06-04 12:31
It would be great if there was an option that the task log to stdout (at least for kubernetesExecutor). Writing to stdout on kubernetesExecutor probably would make remote logging obsolete in most cases, since the cloud logging tools on GCP/AWS/Azure collect the logs for kubernetes anyway.
Does anybody now if somebody is working on this? I would help, but not sure where to start here.

**Comment by deas** [comment] 2021-06-04 12:53
I guess we don't want to break expected default behavior.

However, I think we should allow container users to switch to "all logs stdout" when using the `apache/airflow` images leveraging `AIRFLOW__LOGGING__LOGGING_CONFIG_CLASS`.

**Comment by whitleykeith** [comment] 2021-08-24 16:36
I've had this issue for a while now, but I was able to resolve it by adding this to the top of my `dag.py` file.


```python
# Set Task Logger to INFO for better task logs
log = logging.getLogger("airflow.task")
handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.INFO)
log.addHandler(handler)
```

It does pretty much what @hsnprsd had in his class, but doesn't require overriding the default logging config.

**Comment by matteosdocsity** [comment] 2023-04-19 06:44
is there anyone that is using stackdriver as logging? Even if this logs are pulled in streaming I cannot see anything else rather than Airflow built-in logs like:

`[2023-04-19, 06:39:04 UTC] {taskinstance.py:1309} INFO - Executing <Task(TemplatedPythonOperator): hello-task> on 2023-02-15 00:00:00+00:00
[2023-04-19, 06:39:04 UTC] {standard_task_runner.py:55} INFO - Started process 36 to run task
[2023-04-19, 06:40:15 UTC] {local_task_job.py:276} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-04-19, 06:40:15 UTC] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 36. PIDs of all processes in the group: [36]
[2023-04-19, 06:40:15 UTC] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 36
[2023-04-19, 06:40:16 UTC] {process_utils.py:79} INFO - Process psutil.Process(pid=36, status='terminated', exitcode=0, started='06:39:04') (36) terminated with exit code 0`

I do not know how to expose logging.info or print into stackdriver.

**Comment by potiuk** [comment] 2023-04-19 09:37
See DEFAULT_LOGING_CONFIG you have in our configuration https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/logging-tasks.html

**Comment by matteosdocsity** [comment] 2023-04-19 10:44
ok @potiuk thanks for reviewing the Docs, unfortunately it appears obvious that Stackdriver is not working...even in that case the [documentation](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/logging/stackdriver.html) seems not complete, but more a copy and paste of GCS where is written
`Verify that the Google Cloud Storage viewer is working in the UI. With Stackdriver you should see the logs pulled in the real time`

**Comment by potiuk** [comment] 2023-04-19 10:55
Possibly you made some mistake, hard to say. It's likely it needs some more debugging from your side. And if you do find the mistake and woudl see that docs were misleading.

I have a kind request - can you please make a fix to the page once you do find it? 


Airflow is created by almost 2500 people - most of them are people like you who use it completely for free - making use of the voluntary work of those quater of thousnd people who mostly contributed in their free time, often during their nights and weekends.

So if you do find how to configure it properly and see how you can configure the documentation, I have a kind request - please submit a change and clarification to the docs.

It's almost as easy as complaining in an issue here. Click "suggest a change to this Page" button at the bottom of the page and PR will be opened for you, and you will be able to update the docs add clarifications etc. using the very same GitHub UI that you are using now to comment in the issue - no special environment, no dev env setting - just add words clarifing the documentation.

**Comment by potiuk** [comment] 2023-04-19 10:57
So if you do see a mistake in the docs, fixing it and making docs clearer is the simplest thing you can do to say "thank you" for all the hard work 2500 did so that you can make use of the software.

**Comment by matteosdocsity** [comment] 2023-04-19 11:13
Got it and for sure, the problem @potiuk is that Stackdriver seems not working, so really do not how to change the docs. Are there some tests in airflow pipelines that are testing reading/writing logs in Stackdriver?

**Comment by matteosdocsity** [comment] 2023-04-19 12:26
For what concerns the Stackdriver issue I've just reported [here](https://github.com/apache/airflow/issues/30740) the specs on how to reproduce it

**Comment by potiuk** [comment] 2023-04-19 16:18
Sure there are plenty unit tests. I doubt it would not work, otherwise it could have been quite a problem for other people, but let'see maybe someone will pick it up @dstandish - this is the discussion that lead to my PR so maybe indeed there is a problem with stackdriver (see the issue created by the user)

**Comment by dstandish** [comment] 2023-04-19 17:27
hi, should be resolved by https://github.com/apache/airflow/pull/28440 methinks

**Closed as completed** 2023-04-19 17:31 UTC
Labels: area:logging, kind:feature, provider:cncf-kubernetes
