### ISSUE TITLE
Dag with @once schedule interval

### ISSUE THREAD

**Issue by martingrayson** [apache/airflow#921] opened 2016-01-27 12:56 UTC
I have a dag that I dont want to be regularly scheduled by the scheduler - I'll run it manually by firing `trigger_dag` commands.

To do so, I've set my schedule interval to `@once`, however I'm getting an error on the first trigger run.
The logic in the `schedule_dag` sub doesnt seem to work - the scheuler just hits [this](https://github.com/airbnb/airflow/blob/master/airflow/jobs.py#L407) and failed each time  with an index out of range.

To me the logic around line 407 in jobs.py doesnt make sense - this section needs to be moved higher as it will never be run: 

```
elif dag.schedule_interval == '@once' and not last_scheduled_run:
                next_run_date = datetime.now()
```

I am guessing this is because the scheduler hasn't ever triggered the dag without my external trigger. Is there a way around this? Is there a way of specifying a dag should only ever be run via external triggers?

**Comment by mistercrunch** [comment] 2016-01-27 17:26
Can you share the stack trace please.

Sounds like you might want to use `schedule_interval=None`, but we should still get to the bottom of this. We use `@once` at Airbnb, so it may be some sort of edge case around it.

**Comment by r39132** [comment] 2016-02-17 04:27
@martingrayson Can you provide a stack trace as well as the version that you are on (e.g. You can provide a `git log | head` snippet)!

**Comment by r39132** [comment] 2016-02-17 04:47
I just tried to reproduce this. I am running on current master head. I am running Local Executor on my Mac Laptop against a local PostgreSQL DB, everything on UTC.

My Target DAG has a once schedule: 

```
from airflow.operators import *
from airflow.models import DAG
from datetime import date, datetime, time, timedelta

args = {
    'start_date': datetime.now(),
    'owner': 'airflow',
}

dag = DAG(
    dag_id='simple_dummy_once_dag_v1',
    default_args=args,
    schedule_interval='@once')


run_this = DummyOperator(
    task_id='run_this',
    dag=dag)
```

I execute the following command 2 times to create to DAG runs: 

```
sid-as-mbp:dags siddharth$ airflow trigger_dag simple_dummy_once_dag_v1
[2016-02-17 04:36:49,089] {__init__.py:36} INFO - Using executor LocalExecutor
[2016-02-17 04:36:49,666] {cli.py:101} INFO - Created <DagRun simple_dummy_once_dag_v1 @ 2016-02-17 04:36:49.642934: manual__2016-02-17T04:36:49.642934, externally triggered: True>
```

I start with all of my DAGs disabled (which is a config parameter):
<img width="793" alt="screenshot 2016-02-17 04 38 15" src="https://cloud.githubusercontent.com/assets/581734/13099988/475eeab4-d530-11e5-9ae8-debd3e2bca87.png">

Here are the 2 DAG Runs ready to run (in running, but not actually running since the DAG is disabled):
<img width="835" alt="screenshot 2016-02-17 04 43 04" src="https://cloud.githubusercontent.com/assets/581734/13100077/f9d1ace0-d530-11e5-8ade-987d983d068c.png">

I now enable `simple_dummy_once_dag_v1`.
<img width="807" alt="screenshot 2016-02-17 04 44 47" src="https://cloud.githubusercontent.com/assets/581734/13100098/3160b3ae-d531-11e5-8db8-59be985e5e92.png">

And 3 jobs succeed, 1 scheduled (for once) and 2 triggered:
<img width="791" alt="screenshot 2016-02-17 04 45 58" src="https://cloud.githubusercontent.com/assets/581734/13100118/636207cc-d531-11e5-9bbe-b8ab73f76430.png">

**Comment by r39132** [comment] 2016-02-17 04:49
I also triggered this one more time while the DAG was enabled. It all works fine for me. 

<img width="815" alt="screenshot 2016-02-17 04 48 32" src="https://cloud.githubusercontent.com/assets/581734/13100146/b857f4e4-d531-11e5-9f30-a24cf3c6db96.png">

Pending some further details from you, I am closing this. If you are still seeing this, `@` me on gitter.

**Closed as completed by r39132** 2016-02-17 04:49 UTC
Labels: Can't Reproduce
