### ISSUE TITLE
Problem with Microsoft Azure Provider base_azure hook

### ISSUE THREAD

**Issue by shakeelansari63** [apache/airflow#33025] opened 2023-08-02 07:11 UTC
### Apache Airflow version

2.6.3

### What happened

When using AzureBaseHook from airflow/providers/microsoft/azure/hooks/base_azure.py with SDKClient class, the get_conn() method fails to instanciate the Client class object.   
  
The error message says, `missing parameter credential`   
  
This is because the sdk_client is being instanciated with `credentials=ServicePrincipalCredentials`
  
Notice an extra `s` in credentials key which is not needed.

### What you think should happen instead

The sdk_client should be instanciated with `credential=ServicePrincipalCredential` which will be instanciated correctly 

### How to reproduce

1. Install any Azure client, let's say azure-monitor-query
`pip install azure-monitor-query`

2. Use the Azure connection with Azure client
```
from airflow.providers.microsoft.azure.hooks.base_azure import AzureBaseHook
from azure.monitor.query import LogsQueryClient

# Lets say we have an azure connection with name Azure_Default

conn = AzureBaseHook(sdk_client = LogsQueryClient, conn_id = 'Azure_Default')
client = conn.get_conn()
``` 
  
This will fail - 

### Operating System

Any

### Versions of Apache Airflow Providers

apache-airflo-providers-microsoft-azure   v6.2.1

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nathadfield** [comment] 2023-08-02 09:24
@shakeelansari63 This looks like a simple change but I have not been able to replicate this with the code you provided.  Can you review this or do you have an example DAG that can illustrate the problem?

**Comment by shakeelansari63** [comment] 2023-08-02 14:56
Hi @nathadfield ,

Here is example - 
I have created an Azure Connection As Follow - 
![image](https://github.com/apache/airflow/assets/8319053/2676883b-17ea-4a1a-b3d9-ffadf0a75a23)  
  
Note: I haven't added any key_json or key_path in extra. Which means, following piece of code will be ran to instanciate the client - 
![image](https://github.com/apache/airflow/assets/8319053/0087944e-00e2-49d4-ab5e-0aa0bb3ff4ce)  
  
And When I call the get_conn() method, it gives following error - 
![image](https://github.com/apache/airflow/assets/8319053/fe7f3103-ae18-43dc-bd1d-e0a086e96d6e)  
  
And this error is because it need `credentail` not `credentials`.

**Comment by nathadfield** [comment] 2023-08-03 09:11
@shakeelansari63 Having made this change, we are now encountering [test failures](https://github.com/apache/airflow/actions/runs/5740945880/job/15560093916?pr=33040) and so I remain unconvinced that this is indeed a problem.

**Comment by pankajkoti** [comment] 2023-08-03 10:02
I added a comment that could be the cause https://github.com/apache/airflow/pull/33040#issuecomment-1663696347 on the PR

**Comment by shakeelansari63** [comment] 2023-08-03 10:03
@nathadfield , I got the issue here. 
Looks like you are using very old version of azure SDK. 

I looked into one of the failure, for ContainerInstanceManagementClient. 

This is from `provider.yaml`
```
 - azure-mgmt-container-instance>=1.5.0,<2.0
```

This is very old version of azure SDK (from 2019) which is still using `credentials` parameter. But in newer version all azure sdks use `credential` parameter.

**Comment by shakeelansari63** [comment] 2023-08-03 10:05
From what I can see from Pypi, latest version of `azure-mgmt-containerinstance` is `10.1.0`

**Comment by nathadfield** [comment] 2023-08-03 10:12
@shakeelansari63 Yep.  I'll ask around to see what I can find out but it seems like you won't be able to use `LogsQueryClient` until `azure-mgmt-containerinstance` is brought up to date.

**Comment by nathadfield** [comment] 2023-08-03 10:14
#30199

**Comment by eladkal** [comment] 2023-08-03 10:19
I'm closing this issue as the root cause is updating old package as listed in https://github.com/apache/airflow/issues/30199

PRs are welcome.
Azure offers [Airflow as managed service in their eco system](https://techcommunity.microsoft.com/t5/azure-data-factory-blog/introducing-managed-airflow-in-azure-data-factory/ba-p/3730151) try maybe contacting Azure support maybe they will assign an engineer to work on Azure open source issues.

**Closed as completed by eladkal** 2023-08-03 10:19 UTC
Labels: kind:bug, provider:microsoft-azure, area:providers
