### ISSUE TITLE
v3.5.0 airflow.providers.microsoft.azure.operators.cosmos not running

### ISSUE THREAD

**Issue by BenGatewood** [apache/airflow#21412] opened 2022-02-08 05:53 UTC
### Apache Airflow version

2.2.3 (latest released)

### What happened

Submitting this on advice from the community Slack: Attempting to use the v3.5.0 `AzureCosmosInsertDocumentOperator` operator fails with an attribute error: `AttributeError: 'CosmosClient' object has no attribute 'QueryDatabases'`

### What you expected to happen

Expected behaviour is that the document is upserted correctly.  I've traced through the source and `does_database_exist()` seems to call `QueryDatabases()`  on the result of `self.get_conn()`. Thing is `get_conn()` (AFAICT) returns an actual MS/AZ `CosmosClient` which definitely does not have a `QueryDatabases()` method (it's `query_databases()`)

### How to reproduce

From what I can see, any attempt to use this operator on airflow 2.2.3 will fail in this way

### Operating System

Ubuntu 18.04.5 LTS

### Versions of Apache Airflow Providers

azure-batch==12.0.0
azure-common==1.1.28
azure-core==1.22.0
azure-cosmos==4.2.0
azure-datalake-store==0.0.52
azure-identity==1.7.1
azure-keyvault==4.1.0
azure-keyvault-certificates==4.3.0
azure-keyvault-keys==4.4.0
azure-keyvault-secrets==4.3.0
azure-kusto-data==0.0.45
azure-mgmt-containerinstance==1.5.0
azure-mgmt-core==1.3.0
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-resource==20.1.0
azure-nspkg==3.0.2
azure-storage-blob==12.8.1
azure-storage-common==2.1.0
azure-storage-file==2.1.0
msrestazure==0.6.4

### Deployment

Virtualenv installation

### Deployment details

Clean standalone install I am using for evaluating airflow for our environment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2022-02-08 09:28
Assigned yo @BenGatewood - fix is most welcome !

**Comment by potiuk** [comment] 2022-02-08 15:35
Is it serious enough to skip Azure from release and how big of a fix it can be? 
I can hold one or two more days with releasing RC2 for providers (to save time on coordination/release overhead) if this is something that we will likely have a fix in a day or two.

**Comment by josh-fell** [comment] 2022-02-08 16:07
AFAICT This hook has been non-functional for a while. The `AzureCosmosDBHook` code looks to be aligned with [version 3.2 of the azure-cosmos package](https://pypi.org/project/azure-cosmos/3.2.0/) release in July 2020. However, [v4.0](https://pypi.org/project/azure-cosmos/4.0.0/) was already released in May 2020 which renamed these methods. I don't think this needs to be a blocker for RC2 since it's been broken for quite some time already.

**Comment by potiuk** [comment] 2022-02-08 18:23
All right. Thanks for confirming @josh-fell ! . So no harm in releasing it now as it is not a regression. I proceed with RC2 then :)

**Comment by BenGatewood** [comment] 2022-02-09 02:09
OK I've got this working on a monkey-patched local version. Is there a style/form guide for PRs I should follow here?

**Comment by josh-fell** [comment] 2022-02-09 03:20
There is a wonderfully [detailed doc on contributing](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst). It outlines the contribution workflow, PR guidelines, local testing options, `pre-commit` checks you should run before submitting a PR, etc. On Slack you can pose questions in the #airflow-how-to-pr channel as well.

**Closed as completed** 2022-02-23 16:39 UTC
Labels: kind:bug, provider:microsoft-azure, good first issue, area:core
