### ISSUE TITLE
'TrinoHook' object has no attribute 'strip_sql_string'

### ISSUE THREAD

**Issue by hochupivas** [apache/airflow#25742] opened 2022-08-16 14:11 UTC
### Apache Airflow version

Other Airflow 2 version

### What happened

Calling the TrinoOperator/Hook in the latest 4.0.0 version results in the above error for any query.

`File "/opt/airflow/dags/utils/trino.py", line 21, in get_data
    df = engine.get_pandas_df(query)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/trino/hooks/trino.py", line 180, in get_pandas_df
    cursor.execute(self.strip_sql_string(sql), parameters)
AttributeError: 'TrinoHook' object has no attribute 'strip_sql_string'`

### What you think should happen instead

The SQL is executed correctly, no errors in the TrinoHook.

### How to reproduce

Run a query with an instance of the TrinoHook class against a data store

### Operating System

macOS

### Versions of Apache Airflow Providers

4.0.0

### Deployment

MWAA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment] 2022-08-16 14:29
Yep. thanks for raising it. Duplicate of #25740 - you can find workaround is there, in a few days we will release common-sql-provider-1.1.0 that should fix it when installed together and we will release a  bugfix version of all affected providers right after.

**Comment by potiuk** [comment] 2022-08-16 14:29
Closing as duplicate

**Closed as completed by potiuk** 2022-08-16 14:29 UTC
Labels: kind:bug, duplicate, area:core
