### ISSUE TITLE
WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin

### ISSUE THREAD

**Issue by IndrajeetTech2020** [apache/airflow#16155] opened 2021-05-29 05:15 UTC
WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin

Issue with airlow webserver command on airflow 2.1.0

Please help

**Comment by gshiba** [comment] 2021-06-16 07:14
Same issue here.

* I migrated from 2.0.1 from 2.1.0.
* I ran `airflow db upgrade`
* `airflow scheduler` successfully starts (and runs dags)
* `airflow webserver`, however, does not start. 

**Apache Airflow version**: 2.1.0
**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): n/a
**Environment**:
- **Cloud provider or hardware configuration**: Linode server
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS
- **Kernel** (e.g. `uname -a`): Linux localhost 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
* `airflow webserver` does not start the webserver
* instead, it keeps printing error messages (details below)
* error messages are the same as what is described in #10331

**What you expected to happen**: The webserver starts.

**Details**:

Starting it:
```
$ docker run  --rm -it -v ~/airflow:/airflow -v /var/run/docker.sock:/var/run/docker.sock --name airflow_webserver --net network airflow:2.1.0 webserver                                                                                                                                                                                                           
/usr/local/lib/python3.8/site-packages/airflow/configuration.py:346 DeprecationWarning: The hide_sensitive_variable_fields option in [admin] has been moved to the hide_sensitive_var_conn_fields option in [core] - the old setting has been used, but please update your config.                                                                                                             
/usr/local/lib/python3.8/site-packages/airflow/configuration.py:346 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.                                                                                                                                         
/usr/local/lib/python3.8/site-packages/airflow/configuration.py:346 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.                                                                                                                                         
  ____________       _____________                                                                                                                                                                                                                                                                                                                                                             
 ____    |__( )_________  __/__  /________      __                                                                                                                                                                                                                                                                                                                                             
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /                                                                                                                                                                                                                                                                                                                                             
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /                                                                                                                                                                                                                                                                                                                                              
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/                                                                                                                                                                                                                                                                                                                                               
[2021-06-16 06:49:54,151] {dagbag.py:487} INFO - Filling up the DagBag from /dev/null                                                                                                          
[2021-06-16 06:49:54,541] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_create Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:49:54,552] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_edit Admin                                                                                                                                                                                                                                                       
[2021-06-16 06:49:54,563] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_delete Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:49:54,848] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin                                                                                                                                                                                                                                                            
Running the Gunicorn Server with:                                                                                                                                                                                                                                                                                                                                                              
Workers: 4 sync                                                                                                                                                                                                                                                                                                                                                                                
Host: 0.0.0.0:8080                                                                                                                                                                             
Timeout: 120                                                                                                                                                                                   
Logfiles: - -                                                                                                                                                                                  
Access Logformat:                                                                                                                                                                              
=================================================================                                                                                                                                                                                                                                                                                                                              
/usr/local/lib/python3.8/site-packages/airflow/configuration.py:346 DeprecationWarning: The hide_sensitive_variable_fields option in [admin] has been moved to the hide_sensitive_var_conn_fields option in [core] - the old setting has been used, but please update your config.                                                                                                             
[2021-06-16 06:49:58 +0000] [8] [INFO] Starting gunicorn 20.1.0                                                                                                                                                                                                                                                                                                                                
[2021-06-16 06:49:58 +0000] [8] [INFO] Listening at: http://0.0.0.0:8080 (8)                                                                                                                                                                                                                                                                                                                   
[2021-06-16 06:49:58 +0000] [8] [INFO] Using worker: sync                                                                                                                                                                                                                                                                                                                                      
[2021-06-16 06:49:58 +0000] [10] [INFO] Booting worker with pid: 10                                                                                                                            
[2021-06-16 06:49:58 +0000] [11] [INFO] Booting worker with pid: 11                                                                                                                            
[2021-06-16 06:49:58 +0000] [12] [INFO] Booting worker with pid: 12                                                                                                                            
[2021-06-16 06:49:58 +0000] [13] [INFO] Booting worker with pid: 13                                                                                                                            
/usr/local/lib/python3.8/site-packages/airflow/configuration.py:346 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.
/usr/local/lib/python3.8/site-packages/airflow/configuration.py:346 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.                                                                                                                                         
/usr/local/lib/python3.8/site-packages/airflow/configuration.py:346 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.                                                                                                                                         
/usr/local/lib/python3.8/site-packages/airflow/configuration.py:346 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.                                                                                                                                         
[2021-06-16 06:50:09,099] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_create Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:50:09,100] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_create Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:50:09,104] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_create Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:50:09,113] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_create Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:50:09,148] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_edit Admin                                                                                                                                                                                                                                                       
[2021-06-16 06:50:09,149] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_edit Admin                                                                                                                                                                                                                                                       
[2021-06-16 06:50:09,153] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_edit Admin                                                                                                                                                                                                                                                       
[2021-06-16 06:50:09,157] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_edit Admin                                                                                                                                                                                                                                                       
[2021-06-16 06:50:09,194] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_delete Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:50:09,195] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_delete Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:50:09,200] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_delete Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:50:09,205] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_delete Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:50:10,382] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin                                                                                                                                                                                                                                                            
[2021-06-16 06:50:10,383] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin                                                                                                                                                                                                                                                            
[2021-06-16 06:50:10,384] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin                                                                                                                                                                                                                                                            
[2021-06-16 06:50:10,394] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin                                                                                                                                                                                                                                                            
[2021-06-16 06:50:27 +0000] [8] [INFO] Handling signal: ttin                                                                                                                                                                                                                                                                                                                                   
[2021-06-16 06:50:27 +0000] [14] [INFO] Booting worker with pid: 14                                                                                                                                                                                                                                                                                                                            
/usr/local/lib/python3.8/site-packages/airflow/configuration.py:346 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.                                                                                                                                         
[2021-06-16 06:50:31,870] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_create Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:50:31,882] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_edit Admin                                                                                                                                                                                                                                                       
[2021-06-16 06:50:31,893] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_delete Admin                                                                                                                                                                                                                                                     
[2021-06-16 06:50:32,158] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin    
```
Then it goes into an loop of workers getting rebooted:
```
[2021-06-16 06:52:06 +0000] [8] [INFO] Handling signal: ttou
[2021-06-16 06:52:06 +0000] [13] [INFO] Worker exiting (pid: 13)
[2021-06-16 06:52:30 +0000] [8] [INFO] Handling signal: ttin
[2021-06-16 06:52:30 +0000] [18] [INFO] Booting worker with pid: 18
/usr/local/lib/python3.8/site-packages/airflow/configuration.py:346 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.
[2021-06-16 06:52:32,954] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_create Admin
[2021-06-16 06:52:32,970] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_edit Admin
[2021-06-16 06:52:32,980] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_delete Admin
[2021-06-16 06:52:33,231] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin
[2021-06-16 06:52:37 +0000] [8] [INFO] Handling signal: ttou
[2021-06-16 06:52:37 +0000] [14] [INFO] Worker exiting (pid: 14)
[2021-06-16 06:53:00 +0000] [8] [INFO] Handling signal: ttin
[2021-06-16 06:53:00 +0000] [19] [INFO] Booting worker with pid: 19
/usr/local/lib/python3.8/site-packages/airflow/configuration.py:346 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.
[2021-06-16 06:53:03,256] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_create Admin
[2021-06-16 06:53:03,270] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_edit Admin
[2021-06-16 06:53:03,281] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists View Menus.can_delete Admin
[2021-06-16 06:53:03,597] {manager.py:563} WARNING - Refused to delete permission view, assoc with role exists DAG Runs.clear Admin
```
... until it is killed via ctrl-c:

```
^C[2021-06-16 06:53:19 +0000] [8] [INFO] Handling signal: int
[2021-06-16 06:53:19,480] {webserver_command.py:431} INFO - Received signal: 2. Closing gunicorn.
[2021-06-16 06:53:19 +0000] [16] [INFO] Worker exiting (pid: 16)
[2021-06-16 06:53:19 +0000] [17] [INFO] Worker exiting (pid: 17)
[2021-06-16 06:53:19 +0000] [18] [INFO] Worker exiting (pid: 18)
[2021-06-16 06:53:19 +0000] [19] [INFO] Worker exiting (pid: 19)
[2021-06-16 06:53:21 +0000] [8] [INFO] Shutting down: Master
```

During the loop, the endpoint `<ip>:8080` is nonresponsive.

Thanks!

**Comment by eladkal** [comment] 2021-06-22 17:34
It's not a critical message.
duplicate of https://github.com/apache/airflow/issues/10331

**Closed as completed by eladkal** 2021-06-22 17:34 UTC
Labels: kind:bug, duplicate
