### ISSUE TITLE
Logging bug in a long runs

### ISSUE THREAD

**Issue by egS27** [apache/airflow#15990] opened 2021-05-21 14:42 UTC
**Apache Airflow version**:
2.0.2

**Environment**:
 Kubernetes v1.18.3
 Openshift 4.5.37

**What happened**:
We are running our python code in kubernetes operators(airflow.contrib.operators.kubernetes_pod_operator).
During long runs(>10h) the airflow with the logs turned on(`get_logs=True` in k8s operator field) behaves absolutely normally, and then throws an unexpected error.

If we set `get_logs=False`  - we have success dag run, otherwise, we have the same error every time.

Logs:

```
> [2021-05-18 13:54:10,199] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/response.py", line 696, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/response.py", line 436, in _error_catcher
    yield
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/response.py", line 763, in read_chunked
    self._update_chunk_length()
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/response.py", line 700, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 366, in execute
    final_state, _, result = self.create_new_pod_for_operator(labels, launcher)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 513, in create_new_pod_for_operator
    final_state, result = launcher.monitor_pod(pod=self.pod, get_logs=self.get_logs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/cncf/kubernetes/utils/pod_launcher.py", line 145, in monitor_pod
    for line in logs:
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/response.py", line 807, in __iter__
    for chunk in self.stream(decode_content=True):
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/response.py", line 792, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
[2021-05-18 13:54:10,204] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=pipline, task_id=task7, execution_date=20210518T132920, start_date=20210518T133244, end_date=20210518T135410
[2021-05-18 13:54:10,280] {local_task_job.py:146} INFO - Task exited with return code 1
```

We have an airflow instance on other kubernetes server, where we are able to run the same code with the same dags and get no errors.

**Comment by jedcunningham** [comment] 2021-05-21 23:47
@egS27, can you confirm if you have `enable_tcp_keepalive` set to True? If it isn't, can you try it with it enabled?

https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#enable-tcp-keepalive

(Reason I ask is the old default was False, so instances that were updated sometimes still have the old default in airflow.cfg)

**Comment by egS27** [comment] 2021-05-24 06:22
@jedcunningham Thanks for replying, I will provide updates soon.

**Comment by egS27** [comment] 2021-05-24 10:44
@jedcunningham 
`True` is set for `enable_tcp_keepalive`
![image](https://user-images.githubusercontent.com/84581994/119336201-07635a00-bc96-11eb-8e1e-5e901ca3e197.png)

**Comment by MatthewRBruce** [comment] 2021-06-16 14:20
We also see this in a GKE environment when Google performs maintenance on the GKE Master nodes.  It's our understanding that the Master nodes (or a daemon on them) gets restarted for maintenance and the TCP connection gets severed.  

There does seem to be some logic around dealing with interruptions in reading the logs and re-attaching here:
https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/utils/pod_launcher.py#L157-L161
But I think the issue is that there's no `try/except` around the for loop when actually iterating through the lines:
https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/utils/pod_launcher.py#L147-L151

Also FWIW, our error is a Connection Reset by Peer error, not an Incomplete Read error:
```
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by trucnguyenlam** [comment] 2021-07-16 08:56
I can confirm this happens on airflow 2.1.1, eks 1.19, we use s3 as a logging backend

**Comment by potiuk** [comment] 2022-03-28 18:49
it appears this issue was resolved in PR https://github.com/apache/airflow/pull/17649

that PR was released in airflow 2.0.3

**Comment by potiuk** [comment] 2022-03-28 18:50
@trucnguyenlam -> just upgrade to latest cncf.kubernetes provider.

**Closed as completed** 2022-03-28 18:58 UTC
Labels: kind:bug, area:providers, provider:cncf-kubernetes, _eol_affected_version:2.1

**Comment by egS27** [comment] 2022-03-29 02:16
@dstandish was the original issue resolved? In this case, please, provide corresponded note in the changelog. We are still using custom logging.

**Comment by dstandish** [comment] 2022-03-29 03:31
> @dstandish was the original issue resolved? In this case, please, provide corresponded note in the changelog. We are still using custom logging. In another case, please, open the issue again.

Jarek provided the [resolving PR](https://github.com/apache/airflow/pull/17649)  [above](https://github.com/apache/airflow/issues/15990#issuecomment-1081015823). You can open the changelog and search for `17649` to see the changelog note.  It was fixed quite a while ago (in 2.0.3) it seems.

**Comment by potiuk** [comment] 2022-03-29 10:01
> @dstandish was the original issue resolved? In this case, please, provide corresponded note in the changelog. We are still using custom logging. In another case, please, open the issue again

@egS27 - as mentioned above the original report is for 1.10 which is EOL for 10 months already and there is no expectation on any support there, including finding specific commits that fix the problem from the community. However our code and issues are fully open, and you can search for relevant issus fixing the problem. Using EOL version means exactly this - you are on your own and you should expect no support from the community for issues there.

If you need support for - let me remind you the FREE software you have - from people who mostly support users like you in your free time, there are a number of companies that provide paid support for Airflow. You can easilly google them. If your expectation is some kind of SLA (and especially for an EOL version), then your best way to approach is to hire such a company.

If you migrate to a supported version (Airlfow 2 generally is "live" and supported) and find similar issue (it won't be likely the same as Airflow 2 codebase and 1.10 codebase differ quite drastically) - feel free to open one, and there is a chance someone in their free time will help you (but again, if you  expect some SLA, paying for support is a good option).

I just write it so that you have the right expectations set.

Feel free to search for relevant issue. We are not going to open the issue.

**Comment by potiuk** [comment] 2022-03-29 10:08
And just to clarify - the 2.0.2 issue you mentioned has been (likely) fixed in https://github.com/apache/airflow/pull/17649 

We are NOT referring to issues in the changelogs. Our changelogs refer to PRs that solve the problem instead. And those PRs are linked to the issues when they are relevant (like this one is ). So please. Upgrade. Don't expect your particular issue will be refered to in the changelog.

**Comment by potiuk** [comment] 2022-03-29 10:08
Again - just to set the expectations, becasue apparently your expectations were different.

**Comment by egS27** [comment] 2022-03-29 11:42
@dstandish Jarek mentioned that this pr was for resolving not the original issue. (**different** story which appears this issue was resolved in PR 17649).  This is why I am asking about the original issue, in particular, maybe don't get the idea correctly...
@potiuk I got your point. Yes, we identified a bug in the stale version, but we use a fresh one and don't miss updates. If the bug was identified, I think we can expect that it was fixed in the next versions, and I am asking about a mention of that fix. I am not expecting any support for 1.10. I am asking about the note in the changelog(with pr attached), with which I can go and make sure that issue was fixed.
Also, I cannot find this pr in the airflow changelog.
![image](https://user-images.githubusercontent.com/84581994/160602613-4cbbf582-a922-4820-95b0-bf7c1456df51.png)

**Comment by potiuk** [comment] 2022-03-29 12:05
@sg27  Because you are looking in a wrong place. This is a kubernetes provider fix, not airflow. https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/index.html

**Comment by potiuk** [comment] 2022-03-29 12:14
And I heartily recommend "search" on Airlfow docs site. It really fast and really good:

![image](https://user-images.githubusercontent.com/595491/160608893-62ab9b9b-2207-4dc5-9bed-27835b5bbe6a.png)
