### ISSUE TITLE
Catchup still occurs for the current day  even though catchup is set to false.

### ISSUE THREAD

**Issue by pedro-cf** [apache/airflow#31937] opened 2023-06-15 14:09 UTC
### Apache Airflow version

2.6.1

### What happened

When catchup is set to False in an Airflow DAG, catchup should be disabled, meaning the scheduler should not attempt to schedule and execute past task instances. However, catchup is still occurring for the current day, leading to unexpected task executions.

### What you think should happen instead

When catchup is set to False, the scheduler should completely disable catchup functionality, ensuring that no past task instances are scheduled and executed, even for the current day. The DAG should only execute tasks going forward from the moment catchup is set to `False.

### How to reproduce

1. Create a test DAG.
2. Configure the catchup parameter of the DAG to False.
3. Set the start_date of the DAG to the current date and the schedule_interval to @daily.
4. Enable the DAG.
5. Observe that a task is executed immediately, despite catchup being set to False.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Docker-Compose

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by ephraimbuddy** [comment] 2023-06-15 15:37
Your start_date should be a date in the past without that, you might be having issues with your @daily schedule. Let me know if this fixed your issue

**Comment by pedro-cf** [comment] 2023-06-15 15:39
> Your start_date should be a date in the past without that, you might be having issues with your @daily schedule. Let me know if this fixed your issue

I mentioned to set start_date as the current date, but it can be set to a past date and the bug still happens.

**Comment by ephraimbuddy** [comment] 2023-06-15 16:04
> > Your start_date should be a date in the past without that, you might be having issues with your @daily schedule. Let me know if this fixed your issue
> 
> I mentioned to set start_date as the current date, but it can be set to a past date and the bug still happens.

It will execute for that day. This is not wrong. The next day will now be at 00:00 but maybe @uranusjr will have more explanations

**Comment by pedro-cf** [comment] 2023-06-15 16:25
> @daily

because it's "@daily" it interprets it as still not having run it today so it runs ? so a solution could be setting the scheudle to a cron ? 0 0 * * *

**Comment by pedro-cf** [comment] 2023-06-19 13:18
I think I speak for a lot of people from my experience and colleagues that when I set catchup to false and set a schedule of f.e. ``0 4 * * *`` and enable my DAG I intended for it to run on the next day at 4 AM not as soon as I enable it.

**Comment by potiuk** [comment] 2023-06-19 13:43
> I think I speak for a lot of people from my experience and colleagues that when I set catchup to false and set a schedule of f.e. `0 4 * * *` and enable my DAG I intended for it to run on the next day at 4 AM not as soon as I enable it.

Why not set start_date in the future, when you want to start it ? That's non-ambiguous, and very clearly describes your intention. Basing when the first run should run the fact when you "enable" it in the UI seems lika spreading the schedule definition not only between two places (DAG + UI) but also making it dependent on when one of the users (without really tracking it) perform certain action. 

It's enough "variability" to have 'catchup=False` to decide based on the user actions.

My feeling is that maybe we shoud just communnicate it better that schedule + start_date is the way how your schedule definition looks like.  I think just explaining that "if you want to control start_date of your DAG, it should be in the dag definition".  Just detecting if the DAG has no start_date / start_date in the past and catchup=false, the "Enable" button should have an information that it will start running immediately, unless you specify start_date in the future that limits it.

**Comment by nathadfield** [comment] 2023-06-29 14:19
How `start_date` functions is explained [here](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dag-run.html#data-interval).

**Comment by nathadfield** [comment] 2023-06-29 14:20
Closing as this is working as designed.  This is explained in more detail [here](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dag-run.html#data-interval).

**Closed as completed by nathadfield** 2023-06-29 14:19 UTC
Labels: kind:bug, area:core, needs-triage

**Comment by contentfree** [comment] 2024-05-01 00:49
This behavior, while possibly working "as designed", is certainly a violation of the Principle of Least Surprise. If I have a DAG that I disabled some time ago and it has a schedule for once a day and I have catchup = false, I'm _very_ surprised when I enable it after the scheduled time (in preparation for the next day) and it immediately runs.
