### ISSUE TITLE
Add api call for changing task instance status

### ISSUE THREAD

**Issue by josephine093** [apache/airflow#23246] opened 2022-04-26 09:17 UTC
### Description

In the UI you can change the status of a task instance, but there is no API call available for the same feature.

It would be nice to have an api call for this as well. 

### Use case/motivation

I found a solution on stack-overflow on [How to add manual tasks in an Apache Airflow Dag]. There is a suggestion to set a task on failed and change it manually to succeed when the task is done.

Our project has many manual tasks. This suggestions seems like a good option, but there is no api call yet to call instead of change all status manually. I would like to use an api call for this instead. 

You can change the status of on a dag run so it also seems natural to have something similar for task instances. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment] 2022-04-26 10:20
There is `/api/v1/dags/{dag_id}/updateTaskInstancesState`.

Sample payload : https://github.com/apache/airflow/blob/2bb1cd2fec4e2069cb4bbb42d1a880e905d9468e/tests/api_connexion/endpoints/test_task_instance_endpoint.py#L1205-L1214

**Comment by ashb** [comment] 2022-04-26 10:27
There should probably also be a `POST` to update a single TI just for consistency sake too.

**Comment by tirkarthi** [comment] 2022-04-26 10:42
Agreed, there is also https://github.com/apache/airflow/issues/23227 to clear a given task under a DAG run which seems little similar to this request if my understanding is correct.

**Comment by erdos2n** [comment] 2022-04-26 16:15
@ashb @tirkarthi is it possible to get assigned this issue? I would love to take it if possible.

**Comment by ephraimbuddy** [comment] 2022-04-28 10:55
> > There should probably also be a `POST` to update a single TI just for consistency sake too.
> 
> I think updating a single TI is possible in the current endpoint. Setting these:
> 
> ```python
>     "include_upstream": False, 
>      "include_downstream": False, 
>      "include_future": False, 
>      "include_past": False, 
> ```
> 
> False in the payload will have it update only the particular task instance

Problem with this is the date range that it clears. Yeah, will be good to be more specific

**Comment by ashb** [comment] 2022-04-28 16:22
From a RESTy point of view I like and end point where the task id is in the URL :)

**Comment by erdos2n** [comment] 2022-05-13 18:18
@ephraimbuddy @ashb about to write some test cases. Should this be a `PATCH` request since this updates a task instance state as opposed to `POST` which is typically used to create the task instance?

**Comment by uranusjr** [comment] 2022-05-14 16:59
PATCH sounds like a reasonable choice to me.

**Comment by erdos2n** [comment] 2022-06-19 13:56
I have written the methods needed, but for some reason my tests are failing when I run them locally. Curious if it's something in the `v1.yaml` file. Can someone possibly help me out with this sometime?

**Comment by potiuk** [comment] 2022-06-19 23:11
Runing stuff in `breeze` (after updating the image)  is the best way to test stuff in a reproducible environment that is the same on CI as locally and one that you can make sure hsa all the same dependencies - this is an often reason of the "works for me" syndrome when running tests. I recommend running tests for breeze (not sure though if that's exactly the case of yours).

**Comment by erdos2n** [comment] 2022-07-21 18:18
unnassigning myself, as I am unable to get the tests to pass

**Comment by cedkoffeto** [comment] 2022-08-18 22:16
Hi everyone, I am new in the airflow community and want to help and learn.
Am interested in this issue so @erdos2n  can we assign it to me, please?

**Comment by cedkoffeto** [comment] 2022-08-18 22:38
Do you think we should add an API call like this?  /taskInstances/{task_instance_id}/update just to be focused on the DagRun itself.

**Comment by potiuk** [comment] 2022-08-26 21:51
I think it's best to add draft PR with proposal and discuss it there.

**Comment by cedkoffeto** [comment] 2022-08-28 14:43
Sure, Thank you for your feedback

**Closed as completed** 2022-10-31 05:31 UTC
Labels: kind:feature, area:API
