### ISSUE TITLE
container_client.create_container() fails when using Container level SAS token (but fine with Storage level SAS token)

### ISSUE THREAD

**Issue by zockette** [apache/airflow#19409] opened 2021-11-04 19:05 UTC
### Apache Airflow Provider(s)

microsoft-azure

### Versions of Apache Airflow Providers

apache-airflow-providers-microsoft-azure 3.2.0
apache-airflow-providers-microsoft-azure 3.3.0rc1

### Apache Airflow version

2.1.2

### Operating System

Red Hat Enterprise Linux Server release 7.9 (Maipo)

### Deployment

Virtualenv installation

### Deployment details

Using Azure Blob Storage connection (wasb.py) hook with SAS Token.
azure-storage-blob==12.8.1

### What happened

While trying to upload a file to blob storage via airflow.providers.microsoft.azure.transfers.local_to_wasb.LocalFilesystemToWasbOperator with a SAS Token, the task always fails on "container_client.create_container()" in the wrong way.

The underlying azure/storage/blob/_container_client.py create_container doesn't return a "ResourceExistsError" but a generic "azure.core.exceptions.HttpResponseError: The requested URI does not represent any resource on the server." instead.

### What you expected to happen

The setup of "try to create, if it fails with a specific error it's ok, otherwise, go kaboom" should probably handle more error types.

Given what I've seen with blob management with SAS token in my Azure adventures, I suspect the setup doesn't handle the container name being already part of the SAS token path.

### How to reproduce

Get yourself an Azure Blob Storage Container with a **Container-level** SAS Token (**not** a Storage-level SAS Token). 
Setup an Azure Blob Storage connection in Airflow.
=> Make sure you input the SAS Token in both the "Extra" field's extra__wasb__sas_token key and in the "SAS Token (optional)" field. Otherwise you're going to have a bad time (and if you're using 3.2.0 you'll have to patch the code, works out of the box with 3.3.0rc1).
Run an operator like this: LocalFilesystemToWasbOperator(dag=dag,task_id='upload_to_blob_storage', file_path='/tmp/lalala.txt', container_name="this_actually_acts_as_a_path_within_the_blob_and_not_as_a_container_its_MAGIC",blob_name='hihi.txt', wasb_conn_id='name_of_connection')

Or via the azure-cli:

> from azure.storage.blob import BlobServiceClient
> sas_url = "https://xxx.blob.core.windows.net/mycontainername?sp=racwdlme&st=2021-10-15T11:34:50Z&se=2021-12-31T20:34:50Z&spr=https&sv=2020-08-04&sr=c&sig=xhfhfhtfjftjftjftj"
> blob_client=BlobServiceClient(account_url=sas_url)
> container_client = blob_client.get_container_client('mycontainername')
> container_client.create_container()

### Anything else

Given what I've seen with blob management with SAS token in my Azure adventures, I suspect the setup doesn't handle the container name being already part of the **Container-level** SAS token path.

But I couldn't say whether the Azure Python SDK is to blame or if it should be handled in the Airflow provider :(

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment] 2021-11-06 07:45
I'm not really sure if this is Airflow problem or the azure python sdk.
Could you show a minimal working code example with the SDK?

**Comment by josh-fell** [comment] 2021-11-07 03:33
Hmm I wasn't sure off the top of my head but I dug into to the SDK a little. From what I can gather, if `ContainerClient. create_container()` [fails to create a container](https://github.com/Azure/azure-sdk-for-python/blob/73d0b36cf9c5ded2c5a642a48e9cf879f06455b5/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L291-L299) (assuming metadata retrieval is OK) the original exception set is  `HttpResponseError`. Then there is a [method](https://github.com/Azure/azure-sdk-for-python/blob/73d0b36cf9c5ded2c5a642a48e9cf879f06455b5/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py#L86) which looks at the error response and tries to raise a more specific error based on the response headers. There is a long set of errors that are checked but if the error code pulled from the headers doesn't match this exhaustive, the `HttpResponseError` is used when raising the exception.

With that said though, I'm unable to reproduce the issue with the steps outlined with version 3.2.0 and 3.3.0 of the Azure provider. @zockette Are there other details you could add to help reproduce the error?

**Connection**
![image](https://user-images.githubusercontent.com/48934154/140631284-d46a5a3c-f82f-456e-8422-b0e05e08684b.png)

**DAG**
```python
from datetime import datetime

from airflow.decorators import dag
from airflow.providers.microsoft.azure.transfers.local_to_wasb import LocalFilesystemToWasbOperator

from datetime import datetime

from airflow.decorators import dag
from airflow.providers.microsoft.azure.transfers.local_to_wasb import LocalFilesystemToWasbOperator


@dag(
    dag_id="example_local_to_wasb",
    schedule_interval="@once",
    start_date=datetime(2021, 1, 1),
    catchup=False,
    default_args={"container_name": "mycontainer", "blob_name": "myblob"},
)
def local_to_wasb():
    upload = LocalFilesystemToWasbOperator(
        task_id="upload_file",
        container_name="mycontainer",
        blob_name="myblob",
        file_path="include/example-text.txt",
        load_options={"overwrite": True},
    )


dag = local_to_wasb()
```

**DAG Run Log**
![image](https://user-images.githubusercontent.com/48934154/140631362-88b3b09c-fa13-44a2-8fe6-4d760d3225ae.png)

**Comment by zockette** [comment] 2021-11-07 17:32
Well I can say that create_container error is the same via the CLI:

![image](https://user-images.githubusercontent.com/58522841/140654255-beb06d1c-066d-47f1-9c8a-8b4e1e301108.png)

Uploading works just fine:
![image](https://user-images.githubusercontent.com/58522841/140654387-3f513a10-bb81-45a1-a8ea-5db0c44ed41a.png)

Your SAS token has been generated at Storage level, not at Container leveln yes?  I'm pretty sure because Storage level tokens start with ?sv while Container level tokens start with ?sp.

After further digging I can fairly confidently say that BlobServiceClient doesn't behave the same if it's a Container SAS token and it only works "as intended" with a Container SAS token.

Works fine with Storage level token:
![image](https://user-images.githubusercontent.com/58522841/140655083-8e07ac93-5e49-4953-8ca6-c07cc6e48977.png)

So now the question I guess is: should and will the microsoft-azure provider handle the error that comes when trying to run create_container with a Container level SAS token? 

Handling could be done by either confirming the behaviour with the guys managing the BlobServiceClient code and adding it to the error mappings, by having a flag at operator level to bypass the container existence check/container creation attempt bit or by documenting that Container level SAS token are not supported (pls no D:).

Also one extra bit of weirdness: using a Container level SAS token will make the "container" parameter of the operator act as a path on the container. Not sure if intended :-)

**Comment by zockette** [comment] 2021-11-07 17:40
For reference, a Storage level SAS token would come from:
![image](https://user-images.githubusercontent.com/58522841/140655544-c98ed7e0-5865-4382-bbf9-86c5e2adda45.png)

A Container level SAS token is made via the Container UI:
![image](https://user-images.githubusercontent.com/58522841/140655604-8af0fbe1-db7b-46e5-9a8c-ff99000451c7.png)

Hope you like my mspaint skills 😎

**Comment by josh-fell** [comment] 2021-11-08 16:12
@zockette Thanks for the additional context about the container-level SAS token. This was the reason for my asking for other details; I didn't want to ask a leading question. Would you mind updating the issue title and the steps to reproduce please for future readers of the issue? That valuable context is missing upfront.

I'm still unclear if this is an Airflow "issue" or more of a feature request to handle container-level SAS tokens.

@eladkal Should we add some context to the operator (or maybe even the `WasbHook`/Connection) doc that container-level SAS tokens aren't supported in the interim?

**Comment by zockette** [comment] 2021-11-09 10:48
If someone faces the issue meanwhile (microsoft-azure 3.2.0 to 3.3.0rc1 at the time of writing), this can be patched by commenting out "container_client.create_container()" @ line 365 of YOUR_PYTHON_VENV_DIR_HERE/lib/python3SOMEVERSIONNUMBER/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py.

You'll lose the auto-creation of containers when they don't exist however.

**Comment by eladkal** [comment] 2021-12-01 06:43
> @eladkal Should we add some context to the operator (or maybe even the `WasbHook`/Connection) doc that container-level SAS tokens aren't supported in the interim?

Do you think this is something that we should address by documentation or is there a code changes needed that can solve the problem from the root?

**Comment by josh-fell** [comment] 2021-12-03 00:58
I was thinking we should add a disclaimer in the docs as an explicit "heads up" for others so there is no confusion until a possible fix is implemented. 

But if you could be so kind as to assign this to me that would be lovely.

If you agree on the disclaimer, I can whip that up in the interim.

**Comment by josh-fell** [comment] 2021-12-04 05:58
When I test this using `main` specifically with a container-level SAS token with all available perms on said container, the following exception is thrown:
```
[2021-12-03, 23:17:34 EST] {taskinstance.py:1698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_container_client.py", line 298, in create_container
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 134, in create
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'This request is not authorized to perform this operation.'
```

_Digging, part 1_
Currently when attempting to upload a blob, we are attempting to first create a container, if it already exists, simply return the `ContainerClient` to continue the upload. However, only a `ResourceExistsError` is caught during the creation step which leads to task failure.

_Digging, part 2_
Looking at the [documentation for service SAS perms](https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#permissions-for-a-directory-container-or-blob) re: containers/blobs:
>A service SAS cannot grant access to certain operations:
>
> - Containers, queues, and tables cannot be created, deleted, or listed.
> - Container metadata and properties cannot be read or written.
> ...
> - Containers cannot be leased.
>
>To construct a SAS that grants access to these operations, use an account SAS. 

Reading container properties is part of creating containers which again leads to the above exception.

There is also a discussion [here](https://github.com/Azure/azure-sdk-for-python/issues/18012) about this too.

_Possible next steps_
1. We can continue to inherently disallow the use of container-level SAS to upload blobs without updating any logic in the provider and document this constraint. This of course assumes that the behavior to _always_ attempt creating a container is desired.
2. Simply catch a `HttpResponseError` exception when attempting to perform the container creation. Again, keeping the assumption that container creation attempts are desired here.
3. Refactor the blob `upload` mechanism in the provider to make the container creation configurable. 

P.S. Generally speaking the `WasbHook` methods seem to favor using a `ContainerClient` to perform blob-level operations even though this hook specifically interacts with Azure Blob Storage using a `BlobServiceClient` which can directly perform these operations. Presumably this exists because of the "auto-container creation" behavior. IMO this behavior seems worth of revisiting.

**Comment by josh-fell** [comment] 2021-12-17 16:44
@eladkal Can you assign this to me? I'm going to whip something up.

**Comment by zockette** [comment] 2022-02-20 12:09
Workaround for apache-airflow-providers-microsoft-azure-3.6.0: 
this can still be patched by commenting out "container_client.create_container()" @ line 323 (moved from line 365 since 3.3.0rc1) of YOUR_PYTHON_VENV_DIR_HERE/lib/python3SOMEVERSIONNUMBER/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py.

**Closed as completed** 2022-03-02 19:38 UTC
Labels: kind:bug, provider:microsoft-azure, area:providers, good first issue
