### ISSUE TITLE
S3ToSnowflakeOperator generating copy statement that fails

### ISSUE THREAD

**Issue by JavierLopezT** [apache/airflow#10925] opened 2020-09-14 09:29 UTC
**Apache Airflow version**:
1.10.10

**Environment**:
Docker-compose

**What happened**:
I used S3ToSwnoflakeTransfer and it gave me the following copy statement:
```
COPY INTO ods.stg_users 
FROM @s3_airflow_ods/
files=airflow/sta_tables/import_users/users_20200911T112003de.csv
file_format=REDSHIFT_UNLOAD_FILE_FORMAT;
```
Which throws several errors. First, it says this:
`SQL compilation error: syntax error line 3 at position 13 unexpected '/'. syntax error line 3 at position 13 unexpected '/'. syntax error line 3 at position 24 unexpected '/'. syntax error line 3 at position 37 unexpected '/'. syntax error line 3 at position 61 unexpected '.'. syntax error line 4 at position 0 unexpected 'file_format'.`
If it would have worked, then an error of file_format would have arisen, because I have got to specify both data warehouse and schema. 
Furthermore, once the problem with file_format is solved, it shows an error of `Cannot perform operation. This session does not have a current schema`

**What you expected to happen**:
The copy statement that works for me has been:
```
COPY INTO ods.stg_users 
FROM @s3_airflow_ods/airflow/sta_tables/import_users/users_20200911T122850de.csv
file_format=dwh.dw.REDSHIFT_UNLOAD_FILE_FORMAT;
```
So for me, the copy statement has had to be changed from:
```
COPY INTO {schema}.{table}
FROM @{stage}/
files={s3_keys}
file_format={file_format}
```
to
```
USE SCHEMA {schema};
COPY INTO {schema}.{table}
FROM @{stage}/{s3_keys}
file_format={database}.{file_format_schema}.{file_format}
```
**How to reproduce**
Using a file_format that is in a different schema that the table to copy into.

@feluelle Could you take a look at this, please? As soon as you (or someone else) confirm this needs(or can) to be changed, I will start working on it

**Comment by feluelle** [comment] 2020-09-23 07:44
I think the syntax you are using is incorrect.

From the [snowflake docs](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#reloading-files) it should be:
```
COPY INTO load1 FROM @%load1/data1/
    FILES=('test1.csv', 'test2.csv')
```

So in your case it should be:
```
COPY INTO ods.stg_users 
FROM @s3_airflow_ods/
files=('airflow/sta_tables/import_users/users_20200911T112003de.csv')
file_format=REDSHIFT_UNLOAD_FILE_FORMAT;
```

**Comment by eladkal** [comment] 2020-11-03 12:30
@JavierLopezT can you confirm the issue is resolved?

**Comment by JavierLopezT** [comment] 2020-11-03 17:56
> @JavierLopezT can you confirm the issue is resolved?

Probably feluelle is right, but I didn't have the chance to look into it. Sorry. I'll do ASAP

**Comment by eladkal** [comment] 2020-11-15 12:45
@JavierLopezT I'm closing this issue for now. If needed please comment with your findings and we will reopen this.

**Closed as completed by eladkal** 2020-11-15 12:45 UTC
Labels: kind:bug, Can't Reproduce
